### PR TITLE
Vendor in CDI 1.3.0

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
The PR updates the version of CDI that is being vendored in. It also updates the testing manifest template to use the latest version so upload is now available.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
Whoops always forget that part. Give me sec and I will update.

**Comment by rmohr** [comment]
ci test please

**Comment by rmohr** [comment]
ci test please

**Comment by rmohr** [comment]
ci test please

**Comment by rmohr** [comment]
ci test please

**Pull request merged**
