### PR TITLE
Add virt-handler flag for kubelet pod path

### LINKED ISSUE #3426: virt-handler pod directory is hard-coded, no support for custom kubelet root
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

Pods were stuck in 'Terminating' state. Through debugging it was determined that virt-handler was not detecting that the ContainerDisk was mounted, skipping unmount, and letting the pod hang forever.

The root cause of this is that kubelet had it's --root-dir set to an unexpected path, and kubevirt's configuration didn't match. This is important because virt-handler looks at mountinfo from the host's perspective and needs its local mounts to match paths that the host also has.

The first step of working around this was to set virt-handler's "kubelet-pods" volume mount to match the Kubelet's view of the world. This allowed virt-handler to see the ContainerDisk in the mountinfo, and allowed it to unmount and let the pod terminate cleanly.

However, there is another place where the code has hardcoded its view of pod path to "/var/lib/kubelet/pods" - https://github.com/kubevirt/kubevirt/blob/7137c788e5403f1f6c6742dac8ce16e127e399b4/pkg/container-disk/container-disk.go#L41

_*We need to make this configurable.*_

**What you expected to happen**:
Expect to be able to use kubevirt with a custom kubelet --root-dir configuration.

**How to reproduce it (as minimally and precisely as possible)**:

Set up a kubelet with an alternate --root-dir, something not "/var/lib/kubelet"

### PR DESCRIPTION
**Pull request by mlsorensen**
**What this PR does / why we need it**: 
If Kubelet is not using a standard --root-dir, virt-handler
won't detect containerdisks properly. This moves from a
hard-coded "/var/lib/kubelet/pods" path to a configurable
one so virt-handler's paths can match the Kubelet's view.

Signed-off-by: Marcus Sorensen <marcus_sorensen@apple.com>

**Which issue(s) this PR fixes** :
Fixes #3426

**Special notes for your reviewer**: There's a separate issue (edit: #3365) for exposing configurables like these through the operator, via merging JSON docs. I don't suspect this will be usable for most until this happens, unless they edit the daemonset after deployment.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mlsorensen** [comment]
> with the operator, how would this flag be set? do we need something like this #3402 for the handler so we can establish custom args on the kubevirt cr

Yes, possibly. I was actually referring to #3365 in the reviewer note...

**Comment by mlsorensen** [comment]
> I'm not sure this change will work as expected.
> 
> When virt-operator creates the virt-handler daemonset, we are passing in the host pods directory as a hostPath volume. below is some code from `pkg/virt-operator/creation/components/deployments.go`
> 
> ```
>         volumes := []volume{                                                                                                   
>                 {"libvirt-runtimes", "/var/run/kubevirt-libvirt-runtimes", "/var/run/kubevirt-libvirt-runtimes", nil},         
>                 {"virt-share-dir", "/var/run/kubevirt", "/var/run/kubevirt", &bidi},                                           
>                 {"virt-lib-dir", "/var/lib/kubevirt", "/var/lib/kubevirt", nil},
>                 {"virt-private-dir", "/var/run/kubevirt-private", "/var/run/kubevirt-private", nil},                           
>                 {"device-plugin", "/var/lib/kubelet/device-plugins", "/var/lib/kubelet/device-plugins", nil},                  
>                 {"kubelet-pods-shortened", "/var/lib/kubelet/pods", "/pods", nil},                                             
>                 {"kubelet-pods", "/var/lib/kubelet/pods", "/var/lib/kubelet/pods", &bidi},                                     
>                 {"node-labeller", "/var/lib/kubevirt-node-labeller", "/var/lib/kubevirt-node-labeller", nil},                  
>         }
> ```
> 
> So, if the host's directory is different than `/var/lib/kubelet/pods`, I think what we actually want to do is update these hostPath volumes. The host can have a path other than the default, but that path will always be mapped internally in virt-handler as `/var/lib/kubelet/pods`
> 
> Here's an example
> 
> ```
>                 {"kubelet-pods-shortened", "/some/custom/pod/path", "/pods", nil},                                             
>                 {"kubelet-pods", "/some/custom/pod/path", "/var/lib/kubelet/pods", &bidi},       
> ```
> 
> That would map the host's `/some/custom/pod/path` to our default paths in virt-hander. Then everything should just work.
> 
> Does this make sense?



> I'm not sure this change will work as expected.
> 
> When virt-operator creates the virt-handler daemonset, we are passing in the host pods directory as a hostPath volume. below is some code from `pkg/virt-operator/creation/components/deployments.go`
> 
> ```
>         volumes := []volume{                                                                                                   
>                 {"libvirt-runtimes", "/var/run/kubevirt-libvirt-runtimes", "/var/run/kubevirt-libvirt-runtimes", nil},         
>                 {"virt-share-dir", "/var/run/kubevirt", "/var/run/kubevirt", &bidi},                                           
>                 {"virt-lib-dir", "/var/lib/kubevirt", "/var/lib/kubevirt", nil},
>                 {"virt-private-dir", "/var/run/kubevirt-private", "/var/run/kubevirt-private", nil},                           
>                 {"device-plugin", "/var/lib/kubelet/device-plugins", "/var/lib/kubelet/device-plugins", nil},                  
>                 {"kubelet-pods-shortened", "/var/lib/kubelet/pods", "/pods", nil},                                             
>                 {"kubelet-pods", "/var/lib/kubelet/pods", "/var/lib/kubelet/pods", &bidi},                                     
>                 {"node-labeller", "/var/lib/kubevirt-node-labeller", "/var/lib/kubevirt-node-labeller", nil},                  
>         }
> ```
> 
> So, if the host's directory is different than `/var/lib/kubelet/pods`, I think what we actually want to do is update these hostPath volumes. The host can have a path other than the default, but that path will always be mapped internally in virt-handler as `/var/lib/kubelet/pods`
> 
> Here's an example
> 
> ```
>                 {"kubelet-pods-shortened", "/some/custom/pod/path", "/pods", nil},                                             
>                 {"kubelet-pods", "/some/custom/pod/path", "/var/lib/kubelet/pods", &bidi},       
> ```
> 
> That would map the host's `/some/custom/pod/path` to our default paths in virt-hander. Then everything should just work.
> 
> Does this make sense?

That makes total sense, and is in fact what we are doing, since we have abandoned trying to use virt-operator. The issue is that it's easy to adjust the hostPath part, no patches necessary, but the config this PR fixes is currently hard-coded.

I apologize for not being clear - fixing the hostPath is enough to fix the volume unmount part, however a second problem then rears its head here:

https://github.com/kubevirt/kubevirt/blob/b058e41e05a94e576fb0c0db1b727011292eb450/pkg/container-disk/container-disk.go#L71

That will quickly fill up your logs.  So in order to put to rest the entire configuration issue of using an alternate Kubelet root, both configurations are required. This PR just fixes the part that isn't already configurable.

I fully understand that a follow up would need to be done to expose this configurability through the virt-operator, whether it be a part of the existing idea to generally allow customization, or a special flag, or something else.

**Comment by davidvossel** [comment]
So because we're doing this.

`
out, err := exec.Command("/usr/bin/chroot", "--mount", "/proc/1/ns/mnt", "mount", "-o", "ro,bind", strings.TrimPrefix(sourceFile, nodeRes.MountRoot()), targetFile).CombinedOutput()
                                if err != nil {
                                        return fmt.Errorf("failed to bindmount containerDisk %v: %v : %v", volume.Name, string(out), err)
                                }
`

we're executing this mount command in the host mount namespace, which potentially has a different path for the pods directory than what we have mapped in virt-handler. 

I see how your pr fixes this now.

**Comment by davidvossel** [comment]
>  since we have abandoned trying to use virt-operator.

@mlsorensen that's unfortunate. I think I missed that conversation.

If we made the cert rotation logic optional, and placed it in a new component instead of the operator, it's possible we could consider supporting the old manifests install method. I'm doubtful that the manifests only approach is something we'd advertise as a release asset, but it's something that would be pretty easy to make virt-operator dump to a file for advanced use cases.

Maybe you're already aware of this function `func dumpInstallStrategyToBytes(strategy *InstallStrategy) []byte`.  That essentially creates the equivalent of a yaml manifest for install.

**Comment by mlsorensen** [comment]
> > since we have abandoned trying to use virt-operator.
> 
> @mlsorensen that's unfortunate. I think I missed that conversation.
> 
> If we made the cert rotation logic optional, and placed it in a new component instead of the operator, it's possible we could consider supporting the old manifests install method. I'm doubtful that the manifests only approach is something we'd advertise as a release asset, but it's something that would be pretty easy to make virt-operator dump to a file for advanced use cases.
> 
> Maybe you're already aware of this function `func dumpInstallStrategyToBytes(strategy *InstallStrategy) []byte`. That essentially creates the equivalent of a yaml manifest for install.

Perhaps not the right forum to discuss, but currently what we are doing is running virt-operator one time as a job, with "--dump-install-strategy". This requires very few permissions, basically just listing namespaces if I recall.  I agree that it would be cleaner to be able to just run this anywhere for a specific version of kubevirt by calling the function, we shouldn't need to be in a cluster or list namespaces. Will look into that.

It comes down to everything in our cluster needing to be strictly version controlled, and working within the system that does this, along with just not wanting to give applications certain permissions to change key cluster configurations.

**Pull request merged**
