### PR TITLE
e2e tests: move pod_servers functions

### PR DESCRIPTION
**Pull request by fossedihelm**
### What this PR does
Functions in pod_servers.go file are only
used in probes.go file.
Move them there and make them unexported.
Also, sort and rename imports.

### Release note

```release-note
NONE
```

/cc @EdDev @orelmisan

### CODE REVIEW

**Review by dankenigsberg — APPROVED** [review]

**Review by 0xFelix — APPROVED** [review]
/approve

**Comment by orelmisan** [comment]
/hold

Lets wait for ACK from sig network maintainer.
@EdDev

**Comment by orelmisan** [comment]
> > /hold
> > Lets wait for an ACK from sig network maintainer. @EdDev
> 
> @orelmisan May I ask why? The sig network is sole owner of this, the move just makes it official...

Because sig-network is owning this code I would expect to see feedback from the network maintainer before it gets merged.
Same for any other code, owned by any other sig.

**Comment by EdDev** [comment]
> > > /hold
> > > Lets wait for an ACK from sig network maintainer. @EdDev
> > 
> > 
> > @orelmisan May I ask why? The sig network is sole owner of this, the move just makes it official...
> 
> Because sig-network is owning this code I would expect to see feedback from the network maintainer before it gets merged. Same for any other code, owned by any other sig.

I pretty much agree.
At the minimum, I would expect a representative from the sig-network to acknowledge this for awareness.
@orelmisan, I trust you can decide if this makes sense and ack.

**Comment by xpivarc** [comment]
@orelmisan @EdDev I agree with you but this is just files being moved that are owned by you. The only possible request I could see is to move the file as is, rename or something to match your style.

**Review by orelmisan — APPROVED** [review]
Thank you @fossedihelm 
/hold cancel

**Pull request merged**
