### PR TITLE
passt: updating passt rpm and run `make rpm-deps`

### PR DESCRIPTION
**Pull request by AlonaKaplan**
**What this PR does / why we need it**:
The old rpms disappeared from the repo.
The next stage should be to backup the rpms on goggle cloud so issue like this won't happen again.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
Assured the RPMs are present where the [PR says they are](https://download.copr.fedorainfracloud.org/results/sbrivio/passt/centos-stream-8-aarch64/04696396-passt/).

**Review by enp0s3 — COMMENTED** [review]
/approve

**Comment by rmohr** [comment]
hm, we did not approve the mirror PR: https://github.com/kubevirt/kubevirt/pull/8223

**Comment by rmohr** [comment]
Force merging to restore CI.

**Comment by rmohr** [comment]
Mentioned the wrong PR. We did not approve this one: https://github.com/kubevirt/kubevirt/pull/8139. It would have mirrored the dependency. @AlonaKaplan FYI.

**Pull request merged**
