### PR TITLE
fix ticker leak

### PR DESCRIPTION
**Pull request by rokkiter**
Thanks for https://github.com/kubevirt/kubevirt/pull/10198#issuecomment-1658822641 remind me, Sorry, PR has been merged when I saw it.
Four possible leaked tickers are proposed here, and after checking, it is confirmed that two tickers need to be modified.

**What this PR does / why we need it**:
fix ticker leak
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vasiliy-ul** [comment]
Thanks, @rokkiter, for this follow-up PR.

> Four possible leaked tickers are proposed here, and after checking, it is confirmed that two tickers need to be modified.

Regarding the two others:

https://github.com/kubevirt/kubevirt/blob/417788458b68c37050f5797c603f33f6446d8459/pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go#L245

and 

https://github.com/kubevirt/kubevirt/blob/417788458b68c37050f5797c603f33f6446d8459/pkg/virt-launcher/monitor.go#L189

Indeed, they are stopped at some point in the code. Though, I think it would be better to use `defer ticker.Stop()` there. Thus, if, at some point, the code is refactored, we ensure the tickers are not leaked. WDYT?

**Comment by rokkiter** [comment]
My intention is to fix those tickers that are sure to leak, if defer is considered valuable, then it is worth modifying here.

**Comment by vasiliy-ul** [comment]
Thanks for fixing those as well!

/lgtm
/approve

**Pull request merged**
