### PR TITLE
propagate device aliases to libvirt using user-aliases

### PR DESCRIPTION
**Pull request by ahadas**
VMI devices are assigned with a mandatory name (#528) which is great since it enables their identification. This PR takes it a step further by making libvirt honor those aliases. This is done by using the naming convention for user-aliases (i.e., "ua-<alias>"). That would allow us to leverage[ the API that was recently added to libvirt](https://bugzilla.redhat.com/show_bug.cgi?id=1576916) (intended for oVirt 4.2) for unplugging a device by specifying only its alias.

```release-note
NONE
```

Signed-off-by: Arik Hadas <ahadas@redhat.com>

### CODE REVIEW

**Comment by ahadas** [comment]
not sure what's wrong this time...

**Comment by stu-gott** [comment]
Thanks @ahadas! I think the bot is telling you this PR needs a release note.  https://git.k8s.io/community/contributors/guide/release-notes.md This link explains what needs to be done.

**Comment by cynepco3hahue** [comment]
@ahadas you need to run `make generate` and commit again to make travis happy :smile:

**Comment by ahadas** [comment]
@stu-gott @cynepco3hahue thanks for the tips! I think I finally got it right :)

**Pull request merged**
