### PR TITLE
tests, network: XFail IPv6 connectivity check to an external address

### PR DESCRIPTION
**Pull request by EdDev**
This is a clone of #5114 with a rebased over https://github.com/kubevirt/kubevirt/pull/5099 to see results.

**What this PR does / why we need it**:
IPv6 connectivity check to the statically set address fails on CI.
The same tests pass locally.

Marking the assertion with xfail in order to allow investigation.

Ref: https://github.com/kubevirt/kubevirt/issues/5113

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Seen on https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-cnao-1.19

Originally raised by @enp0s3 on slack.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Comment by stu-gott** [comment]
/hold

this PR merges two separate PRs that should likely be committed separately

**Comment by EdDev** [comment]
> /hold
> 
> this PR merges two separate PRs that should likely be committed separately

We suspect these two are needed to open up the CI gate. At the minimum we need to see it passes and the rest can be merge independently but with force.

**Comment by EdDev** [comment]
See #5114 on why this is closed.

**Pull request closed without merging**
