### PR TITLE
Add checks to avoid duplicated Names for Devices

### PR DESCRIPTION
**Pull request by victortoso**
**What this PR does / why we need it**:
This PR adds a few extra checks and tests in regards to duplicated field:'Name' for Devices. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Motivation for this comes from https://github.com/kubevirt/kubevirt/pull/6829#discussion_r756148440 and https://github.com/kubevirt/kubevirt/pull/6829#discussion_r756132092
This PR should be updated after https://github.com/kubevirt/kubevirt/pull/6829 is merged

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by victortoso** [comment]
/hold
#6829 to be merged and this to be rebased + updated

**Comment by victortoso** [comment]
/unhold
* rebased after #6829

**Review by rmohr — COMMENTED** [review]
@victortoso finally got to it. Thanks a lot :+1. I think it makes sense to ensure that every device has a unique name ( for instance a sound and a gpu card with the same name should be rejected), what do you think?

**Comment by victortoso** [comment]
@rmohr hey, as usual, this PR is not urgent but let me know if I've got it right from your [comment](https://github.com/kubevirt/kubevirt/pull/6864#pullrequestreview-838271310). cheers!

**Comment by victortoso** [comment]
ping
/retest

**Comment by rmohr** [comment]
@victortoso thanks! I will bring it up on the next community meeting. I want to check with a few more maintainers if they agree that we can take it in without breaking backward compatibility too much (like some people could have duplicates already).

**Pull request closed without merging**
