### PR TITLE
Bump Kubevirtci, disable the custom SELinux policy and adapt for robust stack providers

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:

Bump Kubevirtci, changes:

[1b9174d centos8: update SELinux policy version](https://github.com/kubevirt/kubevirtci/pull/975)
[e1cf770 robust stack: Fix sanity check](https://github.com/kubevirt/kubevirtci/pull/970)
[bc50e16 Add WFFC variation of rook-ceph-block](https://github.com/kubevirt/kubevirtci/pull/967)
[656d01a centos8: set SELinux boolean that is now required for chardev access by containers](https://github.com/kubevirt/kubevirtci/pull/968)
[31e5860 vm based providers: Introduce robust stack provider](https://github.com/kubevirt/kubevirtci/pull/954)
[15b2c14 Refresh snapshot CRDs follow up for 1.26-centos9 provider](https://github.com/kubevirt/kubevirtci/pull/947)
[0163752 Enable Seccomp configuration](https://github.com/kubevirt/kubevirtci/pull/960)
[e037eb1 Adds note about CLI dependencies](https://github.com/kubevirt/kubevirtci/pull/959)
[9c37b86 k8s-1.24-psa: Remove leftovers](https://github.com/kubevirt/kubevirtci/pull/956)

Was created manually because the following changes are needed as well:

The SELinux policy in the latest Centos 8 base image is now similar to Centos 9, which means it has all the permissions we need but somehow prevents us from loading a custom policy.
The 3rd commit of this PR disables the custom SELinux policy on all lanes to be compatible with that.
This is a good thing overall, since we don't want to have to use our custom SELinux policy.
Thanks @jean-edouard 

The 2nd commit of this PR adapts dual stack assertion to be skipped for
`KUBEVIRT_SINGLE_STACK` instead if the provider is x.yz-ipv6,
since we support robust stack providers now.
Remove legacy providers from the condition as well.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Depends on https://github.com/kubevirt/project-infra/pull/2580

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by oshoval** [comment]
Might need also the fix of https://github.com/kubevirt/kubevirt/pull/9373 (or vice versa)

**Comment by jean-edouard** [comment]
@oshoval we're both bumping + fixing, my PR is https://github.com/kubevirt/kubevirt/pull/9373
Maybe I should cherry-pick your fix, or you mine?

**Comment by oshoval** [comment]
> @oshoval we're both bumping + fixing, my PR is #9373 Maybe I should cherry-pick your fix, or you mine?

Sure, meant that as well, will cherry-pick yours if its fine

**Comment by oshoval** [comment]
@jean-edouard 
Cherry-picked your fix, and rebased, can you please take a look ?
Thanks

**Comment by oshoval** [comment]
Running here the single stack with 2580
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2580/rehearsal-pull-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1633001999035273216

/cc @brianmcarey @jean-edouard

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Review by jean-edouard — COMMENTED** [review]
/approve

**Comment by oshoval** [comment]
Thanks Jed, Brian

**Pull request merged**
