### PR TITLE
virtctl: Compatible with multiple TigerVNC versions on OSX

### PR DESCRIPTION
**Pull request by imjoey**
Signed-off-by: imjoey <majunjiev@gmail.com>

**What this PR does / why we need it**:

Current the supported version of TigerVNC client is restricted to `1.8.0` (hardcoded). This pull request changes the way to find the TigerVNC executable file and enables the compatibility with multiple versions. If there has multiple versions installed, the latest one will always be launched first.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

This PR has been tested locally at several conditions:
1. With both TigerVNC v1.9.0 and v1.8.0 installed, v1.9.0 was launched
2. With only TigerVNC v1.9.0 installed, v1.9.0 was launched
3. With no TigerVNC installed, the log outputs as before: `Error encountered: exec: "remote-viewer": executable file not found in $PATH`

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by slintes** [comment]
nice, thanks!

**Comment by slintes** [comment]
ci test please

**Comment by petrkotas** [comment]
@slintes I am afraid that this PR cannot be fully tested via our CI. I would agree to merge it, and wait for the feedback from macos guys. What do you think?

**Comment by slintes** [comment]
@petrkotas yes, agree, will merge
@imjoey thanks for your contribution :)

**Comment by imjoey** [comment]
@petrkotas @slintes Thanks very much. 😄

**Comment by petrkotas** [comment]
@imjoey can you please send a short mail to kubevirt-dev <kubevirt-dev@googlegroups.com> introducing your change? Ideally with a screenshot :).

Thanks in advance!

**Comment by imjoey** [comment]
@petrkotas  Sure, I'll do it right away.

**Pull request merged**
