### PR TITLE
Enable Passt feature gate for test that require it.

### PR DESCRIPTION
**Pull request by Barakmor1**
Enable Passt feature gate in test that require it
to avoid flackiness

Signed-off-by: bmordeha <bmodeha@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by fossedihelm — COMMENTED** [review]
@Barakmor1 There is a package containing the `Skip` checks. https://github.com/kubevirt/kubevirt/blob/main/tests/framework/checks/skips.go
I think it is better to move the function there. Thanks!

**Comment by Barakmor1** [comment]
> @Barakmor1 There is a package containing the `Skip` checks. https://github.com/kubevirt/kubevirt/blob/main/tests/framework/checks/skips.go I think it is better to move the function there. Thanks!

Done.

**Comment by jean-edouard** [comment]
Isn't that feature gate always set already?
https://github.com/kubevirt/kubevirt/blob/8378b54233828948a9606b7c146060407248ca6a/tests/testsuite/kubevirtresource.go#L94

**Comment by Barakmor1** [comment]
> Can you provide the failure you see? As Jed suggested this should not happen

The failures happens in Openshift-CNV project

**Pull request closed without merging**
