### PR TITLE
Revert kubevirtci to previous published version

### PR DESCRIPTION
**Pull request by brianmcarey**
**What this PR does / why we need it**:

There is an issue starting the latest kubevirtci providers using docker[1] - revert to the previous version to allow docker users to successfully bring up the test clusters.

This change reverts https://github.com/kubevirt/kubevirt/pull/10375

[1] https://github.com/kubevirt/kubevirt/pull/10375#issuecomment-1712803145

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @dhiller @xpivarc @oshoval 
**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [x] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [x] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve

**Comment by akalenyu** [comment]
Would things be fine if docker client is bumped to something >= https://github.com/kubevirt/kubevirtci/pull/1067/files#diff-d17443c3719a1a4d24cc846ad591f53113b107f8d88823b858f6515903fb1dceR7?

**Comment by brianmcarey** [comment]
> Would things be fine if docker client is bumped to something >= https://github.com/kubevirt/kubevirtci/pull/1067/files#diff-d17443c3719a1a4d24cc846ad591f53113b107f8d88823b858f6515903fb1dceR7?

I am going new providers published using the latest from kubevirtci using docker rather than podman - we recently changed how the providers are published which we believe is causing this issue. 

This revert is just while we are waiting on new providers to be published - as the publishing can take some time.

**Pull request merged**
