### PR TITLE
SECURITY: Vulnerability reporting and vendor update

### PR DESCRIPTION
**Pull request by fabiand**
**What this PR does / why we need it**:

Clarifying how KubeVirt is supported by vendor security teams, removes the requirement for PGP encrypted vulnerability reporting.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Removal of PGP encryption got discussed offlist.
While it is less confidential, it is removing friction on the reporter side, as well as on the maintainer side - this benefit is considered to be more beneficial (aka faster and lower burden for reporters) besides the increased security of an encrypted email.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabiand** [comment]
@rthallisey @vasiliy-ul please review

**Review by vasiliy-ul — APPROVED** [review]

**Comment by fabiand** [comment]
Thanks!

Now we just need approvals!

**Comment by rmohr** [comment]
Two maintianers lgtm and one maintainer creating it makes 3 +1 already. Probably fair to approve.

/approve

/hold

just placing a hold in case you disagree.

**Comment by fabiand** [comment]
Thanks, I agree that this is enough. After all it's "backwards compatible"

**Pull request merged**
