### PR TITLE
docs/devel/networking: unbreak URL

### PR DESCRIPTION
**Pull request by dankenigsberg**
The currently-used anchor no longer exists.

```release-note
NONE
```
/cc @maiqueb

### CODE REVIEW

**Comment by maiqueb** [comment]
/lgtm
/hold

I'm good w/ this particular fix, but I'll have yet to go through the PR this one depends on. 

BTW: I'd have appreciated a note indicating this PR depends on another. Do you mind using the "Special notes for your reviewer:" section in the PR's description for that ? Something like `Depends-on: xyz` ?

**Comment by dankenigsberg** [comment]
The current doc point to a currently broken URL (I did not research what broken it and when). This pr fixes it, depending on nothing.

**Comment by maiqueb** [comment]
> The current doc point to a currently broken URL (I did not research what broken it and when). This pr fixes it, depending on nothing.

Either I am loosing my mind, or this PR features 8 commits, 7 of which are unrelated to unbreaking the URL.

**Comment by dankenigsberg** [comment]
> > The current doc point to a currently broken URL (I did not research what broken it and when). This pr fixes it, depending on nothing.
> 
> Either I am loosing my mind, or this PR features 8 commits, 7 of which are unrelated to unbreaking the URL.

No, it is me being careless with what I push. Single tiny patch rebased on master.

**Review by maiqueb — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
