### PR TITLE
[release-0.30] Add test related to launcher capabilities

### PR DESCRIPTION
**Pull request by kbidarkar**
Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>

**What this PR does / why we need it**: `Add test related to launcher capabilities`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: `Add test related to launcher capabilities`

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by kbidarkar** [comment]
Backport of #3502

**Comment by rmohr** [comment]
/override pull-kubevirt-e2e-k8s-1.18

that lane does not exist.

**Comment by stu-gott** [comment]
@kbidarkar this PR has merge conflicts

**Pull request merged**
