### PR TITLE
Make longer timeouts for SyncVMI and MigrateVirtualMachine

### LINKED ISSUE #2471: SyncVMI sometimes fails with "context deadline exceeded" (not only) during migrations
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Mostly during migrations, but also on other tests (see 1st comment), SyncVMI sometimes fails with "context deadline exceeded". During our CI tests this results in a test failure, because this triggers an unexpected warning event. However, if you ignore this warning, SyncVMI succeeds on the next try.

e.g.:
```
[rfe_id:393][crit:high[vendor:cnv-qe@redhat.com][level:system] VM Live Migration Starting a VirtualMachineInstance with auto converge enabled should complete a migration expand_less | 6m7s
-- | --
/root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:431 Unexpected Warning event received: testvmid6j2tfjm72qrwn5wsnsn6p4g2rbt9ft9mdnp9h9n55ln5gnw,a9419b63-a29a-11e9-b527-525500d15501: unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded Expected     <string>: Warning not to equal     <string>: Warning /root/go/src/kubevirt.io/kubevirt/tests/utils.go:348
```

**What you expected to happen**:
No SyncVMI failures, no warning events during migrations

**How to reproduce it (as minimally and precisely as possible)**:
not 100% reproducable
see e.g. cri-o CI test lane on this PR, there it happened several times: https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=kubevirt&pr=2459
I also experienced this regularly while working on the NFS migration test.

### PR DESCRIPTION
**Pull request by fedepaol**
**What this PR does / why we need it**:
We found out that several tests are failing because the SyncVMI call takes longer than 5 seconds to execute. This causes a Warning event that makes tests fail.

In the sriov-ci experimental lane we found one case that took 16 seconds to execute.
This PR raises the timeout to 20 seconds.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2471

**Release note**:

```release-note

NONE
```

### CODE REVIEW

**Comment by slintes** [comment]
lgtm
@rmohr @davidvossel wdyt?

**Comment by rmohr** [comment]
@fedepaol can you increase the worker number to 10 or 12 in https://github.com/kubevirt/kubevirt/blob/master/cmd/virt-handler/virt-handler.go#L280? Apart from that I like it.

**Comment by fedepaol** [comment]
@rmohr done

**Comment by rmohr** [comment]
/lgtm

Let's see what CI thinks.

**Pull request merged**
