### PR TITLE
tests, libnet, cloudinit: Drop redundant slice init

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

When using slices, there is no need to initialize it before performing an append operation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by vasiliy-ul — APPROVED** [review]

**Review by ormergi — APPROVED** [review]
@EdDev Good catch thanks for addressing this.

**Comment by EdDev** [comment]
> To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **xpivarc** after the PR has been reviewed.
> You can assign the PR to them by writing `/assign @xpivarc` in a comment when ready.

/assign @xpivarc 
Hi, could you please have a look?

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
