### PR TITLE
build: avoid double slashes in paths

### PR DESCRIPTION
**Pull request by mpolednik**
Although double slashes don't hurt us in the build process, it does seem like the path variables aren't properly constructed. This can be fixed easily by 1) stripping trailing slash and 2) make sure we have leading slash after each variable.

### CODE REVIEW

**Comment by davidvossel** [comment]
retest this please

**Comment by davidvossel** [comment]
retest this please

**Comment by fabiand** [comment]
retest this please

**Comment by rmohr** [comment]
needs a rebase

**Comment by mpolednik** [comment]
@rmohr Rebased.

**Comment by rmohr** [comment]
ok to test

**Comment by rmohr** [comment]
retest this please

**Comment by mpolednik** [comment]
Functional test failures are still unrelated to the PR.

**Comment by davidvossel** [comment]
retest this please

**Pull request merged**
