### PR TITLE
Bump kubevirtci: Stabilize SRIOV-lane

### PR DESCRIPTION
**Pull request by ormergi**
Signed-off-by: Or Mergi <ormergi@redhat.com>

**What this PR does / why we need it**:
This PR stabilize sriov-lane, folowing the PR https://github.com/kubevirt/kubevirt/pull/3435
Adding the changes from https://github.com/kubevirt/kubevirtci/pull/378
and https://github.com/kubevirt/kubevirtci/pull/383

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by phoracek** [comment]
I think you either have not commited all files after `make sync-kubevirtci` or have not called `make generate`.

**Comment by oshoval** [comment]
i would suggest please to prefix the commit message of bumps with 
`Bump kubevirtci - '<Reason>

**Comment by danielBelenky** [comment]
/override pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6

Overriding because it's a known issue.

**Comment by danielBelenky** [comment]
/override pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6

Overriding because it fails due to a *known* flaky test and there's no reason to rerun as all the other tests passed.

**Pull request merged**
