### PR TITLE
[release-0.54] sriov: Fix network to PCI-Address mapping

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This is a manual cherry-pick of the following PRs:
- https://github.com/kubevirt/kubevirt/pull/8093
- https://github.com/kubevirt/kubevirt/pull/8263
   diffs: 
   - Makefile: not adding `network/namescheme` package to lint since it doesn't exist in this branch
- https://github.com/kubevirt/kubevirt/pull/8226
   diffs: 
   - Makefile: not adding `network/sriov` package to lint since it doesn't exist in this branch
   - vmi.go: using `EscapeJSONPointer()` from `kubevirt.io/kubevirt/pkg/controller` since it didn't move [yet](https://github.com/kubevirt/kubevirt/commit/19af7003bbeb299ee9ed0155048956556709f554). 
   - template.go: exposed downwardAPI slightly differently since `rendervolumes.go` is not introduced [yet](https://github.com/kubevirt/kubevirt/commit/05059f8ef6b00d3ff9d131f05d0d3d2bf35a1c49)
   - tests/network/sriov.go: 
       - manually added `findIfaceByMAC()` ([source](https://github.com/kubevirt/kubevirt/blob/main/tests/network/sriov.go#L664-L682)) needed for test.
       - refactored test to use old functions prior to recent [refactor](https://github.com/kubevirt/kubevirt/pull/8299).
       - Add skip to test in case Multus is not updated with the updated network-status annotation.

This cherry pick PR fixes https://github.com/kubevirt/kubevirt/issues/7444 on `release-0.54` branch

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by EdDev — APPROVED** [review]

**Comment by RamLavi** [comment]
[fixed](https://github.com/kubevirt/kubevirt/compare/b563fc1fa5d812895fc00b8ea85ed0a47f9a871e..e49740c3d8e2ba4c6a4fbe1ed784d88fa0b50405)
/hold cancel

**Pull request merged**
