### PR TITLE
Provide client-gen install instructions

### PR DESCRIPTION
**Pull request by drssdinblck**
This pull request provides install instructions for how to install the Kubernetes client code generator as this might not be obvious to everyone.

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm

Thank you!

**Comment by drssdinblck** [comment]
@rmohr would you be so kind to leave the /ok-to-test label? Otherwise this pull request can't be merged unfortunately.

**Comment by rmohr** [comment]
@drssdinblck I think only `retest` does not work without the label, but tide takes the PR into the merge queue and retries internally when a PR is approved. That should also be the reason why you see it merged now.

**Pull request merged**
