### PR TITLE
refactor, tests, utils: extract flow interface from utils.RunVMI* funcs

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

This is an initial stab at replacing the `Run..AndExpect` functions with a flow-based interface to be more explicit and clear about what's happening when.

Also with this PR the `RunVMI` funcs in `utils.go` are being marked as deprecated.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
deprecate RunVMI funcs in utils.go
```

### CODE REVIEW

**Comment by dhiller** [comment]
@xpivarc @EdDev thoughts? Is this worth pursuing?

**Comment by dhiller** [comment]
> I think it violates the “no commands” [rule](https://github.com/kubevirt/kubevirt/tree/main/tests/libvmi#rules).
> 
> But now I also recognized that I missed another rule. It should not contain ginkgo or gomega functionalities.

@EdDev fair. But do you think this is an improvement and provides more clarity or do you suggest otherwise?

**Comment by EdDev** [comment]
> > I think it violates the “no commands” [rule](https://github.com/kubevirt/kubevirt/tree/main/tests/libvmi#rules).
> > But now I also recognized that I missed another rule. It should not contain ginkgo or gomega functionalities.
> 
> @EdDev fair. But do you think this is an improvement and provides more clarity or do you suggest otherwise?

I feedback too early and to late in my day, sorry for not looking at the bigger picture.

I think you used a mix of two build pattern, the 2nd is like the one used for client commands. I call it the build train pattern :)
IMO it works fine when the number of options are limited and fit nicely on one line. It looks odd to me to add
a large number of options this way, as the line breaks.
If I compare it to the k8s commands, I think the **must** fields are arranged with this build pattern and options are not. And I kind of like it, as it indeed limits well the train length and keeps things consistent (i.e. the train looks similar when used, we do not see one longer then the other too much).

If I simplify what you suggest, then it is something like this:
```go
vmi := libvmi.New(...)
client := kubevirt.TestClient()
client.Vmi(vmi, ...).Run(...).Wait(...)
```

Now, unlike the client pattern, we have a problem here to return errors of `Run`.
We could indeed assert it internally, but I usually do not like it because it messes up the report due to that awful offset (i.e. we do not know the distance of the stack calls from the test itself).

How about this option:
```go
vmi := libvmi.New(...)
client := kubevirt.VMIClient()
vmi, err := client.Run(vmi, libwait.WithWaitForPhase(v1.Running))
```

**Comment by dhiller** [comment]
> > > I think it violates the “no commands” [rule](https://github.com/kubevirt/kubevirt/tree/main/tests/libvmi#rules).
> > > But now I also recognized that I missed another rule. It should not contain ginkgo or gomega functionalities.
> > 
> > 
> > @EdDev fair. But do you think this is an improvement and provides more clarity or do you suggest otherwise?
> 
> I feedback too early and to late in my day, sorry for not looking at the bigger picture.
> 
> I think you used a mix of two build pattern, the 2nd is like the one used for client commands. I call it the build train pattern :) IMO it works fine when the number of options are limited and fit nicely on one line. It looks odd to me to add a large number of options this way, as the line breaks. If I compare it to the k8s commands, I think the **must** fields are arranged with this build pattern and options are not. And I kind of like it, as it indeed limits well the train length and keeps things consistent (i.e. the train looks similar when used, we do not see one longer then the other too much).
> 
> If I simplify what you suggest, then it is something like this:
> 
> ```go
> vmi := libvmi.New(...)
> client := kubevirt.TestClient()
> client.Vmi(vmi, ...).Run(...).Wait(...)
> ```
> 
> Now, unlike the client pattern, we have a problem here to return errors of `Run`. We could indeed assert it internally, but I usually do not like it because it messes up the report due to that awful offset (i.e. we do not know the distance of the stack calls from the test itself).
> 
> How about this option:
> 
> ```go
> vmi := libvmi.New(...)
> client := kubevirt.VMIClient()
> vmi, err := client.Run(vmi, libwait.WithWaitForPhase(v1.Running))
> ```

I agree that `runner.go` doesn't fit into `libvmi` (at least not right now), so I'm open to suggestions where it should go. I.e. should we create a `vmiconfig` package? (Naming is hard)

I understand that you are concerned with not explicitly handling errors here, but that is a problem that doesn't arise from the changes I made, but lies deeper, i.e. within `libwait`. In this PR I just tackle the problem of replacing the `RunVMI*` funcs with a better, more readable interface. 

IIUC users of the `utils.Run*` funcs don't really care about why the `vmi` run fails, since they don't expect it to fail in general. I agree that proper error handling would be beneficial here, so how about we store the error inside the `client` struct and check it at the end?

Example:
```
vmiRunner := vmiconfig.NewRunnerFor(vmi)
Expect(vmiRunner.Run().ThenWaitFor(v1.Running).Err).To(NotHaveOccurred())
vmi = vmiRunner.VMI
```

Aside from that: I actually am not sure whether the `client` nomenclature actually fits here, since I think this wording should only be used when using a proper client of an API, while we are just wrapping a VMI instance inside a helper struct that gives us a convenient, pleasant to read interface to wrap the details of running a VMI and expecting a state.

**Comment by EdDev** [comment]
> IIUC users of the `utils.Run*` funcs don't really care about why the `vmi` run fails, since they don't expect it to fail in general. I agree that proper error handling would be beneficial here, so how about we store the error inside the `client` struct and check it at the end?

They care when it fails, looking for what happened and where.
If the offset is not set correctly, they are clueless and start depending on odd logs.

String the error reminds me of C coding, but the real disadvantage its complexity (IMO).
I prefer a direct approach where we use helpers and do not mix assertions with functionality.

> Aside from that: I actually am not sure whether the client nomenclature actually fits here, since I think this wording should only be used when using a proper client of an API, while we are just wrapping a VMI instance inside a helper struct that gives us a convenient, pleasant to read interface to wrap the details of running a VMI and expecting a state.

What a "client" is depends on what you decide it is. While one client is for accessing the API Server, another client may include logic that embeds common testing functionality.
You can name it differently, but in my view it will be a client, which has more stuff.

**Pull request closed without merging**
