### PR TITLE
Bump bazeldnf to a version which can handle src packages

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

If src packages are in the same repo xml like the original package, bazeldnf could get confused. The new version filters them out earlier to avoid this.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhlhahaha** [comment]
Thanks!
/lgtm

**Comment by rmohr** [comment]
/close

replaced with #4798

**Pull request closed without merging**
