### PR TITLE
Bump kubevirtci

### PR DESCRIPTION
**Pull request by oshoval**
https://github.com/kubevirt/kubevirtci/pull/626 should fix k8s-1.21-sig-network (see PR for more details)
 
Changes:
`f0f1952` Switch to booting via kernel and initrd from outside the image (https://github.com/kubevirt/kubevirtci/pull/593)
`68abe5b` cnao, provision, Bump k8s-1.19/1.20/1.21 cnao to v0.56.0 (https://github.com/kubevirt/kubevirtci/pull/626)
`5760734` conformance tests: point to alternative registry (https://github.com/kubevirt/kubevirtci/pull/624)

Signed-off-by: Or Shoval <oshoval@redhat.com>

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
Will add the missing files, once https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5923/pull-kubevirt-e2e-k8s-1.21-sig-network/1407951176879575040 done

**Comment by rmohr** [comment]
@oshoval thanks, but we run a periodic two times a day which will create this kind of PR: https://github.com/kubevirt/kubevirt/pull/5926

I don't t hink that you have to create them manually.

**Comment by rmohr** [comment]
https://prow.ci.kubevirt.io/?job=*kubevirtci-bump*

**Comment by oshoval** [comment]
> @oshoval thanks, but we run a periodic every day which will create this kind of PR: #5926
> 
> I don't t hink that you have to create them manually.

I understand, but i had to check that k8s-1.21-sig-network is fixed by that, so on the way did it
i can close it if needed once i finish to change, just saw on slack that sometimes if we do need something without waiting the next run (24 hours) its ok to do that

**Comment by oshoval** [comment]
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5923/pull-kubevirt-e2e-k8s-1.21-sig-network/1407959931767754752

Passed (at least the ones that are not XFAIL)

Closing upon Roman request

**Comment by rmohr** [comment]
> Closing upon Roman request

I have no issues if you create your own PR. I just wanted to point out that it is there to make this work obsolete.

**Pull request closed without merging**
