### PR TITLE
refector : fix typo and modify code to make it more readable

### LINKED ISSUE #11300: refactor : fix typo and modify code to make it more readable
**Is your feature request related to a problem? Please describe**:
1. While analyzing the code, there are typos in the code and comments, so I'm trying to fix them.
(One question is, is the word "behaviour" a typo for "behavior"?)

2. modify code to make it more readable

**Describe the solution you'd like**:

**Describe alternatives you've considered**:

**Additional context**:

### PR DESCRIPTION
**Pull request by yj-yoo**
### What this PR does
- the RandomWithPrefix() function in the common package has been modified so that it can be used more universally.
- remove unnecessary newline and return
- added constants for readability
- conditional expressions and code simplification
- edit and modify comment
- modify the error log to fit fmt.Errorf() usage.
- change constants and variable to camel case.
- remove unnecessary type conversion
- remove duplicate packages
- edit long code to make it more readable.

Fixes #11300 

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by aburdenthehand** [comment]
For the interest of the reviewers, the PR description:
What does this PR do?

    The RandomWithPrefix() function in the common package has been modified to make it more universally usable.
    Remove unnecessary newlines and return
    Add constants for readability
    Simplify conditional expressions and code
    Edit and fix comments
    Fix error logs to match use of fmt.Errorf()
    Replace constants and variables with camel case
    Remove unnecessary type conversions
    Remove duplicate packages
    Edit long code to make it more readable.

Fix #11300

**Comment by awels** [comment]
looks fine to me, let me run the tests
/test all

**Comment by awels** [comment]
make sure to run `make generate` to ensure we don't get all these failures.

**Comment by EdDev** [comment]
@yj-yoo , please run `make generate` locally and add the changes to your relevant commit.

ref: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11315/pull-kubevirt-generate/1760538844953841664#1:build-log.txt%3A1944

**Comment by EdDev** [comment]
@yj-yoo , please check the unit test failures. I think they are related to the changes.

**Comment by aburdenthehand** [comment]
/remove-lifecycle stale
@yj-yoo You will need to rebase this before we can continue. 
Also, your last commit was not signed - but your first one was: if you squash all over your subsequent commits then the PR will be able to merged. (A PR cannot be merged unless all the [commits are signed](https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md#contributor-compliance-with-developer-certificate-of-origin-dco).)

**Comment by avlitman** [comment]
Hi @yj-yoo, thanks for this pr, are you planing to work on this more?

**Pull request closed without merging**
