### PR TITLE
Fix and improve implemention of `buildDevicesMetadata` method

### PR DESCRIPTION
**Pull request by VirrageS**
**What this PR does / why we need it**: In old implementation we used `taggedGPUs` map but we never written to it which was basically a bug. Now we use single map `taggedHostDevices` for tagged host devices and gpus. 

**Special notes for your reviewer**: None

**Release note**:
```release-note
GPUs are now correctly returned in `ConfigDriveMetadata.Devices` in cloud-init metadata.
```

### CODE REVIEW

**Comment by vladikr** [comment]
Hey @VirrageS , thanks for this PR!
It would be great if you could add a unit test to exercise this code. 
Thanks.

**Comment by VirrageS** [comment]
@vladikr could you take a look?

**Comment by VirrageS** [comment]
@rmohr do you know if somebody could take a look at it? @vladikr seems unresponsive :(

**Comment by rmohr** [comment]
/retest
/lgtm
/approve


Can you adjust the release message? Seems like you are fixing something user-visible here.

**Comment by oshoval** [comment]
> https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7676/pull-kubevirt-e2e-kind-1.23-sriov/1658024759478194176
> 
> seems like a real regression ? never saw it before please take a look, happens few times

FYI @EdDev

**Comment by VirrageS** [comment]
This should be fixed in latest commit.

**Comment by EdDev** [comment]
@VirrageS , the linter is not happy: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7676/pull-kubevirt-unit-test/1659236619636445184#1:build-log.txt%3A321

**Pull request closed without merging**
