### PR TITLE
virt-launcher: access-credentials: Trim newlines from SSH keys in secret

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
The secret that contains SSH keys for a VM can potentially contain multiple keys separated by newline, or just a single key with a newline at the end. This PR removes the newlines and splits the keys into a slice.

First commit in this PR add a `Stop()` method to the `AccessCredentialManager`, which is used in the new unit test to stop `fsnotify` and not leak it.

```release-note
None
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
Is the change to the manager really required to strip newlines from one or more keys? If not I'd like to keep these changes separate.

**Comment by akrejcir** [comment]
The `Stop()` method is needed so unit tests don't leak `fswatch`.
It would not be a big issue if unit tests leak.

**Comment by 0xFelix** [comment]
Can you add a sentence to the commit message why stopping the manager is needed.  Just for that tiny little bit of extra context? Thank you!

**Comment by akrejcir** [comment]
ping?

**Pull request merged**
