### PR TITLE
Add more fields to the Flavors API

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
Added `DomainSpec` to flavor API. It contains values that will be set on VM, ignoring `devices` field.
If a field is set on both, VM and flavor, the validating webhook will fail and report conflict.

The other commit is just an API change without functionality. It will be useful for future PRs.

**Special notes for your reviewer**:

**Release note**:
```release-note
Added DomainSpec field to flavor API.
```

### CODE REVIEW

**Comment by akrejcir** [comment]
Waiting for: https://github.com/kubevirt/kubevirt/pull/6920

/hold

**Comment by lyarwood** [comment]
205a38f90ab111b8c4f8a746a2a63d30419f990b just removed floppy disks, I'll rebase now so the tests get to run at least.

**Comment by lyarwood** [comment]
@akrejcir - can you close this PR out please, I'm going to move forward in a fresh PR shortly.

**Pull request closed without merging**
