### PR TITLE
go-sdk package support for third party applications

### PR DESCRIPTION
**Pull request by kunalkushwaha**
**What this PR does / why we need it**:
To integrate KubeVirt into existing go projects in the existing k8s ecosystem, currently whole KubeVirt project is required to vendor.
[go-sdk](https://github.com/kunalkushwaha/go-sdk) host packages using which any go project can integrate KubeVirt without vendoring whole KubeVirt codebase.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubevirt/kubevirt/issues/677

**Special notes for your reviewer**:
Currently, I moved all packages which were required by `pkg/api` & `/pkg/kubecli`.
In case we want to keep supporting packages that are moved in [go-sdk](https://github.com/kunalkushwaha/go-sdk), minor changes will be required in KubeVirt codebase over various files.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by kunalkushwaha** [comment]
@rmohr Thanks for review. 

> I would suggest that we follow the kubernetes approach. Put everything which we want to provide as part of an sdk into staging/kubevirt.io/kubevirt on a similar level to pkg. Then modify hack/dep-prune.sh to do the symlinking properly into the vendor folder.

I got your point. Just to clarify, following steps are required.
- Move the all code required for clients( as in go-sdk) to `github.com/kubevirt/staging/src/go-sdk/..` similar to Kubernetres https://github.com/kubernetes/kubernetes/tree/master/staging
- Modify `hack/dep-prune.sh` to create symlinks to `vendor/kubevirt.io/..` for each packages in `github.com/kubevirt/staging/src/go-sdk/..`
    - e.g.  github.com/kubevirt/staging/src/go-sdk/`  will create symlink to  `vendor/kubevirt.io/go-sdk`

- Once this is done, ask for new repo `go-sdk` and publish code it from `../staging/src/..` folder.

**Comment by rmohr** [comment]
Sounds correct. Maybe we want to call the package `client-go` too?

**Comment by kunalkushwaha** [comment]
Closing this PR for #2297 .

#2297  includes all changes as discussed in https://github.com/kubevirt/kubevirt/pull/2286#issuecomment-492892661

**Pull request closed without merging**
