### PR TITLE
tests, multi queue: Use pointer.Bool

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
It is nicer than defining a boolean
and referring it manually.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Review by rhrazdil — CHANGES_REQUESTED** [review]
Thanks, nicer indeed.
IIUC, pointer.Boolptr is deprecated: https://github.com/kubernetes/utils/blob/f6158b442e7c/pointer/pointer.go#L133
Shouldn't we use `pointer.Bool(true/false)` instead?

**Comment by oshoval** [comment]
Addressed comments

**Comment by dhiller** [comment]
/hold for getting the clone fix PR in

FYI @brianmcarey

**Pull request merged**
