### PR TITLE
sig-tests: Add approvers and include unit tests under sig-tests ownership

### PR DESCRIPTION
**Pull request by AlonaKaplan**
### What this PR does
Before this PR:
sig-tests owned only the e2e tests.

After this PR:
unit tests are included under sig-tests ownership.
The approvers list was extended.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by AlonaKaplan** [comment]
@dhiller @enp0s3 
That's what we planned to add to sig-test.

> sig-testing: 
> - .golangci.yml
> - tests/
> - nogo_config.json
> - cluster-up/
> - (.*/)*.*_test.go

However, I"m not sure all of those should be added.
`cluster-up` is just a copy of the kubevirtci, I don't think there is a need for an kubevirt owner for it.
`.golangci.yml` is for the linter. I find it more related to `sig-buildsystem` than the tests.
Same for `nogo_config.json`, I find it more related to the build than the tests.

What do you think?

**Comment by enp0s3** [comment]
@AlonaKaplan @dhiller I agree that linters, cluster-up and nogo related configs should be owned by `sig-buildsystem`

**Pull request merged**
