### PR TITLE
Fix for libvirt >= 9.1.0: Support multiple watchdogs in the domain schema

### PR DESCRIPTION
**Pull request by vasiliy-ul**
The issue has been found while testing a downstream build of KubeVirt v1.0.0 with libvirt **9.5.0**. Currently, it is not reproducible with the latest upstream images, since the libvirt version there is **9.0.0**. However, this issue is likely to emerge after an update of the virt stack.

The failing test with a watchdog device:

https://github.com/kubevirt/kubevirt/blob/d16161124f3008a0404de663f678f5a1b463ce5a/tests/vmi_configuration_test.go#L145-L155

**What this PR does / why we need it**:

Starting from version **9.1.0**, Libvirt adds an implicit watchdog device for q35 machine:

https://gitlab.com/libvirt/libvirt/-/commit/926594dcc82b40f483010cebe5addbf1d7f58b24

https://libvirt.org/formatdomain.html#watchdog-devices

> Having multiple watchdogs is usually not something very common, but be aware that this might happen, for example, when an implicit watchdog device is added as part of another device. For example the iTCO watchdog being part of the ich9 southbridge, which is used with the q35 machine type. Since 9.1.0

With the introduction of nic hotplug feature, we now call `define domain` twice (the actual call is done inside `l.setDomainSpecWithHooks(v, s)` callback):

https://github.com/kubevirt/kubevirt/blob/d16161124f3008a0404de663f678f5a1b463ce5a/pkg/virt-launcher/virtwrap/manager.go#L993-L998

https://github.com/kubevirt/kubevirt/blob/d16161124f3008a0404de663f678f5a1b463ce5a/pkg/virt-launcher/virtwrap/nichotplug.go#L180-L201

If the VMI spec requires a watchdog, then after the first call, the xml returned from `util.GetDomainSpecWithFlags(dom, libvirt.DOMAIN_XML_INACTIVE)` will include two devices (the requested and an implicit one):

```xml
    <watchdog model='i6300esb' action='poweroff'>
      <alias name='ua-watchdog'/>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x0b' function='0x0'/>
    </watchdog>
    <watchdog model='itco' action='poweroff'/>

```

However, the current schema supports only a single watchdog device:

https://github.com/kubevirt/kubevirt/blob/d16161124f3008a0404de663f678f5a1b463ce5a/pkg/virt-launcher/virtwrap/api/schema.go#L481

This leads to a malformed unmarshaled domain object (here `itco` watchdog should not have an address):

```xml
    <watchdog model="itco" action="poweroff">
        <alias name="ua-watchdog"></alias>
        <address type="pci" domain="0x0000" bus="0x02" slot="0x0b" function="0x0"></address>
    </watchdog>
```

 and on the second call of `define domain` it results in the following error:

```
unsupported configuration: itco model of watchdog is part of the machine and cannot have any address set.
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vasiliy-ul** [comment]
/cc @andreabolognani 

Hi Andrea, referring to your comment https://github.com/kubevirt/kubevirt/pull/10050#issuecomment-1639886618, maybe you will face the same issue when updating the virt stack. FYI.

**Comment by andreabolognani** [comment]
@vasiliy-ul thanks a lot for the heads-up!

Your changes look reasonable, and IIUC them getting merged would avoid me running into any issues when upgrading libvirt later.

I am however wondering if it would make sense to extend the VM spec so that it allows controlling the built-in iTCO watchdog, in addition of the existing ability to control the i6300esb one? I'm not too familiar with the topic, but I would expect that many users wouldn't need a second watchdog in that case.

**Comment by jean-edouard** [comment]
Would it make sense to test this in https://github.com/kubevirt/kubevirt/blob/main/tests/operator/operator.go#L1617 by adding a watchdog to the VMIs created by `generateMigratableVMIs()`?

**Comment by vasiliy-ul** [comment]
> Your changes look reasonable, and IIUC them getting merged would avoid me running into **any** issues when upgrading libvirt later.
> 

'**any** issues' sounds a bit optimistic, but let's hope for the best :)

> I am however wondering if it would make sense to extend the VM spec so that it allows controlling the built-in iTCO watchdog, in addition of the existing ability to control the i6300esb one? I'm not too familiar with the topic, but I would expect that many users wouldn't need a second watchdog in that case.

That is a very good point. I haven't thought about it. Adding iTCO watchdog to the VM spec sounds reasonable for me (especially since it is anyway present). Perhaps I can do that in a follow-up... just maybe lets see if there are some other comments on that since I am not very familiar with the watchdogs either.

**Comment by vasiliy-ul** [comment]
> Would it make sense to test this in https://github.com/kubevirt/kubevirt/blob/main/tests/operator/operator.go#L1617 by adding a watchdog to the VMIs created by `generateMigratableVMIs()`?

@jean-edouard, I will look into that. Thanks for pointing to the specific test :+1:

**Comment by vasiliy-ul** [comment]
Regarding extending the VMI spec with iTCO: this can be done after bumping libvirt version since the device is not supported prior to 9.1.0: https://gitlab.com/libvirt/libvirt/-/commit/5b80e93e42a1d89ee64420debd2b4b785a144c40

**Comment by andreabolognani** [comment]
> Regarding extending the VMI spec with iTCO: this can be done after bumping libvirt version since the device is not supported prior to 9.1.0

Yeah, I was thinking about a follow-up PR anyway.

**Comment by vasiliy-ul** [comment]
@jean-edouard, it looks like the issue is not reproducible on migration flow. Therefore, it will not be covered in the operator tests if we add a watchdog to VMIs in `generateMigratableVMIs()`. Seems that only the VMI creation is affected.

Apart from the test mentioned in the description, this is also covered by

https://github.com/kubevirt/kubevirt/blob/de8fd7887862a84fcfe45f5680fa38769ff1555e/tests/vmi_monitoring_test.go#L50

I double-checked, and the test also fails without this fix.

Nevertheless, I think it still might be beneficial to use watchdogs in the operator tests, as it sort of increases the tests coverage and potentially may help in identifying future problems. I added the related changes in a separate commit. I can drop it, but I think it won't hurt to have it. WDYT?

**Comment by rmohr** [comment]
/lgtm
/approve

/hold

@jean-edouard does it look good for you?

**Pull request merged**
