### PR TITLE
Adding @rnetser to the list of test-reviewers

### PR DESCRIPTION
**Pull request by rnetser**
**What this PR does / why we need it**:
Adding @rnetser to the list of test-reviewers

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
@rnetser you need to sign your commit though.

https://github.com/kubevirt/kubevirt/blob/master/CONTRIBUTING.md#contributor-compliance-with-developer-certificate-of-origin-dco

**Comment by rmohr** [comment]
Merging a few trivial patches alongside with some CI stabilization PRs.

**Pull request merged**
