### PR TITLE
Update CDI api references to be v1beta1 instead of v1alpha1

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Currently KubeVirt uses v1alpha1 API of CDI to do things like upload and create datavolumes. CDI has updated their API to v1beta1 which may have additional fields not present in the v1alpha1 API. This PR updates all references to use the new API.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
CDI API version used is now v1beta1
```

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
The risk here is that if someone is using an older version of CDI and updates KubeVirt, then KubeVirt's interaction with the old version won't work with this new v1beta1 cdi client.

What would you think about having virt-operator validate that if the DataVolume CRD exists, that it supports v1beta1, and if the CRD exists without v1beta1, that virt-operator refuses the install/update of the KubeVirt CR?

The sync error on the KubeVirt CR would indicate the error "Incompatible CDI install detected. Must update CDI to release x.y.z or higher"

**Comment by awels** [comment]
/hold
Agreed, I am actually already working on adding a condition to the kubevirt cr.

**Comment by awels** [comment]
Thinking about this a bit more, I don't think we should stop an upgrade. We have checks for features that require CDI. If CDI is not installed or not present, the features will simply not work. In combination with the condition that should give the user enough information to determine what they need to do to enable the features requiring CDI.

**Comment by awels** [comment]
@davidvossel I added a condition to the kubevirt CR to indicate if it properly found CDI with a compatible version. The status is true if yes, and false if no. Added some functional tests to verify it is reporting properly. I still don't think we should stop kubevirt upgrade due to bad CDI, just some features won't be available until they also upgrade CDI

**Comment by davidvossel** [comment]
> Added some functional tests to verify it is reporting properly. I still don't think we should stop kubevirt upgrade due to bad CDI, just some features won't be available until they also upgrade CDI

I get where you're coming from, and for the install case this makes sense.

However, for updates the thing that concerns me is people can be in a situation where their VM/VMI is up and running using a DataVolume, then after the update they're in a situation where that VM/VMI is unusable. It's possible it might even making existing workloads fail because our informer will fail to detect the datavolume exists.

I'm not sure it's a situation where features simply aren't available. For updates it appears like it can impact existing workloads as well.

**Comment by mhenriks** [comment]
> However, for updates the thing that concerns me is people can be in a situation where their VM/VMI is up and running using a DataVolume, then after the update they're in a situation where that VM/VMI is unusable. It's possible it might even making existing workloads fail because our informer will fail to detect the datavolume exists.

That is a very good point.  But I suspect the number of cases in which a datavolume is looked up are few and could be handled by looking for a PVC of the same name (when in this state)?  I know the restore logic would have to deal with it somehow as well.

I am not necessarily opposed to aborting an upgrade if old CDI is detected.  In this situation, we should still be able to take advantage of the new condition because the KubeVirt CRD is updated at the same time as the operator, right?

**Comment by awels** [comment]
The only potential issue I can think of, for running workloads is a live migration where the new pod on the new node needs to know the DV so it can attach the matching PVC to the new pod. Other than that, running workloads don't care about DVs because we use DVs to determine if the VM is able to run. Once its running it won't reference the DV again. Snapshots might be a different beast, haven't looked into those closely.

And thinking some more about the live migration scenario. The live migration simply won't complete due to the new pod not being able to start because of no DV support. You can start the live migration, and once CDI is updated it can compete. Seems like normal k8s behavior to me.

**Comment by davidvossel** [comment]
>  Other than that, running workloads don't care about DVs because we use DVs to determine if the VM is able to run. 

i don't know for sure what will happen. It could lead to a confusing state for our VM controller if one one the DataVolumes in a VM's DataVolumeTemplate section is all of the suddened not present after the VMI has launched. Maybe it works fine, maybe things get weird. It's kind of undefined territory.

**Comment by davidvossel** [comment]
> I am not necessarily opposed to aborting an upgrade if old CDI is detected. In this situation, we should still be able to take advantage of the new condition because the KubeVirt CRD is updated at the same time as the operator, right?

usually the crd is updated. i think 99% of the update flows people use are related to the olm flow. and in that case the crd is updated.

**Pull request closed without merging**
