### PR TITLE
First phase of separating storage code to storage pkg

### PR DESCRIPTION
**Pull request by ShellyKa13**
**What this PR does / why we need it**:
Moving snapshot and restore code of new storage pkg
moving storage types to new storage pkg
As a KubeVirt storage developer, I would like to modify code and tests with minimal disruption to other bits of KubeVirt code.
As a KubeVirt storage maintainer, I would like to be called whenever storage-related code is modified so that I can approve the change.
As a reviewer, I would like to quickly find storage-related code, tests and APIs under main/pkg/storage and main/tests/storage

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alicefr** [comment]
You might want to remove the pkg/storage/BUILD.bazel file from the commit

**Comment by rmohr** [comment]
/approve

separation makes sense and looks good from quick glance. Happy if someone else can review.

**Comment by brybacki** [comment]
it looks good to me, did not find any problems 
/lgtm

**Comment by ShellyKa13** [comment]
/hold
holding to let @arnongilboa PR: https://github.com/kubevirt/kubevirt/pull/8134 get in which probably has conflicts with this PR

**Pull request merged**
