### PR TITLE
Add Pep as a maintainer

### PR DESCRIPTION
**Pull request by codificat**
**What this PR does / why we need it**:

Access to [CNCF services](https://github.com/cncf/servicedesk) is limited to project maintainers.

As a community liaison I'd need to interact with these services, hence this request

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
goveralls seems to be down. PR is good on travis.

**Comment by rmohr** [comment]
/hold

/cc @fabiand 

can you approve too?

**Comment by fabiand** [comment]
/lgtm
/approve

For the reference - Pep will be helping us with community administrative
stuff.

**Pull request merged**
