### PR TITLE
[WIP] run CI against latest libvirt+qemu

### PR DESCRIPTION
**Pull request by crobinso**
I've set up some automation to generate [kubevirt/libvirt](https://github.com/kubevirt/libvirt) container images with the latest qemu/libvirt/... generated by [kubevirt-copr](https://github.com/crobinso/kubevirt-copr). Images are at [aintdiscole/kubevirt-libvirt](https://hub.docker.com/r/aintdiscole/kubevirt-libvirt). With these available it's a bit easier for devs to run the kubevirt test suite against latest releases of libvirt and qemu.

This PR updates WORKSPACE to point at a recently generated image. It's not intended for merge. Mostly I want to start a discussion about what is the ideal setup/archiecture for this type of testing. @rmohr I know you had some ideas on this front, please share them, I would like to help.

### CODE REVIEW

**Comment by rmohr** [comment]
> @rmohr I know you had some ideas on this front, please share them, I would like to help.

Great to see this. I think with your change we are not missing much. I would really just go with a periodic job which runs the tests on one of our k8s versions with the latest kubevirt master.

We would have:

 * A job which generates new libvirt/qemu images (possibly simplest thing: just runs once a day and pushes)
 * A periodic job which checks out kubevirt(master), changes the base image in the WORKSPACE file and runs our e2e tests against one of our k8s versions which we test.
 * Our periodics notify us in slack if they fail, so we have a trigger to investigate things.

We can of course try to make things smarter and more sophisticated once we have that, but this should be almost trivial to do and would help a lot already. @crobinso what do you think?

**Comment by crobinso** [comment]
@rmohr sounds good to me. Are there already periodic jobs in kubevirt CI? If there's an existing example I can follow as a starting point that will help. I haven't looked at any kubevirt CI plumbing before

The pending kubevirt/libvirt changes to switch back to RHEL based builds already broke my scheme here but after that stuff settles down I will get this basic example working again

**Comment by rmohr** [comment]
> @rmohr sounds good to me. Are there already periodic jobs in kubevirt CI? If there's an existing example I can follow as a starting point that will help. I haven't looked at any kubevirt CI plumbing before
> 
> The pending kubevirt/libvirt changes to switch back to RHEL based builds already broke my scheme here but after that stuff settles down I will get this basic example working again

@crobinso took me a while to bring #4703 into kubevirt. I think now it makes sense to start testing latest too.

What you basically have to do is extending `hack/rpm-deps.sh` to point to a separate `repo.yaml` file (`-f` flag on `bazeldnf`) and to install just whatever is in the latest repos instead of specific versions.

A job run would roughly look like this:

```
# prepare latest-repos.yaml
$ some_magic > latest-repo.yaml
$ make rpm-deps # with an indicator that we don't want pinned versions
$ automation/test.sh
```

An example periodic job would `periodic-kubevirt-push-nightly-conformance` here: https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml#L253

You would simply call the above instead of the current arguments. A good example with the automation script called already would be this presubmit job: 

https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml#L20

**Comment by crobinso** [comment]
Update branch hacks the bazeldnf world to pull latest Fedora style virt packages from [virt-preview](https://copr.fedorainfracloud.org/coprs/g/virtmaint-sig/virt-preview/). This could be a starting point for a recurring job. virt-preview makes it easy to get latest Fedora qemu package, though we would need another solution if we wanted something akin to latest RHEL qemu-kvm

**Pull request closed without merging**
