### PR TITLE
[release-1.1] fix: Reduce VM recovery times

### PR DESCRIPTION
**Pull request by jcanocan**
This is an manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/10961

NOTE: Slight change required with the original since `ptr` package is not present in release branch 1.1.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
Reduced VM rescheduling time on node failure
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm

Thanks

**Comment by xpivarc** [comment]
@jcanocan Can you please split the additional fix or at least point me to the diff?

**Comment by jcanocan** [comment]
> @jcanocan Can you please split the additional fix or at least point me to the diff?

Sure! Those! Basically, the linter is complaining that the `Eventually` is missing a `Should` statement. Also, the func `getHandlerNodePod` was not designed for being used in this way, so I've to return the pod inside the `Eventually`. I will create a follow-up PR in main for the `Eventually`  statement.

https://github.com/kubevirt/kubevirt/pull/11100/files#diff-500fb5c01cd6016282d6623d1cdf1a711815ddccb8aef0a234f6e159ea265665R1930-R1932

https://github.com/kubevirt/kubevirt/pull/11100/files#diff-500fb5c01cd6016282d6623d1cdf1a711815ddccb8aef0a234f6e159ea265665R1936-R1938

https://github.com/kubevirt/kubevirt/pull/11100/files#diff-500fb5c01cd6016282d6623d1cdf1a711815ddccb8aef0a234f6e159ea265665R1946

**Comment by xpivarc** [comment]
@jcanocan Please fix the main first and then include the fix here.

**Comment by jcanocan** [comment]
> @jcanocan Please fix the main first and then include the fix here.

Done: https://github.com/kubevirt/kubevirt/pull/11101

**Comment by jcanocan** [comment]
/hold
Until issue https://github.com/kubevirt/kubevirt/pull/11101 is solved.

**Comment by dominikholler** [comment]
@geetikakay are you comfortable already backporting the change to downstream 4.15 already , or do you like to have a look at downstream 4.16 before?

**Comment by geetikakay** [comment]
> @geetikakay are you comfortable already backporting the change to downstream 4.15 already , or do you like to have a look at downstream 4.16 before?

I would like to go with your second option. i would prefer to first examine the changes in version 4.16 .

**Review by 0xFelix — APPROVED** [review]
/lgtm

Thanks!

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
