### PR TITLE
return test 6053 from quarantine

### PR DESCRIPTION
**Pull request by ShellyKa13**
**Release note**:

```release-note
NONE

```

### CODE REVIEW

**Comment by fgimenez** [comment]
/hold

@ShellyKa13 we need to follow the procedure described here https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md to manage quarantined tests. In particular, to get a test out of quarantine we need to check that it is not failing for 14 days after its fix has been merged. 

Looking at the board where we are tracking the quarantined tests I see that the fix for this one is still in progress, is that correct?

**Comment by ShellyKa13** [comment]
@fedepaol I thought it failed but I saw that it started passing regularly after some day so I followed it and I saw it hasn't failed for the last 14 days according to this search: https://search.ci.kubevirt.io/?search=6053&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by fgimenez** [comment]
Something seems to be wrong with that search, I see in flakefinder that the tests failed in the rook-ceph periodic between 2021-06-24 and 2021-06-30 https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-06-30-168h.html#row18

If you think the test should be taken out of quarantine let's follow the procedure and start now the 14 days period to check if it fails again. If it doesn't fail passed this period let's propose a PR for taking it out of quarantine, wdyt?

**Comment by fgimenez** [comment]
For completeness this is the failed execution https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-rook-ceph/1408002066273538048 failed after the fix was merged https://github.com/kubevirt/kubevirt/pull/5825

**Comment by ShellyKa13** [comment]
@fgimenez yeah I know that it failed after the merge but then I saw that it didnt fail for a long period of time so I thought it was fixed regardless after the merge. so last time it failed was on the 24th? whats the best way to find it? and sure we can start the countdown again starting today if thats what you think is needed

**Comment by fgimenez** [comment]
> so last time it failed was on the 24th?

yes, I didn't find any more recent failure

> whats the best way to follow it?

should be https://search.ci.kubevirt.io/ as you did, but for some reason it is not working as expected, will take a look at it. This time I searched for this concrete tests through the 168h reports of flakefinder here https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/index.html

> and sure we can start the countdown again starting today if thats what you think is needed

yep, I think it's the best thing we can do now, I'll set the due date to 2021-07-19 in the ticket.

**Comment by ShellyKa13** [comment]
OK then, closing for now

**Pull request closed without merging**
