### PR TITLE
should set velero backup hook annotations when GuestAgent has connected

### LINKED ISSUE #9423: Velero Backup report failure if GuestAgent has not connected
**What happened**:
Create Velero backup on VM which GuestAgent has not connected. 
Backup will report as `PartiallyFailed`, failure log looks like below

> time="2023-03-13T11:45:07Z" level=info msg="stderr: {\"component\":\"freezer\",\"level\":\"info\",\"msg\":\"Starting...\",\"pos\":\"main.go:46\",\"timestamp\":\"2023-03-13T11:45:07.493380Z\"}\n{\"component\":\"freezer\",\"level\":\"error\",\"msg\":\"Freezeing VMI failed\",\"pos\":\"main.go:81\",\"reason\":\"server error. command Freeze failed: \\\"LibvirtError(Code=86, Domain=10, Message='Guest agent is not responding: QEMU guest agent is not connected')\\\"\",\"timestamp\":\"2023-03-13T11:45:07.498572Z\"}\n" backup=acs-dr/vm-backup-29ppm hookCommand="[/usr/bin/virt-freezer --freeze --name v4 --namespace vm-n1-hub]" hookContainer=compute hookName="<from-annotation>" hookOnError=Continue hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:174" name=virt-launcher-v4-kqnlb namespace=vm-n1-hub resource=pods

**I think we should set velero backup hook in pod annotation only if GuestAgent is connected.**

```
"post.hook.backup.velero.io/command": "[\"/usr/bin/virt-freezer\", \"--unfreeze\", \"--name\", \"vm-1\", \"--namespace\", \"default\"]",
"post.hook.backup.velero.io/container": "compute",
"pre.hook.backup.velero.io/command": "[\"/usr/bin/virt-freezer\", \"--freeze\", \"--name\", \"vm-1\", \"--namespace\", \"default\"]",
"pre.hook.backup.velero.io/container": "compute",
```

**What you expected to happen**:
Velero backup should success.

**How to reproduce it (as minimally and precisely as possible)**:
Create Velero backup on VM which GuestAgent has not connected. 

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0
- Kubernetes version (use `kubectl version`): v1.25
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lxs137**
**What this PR does / why we need it**:

Set velero backup hook pod annotation only if GuestAgent has connected. 
It can avoid velero backup report failure if GuestOS does not connect GuestAgent.

**Which issue(s) this PR fixes**:
Fixes #9423

**Special notes for your reviewer**:

**Release note**:

```release-note
should set velero backup hook annotations when GuestAgent has connected
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
Hi, thanks for the PR.

With this change backups will be created regardless of the VMI being frozen or not. I suspect this may result in corrupted backups? Is freezing a feature of qemu or the qemu-guest-agent? Is the guest agent really necessary to freeze a VM?

**Comment by 0xFelix** [comment]
Ok, looking at the code, the freeze is a qemu-guest-agent feature. So how do we make sure backups are consistent when the FSes are not frozen?

**Comment by lxs137** [comment]
@0xFelix If GuestOS dose not support QEMUGuestAgent, I think it's vm user's responsibility to freeze the filesystem manually. In this case, maybe we should do nothing.

**Comment by mhenriks** [comment]
This issue was previously addressed here, surprised there is still an issue:  https://github.com/kubevirt/kubevirt/pull/8217

Adding/removing annotations is racy, would be better to handle in virt-vfeezer if possible

**Comment by lxs137** [comment]
> This issue was previously addressed here, surprised there is still an issue: #8217
> 
> Adding/removing annotations is racy, would be better to handle in virt-vfeezer if possible

@mhenriks great, I will try this solution

**Pull request closed without merging**
