### PR TITLE
Add metrics types to kubevirt metrics description

### PR DESCRIPTION
**Pull request by assafad**
When querying Prometheus it is extremely important to know the metric type: gauge/counter/histogram/summary.
This PR Adds metrics types to kubevirt metrics documentation.

Signed-off-by: assafad <aadmi@redhat.com>

```release-note
None
```

### CODE REVIEW

**Review by enp0s3 — APPROVED** [review]
/approve
/retest

**Comment by xpivarc** [comment]
/hold
@assafad You need to rebase.

**Pull request merged**
