### PR TITLE
storage tests: remove standalone nfs access tests via ipv4/ipv6

### PR DESCRIPTION
**Pull request by akalenyu**
### What this PR does
Arguably, it's none of kubevirt's business to test that an nfs server
is reachable via it's ipv4/ipv6 IP. this is something that kubelet
should cover and is seamless from the kubevirt perpsective when
the storage is available to the pod.
this was previously discussed in https://github.com/kubevirt/kubevirt/pull/7324#issuecomment-1077350079

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
/cc @vladikr @xpivarc 

Hey! I need some help here; context https://github.com/kubevirt/kubevirt/pull/4659/commits/7d696ec551fa80de83863e268339444ae50f6064
When I rewrite the non qemu owned test to use a hostPath source instead of NFS, it fails.
Reading the code I am pretty sure the only time we will chown, is when the volume source is HostDisk, so, this test was probably just passing as a fluke. Can you point me at something that will chown the PVC sources?
(as that commit originally intended)

**Comment by akalenyu** [comment]
> /cc @vladikr @xpivarc
> 
> Hey! I need some help here; context [7d696ec](https://github.com/kubevirt/kubevirt/commit/7d696ec551fa80de83863e268339444ae50f6064) When I rewrite the non qemu owned test to use a hostPath source instead of NFS, it fails. Reading the code I am pretty sure the only time we will chown, is when the volume source is HostDisk, so, this test was probably just passing as a fluke
> 
> https://github.com/kubevirt/kubevirt/blob/09e7adbdbf94fefc74a3d68acd0a5b698415a25c/pkg/virt-handler/non-root.go#L66-L81
> 
> Can you point me at something that will chown the PVC sources?
> (as that commit originally intended)

Please ignore! just need your review now.
The issue was https://github.com/kubevirt/kubevirt/compare/61b001608cd9742b7d23049f1bc956fd7cd4b61e..9b9541456faa248adf66309afeeb9b92c15ecc40

**Comment by xpivarc** [comment]
> /cc @vladikr @xpivarc
> 
> Hey! I need some help here; context [7d696ec](https://github.com/kubevirt/kubevirt/commit/7d696ec551fa80de83863e268339444ae50f6064) When I rewrite the non qemu owned test to use a hostPath source instead of NFS, it fails. Reading the code I am pretty sure the only time we will chown, is when the volume source is HostDisk, so, this test was probably just passing as a fluke
> 
> https://github.com/kubevirt/kubevirt/blob/09e7adbdbf94fefc74a3d68acd0a5b698415a25c/pkg/virt-handler/non-root.go#L66-L81
> Can you point me at something that will chown the PVC sources?
> (as that commit originally intended)

The intention was that https://github.com/kubevirt/kubevirt/blob/main/pkg/host-disk/host-disk.go#L232 would cover this.

**Comment by akalenyu** [comment]
> > /cc @vladikr @xpivarc
> > Hey! I need some help here; context [7d696ec](https://github.com/kubevirt/kubevirt/commit/7d696ec551fa80de83863e268339444ae50f6064) When I rewrite the non qemu owned test to use a hostPath source instead of NFS, it fails. Reading the code I am pretty sure the only time we will chown, is when the volume source is HostDisk, so, this test was probably just passing as a fluke
> > https://github.com/kubevirt/kubevirt/blob/09e7adbdbf94fefc74a3d68acd0a5b698415a25c/pkg/virt-handler/non-root.go#L66-L81
> > 
> > Can you point me at something that will chown the PVC sources?
> > (as that commit originally intended)
> 
> The intention was that https://github.com/kubevirt/kubevirt/blob/main/pkg/host-disk/host-disk.go#L232 would cover this.

Yep, I figured that out, it's just that my grep lost this because it's using the deprecated version of chown https://github.com/kubevirt/kubevirt/blob/9b9541456faa248adf66309afeeb9b92c15ecc40/pkg/ephemeral-disk-utils/utils.go#L122-L123 https://github.com/kubevirt/kubevirt/blob/9b9541456faa248adf66309afeeb9b92c15ecc40/pkg/host-disk/host-disk.go#L257

So, 2 questions as a conclusion:
- Should it be using the deprecated variation?
- Do we intend to only chown the disk file (and not the entire mount recursively)?
(context-https://github.com/kubevirt/kubevirt/compare/61b001608cd9742b7d23049f1bc956fd7cd4b61e..9b9541456faa248adf66309afeeb9b92c15ecc40)

**Comment by awels** [comment]
yay, I hate those tests, glad they are getting removed
/lgtm

**Review by enp0s3 — COMMENTED** [review]
/approve
@akalenyu Thank you!

**Pull request merged**
