### PR TITLE
[release-0.59] Add VirtualMachine foreground finalizer

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/8937 and https://github.com/kubevirt/kubevirt/pull/9259
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Added foreground finalizer to  virtual machine
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
/cc @xpivarc @iholder101 
I created this backport PR which also contains the fix for `--cascade=orphan` fix

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
