### PR TITLE
OWNERS_ALIAS: Remove Alona Kaplan from the reviewer list

### PR DESCRIPTION
**Pull request by EdDev**
### What this PR does

Alona is no longer actively reviewing PRs in the project. Therefore, help Prow bot to avoid automatically assigning PRs for review on her name.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer
This change is made with consent from @AlonaKaplan .

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
change: Rebase

**Comment by dhiller** [comment]
> > @EdDev Should we remove @AlonaKaplan from being an approver as well? Is she planning to be at least somewhat active on this repo?
> 
> @iholder101 , I think that approvers can either be removed by themselves, by a bot that follows some rules (I think @dhiller has one that cleans members in general) or by an approvers committee. I vote to let a bot do it, seems to me the most polite way to suggest removing inactive approvers.

I agree that we might leave her there for now - at least she will not get assigned reviews which is the thing this PR wants to tackle I believe.

When i run the bot next time, it might move her to emeritus_approvers.

**Review by dhiller — APPROVED** [review]
@EdDev thank you!

**Comment by dhiller** [comment]
> > > @EdDev Should we remove @AlonaKaplan from being an approver as well? Is she planning to be at least somewhat active on this repo?
> > 
> > 
> > @iholder101 , I think that approvers can either be removed by themselves, by a bot that follows some rules (I think @dhiller has one that cleans members in general) or by an approvers committee. I vote to let a bot do it, seems to me the most polite way to suggest removing inactive approvers.
> 
> I agree that we might leave her there for now - at least she will not get assigned reviews which is the thing this PR wants to tackle I believe.
> 
> When i run the bot next time, it might move her to emeritus_approvers.

FTR - the "bot" is actually a script I've created while working on cleaning up the org members list last time: https://github.com/kubevirt/project-infra/pull/3283

**Pull request merged**
