### PR TITLE
OWNERS: Move AlonaKaplan to the emeritus approvers

### PR DESCRIPTION
**Pull request by EdDev**
### What this PR does

Based on the project governance [1], maintainers that are idle for 6 months or more are to be moved to the emeritus list.

Unfortunately, it seems Alona has changed focus and is no longer active [2] in the project.
Therefore, Alona is moved to the emeritus approvers list.

[1] https://github.com/kubevirt/community/blob/main/GOVERNANCE.md#removing-maintainers
[2] https://github.com/AlonaKaplan?tab=overview&from=2024-05-10&org=kubevirt

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

This is a sad PR :/

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder101** [comment]
Thank you @AlonaKaplan for all of your contribution!
Would you like to be the one approving this PR? :)

/lgtm

**Comment by vladikr** [comment]
/approve
Thanks.

**Comment by EdDev** [comment]
> @EdDev I just want to point out that [1] https://github.com/kubevirt/community/blob/main/GOVERNANCE.md#removing-maintainers is about maintainers and we don't define approvers as one. So the rule/guidance doesn't really apply. Maybe we have a better reference to provide? (Or we need to make one)

From my point of view the rules are the same and we can apply them to approvers.
While organization maintainers are the ones mentioned in that list, the approvers are maintainers of projects/repos.

@aburdenthehand  mentioned that he already prepared the needed changes to apply it for repos "approvers", so I hope he will post it soon.

**Comment by aburdenthehand** [comment]
Correct, what's holding it up is we don't yet have an easy and universal way of demonstrating that an approver has been inactive in a repo.

**Pull request merged**
