### PR TITLE
repeated_test: Remove tests_suite_test.go from focus-file set

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

If the file `tests/tests_suite_test.go` is included in the set of changed files, it will pull in all the other tests, which will void using `-focus-file` flag.

Example: PR https://github.com/kubevirt/kubevirt/pull/9902 , job run https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9902/pull-kubevirt-check-tests-for-flakes/1678382062605701120#1:build-log.txt%3A2275

Thus we extend the filtering grep to also exclude the suite file.

We also add `--dry-run` flag in order to see which tests will actually be run but neither executing them nor spinning up the cluster if the flag is set.

Finally we move the cluster-sync out of the inner loop, since we only need to do this once at the start of the test cycle, since if a test fails in a further cycle there's something wrong with the suite anyway.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
Testing changes in draft PR #10078

**Comment by dhiller** [comment]
> Testing changes in draft PR #10078

Actually the test run has executed the expected amount of tests: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/10078/pull-kubevirt-check-tests-for-flakes/1678744626313302016#1:build-log.txt%3A2262

so looks ok from my side.

**Comment by dhiller** [comment]
Lots of flakes seem to be appearing in this run... Not at all related to the changes of this PR.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
