### PR TITLE
Drop SRIOVLiveMigration feature gate test

### PR DESCRIPTION
**Pull request by vasiliy-ul**
**What this PR does / why we need it**:

SRIOVLiveMigration feature gate has been removed so the test is not needed anymore.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by EdDev — APPROVED** [review]
Thank you!

**Comment by vasiliy-ul** [comment]
Forgot to include the removal of unneeded imports. Updated.

**Review by EdDev — APPROVED** [review]

**Comment by vasiliy-ul** [comment]
Again hitting this error:
> failed to get image info: failed to invoke qemu-img: exit status 2: 'fatal error: runtime: cannot allocate memory

Anyway, lets give another try

/retest-required

**Comment by EdDev** [comment]
> Again hitting this error:
> 
> > failed to get image info: failed to invoke qemu-img: exit status 2: 'fatal error: runtime: cannot allocate memory
> 
> Anyway, lets give another try
> 
> /retest-required

Hopefully this will solve it temporarily: https://github.com/kubevirt/project-infra/pull/2334

**Pull request merged**
