### PR TITLE
Fix node_labeller flaky test

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
Fixes the flakiness of the test `should run node-labeling`
The test calls `nlController.execute()` function which perform a `PATCH`, but the mock kubeClient hasn't the reactor to manage that api call. This causes a failure of the labeling process and a re-queuing of the node. The test should fail but, since the re-queue process is delayed, it passes most of the time. If the re-queue process succeed before test makes `Expect(nlController.queue.Len()).To(Equal(0), "labeller should process all nodes from queue")` the test fail, otherwise no.
Adding the patch reactor to the mock kubeClient makes the test pass.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by jean-edouard — COMMENTED** [review]
Good catch!
Can we push this further and move `Expect(nlController.queue.Len()).To(Equal(0)` into a `Consistently` loop of a few seconds, to ensure that failure cases are properly captured as well?
Alternatively, we could add a test that doesn't do `expectNodePatch()` and `Eventually` expects that the queue will be `> 0`.
WDYT?
/ok-to-test

**Comment by acardace** [comment]
> Good catch! Can we push this further and move `Expect(nlController.queue.Len()).To(Equal(0)` into a `Consistently` loop of a few seconds, to ensure that failure cases are properly captured as well? Alternatively, we could add a test that doesn't do `expectNodePatch()` and `Eventually` expects that the queue will be `> 0`. WDYT? /ok-to-test

Good idea! I'd follow the `Consistently` route, and also we should take this as a pattern wherever unit tests check for queue's lengths to see if an error occurred. Probably we have a bunch of flaky unit tests that randomly fail like this (?).

The `Consistently` timeout should be greater than the backoff of the rate limiter otherwise we still might get false positives.

**Comment by fossedihelm** [comment]
>> Good catch! Can we push this further and move Expect(nlController.queue.Len()).To(Equal(0) into a Consistently loop of a few seconds, to ensure that failure cases are properly captured as well? Alternatively, we could add a test that doesn't do expectNodePatch() and Eventually expects that the queue will be > 0. WDYT? /ok-to-test

>Good idea! I'd follow the Consistently route, and also we should take this as a pattern wherever unit tests check for queue's lengths to see if an error occurred. Probably we have a bunch of flaky unit tests that randomly fail like this (?).
The Consistently timeout should be greater than the backoff of the rate limiter otherwise we still might get false positives.

Thanks. Totally agree with both. I'm working on it making this test more robust.

**Review by acardace — APPROVED** [review]
well spotted! All looks good to me.

**Comment by jean-edouard** [comment]
@fossedihelm please run `make generate && make` and commit the changes, some robot doesn't like where "time" is in the list of imports...

**Comment by fossedihelm** [comment]
> @fossedihelm please run `make generate && make` and commit the changes, some robot doesn't like where "time" is in the list of imports...

@jean-edouard Thanks, I forgot to run it. Fixed

**Review by acardace — APPROVED** [review]

**Comment by dhiller** [comment]
/test pull-kubevirt-e2e-k8s-1.20-sig-compute

/hold

we should stop retesting until flakiness fixes got in

**Pull request merged**
