### PR TITLE
Remove quarantine label

### PR DESCRIPTION
**Pull request by vatsalparekh**
Signed-off-by: Vatsal Parekh <vparekh@redhat.com>

**What this PR does / why we need it**:
Remove the quarantine label added in #5998 
I was not able to reproduce this locally and after some changes in the test file, I see this has not failed in last 15 days, so removing the quarantine label for stability check

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zcahana** [comment]
We also have #6096 which should further reduce timeout-based flakes in this test, as well as address the failures in its VMI-counterpart.

/lgtm
/cc @enp0s3

**Comment by zcahana** [comment]
> /hold until #6096 makes stability better

#6096 has just been merged.

**Comment by fgimenez** [comment]
/retest

> #6096 has just been merged.

Great, we are now checking the stability in the periodics. If we don't have any more failures until 2021-08-12 we can unhold this one.

**Comment by vatsalparekh** [comment]
@fgimenez 
/hold cancel

**Review by phoracek — COMMENTED** [review]
/approve

**Pull request merged**
