### PR TITLE
Fixes olm schema validation for the KubeVirt CR api

### PR DESCRIPTION
**Pull request by davidvossel**
This addresses the issue found in https://github.com/kubevirt/kubevirt/issues/5608. We'll need to backport this to the release-0.41 branch before we can consider that issue closed though. 

The olm has stricter schema validation and refuses to upgrade KubeVirt without this change. 

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
@tiraboschi does hco somehow shortcut the kubevirt operator and let also OLM update the VM and VMI CRDs? If so, @davidvossel I think we have to pull in https://github.com/kubevirt/kubevirt/pull/5495/commits/51a0c81550944be0ea3e5f5d58519dc73ae994da which fixes something similar for `spec.machine`.

**Comment by tiraboschi** [comment]
> @tiraboschi does hco somehow shortcut the kubevirt operator and let also OLM update the VM and VMI CRDs? If so, @davidvossel I think we have to pull in [51a0c81](https://github.com/kubevirt/kubevirt/commit/51a0c81550944be0ea3e5f5d58519dc73ae994da) which fixes something similar for `spec.machine`.

No, I'm pretty sure that the OLM will care only about the CRDs explicitly listed in the CSV and VM and VMI ones are not.
Since the upgrade cannot be easily rolled back, before deploying a newer version of a CRD, the OLM will implicitly try to verify the compatibility of it with the existing corresponding CRs.
I'm pretty sure that the OLM is not going to do anything like that for CRDs that it is neither aware of.

**Comment by rmohr** [comment]
> No, I'm pretty sure that the OLM will care only about the CRDs explicitly listed in the CSV and VM and VMI ones are not.
> Since the upgrade cannot be easily rolled back, before deploying a newer version of a CRD, the OLM will implicitly try to verify the compatibility of it with the existing corresponding CRs.
> I'm pretty sure that the OLM is not going to do anything like that for CRDs that it is neither aware of.

Great. Then the scope of the PR should be correct, as it is.

**Comment by rmohr** [comment]
there is a compile error.

**Comment by davidvossel** [comment]
> can you have a look at what I pushed?

+1 thanks

**Pull request merged**
