### PR TITLE
[release-0.22] Put all our direct dependencies on our mirror

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Put all our direct dependencies on our mirror

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by slintes** [comment]
interesting that the windows, genie and sriov lanes were running already, before the jobs for this branch were merged :thinking: 

/test all

**Comment by rmohr** [comment]
> interesting that the windows, genie and sriov lanes were running already, before the jobs for this branch were merged

What do you mean?

**Comment by rmohr** [comment]
Maybe the setup for these three is not correct?

**Comment by slintes** [comment]
> Maybe the setup for these three is not correct?

that was my first thought as well, but `skip_branches` looks for them

**Pull request merged**
