### PR TITLE
Add Killercoda.com to Adopters

### PR DESCRIPTION
**Pull request by killercoda-github**
**What this PR does / why we need it**:

Add Killercoda.com to Adopters

Release note:
```release-note
NONE
```

### CODE REVIEW

**Comment by dankenigsberg** [comment]
/lgtm

Thanks! It's great to hear about another KubeVirt user. Would you add an explicit NONE to the release notes so this can be merged?

**Comment by dankenigsberg** [comment]
/ok-to-test

Any chance @killercoda-github  would like to contribute more by providing a KubeVirt playground in your platform?

**Comment by killercoda-github** [comment]
@dankenigsberg sounds like a great idea! We'll do!

**Review by dankenigsberg — APPROVED** [review]

**Pull request merged**
