### PR TITLE
virt-handler: Restrict node access

### PR DESCRIPTION
**Pull request by fossedihelm**
### What this PR does
As of today a virt-handler has "full" access to all Nodes. Therefore installing Kubevirt means that every node will have a service account that can be miss used to influence the scheduling of other Pods, potentially with a more privileged service account.

This PR introduces [validationAdmissionPolicy](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/), that will prevent the virt-handler user from:

- changing the node's spec
- adding/removing/updating labels and annotations not owned by kubevirt.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

- This change will take affect only on cluster that support validatingAdmissionPolicy v1.
- e2e test were introduced, but due to bazel related https://github.com/google/cel-go/issues/947 - unit tests will be -introduced in later PR (see draft https://github.com/kubevirt/kubevirt/pull/12021)

The following alternatives were considered: Full alternative discussion on https://github.com/kubevirt/community/pull/246

This PR is relying on https://github.com/kubevirt/kubevirt/pull/12009

### Special notes for your reviewer

This PR takes https://github.com/kubevirt/kubevirt/pull/11982 commits and:
- adds FG management
- fixes e2e test reducing computational cost
- fixes vap deletion

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (https://github.com/kubevirt/community/pull/246) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Introduce validatingAdmissionPolicy to restrict node patches on virt-handler
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
[Changes](https://github.com/kubevirt/kubevirt/compare/0244850728e484088cb55dcfedeb5d204bc98a09..15b762585d0d4245657906a42da84be65d552776): Addressed flakyness

**Review by jean-edouard — APPROVED** [review]

**Comment by fossedihelm** [comment]
/hold
 Depends on another pr

**Comment by RamLavi** [comment]
I'm not sure I understand why this PR is merging two different changes regarding node restriction.
Also, I don't think we should use a FG for this use case.

I suggest we discuss this offline
/hold

**Comment by fossedihelm** [comment]
/close

In favor https://github.com/kubevirt/kubevirt/pull/11982

**Pull request closed without merging**
