### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by xpivarc**
Debugging failed to get image info: failed to invoke qemu-img: signal: segmentation fault on periodic-kubevirt-e2e-k8s-1.20-cgroupsv2

### CODE REVIEW

**Comment by xpivarc** [comment]
/pull-kubevirt-e2e-k8s-1.20-cgroupsv2

**Comment by maya-r** [comment]
I'm assuming this was meant to investigate a problem that #6335 resolved -- should this PR be closed?

**Pull request closed without merging**
