### PR TITLE
Pin dependencies to prevent the update

### PR DESCRIPTION
**Pull request by cynepco3hahue**
- k8s dependencies
- client-go dependencies
- Azure and go-kit dependencies

**What this PR does / why we need it**:
This PR pin some dependencies to prevent their update as a side effect of `make deps-update`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@slintes I did it, but `go mod tidy` change it to the `date-commit` stuff, I believe at least for 1.11.5 only tags that supported should have the form `v0.3.0`

**Comment by slintes** [comment]
> @slintes I did it, but `go mod tidy` change it to the `date-commit` stuff

ok, too bad
I can't see logs of the failed jobs, probably because of the change in the prow config of today,will retrigger tests

/retest

**Pull request merged**
