### PR TITLE
Use the dedicated container_file_t tmpfs for tests

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
See https://github.com/kubevirt/kubevirtci/pull/340

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Depends on https://github.com/kubevirt/kubevirtci/pull/340

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vladikr** [comment]
Looks good. Please run `make` to make travis happy ;)

**Comment by jean-edouard** [comment]
Thanks @vladikr, fixed.

**Comment by vladikr** [comment]
/override pull-kubevirt-e2e-k8s-1.15-ceph
The failed test isn't relevant for this PR.

**Comment by jean-edouard** [comment]
Force-pushed to rebase and fix test (srcDir needs to be under tmpDir).

**Pull request merged**
