### PR TITLE
Integrate functional tests with oVirt CI

### PR DESCRIPTION
**Pull request by rmohr**

### CODE REVIEW

**Comment by rmohr** [comment]
test

**Comment by rmohr** [comment]
ok to test

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
ready to test

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
ready to test

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
ready to test

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
ready to test

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
ready to test

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
ready to test

**Comment by rmohr** [comment]
ready to test

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
[Run functional tests on ovirt-jenkins and report back to github pull requests if they passed.](https://trello.com/c/TamIvtDi/5-run-functional-tests-on-ovirt-jenkins-and-report-back-to-github-pull-requests-if-they-passed)

**Comment by fabiand** [comment]
This is great work @rmohr - lgtm

**Comment by fabiand** [comment]
retest this please

**Pull request merged**
