### PR TITLE
Configure Kind clusters to use CI's proxy

### PR DESCRIPTION
**Pull request by ormergi**
This PR tests kubevirt/kubevirtci#772 changes

Signed-off-by: Or Mergi <ormergi@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by dhiller** [comment]
Looks like the setup worked. @ormergi can you confirm?

**Comment by ormergi** [comment]
> Looks like the setup worked. @ormergi can you confirm?

@dhiller Other SR-IOV jobs are passing now, I think its because the SR-IOV nodes schedule only them.
We are trying to verify it by correlating between mirror-proxy logs to the jobs log, I will update with our findings.

**Comment by ormergi** [comment]
@dhiller We can confirm that KIND cluster pulls form the CI mirror-proxy, we saw pulling events on the proxy logs
one the same time when the SR-IOV job deployed its components (e.g sriov-cni, sriov-dp).
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7516/pull-kubevirt-e2e-kind-1.22-sriov/1511252356208005120

Could you please do forwarder checking to see if everything is in place?

**Comment by dhiller** [comment]
@ormergi I have just rerun the job to test whether the priorityclass works now

**Comment by ormergi** [comment]
> Seems to get assigned:
> 
> ```
> $ kubectl describe pod 9c1c592c-b4ea-11ec-ad9f-7e363ff3a229                                                                                               
> ...
> Priority:             1000000                                                                                                                      
> Priority Class Name:  sriov                                         
> ...
> ```
> 
> tada

Very nice!

**Pull request closed without merging**
