### PR TITLE
[release-0.55] tests, console: Prevent NewExpecter negative timeout scenario

### PR DESCRIPTION
**Pull request by orelmisan**
**What this PR does / why we need it**:
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/9497 and the proposed change in https://github.com/kubevirt/kubevirt/pull/9515.

Run `make generate` in order to update the year in the license comment of the generated files, in order to pass the `pull-kubevirt-generate ` lane.

Cherry-picked the commit from PR https://github.com/kubevirt/kubevirt/pull/8987 in order to pass the `pull-kubevirt-e2e-windows2016 lane`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/e12823c701ed761acea02a86e62a5623dc64a022..60c36a347813b085638e86a8f850830ab8e653a9): Cherry-picked the commit from PR https://github.com/kubevirt/kubevirt/pull/8987 in order to pass the `pull-kubevirt-e2e-windows2016` lane.

**Review by ormergi — APPROVED** [review]

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
