### PR TITLE
tests: ensure the virt-handler killer pod has gone after deletion

### PR DESCRIPTION
**Pull request by enp0s3**
Make sure the killer-pod has been deleted in order not to affect other tests.

Signed-off-by: Igor Bezukh <ibezukh@redhat.com>

**What this PR does / why we need it**:
In time frame between a deletion TS was added to
the killer pod and until it's actually has been deleted
we may have an inconsistent bahavior where the killer pod
keeps killing the virt-handler in the upcoming tests.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by enp0s3** [comment]
cherry-pick release-0.34

**Review by stu-gott — APPROVED** [review]
/lgtm

**Pull request merged**
