### PR TITLE
virt-api: request/limits can now be used with CPU/Memory hotplug

### PR DESCRIPTION
**Pull request by acardace**
**What this PR does / why we need it**:

The limitation in configuring requests/limits when using CPU/Memory hotplug has no real technical roadblock and as such can be removed to have more freedom when defining a VM.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
Requests/Limits can now be configured when using CPU/Memory hotplug
```

### CODE REVIEW

**Comment by mhenriks** [comment]
Love PRs that just delete code!

**Comment by xpivarc** [comment]
@acardace @mhenriks Please provide an example of how this should work, I fail to understand this. Afaik there was a real usability /& correctness issue that caused us to block requests/limits!

**Comment by xpivarc** [comment]
> @xpivarc Perhaps its the case where you for some reason define `liveUpdateFeatures`, but at the same time you use CPU and mem requests instead of using VM CPU/mem topology. In such case every change you do afterwards in the VM CPU/mem topology should be staged to the next power cycle.

Well if you define the `liveUpdateFeatures` then the changes will not be staged or?

**Comment by xpivarc** [comment]
@acardace @mhenriks please look into reverting this PR or creating a blocker issue for the next release to sort out all possible technical implications this has.
As an example currently, one VM spec can have 2 meanings, depending if the VM was started or hotpluged.

**Pull request merged**
