### PR TITLE
Vendor in CDI 1.5

### PR DESCRIPTION
**Pull request by stu-gott**
Backport CDI vendor fix to release 0.13

**Release note**:
```release-note
Target CDI 1.5.1 (fixes mandatory status field in DataVolumes)
```

### CODE REVIEW

**Comment by stu-gott** [comment]
ci test please

**Comment by stu-gott** [comment]
ci test please

**Comment by davidvossel** [comment]
is failing because the patch can't be ported over directly. you need to re-run make/make generate

**Comment by stu-gott** [comment]
Negative. when you run `make` and `make generate`, there are no changes to the git tree. The actual error from the travis log is:

```Error: Error downloading packages:
  Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=fedora-28&arch=x86_64
  The command '/bin/sh -c dnf install -y dnf-plugins-core &&     dnf copr enable -y @virtmaint-sig/virt-preview &&     dnf -y install libvirt-devel-${LIBVIRT_VERSION} make git mercurial sudo
gcc findutils gradle rsync-daemon rsync qemu-img protobuf-compiler &&     dnf -y clean all' returned a non-zero code: 1
  make: *** [generate] Error 1
  The command "make generate" exited with 2.
```

This is network related? bad cache?

**Comment by stu-gott** [comment]
ci test please

**Comment by davidvossel** [comment]
ci test please

**Comment by davidvossel** [comment]
ci test please

**Comment by davidvossel** [comment]
> This is network related? bad cache?

I can't make sense of it.  Travis is passing on all our other PRs without hitting the repo update issue.

**Comment by davidvossel** [comment]
I just noticed travis was never actually re-running. We've just been looking at the same travis failure over and over.  I forced an update to the pr which will force travis to re-run.

**Comment by stu-gott** [comment]
ah! I just don't even know what to say to that. but thanks! what change did you make?

**Comment by davidvossel** [comment]
>  what change did you make?

I just amended the commit message. it's a no-op change that changes the git hash of the commit.

**Comment by davidvossel** [comment]
The functional tests are still failing to even execute.  I did my best to verify this locally using the openshift-3.11-crio lane.  

The only consistent test failure I've found is this

```
[Fail] Migrations Starting a VirtualMachineInstance  with an Alpine read only disk [It] should be successfully migrated multiple times 
/root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:111
```

However, after re-running the functional tests without this PR using 1.13, the same failure still persists so it is at least not introduced by this PR.

**Comment by stu-gott** [comment]
Tests pass locally here too, minus what you've noted

**Comment by slintes** [comment]
> > what change did you make?
> 
> I just amended the commit message. it's a no-op change that changes the git hash of the commit.

hint for the next time: there is a `Restart build` button on the travis site, might have been enough and easier :slightly_smiling_face:

**Comment by davidvossel** [comment]
> hint for the next time: there is a Restart build button on the travis site, might have been enough and easier

ha, thanks for the tip!

**Pull request merged**
