### PR TITLE
[restore tests]: apply mac patch to controllerrevision test as well

### PR DESCRIPTION
**Pull request by akalenyu**
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>

**What this PR does / why we need it**:
It appears we need the mac address patch here as well, otherwise, we're creating a new restored VM with same MAC as source. Kubemacpool environments caught this.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder101** [comment]
> /uncc @itamarh
> /cc @iholder101

This happens too often :laughing:

**Comment by iholder101** [comment]
Thanks @akalenyu! Nice catch!
/lgtm

@lyarwood can you also take a look? maybe we forgot more tests?

**Comment by lyarwood** [comment]
> Thanks @akalenyu! Nice catch!
> /lgtm
>
> @lyarwood can you also take a look? maybe we forgot more tests? 

These are the only raw restore tests for instance types that I'm aware of so we should be good. AFAIK the clone tests should arleady handle this right?

**Review by lyarwood — APPROVED** [review]

**Comment by akalenyu** [comment]
@dhiller any known fossa failure?

**Pull request merged**
