### PR TITLE
Update golang to 1.11.2 version

### PR DESCRIPTION
**Pull request by mfranczy**
**What this PR does / why we need it**:
Update golang to 1.11.2 version

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by mfranczy** [comment]
ci test please

**Comment by mfranczy** [comment]
ci test please

**Comment by davidvossel** [comment]
travis-ci failed.

Besides keeping up with build improvements, is there a specific reason we're wanting to update the golang version?  I'm just curious if there's an expected improvement we're getting from this

**Comment by mfranczy** [comment]
ci test please

**Comment by mfranczy** [comment]
/hold cancel

ds builds pass

**Comment by mfranczy** [comment]
ci test please

**Comment by mfranczy** [comment]
ci test please

**Comment by davidvossel** [comment]
where are we at with this? The code changes look fine to me.

**Comment by davidvossel** [comment]
> I am not blocking this anymore, we can merge it.

perfect, I'm just waiting on CI then

**Comment by mfranczy** [comment]
restarting tests cause they are in the "Running" state more than 10 hours...

**Comment by mfranczy** [comment]
ci test please

**Pull request merged**
