### PR TITLE
propagate vmi uid to libvirt domain

### PR DESCRIPTION
**Pull request by ahadas**
**What this PR does / why we need it**:
Propagate the UID that a VMI is defined with to libvirt as the UUID of the domain. It is better than letting libvirt generate a different UID for the domain.

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by mfranczy** [comment]
Converter tests are failing (unit tests), you might want to add output from `make generate` as well.

**Comment by ahadas** [comment]
@mfranczy thanks :) fixed the failing unit test and added the output of `make generate`

**Comment by ahadas** [comment]
oops, do not merge! there's a problem with this that I'm checking

**Comment by cynepco3hahue** [comment]
@ahadas When it will be ready for merge just run `/unhold`

**Comment by ahadas** [comment]
Closing this PR as on the one hand, the UID (in ObjectMetadata) of a VMI is auto-generated by the system and cannot be set by the user. On the other hand, the Name (in ObjectMetadata) of the VMI cannot be updated. So in this situation, I don't see a reason to propagate the ID - when needing to do some operation through libvirt we can use the Name as the identifier.

**Comment by rmohr** [comment]
Yes we explicitly did not use the k8s uuid, so that you can set the firmware uuid.

**Pull request closed without merging**
