### PR TITLE
Add virtio-gpu device for aarch64 VMs

### PR DESCRIPTION
**Pull request by zhlhahaha**
Signed-off-by: howard zhang <howard.zhang@arm.com>

**What this PR does / why we need it**:
Issue details in following comments
https://github.com/kubevirt/kubevirt/issues/8708#issuecomment-1301896896

**Release note**:
```release-note
NONE
```

Hi @andreabolognani 
After add the virtio-gpu as well as virtio-gpu-pci, VM can successfully boot on Arm64, and both e2e tests and unit tests passed on Arm64 server. I use `make rpm-deps` to update the package information. It seems many other packages have updated as well. I am not sure if it is ok.

### CODE REVIEW

**Comment by zhlhahaha** [comment]
cc: @xpivarc @awels

**Comment by xpivarc** [comment]
/approve
@andreabolognani

**Comment by andreabolognani** [comment]
@zhlhahaha good stuff!

You managed to figure out the root cause of the issue: if virtio-gpu-pci is used but virtio-gpu is not available, QEMU will apparently just straight up crash.

```
# /usr/libexec/qemu-kvm -display none -accel tcg -M virt -cpu max -device virtio-gpu-pci
qemu-kvm: -device virtio-gpu-pci: missing object type 'virtio-gpu-device'
Aborted (core dumped)
```

This leads me to believe that we have a bug in the RPM package for QEMU, since this requirement should be recorded as an explicit dependency. It shouldn't be possible to install the `qemu-kvm-device-display-virtio-gpu-pci` package without the `qemu-kvm-device-display-virtio-gpu` package coming along for the ride. I'll take care of filing a bug for this.

As far as KubeVirt is concerned in the short term, your solution is correct.

Just one minor suggestion: could you please split the changes into two separate commits? One which is the result of running `make rpm-deps` before making any changes to `hack/rpm-deps.sh`, and a second one which includes both the changes to `hack/rpm-deps.sh` and the changes produced by a second `make rpm-deps` run. This would make it clear which of the changes are necessary to fix the issue, and which are unrelated package updates.

**Comment by andreabolognani** [comment]
@zhlhahaha excellent, thanks!

/lgtm

**Comment by brianmcarey** [comment]
/test pull-kubevirt-e2e-kind-1.23-sriov 

New required job was added and stuck in expected state.

**Comment by andreabolognani** [comment]
> This leads me to believe that we have a bug in the RPM package for QEMU, since this requirement should be recorded as an explicit dependency. It shouldn't be possible to install the `qemu-kvm-device-display-virtio-gpu-pci` package without the `qemu-kvm-device-display-virtio-gpu` package coming along for the ride. I'll take care of filing a bug for this.

FYI filed now as https://bugzilla.redhat.com/show_bug.cgi?id=2149022

**Pull request merged**
