### PR TITLE
Update kubevirtci to the latest version

### PR DESCRIPTION
**Pull request by danielBelenky**
The latest version includes updated okd images with renewed
certs.

**Release note**:

```release-note
NONE
```

Signed-off-by: Daniel Belenky <dbelenky@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
@danielBelenky you can write `NONE` into the release-label section, to get rid of the `release-note-label-needed` flag.

**Comment by oshoval** [comment]
LGTM

**Comment by danielBelenky** [comment]
Closing in favor of #2939

**Pull request closed without merging**
