### PR TITLE
Use constants

### PR DESCRIPTION
**Pull request by lucky-sideburn**
### What this PR does
Before this PR:

After this PR:

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note

```

### CODE REVIEW

**Comment by jean-edouard** [comment]
Thank you for your PR @lucky-sideburn
I don't thing these can be consts, since they are dynamically initialized...

**Comment by lucky-sideburn** [comment]
Ok @jean-edouard thank you :) I close the PR.

**Comment by iholder101** [comment]
@lucky-sideburn if you want to go for a small cleanup effort in this file, you can use our pointer package [1] to replace these variables, e.g. replace `_true` with `pointer.P(true)`.

[1] https://github.com/kubevirt/kubevirt/blob/main/pkg/pointer/pointer.go

**Comment by lucky-sideburn** [comment]
Hi @iholder101 

Thank you for your suggestion. Yes, I would like to contribute to the project (I will use the pointer package)

I am also the author of [KubeInvaders](https://landscape.cncf.io/?item=observability-and-analysis--chaos-engineering--kubeinvaders), a tool for performing Chaos Engineering on Kubernetes. I am currently developing support for KubeVirt, and once it is finished, I would love to share it with the KubeVirt community. 😊

**Comment by iholder101** [comment]
> Yes, I would like to contribute to the project (I will use the pointer package)

Awesome, thank you!

> I would love to share it with the KubeVirt community. 😊

You're welcome to join our community meeting at Wednesdays. Check out https://kubevirt.io/videos/community/meetings.html for more info.

**Comment by lucky-sideburn** [comment]
@iholder101 ok I will join

**Comment by lucky-sideburn** [comment]
Hi @iholder101 thank you for the link of the community meetings. I attended one, but only as an auditor.

I've added to KubeInvaders the ability to discover and reboot virtual machines created with KubeVirt. [Here](https://www.youtube.com/watch?v=m3qpqjsrCus) you can find a demonstration. In the coming weeks, I'll also set up useful metrics and other chaos testing methods.

Happy new year!

**Pull request closed without merging**
