### PR TITLE
cluster-sync, Remove prefetch images logic

### PR DESCRIPTION
**Pull request by oshoval**
At the past kubevirt prefetched images (CDI and the dynamic built ones)
due to few reasons:
1. Kubevirtci didn't support prefetching CDI images yet.
2. CDI had flaky tests / and flaky `cluster-sync` and it was in order
to reduce chances of races.

Prefetch CDI images is not needed anymore, since
kubevirtci does it when provisioning (see Note).
The images that are built during cluster-build,
will simply pulled by their pod according needs.

CDI version was upgraded since then, so some of the problems are solved,
but since we are prefetching the images as part of the provision, no
regression will be possible.

This PR makes `cluster-sync` faster by around 3 minutes.

Note:
This PR depends on, which fetches the CDI images as part of the provisions:
https://github.com/kubevirt/kubevirtci/pull/659
https://github.com/kubevirt/kubevirtci/pull/660

Signed-off-by: Or Shoval <oshoval@redhat.com>

```release-note
None
```

### CODE REVIEW

**Comment by brybacki** [comment]
Let me clarify one thing, prefetch was the fix for randomly timeouting storage tests not for the `cluster-sync` problems.

**Comment by oshoval** [comment]
So far was ok

/test pull-kubevirt-e2e-k8s-1.20-sig-storage
/test pull-kubevirt-e2e-k8s-1.19-sig-storage
/test pull-kubevirt-e2e-k8s-1.21-sig-storage

**Comment by rmohr** [comment]
What I find interesting is that we have pretty long sync phases, even if the images are already present. It looks a little bit to me like `crictl` is blindly overriding existing blobs which makes the sync process in general pretty slow.

**Comment by oshoval** [comment]
> What I find interesting is that we have pretty long sync phases, even if the images are already present. It looks a little bit to me like `crictl` is blindly overriding existing blobs which makes the sync process in general pretty slow.

I saw what you mean for the "static" images (quay, not the ones we build),
I am not sure if its really copy them from scratch, or it just looks much slower but it actually takes time mostly just for the dynamic images.

If i manually run `docker pull quay.io/kubevirt/cdi-controller:v1.36.0` on the node, then its fine in the 2nd time..

Anyhow, wdyt about this change?
so far it seems safe.
Discussed with Bartosz and Igor offline, and we are running it several times to make sure.

Btw we can consider prefetch CDI images on kubevirtci if its legit to check what manifests kubevirt uses,
its nice to have and orthogonal to this PR, and if needed can be done on other PR.

**Comment by oshoval** [comment]
The flake that appears 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6228/pull-kubevirt-e2e-k8s-1.20-sig-storage/1425425180569636864
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6228/pull-kubevirt-e2e-k8s-1.19-sig-storage/1425425180716437504

I saw in the past as well (hopefully this PR doesnt make it worse, but anyhow its not the solution to fetch all those images everytime for it)

**Comment by oshoval** [comment]
All those errors seen in the past as well

/test pull-kubevirt-e2e-k8s-1.20-sig-storage
/test pull-kubevirt-e2e-k8s-1.19-sig-storage
/test pull-kubevirt-e2e-k8s-1.21-sig-storage

**Comment by oshoval** [comment]
https://search.ci.kubevirt.io/?search=pod+not+owned+by+qemu&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

This test was flaky before, but this PR might cause it to be little more flaky
what do you suggest @brybacki  ?
maybe the test can be improved ?

**Comment by brybacki** [comment]
so kubevirtci can prefetch current cdi, that is good news, that should be enough, no need to repeat the process and waste time/bandwith for it in kubevirt

**Comment by brybacki** [comment]
I'll try to look into the failing test later,

**Comment by oshoval** [comment]
> I'll try to look into the failing test later,

Thanks, but once we prefetch its pretty ortogonal to this PR imo right ?

**Comment by oshoval** [comment]
Thanks
lets hold it until the PRs that prefetch the images on kubevirtci are merged and bumped

/hold

**Comment by oshoval** [comment]
> Note:
> This PR depends on, which fetches the CDI images as part of the provisions:
> [kubevirt/kubevirtci#659](https://github.com/kubevirt/kubevirtci/pull/659)
> [kubevirt/kubevirtci#660](https://github.com/kubevirt/kubevirtci/pull/660)

PRs are merged, once kubevirtci will be bumped on kubevirt will release the hold

**Comment by oshoval** [comment]
/hold cancel
the PRs were bumped on kubevirt

@enp0s3 
can you take a look please?

**Review by enp0s3 — APPROVED** [review]
Thank you!
/approve

**Comment by rmohr** [comment]
:+1 very helpful.

**Pull request merged**
