### PR TITLE
Fix vmexport download snapshot test

### PR DESCRIPTION
**Pull request by alromeros**
**What this PR does / why we need it**:

This PR fixes a minor error in the virtctl vmexport download snapshot test, so we use an appropriate volume name to download.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
Can it be that we don't run this test? I can't find any failing instances. Do you have an example?

**Comment by alromeros** [comment]
> Can it be that we don't run this test? I can't find any failing instances. Do you have an example?

We skip the test if it's not run on openshift. We've been seeing this test failing repeatedly downstream.

**Pull request merged**
