### PR TITLE
Bump kubevirtci and fix kubectl output

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:
This PR bumps kubevirtci to latest version (see #5910). Also it suppresses verbose output when calling `cluster-up/kubectl.sh` to fix the pod checks. See https://github.com/kubevirt/kubevirt/pull/5911/files#diff-ce25e369a9df9edc525425cc144fc8c40599fff3cc1e5058b64336d71af67162R163

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @ormergi @fgimenez 

**Release note**:

```release-note
Bumps kubevirtci, also suppresses kubectl.sh output to avoid confusing checks
```

### CODE REVIEW

**Comment by dhiller** [comment]
/override pull-kubevirt-e2e-kind-1.17-sriov

This provider does not exist in the latest kubevirtci any more.

**Review by fgimenez — APPROVED** [review]
/lgtm

Thanks!

**Review by ormergi — APPROVED** [review]
Thank you!

**Comment by ormergi** [comment]
Looking on https://github.com/kubevirt/kubevirt/blob/main/automation/test.sh#L243 again
when we call `kubectl get pods -n $i --no-headers | grep -v Running` 
It will probably interpreters to something like: 
`echo blah blah blah; kubectl get pods -n kubevirt --no-headers | grep -v Running`
And the output will be:
```
selecting docker as container runtime
virt-handler-dgtv4                        1/1     Running   0          14h
virt-operator-7679cf9568-96pxk            1/1     Running   0          14h
....
```
The while condition on [[1] ](https://github.com/kubevirt/kubevirtci/blob/main/cluster-up/cluster/ephemeral-provider-common.sh#L9-L37 ) will take in account the first line which is `selecting docker as container runtime`
or any other echo content that been passed to stdout along the way calling `hack./kubectl.sh`

I think we should avoid adding logic that could generate stdout content on scripts that meant to be sourced
I afraid we might hit it again lets figure this out on a follow up PR

[1] https://github.com/kubevirt/kubevirtci/blob/main/cluster-up/cluster/ephemeral-provider-common.sh#L9-L37

**Review by enp0s3 — APPROVED** [review]
/approve
/hold
lets see the lanes

**Comment by dhiller** [comment]
FYI the failure on `bazel shutdown` was not introduced by this PR: https://search.ci.kubevirt.io/?search=Usage%3A+bazel+%3Ccommand%3E+%3Coptions%3E&maxAge=336h&context=3&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by dhiller** [comment]
See https://github.com/kubevirt/kubevirt/pull/5914

**Comment by dhiller** [comment]
@enp0s3 do you still have objections here?

**Comment by enp0s3** [comment]
> @enp0s3 do you still have objections here?

@dhiller Thank you for the notification. unholded

**Pull request merged**
