### PR TITLE
rpm: Update virtualization packages

### PR DESCRIPTION
**Pull request by andreabolognani**
**What this PR does / why we need it**:

Update virtualization packages. Specifically:

* QEMU (7.1.0 → 7.2.0)
* libvirt (8.10.0 → 9.0.0)
* SeaBIOS (1.16.0 → 1.16.1)
* EDKII (20220826 → 20221207)
* passt (20221026 → 20221110)
* virtiofsd (1.4.0 → 1.5.0)
* swtpm (0.7.0 → 0.8.0)

**Release note**:

```release-note
This version of KubeVirt includes upgraded virtualization technology based on libvirt 9.0.0 and QEMU 7.2.0.
Each new release of libvirt and QEMU contains numerous improvements and bug fixes.
```

### CODE REVIEW

**Comment by andreabolognani** [comment]
@rmohr please take a look at the commit "[rpm: Manually fix URL for passt package](https://github.com/kubevirt/kubevirt/pull/9159/commits/0c4f51eecaa5a274036d073931082b8f121e214c)". Is this something that we can address in bazeldnf?

**Comment by andreabolognani** [comment]
Note that the PR is currently marked as draft because libvirt 9.0.0 is not available in CentOS Stream 9 yet. That should hopefully change next week :)

**Comment by rmohr** [comment]
> @rmohr please take a look at the commit "[rpm: Manually fix URL for passt package](https://github.com/kubevirt/kubevirt/pull/9159/commits/0c4f51eecaa5a274036d073931082b8f121e214c)". Is this something that we can address in bazeldnf?

Yes definitely. Is the package pinned? If not, we should fix it very soon, because we could break automatic version bumps of the unpinned packages.

**Comment by andreabolognani** [comment]
> Yes definitely.

So we would just always generate fully escaped URLs? That sounds like a good idea in general.

I haven't looked at the logic handling this, so I'm unclear on how much of the generated URL is assembled by bazeldnf from smaller building blocks and how much is taken verbatim from other sources such as the repository's repodata files.

> Is the package pinned? If not, we should fix it very soon, because we could break automatic version bumps of the unpinned packages.

It is pinned.

Moreover, the third-party repository that's currently used is somehow not triggering the issue. I think that might be because its baseurl already contains an escaped caret.

**Comment by andreabolognani** [comment]
A libvirt 9.0.0 build has made its way into CentOS Stream 9 composes, so there's no longer anything (that I'm currently aware of ;) preventing this from being merged.

**Comment by andreabolognani** [comment]
The bazel issue with the passt URL was no longer showing up locally, so I figured I'd drop the corresponding commit and see whether CI would be okay with that. Well, it was not :(

**Comment by andreabolognani** [comment]
The fossa test is failing but it seems to be unrelated to my changes. Everything else is green.

Anyone willing to lgtm/approve?

**Comment by alicefr** [comment]
/lgtm

This also fixed `make rpm-deps` as the `edk-ovmf` package version is outdated and it fails to check it from the centos repo

**Comment by andreabolognani** [comment]
Thanks a lot @alicefr @rmohr :)

Any ideas about the FOSSA job? Should we just try running it again, see whether it succeeds this time around?

**Comment by xpivarc** [comment]
> Thanks a lot @alicefr @rmohr :)
> 
> Any ideas about the FOSSA job? Should we just try running it again, see whether it succeeds this time around?

It is not a required job and is a known issue. Unfortunately.

**Pull request merged**
