### PR TITLE
README: Update K8s version

### LINKED ISSUE #3393: README: Align the cluster commands with updated Kubernetes versions
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**: I am newbie trying to find my way around this project. I was looking through [Getting Started Guide](https://github.com/kubevirt/kubevirt/blob/master/docs/getting-started.md#compile-and-run-it) and I think the below command has been bumped up to `k8s-1.15`.
```
export KUBEVIRT_PROVIDER=k8s-1.13.3 # this is also the default if no KUBEVIRT_PROVIDER is set
```
The error I am getting is:
`./cluster-up/up.sh: line 12: /home/animesh/kubervirt/kubevirt/cluster-up//cluster/k8s-1.13.3/provider.sh: No such file or directory
`

**What you expected to happen**:
Successfully run the commands.

**How to reproduce it (as minimally and precisely as possible)**:
Follow [this](https://github.com/kubevirt/kubevirt/blob/master/docs/getting-started.md#compile-and-run-it) section of the Getting Started guide.

**Anything else we need to know?**:
I think similar doc changes are needed inside the directories as well. e.g.
https://github.com/kubevirt/kubevirt/tree/master/cluster-up/cluster/k8s-1.14

I would like to work on this issue :)

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by animeshk08**
This commit updates K8s version in getting started
and respective cluster doc.

Signed-off-by: Animesh Kumar <animuz111@gmail.com>

**What this PR does / why we need it**:
Updates K8s version to based on the updated images.
This is in response to this commit: https://github.com/kubevirt/kubevirt/commit/ca350eb9ee10f320181ec158257dd982068543cf
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3393

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
Hi @animeshk08, thanks for your work!

Unfortunately the contents of `cluster-up` folder in this project are vendored in from the https://github.com/kubevirt/kubevirtci/tree/master/cluster-up folder. So, in order to get these changes in, you can move the changes on that folder into a PR against kubevirt/kubevirtci, and when that got merged, to use the `bump-kubevirtci` make target in this project.

**Comment by dhiller** [comment]
One other thing I noted is that you always should run `make generate` before pushing your changes: https://travis-ci.org/github/kubevirt/kubevirt/builds/686420642#L2497

**Comment by animeshk08** [comment]
Hi @dhiller, Thank you so much for the help. I will open a PR at KubeVirt CI :)

**Comment by davidvossel** [comment]
ha, and @dhiller already said everything i just said, oops. I should have read the comments.

**Comment by rmohr** [comment]
Looks like this one can be close?

**Pull request closed without merging**
