### PR TITLE
Fixes migration controller null pointer dereference

### PR DESCRIPTION
**Pull request by davidvossel**
If a migration object transistions to "Failed" before being handed off to virt-controller, it's possible that we'll attempt to access the vmi.Status.MigrationState when it's an uninitialized null pointer.  This can happen for example if the target pod fails during execution before the handoff, or if the target pod is somehow deleted before the handoff.

The result is that virt-controller can get into a situation where it crash loops until the effected migration object is removed from the cluster.

```release-note
Fixes null pointer dereference in migration controller
```

### CODE REVIEW

**Review by enp0s3 — COMMENTED** [review]
@davidvossel Great catch! 
There is some issue with the migration unit tests though. Trying to find out the root cause. Can you please take a look?

**Comment by enp0s3** [comment]
> @davidvossel Great catch!
> There is some issue with the migration unit tests(I've reproduced the fails locally using this PR as a rebase). Trying to find out the root cause. Can you please take a look?

@davidvossel OK I think that we probably should not expect the VMI to be patched while `VMI.status.MigrationState` is `nil`, in the unit tests.

**Review by stu-gott — COMMENTED** [review]
/approve

**Comment by davidvossel** [comment]
/hold

looking into unit tests

**Comment by davidvossel** [comment]
/hold cancel

Thanks @enp0s3, the unit test were indeed failing. Odd that CI didn't catch this  though. I've fixed the tests and improved how we validate the patch contents in the tests as well.

**Review by stu-gott — COMMENTED** [review]
/lgtm

**Comment by maya-r** [comment]
This PR seems to cause goveralls to fail

**Pull request merged**
