### PR TITLE
Update bazel version and bazel python rules

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

Updates the bazel version to latest 4.2.1 in codebase and builder image, and uses the new builder image. Also updates python rules.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
Required for kubevirt/project-infra#1528

**Comment by dhiller** [comment]
> /lgtm
> /approve
> 
> Do we already pre-pull this bazel version in our bootstrap images?

No, I don't think so.

**Comment by fgimenez** [comment]
> > Do we already pre-pull this bazel version in our bootstrap images?
> 
> No, I don't think so.

Will be done here https://github.com/kubevirt/project-infra/pull/1546

**Pull request merged**
