### PR TITLE
[Testing] polarion match for service account test

### PR DESCRIPTION
**Pull request by mfranczy**
Signed-off-by: Marcin Franczyk <mfranczy@redhat.com>

**What this PR does / why we need it**:
Polarion match for service account tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by mfranczy** [comment]
ci test please

**Comment by mfranczy** [comment]
@ILpinto did you see my comment about merging polarion tests?

**Comment by ILpinto** [comment]
@mfranczy no,

**Comment by mfranczy** [comment]
ci test please

**Comment by vladikr** [comment]
ci test please

**Comment by stu-gott** [comment]
ci test please

**Comment by mfranczy** [comment]
because of some reasons `ci test please` didn't work for travis, I re-run travis tests manually, looks good now, failing tests are not related.

**Pull request merged**
