### PR TITLE
Pull in latest CI cluster

### PR DESCRIPTION
**Pull request by slintes**
**What this PR does / why we need it**:

Pull in latest CI cluster with

- increased pod limit on os clusters to 110
- updated local volume provisioner
- new OKD 4.1.2 provider
- audit logging enabled
- some fixes and additions to gocli

For a complete list see https://github.com/kubevirt/kubevirtci/commits/master

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
/lgtm
/approve

Let's see if our retester can handle this.

**Comment by rmohr** [comment]
hm, a `make generate` missing.

**Comment by cynepco3hahue** [comment]
@slintes We have some issue with the local provisioner
```
+ grep -v Running
local-volume-provisioner-5ddd8   0/1       CrashLoopBackOff   7         14m
```

**Comment by rmohr** [comment]
/hold

let's stop testing until this is resolved

**Comment by slintes** [comment]
@rmohr I also see several tests timing out again. Is that an issue with the CI servers (are they getting slower for some reason), or should we increase timeout again?

**Comment by slintes** [comment]
I don't see the cri-o issue locally with the CI image of today...
```
$ k get pod
NAME                             READY   STATUS    RESTARTS   AGE
...
local-volume-provisioner-wvpg7   1/1     Running   0          5h
```
will update to the latest cluster-up version...

**Comment by cynepco3hahue** [comment]
@slintes @rmohr I hope it does not some flaky issue that will appear and disappear :confused:

**Comment by rmohr** [comment]
/override pull-kubevirt-e2e-os-3.11.0-crio

Results look good.

**Comment by slintes** [comment]
this test was still running, and when it failed, it overrode the override...

/override pull-kubevirt-e2e-os-3.11.0-crio

**Pull request merged**
