### PR TITLE
VM unit tests, remove informers

### PR DESCRIPTION
**Pull request by xpivarc**
### What this PR does
Remove informers in order to simplify test setup. This also improve test runtime from ~15 seconds down to ~0.2 seconds.

Fixes #

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by fossedihelm — COMMENTED** [review]
The only disadvantage I see is that we are going a little bit far from converting the test package from `package watch` to `package watch_test`.
But great work!
/lgtm

**Comment by fossedihelm** [comment]
/hold
unit test failure is relevant

**Comment by xpivarc** [comment]
@fossedihelm PTAL

**Review by fossedihelm — APPROVED** [review]
Unit test failure seems unrelated

**Comment by xpivarc** [comment]
/hold cancel
Rebased

**Pull request merged**
