### PR TITLE
Fix rpm dependency chaos for test images

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Remove all manually managed RPMs for testing. Instead the dependencies can be resolved upfront and the WORKSPACE file will be automatically updated. livirt dependencies stay for now and will be handled in a separate PR.
The biggest benefit is easy on-the-fly update of all dependencies in an individual PR, as well as much much simpler flows for integrating new architectures in kubevirt.

https://github.com/kubevirt/kubevirtci/tree/master/cluster-provision/images/kubevirt-testing can be deprecated once this is merged.

Run

```
make rpm-deps
```

to update RPM dependencies to the latest state.

Modify `repo.yaml` to use different fedora or copr versions or different architectures. Initially it looks like this:

```yaml
repositories:
- arch: x86_64
  metalink: https://mirrors.fedoraproject.org/metalink?repo=fedora-32&arch=x86_64
  name: 32-x86_64-primary-repo
- arch: x86_64
  metalink: https://mirrors.fedoraproject.org/metalink?repo=updates-released-f32&arch=x86_64
  name: 32-x86_64-update-repo
- arch: ppc64le
  metalink: https://mirrors.fedoraproject.org/metalink?repo=fedora-32&arch=ppc64le
  name: 32-ppc64le-primary-repo
- arch: ppc64le
  metalink: https://mirrors.fedoraproject.org/metalink?repo=updates-released-f32&arch=ppc64le
  name: 32-ppc64le-update-repo

```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

More background can be found at https://github.com/rmohr/bazeldnf.

In short, `bazeldnf` does:
 * introducing a `rpmtree` target, which is not much more than just a bundle of RPMs converted into single tar archives. It can be used for instance as a container-layer, or as a source for required headers or libraries.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
@alicefr FYI
/cc @maya-r 
/cc @davidvossel

**Comment by maya-r** [comment]
Somewhat meaningless since you will have to fix the lanes first, but
/lgtm

**Comment by rmohr** [comment]
> Somewhat meaningless since you will have to fix the lanes first, but

:+1: Let's see how it goes now.

**Review by davidvossel — COMMENTED** [review]
/approve

can you add a brief md in the docs section or something people can reference to understand how this tooling works?

In general I know it's pretty straight forward. In most cases someone simply adds a package to the list in hack/rpms-deps.sh or adds a repo to repo.yaml. What i'm looking for is a document that briefly explains how to make changes here and generally what's happening behind the scenes with pulling the rpms, caching, and generating the WORKSPACE

basically a quick reference because (speaking for myself) i'm going to forget how this works in half a year when I have to alter something.

**Comment by rmohr** [comment]
> can you add a brief md in the docs section or something people can reference to understand how this tooling works?

Done: https://github.com/kubevirt/kubevirt/pull/4710/files#diff-239d842db248236a96e77231a4c97e7daa7f77b540191c56e433ae4ede9712f2

Tests look good to.

**Review by davidvossel — APPROVED** [review]
/lgtm

excellent work

**Pull request merged**
