### PR TITLE
make VMs ping each other and not themselves

### PR DESCRIPTION
**Pull request by alonSadan**
**What this PR does / why we need it**:
The Vms using pingThroughSriov should ping each other,
but they are pinging themselves. This PR fixes that.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by alonSadan** [comment]
@phoracek I saw you touched this code recently. 
Is this correct or I am missing something?

**Comment by phoracek** [comment]
/lgtm

Ooof, stupid me... :D

**Comment by AlonaKaplan** [comment]
/lgtm

Will approve when I will see the sriov lane passing - https://prow.apps.ovirt.org/?author=alonSadan&job=pull-kubevirt-e2e-kind-1.17-sriov

**Comment by alonSadan** [comment]
@AlonaKaplan 
Thanks:)

**Pull request merged**
