### PR TITLE
[release-0.49]: Bugfix: virt-handler socket leak

### PR DESCRIPTION
**Pull request by iholder101**
**What this PR does / why we need it**:
Manual backport of https://github.com/kubevirt/kubevirt/pull/9003.

The only "interesting" commit here is https://github.com/kubevirt/kubevirt/pull/9016/commits/4b99d99b16b93e07e51f61b87898a17d7c589754.

**Release note**:

```release-note
Bugfix: virt-handler socket leak
```

### CODE REVIEW

**Comment by iholder101** [comment]
/cc @Barakmor1 @enp0s3

Can you please take a look?

**Comment by iholder101** [comment]
Added a `make generate` commit like I did e.g. in https://github.com/kubevirt/kubevirt/pull/9006

**Review by enp0s3 — APPROVED** [review]
/approve

**Pull request merged**
