### PR TITLE
kubevirtci: Bump to 8f48705

### LINKED ISSUE #4961: periodic-kubevirt-e2e-k8s-prev #1356519903128981504 — Storage Starting a VirtualMachineInstance [rfe_id:2288][crit:high][vendor:cnv-qe@redhat.com][level:component] With Cirros BlockMode PVC [test_id:1015] should be successfully started
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/triage build-watcher

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1356519903128981504

```
tests/storage_test.go:826
Timed out after 90.000s.
Timed out waiting for VMI testvmi-vlwww to enter [Running] phase(s)
Expected
    <v1.VirtualMachineInstancePhase>: Scheduling
to be an element of
    <[]interface {} | len:1, cap:1>: [["Running"]]
tests/utils.go:2813
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
* Use default values for node cidr mask size (#565)
* Add option to deploy Istio service mesh (#536)
* Use calico 3.17 for k8s-1.17 (#561)
* Activate dual stack again (#558)
* Bump calico to v3.18.0 (#555)
* Run bazelisk run //robots/kubevirtci-bumper:kubevirtci-bumper -- -ensure-last-three-minor-of v1 --k8s-provider-dir /home/prow/go/src/github.com/kubevirt/project-infra/../kubevirtci/cluster-provision/k8s (#548)
* Move k8s 1.20 to crio CE (#541)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4961 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by phoracek — APPROVED** [review]
/lgtm

**Review by EdDev — COMMENTED** [review]
I think it worth mentioning what else you bring in from kubevirtci.

The subject should be the bump and the content what is included in it, obviously it is not only the CIDR change (per what I see with the ISTIO).

**Comment by qinqon** [comment]
/hold

I still see
```
E0312 02:59:28.202205       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 02:59:28.203235       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 02:59:28.218636       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 02:59:28.218950       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 02:59:28.224800       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 02:59:28.224855       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 02:59:28.516650       1 disruption.go:505] Error syncing PodDisruptionBudget kubevirt-test-default1/kubevirt-disruption-budget-pbm7t, requeuing: Operation cannot be fulfilled on poddisruptionbudgets.policy "kubevirt-disruption-budget-pbm7t": StorageError: invalid object, Code: 4, Key: /registry/poddisruptionbudgets/kubevirt-test-default1/kubevirt-disruption-budget-pbm7t, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 8d276568-d44d-41c8-821a-61887616214d, UID in object meta: 
E0312 02:59:32.596047       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 02:59:32.596760       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 02:59:57.798893       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 02:59:57.799324       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 02:59:57.899281       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 02:59:57.900134       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 02:59:57.911033       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 02:59:57.911356       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 03:00:19.961330       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 03:00:19.962390       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 03:01:43.839987       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 03:01:43.841641       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 03:03:01.041232       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 03:03:01.042333       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 03:03:43.471174       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 03:03:43.472031       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 03:05:13.126237       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 03:05:13.128543       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 03:05:58.851969       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 03:05:58.854739       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 03:05:58.875019       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 03:05:58.875306       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"
E0312 03:05:58.890346       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0312 03:05:58.890680       1 event.go:291] "Event occurred" object="node02" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node node02 status is now: CIDRNotAvailable"

```

**Comment by qinqon** [comment]
/hold cancel

The bump-kubevirtci was done too early and it took old version, now the kubevirtci version is pointing to the fix.

**Review by phoracek — APPROVED** [review]
/lgtm

**Comment by qinqon** [comment]
/retest 

```
3d8be2122b76: Waiting
docker: error pulling image configuration: Get "https://quay.io/v2/kubevirt/builder/blobs/sha256:13ece1c97934b93ffe25aee6217eba25bc21301aef60f2551bf8a58f615e08bd": net/http: TLS handshake timeout.
See 'docker run --help'.
make: *** [Makefile:51: client-python] Error 125
+ EXIT_VALUE=2

```

**Review by EdDev — APPROVED** [review]

**Review by dhiller — APPROVED** [review]
/approve

**Comment by qinqon** [comment]
/retest

is still flaky

**Pull request merged**
