### PR TITLE
[release-0.41] Generate ISO images 4k aligned for node storage with 4k blocksize

### PR DESCRIPTION
**Pull request by enp0s3**
Manual cherry-pick of [#5806](https://github.com/kubevirt/kubevirt/pull/5806)

Signed-off-by: Igor Bezukh <ibezukh@redhat.com>

Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1976730

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by rmohr — CHANGES_REQUESTED** [review]
@enp0s3 I think you will also have to pull in https://github.com/kubevirt/kubevirt/pull/5990 or some tests will be flaky under certain circumstances.

**Comment by enp0s3** [comment]
https://github.com/kubevirt/kubevirt/pull/6158

> @enp0s3 I think you will also have to pull in #5990 or some tests will be flaky under certain circumstances.

@rmohr Thank you. I've created #6158

**Comment by enp0s3** [comment]
/hold
Let's wait till #6184 will land. It should resolve the flakiness of `test_id:5004`

**Comment by enp0s3** [comment]
/override pull-kubevirt-e2e-k8s-1.18

`test_id:5004` and `test_id:1663` were quarantined in main branch. I've ran them locally with the PR rebase and they have passed. In addition, this PR merged in main and didn't affect these tests stability. Therefore I will override the lane.

**Comment by enp0s3** [comment]
/unhold
Since this is an important fix for the cases where the nodes are using 4k block size storage, I will unhold the PR and will take care about backporting tests stability PRs in parallel to this PR.

**Pull request merged**
