### PR TITLE
add critical-pod annotation for pods

### PR DESCRIPTION
**Pull request by shiywang**
Fixes: https://github.com/kubevirt/kubevirt/issues/1149
Signed-off-by: Shiyang Wang <shiywang@redhat.com>

### CODE REVIEW

**Comment by fabiand** [comment]
ok to test

**Comment by fabiand** [comment]
Thanks!

Let's see what the CI says.

**Comment by fabiand** [comment]
@yanirq doyou mind opening an issue for the priorities?

**Comment by yanirq** [comment]
> @yanirq doyou mind opening an issue for the priorities?
@fabiand  It depends , if we/dscheduler project decide to add a scoring mechanism for load balancing which will utilize pod priority for rescheduling decisions then it would make sense.
Its not handled yet.

**Pull request merged**
