### PR TITLE
Remove quarantine 3189

### PR DESCRIPTION
**Pull request by brybacki**
**What this PR does / why we need it**:

Tests 3189 and 5252 are stable for two weeks since the fix. Remove quarantine. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

This was originally fixed by: https://github.com/kubevirt/kubevirt/pull/5613

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by enp0s3 — APPROVED** [review]
/approve

**Comment by brybacki** [comment]
@mhenriks can you approve?

**Pull request merged**
