### PR TITLE
Allow `kubevirt:default` clusterRole to get,list kubevirts

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
Kubevirt resource is in category all.
`kubectl get all` or `virtctl permitted-devices` fails if
the user don't have the permissions to list Kubevirt resource.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] ~Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required~
- [ ] ~PR: The PR description is expressive enough and will help future contributors~
- [ ] ~Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)~
- [ ] ~Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)~
- [ ] ~Upgrade: Impact of this change on upgrade flows was considered and addressed if required~
- [ ] ~Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test~
- [ ] ~Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.~
- [ ] ~Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered~

**Release note**:

```release-note
Allow `kubevirt.io:default` clusterRole to get,list kubevirts
```
/cc @acardace

### CODE REVIEW

**Review by orelmisan — COMMENTED** [review]
Thank you @fossedihelm 
Which persona uses this ClusterRole? Is it a non-cluster admin persona?
If so, IIUC this change could expose cluster-wide configuration to a non-admin user.

**Comment by acardace** [comment]
> Thank you @fossedihelm Which persona uses this ClusterRole? Is it a non-cluster admin persona? If so, IIUC this change could expose cluster-wide configuration to a non-admin user.

It exposes the kubevirt CR in read-only mode so I think it's totally fine.

**Comment by acardace** [comment]
/approve

nice that you unexported all those vars!

**Comment by orelmisan** [comment]
> > Thank you @fossedihelm Which persona uses this ClusterRole? Is it a non-cluster admin persona? If so, IIUC this change could expose cluster-wide configuration to a non-admin user.
> 
> It exposes the kubevirt CR in read-only mode so I think it's totally fine.

Are there any confidential parameters there that regular users should not be exposed to?

**Comment by stu-gott** [comment]
/cc @davidvossel

Can you recall a historical reason that the default account wouldn't have access to the KubeVirt CR?

**Comment by oshoval** [comment]
i am just checking something, this is why i put a hold, so the lgtm wont catch
will remove both soon

/lgtm
/hold

**Comment by xpivarc** [comment]
/lgtm
/hold
Let's give one more day for @davidvossel to respond

**Pull request merged**
