### PR TITLE
virtctl/imageupload progress bar: write to stdout

### PR DESCRIPTION
**Pull request by akalenyu**
### What this PR does
We've been using an older progress bar library for ages now that defaulted to stdout:
https://github.com/kubevirt/kubevirt/pull/12184
Let's keep it that way

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — APPROVED** [review]

**Review by 0xFelix — COMMENTED** [review]
/approve

Thanks

**Comment by 0xFelix** [comment]
Can / should we add a test for the expected output by the way?

**Comment by oshoval** [comment]
> Can / should we add a test for the expected output by the way?

imho no need over testing

**Comment by 0xFelix** [comment]
The change which is being reversed with this PR went unnoticed because there were no tests.

**Comment by akalenyu** [comment]
> The change which is being reversed with this PR went unnoticed because there were no tests.

Sure thing, I'll add that
/hold

**Comment by oshoval** [comment]
> The change which is being reversed with this PR went unnoticed because there were no tests.

Still, i think that some tests are born due to a bug,
if there was no bug in the original development, they were not added
in this case i think that each test should be considered if this code is prone for changes / part of the core
or not, 
in this case i think it is not one of those, hence the fact there was a bug doesnt merit a test imho

**Review by 0xFelix — APPROVED** [review]
/lgtm

Not allowed to approve in `tests/storage`.

**Review by xpivarc — COMMENTED** [review]
/approve

**Review by aglitke — COMMENTED** [review]
/lgtm

**Pull request merged**
