### PR TITLE
e2e: Move privileged pods to privileged ns

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
Currently RenderPrivilegedPod() that creates privileges pods in the test suite, is created under the default test namespace. In order to conform with PSA, this PR is moving these pods to dedicated namespace with dedicated PSA privileges.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by RamLavi** [comment]
if CI goes smoothly, I'll try to reintroduce the custom reporters

**Comment by jean-edouard** [comment]
@RamLavi please review https://github.com/kubevirt/kubevirt/pull/8649
I believe most, if not all of the fixes in this PR are already implemented there.
Thanks!

**Pull request closed without merging**
