### PR TITLE
fix: execution order of multiple sidecars

### LINKED ISSUE #11940: Can't control the execution order of multiple hook sidecars
**What happened**:

I've noticed the **Priority** field in the response of the Info service, which can be used for sorting. However, currently, sortCallbacksPerHookPoint sorts based on the **HookPoint** rather than **callBackClient**.

**What you expected to happen**:
Sort callBackClients based on the Priority field of HookPoint.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.0
- Kubernetes version (use `kubectl version`): v1.29.3
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by go-bai**
### What this PR does
Before this PR: Can't control the execution order of multiple hook sidecars

After this PR: Can control the execution order of multiple hook sidecars

Fixes #11940

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
fix: execution order of multiple sidecars
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
/cc @victortoso 
Can you have a look? I  am not totally convinced of these changes. Thanks

**Comment by victortoso** [comment]
[Suggested](https://github.com/kubevirt/kubevirt/issues/11940#issuecomment-2120166717) to add a comment in the design proposal so we can set expectations and validate expected behavior

**Comment by fs185143** [comment]
/reopen

this is still an issue in kubevirt v1.8.2. we would like our sidecar to run _after_ the passt container.

**Comment by fs185143** [comment]
@victortoso what's the latest on this?

**Pull request closed without merging**
