### PR TITLE
instancetype, virt-controller: Clean up CRs after expand

### LINKED ISSUE #13117: `ControllerRevisions` not removed when using `InstancetypeReferencePolicy` `Expand` or `ExpandAll`
/area instancetype

**What happened**:

$subject, these currently remain even after the `VirtualMachine` has been expanded and successfully updated.

**What you expected to happen**:

These `ControllerRevisions` should be removed once the `VirtualMachine` is successfully updated.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a `VirtualMachine` using an instance type and/or preference
* Confirm that `ControllerRevisions` have been created 
* Enable the `Expand` or `ExpandAll` `InstancetypeReferencePolicy` within the `KubeVirt` CR.
* Confirm that `ControllerRevisions` still exist
* 
**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype

### What this PR does

Once we have successfully expanded and updated the VirtualMachine we should ensure any instance type or preference ControllerRevisions are removed from the cluster.

Fixes #13117

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by lyarwood** [comment]
/cc @vladikr 
/cc @akrejcir 

A simple follow up fix for the `instancetypeReferencePolicy` implementation in 1.4 if you have time to review.

**Review by 0xFelix — APPROVED** [review]
/approve

**Pull request merged**
