### PR TITLE
[Migration Policies]: Move helper functions out of API package & stop using "LabelSelector"

### PR DESCRIPTION
**Pull request by iholder-redhat**
**What this PR does / why we need it**:
After this PR:
1. Helper methods for migration policies will be moved away from API package
2. Instead of using [LabelSelector](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L1182) (whish is essentially a struct with `map[string]string` field for matching labels and `[]LabelSelectorRequirement` for requirements), now the selectors are defined to be `map[string]string`, without the requirements part, as it is now being ignored.

This PR addresses [these comments](https://github.com/kubevirt/kubevirt/pull/7322#pullrequestreview-919007432), see them for more info.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder-redhat** [comment]
> Thanks @iholder-redhat This PR merely improves the code quality and doesn't change the logic. /approve
> 
> /cc @xpivarc please take a look as well.

@xpivarc ping

**Comment by xpivarc** [comment]
> Thanks @iholder-redhat This PR merely improves the code quality and doesn't change the logic. /approve
> 
> /cc @xpivarc please take a look as well.

@vladikr  This does change the API, right?

**Comment by iholder-redhat** [comment]
> > Thanks @iholder-redhat This PR merely improves the code quality and doesn't change the logic. /approve
> > /cc @xpivarc please take a look as well.
> 
> @vladikr This does change the API, right?

Let me explain.
Previously we used `metav1.LabelSelector` as the type for label selectors. The struct has two fields and is defined in the following way (I've removed json metadata & comments for clarity):
```go
type LabelSelector struct {
	MatchLabels map[string]string
	MatchExpressions []LabelSelectorRequirement
}
```

Currently, the "MatchExpressions" field is ignored. So it is part of the API, but a part that is redundant and should be deleted. IOW this change does not add any capabilities or anything like that, just protects the user from using something that would later be completely ignored.

Also, I'd like to stress out that this package is `v1alpha1`, which means that by definition its API is not stable yet.

**Comment by xpivarc** [comment]
> > > Thanks @iholder-redhat This PR merely improves the code quality and doesn't change the logic. /approve
> > > /cc @xpivarc please take a look as well.
> > 
> > 
> > @vladikr This does change the API, right?
> 
> Let me explain. Previously we used `metav1.LabelSelector` as the type for label selectors. The struct has two fields and is defined in the following way (I've removed json metadata & comments for clarity):
> 
> ```go
> type LabelSelector struct {
> 	MatchLabels map[string]string
> 	MatchExpressions []LabelSelectorRequirement
> }
> ```
> 
> Currently, the "MatchExpressions" field is ignored. So it is part of the API, but a part that is redundant and should be deleted. IOW this change does not add any capabilities or anything like that, just protects the user from using something that would later be completely ignored.
> 
> Also, I'd like to stress out that this package is `v1alpha1`, which means that by definition its API is not stable yet.

I understand I just want confirmation from Vladik as it wasn't clear from the comment.
Otherwise
/lgtm
/hold

**Comment by vladikr** [comment]
Thank @xpivarc!
/unhold

**Pull request merged**
