### PR TITLE
Pod Security Admission/Standards

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:

Adjust components to satisfy PSA. Not all components can be adjusted. The primary problem is virt-handler that is by design privileged and therefore the installed namespace will never satisfy the restricted policy. It is still good practice for our components to try to satisfy these policies.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by fabiand** [comment]
In order to meet the restrictions on the namespace level, could we introduce a new namespace which is holindg our privileged components - like handler?

A naive approach could be to simply take the currently defined namespace, and derive the new one by suffixing the current one with `-privileged`, this new namespace can then have different restrictions.

**Comment by xpivarc** [comment]
/close
Done in https://github.com/kubevirt/kubevirt/pull/8436

**Pull request closed without merging**
