### PR TITLE
update doc about ssh method usage

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:
I am using the ssh way to test but actually it's `kind`, so we need change doc about this
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by slintes** [comment]
Hey @jichenjc, thanks for rising this :+1: 
Actually I think we should update the doc to use `cluster-up/ssh.sh <nodename>` for all clusters. Only the node names differ depending on cluster type (kubernetes/openshift, kind, okd). You can get the node names with `cluster-up/kubectl.sh get nodes`. This should also work for kind. Can you give it a try and update the doc with this please?

**Comment by jichenjc** [comment]
@slintes I updated according to your suggestion :)

**Comment by slintes** [comment]
Thanks a lot, looks good now!

/lgtm
/approve

**Comment by slintes** [comment]
tide queue is empty, will merge manually (doc change only)

**Pull request merged**
