### PR TITLE
Deprecate mediatedDevicesTypes in favor of mediatedDeviceTypes

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes RHBZ#2054863

**Special notes for your reviewer**:

**Release note**:

```release-note
CR option mediatedDevicesTypes is deprecated in favor of mediatedDeviceTypes
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
Thanks @jean-edouard I am wondering if, for consistency, we should also rename `NodeMediatedDeviceTypesConfig` to `NodeMediatedDevicesTypesConfig`.
Also, I think that we can update the test https://github.com/kubevirt/kubevirt/blob/85575d0fad2e6a30bccfa39d0f2fdae14c525d5c/tests/mdev_configuration_allocation_test.go#L234 with the new field.
Thanks

**Comment by jean-edouard** [comment]
> Thanks @jean-edouard I am wondering if, for consistency, we should also rename `NodeMediatedDeviceTypesConfig` to `NodeMediatedDevicesTypesConfig`. Also, I think that we can update the test
> 
> https://github.com/kubevirt/kubevirt/blob/85575d0fad2e6a30bccfa39d0f2fdae14c525d5c/tests/mdev_configuration_allocation_test.go#L234
> 
> with the new field.
> Thanks

Good point. In that case, I think I'll rename `MediatedDevicesTypes` to `MediatedDeviceTypes` instead. It makes more grammatical sense anyway.
I initially thought renaming `NodeMediatedDeviceTypes` to `NodeMediatedDevicesTypes` would be less invasive, but it ends up being a similar in size because of that additional struct.

**Comment by jean-edouard** [comment]
@fossedihelm done, PTAL!
@vladikr please let me know if there's an issue with making mediatedDevice(s)Types optional

**Review by fossedihelm — COMMENTED** [review]
@jean-edouard There is a leftover in `tests/mdev_configuration_allocation_test.go:239` where `MediatedDevicesTypes` is still used.
Everything else seems to me to be correct. Thanks

**Comment by jean-edouard** [comment]
> @jean-edouard There is a leftover in `tests/mdev_configuration_allocation_test.go:239` where `MediatedDevicesTypes` is still used. Everything else seems to me to be correct. Thanks

Nice catch, thanks, fixed!

**Comment by fossedihelm** [comment]
/lgtm
Thanks

**Pull request merged**
