### PR TITLE
Fix virtctl expose

### LINKED ISSUE #1273: virtctl export not allow string for target-port
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Cant create a target-port with a string value with the virtctl expose command

```
virtctl.sh expose vmi vmi-ephemeral --port=5555 --target-port=http --name=myvm-ssh
invalid argument "http" for "--target-port" flag: strconv.ParseInt: parsing "http": invalid syntax
```

**What you expected to happen**:
```
Service myvm-ssh successfully exposed for vmi vmi-ephemeral
```

**How to reproduce it (as minimally and precisely as possible)**:
just run the command

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by SchSeba**
**What this PR does / why we need it**:
 Change the virtctl expose target-port variable to be string an not interger
  
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1273

**Special notes for your reviewer**:
Also change: 
VM -> VMI 
OVM -> VM 
VMRS -> VMIRS

**Release note**:

```release-note
Change virtctl expose target-port from int to string
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/1280)

### CODE REVIEW

**Comment by davidvossel** [comment]
ok to test

**Comment by SchSeba** [comment]
@davidvossel I think the failing checks or not relevant to the PR can you take a look please?

**Comment by davidvossel** [comment]
retest this please

**Comment by SchSeba** [comment]
> I understand that the actual translation of name to port is done inside the k8s service creation code?
what kind of error do we get when we pass an unknown string? will we get service creation failure in the virtctl call?

You don't get any error.
There is no unknown string.

This will create a service with the target-port name, if there is no match port name in the pod the target port on the service will be empty.

Also the service will auto update if you create a pod with the right port name.

**Comment by yuvalif** [comment]
Could you add a test for that?
If target-port is empty,  i think that it is assumed to be the same as the "port".  So, if "port" is set to something else than "80" the overall test should show no connectivity - but this will be tricky to debug :-(

**Comment by vladikr** [comment]
It still looks good to me. There were no objections in the past 8 days, so I'll merge.
Thanks @SchSeba !

**Pull request merged**
