### PR TITLE
[release-0.49] Avoid required uid/gid 0 for libguestfs pod

### PR DESCRIPTION
**Pull request by alicefr**
Simplify the libguestfs pod creation without setting the uid/gid and
relying on k8s defaults.

In order to correctly set the permissions to the directories needed by
libguestfs, we use by an emptydir volume for all the directory where
libguestfs writes.

Signed-off-by: Alice Frosi <afrosi@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

- Cherry pick of https://github.com/kubevirt/kubevirt/pull/7594

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by alicefr** [comment]
@xpivarc can you have a quick look? It is the same as https://github.com/kubevirt/kubevirt/pull/7594 I just needed to fix manually one import for the tests

**Review by maiqueb — APPROVED** [review]
Thank you.

**Comment by alicefr** [comment]
hi @jean-edouard, could you please have a quick look to this PR and approve it? Many thanks

**Review by jean-edouard — APPROVED** [review]
/approve

**Pull request merged**
