### PR TITLE
VMI CRD validation with OpenAPI v3 schema

### PR DESCRIPTION
**Pull request by nunnatsa**
### What this PR does
Move many VMI validation from the validating webhook, to the CRD, using [OpenAPI v3 schema](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject)

See [here](https://book.kubebuilder.io/reference/markers/crd-validation) for more info.

Continue the CRD validation started at #11156 

Before this PR:
Many simple validation are done in the webhook logic

After this PR:
These validations are now done by the api-server, according to the CRD.

Many field are now validated by the CRD:
* firmware.Serial
* spec.domain.devices.inputs
* spec.Domain.IOThreadsPolicy
* disk name duplication
* volume name duplication
* sound device
* interface
* CPU feature policy

### Checklist
This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Removed many vmi validation to the CRD, using OpenAPI v3 schema
```

### CODE REVIEW

**Review by vasiliy-ul — COMMENTED** [review]
I actually like the idea of doing the validation in the schema :+1:  Though in the previous PR https://github.com/kubevirt/kubevirt/pull/11156 some concerns were raised. From the discussion, it is not fully clear if those have been addressed. Are we okay with going forward here?

**Review by orelmisan — COMMENTED** [review]
Thank you for the PR @nunnatsa.
Is there a way (other than adding e2e tests) to test the generated schema?

**Comment by nunnatsa** [comment]
@orelmisan - Not sure we need to retest K8s mechanisms

**Comment by orelmisan** [comment]
> @orelmisan - Not sure we need to retest K8s mechanisms

I'm not talking about the K8s mechanism.
For example, lets assume that some field is validated using a regex.
How or where do we validate the correctness of the regex against several test cases?

**Comment by nunnatsa** [comment]
You have a point regarding regex. In this specific PR, I just copied the regex from the code, as is

**Comment by nunnatsa** [comment]
Last commit adds unit test to make sure the CRD validation is working.

**Review by orelmisan — COMMENTED** [review]
The addition of unit tests to the CRD is awesome.
Please consider moving it to the beginning of the PR, so it would be easier to compare each test removed from the webhook vs the new test added against the CRD schema.

**Pull request closed without merging**
