### PR TITLE
Fix bug in restore-controller when creating a restore PVC with both dataSource and dataSourceRef

### PR DESCRIPTION
**Pull request by alromeros**
**What this PR does / why we need it**:

With the [dataSourceRef API inclusion](https://kubernetes.io/blog/2021/08/30/volume-populators-redesigned/) in k8s v1.22, a new validation mechanism was added for PVCs ensuring that, if present, both the dataSource and dataSourceRef fields must be equal.

This behavior conflicts with the restore-controller, which creates the restore PVC using the source spec as a reference, but overwriting the dataSource field. If the source PVC has a populated dataSourceRef field, just overwriting the dataSource triggers the validation error.

This Pull Request aims to modify this behavior, so both dataSource and dataSourceRef are overwritten.

**Which issue(s) this PR fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2128872

**Special notes for your reviewer**:
In order to replicate the bug in older k8s versions (v1.18-v1.23), the `AnyVolumeDataSource` feature gate needs to be enabled in kube-apiserver. This feature gate is enabled by default in newer versions.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by akalenyu — COMMENTED** [review]
Awesome!

I think you could have even reduced the tests to `VMRestore of already "restored" (i.e. PVC that was created from a dataSource) PVC` but definitely a wider cover with the included cloning mechanism.
More info on the validation logic is described here btw:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#data-source-references

Note that this is likely a problem on `release-0.53` as well, as that is what we ship with OpenShift 4.11 (=> k8s 1.24 where the FG is enabled by default)

/lgtm

**Comment by alromeros** [comment]
> Awesome!
> 
> I think you could have even reduced the tests to `VMRestore of already "restored" (i.e. PVC that was created from a dataSource) PVC` but definitely a wider cover with the included cloning mechanism. More info on the validation logic is described here btw: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#data-source-references
> 
> Note that this is likely a problem on `release-0.53` as well, as that is what we ship with OpenShift 4.11 (=> k8s 1.24 where the FG is enabled by default)
> 
> /lgtm

Thank you for the input! I'll wait for this PR to be merged before opening the backport PR.

**Comment by brianmcarey** [comment]
The bumped non-root lanes are stuck in expected state - triggering them now.

/test pull-kubevirt-e2e-k8s-1.24-operator-nonroot
/test pull-kubevirt-e2e-k8s-1.24-sig-compute-nonroot
/test pull-kubevirt-e2e-k8s-1.24-sig-network-nonroot
/test pull-kubevirt-e2e-k8s-1.24-sig-storage-nonroot

**Pull request merged**
