### PR TITLE
Tests: Handle various names of the qemu binary

### PR DESCRIPTION
**Pull request by vasiliy-ul**
**What this PR does / why we need it**:

Qemu binary may have different names depending on the base container
image used by virt-launcher. E.g. qemu-kvm or qemu-system-x86_64. Try
to handle that by considering also the qemu-system-* prefix when looking
through the list of running processes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

This test currently fails in our downstream CI because the qemu proccess has different name.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alicefr** [comment]
@vasiliy-ul my only concern in using only qemu as prefix is if in the future we might add other daemons that starts with qemu

**Comment by vasiliy-ul** [comment]
> @vasiliy-ul my only concern in using only qemu as prefix is if in the future we might add other daemons/process that starts with qemu.

@alicefr, I think in that case the test will fail because it will find multiple `qemu-*` processes. Then the person introducing new changes will need to extend the test to handle new names (which should be done anyway).

**Comment by vasiliy-ul** [comment]
Alternatively, it's possible to make the check explicit by comparing to `"qemu-kvm"` and `"qemu-system-x86_64"`.

**Comment by vasiliy-ul** [comment]
@alicefr, I've made the process search more strict to handle only `qemu-kvm` and `qemu-system-*`. WDYT?

**Comment by alicefr** [comment]
Thanks @vasiliy-ul 
/lgtm

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
