### PR TITLE
Return error if VMI is in Failed state when console access

### LINKED ISSUE #5360: console command stuck there if VMI is failed status
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:

```
# ./cluster-up/kubectl.sh get vmi
NAME            AGE     PHASE    IP              NODENAME
vmi-ephemeral   3h28m   Failed   10.244.140.83   node02

# ./cluster-up/virtctl.sh console vmi-ephemeral
```

the console command stuck there for long time 

**What you expected to happen**:

should report error and quit this command 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5360

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
looks good, can you add a unit test case for these changes in ```pkg/virt-api/rest/subresource_test.go``` so we dont  mess this up again in the future

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Comment by jichenjc** [comment]
```
Timed out after 1.000s.
    Expected
        <map[string]string | len:2>: {
            "cpumanager": "false",
            "kubevirt.io/schedulable": "false",
        }
    to have {key: value}
        <map[interface {}]interface {} | len:1>: {
            "kubevirt.io/schedulable": "true",
        }

    pkg/virt-handler/heartbeat/heartbeat_test.go:121
```

**Pull request merged**
