### PR TITLE
Fix coexistance of scsi and sata drives

### PR DESCRIPTION
**Pull request by mstarostik**
makeDeviceName() counted device indices by bus. But SCSI and SATA
devices share the 'sd' prefix so adding both resulted in duplicate
names.
This fixes it by counting per prefix instead of bus.

Use case: Installing Windows with a SCSI disk and SATA CDROMs for
Install medium, virtio drivers, and unattended config.

Signed-off-by: Malte Starostik <github@xodtsoq.de>

**What this PR does / why we need it**:

This makes it possible to attach both SCSI and SATA drives to a single machine.
Major use case for this is installing virtio-scsi drivers on Windows, both at setup time as well as into an imported or converted 
VM. 

Without this, such a setup fails to start with:
```server error. command SyncVMI failed: "LibvirtError(Code=27, Domain=20, Message='XML error: target 'sda' duplicated for disk sources '/var/run/kubevirt-private/vmi-disks/system/win10.img' and '/var/run/kubevirt-ephemeral-disks/disk-data/drivers/disk.qcow2'')"```

**Release note**:
```release-note
fixes a bug that prevented unique device name allocation when configuring both scsi and sata drives
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
/ok-to-test
/lgtm
Good catch!

**Comment by vladikr** [comment]
Thank @mstarostik !
Perhaps you could add a functional test as well to make sure that this is working as expected?

**Comment by mstarostik** [comment]
> Thank @mstarostik !
> Perhaps you could add a functional test as well to make sure that this is working as expected?

Done. Not sure if it's the right approach, but works for me.

**Comment by rmohr** [comment]
@mstarostik sorry for the late LGTM. Thanks again.

**Pull request merged**
