### PR TITLE
Fix typo in cluster-clean.sh: kubectl -> _kubectl

### PR DESCRIPTION
**Pull request by vasiliy-ul**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder-redhat** [comment]
Awesome, great you cached that!

BTW - do our lanes perform cluster cleaning? did you check that it works locally? just to be sure

**Comment by vasiliy-ul** [comment]
> BTW - do our lanes perform cluster cleaning? 

Dont know for sure. I think `cluster-sync` is called to deploy everything and that one includes `cluster-clean`. But AFAIK for every run a new instance is brough up with `cluster-up` hence the 'clean' part should be mostly a no-op.

> did you check that it works locally? just to be sure

Well, when I run `cluster-clean` and see that the command is executed:

```
+ _kubectl get vmsnapshots --all-namespaces -o=custom-columns=NAME:.metadata.name,NAMESPACE:.metadata.namespace,FINALIZERS:.metadata.finalizers --no-headers
+ export KUBECONFIG=/home/vulyanov/work/upstream/github/kubevirt.io/kubevirt/_ci-configs/k8s-1.20/.kubeconfig
+ KUBECONFIG=/home/vulyanov/work/upstream/github/kubevirt.io/kubevirt/_ci-configs/k8s-1.20/.kubeconfig
+ grep vmsnapshot-protection
+ /home/vulyanov/work/upstream/github/kubevirt.io/kubevirt/_ci-configs/k8s-1.20/.kubectl get vmsnapshots --all-namespaces -o=custom-columns=NAME:.metadata.name,NAMESPACE:.metadata.namespace,FINALIZERS:.metadata.finalizers --no-headers
+ read p
error: the server doesn't have a resource type "vmsnapshots"
```
While previously it was:
```
+ kubectl get vmsnapshots --all-namespaces -o=custom-columns=NAME:.metadata.name,NAMESPACE:.metadata.namespace,FINALIZERS:.metadata.finalizers --no-headers
+ grep vmsnapshot-protection
+ read p
error: the server doesn't have a resource type "vmsnapshots"
```
It appears that the **host** `kubectl` was called. Not sure how to test it further.

**Comment by iholder-redhat** [comment]
Thanks @vasiliy-ul 

/lgtm
@dhiller FYI

**Comment by iholder-redhat** [comment]
Note: maybe it's valuable to ensure we don't have more cases when we use the host's kubectl.
Something like `grep kubectl . -R --include=*.sh | grep -v "_kubectl"`

**Review by dhiller — APPROVED** [review]
/approve

Thank you for the fix!

**Pull request merged**
