### PR TITLE
[release-1.3] Add unit tests to check for API backward compatibility

### PR DESCRIPTION
**Pull request by Sreeja1725**
It is a manual cherry-pick into release-1.3, and the original PR can be found [here](https://github.com/kubevirt/kubevirt/pull/11856)
Automatic backport failed as the code exceeded more than 20000 lines.
ref- https://github.com/kubevirt/kubevirt/pull/11856#issuecomment-2193645710

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Add unit tests to check for API backward compatibility
```

### CODE REVIEW

**Comment by alaypatel07** [comment]
/lgtm

@xpivarc for approval
cc @EdDev

**Review by EdDev — COMMENTED** [review]
There is a need to add these 2 details in the PR description:
- Mention it is a manual backport and ref the original PR.
- Reason why it is ok to backport this.


Q: An automatic backport failed?

**Comment by Sreeja1725** [comment]
> Q: An automatic backport failed?
Yes, Since the changes exceeded 20000 lines, automatic cherry-pick failed. Ref - https://github.com/kubevirt/kubevirt/pull/11856#issuecomment-2193645710

**Review by EdDev — APPROVED** [review]

**Comment by EdDev** [comment]
@xpivarc , can we please merge this PR?

**Comment by xpivarc** [comment]
Edited the title for you, I have a look this week

**Comment by EdDev** [comment]
> Edited the title for you, I have a look this week

Can we have it as part of the GA?

**Comment by alaypatel07** [comment]
The test is passing 
/lgtm
/test all

**Comment by alaypatel07** [comment]
@xpivarc @EdDev this is ready to be merged IMO PTAL

**Review by EdDev — APPROVED** [review]

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
