### PR TITLE
Fix links in monitoring-guidelines

### PR DESCRIPTION
**Pull request by sradco**
Signed-off-by: Shirly Radco <sradco@redhat.com>

**What this PR does / why we need it**:
Fix links in monitoring-guidelines

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sradco** [comment]
@phoracek please approve this PR

**Review by phoracek — APPROVED** [review]
/lgtm

**Comment by sradco** [comment]
@phoracek Please approve this PR

**Comment by phoracek** [comment]
@sradco sorry, but I'm not an approver

**Comment by sradco** [comment]
@mhenriks Hi, please approve this PR

**Comment by marceloamaral** [comment]
The PR needs rebase, after that I can approve it

**Comment by sradco** [comment]
@mhenriks can you please review this PR?

**Pull request merged**
