### PR TITLE
Fix SR-IOV 1.17 test lane

### PR DESCRIPTION
**Pull request by phoracek**
**What this PR does / why we need it**:

This PR bumps kubevirtci to the latest version, including SR-IOV cluster fixes. It also sets the number of nodes needed for the SR-IOV test lane to 2, since that is the new requirement of the kind cluster.

**Special notes for your reviewer**:

This PR is currently used to verify changes on kubevirtci:
* Merged: https://github.com/kubevirt/kubevirtci/pull/322
* Merged: https://github.com/kubevirt/kubevirtci/pull/319

This infra change would make CI output better:
* Merged: https://github.com/kubevirt/project-infra/pull/395

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by phoracek** [comment]
The issue seems to be that we execute the Makefile with `dash`, resulting in `/bin/sh: 1: Syntax error: "(" unexpected`.

**Comment by phoracek** [comment]
The updated kubevirtci has issues running kind on single-node.

**Comment by phoracek** [comment]
/hold

Until dependencies get merged and this is rebased.

**Comment by phoracek** [comment]
The lane has passed https://prow.apps.ovirt.org/log?id=1241460797306048512&job=pull-kubevirt-e2e-kind-k8s-sriov-1.17.0.

Now we need to get PRs on kubevirtci merged, bump kubevirtci on kubevirt and rebase this.

**Comment by vladikr** [comment]
look good to me in general and all tests are passing as well.
However, I can't say I'm able to follow every line in this code and be 100% sure what it does :/
I'd be comfortable is some else will look at it and approve.
/lgtm

**Comment by phoracek** [comment]
@vladikr the only thing on kubevirt/kubevirt is change in number of nodes. kubevirtci changes are just fetched. Reviewed on: https://github.com/kubevirt/kubevirtci/pull/322 and https://github.com/kubevirt/kubevirtci/pull/319.

Let me see if we can find someone with approver rights who could confirm these kind changes.

**Pull request merged**
