### PR TITLE
nominate iholder101 as core approver

### PR DESCRIPTION
**Pull request by enp0s3**
Signed-off-by: enp0s3 <ibezukh@redhat.com>

**What this PR does / why we need it**:
I would like to propose a nomination of Itamar Holder AKA @iholder101 for core approver role.
Itamar is one of the [main contibutors](https://github.com/kubevirt/kubevirt/graphs/contributors) to Kubevirt. To me he is a great asset to the kubevirt core. He has:
* More than 100 [merged PRs](https://github.com/kubevirt/kubevirt/pulls?q=is%3Aclosed+is%3Apr+author%3Aiholder101+is%3Amerged+)
* More than 100 [reviews](https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+commenter%3Aiholder101+is%3Aclosed+-author%3Aiholder101+is%3Amerged)

I would like to note some of his most significant efforts:

### Implementations:
- cgroup v2 support (https://github.com/kubevirt/kubevirt/pull/6042)
- Live-Migration Policies API (https://github.com/kubevirt/kubevirt/pull/6399, https://github.com/kubevirt/kubevirt/pull/9466)
- Cloning API (https://github.com/kubevirt/kubevirt/pull/7336, https://github.com/kubevirt/kubevirt/pull/8458, https://github.com/kubevirt/kubevirt/pull/9596, https://github.com/kubevirt/kubevirt/pull/7318)
- Multifd (QEMU-level parallel) migration support (https://github.com/kubevirt/kubevirt/pull/8575)
- Boot from a custom kernel/initrd (https://github.com/kubevirt/kubevirt/pull/5416)
- HyperV Reenlightenment TSC frequencies and migrations (https://github.com/kubevirt/kubevirt/pull/7986, https://github.com/kubevirt/kubevirt/pull/8359)
- virt-handler socket leak (https://github.com/kubevirt/kubevirt/pull/8948)
- Scale virt-api replicas w.r.t. the number of nodes (https://github.com/kubevirt/kubevirt/pull/7401)
- Podman support for "make" and "make test" (https://github.com/kubevirt/kubevirt/pull/6880)

### Significant Reviews:
- CPU hotplug (https://github.com/kubevirt/kubevirt/pull/9757)
- VM Pools (https://github.com/kubevirt/kubevirt/pull/6717)
- Preferences and instancetypes (https://github.com/kubevirt/kubevirt/pull/8466, https://github.com/kubevirt/kubevirt/pull/7578) 
- USB Redirection (https://github.com/kubevirt/kubevirt/pull/4089)
- Monitoring refactoring (https://github.com/kubevirt/kubevirt/pull/7918)
- Housekeeping cgroup (https://github.com/kubevirt/kubevirt/pull/8233, and a serious follow-up which is still WIP, https://github.com/kubevirt/kubevirt/pull/8869)
- Controller template refactoring (https://github.com/kubevirt/kubevirt/pull/7975, https://github.com/kubevirt/kubevirt/pull/7534, https://github.com/kubevirt/kubevirt/pull/8005, https://github.com/kubevirt/kubevirt/pull/7803)
- Free Page Reporting (https://github.com/kubevirt/kubevirt/pull/9426, https://github.com/kubevirt/kubevirt/pull/9572)
- Host-model migration fix (https://github.com/kubevirt/kubevirt/pull/7672, https://github.com/kubevirt/kubevirt/pull/5623)

### Issues / Design proposals:
- Deprecation policy (https://github.com/kubevirt/kubevirt/pull/7791, https://github.com/kubevirt/kubevirt/pull/9012)
- Monitoring code refactoring (https://github.com/kubevirt/community/pull/219)
- Refactor Flavor API (https://github.com/kubevirt/community/pull/165)
- Scaling virt components (https://github.com/kubevirt/kubevirt/issues/7101, https://github.com/kubevirt/kubevirt/issues/9565)
- cgroup v2: tracking of the allowed devices (https://github.com/kubevirt/kubevirt/issues/7710)

### Also worth mentioning - Graduate Swap to Beta in upstream Kubernetes:
- KEP: https://github.com/kubernetes/enhancements/pull/3957
- POCs: https://github.com/kubernetes/kubernetes/pull/117392, https://github.com/kubernetes/kubernetes/pull/116637

**Special notes for your reviewer**:
/cc @acardace 
/cc @xpivarc 
/cc @dhiller
/cc @alicefr 
/cc @rthallisey
/cc @davidvossel
/cc @vladikr
/cc @stu-gott
/cc @jean-edouard
/cc @fabiand
/cc @rmohr
/cc @vasiliy-ul

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
I fully support this.

/lgtm

**Review by vasiliy-ul — APPROVED** [review]
+1 LGTM

**Comment by vladikr** [comment]
+1 from me too.
/lgtm

**Comment by vladikr** [comment]
looks like we all only LGTM'ed it
/approve

/hold
let's just give @davidvossel a chance to review.

**Review by davidvossel — COMMENTED** [review]
/lgtm

**Comment by iholder101** [comment]
Thanks everyone :)
Appreciate it

/retest-required

**Pull request merged**
