### PR TITLE
export: Introduce v1beta1 version

### PR DESCRIPTION
**Pull request by mhenriks**
### What this PR does
Before this PR:

`v1alpha1` is current, and only, version in the `export.kubevirt.io` API group

After this PR:

`v1beta1` is added to `export.kubevirt.io`.  It precisely mirrors `v1alpha1`.  `v1alpha1` still exists and is supported but will be removed eventually.

`v1beta1` will become the "stored" version of the API. Meaning whenever resources are created/updated, they will be tagged as `v1beta1` versions.

Requirements for v1beta1 have been met: https://github.com/kubevirt/community/blob/main/docs/api-graduation-guidelines.md#beta

Fixes #

https://issues.redhat.com/browse/CNV-41870

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Introduce export.kibevirt.io/v1beta1
```

### CODE REVIEW

**Comment by mhenriks** [comment]
cc @alicefr @alaypatel07 @awels

**Comment by alicefr** [comment]
Same question as for https://github.com/kubevirt/kubevirt/pull/11955#issuecomment-2126358084

**Comment by mhenriks** [comment]
> Same question as for [#11955 (comment)](https://github.com/kubevirt/kubevirt/pull/11955#issuecomment-2126358084)

@jpeimer do we have good tier 2 testing for export API similar to snapshot API?

**Review by awels — APPROVED** [review]

**Pull request merged**
