### PR TITLE
Make the operator the only dev workflow for installing kubevirt

### PR DESCRIPTION
**Pull request by davidvossel**
**What this PR does / why we need it**:

Previously developers could use 'cluster-sync' or 'cluster-sync-operator' to install kubevirt in their dev environment. The first method would use the old manifest way of installing kubevirt, and the latter option uses the operator.

The operator is the way of the future. We should consolidate down to a single install path that uses the operator. 

**Release note**:
```release-note
Replaces 'make cluster-sync-operator' with 'make cluster-sync'
```

### CODE REVIEW

**Comment by davidvossel** [comment]
I had to add some fixes related to the recent CDI 1.5.1 deployment cleanup. Lets make sure CI still passes before merging

**Comment by davidvossel** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
I think because of network connectivity issues we will not have better CI results.

**Pull request merged**
