### PR TITLE
[bugFix]: Fix panic in virt-handler when process is not found during CPU housekeeping

### PR DESCRIPTION
**Pull request by Barakmor1**
The `FindProcess` function from the [`go-ps` package](github.com/mitchellh/go-ps) returns nil without error if a process isn't found, but our code incorrectly assumes an error. This commit adds a check to ensure the process is not nil before invoking its methods, preventing the panic.

Ideally, we should avoid using the [`go-ps` package](github.com/mitchellh/go-ps), as it is outdated and we don't want to keep it as a dependency.

Panics: https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.30-sig-compute/1768655952652800000 https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.30-sig-compute/1818665585588834304

Please review virt-handler logs for details on the panics.

### What this PR does
Before this PR:

After this PR:

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by fossedihelm — COMMENTED** [review]
There is another place that is affected by this:
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-handler/isolation/detector.go#L236-L243
Can you address it too? Thanks

**Comment by Barakmor1** [comment]
@fossedihelm Thanks for the important note!

**Review by jean-edouard — APPROVED** [review]

**Pull request merged**
