### PR TITLE
virt-config fixes (tests and docs)

### PR DESCRIPTION
**Pull request by andreabolognani**
**What this PR does / why we need it**:

Some issues with tests and documentation for the KubeVirt CR are addressed.

**Which issue(s) this PR fixes**:

None.

**Special notes for your reviewer**:

None.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by andreabolognani** [comment]
None of the CI failures _seem_ to be connected to my changes - a lot of timeouts and stuff like that.

**Comment by rmohr** [comment]
/lgtm
/approve

thanks.

**Comment by rmohr** [comment]
> None of the CI failures _seem_ to be connected to my changes - a lot of timeouts and stuff like that.

Yes, this time it was calico not getting ready:

```
kube-system              pod/calico-node-wk8tb                                                 0/1     Running   0          48m   192.168.66.101   node01   <none>           <none>
```

We updated `runc` in the containers to get rid of some sporadic dev-permission denials but traded this bug with a new runc/containerd bugs :/

**Pull request merged**
