### PR TITLE
add test id

### PR DESCRIPTION
**Pull request by dalia-frank**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by usrbinkat** [comment]
Thank you for your contribution @dalia-frank. Can we please get a description and possibly a bug/rfe opened for this PR to attach to?

**Comment by akalenyu** [comment]
I think this is just about easier interaction with test reporting tools, should be harmless
Example:
https://github.com/kubevirt/kubevirt/pull/7565

/lgtm
/ok-to-test
/cc @kbidarkar

**Comment by EdDev** [comment]
> I think this is just about easier interaction with test reporting tools, should be harmless Example: #7565
> 
> /lgtm /ok-to-test /cc @kbidarkar

It may be harmless, but it still needs some text in the commit and PR description that describes it.
The release-notes also need to be updated (to `NONE`) in the PR description.

Please also note that `ok-to-test` is not safe to use, and if it is, then a reasoning needs to be given.

**Pull request merged**
