### PR TITLE
[release-0.58] migration: apply backoff only for evacuation migrations

### PR DESCRIPTION
**Pull request by acardace**
**What this PR does / why we need it**:
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/8808.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Apply migration backoff only for evacuation migrations.
```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve

**Comment by acardace** [comment]
I don't think there are conflicts, otherwise, also the other lanes wouldn't pass, I think the bot got confused because at first I opened the PR against main by mistake, I'll re-create it I guess.

**Pull request closed without merging**
