### PR TITLE
Introduce a DiskBus type and associated constants

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

This is a simpler refactor PR replacing the use of string based disk buses with a specific string based type and associated constants. 

A small amount of leftover floppy disk code was found during this process and is removed in the initial commit.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # N/A

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

nice!

**Comment by xpivarc** [comment]
/hold
More tests need to be adjusted

**Comment by lyarwood** [comment]
@xpivarc this should be good now btw.

**Pull request merged**
