### PR TITLE
Update kubevirtci sha to latest master

### PR DESCRIPTION
**Pull request by danielBelenky**
The latest master includes an updated ocp-4.3 provider.

Signed-off-by: Daniel Belenky <dbelenky@redhat.com>

```release-note
None
```

### CODE REVIEW

**Comment by phoracek** [comment]
@danielBelenky could I ask you to fetch the current kubevirtci master? It includes some SR-IOV lane fixes. Thanks

**Comment by phoracek** [comment]
We already bumped to the latest kubevirtci in https://github.com/kubevirt/kubevirt/pull/3185. I believe this can be closed.

**Comment by davidvossel** [comment]
closing because pr #3185 addresses this

**Pull request closed without merging**
