### PR TITLE
Remove deprecated file-based watchdog and graceful shutdown triggers

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Remove deprecated file-based watchdog and graceful shutdown triggers. The PR which did the change is now more than two years old (https://github.com/kubevirt/kubevirt/pull/3212), and there is no chance that a <0.29 KubeVirt deployment is still around.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

A preparatory cleanup to make restarting  the work on something like https://github.com/kubevirt/kubevirt/pull/3311 easier.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

while this change is closed in itself, there are still a lot of old code paths left.

**Review by davidvossel — COMMENTED** [review]
look for places where `!cmdclient.SocketMonitoringEnabled(socket)` is in use as well

**Pull request closed without merging**
