### PR TITLE
Add runbook_url to alerts

### PR DESCRIPTION
**Pull request by sradco**
Signed-off-by: Shirly Radco <sradco@redhat.com>

**What this PR does / why we need it**:
Add runbook_url to alerts.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
This PR adds to each alert the runbook url that points to a runbook that provides additional details on each alert and how to mitigate it.
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
In which repo are the runbooks defined? I tried grepping around but couldn't find it.
I'm asking because looking at the first line on the first linked page I found a typo:
`KubeVirtComponenetExceedsRequestedCPU` in https://kubevirt.io/monitoring/runbooks/KubeVirtComponentExceedsRequestedCPU
Clicking though the links generated by this PR, I also get more 404 than existing pages, is that expected?
Thank you!

**Comment by sradco** [comment]
> In which repo are the runbooks defined? I tried grepping around but couldn't find it.
> I'm asking because looking at the first line on the first linked page I found a typo:
> `KubeVirtComponenetExceedsRequestedCPU` in https://kubevirt.io/monitoring/runbooks/KubeVirtComponentExceedsRequestedCPU
The repo is
kubvirt/monitoring/docs/runbooks/
> Clicking though the links generated by this PR, I also get more 404 than existing pages, is that expected?

Yes, We are working in parallel to add all missing runbooks.

> Thank you!

**Comment by sradco** [comment]
@jean-edouard  @phoracek @yuhaohaoyu  Hi, Can you please review and add lgtm if it is ok?

**Review by RamLavi — APPROVED** [review]
/lgtm

**Comment by RamLavi** [comment]
/hold
looks good from network side, waiting for lgtm from other teams

**Pull request merged**
