### PR TITLE
add vi-minimal to base packages for containers

### PR DESCRIPTION
**Pull request by davidvossel**
it would be a good idea for us to ship our containers with a basic text editor. 

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
The rpm verify job will be fixed with #4766

**Review by enp0s3 — APPROVED** [review]
/lgtm

**Comment by dankenigsberg** [comment]
Why is it such a great idea @davidvossel ? I can see why it can assist random debugging task. Is this the case? Does it merit the added storage and memory requirements

**Comment by davidvossel** [comment]
> Why is it such a great idea @davidvossel ? I can see why it can assist random debugging task. Is this the case? Does it merit the added storage and memory requirements

Right, it's for debugging.  I wouldn't care about adding it to the container if we could do something like `yum install vim-minimal` inside the container... but now that we're using a scratch container we don't have a practical way to pull in new packages on the fly (at least that i'm aware of)

**Pull request merged**
