### PR TITLE
check pods and nodes

### PR DESCRIPTION
**Pull request by iholder-redhat**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by oshoval** [comment]
You may want to /uncc people when there is a draft, up to you :)
Thanks

**Comment by iholder-redhat** [comment]
@oshoval Thanks! Didn't know about that option
/uncc

**Pull request closed without merging**
