### PR TITLE
tests, network: Remove duplicate imports

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR fixes duplicate imports in vmi_netowrking.go tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by EdDev — APPROVED** [review]

**Review by orelmisan — APPROVED** [review]
Thank you @RamLavi

**Review by ormergi — APPROVED** [review]
Looks good, we surly need to apply this all over the code base.

**Pull request merged**
