### PR TITLE
[release-0.36]  Fix test that is overriding all devices instead of interfaces 

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by davidvossel — CHANGES_REQUESTED** [review]
The functional test change is fine. We don't require a 1:1 relationship of volumes to disks though. This validation will also break filesystems like virtofs.

**Comment by xpivarc** [comment]
@davidvossel I changed this to only test fix. I will open a PR with the validation.

**Comment by maya-r** [comment]
/lgtm
/retest-required
@davidvossel you've said you think the functional test is fine. Now that is the only part left, do you think it can be approved?

**Comment by fgimenez** [comment]
1.17 and 1.18 lanes have been failing for 3 weeks now with different errors https://prow.ci.kubevirt.io/pr-history/?org=kubevirt&repo=kubevirt&pr=6801 should we override?

**Comment by xpivarc** [comment]
> 1.17 and 1.18 lanes have been failing for 3 weeks now with different errors https://prow.ci.kubevirt.io/pr-history/?org=kubevirt&repo=kubevirt&pr=6801 should we override?

+1 from me

**Comment by rmohr** [comment]
/override pull-kubevirt-e2e-k8s-1.17



<br class="Apple-interchange-newline">

**Pull request merged**
