### PR TITLE
[Release 0.49] Switch to semantic DeepEquals()

### PR DESCRIPTION
**Pull request by davidvossel**
This is a backport of https://github.com/kubevirt/kubevirt/pull/7135 which fixes some wonkyness we've experienced with our controllers recently.

```release-note
Switch from reflects.DeepEquals to equality.Semantic.DeepEquals() across the entire project
```

### CODE REVIEW

**Review by rmohr — CHANGES_REQUESTED** [review]
Seems like a `make` run is needed:

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   pkg/virt-handler/hotplug-disk/BUILD.bazel
	modified:   pkg/virt-launcher/virtwrap/util/BUILD.bazel
```

**Comment by davidvossel** [comment]
> Seems like a make run is needed:

oops, thanks. Fixed

**Pull request merged**
