### PR TITLE
update listType markers for kubevirt pci host devices

### PR DESCRIPTION
**Pull request by davidvossel**
listType=set is used for string lists. We need to use atomic or map for structs. 

```release-note
NONE
```

### CODE REVIEW

**Comment by davidvossel** [comment]
waiting on https://github.com/kubevirt/kubevirt/pull/4396 to be merged before moving this out of draft. That pr will conflict with this one, so we'll have to rebase after #4396 is finally merged

**Comment by davidvossel** [comment]
this should be good to go now

**Comment by vladikr** [comment]
Thanks! 
/lgtm
/approve

**Comment by rmohr** [comment]
/override pull-kubevirt-e2e-k8s-1.18 

Fails on an a flaky test which I am fixing in another PR.

**Pull request merged**
