### PR TITLE
Revert "Bump kubevirtci"

### PR DESCRIPTION
**Pull request by brianmcarey**
### What this PR does

This reverts commit 6200c1bb98e92d2e51576dda03a4f916e161f0af.

There has been a bad flake affecting cluster-up[1] that has appeared since merging the latest bump-kubevirtci. Revert this update to reduce the impact of the flake and allow time for investigation.

The impact is quite high across all lanes that use the virtual kubevirtci providers[2]

[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13020/pull-kubevirt-e2e-k8s-1.31-sig-network/1843292337933914112#1:build-log.txt%3A343
[2] https://search.ci.kubevirt.io/?search=failed+to+create+new+CRI+runtime+service%3A+validate+service+connection%3A+validate+CRI+v1+runtime+API+for+endpoint&maxAge=48h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

/cc @dhiller @xpivarc 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve

**Comment by dhiller** [comment]
FYI @alicefr @vladikr @acardace 

please help to get this in

**Comment by dhiller** [comment]
FYI @jean-edouard @fossedihelm can you help here please?

**Comment by fossedihelm** [comment]
I don't think I have rights to approve :) 
/approve

**Review by xpivarc — COMMENTED** [review]
/approve
Let me know if you need help with the investigation

**Comment by brianmcarey** [comment]
> Does this PR require priority?

Yes you are right - I was hoping this would get picked up in a batch but it hasn't. Going to make this a priority for tide.

/priority critical-urgent

**Pull request merged**
