### PR TITLE
Limit CriticalAddonsOnly taint to a single compute

### PR DESCRIPTION
**Pull request by danielBelenky**
The CriticalAddonsOnly taint and toleration is meant to be used by K8s
addons that can be scheduled on a compute node but are critical for the
proper functionality of the cluster. KubeVirt is one example for such
addon.

In the existing test, we used to taint every node that runs a kubevirt
component and our components can be scheduled on the master nodes we
might end up tainting masters. The problem with doing it is that some
core components might not tolerate this taint and we might end up with a
broken cluster which might not recover properly.

This patch limits the taint in the test to be set only on one compute
node. It should be enough for us to ensure that our components can
actually tolerate while not risking any core components.

Signed-off-by: Daniel Belenky <dbelenky@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by ILpinto — COMMENTED** [review]
/lgtm

**Review by stu-gott — APPROVED** [review]
/approve

**Pull request merged**
