### PR TITLE
[release-0.53]: Bugfix: virt-handler socket leak

### PR DESCRIPTION
**Pull request by iholder101**
**What this PR does / why we need it**:
Manual backport of https://github.com/kubevirt/kubevirt/pull/9002.

No interesting conflicts, only straight forward and minor ones.

**Release note**:

```release-note
Bugfix: virt-handler socket leak
```

### CODE REVIEW

**Comment by iholder101** [comment]
/hold

blocked by https://github.com/kubevirt/kubevirt/pull/9006

**Review by enp0s3 — COMMENTED** [review]
/approve

**Pull request merged**
