### PR TITLE
[release-0.36] Fix Guest Agent version compatibility check

### PR DESCRIPTION
**Pull request by stu-gott**
This is a manually created backport of https://github.com/kubevirt/kubevirt/pull/4682

----------------

**What this PR does / why we need it**:
We recently added a VMI status condition for AgentVersionNotSupported. This was intended to warn the user that the version of the QEMU guest agent they're using isn't compatible with KubeVirt. The method we currently use to check for compatibility is error prone. This PR introduces a new method of checking -- Instead of checking the package version number, we now inspect which calls the QEMU guest agent actually supports. As part of this we no longer need to track compatible versions (since package version numbers are now ignored entirely).

The fundamental issue that's causing this check to fail so often is that the guest agent [API](https://www.mankier.com/7/qemu-ga-ref) isn't versioned--the "version" call returns the guest agent version, not an API version. So any regexp we craft to check versions will eventually fail, even though odds are overwhelmingly that nothing's wrong.

**Which issue(s) this PR fixes**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1908419

**Release note**:
```release-note
Updated Guest Agent Version compatibility check. The new approach is much more accurate.
```

### CODE REVIEW

**Comment by davidvossel** [comment]
/hold

it looks like this somehow broke access credentials test. The agent connected condition for those tests isn't being satisfied, which is  a precondition for actually doing any of the access credential stuff

**Comment by stu-gott** [comment]
Thanks! I was already investigating. You are correct that something is off.

To put your mind at ease: those 2 tests were new with this PR, so not so much a mystery regression as something related to test suite changes between 0.36 and master.

**Comment by stu-gott** [comment]
/hold

Asserting an independent hold from @davidvossel's. The most recent patch fixed the immediate issue with outright failures due to guest agent availability, but the tests appear to fail a considerable percentage of runs now.

**Comment by stu-gott** [comment]
/hold cancel

Silly me. I forgot invoking qemu-ga directly doesn't use a config file. Failures with tests should be fixed. I don't like deviating from the original patches on main so much, but release-0.36 just works differently

**Review by davidvossel — APPROVED** [review]
/lgtm

**Pull request merged**
