### PR TITLE
Wait for virt-operator pods to be ready after scale back in E2E tests

### PR DESCRIPTION
**Pull request by machadovilaca**
**What this PR does / why we need it**:

Monitoring lane if failing on recent K8S versions. This PR ensures virt-operator is ready after rescales to ensure connection refused error does not happen

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```
none
```

### CODE REVIEW

**Review by dhiller — COMMENTED** [review]
I see that this change only affects one of the three tests that were failing in recent runs:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1751952489063649280
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1751944133791977472

Were the other failures also related to the operator pods not being ready?   

(In those test failures I see a conflict in the resource version, which makes me believe there's an error in some update. Didn't look to closely into those tests TBH.)

**Review by brianmcarey — COMMENTED** [review]
/lgtm

thanks @machadovilaca

**Review by brianmcarey — COMMENTED** [review]
Actually just one small thing - I don't think this change requires a Release Note as its just a small test update

/lgtm cancel

**Comment by machadovilaca** [comment]
> Actually just one small thing - I don't think this change requires a Release Note as its just a small test update
> 
> /lgtm cancel

updated @brianmcarey

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by dhiller** [comment]
> I see that this change only affects one of the three tests that were failing in recent runs:
> 
> * https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1751952489063649280
> * https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1751944133791977472
> 
> Were the other failures also related to the operator pods not being ready?
> 
> (In those test failures I see a conflict in the resource version, which makes me believe there's an error in some update. Didn't look to closely into those tests TBH.)

@machadovilaca ?

**Comment by machadovilaca** [comment]
> > I see that this change only affects one of the three tests that were failing in recent runs:
> > 
> > * https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1751952489063649280
> > * https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1751944133791977472
> > 
> > Were the other failures also related to the operator pods not being ready?
> > (In those test failures I see a conflict in the resource version, which makes me believe there's an error in some update. Didn't look to closely into those tests TBH.)
> 
> @machadovilaca ?

@dhiller I think these are related, always refused when trying to connect to `kubevirt-operator-webhook`

**Comment by dhiller** [comment]
/test pull-kubevirt-e2e-k8s-1.29-sig-monitoring

Just want to see it succeeding another time, then I'll be convinced that this can go in.

**Comment by brianmcarey** [comment]
> /test pull-kubevirtci-bump-kubevirt

This job has been removed from the presubmits. Is this urgent or can you wait for the periodic?

**Comment by oshoval** [comment]
> > /test pull-kubevirtci-bump-kubevirt
> 
> This job has been removed from the presubmits. Is this urgent or can you wait for the periodic?

I prefer that we do return please the job, there is no reason to drop it, it works perfect and unharmful
it was discussed in the past and was approved to be added
There is no reason to wait when something is needed imo, it allows managing the time better

**Comment by oshoval** [comment]
> > /test pull-kubevirtci-bump-kubevirt
> 
> This job has been removed from the presubmits. Is this urgent or can you wait for the periodic?

It is fine thanks, lets wait

**Comment by dhiller** [comment]
/lgtm cancel

The lane has been failing twice as seen similarly on the periodic lane.
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11110/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1752729495531425792
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11110/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1752645186241957888

**Comment by machadovilaca** [comment]
> /lgtm cancel
> 
> The lane has been failing twice as seen similarly on the periodic lane.
> 
> * https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11110/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1752729495531425792
> * https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11110/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1752645186241957888

might be yet another issue, it's different from the original, I'll take another look

**Pull request closed without merging**
