### PR TITLE
pull out some duplicated code to improve readability

### PR DESCRIPTION
**Pull request by ashleyschuett**
Signed-off-by: Ashley Schuett <aschuett@redhat.com>

**What this PR does / why we need it**:

improve readability of creating a patch with labels/annotation and spec field since multiple resource need to create this patch. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ashleyschuett** [comment]
@dhiller thanks for reviewing! I have rebased now :)

**Comment by iholder-redhat** [comment]
/lgtm
Thanks :)

**Pull request merged**
