### PR TITLE
Moving updater package under storage

### PR DESCRIPTION
**Pull request by Barakmor1**
Moving the package under storage is good because it keeps related code together. Since it's only used there, it makes the project easier to manage.

### What this PR does
Before this PR:

After this PR:

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by Barakmor1** [comment]
> @Barakmor1 what happened to the unit tests for the status package?

The unit tests in the status package were testing deleted objects like `KubeVirtStatusUpdater` and `VMStatusUpdater` and more. Since those objects were removed, we also had to remove the tests for them.

**Comment by mhenriks** [comment]
> > @Barakmor1 what happened to the unit tests for the status package?
> 
> The unit tests in the status package were testing deleted objects like `KubeVirtStatusUpdater` and `VMStatusUpdater` and more. Since those objects were removed, we also had to remove the tests for them.

I see that types like VirtualMachine, etc are still referenced in the code. Don't you think that should be updated as well? 
 
For example: https://github.com/kubevirt/kubevirt/blob/c8f45ba077e46993ac2275ce8484cf3bf9826991/pkg/storage/status/status.go#L172-L206

**Comment by Barakmor1** [comment]
> > > @Barakmor1 what happened to the unit tests for the status package?
> > 
> > 
> > The unit tests in the status package were testing deleted objects like `KubeVirtStatusUpdater` and `VMStatusUpdater` and more. Since those objects were removed, we also had to remove the tests for them.
> 
> I see that types like VirtualMachine, etc are still referenced in the code. Don't you think that should be updated as well?
> 
> For example:
> 
> https://github.com/kubevirt/kubevirt/blob/c8f45ba077e46993ac2275ce8484cf3bf9826991/pkg/storage/status/status.go#L172-L206

The reason I didn't delete this part in [PR #12597](https://github.com/kubevirt/kubevirt/pull/12597) is that there was a request to keep the package. While working on the PR, I found no usage of the updater package, so removing the switch cases for unused objects would have left empty functions, which seemed odd. However, now that storage is using the updater, the unused functionality can be removed. I’d be happy to clean up more code from the package.

**Comment by Barakmor1** [comment]
@mhenriks Please let me know what you think

**Pull request merged**
