### PR TITLE
launcher: Drop console hack

### LINKED ISSUE #834: Remove ocp hack once console websocket is introduced
#819 needs to be reverted then.

### PR DESCRIPTION
**Pull request by fabiand**
We temporarily carried a console hack in order to allow the OpenShift
Webconsole to conncet to a VM's console. But since then we added a
API subresource which can be accessed, and it's up to the webconsole
to adjust to this new feature.

Originally introduced with #819

Fixes #834 

```release-note
A friendly hack we carried around for OpenShift Web Console is getting removed by this change.
```

Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

### CODE REVIEW

**Comment by fabiand** [comment]
I'd liekt o get this into v0.7.0

**Comment by fabiand** [comment]
Right - Just to understand it correctly:

The current kubevirt console code uses a different transport than the k8s
container console.

The work in #1015 contains partial work to adjust the kubevirt code to have
the same transport as k8s container console.

Correct?

if so, then yes, dropping it in 0.8 is also fine for me.

**Comment by rmohr** [comment]
> The work in #1015 contains partial work to adjust the kubevirt code to have
> the same transport as k8s container console.

yes it contains the necessary glue-code (the ssh sessions there are transported with the streaming protocol). That part can be copied and connected to the vm-console stream.

**Comment by rmohr** [comment]
@mareklibra the discussion in that PR might be interesting for you.

**Comment by fabiand** [comment]
Could you remind me what /hold means?

**Comment by rmohr** [comment]
> Could you remind me what /hold means?

Updated the comment, was bad practice that I did not also add the reason. Just meant as a marker that although the PR may be fine we have reasons to not merge it right now. I had the impression we agreed on removing it once we provide the k8s streaming protocol support.

**Comment by fabiand** [comment]
Just noting it here as well: The stream protocol has an issue. but there is another workaround which is to just launch the socket-connector from the terminal which is created in the webconsole for the VM serial console.

**Pull request merged**
