### PR TITLE
Fix tests relying on bearer token behavior

### PR DESCRIPTION
**Pull request by stu-gott**
A handful of functional tests relied on using "--token" to indicate preference as to which service account the test should run as. These tests might have worked at some point in the past, but don't behave correctly with current k8s or openshift clients.

Since the intention of the test is to simply verify VM creation behavior/permissions, these tests have been changed to instead use the "auth can-i" subcommand--which unambiguously checks permissions for the explicitly named account.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by stu-gott** [comment]
/cc @danielBelenky 
No code changes in forced commit -- added the PR description to the changeset as requested.

**Comment by rmohr** [comment]
> @stu-gott could you please add the description to the commit message? it will be lost when we merge it otherwise...

Why would it be lost otherwise?

**Comment by rmohr** [comment]
Tests look good. Merging without tide right now.

**Pull request merged**
