### PR TITLE
Run a first set of unit tests in parallel through ginkgo

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

This is the second attempt after #5712 to run unit tests in parallel through ginkgo. In the first attempt in #5684 I made a mistake which led to tests being skipped. This time it should be done properly.

A new `ginkgo_test` target is introduced. In order to make use of it, do the following:

First import `ginkgo_test` to a BUID file with the `go_test` target you want to speed up: 

```python
load("@kubevirt//tools/ginkgo:ginkgo.bzl", "ginkgo_test")`
```

Mark the original `go_test` target with the `cov` tag to avoid double exeuction if you do something like `bazel test //pkg/...`:

```python
go_test(
    name = "go_default_test",
    [...]
    tags = ["cov"],
   [...]
)
```

Introduce the new `ginkgo_test` target, point it to the `go_test` target and tell it to run in parallel with the `-p` flag:

```python
ginkgo_test(
    name = "go_parallel_test",
    tags = ["nocov"],    
    ginkgo_args = ["-p"],
    go_test = ":go_default_test",
)
```

Further a `nocov` tag is added to exclude it from coverage runs. There we want to still run the `go_test` target

The PR runs a first set of very slow unit tests in parallel now.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

The original starlark wrapper is from here: # Inspired by https://github.com/onsi/ginkgo/issues/800#issuecomment-829037396 and is extended with junit merging.

Most tests are fast enough and don't require parallel building. Therefore I think this mental overhead is acceptable if one has to run test suites in parallel too.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

I need to handle coverage.

**Comment by rmohr** [comment]
Should be ready for review. Thanks.

**Review by dhiller — APPROVED** [review]
/approve
/hold

Looks good to me. I think I need to look even deeper into bazel, the ease of defining a new test target is impressive.

Holding for others to take a look, unhold when ready.

**Comment by davidvossel** [comment]
@rmohr @dhiller i think this disabled unit test result caching, which is helpful for our dev environments

**Comment by rmohr** [comment]
> @rmohr @dhiller i think this disabled unit test result caching, which is helpful for our dev environments

Can you please check if you still have `--cache_test_results=no` in one of your .bazelrc files set? The PR should have no impact on it and I can't reproduce your issue.

**Comment by davidvossel** [comment]
> Can you please check if you still have --cache_test_results=no in one of your .bazelrc files set? The PR should have no impact on it and I can't reproduce your issue.

yup, that was it. something created a `ci.bazelrc` file that had this cache setting disabled

**Pull request merged**
