### PR TITLE
virtctl: Allow Kubernetes auth plugins

### PR DESCRIPTION
**Pull request by mlsorensen**
This allows client auth plugins/providers to work with virtctl (e.g. oidc).

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by fabiand** [comment]
ok to test

**Comment by fabiand** [comment]
ci test please

**Comment by rmohr** [comment]
@mlsorensen could you update the build dependencies? Taken from travis:

```
../../vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:26:2: cannot find package "github.com/Azure/go-autorest/autorest" in any of:
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/Azure/go-autorest/autorest (vendor tree)
	/gimme/.gimme/versions/go1.9.2.linux.amd64/src/github.com/Azure/go-autorest/autorest (from $GOROOT)
	/root/go/src/github.com/Azure/go-autorest/autorest (from $GOPATH)
../../vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:27:2: cannot find package "github.com/Azure/go-autorest/autorest/adal" in any of:
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/Azure/go-autorest/autorest/adal (vendor tree)
	/gimme/.gimme/versions/go1.9.2.linux.amd64/src/github.com/Azure/go-autorest/autorest/adal (from $GOROOT)
	/root/go/src/github.com/Azure/go-autorest/autorest/adal (from $GOPATH)
../../vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:28:2: cannot find package "github.com/Azure/go-autorest/autorest/azure" in any of:
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/Azure/go-autorest/autorest/azure (vendor tree)
	/gimme/.gimme/versions/go1.9.2.linux.amd64/src/github.com/Azure/go-autorest/autorest/azure (from $GOROOT)
	/root/go/src/github.com/Azure/go-autorest/autorest/azure (from $GOPATH)
../../vendor/k8s.io/client-go/plugin/pkg/client/auth/openstack/openstack.go:26:2: cannot find package "github.com/gophercloud/gophercloud/openstack" in any of:
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/gophercloud/gophercloud/openstack (vendor tree)
	/gimme/.gimme/versions/go1.9.2.linux.amd64/src/github.com/gophercloud/gophercloud/openstack (from $GOROOT)
	/root/go/src/github.com/gophercloud/gophercloud/openstack (from $GOPATH)
../../vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go:31:2: cannot find package "golang.org/x/oauth2" in any of:
	/root/go/src/kubevirt.io/kubevirt/vendor/golang.org/x/oauth2 (vendor tree)
	/gimme/.gimme/versions/go1.9.2.linux.amd64/src/golang.org/x/oauth2 (from $GOROOT)
	/root/go/src/golang.org/x/oauth2 (from $GOPATH)
../../vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go:32:2: cannot find package "golang.org/x/oauth2/google" in any of:
	/root/go/src/kubevirt.io/kubevirt/vendor/golang.org/x/oauth2/google (vendor tree)
	/gimme/.gimme/versions/go1.9.2.linux.amd64/src/golang.org/x/oauth2/google (from $GOROOT)
	/root/go/src/golang.org/x/oauth2/google (from $GOPATH)
```

**Comment by mlsorensen** [comment]
@rmohr - just the glide updates from 'make deps-update', or do I need to add in the new vendor files as well?

**Comment by rmohr** [comment]
All vendors dependencies need to be added too. Thanks.

**Comment by rmohr** [comment]
Thanks! :+1:

**Comment by rmohr** [comment]
Is there a way to test if it works in general which we can transform in a test?

**Pull request merged**
