### PR TITLE
Removed CRD status from generated manifests

### LINKED ISSUE #1279: kubevirt v0.7.0-alpha.2 doesn't work with k8s 1.11
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

When my cluster is up and running, I applied the following two commands. 
    # export VERSION=v0.7.0-alpha.2
    # kubectl create     -f https://github.com/kubevirt/kubevirt/releases/download/$VERSION/kubevirt.yaml

**What happened**:
Got one error: 
error: error validating "https://github.com/kubevirt/kubevirt/releases/download/v0.7.0-alpha.2/kubevirt.yaml": error validating data: [ValidationError(CustomResourceDefinition.status): missing required field "conditions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus, ValidationError(CustomResourceDefinition.status): missing required field "storedVersions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus]; if you choose to ignore these errors, turn validation off with --validate=false

**What you expected to happen**:
No errors, and then deploy a virtualmachine following steps from http://kubevirt.io/get_kubevirt/#deploy-a-virtualmachine 

**How to reproduce it (as minimally and precisely as possible)**:
1, Use 'kubeadm' to set up a cluster (one master and one node) 
2, Both "kubect get pods --all-namespaces" and "kubectl get nodes" output expected results. 
3, run these two commands from http://kubevirt.io/get_kubevirt/#deploy-kubevirt

**Anything else we need to know?**:
N/A 

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications: 
- Cloud provider or hardware configuration: Virtualmachines for both k8s master and its node
- OS (e.g. from /etc/os-release): RHEL7.5
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by slintes**
**What this PR does / why we need it**:

Removed CRD status from generated manifests, in order to work with k8s 1.11

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #1279

**Special notes for your reviewer**:

- updated https://github.com/ant31/crd-validation, which contains the needed fix
  see https://github.com/ant31/crd-validation/pull/5
- updated k8s dependencies to 1.10.5, needed by above update

**Release note**:
```release-note
Removed CRD status from manifests, did break KubeVirt on k8s 1.11
```

### CODE REVIEW

**Comment by slintes** [comment]
OK to test

**Comment by stu-gott** [comment]
Thanks @slintes!

**Comment by rmohr** [comment]
ok to test

**Comment by rmohr** [comment]
retest this please

**Comment by slintes** [comment]
mh, it's always the same test which fails ("Storage Starting a VirtualMachineInstance With an emptyDisk defined [It] should create a writeable emptyDisk with the right capacity"), but it works on my machine...

**Comment by cynepco3hahue** [comment]
@slintes It fails on `Missing error` from libvirt, we still waiting for the fix on libvirt-go side.
It the reason for almost all failures under PR CI runs, so I will merge it.

**Pull request merged**
