### PR TITLE
Return directly when key function executes failed

### PR DESCRIPTION
**Pull request by crazytaxii**
workqueue

Signed-off-by: HF <crazytaxii666@gmail.com>

**What this PR does / why we need it**:
Fixed code error.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Return directly when key function executes failed, the unexpected key should not be added into workqueue.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
Hi @crazytaxii! Thank you for your contribution.
Could you please give more information about what this PR does and what it's for? `Fixed code error.` doesn't really say much...
Thank you!

**Comment by crazytaxii** [comment]
> Hi @crazytaxii! Thank you for your contribution. Could you please give more information about what this PR does and what it's for? `Fixed code error.` doesn't really say much... Thank you!

If we don't return, the invalid or empty key will be added into work queue.

**Comment by jean-edouard** [comment]
> > Hi @crazytaxii! Thank you for your contribution. Could you please give more information about what this PR does and what it's for? `Fixed code error.` doesn't really say much... Thank you!
> 
> If we don't return, the invalid or empty key will be added into work queue.

Indeed! Thank you.
/approve

**Review by vasiliy-ul — APPROVED** [review]

**Pull request merged**
