### PR TITLE
virt-launcher, converter: Remove redundent check for '/dev/vhost-net' presense

### PR DESCRIPTION
**Pull request by ormergi**
**What this PR does / why we need it**:
In case a VM requires virtio network, when at least one interface model is set to virtio explicitly or empty (implicitly), virt-controller template code will add mount /dev/vhost-net to virt-launcher pod.

The virt-launcher converter code (VM spec to domain XML) checks if /dev/vhost-net exist, if not and Kubevirt is not set to allow software emulation, it will fail syncVMI routine and cause re-enqueues.

In Kubernetes, if a pod spec specifies a resource that doesn't exist the pod hang on scheduling phase and wont start.
In our case, when '/dev/vhost-net' is not present in any node virt-launcher pod wont start.

Failing in case a VM has virito interface(s) but '/dev/vhost-net' is not present is redundant, because when virt-launcher converter code runs it means the pod has started and '/dev/vhost-net' exist.

Also, virt-handler claims ownership of `/dev/vhost-net` [1] just before network setup starts.
If `/dev/vhost-net` is not present, the network setup code will fail and cause the virt-launcher pod to fail.

[1] https://github.com/kubevirt/kubevirt/blob/aa6bdd0b7d6e9c279009efa6f497fee101a13040/pkg/virt-handler/vm.go#L571-L570

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Unfortunately its not possible to unit-test this because a need k8s API server is necessary to decide if pod spec is valid
and schedule successfully.

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ormergi** [comment]
/cc @vladikr @xpivarc 

@vladikr / @xpivarc Could you please take a look? I will appreciate your feedback on it :slightly_smiling_face:

**Review by EdDev — COMMENTED** [review]
This one makes sense to me, thanks!

My only request is to check what is the error libvirt produces when this is indeed missing (caused by some bug / unexpected behavior).

**Comment by AlonaKaplan** [comment]
/approve

Please also add to the description virt-handler already has exactly the same check (verifying /dev/vhost-net is on the virt-launcher's moint namespace).

**Comment by ormergi** [comment]
> My only request is to check what is the error libvirt produces when this is indeed missing (caused by some bug / unexpected behavior).

When /dev/vhost-net is not present virt-launcher will failed much earlier, before network setup is start:
https://github.com/kubevirt/kubevirt/blob/aa6bdd0b7d6e9c279009efa6f497fee101a13040/pkg/virt-handler/vm.go#L571-L570
```
...
Events:
  Type     Reason            Age   From                       Message
  ----     ------            ----  ----                       -------
  Normal   SuccessfulCreate  33s   virtualmachine-controller  Created virtual machine pod virt-launcher-vmi-masquerade-zk2xd
  Warning  SyncFailed        26s   virt-handler               failed to configure vmi network: setup failed at pre-setup stage, err: Critical network error: failed to set up vhost-net device, failed opening vhost-net for path root: /proc/924031/root, relative: /dev/vhost-net: no such file or directory
```

**Comment by ormergi** [comment]
> /approve
> 
> Please also add to the description virt-handler already has exactly the same check (verifying /dev/vhost-net is on the virt-launcher's moint namespace).

Done

**Review by EdDev — APPROVED** [review]
Thank you!

I am missing the same information to be in sync with the commit message, but I will not block on it.

**Comment by ormergi** [comment]
> Thank you!
> 
> I am missing the same information to be in sync with the commit message, but I will not block on it.

Done

**Comment by xpivarc** [comment]
I am confused, are we able to run with emulation?

**Pull request merged**
