### PR TITLE
Update go base image to use current stable debian 12 base

### PR DESCRIPTION
**Pull request by brianmcarey**
**What this PR does / why we need it**:

The builder image (centos stream 9) uses glibc verion 2.34 - the old stable go base image (debian 11) has
glibc verion 2.31.

This causes issues with running binaries that are built by the builder image
and run inside of containers based on the go base image.

```
/usr/bin/csv-generator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/csv-generator)
/usr/bin/csv-generator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/csv-generator)
```

Updating the base image to the current stable debian 12 resolves these
issues as the current stable has glibc version 2.36[1]

[1] https://tracker.debian.org/pkg/glibc

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @xpivarc @dhiller 

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:
```release-note
Update container base image to use current stable debian 12 base
```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve

Thank you @brianmcarey

**Comment by oshoval** [comment]
removing lgtm, and adding back, to check updated phase plugin duty

/lgtm cancel

**Comment by oshoval** [comment]
sorry that it caused rerunning, but just 1h max passed, so no much harm made
had to check all is fine

**Comment by oshoval** [comment]
some flake here (not related to the PR i guess, but not familiar with it)
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11068/pull-kubevirt-e2e-k8s-1.29-sig-compute-migrations/1749778140860780544

**Comment by oshoval** [comment]
Since we bumped pull-kubevirt-e2e-k8s-1.29-ipv6-sig-network
after the lgtm approve happens, it means it will run by tide only when all jobs pass
because it missed the phase comment
but its ok

**Pull request merged**
