### PR TITLE
[release-0.41] make-generate: updated license header year

### PR DESCRIPTION
**Pull request by enp0s3**
Signed-off-by: Igor Bezukh <ibezukh@redhat.com>

**What this PR does / why we need it**:
fix `make generate` leftovers

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
Thanks for the manual update!

/approve

**Comment by stu-gott** [comment]
Every change in this PR is in a comment? There are no code changes?

**Comment by enp0s3** [comment]
> Every change in this PR is in a comment? There are no code changes?

@stu-gott Yep, you are correct, why trigger all the lanes.

**Pull request merged**
