### PR TITLE
Properly count PRs by not counting merges by maintainers.

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Fixes the PRs count when generating the release notes. It was giving maintainers credit for PRs they merged. By ignoring the merges the counts are correct.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
Note, we just did this in CDI as well, I noticed while I was off I still had a huge number of PRs according to the release note script. It turns out it was counting all my merges as well. This PR fixes that.

**Comment by davidvossel** [comment]
> What I might want to add is actually top reviewers! (which is != mergers)

Personally, I like that stat given that's my primary role at the moment :D

**Comment by slintes** [comment]
I think it's hard to find something really fair.
Counting PRs? Some are small, some are big.
Counting commits? Some people commit often and have many small commits. Some squash them after a while, reducing the nr commits. Some just don't commit often and have more code in each one.
We should count changed lines of code! :wink: 
Or just skip that stat, at the end this is no competition, right? Just write the names in alphabetical order. :slightly_smiling_face: 
But if keep counting commits, yes, I think it's fair enough to also count merges.

**Comment by awels** [comment]
We have the same issue in CDI. I am the main merger for that project, and thus the main reviewer, however last month I was basically away the entire month so didn't do much. When I generated the stats, I had the highest count by far due to the most merges. As has been said above its not a competition on the most PRs, whatever. However its a decent indicator on the activity of people in the project, and IMO it was skewed by the merges being counted.

In CDI we decided to exclude merges, I opened this PR to explain our thoughts on this, and ultimately feel free to close it if you guys don't think it makes sense for your project.

**Comment by fabiand** [comment]
Thanks for raising this. Let's keep it as it is for now.

**Pull request closed without merging**
