### PR TITLE
Extend VMI status interfaces to reflect virt-laucnher pod interfaces names

### PR DESCRIPTION
**Pull request by ormergi**
**What this PR does / why we need it**:
- Extend the VMI status interfaces to also reflect the pod interface name.
- virt-controller update the new field according to the pod Multus network-status annotation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
The VMI status interface now reflects pod interface names.
```

### CODE REVIEW

**Comment by maiqueb** [comment]
Can you explain why this change is needed (in the PRs description)? What you're doing is clear, but why you need this is not.

**Comment by ormergi** [comment]
> Can you explain why this change is needed (in the PRs description)? What you're doing is clear, but why you need this is not.

It's still a draft so the description doesn't have all info.
Having the new attribute enable blocking unplug interface requests at virt-api level for legacy VMs (that have ordinal interface names net1, net2...).

We may not need to do this change eventually, the alternative is to raise an event saying unplug not supported for legacy VMs.

**Comment by ormergi** [comment]
Closing this for now as we dont need pod iface name is status at the moment.
/close

**Pull request closed without merging**
