### PR TITLE
[release-0.34] Revert test kubevirt cr

### PR DESCRIPTION
**Pull request by ashleyschuett**
**What this PR does / why we need it**:

Removes using the KubeVirt CR configuration object for all func tests. This is being reverted because it completely overrides existing kubevirt configurations instead of only modifying needed configuration values. This has the effect of making all tests which update the configuration fail for systems when they are configured or provisioned with the configmap resource. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vladikr** [comment]
oh... I was planning to use this in the #3937 ... 
How can we test the CR without this? :)

**Comment by ashleyschuett** [comment]
@vladikr it's not being reverted on master so you should still be okay for testing your PR

**Comment by rmohr** [comment]
> Removes using the KubeVirt CR configuration object for all func tests.

@ashleyschuett can you add a little bit more to the description? Like `reverting because it completely overrides existing kubevirt configurations instead of testing everything it can with the default configuration and just modifying needed bits`.

**Comment by rmohr** [comment]
@ashleyschuett here an issue which tracks what needs to be changed on master: https://github.com/kubevirt/kubevirt/issues/4317

**Comment by rmohr** [comment]
/retest

the known permission denied issue.

**Pull request merged**
