### PR TITLE
vnc_test: place err variable more locally

### PR DESCRIPTION
**Pull request by dankenigsberg**
Variables with a too-wide scope may have unexpected side-effects, particularly when multiple lambda closures are defined and used.
Let us define an err variable closer to its needed context.

Requested by @xpivarc on https://github.com/kubevirt/kubevirt/pull/11302#discussion_r1500332243

```release-note
NONE
```

### CODE REVIEW

**Review by xpivarc — APPROVED** [review]
/approve

**Comment by brianmcarey** [comment]
It looks like the phased plugin missed this PR  - cc @oshoval 

/test pull-kubevirt-e2e-windows2016
/test pull-kubevirt-e2e-kind-1.27-vgpu
/test pull-kubevirt-e2e-kind-sriov
/test pull-kubevirt-e2e-k8s-1.29-ipv6-sig-network
/test pull-kubevirt-e2e-k8s-1.27-sig-network
/test pull-kubevirt-e2e-k8s-1.27-sig-storage
/test pull-kubevirt-e2e-k8s-1.27-sig-compute
/test pull-kubevirt-e2e-k8s-1.27-sig-operator
/test pull-kubevirt-e2e-k8s-1.28-sig-network
/test pull-kubevirt-e2e-k8s-1.28-sig-storage
/test pull-kubevirt-e2e-k8s-1.28-sig-compute
/test pull-kubevirt-e2e-k8s-1.28-sig-operator

**Comment by oshoval** [comment]
> It looks like the phased plugin missed this PR - cc @oshoval
> 
> /test pull-kubevirt-e2e-windows2016 /test pull-kubevirt-e2e-kind-1.27-vgpu /test pull-kubevirt-e2e-kind-sriov /test pull-kubevirt-e2e-k8s-1.29-ipv6-sig-network /test pull-kubevirt-e2e-k8s-1.27-sig-network /test pull-kubevirt-e2e-k8s-1.27-sig-storage /test pull-kubevirt-e2e-k8s-1.27-sig-compute /test pull-kubevirt-e2e-k8s-1.27-sig-operator /test pull-kubevirt-e2e-k8s-1.28-sig-network /test pull-kubevirt-e2e-k8s-1.28-sig-storage /test pull-kubevirt-e2e-k8s-1.28-sig-compute /test pull-kubevirt-e2e-k8s-1.28-sig-operator

Hi
Ye it happens here and there, didnt see something in the logs, if we want to debug it we need to add more prints and fetch fresh logs once it happen.
We dont need to run it manually, tide will run it once all the required lanes are passing,
it is even better to not run it manually, so we will make sure it what happens even without
run_before_merge, as the fix should act as if there was one, based on the required_manually configuration only

**Pull request merged**
