### PR TITLE
e2e: Double number of e2e parallel nodes from 3 to 6

### PR DESCRIPTION
**Pull request by brianmcarey**
### What this PR does

Increasing the number of parallel nodes will reduce the runtime for e2e
test lanes that include parallel tests.

An increase in kubevirtci node memory is also required in order to benefit from
this increased parallelization. The new test clusters still fit within
the memory request limit of the test pods which is currently at 29GB.

| Job Name                               | #11524     | 7 day Avg | Time Saving |  
|----------------------------------------|------------|-------------|-------------|
| pull-kubevirt-e2e-k8s-1.29-sig-compute | 2hrs 46min | 3hrs 24min  | 38min       | 
|  pull-kubevirt-e2e-k8s-1.29-sig-operator |  1hr 40min | 1hr 38min |   2min       |   
|   pull-kubevirt-e2e-k8s-1.29-sig-network |   1hr 49min |  2hr 13min | 24min  | 
|   pull-kubevirt-e2e-k8s-1.29-sig-compute-migrations |   1hr 14min |  1hr 31min | 16min  | 
|   pull-kubevirt-e2e-k8s-1.29-sig-storage |   1hr 38min |  2hr 24min | 46min  |

After this PR merges - the reduction in time should be clearly visible in the kubevirt grafana instance:
https://grafana.ci.kubevirt.io/d/gY4hNc5Iz/kubevirt-kubevirt-e2e-test-runtimes?orgId=1&viewPanel=2&from=now-90d&to=now

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 
Mailing list discussion: https://groups.google.com/g/kubevirt-dev/c/2-YCqKYqCoM/m/HKW_Kl4kAQAJ

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by brianmcarey** [comment]
| Job Name                               | #11524     | 7 day Avg | Time Saving |  
|----------------------------------------|------------|-------------|-------------|
| pull-kubevirt-e2e-k8s-1.29-sig-compute | 2hrs 46min | 3hrs 24min  | 38min       | 
|  pull-kubevirt-e2e-k8s-1.29-sig-operator |  1hr 40min | 1hr 38min |   2min       |   
|   pull-kubevirt-e2e-k8s-1.29-sig-network |   1hr 49min |  2hr 13min | 24min  | 

There looks to be valuable reductions in runtime for the compute & network lanes - /cc @xpivarc @dhiller 

The storage lane fails consistently with three test failures - @akalenyu could you take a look to see if it is straightforward to fix them ?
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11524/pull-kubevirt-e2e-k8s-1.29-sig-storage/1772174823011651584

**Comment by dhiller** [comment]
Another option on this would be to add env vars in the job configs, there we could adjust a bit more if need be.

**Comment by akalenyu** [comment]
> Job Name	#11524	7 day Avg	Time Saving
> pull-kubevirt-e2e-k8s-1.29-sig-compute	2hrs 46min	3hrs 24min	38min
> pull-kubevirt-e2e-k8s-1.29-sig-operator	1hr 40min	1hr 38min	2min
> pull-kubevirt-e2e-k8s-1.29-sig-network	1hr 49min	2hr 13min	24min
> pull-kubevirt-e2e-k8s-1.29-sig-compute-migrations	1hr 14min	1hr 31min	16min
> There looks to be valuable reductions in runtime for the compute & network lanes - /cc @xpivarc @dhiller
> 
> The storage lane fails consistently with three test failures - @akalenyu could you take a look to see if it is straightforward to fix them ? https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11524/pull-kubevirt-e2e-k8s-1.29-sig-storage/1772174823011651584

Yeah, I think I see what happens.
Could you give this commit a try:
https://github.com/akalenyu/kubevirt/commit/e1a3b3de175538ee642803cd562be106c311893e

If it works we will follow up on https://github.com/kubevirt/kubevirt/pull/4616/commits/747eabc6588ff80c698edf925711d5ffb909a7ea#r534508169
So it doesn't bite us later

**Comment by akalenyu** [comment]
> Job Name	#11524	7 day Avg	Time Saving
> pull-kubevirt-e2e-k8s-1.29-sig-compute	2hrs 46min	3hrs 24min	38min
> pull-kubevirt-e2e-k8s-1.29-sig-operator	1hr 40min	1hr 38min	2min
> pull-kubevirt-e2e-k8s-1.29-sig-network	1hr 49min	2hr 13min	24min
> pull-kubevirt-e2e-k8s-1.29-sig-compute-migrations	1hr 14min	1hr 31min	16min
> There looks to be valuable reductions in runtime for the compute & network lanes - /cc @xpivarc @dhiller
> 
> The storage lane fails consistently with three test failures - @akalenyu could you take a look to see if it is straightforward to fix them ? https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11524/pull-kubevirt-e2e-k8s-1.29-sig-storage/1772174823011651584

BTW check out https://groups.google.com/g/kubevirt-dev/c/2-YCqKYqCoM/m/X-kvCI4UAQAJ

**Comment by brianmcarey** [comment]
> > Job Name	#11524	7 day Avg	Time Saving
> > pull-kubevirt-e2e-k8s-1.29-sig-compute	2hrs 46min	3hrs 24min	38min
> > pull-kubevirt-e2e-k8s-1.29-sig-operator	1hr 40min	1hr 38min	2min
> > pull-kubevirt-e2e-k8s-1.29-sig-network	1hr 49min	2hr 13min	24min
> > pull-kubevirt-e2e-k8s-1.29-sig-compute-migrations	1hr 14min	1hr 31min	16min
> > There looks to be valuable reductions in runtime for the compute & network lanes - /cc @xpivarc @dhiller
> > The storage lane fails consistently with three test failures - @akalenyu could you take a look to see if it is straightforward to fix them ? https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11524/pull-kubevirt-e2e-k8s-1.29-sig-storage/1772174823011651584
> 
> Yeah, I think I see what happens. Could you give this commit a try: [akalenyu@e1a3b3d](https://github.com/akalenyu/kubevirt/commit/e1a3b3de175538ee642803cd562be106c311893e)

That looks better - thanks @akalenyu 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11524/pull-kubevirt-e2e-k8s-1.29-sig-storage/1772926638888062976
> 
> If it works we will follow up on [747eabc#r534508169](https://github.com/kubevirt/kubevirt/commit/747eabc6588ff80c698edf925711d5ffb909a7ea#r534508169) So it doesn't bite us later

**Comment by brianmcarey** [comment]
| Job Name                               | #11524     | 7 day Avg | Time Saving |  
|----------------------------------------|------------|-------------|-------------|
| pull-kubevirt-e2e-k8s-1.29-sig-compute | 2hrs 46min | 3hrs 24min  | 38min       | 
|  pull-kubevirt-e2e-k8s-1.29-sig-operator |  1hr 40min | 1hr 38min |   2min       |   
|   pull-kubevirt-e2e-k8s-1.29-sig-network |   1hr 49min |  2hr 13min | 24min  | 
|   pull-kubevirt-e2e-k8s-1.29-sig-compute-migrations |   1hr 14min |  1hr 31min | 16min  | 
|   pull-kubevirt-e2e-k8s-1.29-sig-storage |   1hr 38min |  2hr 24min | 46min  |

**Comment by akalenyu** [comment]
> Job Name	#11524	7 day Avg	Time Saving
> pull-kubevirt-e2e-k8s-1.29-sig-compute	2hrs 46min	3hrs 24min	38min
> pull-kubevirt-e2e-k8s-1.29-sig-operator	1hr 40min	1hr 38min	2min
> pull-kubevirt-e2e-k8s-1.29-sig-network	1hr 49min	2hr 13min	24min
> pull-kubevirt-e2e-k8s-1.29-sig-compute-migrations	1hr 14min	1hr 31min	16min
> pull-kubevirt-e2e-k8s-1.29-sig-storage	1hr 38min	2hr 24min	46min
> @xpivarc @dhiller @akalenyu - I think these time savings merit giving this change a try to see how it runs when all lanes are using it? What do you think?

I'd run it for the sport through some cycles, but ultimately I think we need to sit down and do the resource math
so we know if there is a risk of contention

**Comment by fabiand** [comment]
@brianmcarey @dhiller please provide a link to the metric which allows us to measure the impact of this change.

Please include the link in the PR description.

**Review by dhiller — COMMENTED** [review]
/approve

**Comment by dhiller** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: _[dhiller](https://github.com/kubevirt/kubevirt/pull/11524#pullrequestreview-1962949506)_ **Once this PR has been reviewed and has the lgtm label**, please assign [fabiand](https://github.com/fabiand) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubevirt%2Fkubevirt).
> 
> Needs approval from an approver in each of these files:
> * **[OWNERS](https://github.com/kubevirt/kubevirt/blob/main/OWNERS?rgh-link-date=2024-04-24T16%3A10%3A48Z)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment Approvers can cancel approval by writing `/approve cancel` in a comment

I think you need to rebase this PR, since the OWNERS are IIRC taken from the PR itself (which is admittedly odd)

**Comment by brianmcarey** [comment]
> > [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> > This pull-request has been approved by: _[dhiller](https://github.com/kubevirt/kubevirt/pull/11524#pullrequestreview-1962949506)_ **Once this PR has been reviewed and has the lgtm label**, please assign [fabiand](https://github.com/fabiand) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).
> > The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubevirt%2Fkubevirt).
> > Needs approval from an approver in each of these files:
> > 
> > * **[OWNERS](https://github.com/kubevirt/kubevirt/blob/main/OWNERS?rgh-link-date=2024-04-24T16%3A10%3A48Z)**
> > 
> > Approvers can indicate their approval by writing `/approve` in a comment Approvers can cancel approval by writing `/approve cancel` in a comment
> 
> I think you need to rebase this PR, since the OWNERS are IIRC taken from the PR itself (which is admittedly odd)

Rebased on the latest main.

**Review by dhiller — COMMENTED** [review]
/approve

**Comment by dhiller** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: _[dhiller](https://github.com/kubevirt/kubevirt/pull/11524#pullrequestreview-2022046278)_ **Once this PR has been reviewed and has the lgtm label**, please assign [fabiand](https://github.com/fabiand) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubevirt%2Fkubevirt).
> 
> Needs approval from an approver in each of these files:
> * **[OWNERS](https://github.com/kubevirt/kubevirt/blob/main/OWNERS?rgh-link-date=2024-04-25T09%3A46%3A57Z)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment Approvers can cancel approval by writing `/approve cancel` in a comment

@brianmcarey I figure there's a problem with the approve plugin. I read [here](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#filters) that there's an issue and from the issue I read it should be fixed. Need to investigate what is wrong here.

**Comment by dhiller** [comment]
@brianmcarey I see it now. It is the missing approval rights for `images` changes I believe.

@iholder101 @enp0s3 could one of you take a quick look and approve for us if possible? Thank you!

**Comment by iholder101** [comment]
Looks great! Thanks @brianmcarey! I think it's defenitely a step towards the right direction. I'd leave LGTMing for someone from sig/buildsystem.

I also agree with @akalenyu that we may want to play with these settings further, i.e. run all lanes with 3, 4, 5 .. workers and see what happens. Perhaps we should even have a job that will be triggered once in a (long) while to let us tweak settings when necessary.

/approve

**Comment by dhiller** [comment]
> BTW, off-topic but caught my attention:
> 
> > [APPROVALNOTIFIER] This PR is NOT APPROVED
> > This pull-request has been approved by: dhiller
> 
> probably demands a fix :)

I believe this to be correct, since I am no more a top level approver and the `images` folder needs a top level approver approval, sinnce it is missing an OWNERS file.

**Review by dhiller — APPROVED** [review]

**Comment by iholder101** [comment]
> > BTW, off-topic but caught my attention:
> > > [APPROVALNOTIFIER] This PR is NOT APPROVED
> > > This pull-request has been approved by: dhiller
> > 
> > 
> > probably demands a fix :)
> 
> I believe this to be correct, since I am no more a top level approver and the `images` folder needs a top level approver approval, sinnce it is missing an OWNERS file.

@dhiller Right, but it says "this PR is not approved" and then contradicts itself by saying "the PR was approved by dhiller"

**Comment by xpivarc** [comment]
> Job Name 	#11524 	7 day Avg 	Time Saving
> pull-kubevirt-e2e-k8s-1.29-sig-compute 	2hrs 46min 	3hrs 24min 	38min
> pull-kubevirt-e2e-k8s-1.29-sig-operator 	1hr 40min 	1hr 38min 	2min
> pull-kubevirt-e2e-k8s-1.29-sig-network 	1hr 49min 	2hr 13min 	24min
> pull-kubevirt-e2e-k8s-1.29-sig-compute-migrations 	1hr 14min 	1hr 31min 	16min
> pull-kubevirt-e2e-k8s-1.29-sig-storage 	1hr 38min 	2hr 24min 	46min
> 
> @xpivarc @dhiller @akalenyu - I think these time savings merit giving this change a try to see how it runs when all lanes are using it? What do you think?

Looks good to me but I agree with @akalenyu . We need to do the math.
/hold
Adding hold as the CI is not in the best shape and this has a chance to further degrade the CI. We should merge it once we are stable to be able to asses if this PR is making contention or not.

**Comment by brianmcarey** [comment]
> > Job Name 	#11524 	7 day Avg 	Time Saving
> > pull-kubevirt-e2e-k8s-1.29-sig-compute 	2hrs 46min 	3hrs 24min 	38min
> > pull-kubevirt-e2e-k8s-1.29-sig-operator 	1hr 40min 	1hr 38min 	2min
> > pull-kubevirt-e2e-k8s-1.29-sig-network 	1hr 49min 	2hr 13min 	24min
> > pull-kubevirt-e2e-k8s-1.29-sig-compute-migrations 	1hr 14min 	1hr 31min 	16min
> > pull-kubevirt-e2e-k8s-1.29-sig-storage 	1hr 38min 	2hr 24min 	46min
> > @xpivarc @dhiller @akalenyu - I think these time savings merit giving this change a try to see how it runs when all lanes are using it? What do you think?
> 
> Looks good to me but I agree with @akalenyu . We need to do the math. 

I did some testing locally on this - checking the resource usage on the kubevirtci nodes themselves. Running the sig-compute lane with 6 parallel processes didn't lead to any resource bottle necking. 

The cpu load averages peaked at 5.2 for the 1 min average and never went above 2.5 for the 15 min average. The kubevirtci nodes are configured with 6 vcpu so this looks to be well able to handle the load. There were also no memory issues on the kubevirtci nodes. 

For the resource utilization on the workloads cluster - we schedule the e2e test pods based on memory requests of 29GB - 2 kubevirtci nodes of 11GB fall well within this memory request. The CPU usage on the workloads cluster is under utilized as we are limited by memory really. When the cluster is running the max amount of e2e jobs, we use just under 1/3 of the available in the cluster. 

From my testing, this change is definitely worth the time savings per lane.

**Comment by xpivarc** [comment]
/hold cancel
Let's monitor the failures if they increase...

**Comment by dhiller** [comment]
> > > BTW, off-topic but caught my attention:
> > > > [APPROVALNOTIFIER] This PR is NOT APPROVED
> > > > This pull-request has been approved by: dhiller
> > > 
> > > 
> > > probably demands a fix :)
> > 
> > 
> > I believe this to be correct, since I am no more a top level approver and the `images` folder needs a top level approver approval, sinnce it is missing an OWNERS file.
> 
> @dhiller Right, but it says "this PR is not approved" and then contradicts itself by saying "the PR was approved by dhiller"

The first line is the overall status of approval (which at that point was correct, since I am not an approver for all) where the following line just states who issued an approval. I agree that the message is suboptimal, OTOH I have no good idea on how to improve it.

**Pull request merged**
