### PR TITLE
Clean vm.go

### PR DESCRIPTION
**Pull request by xpivarc**
### What this PR does

1. Remove not used functions
2. Unify v1 and metav1 imports
3. Remove redundant args

Fixes #

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by fossedihelm — APPROVED** [review]
Pretty clean! Thank you

**Review by orelmisan — COMMENTED** [review]
Thank you for the cleanup @xpivarc 
Since there are at least three different changes, please consider performing them over several commits as it helps with the review.

**Comment by alicefr** [comment]
I agree with @orelmisan, you could split the changes in 3 commits. 

Additionally, for the patch operations, you could use the [PatchSet type](https://github.com/kubevirt/kubevirt/blob/main/pkg/apimachinery/patch/patch.go#L68). This is just a suggestion and feel free to ignore it.

/approve
/hold
Hold to let you fix the commits

**Pull request merged**
