### PR TITLE
[backport] Don't crash on invalid DataVolume URL

### PR DESCRIPTION
**Pull request by stu-gott**
This is a backport of #1996 to the Release 0.13 branch

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by slintes** [comment]
wow, only 1 lane did actually run tests....
http://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/3403/artifact/ci_build_summary.html

**Comment by slintes** [comment]
ci test please

**Comment by stu-gott** [comment]
Same outcome. Only one lane ran.

**Comment by stu-gott** [comment]
ci test please

**Comment by stu-gott** [comment]
ci test please

**Comment by stu-gott** [comment]
ci test please

**Comment by stu-gott** [comment]
ci test please

**Comment by stu-gott** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
I ran local k8s-1.11.0 and os-3.11.0, tests look fine.

**Pull request merged**
