### PR TITLE
Filter pod route destined to default gateway

### LINKED ISSUE #845: Avoid creating static route to our default gateway
I may have run into an issue related to [#830](https://github.com/kubevirt/kubevirt/pull/830). It seems I'm getting a static route to my gateway, and no default gateway.

Since this is merged I'll just create a new issue.

My lease looks like this:

> lease {
>   interface "eth0";
>   fixed-address 172.16.52.146;
>   option subnet-mask 255.255.255.255;
>   option routers 169.254.1.1;
>   option dhcp-lease-time 86313600;
>   option dhcp-message-type 5;
>   option domain-name-servers 192.168.0.10;
>   option dhcp-server-identifier 10.11.12.13;
>   option classless-static-routes 32.169.254.1.1 169.254.1.1;
>   renew 3 2019/05/01 23:04:52;
>   rebind 0 2020/08/16 23:48:11;
>   expire 6 2020/12/19 20:48:11;
> }

And results in routing table like this:

> [root@fedora ~]# ip route show
> 169.254.1.1 via 169.254.1.1 dev eth0 proto static

And I can't get anywhere. Maybe in the "// Filter out irrelevant routes" it should skip routes with destination IP of the gateway? Or does that defeat your purpose?

I ran some debugging and I'm getting a VIF route entry of Src=nil Dst.IP=169.254.1.1/32

If I do filter out the Dst == router route I'm back in business:

> [root@fedora ~]# ip route show
> default via 169.254.1.1 dev eth0

### PR DESCRIPTION
**Pull request by mlsorensen**
Do not pass a static route that has destination IP
of the default gateway. This commit fixes #845

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by mlsorensen** [comment]
On second thought this might not be quite right. Let me ensure I'm only filtering routes that are Dst == default route and Src == nil

**Comment by mlsorensen** [comment]
I ran into a secondary issue, when no routes are found it caused errors in the DHCP client to have option 121 provided but empty. Tcpdump correctly identified the error but dhclient ended up with some kind of overflow and filled the option data with garbage. The above commit should fix that as well.

**Comment by vladikr** [comment]
ok to test

**Comment by mlsorensen** [comment]
I'll break the filter out and add a test for it.

**Comment by stu-gott** [comment]
retest this please

**Comment by vladikr** [comment]
The functional tests are failing but this is not related to this change. 
I'm going to merge this. Thank you for the contribution.

**Pull request merged**
