### PR TITLE
virt-handler: Remove node access

### PR DESCRIPTION
**Pull request by RamLavi**
### What this PR does
As of today a virt-handler has "full" access to all Nodes. Therefore installing Kubevirt means that every node will have a service account that can be miss used to influence the scheduling of other Pods, potentially with a more privileged service account.
This PR introduces ShadowNode CRD, intended for internal use for virt-handler. The virt-handler will keep read access to nodes but will lose write access. Write will be "proxied" through ShadowNode object and write to the actual Node will be done by virt-controller who will filter what type of labels and annotations will be proxied.
virt-controller entities (node-controller, topology-updater) will also move to write to the shadowNode, so that the shadowNode controller is the only entity that patches the node. 

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

Special notes for your reviewer:
See https://github.com/kubevirt/community/pull/246

There are a few cons to the approach. Creating 1:1 shadow nodes to nodes and therefore increasing the #api calls we do and storage we take.
Because we "proxy" the node updates we now depend on the availability of virt-controller and we increase the work required by virt-controller. In the worst case, we can see heartbeat timeout more in corner cases. The latency of sync increases because we remove the "test" on the node.

For less critical issues, right now we remove any .* kubevirt.io .* label and annotation. This might break a few cases where we or others use these labels to enhance scheduling or other functionality.

Release note:
```release-note
NONE
```

### CODE REVIEW

**Comment by fabiand** [comment]
Hey. How does this pr relate to #10131?

cc @xpivarc

**Comment by xpivarc** [comment]
> Hey. How does this pr relate to #10131?
> 
> cc @xpivarc

Ram is taking this over.

**Comment by RamLavi** [comment]
I have some work to do on this PR. returning to draft

**Comment by RamLavi** [comment]
/hold
until the proposal PR https://github.com/kubevirt/community/pull/246 gets approved.
/cc @fabiand

**Comment by RamLavi** [comment]
I think we can close this PR for now, as it seems this is not the direction we are going to implement.

**Pull request closed without merging**
