### PR TITLE
Generate and collect junit results on our unittests

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Ginkgo requires writing its own junit results. They are wired differently than junit results for standard go tests. In order to write and collect them, the following is node:

 * Tell `rules_go` to not write their own report by setting `GET_TEST_WRAP` to `0`.
 * Converge all unit tests to a common setup function which wire ginkgo to write junit reports
 * Make use of this common setup function across all our unittests
 * Finally copy all results to the artifacts directory, so that prow can collect and display them

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
The first run with visible junit results: There are a lot, but it should also help seeing easier which exact tests takes which time.

**Comment by rmohr** [comment]
/cc @vasiliy-ul 

FYI

**Review by fgimenez — APPROVED** [review]
/lgtm

**Comment by rmohr** [comment]
@fgimenez thanks for the review. Added a small addition to synchronize the suite names with the bazel target to make things more consistent. Would be great if you can have another look.

**Review by fgimenez — APPROVED** [review]
/lgtm

**Pull request merged**
