### PR TITLE
make shallow copy of config parameter

### LINKED ISSUE #5964: GetKubevirtClientFromRESTConfig should not change the content of parameter
**This is a FEATURE REQUEST**:
/kind enhancement

GetKubevirtClientFromRESTConfig will change the content of `config` parameter.  This will overwrite the value of field `NegotiatedSerializer` silently.
```
k.istio, err = istioclient.NewForConfig(config)
k.kubevirt, err = kubecli.GetKubevirtClientFromRESTConfig(config)
if err != nil {
    return nil, err
}
...
```
This code snipped makes method UseOrCreateObject of  k8s.io/client-go return error likes `W0701 15:23:18.284503   57102 reflector.go:436] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"Node\" is registered for version \"v1\" in scheme \"pkg/runtime/scheme.go:100\"") has prevented the request from succeeding`, because `NegotiatedSerializer` has been overwritten.

I have read packages like [prometheus-operator/prometheus-operator](https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/client/versioned/clientset.go#L64), [k8s.io/apiextensions-apiserver](https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/client/clientset/clientset/clientset.go#L66) . These package won't change content of `config` parameter. So I think it's better for  GetKubevirtClientFromRESTConfig not to change paramter of `config`.

### PR DESCRIPTION
**Pull request by xyz-li**
**What this PR does / why we need it**:

Fixes #5964 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
/lgtm
/approve

@xyz-li thanks!

**Comment by xyz-li** [comment]
Failed again. Does it has connection with my pr.

**Comment by rmohr** [comment]
> Failed again. Does it has connection with my pr.

Does not look like it. Looks like this is the error:

```
12:13:48: docker: error pulling image configuration: Get "https://quay.io/v2/phoracek/lspci/blobs/sha256:440380ed3762b4eb120ea60242c794787ceb8feec6881b4e3ff2f6d88f276dde": net/http: TLS handshake timeout.
```

**Pull request merged**
