### PR TITLE
[release 0.50] Bump kubevirtci and align test.sh file

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
Release 0.50 presubmit config requires kind-1.23-vgpu provider and migration lanes management.
Manual cherry-pick  of
[https://github.com/kubevirt/kubevirt/pull/7198](https://github.com/kubevirt/kubevirt/pull/7198)
[https://github.com/kubevirt/kubevirt/pull/7165](https://github.com/kubevirt/kubevirt/pull/7165)
[https://github.com/kubevirt/kubevirt/pull/7242](https://github.com/kubevirt/kubevirt/pull/7242)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
/cc @dhiller

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve

**Comment by fossedihelm** [comment]
Needs https://github.com/kubevirt/kubevirt/pull/7459

**Comment by dhiller** [comment]
Can not be run in 0.50: kubevirt/project-infra#1989

**Review by dhiller — APPROVED** [review]

**Pull request merged**
