### PR TITLE
Fix perfscale buckets error

### PR DESCRIPTION
**Pull request by machadovilaca**
### What this PR does
Before this PR:

There was an error setting up prometheus.Histogram buckets in operator-observability package

After this PR:

operator-observability version is updated to 0.0.14 which already has the bug fix

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Fix perfscale buckets error
```

### CODE REVIEW

**Comment by alaypatel07** [comment]
@machadovilaca can you please describe what was the bug and the effects? It looks like due to this bug we are not getting any Histogram metrics in kubevirt?

Also, should this be a release blocker since the original code is in release v1.2?

**Comment by machadovilaca** [comment]
> @machadovilaca can you please describe what was the bug and the effects? It looks like due to this bug we are not getting any Histogram metrics in kubevirt?
> 
> Also, should this be a release blocker since the original code is in release v1.2?

@alaypatel07 Yes, this should be backported

Histogram metrics should still, but custom bucket definition was not being correctly configured, so we were using the default histogram buckets: https://github.com/prometheus/client_golang/blob/7ac90362b02729a65109b33d172bafb65d7dab50/prometheus/histogram.go#L265

**Comment by machadovilaca** [comment]
@alaypatel07 were you able to verify that the values are back to normal in https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11264/pull-kubevirt-e2e-k8s-1.27-sig-performance/1758190792507133952 ?

**Review by enp0s3 — COMMENTED** [review]
/approve

**Comment by dhiller** [comment]
> @alaypatel07: only [kubevirt](https://github.com/orgs/kubevirt/people) org members may request release block label

@alaypatel07 the `release-blocker` falsely claims that all KubeVirt org members are allowed, but only TopLevel approvers are allowed to issue `/release-blocker` command

**Comment by alaypatel07** [comment]
@dhiller thanks a lot for checking. I'll ping one of maintainers next time I want to assign release blocker to an issue

**Pull request merged**
