### PR TITLE
Patch/sock connector exec

### PR DESCRIPTION
**Pull request by steigr**
**What this PR does / why we need it**:

Safe resources when `virtctl [vnc|console] vm` by `exec`ing into socat and remove dependency on PID-file for serial connection tracking.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by rmohr** [comment]
ci test please

**Comment by slintes** [comment]
Thanks for your contribution, lgtm!
The failing tests are unrelated. But since the tests on several environments did not even run for some reason, I'd like to trigger CI again.

ci test please

**Comment by slintes** [comment]
ci test please

**Comment by slintes** [comment]
@rmohr should be this one?
https://github.com/kubevirt/kubevirt/blob/master/tests/console_test.go#L96

**Comment by rmohr** [comment]
> @rmohr should be this one?
> https://github.com/kubevirt/kubevirt/blob/master/tests/console_test.go#L96

I found that one. It only tests if we can still connect after a previous connection was established. As far as I understand it, it does not test, if a previous connection gets terminated. I am just a little bit cautious be cause of the regressions we had here.

**Comment by slintes** [comment]
@steigr CI looks much better now. We will check if the existing automatic tests are good enough, but a manual test had the expected result. Thanks again for your contribution :) Will merge.

**Pull request merged**
