### PR TITLE
[release-0.53]node-labeller: Take CPU features into account when labeling nodes && fixing MinCPUModel's field logic

### PR DESCRIPTION
**Pull request by Barakmor1**
**What this PR does / why we need it**:
manual back-port of:
https://github.com/kubevirt/kubevirt/pull/9325
and of:
https://github.com/kubevirt/kubevirt/pull/7765

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder101** [comment]
Thank you!
/approve

Please add the BZ links into the PR description

**Comment by Barakmor1** [comment]
here is the BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=2218193

**Review by enp0s3 — COMMENTED** [review]
/approve

**Pull request merged**
