### PR TITLE
tests: increase nc idle and wait timeouts

### PR DESCRIPTION
**Pull request by phoracek**
**What this PR does / why we need it**:

On slower/busy clusters, netcat often times out with:

Ncat: Idle timeout expired (1000 ms).

In order to avoid this issue, we increase the idle and wait timeouts.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by danielBelenky** [comment]
@phoracek we need to cherry-pick this change to 0.26, right?

**Comment by phoracek** [comment]
@danielBelenky oh you are spoiling me. Thanks for the review!

Correct, this should go to 0.26.

**Comment by phoracek** [comment]
Bacport: https://github.com/kubevirt/kubevirt/pull/3243

**Pull request merged**
