### PR TITLE
Stabilize unschedulable node tests a bit

### PR DESCRIPTION
**Pull request by maya-r**
**What this PR does / why we need it**:
In https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4387/pull-kubevirt-e2e-k8s-cnao-1.19/1365490827337404416 we have a flake where test_id 1635 failed to find a node that is schedulable in 60 seconds.
The test that ran before it seems like it has an opportunity to "bleed" an unschedulable node by getting the node before the patch is applied.

Make this less likely to happen by first checking that the node was updated.

While here, bump the time we wait for a schedulable node - 1 minute timeout for something that takes a minute is quite a narrow fit.

and then the A
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
This fixes the latest flake in #4833, but I have seen it flake elsewhere in the same test during testing :-/

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
@maya-r here a PR which addresses this: #4760

**Comment by rmohr** [comment]
> @maya-r here a PR which addresses this: #4760

but not completely ready yet.

**Comment by rmohr** [comment]
@maya-r I think this PR can not address https://github.com/kubevirt/kubevirt/issues/4833. The issue there was that a race between  the VMI start and the virt-handler removal happened. If virt-handler did not take over the VMI before it got evicted from the node, the VMI was moved to failed by the vmi-controller instead of the node-controller. The later one is what we wanted to tests. I think only #5221 can properly address it, since otherwise the webhook is in the way.

**Comment by rmohr** [comment]
@maya-r forget my last comment, I hit the wrong line in a bug list. Your PR may fix it. Can it be that https://github.com/kubevirt/kubevirt/pull/4760 fixes this by accident too?

**Comment by maya-r** [comment]
Yes, it's possible #4760 fixes this. I'll close this PR in the meantime.

**Pull request closed without merging**
