### PR TITLE
Revert "Merge pull request #3612 from ashleyschuett/patch-configuration"

### PR DESCRIPTION
**Pull request by EdDev**
The change causes constant failure when running focused tests [1],
failing on [2].

Another issue the PR introduced has a proposed fix [3].

1. https://github.com/kubevirt/kubevirt/blob/
   bfe9df0830484f261055071fea4287cc1d795eed/tests/vmi_networking_test.go#L677
2. https://github.com/kubevirt/kubevirt/blob/master/tests/utils.go#L2687
3. https://github.com/kubevirt/kubevirt/pull/4143

This reverts commit 78f37c81ff982d96345e212c1da11d73f71565e7, reversing
changes made to 7b70b990b75fea594c0aca58f2b491b6714b246b.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Note that this PR collides with #4143 and attempts to resolve both known issues by reverting the original PR.
The current state makes it difficult to develop locally.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
@EdDev  is the failure consistent or only flaky?

**Comment by EdDev** [comment]
> @EdDev is the failure consistent or only flaky?

It is consistent when running locally the mentioned context.
On CI it is flaky, maybe because the tests run in a different order.

**Comment by davidvossel** [comment]
i believe I found the root cause. 

obsoleted by https://github.com/kubevirt/kubevirt/pull/4154

**Pull request closed without merging**
