### PR TITLE
Define timestamp when building containers

### LINKED ISSUE #2254: Container images are 49y old
/kind bug

**What happened**:

Just deployed KubeVirt (using HCO) and the pulled images are 49y old:

```shell
docker.io/kubevirt/virt-operator                       latest              118361cf815d        49 years ago        290 MB
docker.io/kubevirt/virt-controller                     latest              498ef9fb3bba        49 years ago        292 MB
docker.io/kubevirt/virt-api                            latest              5820ae856c0a        49 years ago        293 MB
docker.io/kubevirt/virt-handler                        latest              544efacdcceb        49 years ago        294 MB
```

```shell
$ docker inspect 5820ae856c0a | grep Created

  "Created": "1970-01-01T00:00:00Z",
```
Which is basically the Unix epoch.

**What you expected to happen**:

Images would be weeks/days old.

**How to reproduce it (as minimally and precisely as possible)**:

Just deploy KubeVirt.

**Anything else we need to know?**:

I don't have any Bazel experience myself but this seems to be related to Bazel [0] which would need `stamp = true` on the `container_image` definition to allow the use of workspace status variables. Once enabled,  `creation_time` should be added by default:

`String, optional, default to {BUILD_TIMESTAMP} when stamp = True, otherwise 0`

[0] https://github.com/bazelbuild/rules_docker/issues/52

**Environment**:
- KubeVirt version (use `virtctl version`): 
  Client Version: version.Info{GitVersion:"v0.17.0", GitCommit:"c0f960702dce718419a767f3913669f539229ff0", GitTreeState:"clean", BuildDate:"2019-05-05T08:09:14Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

  Server Version: version.Info{GitVersion:"v0.17.0-2+9c982f0cb214fd", GitCommit:"9c982f0cb214fdcf040edf674115826b01fc263f", GitTreeState
:"clean", BuildDate:"2019-05-06T16:46:44Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
  Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by iranzo**
**What this PR does / why we need it**:

Hopefully, setting timestamps on container build

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

Closes #2254 

**Special notes for your reviewer**:

**Release note**:

```release-note
Defines build timestamp so that containers are properly tagged with date when built
```

### CODE REVIEW

**Comment by iranzo** [comment]
> /lgtm
> Can you show how does it look now?

Same as in issue linked to this PR:

~~~sh
 iranzo  ~  date
jue jul 18 09:45:47 CEST 2019
 iranzo  ~  docker pull docker.io/kubevirt/virt-api
Using default tag: latest
Trying to pull repository docker.io/kubevirt/virt-api ... 
sha256:e8559de06fbbb27c84a66ff8a10856c89e49a03f5170b83766f46a99e31a90f9: Pulling from docker.io/kubevirt/virt-api
8f6ac7ed4a91: Pull complete 
9dad1b22e3c8: Pull complete 
c4b9b99b46ed: Pull complete 
ba289bef8627: Pull complete 
Digest: sha256:e8559de06fbbb27c84a66ff8a10856c89e49a03f5170b83766f46a99e31a90f9
Status: Downloaded newer image for docker.io/kubevirt/virt-api:latest
 iranzo  ~  docker images |grep virt-api
docker.io/kubevirt/virt-api   latest              1001ae0fd2a4        49 years ago        360 MB
 iranzo  ~  date
jue jul 18 09:46:13 CEST 2019
~~~

**Comment by cynepco3hahue** [comment]
ah I hoped it will fix this one `49 years ago`

**Comment by rmohr** [comment]
> ah I hoped it will fix this one `49 years ago`

this will soon be addressed. Then it will say `50 years ago`.

**Comment by iranzo** [comment]
Tried to fix it 49 years ago but git fails:

~~~sh
X11 forwarding request failed on channel 0
Enumerating objects: 62, done.
Counting objects: 100% (62/62), done.
Delta compression using up to 8 threads
Compressing objects: 100% (32/32), done.
Writing objects: 100% (35/35), 5.44 KiB | 928.00 KiB/s, done.
Total 35 (delta 14), reused 0 (delta 0)
remote: error: object 62c565e429e101259a398773c78085f6dfdcf282: badDateOverflow: invalid author/committer line - date causes integer overflow
remote: fatal: fsck error in packed object
error: remote unpack failed: index-pack abnormal exit
To github.com:iranzo/kubevirt.git
 ! [remote rejected]     timestamps -> timestamps (failed)
error: failed to push some refs to 'git@github.com:iranzo/kubevirt.git'
~~~

So, no way to fix it before it happens :joy:

**Comment by rmohr** [comment]
I don't think we want to fix it btw. It makes the container builds more reproducible. While the shasum of the image itself would not change if the timestamp changes, the image list for multi-arch images would change as far as I know. To work around that bazel people decided to always set it to zero.

**Comment by iranzo** [comment]
> I don't think we want to fix it btw. It makes the container builds more reproducible. While the shasum of the image itself would not change if the timestamp changes, the image list for multi-arch images would change as far as I know. To work around that bazel people decided to always set it to zero.

makes sense, but from the end user PoV, checking images and getting a list of 'being' 49 years old doesn't seem the way to go.

If for multiarch we want the same date for a 'release' it could use the 'release' date for it. Who should we contact to get more information on how is this done in other projects with multiarch, etc?

If we don't want to fix it, the original issue should be then updated and closed

**Comment by rmohr** [comment]
/close

works as expected. @iranzo if you disagree just reopen and we continue the discussion.

**Comment by iranzo** [comment]
I would prefer to have them dated, but I understand the need of reproducible builds :-)

**Pull request closed without merging**
