### PR TITLE
release v1.1.0 perf-scale-data

### PR DESCRIPTION
**Pull request by alaypatel07**
**What this PR does / why we need it**:
This commit updates the file name to `docs/perf-scale-benchmarks.md` where KubeVirt should publish the perf-scale graphs. The graphs are modified to have timeline of the releases and change in kubernetes providers. This will give users idea of how perf-scale data in changing relative to the KubeVirt code as well as k8s provider in CI clusters. The perf-scale-benchmarks.md document is updated to reflect the latest changes.

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alaypatel07** [comment]
@rthallisey @xpivarc Ideally this should be backport to v1.1 release branch after merge as well

**Comment by xpivarc** [comment]
I wonder if we want to keep the v1 data.

**Comment by alaypatel07** [comment]
@xpivarc it was discussed earlier in sig-scale calls to keep previous 3 release data just for historical reference (time wise it will be around 1 year's). So after v 1.1.3 the v1 release data will be removed

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by alaypatel07** [comment]
The e2e test kept failing, I rebased

/hold cancel

**Comment by alaypatel07** [comment]
@rthallisey @xpivarc please bless with labels again

**Comment by xpivarc** [comment]
@alaypatel07 CI is a little bit flaky

**Pull request merged**
