### PR TITLE
Provide additional registry disks

### PR DESCRIPTION
**Pull request by karmab**
```release-note
the following registry disk images are added:

- arch-registry-disk-demo
- debian-registry-disk-demo
- gentoo-registry-disk-demo
- ubuntu-registry-disk-demo
```

### CODE REVIEW

**Comment by simon3z** [comment]
@karmab I know it's more maintenance work, but do we feel we should keep a valid checksum/SHA to make sure the images are correctly downloaded and they're not broken/tampered with?

**Comment by simon3z** [comment]
> @simon3z You mean performing a checksum in the dockerfile to ensure it was downloaded correctly?

@fabiand yes, something like:

```
curl ... && sha512sum ...
```

So that if the downloaded image is not what we expect we have an early failure/feedback (already mentioned it's more maintenance work).
Or any other more advanced functional test to ensure images are booting.

**Comment by rmohr** [comment]
> Do we want to include an automated way to build and sync these optional registry disks so people can test with them?
> 
> Also, it might be nice for us to host a repo of common registryDisks for people to try out.

@davidvossel I want to pick up your comment. Let's create an extra repo on quay for all of these images.

**Comment by rmohr** [comment]
> @karmab I know it's more maintenance work, but do we feel we should keep a valid checksum/SHA to make sure the images are correctly downloaded and they're not broken/tampered with?

That would be very valuable and we should definitely do that.

**Comment by fabiand** [comment]
Any update, otherwise it will get closed.

**Comment by karmab** [comment]
@fabiand  i ve updated it this week actually, i think so let me know whether the md5sum is mandatory in the Docker file and what s missing for this to get merged

**Pull request closed without merging**
