### PR TITLE
Move test_id:1539 out of quarantine

### PR DESCRIPTION
**Pull request by ormergi**
Signed-off-by: Or Mergi <ormergi@redhat.com>

**What this PR does / why we need it**:
This PR move  test_id:1539 out of quarantine lane as it seems to be stable.
Between 21/2/2021 - 10/3/2021 it failed twice:

1. https://prow.k8s.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-cnao-1.19/1367009962546434048
failed due to a timeout along with other 53 tests due to timeouts as well.

2. https://prow.k8s.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-cnao-1.19/1367715990439202817
Reason: test_id:1539 failed due to virt-handler failed to send syncVMI command to virt-laucher pod
it failed because the VM failed to create as we can see in this [log](https://00f74ba44b66baab4437d56df86298651fac8d5214-apidata.googleusercontent.com/download/storage/v1/b/kubevirt-prow/o/pr-logs%2Fpull%2Fkubevirt_kubevirt%2F4916%2Fpull-kubevirt-e2e-k8s-cnao-1.19%2F1367715990439202817%2Fartifacts%2Fk8s-reporter%2F1_overview.log?jk=AFshE3XFFXJjC05rfpqE7zpnXKSSLMV-0Symf884BHObV19oHUSYpSUnuSxkXGC9QLOEeZ_aqhMlPg2SpdoyjvRBisdfaQ2Ixjhd9hofG0xgs905zOo1lkUJiu7cgh9OBWtD7CkdePN13Qq79_KSl26QnQeVjyS0IM8KF5ddInCmoCOuuqKKlPOyG2GJTkcBNBvWc2ZOYor-cQe_1vEs6pX9ptHg-Lt6afFo10aOr39s7c41xhNbv0qpBBGBCnutwpZo50AI1RhyWd_XMyG8Y7cluvVUmxACp1gxkRMtBd1KLlWCaYYgORObWfopQiKUNXKpPSBRWfqi_DYH3ZCYk-vXSAvGI0xVM4cRMtzrwj5aiQR4-NkV7s9DU2-HYhBoiHywadtI0LUqCr7PFWtBikY1PLTe_z5fuWIaMrRHBz_fQc4lSd_63_71mUjO9klbvJXYr5XOIKHvYiF6Cn96HbkYcKnhshJmZdhV9Kp3f1JLQaIOsGxOtd-8JX2FwThQSM3A6VYP-VLTszg47ZZ98rTz4XorH-kPY-YgR_OBiIZa_XuaFdv4zMr1AAA2dcmjUrfi0N_kyZFemMUvxZRxvdNJiryhtILYroBHlkKPBEK-43C0WuTAw4hEMERXByrNOGaBvI3HKIv0XvlxKTLfztMdvxHvbT413rDpM3iSBK2ZI-F_DwFD7GRYkWGRRUW4Yo4sER4CsFk70BbhDkApiXlMJKNCaTyZFPUAj7J0A9ZwCHs2LUhSVrqSYTCZ31CIv-39KDZ4HXisG0FjC6QulY-X6wT__nsvk4mAkE9OZXFrGkiiWE-HzDM4rAOPbVpF7ooO-85BWbVI9PPabzC0eAgcQi-Ia7AX2sVmwrUu10FHJGaCNVnMnqvqZvPqfuWwyw5Vm7D097BOjLgqY1BRQnvZ42jVCWATzti-6mYPgsctZ7RFSAtwYGYkUGvfLUW-KtZ2_Zo92GhVteWnmFZsl91-fdeQAPIZINFRRTyXppOwvZKNv3bM2sX6SdGrqxoKWCy1xvWhxgF0aqLMORbmywU_nbG1SVSxRHNmqLITSeE5rPEeUEw4BBSaBsTv2yB0T-MlvCc&isca=1) 
I think its related to the CI health

@fedepaol @phoracek 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fgimenez** [comment]
Thanks @ormergi this test failed last Friday and it was the only tests failing in the suite, I think we should not bring it right away without any change. Let's wait at least until next Friday and check if it is no longer failing to consider removing it from quarantine.

**Comment by ormergi** [comment]
@fgimenez Its been two weeks and this test is stabilized
 Can we move this test out of quarantine now?

**Review by fgimenez — APPROVED** [review]
/lgtm

test_id:1539 has been stable for 2 weeks now, it can join again the stable suite.

**Review by EdDev — APPROVED** [review]

**Comment by AlonaKaplan** [comment]
Or, do we have an idea why this test was failing and what was changed that now it is passing?

**Comment by ormergi** [comment]
> Or, do we have an idea why this test was failing and what was changed that now it is passing?

We saw this test failed twice in the past 2-3 weeks, first it failed along 53 other tests
second it failed due to a VMI that failed to create, it crushed during syncVMI invoked by virt-handler during creation (the domain did not created yet)
I noticed we hit `CIDRNotAvailable` error on kube-controller-manager log, it fixed by  https://github.com/kubevirt/kubevirt/pull/5207
Its seems that this was something transient that related to CI health, I couldn't find something wrong with the test code.

We let this test run on QUARNTINE lane for two weeks to verify it is stabilized.

**Comment by AlonaKaplan** [comment]
@ormergi thanks for the thorough response.
/approve

**Pull request merged**
