### PR TITLE
rpm: Drop libvirt storage driver

### LINKED ISSUE #4825: Drop libvirt-daemon-driver-storage for libvirt v6.9.0+
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

As of libvirt 6.9.0, the QEMU driver no longer unnecessarily depends on the storage driver, and so it should be possible to stop including the `libvirt-daemon-driver-storage-core` package in containers once a newer libvirt version is imported.

**Anything else we need to know?**:

Original issue: https://github.com/kubevirt/libvirt/issues/61
libvirt fix: https://gitlab.com/libvirt/libvirt/-/commit/accdc0e7730739f398e392c23bc8380d3574a878

### PR DESCRIPTION
**Pull request by andreabolognani**
**What this PR does / why we need it**:

KubeVirt never used the storage driver, and starting with libvirt 6.9.0 it's no longer necessary to keep it around.

**Which issue(s) this PR fixes**:

Fixes #4825

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by andreabolognani** [comment]
These look like they might be genuine failures... I'll investigate.

**Comment by rmohr** [comment]
/retest
/lgtm
/approve

Nice.

**Comment by rmohr** [comment]
> These look like they might be genuine failures... I'll investigate.

Yes, looks like it: https://search.ci.kubevirt.io/?search=tests%2Fstorage%2Fdatavolume.go%3A118&maxAge=48h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by rmohr** [comment]
> KubeVirt never used the storage driver, and starting with libvirt 6.9.0 it's no longer necessary to keep it around.

btw, do you see possibilities to get rid of other dependencies, like e.g. python?

**Comment by andreabolognani** [comment]
> btw, do you see possibilities to get rid of other dependencies, like e.g. python?

@rmohr as the QEMU package becomes increasingly modular, we should be able to drop many of the `qemu-kvm-block-*` and `qemu-kvm-ui-*` binary packages along with their dependencies, which will hopefully result in noticeable space savings. I'm planning to look into that after libvirt's footprint has been minimized.

I'm not sure what you're talking about with regards to Python though. AFAIK neither libvirt nor QEMU explicitly depends on Python, so there's nothing to be removed there; on the other hand, dnf being written in Python means it's considered a protected package in Fedora, and I don't think there's a non-hacky way of not having it in the virt-launcher container.

**Comment by rmohr** [comment]
> I'm not sure what you're talking about with regards to Python though. AFAIK neither libvirt nor QEMU explicitly depends on Python,

In theory that sounds like great news, here a quick and dirty investigation on what definitely pulls in libvirt:

```
$ repoquery -q --installed --whatrequires python3 | grep policycoreutils
policycoreutils-python-utils-0:3.0-2.fc32.noarch
python3-policycoreutils-0:3.0-2.fc32.noarch
```

Let's see what brings in `policycoreutils-python-utils`:

```
$ repoquery -q --installed --whatrequires policycoreutils-python-utils
flatpak-selinux-0:1.6.5-1.fc32.noarch
setroubleshoot-server-0:3.3.23-1.fc32.x86_64
swtpm-0:0.3.0-1.20200218git74ae43b.fc32.x86_64
```

We only have `swtpm` inside our launcher container, following that:

```
$ repoquery -q --installed --whatrequires swtpm
swtpm-tools-0:0.3.0-1.20200218git74ae43b.fc32.x86_64
```

And following `swtpm-tools`:

```
$ repoquery -q --installed --whatrequires swtpm-tools
libvirt-daemon-driver-qemu-0:7.2.0-1.fc32.x86_64
```

**Comment by andreabolognani** [comment]
> There may be more dependencies, also unreladed to libvirt/qemu but this one on python3 is definitely coming from libvirt.

@rmohr Right. libvirt's swtpm support uses `swtpm_setup` and `swtpm_ioctl` from the `swtpm-tools` package, and those tools are written in Python.

I guess there are several ways to remove the indirect dependency on Python, from relegating swtpm support to its own optional subpackage to trying to convince the swtpm upstream to rewrite those in another language. Needless to say, these have different degrees of likelihood to their success :)

Ultimately though, even if we were to remove this dependency you'd still be unable to completely remove Python from the container because dnf depends on it.

I think we should focus on minimizing the number of libvirt and QEMU components that end up in the container, as that will likely yield the most significant savings and we have way more control over that part.

**Comment by andreabolognani** [comment]
> That is the trick. There is no `dnf` in the container :)

Interesting! Can you point out the build step responsible for stripping that from the `fedora:32` image that's used as base? I haven't been able to find it myself.

Looking again, it would seem that `swtpm_setup` is the only tool that's written in Python, while the rest of the project is implemented in C. Perhaps the maintainer would consider reimplementing that component in C? Or perhaps another compiled language such as Rust?

That sounds like the only viable way forward: KubeVirt doesn't have swtpm support right now, but I think we can safely assume that it will be implemented at some point, and so even if we made the swtpm part completely optional in libvirt it would not be a long-term solution...

**Comment by andreabolognani** [comment]
> We only use rpms from fedora 32, but this is a scratch container. That is what `bazeldnf` does. It reads rpm repos, does the dependency resolution for them and stuffs the content of the RPMs into a scratch containers.

Right! I knew what bazeldnf did with RPMs, but I missed the part where the resulting container was built `FROM scratch`. Thanks for the clarification!

I have opened https://github.com/stefanberger/swtpm/issues/437 explaining the issue and asking the maintainer to consider remove the dependency on Python. Let's see how they feel about that :)

**Pull request merged**
