### PR TITLE
Ensure cmdserver is responsive before marking virt-launcher ready

### PR DESCRIPTION
**Pull request by davidvossel**
This patch gives us a strong guarantee that the cmd server is definitely processing requests before the VM start flow beings.  It's unlikely that this fixes any of the errors we are seeing in #937 , but it does however limit the possible causes. 

related to #937

### CODE REVIEW

**Comment by davidvossel** [comment]
retest this please

**Comment by davidvossel** [comment]
retest this please

**Comment by rmohr** [comment]
Fixed the crio-log permissin problem on the CI links. The crio logs have this:

```
• Failure in Spec Setup (BeforeEach) [61.287 seconds]
Networking
/root/go/src/kubevirt.io/kubevirt/tests/vm_networking_test.go:48
  VirtualMachine attached to the pod network [BeforeEach]
  /root/go/src/kubevirt.io/kubevirt/tests/vm_networking_test.go:146
    should be able to reach
    /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
      the Inbound VM
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

      Timed out after 30.171s.
      Expected
          <bool>: false
      to equal
          <bool>: true

      /root/go/src/kubevirt.io/kubevirt/tests/utils.go:864
------------------------------
level=info timestamp=2018-05-04T02:30:34.517527Z pos=utils.go:235 component=tests msg="Created virtual machine pod virt-launcher-testvm5pnrt-44zcf"
level=info timestamp=2018-05-04T02:30:34.582446Z pos=utils.go:235 component=tests msg="Created virtual machine pod virt-launcher-testvmpll7j-79rl7"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xf06cc2]

goroutine 448 [running]:
kubevirt.io/kubevirt/tests.NewConsoleExpecter.func1(0x12e1160, 0xc4200c2380, 0x0, 0xc4204e27a8, 0xc4204e27c0, 0xc420980060)
        /root/go/src/kubevirt.io/kubevirt/tests/utils.go:957 +0x32
created by kubevirt.io/kubevirt/tests.NewConsoleExpecter
        /root/go/src/kubevirt.io/kubevirt/tests/utils.go:956 +0x329
```

This here does not introduce the issue, but we need a fix ...

**Comment by davidvossel** [comment]
> This here does not introduce the issue, but we need a fix ...
tracking here. #988

**Comment by fabiand** [comment]
Any reason of why the PR got merged with failing tests?

**Comment by davidvossel** [comment]
> Any reason of why the PR got merged with failing tests?

our test suite is unstable. This patch is actually to addresses one aspect of that instability and needs to be merged.

**Pull request merged**
