### PR TITLE
sidecar to inject qemu args

### PR DESCRIPTION
**Pull request by ibrokethecloud**
### What this PR does
Before this PR:
PR introduces an additional sample sidecar to inject additional qemu args to the domain definition, based on annotations present on the VMI.

After this PR:
Users can fine tune qemu args in the domain definition to control specific behavior. 

Fixes #
https://github.com/kubevirt/kubevirt/issues/11093
### Why we need it and why it was done in this way
The following tradeoffs were made:
The sidecar approach seems the least disruptive means to perform this operation without changing core kubevirt api to allow inject of random qemu arguments.

The following alternatives were considered:

Links to places where the discussion took place: 
Please refer to conversation from here: https://github.com/kubevirt/kubevirt/issues/11093#issuecomment-2078541705
### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note

```

### CODE REVIEW

**Comment by victortoso** [comment]
I wrote one in the past too, see https://github.com/kubevirt/kubevirt/pull/9166#issuecomment-1768039885

**Review by victortoso — COMMENTED** [review]
You might be able to write this in python and attach to a configmap and enable it with annotation, instead of having to build a container image.

**Comment by alicefr** [comment]
@ibrokethecloud this should be doable with the configmap that @victortoso mentioned. I would avoid to add an new image. On the other hand, I think we are missing the documentation how to achieve it, @victortoso am I correct? If so, would you mind to add the example in the user guide?

**Comment by victortoso** [comment]
Hi @alicefr and @ibrokethecloud 

I created a simple python script to add qemu env/args using sidecars + configmap and published it as a gist:
https://gist.github.com/victortoso/4a54ef0e75a2b917bb21cb33ec4da141

> would you mind to add the example in the user guide?

I'll propose adding it in the user-guide later Today.

Just for clarification, the steps using this example are:

1. The annotation for env/args is: `libvirt.vm.kubevirt.io/qemuArgs`, see how the data was set [here](https://gist.github.com/victortoso/4a54ef0e75a2b917bb21cb33ec4da141#file-vmi-with-sidecar-hook-configmap-yaml-L6)
2. Create the configmap e.g: `k create -f examples/my-config-map.yaml`
3. Create the VMI (should have sidecar metadata properly set, see it [here](https://gist.github.com/victortoso/4a54ef0e75a2b917bb21cb33ec4da141#file-vmi-with-sidecar-hook-configmap-yaml-L16))

Cheers,

**Pull request closed without merging**
