### PR TITLE
Add cluster-profiler to bazel build command 

### PR DESCRIPTION
**Pull request by fgimenez**
Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

**What this PR does / why we need it**: Similar to #6390, we need it to prevent errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6304/pull-kubevirt-e2e-k8s-1.19-operator/1438032939706224640#1:build-log.txt%3A888

/cc @rmohr 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
/lgtm
/approve

@fgimenez it may make sense to just do `tools/...`. I wanted to optimize this for the e2e tests where not all tools are built, but I guess it is not worth the optimization if we then permanently run into that issue.

**Comment by fgimenez** [comment]
> @fgimenez it may make sense to just do `tools/...`. I wanted to optimize this for the e2e tests where not all tools are built, but I guess it is not worth the optimization if we then permanently run into that issue.

makes total sense done, PTAL

**Comment by rmohr** [comment]
oh, seems like we have a visibility problem with  `/...` on a rule.

**Comment by fgimenez** [comment]
> oh, seems like we have a visibility problem with `/...` on a rule.

indeed, it is weird given that the targets in the error are visible from other packages... In any case we get other errors even ignore the visibility issue, better tackle them separately IMO:
```
$ bazelisk build --config=$ARCHITECTURE --check_visibility=false //tools/...
INFO: Build option --check_visibility has changed, discarding analysis cache.
DEBUG: /home/fgimenez/.cache/bazel/_bazel_fgimenez/6a6cb7c381d4f6bf05c2b0cbbadc97c3/external/bazel_gazelle/internal/go_repository.bzl:189:18: org_golang_x_net: gazelle: finding module path for import golang.org/x/sys/windows: finding module path for import golang.org/x/sys/windows: package golang.org/x/sys/windows: build constraints exclude all Go files in /home/fgimenez/.cache/bazel/_bazel_fgimenez/6a6cb7c381d4f6bf05c2b0cbbadc97c3/external/bazel_gazelle_go_repository_cache/pkg/mod/golang.org/x/sys@v0.0.0-20210915083310-ed5796bab164/windows
DEBUG: /home/fgimenez/.cache/bazel/_bazel_fgimenez/6a6cb7c381d4f6bf05c2b0cbbadc97c3/external/bazel_gazelle/internal/go_repository.bzl:189:18: org_golang_x_crypto: gazelle: finding module path for import golang.org/x/sys/windows: finding module path for import golang.org/x/sys/windows: package golang.org/x/sys/windows: build constraints exclude all Go files in /home/fgimenez/.cache/bazel/_bazel_fgimenez/6a6cb7c381d4f6bf05c2b0cbbadc97c3/external/bazel_gazelle_go_repository_cache/pkg/mod/golang.org/x/sys@v0.0.0-20210915083310-ed5796bab164/windows
WARNING: /home/fgimenez/workspace/redhat/kubevirt/tools/BUILD.bazel:3:11: in go_library rule //tools:go_default_library: Target '//tools:go_default_library' violates visibility of target '//vendor/github.com/onsi/ginkgo/ginkgo:go_default_library'. Continuing because --nocheck_visibility is active
WARNING: /home/fgimenez/workspace/redhat/kubevirt/tools/BUILD.bazel:3:11: in go_library rule //tools:go_default_library: Target '//tools:go_default_library' violates visibility of target '//vendor/github.com/wadey/gocovmerge:go_default_library'. Continuing because --nocheck_visibility is active
WARNING: /home/fgimenez/workspace/redhat/kubevirt/tools/BUILD.bazel:3:11: in go_library rule //tools:go_default_library: Target '//tools:go_default_library' violates visibility of target '//vendor/mvdan.cc/sh/v3/cmd/shfmt:go_default_library'. Continuing because --nocheck_visibility is active
INFO: Analyzed 37 targets (1 packages loaded, 13331 targets configured).
INFO: Found 37 targets...
ERROR: /home/fgimenez/workspace/redhat/kubevirt/tools/marketplace/BUILD.bazel:3:11: GoCompilePkg tools/marketplace/go_default_library.a failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags selinux,selinux -src tools/marketplace/main.go -arc ... (remaining 17 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
tools/marketplace/main.go:48:48: crd.Spec.Version undefined (type "kubevirt.io/kubevirt/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1".CustomResourceDefinitionSpec has no field or method Version)
compilepkg: error running subcommand external/go_sdk/pkg/tool/linux_amd64/compile: exit status 2
INFO: Elapsed time: 2.050s, Critical Path: 0.10s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```
I've reverted the last change, now only cluster-profiler is added to the build command, PTAL.

**Comment by rmohr** [comment]
manually merging, since we have a separate fix for the arm64 build which is currently failing on what is fixed here :D

**Pull request merged**
