### PR TITLE
Bug: Missing rules Check whether the vm custom hostname rules are

### PR DESCRIPTION
**Pull request by matthewei**
correct

**What this PR does / why we need it**:

if the admin don't set hostname and we want to use vmi's name. The code just check vmi's name wheather it meets the NS1123LabelMaxLength. we need check all the hostname wheather it meet the rules.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by matthewei** [comment]
This is juest a limit for the vm.spec.hostname. So I'm not sure that the weebhook has validated it.

**Comment by matthewei** [comment]
By the way, I think it would be better if we use weebhook to realize it. what do you think?

**Comment by fossedihelm** [comment]
@matthewei Thanks for the PR and the contribution! I have some doubts about the PR.
As the function comment says:
```
// If the hostname is taken from vmi.Spec.Hostname
// then it already passed DNS label validations.
```
the `vmi.Spec.Hostname` was already validated by admission webhook (https://github.com/kubevirt/kubevirt/blob/d07f8d2b3a5d8d06b9fa2d65b4b2117685dc2936/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L1522-L1530)
Why should we do it again? Did you experience any malfunctions?

But I agree that we can save some computation with early exit. i.e.:

```
func SanitizeHostname(vmi *v1.VirtualMachineInstance) string {
	if vmi.Spec.Hostname != "" {
		return vmi.Spec.Hostname
	}
	
	hostName := strings.Split(vmi.Name, ".")[0]
	if len(hostName) > validation.DNS1123LabelMaxLength {
		hostname = hostName[:validation.DNS1123LabelMaxLength]

	}

	return hostName
}
```
Thank you

**Comment by enp0s3** [comment]
Hi @matthewei, thank you for taking care of it! As I see from [here](https://github.com/kubevirt/kubevirt/blob/d07f8d2b3a5d8d06b9fa2d65b4b2117685dc2936/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L144) the `Spec.Hostname` is already being validated. I don't think we need to do the same limitation for the VM name, since the behavior of taking the hostname from the VM name is a best-effort.

**Comment by matthewei** [comment]
Thanks @enp0s3 @ctrlaltdel, excited receiving your timely reply.

**Pull request closed without merging**
