### PR TITLE
build: Build KubeVirt with go v1.22.8

### PR DESCRIPTION
**Pull request by brianmcarey**
### What this PR does

There are a number of security fixes[1] included inbetween go v1.22.6 & go v1.22.8

[1] https://github.com/golang/go/issues?q=milestone%3AGo1.22.7+label%3ACherryPickApproved

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

/cc @dhiller @xpivarc 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Build KubeVirt with go v1.22.8
```

### CODE REVIEW

**Comment by iholder101** [comment]
Shouldn't go.mod also change?
https://github.com/kubevirt/kubevirt/blob/e307800b8fc56d83a82c461572bbb82fdab78187/go.mod#L3

**Comment by brianmcarey** [comment]
> Shouldn't go.mod also change?
> 
> https://github.com/kubevirt/kubevirt/blob/e307800b8fc56d83a82c461572bbb82fdab78187/go.mod#L3

This is the minimum go version required  - we have stopped updating this for every go bump as this is now a mandatory minimum since go 1.21 - it can cause problems for downstreams that may not have the latest go version available to build with.

**Review by xpivarc — COMMENTED** [review]
/approve

**Review by EdDev — COMMENTED** [review]
1.22.8 is already available.

**Comment by brianmcarey** [comment]
> 1.22.8 is already available.

Ok makes sense to update directly to 1.22.8 

/hold

**Review by EdDev — APPROVED** [review]
The commit messages have not been updated (to reflect the right version), but that is a nit in this case.

**Comment by brianmcarey** [comment]
> The commit messages have not been updated (to reflect the right version), but that is a nit in this case.

Thanks @EdDev - I am still waiting on the builder image to build with the new version before I update that commit. 

I think I am going to wait for https://github.com/kubevirt/kubevirt/pull/12729 to merge first anyway as there is a builder image update included there too. Going to keep the hold in place until then.

**Comment by brianmcarey** [comment]
Changes rebased on latest main and a new builder image has be published. This should be good to go now.

/hold cancel

**Review by EdDev — APPROVED** [review]

**Pull request merged**
