### PR TITLE
tests, net, kubectl: Drop status interface order test

### PR DESCRIPTION
**Pull request by EdDev**
### What this PR does

The existing e2e test has been covering the correct order of the reported interfaces in the VMI status.
The order influenced the correct correspondence between the status report and the interface which relates to the primary network.

This change removes the test from the e2e suite.
The existing unit tests [1] and the low functional impact of this scenario using `kubectl` merits the reduction in e2e coverage.

[1] https://github.com/kubevirt/kubevirt/blob/release-1.2/pkg/network/setup/netstat_test.go#L586

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note
```release-note
NONE
```

### CODE REVIEW

**Review by ormergi — APPROVED** [review]
Thanks for the PR, LGTM

**Comment by EdDev** [comment]
/approve

@orelmisan , it will be good if you also feedback on this one.
/hold

**Comment by acardace** [comment]
@EdDev you should not be approving your own PRs.

**Comment by EdDev** [comment]
> @EdDev you should not be approving your own PRs.

Thank you work the care & warning, but as I am the only approver in the SIG, I have no choice.
You are however welcome to propose a policy for this and we can check if it can work in our case.

**Comment by acardace** [comment]
@EdDev https://github.com/kubevirt/kubevirt/blob/main/OWNERS_ALIASES#L69 @AlonaKaplan is an approver too.

**Comment by EdDev** [comment]
> @EdDev https://github.com/kubevirt/kubevirt/blob/main/OWNERS_ALIASES#L69 @AlonaKaplan is an approver too.

Indeed, but the is phasing out and is not available at the moment to assist.
 
> You also have the kubevirt approvers you can ask to.

@enp0s3 is assisting the sig-network to approve things when the touched codebase is not in our control (yet).
But it is not practical to ask on all PRs such assistance.

There is actually nothing new happening, in the sig-network, the approver has always self-approved PRs due to the lack of maintainers.

I suggest you ref a policy or create one if you are interested in influence on the workflow.

**Review by orelmisan — APPROVED** [review]
Thank you

**Comment by EdDev** [comment]
change: Rebase

We now have lgtm from @ormergi and @orelmisan , releasing the PR:

/unhold

**Review by orelmisan — APPROVED** [review]

**Pull request merged**
