### PR TITLE
kubevirt/builder: Update sonobuoy version on dockerfile

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
This image is used for the periodic nightly job,
which runs kubevirt conformance.
Since v0.56.9 and the related changes are not backward compatible,
(new resultsDir and folder collecting feature)
we will need to update the Dockerfile, hack/dockerized once there is a new image
and then take the relevant changes of kubevirt and kubevirtci.

See https://github.com/kubevirt/kubevirt/pull/8304

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
/cc @brianmcarey 

Thanks

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by enp0s3** [comment]
@brianmcarey AFAIK we don't have a postsubmit job that builds and pushes the new builder, as well as an automated job that creates a PR in Kubevirt to bump the builder digest. Can you please rebase on this PR, push the image to Quay and update @oshoval regarding the new digest?

**Comment by brianmcarey** [comment]
The new builder image has been created: `quay.io/kubevirt/builder:2208300858-ce171084a`

I think this PR can be closed and the changes here be included in https://github.com/kubevirt/kubevirt/pull/8304

**Comment by oshoval** [comment]
> The new builder image has been created: `quay.io/kubevirt/builder:2208300858-ce171084a`
> 
> I think this PR can be closed and the changes here be included in #8304

Thanks a lot, on it

**Pull request closed without merging**
