### PR TITLE
[e2e] Quarantine flaky fsfreeze test

### PR DESCRIPTION
**Pull request by alromeros**
### What this PR does

Hey all,

There is a bug preventing snapshot-related finalizers from being removed after the resource is deleted. Following some offline discussions we've decided it's better to quarantine this test until the bug is addressed.

We should probably close https://github.com/kubevirt/kubevirt/pull/11236 after merging this.

**Release note:**
```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
This tests is suspect of causing ns deletion failures: https://search.ci.kubevirt.io/?search=should+successfully+delete+namespace&maxAge=168h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by dhiller** [comment]
> We should probably close #11236 after merging this.

@alromeros I can't follow here? Do you mean continue working on fixing with #11236, and after that is merged, unquarantine it?

**Comment by alromeros** [comment]
> > We should probably close #11236 after merging this.
> 
> @alromeros I can't follow here? Do you mean continue working on fixing with #11236, and after that is merged, unquarantine it?

That's just a fix that stops the test from failing but doesn't solve the real snapshot bug behind this. I posted it in the description just in case someone is interested but we should probably ignore it and wait for the real fix.

**Comment by dhiller** [comment]
> > > We should probably close #11236 after merging this.
> > 
> > 
> > @alromeros I can't follow here? Do you mean continue working on fixing with #11236, and after that is merged, unquarantine it?
> 
> That's just a fix that stops the test from failing but doesn't solve the real snapshot bug behind this. I posted it in the description to provide more context just in case someone is interested but we should probably ignore it and wait for the real fix.

Thank you for explaining it!

**Comment by ShellyKa13** [comment]
I would actually consider deleting this test altogether, not sure the scenario it checks justifies it.. I understand that it was added because the place that added the event doesnt have UT but just for catching an event in the scenario of fsfreeze fails not sure if its that important to do a functional test for it..

**Comment by alromeros** [comment]
> I would actually consider deleting this test altogether, not sure the scenario it checks justifies it.. I understand that it was added because the place that added the event doesnt have UT but just for catching an event in the scenario of fsfreeze fails not sure if its that important to do a functional test for it..

I get your point but other than the event failure (which I think is a good reason), I think being able to have a test case where we enable SELinux justifies its existence. I would also agree with deleting it if the test itself was flaky, but since the failure is caused by a non-related bug that should be eventually fixed I think removing the test is overkill. Let's see what others think.

**Comment by dhiller** [comment]
All tests green once, merging manually.

**Pull request merged**
