### PR TITLE
Remove the virtiofs SELinux rules from our custom policy

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
With the Centos 9 update, we got a much more recent version of virtiofsd.
Let's see if the functional tests pass with the new version and without our custom SELinux rules.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
Added a commit to remove the entire custom policy to see if it's still needed

**Comment by jean-edouard** [comment]
> Added a commit to remove the entire custom policy to see if it's still needed

It appears to still be needed for passt. Added a commit to make that explicit, and fix a couple of logic issues found along the way.

**Comment by vladikr** [comment]
That's really great news!

/approve
/lgtm

**Pull request merged**
