### PR TITLE
Use only `github.com/coreos/go-semver` package to work with semver

### PR DESCRIPTION
**Pull request by Juneezee**
### What this PR does

Before this PR:

Currently we are using 3 different packages to work with semver:

1. [github.com/Masterminds/semver](https://github.com/Masterminds/semver)
2. [github.com/blang/semver](https://github.com/blang/semver)
3. [github.com/coreos/go-semver](https://github.com/coreos/go-semver)

These 3 packages have very similar API. We can use just one and remove two dependencies from the project.

After this PR:

Replaces all usages of `github.com/Masterminds/semver` and `github.com/blang/semver` with `github.com/coreos/go-semver/semver`.

I chose `github.com/coreos/go-semver` to stay consistent with the `ClusterServiceVersionSpec` from `github.com/operator-framework/operator-lifecycle-manager`.

https://github.com/kubevirt/kubevirt/blob/b62599eee3960fb389330c870d1ca71a987e6a21/vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go#L10

https://github.com/kubevirt/kubevirt/blob/b62599eee3960fb389330c870d1ca71a987e6a21/vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go#L129-L131

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
@Juneezee thank you for the PR, we definitely need to consolidate those!
My one concern is about choosing the one from `coreos`... The repo doesn't seem to see much activity.
What about https://pkg.go.dev/golang.org/x/mod/semver ?
/test all

**Comment by Juneezee** [comment]
> @Juneezee thank you for the PR, we definitely need to consolidate those! My one concern is about choosing the one from `coreos`... The repo doesn't seem to see much activity. What about https://pkg.go.dev/golang.org/x/mod/semver ? /test all

Hi @jean-edouard, thanks for reviewing the PR.

I considered using https://pkg.go.dev/golang.org/x/mod/semver, decided to stick with the one from `coreos` since it's already a dependency we use for `ClusterServiceVersionSpec`.

https://github.com/kubevirt/kubevirt/blob/b62599eee3960fb389330c870d1ca71a987e6a21/pkg/virt-operator/resource/generate/csv/csv.go#L272

While we could use https://pkg.go.dev/golang.org/x/mod/semver, it would introduce another dependency for semver functionality. I'm open to making the switch if you think it's the better approach.

**Comment by jean-edouard** [comment]
> if you think it's the better approach

I do, but I'm curious to see what others think.
@xpivarc any opinion?

**Comment by jean-edouard** [comment]
> `golang.org/x/mod/semver` is the special one because it is does not fully comply with SemVer 2.0.0 specification:

Wow, that a great analysis, thank you!
If I understand correctly, the `v` prefix is **not** accepted by the spec. So only the `coreos` implementation is valid.
In that case, I now agree with you that it's the one we should use :)
/test all

**Comment by Juneezee** [comment]
@jean-edouard Could you re-run the test again for me? Thanks in advance!

**Comment by Juneezee** [comment]
@jean-edouard Rebased. It seems like you need to trigger the test again. Thanks.

**Comment by jean-edouard** [comment]
> @jean-edouard Rebased. It seems like you need to trigger the test again. Thanks.

:facepalm: sorry about that
/test all

**Comment by Juneezee** [comment]
@jean-edouard @fossedihelm Should I attempt to fix the failing test? It looks like the test is flaky

**Comment by fossedihelm** [comment]
/lgtm
@Juneezee All good, it is not related to this PR.
Thanks

**Pull request merged**
