### PR TITLE
[release-1.3] volume-migration: fix migration from source RWX volumes

### PR DESCRIPTION
**Pull request by alicefr**
Manual backport of https://github.com/kubevirt/kubevirt/pull/12818.

Fixes https://github.com/kubevirt/kubevirt/issues/12811

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by alicefr** [comment]
@fossedihelm do you mind taking a look to this manual backport?

**Comment by fossedihelm** [comment]
/lgtm
Thank you

**Pull request merged**
