### PR TITLE
errcheck, instancetype: Remove pkg/instancetype from exclude_files

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/sig code-quality

**What this PR does / why we need it**:

pkg/instancetype currently builds successfully without any errcheck errors and so can be removed from exclude_files.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
Wow, this one was easy 0_o

**Comment by lyarwood** [comment]
> Wow, this one was easy 0_o

^_^ I did see a discussion about this somewhere and thought I'd try to fix things up for instancetypes. Feel free to roll this up into another PR if there's already one active.

**Pull request merged**
