### PR TITLE
virt-controller, services: Remove passt memory overhead

### PR DESCRIPTION
**Pull request by EdDev**
### What this PR does

Remove passt memory overhead.

Passt binding required additional memory when no TCP/UDP ports are specified (i.e. all ports are forwarded to guest).
Once we used passt with binding plugins, we noticed that it works even without the overhead memory.

This change removes the overhead memory and checks it for the previous (deprecated) passt configuration.

TODO: Revert the `vmi_pass` test changes.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
@sbrivio-rh , I am unsure if I can explain what changed that it works now.
Have been there an improvement to the memory consumption of passt when it is set to forward all tcp/udp ports?

**Comment by sbrivio-rh** [comment]
I need a bit here as well ;)

**Comment by AlonaKaplan** [comment]
> Not on top of what we reported at https://bugs.passt.top/show_bug.cgi?id=20#c5 -- that was 487 MiB for TCP plus UDP, IPv4 and IPv6, and I still see that in the last CI run (see `memory/passt` in https://passt.top/builds/latest/test/test.log or skip to memory/passt of https://passt.top/passt/about/#continuous-integration).
> 
> However, do pods actually have IPv4 and IPv6 addressing at the same time? If not, we should be closer to this:
> 

Yes, pods in a dual stack cluster have both IPv4 and IPv6 addressing.

> ```
> > Memory usage: all TCP and UDP ports forwarded, IPv4
> Memory usage summary
> 
>                                                                       type: |  MiB |
>                                     used                                    |368.9 |
>                                   userspace                                 | 38.2 |
>                                    kernel                                   |331.6 |
>                                                                             '------'
> ...passed.
> ```
> 
> ...which should be similar for IPv6-only cases. Maybe at this point the overhead is not substantial enough to cause issues?

**Comment by EdDev** [comment]
@sbrivio-rh , could you share how you are checking the memory consumption?
If I can use the same in the pod, it will be nice.

**Comment by sbrivio-rh** [comment]
> @sbrivio-rh , could you share how you are checking the memory consumption?

Sure, it's implemented in passt's test suite [here](https://passt.top/passt/tree/test/memory/passt). Skip at the [`start_stop_diff`](https://passt.top/passt/tree/test/memory/passt?id=78901eeae3b37c0e15f34512e5ea0c1b7acc4642#n44) definition for a list of the essential commands.

**Comment by EdDev** [comment]
This is not relevant anymore.

/close

**Pull request closed without merging**
