### PR TITLE
[Release-0.53] Fix patch api conflict

### PR DESCRIPTION
**Pull request by Barakmor1**
**What this PR does / why we need it**:
This is a backport PR of:
https://github.com/kubevirt/kubevirt/pull/10027
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by enp0s3 — CHANGES_REQUESTED** [review]
@Barakmor1 Hi. Can you please commit `make generate` changes?

**Comment by Barakmor1** [comment]
Will do :)

**Comment by Barakmor1** [comment]
/close 
it seems like the patch doesn't work for this version the operator doesn't even use the heuristic

**Pull request closed without merging**
