### PR TITLE
Fix quarantine filtering

### PR DESCRIPTION
**Pull request by fgimenez**
**What this PR does / why we need it**: Quarantine filtering is not working properly, probably changes in the latest bump of prow broke it https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4977/pull-kubevirt-e2e-k8s-1.19-sig-storage/1386669499939295232 With these changes, we properly export the skip env var so that it is available on all the scripts. I've also taken the opportunity to remove an unused script related to quarantine.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by yuhaohaoyu — APPROVED** [review]
Now it's consistent with the other assignments to KUBEVIRT_E2E_SKIP env-var.

**Comment by fgimenez** [comment]
/test pull-kubevirt-e2e-k8s-1.19-operator

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5535/pull-kubevirt-e2e-k8s-1.19-operator/1386685483412623360 failed without actual error message, looking into this error but not related to this PR in any case

**Comment by fgimenez** [comment]
/test pull-kubevirt-e2e-k8s-1.19 

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5535/pull-kubevirt-e2e-k8s-1.19/1386688623105019904 not related to these changes

**Review by davidvossel — COMMENTED** [review]
/approve

**Pull request merged**
