### PR TITLE
tests: Move `ObjectEventWatcher` to a separate package

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
Moved `ObjectEventWatcher` from `utils.go` to a separate package.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Review by rhrazdil — APPROVED** [review]
/lgtm

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by akrejcir** [comment]
@rhrazdil can you give `/lgtm` again? I have only added a license comment, because I thought it would fix the `fossa` lane.

**Pull request merged**
