### PR TITLE
Run guest agent e2e tests in parallel

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Most guest agent tests can run in parallel. Only a small set (which
keeps Serial) needs to change cluster settings. This runs 8 more tests in parallel.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
@rmohr 
`Most guest agent unit tests ` typo?

**Comment by rmohr** [comment]
> `Most guest agent unit tests ` typo?

Ups. Fixed in the PR and the commit message. :+1:

**Review by xpivarc — APPROVED** [review]

**Pull request merged**
