### PR TITLE
[release-1.0] [e2e] Refactoring libwait & ignore EvictionStrategy warning

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
This is a manual backport of https://github.com/kubevirt/kubevirt/pull/9901 and https://github.com/kubevirt/kubevirt/pull/9948
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
/hold
waiting for https://github.com/kubevirt/kubevirt/pull/9948 to be merged

**Comment by fossedihelm** [comment]
/cc @xpivarc 
Can you have a look please? Thank you

**Review by xpivarc — COMMENTED** [review]
/approve
/hold
Maybe we can squash the two last commits?

**Comment by fossedihelm** [comment]
@xpivarc Done, thanks!
@akalenyu PTAL!
/unhold

**Comment by xpivarc** [comment]
@fossedihelm Thank you!

**Pull request merged**
