### PR TITLE
[release-0.49] Manual backport of 8222 - parallel testing complications

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
These issues are going to haunt us over here as well unless we backport the fixes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by xpivarc — COMMENTED** [review]
/lgtm

**Comment by akalenyu** [comment]
/test pull-kubevirt-e2e-kind-1.23-vgpu

I think this is a known failure which was addressed in newer kubevirtcis

**Pull request merged**
