### PR TITLE
Change iholder-redhat username to iholder101 in owners file

### PR DESCRIPTION
**Pull request by iholder101**
**What this PR does / why we need it**:
My username is changed from `iholder-redhat` to `iholder101`, updating owners file with the new username.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
Before we proceed with this change, @iholder101, you will have to add your new account to the kubevirt org. Otherwise we get an invalid owners file.

**Comment by iholder101** [comment]
> Before we proceed with this change, @iholder101, you will have to add your new account to the kubevirt org. Otherwise we get an invalid owners file.

Done :+1: 
Thanks for bringing it to my attention!

**Pull request merged**
