### PR TITLE
Ensure that clusters have enough CPU cores to run multi-core tests

### LINKED ISSUE #1690: "VirtualMachineInstance definition with 3 CPU cores should map cores to virtio net queues" fails
/kind bug

**What happened**:
CI fails on:
```
 (root).Tests Suite.Invoking jobs / check-patch.k8s-multus-1.11.1-release.el7.x86_64 / Configurations VirtualMachineInstance definition with 3 CPU cores should map cores to virtio block queues
5
2472, 2471, 2469, 2467, 2466
(root).Tests Suite.Invoking jobs / check-patch.k8s-multus-1.11.1-release.el7.x86_64 / Configurations VirtualMachineInstance definition with 3 CPU cores should map cores to virtio net queues
```

https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/test_results_analyzer/

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Under certain circumstances our test-infra consumed more than 1.0 cpu cores
which could make nodes non-fit for our cpu core tests. Increasing from 4
to 5 cpu cores to give the infrastrucure 2.0 cores.

Makes it possible to run the mult-core tests under more reliable conditions in the 1.11.1-multus clusters:

```
Configurations VirtualMachineInstance definition with 3 CPU cores should map cores to virtio net queues
Configurations VirtualMachineInstance definition with 3 CPU cores should map cores to virtio block queues
```

Further fixes

```
[Fail] IOThreads IOThreads Policies [It] Should honor shared ioThreadsPolicy 
/root/go/src/kubevirt.io/kubevirt/tests/vmi_iothreads_test.go:65
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1690

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
Can we guarantee that it will consume only 1-2 cores? Maybe we can set CPU limit on the `gocli run` command.

**Comment by rmohr** [comment]
@cynepco3hahue I think that we could only do that easily if we e.g. move all multus components in their own namespace and set a namespace limit. But I guess that then kubernetes would evict pods there if they go over the limits ... Other thoughts?

**Comment by cynepco3hahue** [comment]
@rmohr Or we can just skip this tests for multus environment :smile: I think it does not really need, because we have other jobs that run this test, and multus should not change anything in this case.

**Comment by rmohr** [comment]
For reference: https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/2486/artifact/ci_build_summary.html

**Comment by rmohr** [comment]
@vladikr @stu-gott, now it should finally be ok. Maybe you want to do another review.

**Comment by rmohr** [comment]
All three tests pass now across all lanes.

**Pull request merged**
