### PR TITLE
tests, net: Remove legacy SLIRP tests

### PR DESCRIPTION
**Pull request by EdDev**
### What this PR does

As SLIRP binding is targeted for deprecation, only a single test was suppose to be left that uses the binding plugin version.

However, it seems we missed a test in an unexpected location which keeps causing flakes due to its dependency on the quay.io domain.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
For ref, here is a failure example: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11615/pull-kubevirt-e2e-k8s-1.28-sig-network/1775510425878663168

**Comment by EdDev** [comment]
We have one flaky unit test: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11642/pull-kubevirt-unit-test/1775716072918355968
And a strange failure with the SR-IOV machine: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11642/pull-kubevirt-e2e-kind-sriov/1775716072419233792

/test pull-kubevirt-unit-test
/test pull-kubevirt-e2e-kind-sriov

**Review by ormergi — APPROVED** [review]

**Pull request merged**
