### PR TITLE
Improve migration proxy logging

### PR DESCRIPTION
**Pull request by davidvossel**
The logging in our migration proxy code has gaps that leave us without valuable information pertaining to when proxies are start, stop, and fail. As a result, it can be difficult to debug what occurs when a migration fails due to connectivity issues. Without more fidelity in our logs, it's difficult to rule out an issue within our components vs an issue occurring within the cluster network. 

With these changes, we can clearly see when proxies are created, where they are going, when they close, and why they close. 

Below is an example of the new output on the target node.. We have structured fields for the socket the proxy listens to, and the outbound connection.

```
{"component":"virt-handler","level":"info","listening":":::32813","msg":"proxy started listening","outbound":"libvirt-sock","pos":"migration-proxy.go:514","timestamp":"2021-04-22T15:55:13.632070Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::32813","msg":"Manager created proxy on target","outbound":"libvirt-sock","pos":"migration-proxy.go:181","timestamp":"2021-04-22T15:55:13.632162Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::33729","msg":"proxy started listening","outbound":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49152-source.sock","pos":"migration-proxy.go:514","timestamp":"2021-04-22T15:55:13.632233Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::33729","msg":"Manager created proxy on target","outbound":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49152-source.sock","pos":"migration-proxy.go:181","timestamp":"2021-04-22T15:55:13.632262Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::38763","msg":"proxy started listening","outbound":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49153-source.sock","pos":"migration-proxy.go:514","timestamp":"2021-04-22T15:55:13.632318Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::38763","msg":"Manager created proxy on target","outbound":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49153-source.sock","pos":"migration-proxy.go:181","timestamp":"2021-04-22T15:55:13.632341Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::38763","msg":"279 bytes copied outbound to inbound","outbound":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49153-source.sock","pos":"migration-proxy.go:442","timestamp":"2021-04-22T15:55:14.922241Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::38763","msg":"327 bytes copied from inbound to outbound","outbound":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49153-source.sock","pos":"migration-proxy.go:448","timestamp":"2021-04-22T15:55:14.922435Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::33729","msg":"0 bytes copied outbound to inbound","outbound":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49152-source.sock","pos":"migration-proxy.go:442","timestamp":"2021-04-22T15:55:15.105970Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::33729","msg":"74023264 bytes copied from inbound to outbound","outbound":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49152-source.sock","pos":"migration-proxy.go:448","timestamp":"2021-04-22T15:55:15.106233Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::32813","msg":"2372 bytes copied outbound to inbound","outbound":"libvirt-sock","pos":"migration-proxy.go:442","timestamp":"2021-04-22T15:55:15.340626Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::32813","msg":"22904 bytes copied from inbound to outbound","outbound":"libvirt-sock","pos":"migration-proxy.go:448","timestamp":"2021-04-22T15:55:15.341302Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::32813","msg":"Manager stopping proxy on target node","outbound":"libvirt-sock","pos":"migration-proxy.go:242","timestamp":"2021-04-22T15:55:15.411995Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::32813","msg":"proxy stopped listening","outbound":"libvirt-sock","pos":"migration-proxy.go:416","timestamp":"2021-04-22T15:55:15.412167Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::33729","msg":"Manager stopping proxy on target node","outbound":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49152-source.sock","pos":"migration-proxy.go:242","timestamp":"2021-04-22T15:55:15.412371Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::33729","msg":"proxy stopped listening","outbound":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49152-source.sock","pos":"migration-proxy.go:416","timestamp":"2021-04-22T15:55:15.412517Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::38763","msg":"Manager stopping proxy on target node","outbound":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49153-source.sock","pos":"migration-proxy.go:242","timestamp":"2021-04-22T15:55:15.412709Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":":::38763","msg":"proxy stopped listening","outbound":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49153-source.sock","pos":"migration-proxy.go:416","timestamp":"2021-04-22T15:55:15.412818Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
```

And here is output from the source node

```
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-source.sock","msg":"proxy started listening","outbound":"10.244.196.145:32813","pos":"migration-proxy.go:514","timestamp":"2021-04-22T15:55:13.647202Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-source.sock","msg":"Manager created proxy on source node","outbound":"10.244.196.145:32813","pos":"migration-proxy.go:308","timestamp":"2021-04-22T15:55:13.647255Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49152-source.sock","msg":"proxy started listening","outbound":"10.244.196.145:33729","pos":"migration-proxy.go:514","timestamp":"2021-04-22T15:55:13.647388Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49152-source.sock","msg":"Manager created proxy on source node","outbound":"10.244.196.145:33729","pos":"migration-proxy.go:308","timestamp":"2021-04-22T15:55:13.647418Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49153-source.sock","msg":"proxy started listening","outbound":"10.244.196.145:38763","pos":"migration-proxy.go:514","timestamp":"2021-04-22T15:55:13.647530Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49153-source.sock","msg":"Manager created proxy on source node","outbound":"10.244.196.145:38763","pos":"migration-proxy.go:308","timestamp":"2021-04-22T15:55:13.647556Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49153-source.sock","msg":"279 bytes copied outbound to inbound","outbound":"10.244.196.145:38763","pos":"migration-proxy.go:442","timestamp":"2021-04-22T15:55:14.922549Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49153-source.sock","msg":"327 bytes copied from inbound to outbound","outbound":"10.244.196.145:38763","pos":"migration-proxy.go:448","timestamp":"2021-04-22T15:55:14.922641Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49152-source.sock","msg":"0 bytes copied outbound to inbound","outbound":"10.244.196.145:33729","pos":"migration-proxy.go:442","timestamp":"2021-04-22T15:55:15.106388Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49152-source.sock","msg":"74023264 bytes copied from inbound to outbound","outbound":"10.244.196.145:33729","pos":"migration-proxy.go:448","timestamp":"2021-04-22T15:55:15.106492Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-source.sock","msg":"2372 bytes copied outbound to inbound","outbound":"10.244.196.145:32813","pos":"migration-proxy.go:442","timestamp":"2021-04-22T15:55:15.342243Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-source.sock","msg":"22904 bytes copied from inbound to outbound","outbound":"10.244.196.145:32813","pos":"migration-proxy.go:448","timestamp":"2021-04-22T15:55:15.342525Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-source.sock","msg":"Manager stopping proxy on source node","outbound":"10.244.196.145:32813","pos":"migration-proxy.go:321","timestamp":"2021-04-22T15:55:15.453983Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-source.sock","msg":"proxy stopped listening","outbound":"10.244.196.145:32813","pos":"migration-proxy.go:416","timestamp":"2021-04-22T15:55:15.454182Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49152-source.sock","msg":"Manager stopping proxy on source node","outbound":"10.244.196.145:33729","pos":"migration-proxy.go:321","timestamp":"2021-04-22T15:55:15.454823Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49152-source.sock","msg":"proxy stopped listening","outbound":"10.244.196.145:33729","pos":"migration-proxy.go:416","timestamp":"2021-04-22T15:55:15.454914Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49153-source.sock","msg":"Manager stopping proxy on source node","outbound":"10.244.196.145:38763","pos":"migration-proxy.go:321","timestamp":"2021-04-22T15:55:15.458318Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
{"component":"virt-handler","level":"info","listening":"c4c985cb-a40b-4f4f-aa72-39a946cba881-49153-source.sock","msg":"proxy stopped listening","outbound":"10.244.196.145:38763","pos":"migration-proxy.go:416","timestamp":"2021-04-22T15:55:15.458505Z","uid":"c4c985cb-a40b-4f4f-aa72-39a946cba881"}
```

```release-note
Improvements to migration proxy logging
```

### CODE REVIEW

**Comment by davidvossel** [comment]
/hold

I need to add more logging to the handleConnection function in migratino proxy

**Comment by davidvossel** [comment]
i changed this to a draft for now. Something strange is going on with our logger caching. I'm seeing output that doesn't make sense.

**Comment by davidvossel** [comment]
```
package main                                                                                                                   
                                                                                                                               
import (                                                                                                                       
        "kubevirt.io/client-go/log"                                                                                            
)                                                                                                                                                    
                                                                                                                               
func main() {                                                                                                                  
        log.InitializeLogging("fake-component")                                                                                
                                                                                                                               
        log.Log.With("arg1", "val1").Infof("msg 1")                                                                            
        log.Log.With("arg2", "val2").Infof("msg 2")                                                                                                                                                                                                      
}    
```

outputs

```
{"arg1":"val1","component":"fake-component","level":"info","msg":"msg 1","pos":"scratch.go:12","timestamp":"2021-04-21T21:30:10.991436Z"}
{"arg1":"val1","arg2":"val2","component":"fake-component","level":"info","msg":"msg 2","pos":"scratch.go:13","timestamp":"2021-04-21T21:30:10.991477Z"}
```

which is very curious. Apparently the `With()` arguments are cached forever on the default logger, and always get output.

**Comment by davidvossel** [comment]
/hold cancel

The logging works properly now. I added a new `CustomField()` function to our structured logger that will properly add new fields without caching it forever on the default logger like `With()` appears to do. As a follow up to this PR, i'll likely refactor the log pkg to make it less likely to accidentally encounter issues like i did with the `With()` function.

**Review by vladikr — APPROVED** [review]
Looks great! Thanks. This will definitely enhance our debugging abilities.
/lgtm
/approve

**Pull request merged**
