### PR TITLE
tests, network: Format codebase using `gofumpt`

### PR DESCRIPTION
**Pull request by EdDev**
### What this PR does

Cover the tests/network folder with the gofumpt formatter.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note
```release-note
NONE
```

### CODE REVIEW

**Review by orelmisan — APPROVED** [review]
Thank you @EdDev.
To ensure the nice order is kept, would you consider adding this directory to the linter configuration?

**Comment by EdDev** [comment]
> Thank you @EdDev. To ensure the nice order is kept, would you consider adding this directory to the linter configuration?

It is not yet possible because there are a lot of linter errors.
When I tried to handle them, I found many things that need to be sorted out first, which will probably will take some time. That is why I sent this one first, to reduce the changes later.

**Review by orelmisan — APPROVED** [review]

**Comment by iholder101** [comment]
Thank you @EdDev!
+1 for adding it to the linter's configuration in the future.

/approve

**Pull request merged**
