### PR TITLE
use canonical name for box

### PR DESCRIPTION
**Pull request by raghavendra-talur**
Signed-off-by: Raghavendra Talur <rtalur@redhat.com>

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by stu-gott** [comment]
Thanks @raghavendra-talur! I had to look up this setting to remember what it does. https://www.vagrantup.com/docs/vagrantfile/machine_settings.html

Just to be sure I understand: because we also specify config.vm.box_url, I understand this is basically an arbitrary value of our choosing?

**Comment by raghavendra-talur** [comment]
@stu-gott 
> Just to be sure I understand: because we also specify config.vm.box_url, I understand this is basically an arbitrary value of our choosing?

the condition is like this
```
if vm.box exists
    skip download from given url
else
   download from given url and name as vm.box
```

As this box url is same as what we get when we do `vagrant box add centos/7` and many users might already have it, I suggest we keep it same. If not, there would be two large files with different names but same content.

**Comment by fabiand** [comment]
@rmohr objections against merging this?

**Comment by rmohr** [comment]
ok to test

**Comment by fabiand** [comment]
Thanks

**Pull request merged**
