### PR TITLE
Point to latest kubevirtci commit to fetch changes in the kind lane.

### PR DESCRIPTION
**Pull request by fedepaol**
**What this PR does / why we need it**:
The sriov provider has a couple of changes, the most notable is that it now allows multiple nodes (instead of just one), to make it more similar to the sr-iov operator use case scenario (it is supposed to have at least one master and one worker).
This pr fetches the changes applied to the lane and makes the sr-iov tests run on two nodes. 

**Release note**:

```release-note

NONE

```

### CODE REVIEW

**Comment by fedepaol** [comment]
Let's see if we did not break the sr-iov lane :sweat_smile:

**Comment by danielBelenky** [comment]
I've also sent https://github.com/kubevirt/kubevirt/pull/2752 few days ago.
I guess that you're basing on a newer version so should I drop my change?

**Comment by fedepaol** [comment]
> I've also sent #2752 few days ago.
> I guess that you're basing on a newer version so should I drop my change?

Think so, mine got merged this afternoon

**Comment by danielBelenky** [comment]
ok, let's make sure this one is merged asap since I need the new kubevirtci version to verify my pr :)

**Comment by fedepaol** [comment]
> ok, let's make sure this one is merged asap since I need the new kubevirtci version to verify my pr :)

Sure :+1:

**Comment by fedepaol** [comment]
@danielBelenky :tada:

**Pull request merged**
