### PR TITLE
Add puzl.ee to adopters

### PR DESCRIPTION
**Pull request by NikPaushkin**
**What this PR does / why we need it**: We are [puzl.ee](https://puzl.ee), a cloud-native computing provider and a new adopter of Kubevirt, so we're extending the Kubevirt adopters list. On Puzl, people can run Kubevirt based cloud VMs using native k8s API or dashboard with per-second billing.

**Special notes for your reviewer**: Would be cool if you also add us to kubevirt.io website. Please find our logo here  https://static-cdn.puzl.ee/master/static/images/branding/logo__w-text__512.png

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by NikPaushkin** [comment]
I was trying to signoff many times, but it didn't pass still. Any ideas?
image

**Comment by xpivarc** [comment]
Welcome @NikPaushkin , you need to squash your commits.

**Comment by NikPaushkin** [comment]
@xpivarc Hi! It looks ok now.

**Comment by NikPaushkin** [comment]
@fabiand check the tests please, is there something wrong with them?

**Comment by xpivarc** [comment]
> @fabiand check the tests please, is there something wrong with them?

Nothing wrong here. You don't need to worry about this. The bot will retest failed jobs.

**Comment by fabiand** [comment]
@iholder-redhat the failed tests are spot on in the compute field. Do we already look at them?

**Pull request merged**
