### PR TITLE
Add missing test_ids

### PR DESCRIPTION
**Pull request by duyanyan**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
Add missing test_ids
**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by usrbinkat** [comment]
Thank you for the contribution @duyanyan. Can you add a description and possibly link to a bug/rfe as well?

**Comment by duyanyan** [comment]
> usrbinkat

Do you mean the description for memory dump feature? here is the link https://github.com/kubevirt/community/blob/main/design-proposals/vm-memory-dump.md

**Review by xpivarc — APPROVED** [review]
/approve

**Pull request merged**
