### PR TITLE
Label remaining tests as rook-ceph to include them in sig-storage

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:
As we have put together `rook-ceph` and `sig-storage` we need to add labels to existing tests that require rook-ceph to avoid skipping them.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @maya-r @awels @rmohr 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
Looks good to me

**Comment by rmohr** [comment]
@dhiller I see now regularly timeouts on the storage lanes. Can it be that we have to give the storage lane nodes now slightly more memory so that they can still schedule with ceph in place?

**Comment by dhiller** [comment]
> @dhiller I see now regularly timeouts on the storage lanes. Can it be that we have to give the storage lane nodes now slightly more memory so that they can still schedule with ceph in place?

Will have a look at that tomorrow ☺️

**Comment by dhiller** [comment]
> @dhiller I see now regularly timeouts on the storage lanes. Can it be that we have to give the storage lane nodes now slightly more memory so that they can still schedule with ceph in place?

@rmohr I have looked at the stats in grafana, there it looks like the memory gets hogged in somehow, i.e. other jobs pods (non storage) also are completely consuming the requested memory. Then I ran the job locally and checked with docker stats, the maximum I saw was ~ 25GiB. 

we can just try to increase the jobs requested memory though.

**Comment by dhiller** [comment]
/override pull-kubevirt-fossa

Unrelated project-infra config error tracked with this PR: https://github.com/kubevirt/project-infra/pull/1405

**Pull request merged**
