### PR TITLE
Make sure that all events associated to an object are observed in tests

### PR DESCRIPTION
**Pull request by rmohr**
By specifying on the ObjectEventWatcher in the functional tests a start
resourceVersion, we can first create an object and then establish a long
polling collection. This way we get all events which might have occoured
between the object modification and the watch start.

Signed-off-by: Roman Mohr <rmohr@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
@stu-gott thx. Do you have an idea for shorther method names which are still descriptive enough?

**Comment by stu-gott** [comment]
I assume you're talking about functions such as "SinceWatchedObjectResourceVersion"? I don't mind them, honestly. These are inside a test suite and not exposed in an API in any way--so we're always free to change them later.

**Pull request merged**
