### PR TITLE
Move SR-IOV functional tests into a separate suite

### PR DESCRIPTION
**Pull request by booxter**
This will allow us to target just SR-IOV specific tests for SR-IOV
test lane. This also makes it so that these tests are not even triggered for
multus CI jobs since we know we don't deploy SR-IOV components there.

In the future we will add a CI job for SR-IOV that will run the new SRIOV
suite.

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
ci test please

**Comment by booxter** [comment]
/hold

I'd like to merge other more involving pieces and not trigger conflicts with this one.

**Comment by booxter** [comment]
@SchSeba @phoracek please take a look. It's just moving the SR-IOV tests into a separate suite so that we don't need to focus on a complex regex in our (future) CI job.

**Comment by booxter** [comment]
@rmohr @slintes can we nudge this in? it's mostly moving code around.

**Pull request merged**
