### PR TITLE
Continue installing CDI by default

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Continue installing CDI like before #6339.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve

**Comment by awels** [comment]
I see there is a conditional check about CDI and arm, we actually publish arm cdi containers already, but don't for official builds (just nightlies)

**Pull request merged**
