### PR TITLE
Nominate machadovilaca as sig/observability approver

### PR DESCRIPTION
**Pull request by assafad**
### What this PR does / why we need it:
Nominate João Vilaça (@machadovilaca) as sig/observability approver. 
Since joined the project, João has been a [key contributor](https://github.com/kubevirt/kubevirt/graphs/contributors?from=2021-12-28&to=2024-06-08&type=c) to Kubevirt, especially in the observability area. He has over 60 [merged PRs](https://github.com/kubevirt/kubevirt/pulls?q=is%3Aclosed+is%3Apr+author%3Amachadovilaca+is%3Amerged+) and more than 30 [reviews](https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+commenter%3Amachadovilaca+-author%3Amachadovilaca).

### Special notes for your reviewer
/cc @enp0s3 @sradco

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by assafad** [comment]
/hold
waiting for @enp0s3's review

**Comment by enp0s3** [comment]
/approve
/unhold
@machadovilaca :partying_face:

**Pull request merged**
