### PR TITLE
Graduate the DynamicPodInterfaceNaming FG

### PR DESCRIPTION
**Pull request by orelmisan**
### What this PR does
The DynamicPodInterfaceNaming feature-gate was introduced in v1.4 by PR  https://github.com/kubevirt/kubevirt/pull/13078.

The feature works well for at least two projects.
No negative feedbacks were received from the community on the implementation other than the fact that is does
not support migration between two different primary interface names (in this case the migration will fail).

This scenario is not supposed to be supported for the foreseeable future.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by ormergi — APPROVED** [review]
LGTM

**Comment by EdDev** [comment]
@vladikr , per your suggestion, here is the added option on the original design proposal to consider a scenario in which the pod iface name may change: https://github.com/kubevirt/community/pull/356

We will do our best to reject support for such an edge scenario, but if we fail, we do have a way to mitigate it.

Hope this makes the graduation of the feature safer.

**Review by EdDev — APPROVED** [review]
Thank you!

/approve

**Comment by vladikr** [comment]
> @vladikr , per your suggestion, here is the added option on the original design proposal to consider a scenario in which the pod iface name may change: [kubevirt/community#356](https://github.com/kubevirt/community/pull/356)
> 
> We will do our best to reject support for such an edge scenario, but if we fail, we do have a way to mitigate it.
> 
> Hope this makes the graduation of the feature safer.

@EdDev It doesn't look like what I've suggested can fully mitigate the failure to live migrate VMs that are using this feature in case the target pod interface name changes.
As @orelmisan pointed out I've missed that you are deriving the interface name from the tap device name. 
We need a mitigation before we can graduate this, otherwise, I fear that users will face severe consequences if the interface name changes.

**Comment by orelmisan** [comment]
> > @vladikr , per your suggestion, here is the added option on the original design proposal to consider a scenario in which the pod iface name may change: [kubevirt/community#356](https://github.com/kubevirt/community/pull/356)
> > We will do our best to reject support for such an edge scenario, but if we fail, we do have a way to mitigate it.
> > Hope this makes the graduation of the feature safer.
> 
> @EdDev It doesn't look like what I've suggested can fully mitigate the failure to live migrate VMs that are using this feature in case the target pod interface name changes. As @orelmisan pointed out I've missed that you are deriving the interface name from the tap device name. We need a mitigation before we can graduate this, otherwise, I fear that users will face severe consequences if the interface name changes.

https://github.com/kubevirt/kubevirt/pull/13374 which partially implements https://github.com/kubevirt/community/pull/357 will mitigate the potential issue.

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/2f6b423620aff1920183469585b7ab226a73358b..ece89a39a7c2de58f28457de7e9c0b47b6ddf01f): Rebase.

**Comment by orelmisan** [comment]
@vladikr Following the merge of PR #13374, could we now move forward with this one? Please let me know if there's anything else needed on my end to proceed.

**Comment by vladikr** [comment]
> @vladikr Following the merge of PR #13374, could we move forward with this one? Please let me know if there's anything else needed on my end to proceed.

yes, thanks @orelmisan . I was waiting for the backport pr to get merged.

**Comment by orelmisan** [comment]
> > @vladikr Following the merge of PR #13374, could we move forward with this one? Please let me know if there's anything else needed on my end to proceed.
> 
> yes, thanks @orelmisan . I was waiting for the backport pr to get merged.

Thank you @vladikr, would it be possible for you to approve and hold?

**Comment by orelmisan** [comment]
#13387 was merged.
/unhold

**Pull request merged**
