### PR TITLE
Deprecate cpu and memory exceeds alerts

### PR DESCRIPTION
**Pull request by avlitman**
**What this PR does / why we need it**:
Deprecate the KubeVirtComponentExceedsRequestedCPU and KubeVirtComponentExceedsRequestedMemory alerts.
These alerts are wrong and don't need to be reported to the user.

**Which issue(s) this PR fixes**:
jira-ticket: https://issues.redhat.com/browse/CNV-37900

**Special notes for your reviewer**:

- https://issues.redhat.com/browse/CNV-38320 will handle adding a metric to be able to track this issue without creating noise.

**Release note**:

```release-note
KubeVirtComponentExceedsRequestedCPU and KubeVirtComponentExceedsRequestedMemory alerts are deprecated; they do not indicate a genuine issue.
```

### CODE REVIEW

**Comment by sradco** [comment]
/lgtm

Please remember to backport this PR to earlier releases.

**Review by enp0s3 — COMMENTED** [review]
Hi, can you please inform about the deprecation in the kubevirt-dev ML?

**Comment by iholder101** [comment]
:+1: :tada: 
Finally! :smile: very happy to see this PR.

However, I think that these alerts might still be valuable for debug and development purposes. Was it discussed to keep them as metrics instead of alerts, or as an alert that's considered debug-info that the user could filter out?

**Comment by iholder101** [comment]
In addition @avlitman please remove all references to Red Hat from the PR description (CNV versions, s/customer/user, "should be internal", etc).

**Comment by avlitman** [comment]
> 👍 🎉 Finally! 😄 very happy to see this PR.
> 
> However, I think that these alerts might still be valuable for debug and development purposes. Was it discussed to keep them as metrics instead of alerts, or as an alert that's considered debug-info that the user could filter out in production?

Yes it will be a metric/recording rule (mentioned also in the pr description: [CNV-38320](https://issues.redhat.com/browse/CNV-38320) will handle adding a metric to be able to track this issue without creating noise to the customer.)

**Pull request merged**
