### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by ansijain**
Signed-off-by: ansijain <ansi.jain@india.nec.com>

**What this PR does / why we need it**: Typo fix distint -> distinct 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ansijain** [comment]
Seems test failing are not related to the change
@stu-gott @maya-r

**Comment by stu-gott** [comment]
/override pull-kubevirt-e2e-k8s-1.19
/override pull-kubevirt-e2e-windows2016
/lgtm
/approve

It's silly to spend CI resources on a one-word typo fix in a doc file

**Pull request merged**
