### PR TITLE
Bump kubevirtci to support dual stack on k8s-1.18

### PR DESCRIPTION
**Pull request by oshoval**
Signed-off-by: Or Shoval <oshoval@redhat.com>

Supports:

- [x] Dual Ips for non control plane pods (see podIPs).
- [x] IPv6 services (k8s doesn't support yet a dual ip service).

See https://github.com/kubevirt/kubevirtci/pull/427

Only k8s-1.18 is affected by this PR.

```release-note
None
```

### CODE REVIEW

**Comment by rmohr** [comment]
/approve

Does this mean that we can disable the ipv6-kind lane soon?

**Comment by oshoval** [comment]
> /approve
> 
> Does this mean that we can disable the ipv6-kind lane soon?

thanks
once all the test will be supported on this lane, 
atm the tests check IP / dns fields and since they are IPv4 configure stuff according IPv4 and not test IPv6,
once all tests support dual stack and have both paths tested, we can

**Pull request merged**
