### PR TITLE
Remove test 6225 from Quarantine

### PR DESCRIPTION
**Pull request by brybacki**
Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

**What this PR does / why we need it**:

Remove test 6225 from Quarantine

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by fgimenez — COMMENTED** [review]
/lgtm

**Comment by awels** [comment]
/lgtm
@mhenriks if you are reviewing can you review this?

**Pull request merged**
