### PR TITLE
Remove now-stable hotplug test from quarantine.

### PR DESCRIPTION
**Pull request by maya-r**
Waited a bit longer to see that this variant is also stable.
No failures in the past 14 days.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
cc @fgimenez

**Comment by maya-r** [comment]
Hmm, might've mis-searched - the last failure was 12 days ago. Still seems pretty stable.

**Review by phoracek — COMMENTED** [review]
/approve

**Pull request merged**
