### PR TITLE
Remove fedora-atomic image

### PR DESCRIPTION
**Pull request by davidvossel**
Now that fedora cloud is included by default and is a part of our func test suite, we really don't have a reason to keep the atomic registry disk around anymore.

### CODE REVIEW

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by fabiand** [comment]
Is one Fedora image sufficient?

**Comment by davidvossel** [comment]
@fabiand we never used the atomic image except for manual testing. I think i'm the only one who's ever used it actually.

**Pull request merged**
