### PR TITLE
instancetype: Introduce `PreferredSubdomain`

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/hold

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Allow to define the preferred subdomain in VirtualMachine{Preferences,ClusterPreferences}
```

### CODE REVIEW

**Comment by alicefr** [comment]
Looks good
/approve

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Pull request merged**
