### PR TITLE
multus_tests, sriov: add vlan=0 to NAD

### PR DESCRIPTION
**Pull request by alonSadan**
**What this PR does / why we need it**:

There is a difference between a network(defined in networkAttachmentDefenition)
with vlan=0 attribute and a network with no vlan attribute at all.
If the VF has some vlan tag different than 0,
then when it is assigned to a pod (or a vm/i)
which is connected to a network with vlan=0 the vlan tag will be removed.
When the pod is connected to a network with no vlan attribute,
the vlan tag will remain as it is.

This behavior is implemented in SRIOV-CNI.
This is where the vlan is assigned :
https://github.com/k8snetworkplumbingwg/sriov-cni/blob/b18123d809f1c010cae19018e3395ed5981e76f7/pkg/sriov/sriov.go#L287

The investigation found that the source of the ping flakiness is that in our tests,
for some reason, the vlan tag remains from the ping-over-sriov+vlan test.
Then on the ping-over-sriov-no-vlan test, because the network does not have a vlan defined attribute,
it will not remove the existing vlan tag upon VF assignment.
Then, if unfortunately one VM/I will be assigned with a tagged VF it will not remove it, and if another VM/I assigned with
a VF with no vlan tag ,it will lead to a ping failure.

There is an open issue regarding this behavior on SRIOV-CNI: 
https://github.com/openshift/sriov-cni/issues/25 

Another interesting thing is that when the net-attach-def is created by the SRIOV-operator,
after creating a sriovNetwork object, it will give the net-attach-def a value of 0,
no matter if the sriovNetwork object has a vlan attribute or not.

By creating the net-attach-def with a vlan=0 attribute,
the vlan tag is removed from the VF the test seems to pass consistently.

Signed-off-by: alonsadan <asadan@redhat.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
Thank you!

Could you please open an issue on the SR-IOV CNI and link it here?
Not specifying the VLAN should be interpreted by the CNI as VLAN=0, but it cannot assume it should not touch the existing VLAN, that is prone to bugs, especially when the user is not intending to have any VLAN.

BTW, in classic networking, there is a difference between a non VLAN and a VLAN=0. No VLAN means that it is not a trunk (no tagged traffic) while VLAN 0 means that the ethernet header includes a VLAN just for the priority bits. So I find this strange that they are considered the same.

**Comment by alonSadan** [comment]
> Thank you!
> 
> Could you please open an issue on the SR-IOV CNI and link it here?
> Not specifying the VLAN should be interpreted by the CNI as VLAN=0, but it cannot assume it should not touch the existing VLAN, that is prone to bugs, especially when the user is not intending to have any VLAN.
> 
Done: https://github.com/openshift/sriov-cni/issues/25

> BTW, in classic networking, there is a difference between a non VLAN and a VLAN=0. No VLAN means that it is not a trunk (no tagged traffic) while VLAN 0 means that the ethernet header includes a VLAN just for the priority bits. So I find this strange that they are considered the same.
Thanks for the explanation :)

**Review by oshoval — COMMENTED** [review]
Nice
is there a way to tell it to totally "untag" instead of VLAN ID 0 ?
in case 0 removes the vlan header its the same,


but there are basically two options that will allow traffic:
1. dont have vlan header (which is better than option 2)
2. have vlan header with vlan tag 0 (and then for example you can keep the 802.1p priority fields)

Edit:
i see now Edy said the same

**Comment by alonSadan** [comment]
Thanks @oshoval .
I agree.
I just want to emphasize that from what I saw,
when the NAD has a VLAN attribute with a value of 0, 
the CNI will remove the VLAN tag from the VF  completely, and *will not* give the VF a vlan tag 0.

**Comment by alonSadan** [comment]
[Rebased](https://github.com/kubevirt/kubevirt/compare/937945cdfa1a80275b5578d8d759a7c3e54a0ef7..182476630fc44a1ddc4349e791c4bf45f4a1e002) on master

**Review by EdDev — COMMENTED** [review]
Commit message comments:

>  multus_tests, sriov: add vlan=0 to NAD

tests, sriov: Explicitly set vlan=0 to NADs with no VLAN defined

> 
> There is a difference between a network(defined in networkAttachmentDefenition)
> with vlan=0 attribute and a network with no vlan attribute at all.
> If the VF has some vlan tag different than 0,
> then when it is assigned to a pod (or a vm/i)
> which is connected to a network with vlan=0 the vlan tag will be removed.
> When the pod is connected to a network with no vlan attribute,
> the vlan tag will remain as it is.
> 
> This behaviour is intended and is implemented this way in SRIOV-CNI.
> This is where the vlan is assigned :
> https://github.com/k8snetworkplumbingwg/sriov-cni/blob/master/pkg/sriov/sriov.go#L287

The fact that it appears in the code does not mean it is intended.
You can just mention that the SRIOV-CNI is implementing this logic.
> 
> And this is where it is released:
> https://github.com/k8snetworkplumbingwg/sriov-cni/blob/master/pkg/sriov/sriov.go#L386

I would not ref code, but if you do, ref a permanent link (the current one is not permanent and will not be relevant as soon as the code changes).

> 
> As can be seen there, When a VF is released,
> the original attributes that were before the assignment are restored.
> I think that the source of the ping flakiness is that  in our tests,

If you are unsure, it is problematic. You can do something like this: "The investigation found that ...".

> the network does not have a vlan defined attribute,
> so the original attribute does not get restored,
> what can lead to one VF keep it’s vlan tag from the ping-over-sriov+vlan test,
> and then on the ping-over-sriov-no-vlan test, one of the VFs have a vlan tag,
> and the other one doesn’t , so the ping fails.
> 
> Another interesting thing is that when the net-attach-def is created by the SRIOV-operator,
> after creating a sriovNEtwork object, it will give the net-attach-def a value of 0,
> no matter if the sriovNetwork object has a vlan attribute or not.
> 
> By creating the net-attach-def with a vlan=0 attribute,
> the test seems to pass consistently on my local env.
> The only mystery left is why this is happening only on the ConnectX-5 machine,
> and it will require further investigation.

Please drop `on my local env`.
Regarding the mystery, I think we know the answer already. It seems to occur only on the ConnectX-5 SR-IOV NIC, where on numvfs change/reset, the VF config is preserved. This has not been seen on other NIC/s in the CI setups.

**Comment by EdDev** [comment]
Also, please reference the issue you opened on the CNI.

**Comment by alonSadan** [comment]
> tests, sriov: Explicitly set vlan=0 to NADs with no VLAN defined

Done.

>  The fact that it appears in the code does not mean it is intended.
You can just mention that the SRIOV-CNI is implementing this logic.

Done. If it is intended or not will reveal in the [issue](https://github.com/openshift/sriov-cni/issues/25) I opened in SRIOV-CNI.

> I would not ref code, but if you do, ref a permanent link (the current one is not permanent and will not be relevant as soon as the code changes).

Changed to perm links.

> Please drop on my local env.
Regarding the mystery, I think we know the answer already. It seems to occur only on the ConnectX-5 SR-IOV NIC, where on numvfs change/reset, the VF config is preserved. This has not been seen on other NIC/s in the CI setups.

Dropped both "local env" and "mystery" part.


> Also, please reference the issue you opened on the CNI.

I refed it [here](https://github.com/kubevirt/kubevirt/pull/5093#issuecomment-785735810), but I will add it to the PR
description as well.

**Comment by EdDev** [comment]
> As can be seen there, When a VF is released,
> the original attributes that were before the assignment are restored.
> The investigation found that the source of the ping flakiness is that  in our tests,
> the network does not have a vlan defined attribute,
> so the original attribute does not get restored,
> what can lead to one VF keep it’s vlan tag from the ping-over-sriov+vlan test,
> and then on the ping-over-sriov-no-vlan test, one of the VFs have a vlan tag,
> and the other one doesn’t , so the ping fails.

I am re-reading this and something is wrong here.
The release part is irrelevant at this stage and that logic seems fine to me: If nothing was done on assigning the VF, nothing should be done when releasing. That is symmetric.
If on assignment it will get changed, it will gave to be changed on release ask well.

If a test uses a VLAN, it means it was probably annotated on the pod and eventually together with the NAD, it will reach the CNI with a VLAN, at which time it will configure the VF and on release it will be restored.
The question is, is this restore part exists on the current CNI version we use in the tests.

When you now set VLAN=0 to be the default if no VLAN is specified in the pod annotation, then any value that was there before will get overwritten and solve the problem.

Therefore, the open question about what left a VLAN set there is still relevant. I would bet it is the CNI plugin version, but you will need to conform this.

**Comment by alonSadan** [comment]
> ase part is irrelevant at this stage and that logic seems fine to me: If nothing was done on assigning the VF, nothing should be done when releasing. That is symmetric.

Thanks @EdDev  for noticing that. My explanation was indeed not exact, and the release part is not relevant here.
I updated the commit message and the PR desc.

**Comment by EdDev** [comment]
Thank you, there are only two points left:
- `VM/I` =>> `VMI`
- Keep the lines no longer than [72 long](https://chris.beams.io/posts/git-commit/#wrap-72).

**Review by EdDev — APPROVED** [review]
Thank you!

**Comment by alonSadan** [comment]
Thanks Eddy :)

**Review by phoracek — APPROVED** [review]
/approve

Nice catch!

**Pull request merged**
