### PR TITLE
e2e: Increase number of e2e parallel tests to 4

### PR DESCRIPTION
**Pull request by brianmcarey**
### What this PR does

Running 3 tests in parallel has proven to be a very stable base.

Previously running 6 tests in parallel introduced increased instability.

Try running 4 tests in parallel to see if it remains stable and to see what are the potential lane run time savings

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

/cc @dhiller @xpivarc 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by brianmcarey** [comment]
/hold 

To see resulting lane run times.

**Comment by brianmcarey** [comment]
/hold cancel

Comparing the lane runtimes here versus the latest avg runtimes - this changes reduces the runtime of the sig-compute, sig-storage & sig-network by at least 20 minutes. Around 30 mins in the case of the sig-compute lane.

I think this is worth trying to see if everything remains stable at this new value.

**Review by dhiller — APPROVED** [review]
/approve

All for reducing lane runtimes - we can still override the ENV per job if we see degradation of stability.

Might be worth noting this to kubevirt-dev, WDYT?

**Comment by dhiller** [comment]
FYI @akalenyu @EdDev @sradco @jean-edouard

**Review by EdDev — APPROVED** [review]

**Comment by jean-edouard** [comment]
@brianmcarey did we check that there's enough memory for the 4 most memory-hungry parallel tests to run together?
If so, we've previously been running oversized nodes. If not, we'll see "flakiness".
I guess time will tell, let's comment on this PR after it merges with successes (higher test rate / lower cloud resources consumed) and failures (out-of-memory/cpu flakes).
Thanks

**Pull request merged**
