### PR TITLE
[release-0.44] virt-handler: use /proc instead of virt-chroot to stat virt-launcher files

### PR DESCRIPTION
**Pull request by jean-edouard**
and fix mis-uses of path instead of filepath

This is a manual cherry-pick of #6696 

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
@jean-edouard Seems `make generate` is needed

**Comment by jean-edouard** [comment]
> @jean-edouard Seems `make generate` is needed

Yeah, I PRed before https://github.com/kubevirt/kubevirt/pull/7026 was merged, so that was expected.
Will rebase.
Thanks!

**Review by stu-gott — COMMENTED** [review]
/approve

**Pull request merged**
