### PR TITLE
Simplify replacing ticker and fix interval flag default values

### PR DESCRIPTION
**Pull request by VirrageS**
**What this PR does / why we need it**:
* Simplifies replacing `time.Ticker` since now we can use `ticker.Reset` instead of stopping previous one and creating new.
* Fixes default flag values for `qemu-*-interval`. The flags are defined as `pflag.Duration` therefore the default values should be `time.Duration`. If someone would not be careful, they could redefine a flag as `--qemu-agent-version-interval 1s` (what is completely allowed and correct!). But this would be catastrophic because it would result in `time.Second * time.Second` down the line which is some very big value and complete nonsense. The alternative would be to define those flags as `pflag.Int` but this would require changing the types in different functions and would be more painful for the user as they wouldn't be able to set the flag to let's say `10s500ms`.

**Special notes for your reviewer**: None

**Release note**:

```release-note
Simplify replacing `time.Ticker` in agent poller and fix default values for `qemu-*-interval` flags
```

### CODE REVIEW

**Review by xpivarc — APPROVED** [review]

**Review by xpivarc — APPROVED** [review]
Consider capturing these points in the commit:
1. why we can use `Reset`
2. why we are fixing the flag default(not only that as you mentioned)

**Comment by VirrageS** [comment]
@xpivarc you mean in the commit itself or the MR description?

**Comment by xpivarc** [comment]
> @xpivarc you mean in the commit itself or the MR description?

In the commit itself.

**Comment by VirrageS** [comment]
@xpivarc done

**Comment by VirrageS** [comment]
@jean-edouard seems like all the tests have passed. Is there anything else I should do to get it merged?

**Comment by jean-edouard** [comment]
> @jean-edouard seems like all the tests have passed. Is there anything else I should do to get it merged?

@VirrageS you just need an LGTM from another member!

**Review by xpivarc — APPROVED** [review]

**Pull request merged**
