### PR TITLE
Use generate on bazel build

### PR DESCRIPTION
**Pull request by cynepco3hahue**
**What this PR does / why we need it**:
Run `bazel-generate`, before `bazel-build`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
For reference: 
- https://kubevirt-master-stdci-production.apps.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/264/artifact/ci_build_summary.html

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by rmohr** [comment]
@cynepco3hahue I think #2101 will also solve this amongst other  things.

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
@rmohr Yep, but I also play with `standalone` method, just to see if it will solve the `fedora` image problem.

**Comment by cynepco3hahue** [comment]
close in favor of https://github.com/kubevirt/kubevirt/pull/2101

**Pull request closed without merging**
