### PR TITLE
Add go tip with allow failure to Travis

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by davidvossel** [comment]
Why would we want to have go tip in our travis file if we ignore failures?

**Comment by gliptak** [comment]
@davidvossel You might use this as an early warning system, also allowing to use the CI build to check changes (without running tip locally).

**Comment by stu-gott** [comment]
I hear you @gliptak but I guess it depends on how often it fails. As a rule, if it fails often and is allowed to be ignored, it will be ignored 100% of the time. People will think "oh, that's just tip".

**Comment by davidvossel** [comment]
If people find this useful, I don't have a problem with it going in.

**Comment by rmohr** [comment]
I think we need glide to be installed via apt-get install glide, instead of pulling it from the glide repo, since we always fail on installing glide.

**Comment by rmohr** [comment]
@gliptak We are now using dep and no longer glide. Would you mind rebasing, so that I can merge it?

**Comment by gliptak** [comment]
https://github.com/kubevirt/kubevirt/pull/527

**Pull request closed without merging**
