### PR TITLE
Skip GPU tests from compute lane

### PR DESCRIPTION
**Pull request by vatsalparekh**
**What this PR does / why we need it**:
Skip GPU tests from compute lane & rename the sig-compute tag to align with other sig tags
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by fgimenez — APPROVED** [review]
/lgtm

Thanks a lot @vatsalparekh!

**Review by enp0s3 — CHANGES_REQUESTED** [review]
@vatsalparekh  @fgimenez I see that removing the 'owner` prefix from the sig-compute lane will affect the presubmit jobs of Prow. Let's not change the label format, but instead let's update project-infra to use regex in ENV VAR instead of explicit value. Then, when regex will take place, we can safely change the label.

**Comment by vatsalparekh** [comment]
> @vatsalparekh @fgimenez I see that removing the 'owner` prefix from the sig-compute lane will affect the presubmit jobs of Prow. Let's not change the label format, but instead let's update project-infra to use regex in ENV VAR instead of explicit value. Then, when regex will take place, we can safely change the label.

@enp0s3 We also have this https://github.com/kubevirt/project-infra/pull/1142 to remove the tag from the prow job

**Comment by enp0s3** [comment]
> > @vatsalparekh @fgimenez I see that removing the 'owner` prefix from the sig-compute lane will affect the presubmit jobs of Prow. Let's not change the label format, but instead let's update project-infra to use regex in ENV VAR instead of explicit value. Then, when regex will take place, we can safely change the label.
> 
> @enp0s3 We also have this [kubevirt/project-infra#1142](https://github.com/kubevirt/project-infra/pull/1142) to remove the tag from the prow job

@vatsalparekh The thing is, in the time between these merges all the compute tests will fail because the label was changed. The [presubmits](https://github.com/kubevirt/project-infra/blob/013f877c02e989ca3f93dd9b32d0de770f6cdc0e/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L33) job still uses the 'owner' prefix, but even if you will change this job, I mean that in order for this modification to pass smoothly w/o affecting ongoing PRs we need these 2 PRs to be merged together at the same time. I was thinking about using a regex in env var and then to change the label, then I think it will go smoothly.

**Comment by fgimenez** [comment]
> The thing is, in the time between these merges all the compute tests will be skipped because the label was changed.

@enp0s3 nope, this is not the case, in the 1.20 lanes (currently not required), the si-compute tests would not be skipped, they would run as part of the main suite. This is still the case in the main lanes ([1.19](https://github.com/kubevirt/project-infra/blob/013f877c02e989ca3f93dd9b32d0de770f6cdc0e/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L274) and [1.18](https://github.com/kubevirt/project-infra/blob/013f877c02e989ca3f93dd9b32d0de770f6cdc0e/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L427)), sig-operator tests are still being run as part of them.

We need to make the label change now so that we align with the other sigs without disrupting the test filtering.

**Comment by enp0s3** [comment]
> > The thing is, in the time between these merges all the compute tests will be skipped because the label was changed.
> 
> @enp0s3 nope, this is not the case, in the 1.20 lanes (currently not required), the sig-compute tests would not be skipped, they would run as part of the main suite. This is still the case in the main lanes ([1.19](https://github.com/kubevirt/project-infra/blob/013f877c02e989ca3f93dd9b32d0de770f6cdc0e/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L274) and [1.18](https://github.com/kubevirt/project-infra/blob/013f877c02e989ca3f93dd9b32d0de770f6cdc0e/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L427)), sig-operator tests are still being run as part of them.
> 
> We need to make the label change now so that we align with the other sigs without disrupting the test filtering.

@fgimenez @vatsalparekh Thank you for the elaboration, now I see it.

**Review by enp0s3 — APPROVED** [review]
/approve

**Pull request merged**
