### PR TITLE
Take test with id 2666 out of QUARANTINE

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
The test seems to be [stable](https://search.ci.kubevirt.io/?search=test_id%3A2666&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
/lgtm
/approve

No failures seen for the last 14 days: https://search.ci.kubevirt.io/?search=test_id%3A2666&maxAge=336h&context=3&type=build-log&name=periodic.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

Job failures seem to be either flaked tests or unrelated sriov startup issues: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6001/pull-kubevirt-e2e-kind-1.19-sriov/1413075388430553088#1:build-log.txt%3A3126

/retest

**Comment by fgimenez** [comment]
/hold

We had a failure 15 days ago https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sig-compute/1407544247078359040 and we didn't have any changes to fix this test, so it might fail again. Let's wait a bit more and keep an eye on it for a while, we will take care of it in the quarantine meetings.

**Comment by fgimenez** [comment]
It has started failing again, see https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sig-compute/1415516560042233856 and here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-sig-compute/1415317675319496704

**Comment by xpivarc** [comment]
@fgimenez can we unhold?

**Comment by fgimenez** [comment]
/unhold

> @fgimenez can we unhold?

Yes, thanks for the heads up, the due date was 2021/07/23 and  we didn't have more failures in recent executions https://search.ci.kubevirt.io/?search=test_id%3A2666&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Pull request merged**
