### PR TITLE
Revert sriov to only one node setup

### PR DESCRIPTION
**Pull request by fedepaol**
**What this PR does / why we need it**:

Hoping this is temporary, we revert the sriov lane to use just one note to reduce the scope of changes in order to understand ci failures.

```release-note
NONE
```

### CODE REVIEW

**Comment by slintes** [comment]
@fedepaol do you want to merge this, or only check CI?

**Comment by fedepaol** [comment]
@slintes I'd say let's see if the kind lane gets through, if it does let's merge this so I can investigate the issue in a separate PR without making tide's life difficult

**Comment by fedepaol** [comment]
Ran it a couple of times, seems to be fine.
@slintes this is good to go

**Pull request merged**
