### PR TITLE
A functional test to verify VM to VM connectivity

### PR DESCRIPTION
**Pull request by vladikr**
Signed-off-by: Vladik Romanovsky <vromanso@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@vladikr I can see that all runs have failure
```
[Fail] Networking VirtualMachine with nodeNetwork definition given should be able to reach [It] the Inbound VM 
/root/go/src/kubevirt.io/kubevirt/tests/vm_networking_test.go:133
```
Can you please check it?

**Comment by vladikr** [comment]
> Can you please check it?

Yea, I'm still trying to figure this out...
This test works fine when I'm running only the networking related tests but fails when running all functional tests together.

**Comment by stu-gott** [comment]
Looking good so far. @vladikr As far as the errChan--I think the issue is that the "defer GinkoRecover" call is also inside a goroutine.

**Comment by vladikr** [comment]
I realized that the problem is really with the cirros image that we are testing on.
Apparently, the version of netcat get stuck waiting for I/O, even after the set timeout - also there is no bash, but this is less of a problem.

I'm going to change the test to just test vm to vm ping instead of netcat.

**Comment by vladikr** [comment]
retest this please

**Comment by davidvossel** [comment]
retest this please

**Comment by cynepco3hahue** [comment]
@vladikr We still have two failures on `dev` manifests
```
[Fail] Networking VirtualMachine with nodeNetwork definition given should be reachable via the propagated IP from a Pod [It] on a different node from Pod 
/root/go/src/kubevirt.io/kubevirt/tests/vm_networking_test.go:178

[Fail] Networking VirtualMachine with nodeNetwork definition given should be reachable via the propagated IP from a Pod [It] on a different node from Node 
/root/go/src/kubevirt.io/kubevirt/tests/vm_networking_test.go:178
```

**Comment by vladikr** [comment]
> We still have two failures on dev manifests

It passes now. These failures were not related to this test.

**Comment by rmohr** [comment]
> Take a look at the tests/vmlifecycle_test.go's "with non default namespace" test for an example of how to retrieve the list of nodes and schedule a VM to a specific node.

You can use an anti-affinity agains the `kubevirt.io/domain=vmname` label too: https://kubevirt.gitbooks.io/user-guide/assign-vm-node.html#affinity-and-anti-affinity

**Pull request merged**
