### PR TITLE
Bump kubevirtci

### PR DESCRIPTION
**Pull request by oshoval**
Changes:
1. Disable etcd in memory by default for VM based providers (https://github.com/kubevirt/kubevirtci/pull/517).
2. Fix sriov operator VFs creation race condition (https://github.com/kubevirt/kubevirtci/pull/513).
Fixes failures like [1].
3. QEMU VM's based providers: run etcd on RAM memory (https://github.com/kubevirt/kubevirtci/pull/499).

latest included kubevirtci commit: e550ba69d9e6493a2ac3adeb23fad062c8d47713

[1] https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4783/pull-kubevirt-e2e-kind-1.17-sriov/1348889433864146945

Signed-off-by: Or Shoval <oshoval@redhat.com>

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
The failures aren't due to the bump imo.

/retest

**Comment by EdDev** [comment]
Please ref the commits that this bump includes from the kubevirtci repo.
I also do not understand `Disable etcd in memory by default for k8s providers`. Is the original PR/commit explains what are the implications? (if we take the sriov lane, we must run in memory there)

**Comment by oshoval** [comment]
> Please ref the commits that this bump includes from the kubevirtci repo.
> I also do not understand `Disable etcd in memory by default for k8s providers`. Is the original PR/commit explains what are the implications? (if we take the sriov lane, we must run in memory there)

It doesn't affect kind sriov, just k8s providers, this is why i emphasized it.

**Comment by oshoval** [comment]
Address comments.

**Comment by EdDev** [comment]
> Important changes:

We need to specify all changes so it will be clear what entered. If there are other changes, please ref them. In any case, please remove this line.

Also, please add the ref in the commit message as well.

> just k8s-X providers

It is just confusing, because the kind one is also a k8s provider. You can express it as "VM based providers" or "non-kind providers", or "except the SRIOV provider".

**Comment by oshoval** [comment]
Addressed comments.

**Review by EdDev — APPROVED** [review]
Thanks.
Lets see if it passes CI well.

**Comment by oshoval** [comment]
Flakes are not due to this PR.

**Review by enp0s3 — APPROVED** [review]
/approve

**Pull request merged**
