### PR TITLE
Add tests to quarantine

### PR DESCRIPTION
**Pull request by fgimenez**
Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

**What this PR does / why we need it**: Adds tests to quarantine in order to improve the test suite stability. These are quarantined tests:
* `VirtualMachineRestore Tests rook-ceph With a more complicated VM [test_id:5261]should restore a vm that boots from a datavolume (not template)`:
  * https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-04-21-168h.html#row9
  * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1384541045735297024
  * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1384394705759899649
* `VMIlifecycle when virt-handler is deleted [Serial][test_id:4716]should label the node with kubevirt.io/schedulable=false`:
  * https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-04-21-168h.html#row3
  * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.19/1384815982513491968
  * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.19/1384466302961192961
* `Hotplug rook-ceph Online VM Should be able to add and remove and re-add multiple volumes with VMs and block`:
  * https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-04-21-168h.html#row8
  * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev-rook-ceph/1384990631801131008
  * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1385141761776553984
  * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1384905067949199360  

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ashleyschuett** [comment]
This PR https://github.com/kubevirt/kubevirt/pull/5470 should make `[Serial]Operator should reconcile components test updating a deployment is reverted to it's original state` not flaky

**Comment by fgimenez** [comment]
> This PR #5470 should make `[Serial]Operator should reconcile components test updating a deployment is reverted to it's original state` not flaky

Awesome, thanks a lot @ashleyschuett. Let's first quarantine it and then check the stability after the fix is merged, it should be non-flaky for 14 days to be considered stable.

**Comment by fgimenez** [comment]
> > This PR #5470 should make `[Serial]Operator should reconcile components test updating a deployment is reverted to it's original state` not flaky
> 
> Awesome, thanks a lot @ashleyschuett. Let's first quarantine it and then check the stability after the fix is merged, it should be non-flaky for 14 days to be considered stable.

The code of this test has changed and now there are different cases as table entries, let's remove the quarantine for now and check how it behaves.

**Comment by fgimenez** [comment]
> #5445 fixed hotplug tests, this looks like the same failure, I think we should observer all the hotplug add/remove tests as one issue.

@brybacki I agree, we can handle them on a single issue, but we need to quarantine all of them separately, #5445 was merged on 2021/04/21 7:05 and https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1385141761776553984 failed on 2021/04/22 10:02, so `Hotplug rook-ceph Online VM Should be able to add and remove and re-add multiple volumes with VMs and block` is not fixed by #5445

**Comment by brybacki** [comment]
right, needs to be verified

**Review by enp0s3 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
