### PR TITLE
Support setting Multus default network via annotations. 

### PR DESCRIPTION
**Pull request by greg-bock**
**What this PR does / why we need it**:
Adds support for setting the default network in Multus via annotations. https://github.com/intel/multus-cni/pull/174

This adds a new `Default` field to the `CniNetwork` struct.
This can only be set once and is enforced by `validating-webhook`.
Setting this field on a Network in the VMI spec will cause the `v1.multus-cni.io/default-network` annotation to be added to the launcher pod with the network name with the `default` setting.
All other changes are to support naming the default network `eth` vs the normal multus prefix of `net` and fixing count logic for numeric suffix of the network/device name. 

This is useful if you want the vmi default network to not be the default network in a Multus networking setup:
- Users might want to have a separate pod network from the default network to segregate workload networking from k8s or other sensitive services.
- Users might want to only have a single network from Multus that isn't a pod network at all (External SRIOV)  

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Depends on #1806 

**Release note**:

```release-note
Adds support for setting the default network in Multus via annotations.
action required: A version of the Multus cni that supports default via annotations.
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by SchSeba** [comment]
Hi @greg-bock,
Thanks for the PR! 

Can you please add more details on the PR Description?
Can you please provide a use-case for this?

**Comment by greg-bock** [comment]
@SchSeba 
> Can you please provide a use-case for this?

I expanded on the previous use-case provided.

> Can you please add more details on the PR Description?

I added a bit more information. Let me know if there is anything else you have questions about.
I plan on doing doc updates once my other PR is finished.

Note that this branch is  branched from another PR I have going (#1806). To see what is really changing: [compare](https://github.com/stackpath/kubevirt/compare/cloudinit-network..multus-default-annotation)

**Comment by SchSeba** [comment]
@greg-bock  Thanks for adding more comment into the description

I just have one question.
we have the ability to create a vmi without the pod network. (yes the pod will have the eth0 connected to the k8s network but not the VMI)

The VMI will only see the interfaces configured in the yaml

example:
this vmi will only have eth0 and it will be connected using the PTP cni plugin.

```yaml
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
metadata:
  creationTimestamp: null
  labels:
    special: vmi-multus-ptp
  name: vmi-multus-ptp
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
        volumeName: registryvolume
      - disk:
          bus: virtio
        name: cloudinitdisk
        volumeName: cloudinitvolume
      interfaces:
      - bridge: {}
        name: ptp
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  networks:
  - multus:
      networkName: ptp-conf
    name: ptp
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
    name: registryvolume
  - cloudInitNoCloud:
      userData: |
        #!/bin/bash
        echo "fedora" |passwd fedora --stdin
    name: cloudinitvolume
status: {}
```


please tell me if this achieve the same usage of this PR

**Comment by greg-bock** [comment]
Replaced with #1924

**Pull request closed without merging**
