### PR TITLE
OWNERS_ALIAS: Remove myself from code reviewers

### PR DESCRIPTION
**Pull request by vasiliy-ul**
Unfortunately, I will not be able to dedicate enough time to do regular code reviews in the nearest future due to a change of focus. Therefore, I remove myself from the list to avoid automatic review assignments.

Due to personal reasons, I will not be very active in the community during the following few months. Hence, it is better to avoid creating confusion for other contributors expecting review from me.

Still hope to get back in the future, but for now do not have exact timeline for that.

### What this PR does
Before this PR:

After this PR:

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder101** [comment]
Thank you very much @vasiliy-ul for your many contributions to the project, both in terms of review and implementation!

I suggest to add an `emeritus_reviewers` section similar to `emeritus_approvers` so it would be easier for you to re-become a reviewer in the future if you will wish to do so.

@dhiller WDYT?

**Comment by alicefr** [comment]
/lgtm
@vasiliy-ul sad to hear that, but I want also to thank you for the great work and precious feedback!

**Comment by EdDev** [comment]
> I suggest to add an `emeritus_reviewers` section similar to `emeritus_approvers` so it would be easier for you to re-become a reviewer in the future if you will wish to do so.

I am not familiar with such a presedence on other projects.
I also do not see the need. Anyone can be a reviewer, the bar is very low as it only effects the bot assigning one to a PR.

**Comment by iholder101** [comment]
> > I suggest to add an `emeritus_reviewers` section similar to `emeritus_approvers` so it would be easier for you to re-become a reviewer in the future if you will wish to do so.
> 
> I am not familiar with such a presedence on other projects. I also do not see the need. Anyone can be a reviewer, the bar is very low as it only effects the bot assigning one to a PR.

Makes sense.
Thanks again @vasiliy-ul, let us know if you'll have the time to participate in reviews in the future.

/approve

**Comment by dhiller** [comment]
> > I suggest to add an `emeritus_reviewers` section similar to `emeritus_approvers` so it would be easier for you to re-become a reviewer in the future if you will wish to do so.
> 
> I am not familiar with such a presedence on other projects. I also do not see the need. Anyone can be a reviewer, the bar is very low as it only effects the bot assigning one to a PR.

I agree about the emeritus for reviewers - also taking into account that he's still an approver.

**Pull request merged**
