### PR TITLE
Run sig-compute tests with ceph

### PR DESCRIPTION
**Pull request by akalenyu**
### What this PR does
At some point in time it was probably true to say sig-compute does not require an advanced storage solution,
but a quick search over skipped tests today shows this is not the case:
```bash
$ (cd tests; git grep "storage-req" -- ':!storage/**' ':!decorators/**' ':!*.md' | wc -l)
14
```

Before this PR:
sig-compute lane does not use rook-ceph-block as the storage provisioner

After this PR:
sig-compute does use rook-ceph-block as the storage provisioner

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
@akalenyu I think this is fair, although I see a storage-req test failing here. Would you mind taking a look? https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11485/pull-kubevirt-e2e-k8s-1.29-sig-compute/1767277390536380416

**Comment by akalenyu** [comment]
> @akalenyu I think this is fair, although I see a storage-req test failing here. Would you mind taking a look? https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11485/pull-kubevirt-e2e-k8s-1.29-sig-compute/1767277390536380416

yeah we know why this happens from an older PR:
https://github.com/kubevirt/kubevirt/pull/11099#issuecomment-1957153162

/cc @mhenriks 
I recall you were in favor of keeping a non csi/wffc lane

**Review by dhiller — APPROVED** [review]
Thanks @akalenyu !

**Comment by xpivarc** [comment]
@akalenyu ping

**Comment by akalenyu** [comment]
> @akalenyu ping

This is a big change so I am not that keen on going for this - what do you have in mind?
Note we'll be losing some non-CSI coverage

**Comment by xpivarc** [comment]
> > @akalenyu ping
> 
> This is a big change so I am not that keen on going for this - what do you have in mind? Note we'll be losing some non-CSI coverage

Can you elaborate?

**Comment by akalenyu** [comment]
> > > @akalenyu ping
> > 
> > 
> > This is a big change so I am not that keen on going for this - what do you have in mind? Note we'll be losing some non-CSI coverage
> 
> Can you elaborate?

Yeah, today that lane uses "local" for the most part. That is non-CSI storage. So as soon as you switch, you're making a big statement in that "I'm fine with no CSI coverage"

**Comment by vladikr** [comment]
> > > > @akalenyu ping
> > > 
> > > 
> > > This is a big change so I am not that keen on going for this - what do you have in mind? Note we'll be losing some non-CSI coverage
> > 
> > 
> > Can you elaborate?
> 
> Yeah, today that lane uses "local" for the most part. That is non-CSI storage. So as soon as you switch, you're making a big statement in that "I'm fine with no CSI coverage"

I'm not sure then :) 
Should we drop this PR?

**Comment by akalenyu** [comment]
> > > > > @akalenyu ping
> > > > 
> > > > 
> > > > This is a big change so I am not that keen on going for this - what do you have in mind? Note we'll be losing some non-CSI coverage
> > > 
> > > 
> > > Can you elaborate?
> > 
> > 
> > Yeah, today that lane uses "local" for the most part. That is non-CSI storage. So as soon as you switch, you're making a big statement in that "I'm fine with no CSI coverage"
> 
> I'm not sure then :) Should we drop this PR?

Yeah IMO we should
/close

**Pull request closed without merging**
