### PR TITLE
[virtctl] Bump crypto ssh to make the preauth authentiation for some newer ssh server configurations work

### LINKED ISSUE #6851: virtctl ssh to fedora 35 guests is not working
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
```
  $ virtctl ssh  fedora@example-fedora-35
  ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
**What you expected to happen**:
to see a ssh promt

**How to reproduce it (as minimally and precisely as possible)**:
create a fedora 35 VM from cloud image and try to login via `virtctl ssh  `

**Anything else we need to know?**:
`virtctl ssh --local-ssh fedora@example-fedora-35` would work fine.

**Environment**:
If there are any doubts, I would provide all detailed versions.

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Fixes an issue where golang ssh can't connect to some ssh servers which
do not accept ssh-rsa preauthentication and make the connetions fail
with:

```
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedKeyTypes [preauth]
```

Update to a newer golang.org/crypto version which brings in https://go-review.googlesource.com/c/crypto/+/123955/.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6851

**Special notes for your reviewer**:

**Release note**:

```release-note
Make virtctl ssh work with ssh-rsa+ preauthentication
```

### CODE REVIEW

**Comment by dominikholler** [comment]
@rmohr thanks for the quick fix. Maybe I compiled it the wrong way, but for me the new virtctl binary compiled from this PR did not solve the issue.

**Comment by rmohr** [comment]
A few questions: do you have the guest agent enabled or the guest agent socket set in your env? Do you use password or public key, do you use a RSA or an ec key?

**Comment by dominikholler** [comment]
I use the default fedora 35 image, with guest-agent enabled, 5 years old rsa key, password enabled: https://gist.github.com/dominikholler/d08b8ee7449bce38c10b55149f129b0a

**Comment by rmohr** [comment]
> I use the default fedora 35 image, with guest-agent enabled, 5 years old rsa key, password enabled: https://gist.github.com/dominikholler/d08b8ee7449bce38c10b55149f129b0a

Thanks. Can you try again with the latest code change?

**Comment by rmohr** [comment]
/hold

this will need https://github.com/golang/crypto/pull/197 being merged until this can go in.

**Comment by rmohr** [comment]
@dominikholler can confirm that it works on fc35.

**Comment by rmohr** [comment]
/retest

Verified.

/cc @dhiller 

Would you mind doing a code-review? It is just a vendor change.

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
