### PR TITLE
Add VM templates for windows and linux

### PR DESCRIPTION
**Pull request by yanirq**
Added VM templates for RHEL 7.4 and Windows Server 2012 R2

Signed-off-by: Yanir Quinn yquinn@redhat.com

### CODE REVIEW

**Comment by yanirq** [comment]
> It's not clear to me that these belong in the manifest's directory. They're more than "examples" in the sense that they're presumably functional, but they're certainly not critical to the core operation of KubeVirt. Perhaps these belong somewhere under the cluster directory?

I placed them currently both under dev and release, if we are not ready to place them under release yet then they should be at least under manifests/dev

**Comment by fabiand** [comment]
To me they are also closer to a VM definition (like the manifests in `cluster/`) than definitions for our controllers.

To me `cluster/` looks like a good place for now.

**Comment by rmohr** [comment]
@fabiand ok then lets treat them right now like examples.

@yanirq could you move them back to `cluster/`?

**Comment by yanirq** [comment]
> @yanirq could you move them back to cluster/?
@rmohr  done

**Comment by fabiand** [comment]
Added a tracker to add functional tests with #772

**Comment by rmohr** [comment]
> Added a tracker to add functional tests with #772

thx

**Pull request merged**
