### PR TITLE
sig-observability: Add ownerships

### PR DESCRIPTION
**Pull request by assafad**
### What this PR does
Add observability related files and directories to sig-observability ownership, and add @assafad and @avlitman as observability reviewers.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by assafad** [comment]
/cc @enp0s3, @machadovilaca, @sradco, @avlitman 
Please let me know if I missed any observability related locations.

**Comment by avlitman** [comment]
Maybe let's add me and @assafad as reviewers in this pr as well?

**Comment by assafad** [comment]
> Maybe let's add me and @assafad as sig-observability reviewers in this pr as well?

Done.

**Comment by avlitman** [comment]
/lgtm
nit: @enp0s3 can we be owners of the makefile as well maybe?

**Comment by sradco** [comment]
@assafad  Can we also remove https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-operator/resource/OWNERS ?

**Comment by assafad** [comment]
@enp0s3/@fabiand can you PTAL?

**Comment by enp0s3** [comment]
/approve
@assafad Thank you!

**Pull request merged**
