### PR TITLE
Introduce a FeatureGate for SerialConsoleLog

### PR DESCRIPTION
**Pull request by tiraboschi**
**What this PR does / why we need it**:
We suspect that on recent (>=1.27.2)
CRI-O versions the guest-console-log container
could slow down the deletion of the
virt-launcher pods.
Flipping the default value for DisableSerialConsoleLog
on the Kubevirt' API (and enabling it back in the future)
is quite cumbersome so let's
introduce a feature gate (default off!) to
skip the guest-console-log container
from virt-launcher pod until we will be able to
get it working properly.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://issues.redhat.com/browse/CNV-36682

**Special notes for your reviewer**:
NONE

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
/hold
I'm still not persuaded that the guest console log container is the source of the issue.

**Comment by dankenigsberg** [comment]
Instead of "introducing an internal bug", can you instead introduce a feature gate?
If FGSerialConsoleLog is disabled in kubevirt CR, ignoring the VM option should not count as a bug.

**Comment by tiraboschi** [comment]
> Instead of "introducing an internal bug", can you instead introduce a feature gate? If FGSerialConsoleLog is disabled in kubevirt CR, ignoring the VM option should not count as a bug.

Done

**Comment by dankenigsberg** [comment]
> > Instead of "introducing an internal bug", can you instead introduce a feature gate? If FGSerialConsoleLog is disabled in kubevirt CR, ignoring the VM option should not count as a bug.
> 
> Done

Thanks. Don't forget to expose this in HCO ;-)

/lgtm (fwiw)

**Comment by tiraboschi** [comment]
> Thanks. Don't forget to expose this in HCO ;-)
> 
> /lgtm (fwiw)

Unfortunately as we see in https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11067/pull-kubevirt-e2e-k8s-1.29-sig-compute/1750162877156691968 neither this is solving and the issue is still there.

**Comment by dankenigsberg** [comment]
> Unfortunately as we see in CI

I had no doubts about this... It does not matter how we disable SerialConsole.

**Review by EdDev — CHANGES_REQUESTED** [review]
A feature gate is used to control the lifecycle of a feature towards graduation.
It is not intended to be used to control the functionality as a configuration on-off parameter.

The feature has been released formally already, I do not think a FG can be introduced now. If you want to “fix” the situation, you’ll need an exception path with wide approval from the maintainers/approvers.

**Comment by fabiand** [comment]
+1 on Edy.

We do not need a featureGate. Instead we want a cluster level configuration item to configure this feature ot be on or off.
by default it should be off - let's get a good understanding of the runtime overhead, before we consider to turn it on by default.

**Comment by tiraboschi** [comment]
> We do not need a featureGate. Instead we want a cluster level configuration item to configure this feature to be on or off. 

We already have it: `DisableSerialConsoleLog` struct in [`KubeVirtConfiguration.VirtualMachineOptions`](https://github.com/kubevirt/kubevirt/blob/e6c76602ca07591f72481e5aa9ea28283e088050/staging/src/kubevirt.io/api/core/v1/types.go#L2414) is exactly for that.
My concern is that it's not a boolean so flipping its default is not trivial, see https://github.com/kubevirt/kubevirt/pull/11062 

> by default it should be off - let's get a good understanding of the runtime overhead, before we consider to turn it on by default.

Our first attempt (see: https://github.com/kubevirt/kubevirt/pull/11049 ) has been exactly exdcuting:
```
kubectl patch -n kubevirt kv kubevirt --type='merge' --patch '{"spec": {"configuration": {"virtualMachineOptions": {"disableSerialConsoleLog": {}} } }}'
``` 
on the CI lanes.
We didn't merged it because it wasn't really resolving the CI instability.

**Comment by tiraboschi** [comment]
no need for this

**Pull request closed without merging**
