### PR TITLE
add custom kubelet pods directory support of hotplug-disk

### PR DESCRIPTION
**Pull request by qiutingjun**
**What this PR does / why we need it**:
The purpose of the PR is on hotunplug - to set correct kubelet pods dir for vm if kubelet-pods-dir is configured.
Otherwise, add hotplud volume will fail.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
@alicefr I could have sworn we already had a mechanism to specify a custom kubelet path, but I can't find it. Do you remember if we do?

**Comment by alicefr** [comment]
@awels we do but I think we are completely missing documentation and it isn't really straightforward.
You can specify a custom directory by patching virt-handler daemonset and adding the flag `kubelet-pods-dir`: https://github.com/kubevirt/kubevirt/blob/main/cmd/virt-handler/virt-handler.go#L651 .

However, we should definitely improve this. We also have this issue that covers this enhancement: https://github.com/kubevirt/kubevirt/issues/8998

**Comment by alicefr** [comment]
@qiutingjun would you like to work on https://github.com/kubevirt/kubevirt/issues/8998 ? This would allow to have a cleaner mechanism for container disks too. Additionally, hotplugged disks should already be configured correctly if you use the flag `kubelet-pods-dir`. Hence,  I don't think you need to touch hotplugged disks

**Comment by qiutingjun** [comment]
> @qiutingjun would you like to work on #8998 ? This would allow to have a cleaner mechanism for container disks too. Additionally, hotplugged disks should already be configured correctly if you use the flag `kubelet-pods-dir`. Hence, I don't think you need to touch hotplugged disks


sorry for reply late because I got a COVID-19 ast week.
i'd like to work on #8998.

**Pull request closed without merging**
