### PR TITLE
[e2e tests]: Use node pull method in fstrim tests

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
We import fedora (6Gi) and see this test sometimes fails even with 500 seconds timeout. Let's try the node pull method, which will avoid scratch space usage, at the very least, we will be wasting less storage for the test run.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by xpivarc — COMMENTED** [review]
/approve
if it turns out to help ;)

**Comment by akalenyu** [comment]
/close
we're good on this test now

**Pull request closed without merging**
