### PR TITLE
increase cpu-manager test timeout to 3 minutes

### PR DESCRIPTION
**Pull request by mfranczy**
**What this PR does / why we need it**:
It increases the cpu-manager test timeout to 3 minutes, the heartbeat is the place where we update a cpu-manager label and it happens that between calls we have 2 minutes break, as a result we have a flaky test.  The reason why it takes so long is under investigation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by slintes** [comment]
The failing tests don't have the mentioned test failing. But let's try again.

/test all
/lgtm
/approve

**Comment by dhiller** [comment]
On a related note: test fails in the OKD 4.2 lane: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2790/pull-kubevirt-e2e-okd-4.2/1186668276843810816

**Comment by dhiller** [comment]
Though it fails on an expectation that there is only one node having the cpumanager=false label attached. I guess this is related to having two workers?

**Comment by mfranczy** [comment]
@dhiller from weekly reports I saw it failed on a timeout, it means the CPU manager label was not updated in 2 minutes. Didn't check this against OKD4. It's not about two workers.

take a look at
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2771/pull-kubevirt-e2e-k8s-1.15.1-ceph/1184643435949199361

**Comment by mfranczy** [comment]
@dhiller it seems you're right, it's about two nodes having `cpumanager=false`

**Pull request merged**
