### PR TITLE
[release-0.44] Centralize fedora test tool images in one image

### PR DESCRIPTION
**Pull request by ShellyKa13**
This is a cherry-pick of #6108 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by davidvossel** [comment]
@ShellyKa13 What's the reasoning behind backporting this change?  Is this in preparation for another backport?

**Comment by ShellyKa13** [comment]
@davidvossel yes, I have a backport which has changes based on this change, this PR has changes only in tests and frameworks so no risk.

**Pull request merged**
