### PR TITLE
Update qemu from 8.2.0 to 9.0.0

### PR DESCRIPTION
**Pull request by jean-edouard**
### What this PR does
Before this PR:
We're using an older qemu version and `make rpm-deps` fails because the repository doesn't include qemu 8.2.0

After this PR:
Qemu is now at a recent version and `make rpm-deps` works again

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Qemu updated from 8.2.0 to 9.0.0
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
/cc @andreabolognani 
Can you have a look? Thank you

**Comment by andreabolognani** [comment]
@fossedihelm thanks for tagging me!

9.0.0-6 has already been made available so we could potentially pick that up instead of 9.0.0-5. That said, I'm going to prepare the usual "update the entire stack" PR once libvirt 10.5.0 lands in CentOS Stream, and there's probably going to be further QEMU builds between now and then, so it's likely fine to keep things the way they are.

**Comment by jean-edouard** [comment]
> @fossedihelm thanks for tagging me!
> 
> 9.0.0-6 has already been made available so we could potentially pick that up instead of 9.0.0-5. That said, I'm going to prepare the usual "update the entire stack" PR once libvirt 10.5.0 lands in CentOS Stream, and there's probably going to be further QEMU builds between now and then, so it's likely fine to keep things the way they are.

Bumped! Thank you :)

**Comment by fossedihelm** [comment]
/lgtm
/hold
Giving @andreabolognani possibility to check this again.
Feel free to unhold. Thank you

**Comment by xpivarc** [comment]
Is there a reason to not wait for update of the whole stack?

**Comment by jean-edouard** [comment]
> Is there a reason to not wait for update of the whole stack?

This was to unblock `make rpm-deps`. We can wait, but in the meantime no PR can make any change to the package tree.

**Comment by xpivarc** [comment]
> > Is there a reason to not wait for update of the whole stack?
> 
> This was to unblock `make rpm-deps`. We can wait, but in the meantime no PR can make any change to the package tree.

Yes, the question is if we have any changes coming. Maybe lets ask @andreabolognani , what is the ETA, if you have an estimate.

**Comment by andreabolognani** [comment]
I'm waiting for libvirt 10.5.0 to hit the mirrors. IIUC an issue was found in the first build and is currently being addressed. I'm afraid I can't really offer an ETA though... Ideally it wouldn't take longer than a week or two, but we've had cases in the past where multiple circumstances conspired to make the delay much, much longer.

**Comment by brianmcarey** [comment]
The missing qemu version is causing some of our bump automations to fail  - https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/bump-kubevirt-rpms-weekly/1812811149503107072#1:build-log.txt%3A585

Is it ok to take this in without the full libvirt lift?

**Comment by acardace** [comment]
@brianmcarey I think we do, we can bump again later.
@andreabolognani @jean-edouard @xpivarc objections?

**Comment by andreabolognani** [comment]
That CI job is pretty much guaranteed to start failing periodically.

I can see a couple of ways that we could potentially reduce the pain caused by the constant churn of packages in CentOS Stream.

The first one is to augment the artifact mirroring process that is already happening for RPMs added to KubeVirt's WORKSPACE so that, in addition so simply uploading them as-is to cloud storage, it also runs `createrepo` and publishes the output to a known location.

That way, we could have an additional entry in `repo.yaml` and we would simply start pointing directly to KubeVirt's cloud storage for packages that have disappeared from CentOS Stream, which is already happening as the build time fallback anyway. This will supposedly only really be relevant for the few packages for which we pin a specific version.

The other option would be to somehow make bazeldnf ignore the missing packages. I can't immediately see a way to make that work sensibly without potentially cause trouble for other usage patterns, but maybe further analysis would reveal one.

@alicefr I believe we have talked about the first option in the past. Do you remember the outcome of that discussion?

Anyway, that's for the long term. In the immediate, I don't have any specific objection to bumping QEMU on its own if doing so unblock things, with the assumption that CI passes and the understanding that we're going to follow that up with a full upgrade of the virt stack shortly afterwards.

**Comment by alicefr** [comment]
> That CI job is pretty much guaranteed to start failing periodically.
> 
> I can see a couple of ways that we could potentially reduce the pain caused by the constant churn of packages in CentOS Stream.
> 
> The first one is to augment the artifact mirroring process that is already happening for RPMs added to KubeVirt's WORKSPACE so that, in addition so simply uploading them as-is to cloud storage, it also runs `createrepo` and publishes the output to a known location.
> 
> That way, we could have an additional entry in `repo.yaml` and we would simply start pointing directly to KubeVirt's cloud storage for packages that have disappeared from CentOS Stream, which is already happening as the build time fallback anyway. This will supposedly only really be relevant for the few packages for which we pin a specific version.
> 
> The other option would be to somehow make bazeldnf ignore the missing packages. I can't immediately see a way to make that work sensibly without potentially cause trouble for other usage patterns, but maybe further analysis would reveal one.
> 
> @alicefr I believe we have talked about the first option in the past. Do you remember the outcome of that discussion?
> 

We didn't reach a conclusion, but this problems regularly recurs, so yes, I think we could add the google storage for the rpm. The problem is that the storage contains all the rpms, so it will be a fallback for all the dependencies, not only the one with a pinned version. IMO, it is fine since it should firstly pick the official centos stream repo.

**Comment by andreabolognani** [comment]
I have just opened #12452 which is a superset of this PR and as such should IMO supersede it.

**Pull request closed without merging**
