### PR TITLE
Update cloud images

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
Just updates Alpine and Cirros to the latest available versions.
Both now requires 128M of RAM.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by danielBelenky — CHANGES_REQUESTED** [review]
@jean-edouard can you please elaborate in the description why we want to update? does it fix any bug what we currently have?

**Comment by jean-edouard** [comment]
@danielBelenky I did this locally when I was looking for a secureboot-signed image, hoping one of the latest images would be signed.
They don't happen to be, but it took a while to update everything to 128MB (which both Alpine and Cirros require in recent versions), so I thought I shouldn't let it go to waste, assuming we'll want to update the images one day or another anyway.

I'm not against closing this PR for now, I can always reopen it if/when we decide to update.

**Pull request closed without merging**
