### PR TITLE
Add default value for the BlockMultiQueue parameter for API docu

### PR DESCRIPTION
**Pull request by yuhaohaoyu**
Signed-off-by: Hao Yu <yuh@us.ibm.com>

**What this PR does / why we need it**:

In KubeVirt API document at https://kubevirt.io/api-reference/master/definitions.html#_v1_devices, the default value for the device blockMultiQueue setting should be mentioned for good user experience.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1896797

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Review by stu-gott — APPROVED** [review]
/lgtm

**Pull request merged**
