### PR TITLE
docs: Move to kubevirt/developer-guide

### PR DESCRIPTION
**Pull request by fabiand**
**What this PR does / why we need it**:
This is moving the /docs directory to an external repository (current proposal: kubevirt/developer-guide, as shown here: https://github.com/fabiand/developer-guide).
Primary reasons:
- Don't trigger CI for docs/ changes
- Have a repository with a clear purpose: Educate developers

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
The extracted docs can be found in https://github.com/fabiand/developer-guide.

I did consider to just propose to skip CI for changes to `docs/`.
In the end I did not like it because a) it adds an exception for CI b) if docs/ would require CI , then it might be hard to catch or solve.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabiand** [comment]
@lyarwood @acardace @xpivarc @aburdenthehand @vladikr @dhiller my proposal: Let's pull out the docs/ dir into a separate repository to
a) don't trigger ci on doc changes
b) shape up this new repository to be developer focused. AKA a repository with more focus and clear prupose.

**Comment by fabiand** [comment]
For completeness:
community repo also contains developer documentation/contributing guides.

we could
community/design-proposals --> repo:enhancements (as proposed by @lyarwood )
community/*developer guide stuff* --> repo:developer-guide (No pr)
kubevirt/docs --> repo:developer-guide (this PR)

This would move developer dcumentation to one central place.

Similar to how we moved release data from community to sig-release

**Comment by jean-edouard** [comment]
Good idea!
`docs/metrics.md` gets auto-generated, I guess we need to keep that one.
Also let's create and populate the new repo before merging this.
/hold

**Comment by aburdenthehand** [comment]
Interesting idea. 
I would expect to keep these files in this repo:
developer-certificate-of-origin.md
fossa.md
reviewer-guide.md

and maybe these ones as well (but I can see the argument for them moving):
getting-started.md
release-branch-backporting.md
release-procedure.md
release.md


Also, how much of this content belongs in the user guide rather than moved to a new repo?

**Comment by dhiller** [comment]
> Interesting idea. I would expect to keep these files in this repo: developer-certificate-of-origin.md fossa.md reviewer-guide.md
> 
> and maybe these ones as well (but I can see the argument for them moving): getting-started.md release-branch-backporting.md release-procedure.md release.md
> 
> Also, how much of this content belongs in the user guide rather than moved to a new repo?

Some of the docs you mentioned might be part of https://github.com/kubevirt/community/issues/235

**Pull request closed without merging**
