### PR TITLE
Add Microsoft as a KubeVirt adopter

### PR DESCRIPTION
**Pull request by harshitgupta1337**
### What this PR does
This PR adds Microsoft Corporation as an adopter of KubeVirt.

### CODE REVIEW

**Comment by xpivarc** [comment]
Please sign and squash your commits.
/cc @fabiand @aburdenthehand

**Comment by fabiand** [comment]
Nice!

**Comment by aburdenthehand** [comment]
@harshitgupta1337 Awesome to see!
+1 to Lubo's request to sign and squash the commits. 
(For context on the commit signing, please see this section of our [contrib guide](https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md#contributor-compliance-with-developer-certificate-of-origin-dco))

**Comment by fabiand** [comment]
ping?

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
