### PR TITLE
Bump Kubevirtci 2103261553-31913e9

### PR DESCRIPTION
**Pull request by ormergi**
**What this PR does / why we need it**:
Bump kubevirtci to 2103261553-31913e9 tag, includes the following changes:

- 31913e9 (tag: 2103261553-31913e9, upstream/master) Run bazelisk run //robots/cmd/kubevirtci-bumper:kubevirtci-bumper -- -ensure-last-three-minor-of v1 --k8s-provider-dir /home/prow/go/src/github.com/kubevirt/project-infra/../kubevirtci/cluster-provision/k8s (kubevirt/kubevirtci#573)
- ca50a75 (tag: 2103252139-ca50a75) SRIOV Provider use bare sriov components instead of sriov-network-operator (kubevirt/kubevirtci#563)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
I created this PR to reflect kubevirt/kubevirtci#563
Currently kubevirtci bump is not automated (I am not sure if we will ever want to automate this) 
and eventually kubevirtci release tags are piling up, also with the current kubevirtci release we must use the latest release tag.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — APPROVED** [review]

**Comment by ormergi** [comment]
k8s-1.19 lane failed due to VMI that failed to create due to tap0 device failed to create 
```{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"testvmi-mzvhj","namespace":"kubevirt-test-default1","pos":"vm.go:1534","reason":"failed to configure vmi network: Critical network error: error creating tap device named tap0; failed to execute command in launcher namespace 245461: failed running command /usr/bin/virt-chroot create-tap --tap-name tap0 --uid 0 --gid 0 --queue-number 0 --mtu 1480, err: exit status 1, output: Error: failed to create tap device named tap0. Reason: failed to create tap device named tap0. Reason: Tuntap IOCTL TUNSETIFF failed [0], errno operation not permitted\nUsage:\n  virt-chroot create-tap [flags]\n\nFlags:\n      --gid uint              the group of the owner of the tap device\n  -h, --help                  help for create-tap\n      --mtu uint32            the link MTU of the tap device (default 1500)\n      --queue-number uint32   the number of queues to use on multi-queued devices\n      --tap-name string       the name of the tap device (default \"tap0\")\n      --uid uint              the owner of the tap device\n\nGlobal Flags:\n      --cpu uint32      cpu time in seconds for the process\n      --memory uint32   memory in megabyte for the process\n      --mount string    mount namespace to use\n      --user string     switch to this targetUser to e.g. drop privileges\n\nfailed to create tap device named tap0. Reason: failed to create tap device named tap0. Reason: Tuntap IOCTL TUNSETIFF failed [0], errno operation not permitted\n","timestamp":"2021-03-29T10:17:07.928261Z","uid":"91ad804d-bbc3-4a51-a4cf-15b4a9cdb100"}```

k8s-1.18 failed due to conflict, I updated https://github.com/kubevirt/kubevirt/issues/4198

/retest

**Comment by ormergi** [comment]
k8s-1.18 failed again due to conflict
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5332/pull-kubevirt-e2e-k8s-1.18/1376534181026205696
/retest

**Review by fgimenez — COMMENTED** [review]
/lgtm

Thanks for working on this @ormergi! i find it a bit scary :) as we have talked we should aim to bump kubevirtci more frequently and with fewer changes. To be on the safe side it would be good to try a few more executions of the tests here, wdyt?

**Comment by oshoval** [comment]
/hold 

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5332/pull-kubevirt-e2e-kind-1.17-sriov/1376449874538532865

please take a look, the tests are skipped

`08:53:28:       Sriov is not enabled in this environment. Skip these tests using - export FUNC_TEST_ARGS='--ginkgo.skip=SRIOV'`

**Comment by ormergi** [comment]
> /hold
> 
> https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5332/pull-kubevirt-e2e-kind-1.17-sriov/1376449874538532865
> 
> please take a look, the tests are skipped
> its because the resource name maybe `SRIOVDP_RESOURCE_PREFIX` that kubevirt should have it as well.
> we should add a validator maybe that in case the cluster is sriov it should fail them, not skip, so we won't have it quiet again
> 
> `08:53:28: Sriov is not enabled in this environment. Skip these tests using - export FUNC_TEST_ARGS='--ginkgo.skip=SRIOV'`
> 
> `08:53:39: Ran 0 of 749 Specs in 78.611 seconds`


Thanks for the heads up!
I pushed a commit to update the resource name on the tests suite.

Regarding adding a validation that tests were not skip, 
I want to note that this PR  changes for the resource name that being used by the code that checks if its actually possible to run sriov tests on the cluster.

**Comment by ormergi** [comment]
> /lgtm
> 
> Thanks for working on this @ormergi! i find it a bit scary :) as we have talked we should aim to bump kubevirtci more frequently and with fewer changes. To be on the safe side it would be good to try a few more executions of the tests here, wdyt?

Fine by me, lets run it few more times

**Comment by oshoval** [comment]
> Regarding adding a validation that tests were not skip,
> I want to note that this PR changes for the resource name that being used by the code that checks if its actually possible to run sriov tests on the cluster.

It doesn't contradicts, in case of any reason that cluster-up will fail creating the resources and won't detect it,
this kubevirt check will skip silently the tests as it did with this PR before the last commit.
It doesn't need to be in this PR, it just a suggestion for the future.

**Comment by oshoval** [comment]
saw this failure from time to time
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5332/pull-kubevirt-unit-test/1376857686930362370
fails because timeout is long
we better open an issue or something about it

**Comment by oshoval** [comment]
```
12:54:11: ------------------------------
12:54:15: S [SKIPPING] in Spec Setup (BeforeEach) [4.038 seconds]
12:54:15: [Serial]SRIOV
12:54:15: tests/network/vmi_multus.go:587
12:54:15:   VirtualMachineInstance with sriov plugin interface
12:54:15:   tests/network/vmi_multus.go:634
12:54:15:     migration
12:54:15:     tests/network/vmi_multus.go:966
12:54:15:       should be successful with a running VMI on the target [BeforeEach]
12:54:15:       tests/network/vmi_multus.go:1008
12:54:15: 
12:54:15:       Migration tests require at least 2 nodes: not enough compute nodes with SR-IOV support detected
12:54:15: 
12:54:15:       tests/network/vmi_multus.go:970
12:54:15: ------------------------------
```

PTAL, you should make it spin 3 nodes?

**Comment by oshoval** [comment]
Just please make sure those flakes on https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5332/pull-kubevirt-unit-test/1376857686930362370 , for example, are not due to this PR

**Comment by ormergi** [comment]
> Just please make sure those flakes on https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5332/pull-kubevirt-unit-test/1376857686930362370 , for example, are not due to this PR

I saw it failed recently on testgrid, I dont think its related to this PR changes

**Comment by ormergi** [comment]
`Configurations [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with CPU spec [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]when CPU model defined [test_id:1678]should report defined CPU model`
failed on jobs:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5332/pull-kubevirt-e2e-k8s-1.18/1376857686909390848
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5332/pull-kubevirt-e2e-k8s-1.19/1376912799871012864
More details on https://github.com/kubevirt/kubevirt/issues/5005

/test pull-kubevirt-e2e-k8s-1.19

**Comment by ormergi** [comment]
Rebased 

There was a kubevirtci bump few days ago [commit](https://github.com/kubevirt/kubevirt/commit/b347c07ef0ddeff27be7298683b5d5b0852e95f5
), so this PR bring relatively less changes

**Comment by ormergi** [comment]
> Thanks for working on this @ormergi! i find it a bit scary :) as we have talked we should aim to bump kubevirtci more frequently and with fewer changes. To be on the safe side it would be good to try a few more executions of the tests here, wdyt?

@fgimenez There was a kubevirtci bump few days ago [commit](https://github.com/kubevirt/kubevirt/commit/b347c07ef0ddeff27be7298683b5d5b0852e95f5), now this PR bring much less changes

**Review by EdDev — COMMENTED** [review]
Please update the commit message with the changes it includes (like  we see now on the PR description).

**Comment by oshoval** [comment]
Doesnt https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5332/pull-kubevirt-unit-test/1377562329960419329
seems more flaky than without the bump ?

If so maybe wonder to consider bumping in few shots ?

**Comment by ormergi** [comment]
> Please update the commit message with the changes it includes (like we see now on the PR description).

Done

**Comment by ormergi** [comment]
> Doesnt https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5332/pull-kubevirt-unit-test/1377562329960419329
> seems more flaky than without the bump ?
> 
> If so maybe wonder to consider bumping in few shots ?
> 
> EDIT:
> lane is already in pretty bad shape, not sure about the specific test that fail in the link above
> https://prow.apps.ovirt.org/?job=pull-kubevirt-unit-test&state=failure

Yes this test seems to be flaky in general

**Comment by ormergi** [comment]
@dhiller could you please take a look?

**Comment by ormergi** [comment]
k8s-1.19
```
Storage Starting a VirtualMachineInstance [rfe_id:2298][crit:medium][vendor:cnv-qe@redhat.com][level:component] With HostDisk and PVC initialization With multiple empty PVCs [test_id:868]Should initialize an empty PVC by creating a disk.img
```
Failed due to the known issue with creating tap device 

k8s-1.18
```
[owner:@sig-compute]Configurations [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with CPU spec [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]when CPU model defined [test_id:1678]should report defined CPU model 
```
Failed due to failure consoling to the VMI, seems like there is a problem with the connection between `virt-api` and `virt-handler`

**Comment by ormergi** [comment]
One test failed due to VM's failed to create because of the tap devices issue
/retest

**Review by fgimenez — APPROVED** [review]
/lgtm

**Pull request merged**
