### PR TITLE
[release-1.0] update metrics names

### PR DESCRIPTION
**Pull request by avlitman**
This is a manual cherry-pick for: 

- https://github.com/kubevirt/kubevirt/pull/9821
- https://github.com/kubevirt/kubevirt/pull/9787
-  https://github.com/kubevirt/kubevirt/pull/10107
- https://github.com/kubevirt/kubevirt/pull/10322

### CODE REVIEW

**Review by enp0s3 — CHANGES_REQUESTED** [review]
@avlitman Hi. Please add the prefix `[release-1.0]` in the PR title

**Comment by avlitman** [comment]
As agreed with @enp0s3 and @kmajcher-rh we decided to postpone these changes to 4.15 therefor I'm closing this pr.

**Pull request closed without merging**
