### PR TITLE
DNM: test removal of CR update

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
This is just a test for now. Do not merge.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
@jean-edouard  Anything I can help with?

**Comment by jean-edouard** [comment]
> @jean-edouard Anything I can help with?

If this PR is of interest I could revive it.
Upgrading KubeVirt using the CR won't work if the target RBAC has permissions that the source doesn't, which is true in most cases, so the feature doesn't make much sense IMO.
This PR was to figure out how many tests would break without the feature, and the answer seems to be none, since the e2e lanes passed...

**Comment by xpivarc** [comment]
@jean-edouard Right, I think there are more caveats with updating just the images (Cr) without the operator and quit frankly I am convinced it complicates code. I would like to write down all the problems and present it to community for feedback. How did you stumble upon this?

**Comment by jean-edouard** [comment]
> How did you stumble upon this?

Funny story, the big functional test for this feature is broken (I don't remember how exactly unfortunately), but after fixing it it stopped passing! That's when I investigated and found this.

**Pull request closed without merging**
