### PR TITLE
Vm controller remove Informers 

### PR DESCRIPTION
**Pull request by xpivarc**
### What this PR does
Removes the usage of Informers in the VM controller as what we really need is `cache.Store` or `cache.Indexer`. 

Fixes #

### Special notes for your reviewer
The last commit mentions the simplification of unit tests. The problem is that we are using informers in the tests even when we most likely don't need them. This creates a problem because the `framework.FakeControllerSource` is not reflecting the changes synchronously. Meaning, an `.Add` will not be reflected in the underlying `cache.Store` right away and we always need to assert the existence if we don't want flaky behavior. Converting the controller to use `cache.Store` allows us to also switch the unit tests to directly use the store, removing the need for synchronization.

Note: We can also directly use the `cache.Store` of the informers today.

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
@jean-edouard You might be interested in the `Special notes for your reviewer` of this PR.

**Comment by jean-edouard** [comment]
> @jean-edouard You might be interested in the `Special notes for your reviewer` of this PR.

Very interesting indeed!
/cc

**Comment by iholder101** [comment]
Awesome stuff!
Your comment regarding the unit tests is very important. I have personally struggled with this many times and find it very non-intuitive and error prone. Can't wait for the next step of simplifying the unit tests, which is crucial for the project's health.

/approve

**Review by jean-edouard — APPROVED** [review]

**Comment by Barakmor1** [comment]
@xpivarc Have you considered using the [Lister API](https://github.com/kubernetes/client-go/blob/eea636f8f427d6d614ee1276e6ef21e54ef0d20b/listers/core/v1/pod.go#L30)?

**Pull request merged**
