### PR TITLE
[release-1.1] Deprecate cpu and memory exceeds alerts

### PR DESCRIPTION
**Pull request by avlitman**
**What this PR does / why we need it**:
Deprecate the KubeVirtComponentExceedsRequestedCPU and KubeVirtComponentExceedsRequestedMemory alerts.
These alerts are wrong and don't need to be reported to the user.

**Which issue(s) this PR fixes**:
Jira-Ticket: https://issues.redhat.com/browse/CNV-37900

**Special notes for your reviewer**:

- https://issues.redhat.com/browse/CNV-38320 will handle adding a metric to be able to track this issue without creating noise.

**Release note**:

```release-note
KubeVirtComponentExceedsRequestedCPU and KubeVirtComponentExceedsRequestedMemory alerts are deprecated; they do not indicate a genuine issue.
```

### CODE REVIEW

**Comment by brianmcarey** [comment]
@avlitman sorry it looks like the new bot lost the run of itself. FYI @dhiller

**Comment by avlitman** [comment]
> @avlitman sorry it looks like the new bot lost the run of itself. FYI @dhiller

Yes too much noise

**Comment by dhiller** [comment]
@avlitman fair to say that the bot has run crazy, however it's complaint is legit. Just commenting retest, after clearly seeing that the same tests fail over and over is not fair usage of CI.

Before triggering the tests again, please investigate the reason why the tests fail, maybe there's a backport of a fix missing somewhere.

**Comment by avlitman** [comment]
> tests

She I didn't say it's not true.. but I did look at the ci and it does not seem like an issue with the pr.. it failed on timeouts I couldn't find the reason and asked Igor to take a look but in the meantime I wanted to retest, the ci is flaky a lot of times..

**Comment by avlitman** [comment]
> @avlitman fair to say that the bot has run crazy, however it's complaint is legit. Just commenting retest, after clearly seeing that the same tests fail over and over is not fair usage of CI.
> 
> 
> 
> Before triggering the tests again, please investigate the reason why the tests fail, maybe there's a backport of a fix missing somewhere.

Thanks @dhiller, I didn't say it's not true.. but I did look at the ci and it does not seem like an issue with the pr.. it failed on timeouts I couldn't find the reason and asked Igor to take a look but in the meantime I wanted to retest, the ci is flaky a lot of times..

**Comment by dhiller** [comment]
[PR history](https://prow.ci.kubevirt.io/pr-history/?org=kubevirt&repo=kubevirt&pr=11445) shows that check-tests-for-flakes lane is failing every time. When looking at the runs the same test fails every time. I wouldn't call this flaky. WDYT?

**Comment by dhiller** [comment]
^^ @avlitman

**Comment by dhiller** [comment]
@jcanocan I faintly remember you were experiencing the same tests failing, no?

**Comment by dhiller** [comment]
This all is about 

`[Serial][sig-monitoring]Component Monitoring Errors metrics VirtOperatorRESTErrorsBurst and VirtOperatorRESTErrorsHigh should be triggered when requests to virt-operator are failing`

which is failing with 

```
{ Failure tests/tests_suite_test.go:107
Unexpected error:
    <*errors.StatusError | 0xc002bf7a40>: 
    Internal error occurred: failed calling webhook "kubevirt-update-validator.kubevirt.io": failed to call webhook: Post "https://kubevirt-operator-webhook.kubevirt.svc:443/kubevirt-validate-update?timeout=10s": dial tcp 10.105.153.146:443: connect: connection refused
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "Internal error occurred: failed calling webhook \"kubevirt-update-validator.kubevirt.io\": failed to call webhook: Post \"https://kubevirt-operator-webhook.kubevirt.svc:443/kubevirt-validate-update?timeout=10s\": dial tcp 10.105.153.146:443: connect: connection refused",
            Reason: "InternalError",
            Details: {
                Name: "",
                Group: "",
                Kind: "",
                UID: "",
                Causes: [
                    {
                        Type: "",
                        Message: "failed calling webhook \"kubevirt-update-validator.kubevirt.io\": failed to call webhook: Post \"https://kubevirt-operator-webhook.kubevirt.svc:443/kubevirt-validate-update?timeout=10s\": dial tcp 10.105.153.146:443: connect: connection refused",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 500,
        },
    }
occurred
tests/testsuite/kubevirtresource.go:205}
```

**Comment by jcanocan** [comment]
> This all is about
> 
> `[Serial][sig-monitoring]Component Monitoring Errors metrics VirtOperatorRESTErrorsBurst and VirtOperatorRESTErrorsHigh should be triggered when requests to virt-operator are failing`
> 
> which is failing with
> 
> ```
> { Failure tests/tests_suite_test.go:107
> Unexpected error:
>     <*errors.StatusError | 0xc002bf7a40>: 
>     Internal error occurred: failed calling webhook "kubevirt-update-validator.kubevirt.io": failed to call webhook: Post "https://kubevirt-operator-webhook.kubevirt.svc:443/kubevirt-validate-update?timeout=10s": dial tcp 10.105.153.146:443: connect: connection refused
>     {
>         ErrStatus: {
>             TypeMeta: {Kind: "", APIVersion: ""},
>             ListMeta: {
>                 SelfLink: "",
>                 ResourceVersion: "",
>                 Continue: "",
>                 RemainingItemCount: nil,
>             },
>             Status: "Failure",
>             Message: "Internal error occurred: failed calling webhook \"kubevirt-update-validator.kubevirt.io\": failed to call webhook: Post \"https://kubevirt-operator-webhook.kubevirt.svc:443/kubevirt-validate-update?timeout=10s\": dial tcp 10.105.153.146:443: connect: connection refused",
>             Reason: "InternalError",
>             Details: {
>                 Name: "",
>                 Group: "",
>                 Kind: "",
>                 UID: "",
>                 Causes: [
>                     {
>                         Type: "",
>                         Message: "failed calling webhook \"kubevirt-update-validator.kubevirt.io\": failed to call webhook: Post \"https://kubevirt-operator-webhook.kubevirt.svc:443/kubevirt-validate-update?timeout=10s\": dial tcp 10.105.153.146:443: connect: connection refused",
>                         Field: "",
>                     },
>                 ],
>                 RetryAfterSeconds: 0,
>             },
>             Code: 500,
>         },
>     }
> occurred
> tests/testsuite/kubevirtresource.go:205}
> ```

Yes. We have experienced something similar that on SSP some time ago. The problem was related with crypto policies. We statically set the cypher and restart the pod when changed. Also, we had crypto policies tests running right before the webhook tests. Therefore, the crypto policy tests changed the cypher multiple times and, there were some leftovers and, in some occasions, traffic was sent to the previous webhook configured with the old crypto policy.

**Comment by dhiller** [comment]
> > This all is about
> > `[Serial][sig-monitoring]Component Monitoring Errors metrics VirtOperatorRESTErrorsBurst and VirtOperatorRESTErrorsHigh should be triggered when requests to virt-operator are failing`
> > which is failing with
> > ```
> > { Failure tests/tests_suite_test.go:107
> > Unexpected error:
> >     <*errors.StatusError | 0xc002bf7a40>: 
> >     Internal error occurred: failed calling webhook "kubevirt-update-validator.kubevirt.io": failed to call webhook: Post "https://kubevirt-operator-webhook.kubevirt.svc:443/kubevirt-validate-update?timeout=10s": dial tcp 10.105.153.146:443: connect: connection refused
> >     {
> >         ErrStatus: {
> >             TypeMeta: {Kind: "", APIVersion: ""},
> >             ListMeta: {
> >                 SelfLink: "",
> >                 ResourceVersion: "",
> >                 Continue: "",
> >                 RemainingItemCount: nil,
> >             },
> >             Status: "Failure",
> >             Message: "Internal error occurred: failed calling webhook \"kubevirt-update-validator.kubevirt.io\": failed to call webhook: Post \"https://kubevirt-operator-webhook.kubevirt.svc:443/kubevirt-validate-update?timeout=10s\": dial tcp 10.105.153.146:443: connect: connection refused",
> >             Reason: "InternalError",
> >             Details: {
> >                 Name: "",
> >                 Group: "",
> >                 Kind: "",
> >                 UID: "",
> >                 Causes: [
> >                     {
> >                         Type: "",
> >                         Message: "failed calling webhook \"kubevirt-update-validator.kubevirt.io\": failed to call webhook: Post \"https://kubevirt-operator-webhook.kubevirt.svc:443/kubevirt-validate-update?timeout=10s\": dial tcp 10.105.153.146:443: connect: connection refused",
> >                         Field: "",
> >                     },
> >                 ],
> >                 RetryAfterSeconds: 0,
> >             },
> >             Code: 500,
> >         },
> >     }
> > occurred
> > tests/testsuite/kubevirtresource.go:205}
> > ```
> 
> Yes. We have experienced something similar that on SSP some time ago. The problem was related with crypto policies. We statically set the cypher and restart the pod when changed. Also, we had crypto policies tests running right before the webhook tests. Therefore, the crypto policy tests changed the cypher multiple times and, there were some leftovers and, in some occasions, traffic was sent to the previous webhook configured with the old crypto policy.

So I figure there's a backport missing, since I didn't see this test flaking in 1.2++?

**Comment by avlitman** [comment]
Thank you @dhiller I did run make generate and it update to year 2024 in somre files, should I commit that?

**Comment by enp0s3** [comment]
@machadovilaca Hey, can you please help investigating the failure? maybe some leftover from previous monitoring test spec.

**Comment by enp0s3** [comment]
@avlitman It may not be related to your changes but still it can be flaky. The flake could be fixed in main but didn't backport. Note that monitoring lane is not always triggered so it may have been flaky and unnoticed

**Comment by machadovilaca** [comment]
looking

**Comment by enp0s3** [comment]
@avlitman @machadovilaca Please note that the previous ginkgo container `errors metrics` deals with deleting and creating the virt-operator role binding, it may affect the access of virt-operator to to the api components

**Comment by machadovilaca** [comment]
> @avlitman @machadovilaca Please note that the previous ginkgo container `errors metrics` deals with deleting and creating the virt-operator role binding, it may affect the access of virt-operator to to the api components

seems strange, in that case I would expect a fail in both:

```
_, err = virtClient.RbacV1().ClusterRoleBindings().Create(context.Background(), crb, metav1.CreateOptions{})
			if !errors.IsAlreadyExists(err) {
				util.PanicOnError(err)
			}
```

and 

```
			waitUntilAlertDoesNotExist(virtClient, virtOperator.downAlert, virtApi.downAlert, virtController.downAlert, virtHandler.downAlert)
```

the role binding wouldn't have been restored properly, and the alert should still be firing

**Comment by machadovilaca** [comment]
and the error seems to be patching the namespace:
`tests/testsuite/kubevirtresource.go:205`

```
	kv, err = virtClient.KubeVirt(kv.Namespace).Patch(kv.GetName(), types.MergePatchType, patch, &metav1.PatchOptions{})
	Expect(err).ToNot(HaveOccurred())
```

**Comment by machadovilaca** [comment]
@enp0s3 @avlitman https://github.com/kubevirt/kubevirt/pull/11506

**Comment by avlitman** [comment]
> @enp0s3 @avlitman https://github.com/kubevirt/kubevirt/pull/11506

Thank you for creating a fix. So @enp0s3 let's merge the fix first right?

**Comment by avlitman** [comment]
Hi @enp0s3 monitoring lane succeed any chance you can take a look again?

**Review by enp0s3 — APPROVED** [review]
/hold cancel
/approve

**Pull request merged**
