### PR TITLE
TEST: make deploy script executable

### PR DESCRIPTION
**Pull request by lukas-bednar**

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by lukas-bednar** [comment]
@rmohr it got committed https://github.com/kubevirt-incubator/api-reference/commits/master

The thing is that it will make a commit on every change, because timestamp is getting changed.
Do you think that I should deal with it and do a commit only when there is real change ?

**Comment by rmohr** [comment]
@lukas-bednar we can suppress the last updated line, I think: https://github.com/asciidoctor/asciidoctor/issues/1621

**Comment by lukas-bednar** [comment]
@rmohr thanks, it worked!

**Pull request merged**
