### PR TITLE
Revert "Use ginkgo's contexts - update the coding-conventions"

### PR DESCRIPTION
**Pull request by fossedihelm**
### What this PR does
This reverts https://github.com/kubevirt/kubevirt/pull/12148
The reason is that we need a proper discussion and get more feedback from the community.

Fixes #

### Release note

```release-note
NONE
```

/cc @nunnatsa @0xFelix @EdDev @xpivarc @jean-edouard

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by brianmcarey** [comment]
@fossedihelm the revert commit needs to be signed.

**Comment by fossedihelm** [comment]
> @fossedihelm the revert commit needs to be signed.

Yes, I was working on it :) Thank you!

**Pull request merged**
