### PR TITLE
[flaky CI] Disable missed test

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
Disable missed test in https://github.com/kubevirt/kubevirt/pull/4960.

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by enp0s3** [comment]
@fgimenez should we put this test in a quarantine?

**Review by dhiller — COMMENTED** [review]
Shouldn't the test just get a quarantine label?

**Comment by fgimenez** [comment]
Indeed, didn't know about this PR sorry, I've already added the label here https://github.com/kubevirt/kubevirt/pull/5190

**Comment by xpivarc** [comment]
Thanks, guys!

**Comment by xpivarc** [comment]
We don't need this anymore. Test was added to quarantine.

**Pull request closed without merging**
