### PR TITLE
Check how prow dco plugin looks

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

This is just a test for the Prow DCO plugin. I added an unsigned commit to see how it looks.

/hold
/cc @rmohr

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
Looking good so far, the only thing I need to know is how to make the check mandatory.

**Comment by dhiller** [comment]
Maybe this is the way to do it: kubevirt/project-infra#192

**Comment by rmohr** [comment]
> Looking good so far, the only thing I need to know is how to make the check mandatory.

I think that for tide it is mandatory anyway, but for normal merges, I don't think so.

**Comment by dhiller** [comment]
Ah, ok, then we don't need to make it mandatory like in the PR I just posted, right? Need to brush up reading about Prow config then :)

**Comment by dhiller** [comment]
But shouldn't they also be marked as required then? I manually did that in branch protection settings to make it look like it is now.

**Comment by rmohr** [comment]
> But shouldn't they also be marked as required then? I manually did that in branch protection settings to make it look like it is now.

Afaik, tide only looks on its internal configuration. I think it even tries to merge PRs if a required job fails and it is not listed in the branch protection config.

**Comment by rmohr** [comment]
> Afaik, tide only looks on its internal configuration. I think it even tries to merge PRs if a required job fails and it is not listed in the branch protection config.

But: there exists the branchprotector https://github.com/kubernetes/test-infra/tree/master/prow/cmd/branchprotector (which we did not deploy), which can configure github the way prow sees the configuration.

**Comment by dhiller** [comment]
> > But shouldn't they also be marked as required then? I manually did that in branch protection settings to make it look like it is now.
> 
> Afaik, tide only looks on its internal configuration. I think it even tries to merge PRs if a required job fails and it is not listed in the branch protection config.

I found [this configuration of tide](https://github.com/openshift/release/blob/master/core-services/prow/02_config/_config.yaml#L644), might be the right one?

**Comment by rmohr** [comment]
> I found [this configuration of tide](https://github.com/openshift/release/blob/master/core-services/prow/02_config/_config.yaml#L644), might be the right one?

Great, that looks like it!

**Comment by rmohr** [comment]
/close

Everything works like expected. @dhiller thx!

**Pull request closed without merging**
