### PR TITLE
Added supported values for v1.Disk cache mode in API document

### PR DESCRIPTION
**Pull request by yuhaohaoyu**
Signed-off-by: Hao Yu <yuh@us.ibm.com>

**What this PR does / why we need it**:

In KubeVirt API document at https://kubevirt.io/api-reference/master/definitions.html#_v1_disk , the default values for the disk cache mode should be specified for good user experience. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1896795

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/ok-to-test
/approve
/hold

**Review by enp0s3 — APPROVED** [review]
Thank you
/lgtm

**Comment by xpivarc** [comment]
@EdDev can you have a look at this test https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5183/pull-kubevirt-unit-test/1369687355304185856 , please?

**Comment by EdDev** [comment]
> @EdDev can you have a look at this test https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5183/pull-kubevirt-unit-test/1369687355304185856 , please?

Interesting, I have never seen it fail before.
Very odd too, there is no goroutine involved.
@xpivarc can you open an issue on this for tracking (and assign it to me)?

**Comment by xpivarc** [comment]
@EdDev  Thanks :)

**Comment by qinqon** [comment]
"""
/hold
until emergency CI fixes of #5207 are merged
"""

**Pull request merged**
