### PR TITLE
Align with latest kubevirtci.

### PR DESCRIPTION
**Pull request by fedepaol**
**What this PR does / why we need it**:

With this PR we align kubevirtci to the latest release.

The changes are:
- bumping the sr-iov operator image version
- deploying the sr-iov mutating webhook that adds resource requirement to the pods

https://github.com/kubevirt/kubevirtci/pull/167
https://github.com/kubevirt/kubevirtci/pull/163

By bumping the operator image version we avoid consuming unwanted updates and we stabilize the ci.
By deploying the webhook, we test our compatibility against the webhook deployed by the sr-iov operator to add the resource requirements.

**Release note**:

```release-note

NONE

```

### CODE REVIEW

**Comment by rmohr** [comment]
Merging to fix the sriov lane.

**Comment by rmohr** [comment]
@fedepaol could you look into a backport?

**Comment by fedepaol** [comment]
@rmohr sure

**Comment by fedepaol** [comment]
@rmohr I don't think we need to back port this. 0.20 is still using the manual sr-iov configuration, no operators are involved there. If we want to move it to the operator it's not a cherry pick.

**Comment by rmohr** [comment]
Perfect. No backport then.

**Pull request merged**
