### PR TITLE
Remove libvirt-go dependencies in virt-handler

### LINKED ISSUE #5023: remove libvirtd and other unused tools from virt-handler
Virt handler and virt launcher should have different RPM trees. There's no reason (i'm aware of) for virt-handler to contain the libvirtd daemon for example. This has led to some assumptions that since libvirtd is available within virt-handler, that it has a purpose.

> /kind bug

### PR DESCRIPTION
**Pull request by rmohr**
Ensure a clear separation between libvirt and virt-handler.

1. Some minor data type references were pulling in the dependency.

```
bazel query "allpaths(//cmd/virt-handler:virt-handler, //vendor/libvirt.org/go/libvirt:go_default_library)"
```

shows no remaining dependencies.

2. use a trimmed down container for virt-handler which does especially not container libvirtd or libvirt-client to clearer enforce our intended architecture that only virt-launcher has a direct relationship to libvirt and qemu.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5023

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
All issues resolved. The failing test seems to be unrelated to this PR.

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

Thanks!

**Pull request merged**
