### PR TITLE
[Flaky] 3188 test - improve reporting to catch a problem

### PR DESCRIPTION
**Pull request by brybacki**
Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

**What this PR does / why we need it**:
Test: `[sig-storage] DataVolume Integration [rfe_id:3188][crit:high][vendor:cnv-qe@redhat.com][level:system] Starting a VirtualMachineInstance with a DataVolume as a volume source Alpine import should accurately report DataVolume provisioning`
fails sometimes, need to investigate if the test is flaky or there is a real issue.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Improving test reporting - Investigating the issue, trying to run locally and in the CI env. The commit with real fix should follow.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder-redhat** [comment]
Hey @brybacki! Thanks for your work!

When a PR is still under work and not ready for review, It's best to mark it as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/). This way reviewers will know not to review it yet.

For draft PRs the test lanes don't start to run automatically, but you can run them manually by either doing
`/test <TEST-NAME>`
Or:
`/test all`

Thanks!

**Comment by brybacki** [comment]
> 

Right, forgot to click the draft button ;)

**Comment by iholder-redhat** [comment]
> Right, forgot to click the draft button ;)

Well, it's not too late :)
Screenshot-2022_04_26_14_47_08-366x349

**Comment by brybacki** [comment]
> > Right, forgot to click the draft button ;)
> 
> Well, it's not too late :) Screenshot-2022_04_26_14_47_08-366x349

interesting, I was looking for this, and in the meantime I have added WIP to the title.

**Comment by iholder-redhat** [comment]
> interesting, I was looking for this, and in the meantime I have added WIP to the title.

Thanks!

**Comment by brybacki** [comment]
pull-kubevirt-e2e-k8s-1.22-sig-storage

**Comment by brybacki** [comment]
finally, it failed, I can check the new reports.

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7634/pull-kubevirt-e2e-k8s-1.22-sig-storage/1534424372658311168

**Comment by brybacki** [comment]
@mhenriks can you take a look?

**Comment by brybacki** [comment]
After talking with @xpivarc and looking at the logs, I think this is what happens:

VM is created, then it should show Provisioning. But sometimes when the virt-controller errors more than once on "the object has been modified; please apply your changes to the latest version and try again", then we can miss the `PrintableStatus == provisioning`, because the next time it reconciles, it will see DV `Succeeded` and will show status Stopped (https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7634/pull-kubevirt-e2e-k8s-1.22-sig-storage/1534424372658311168/artifacts/k8s-reporter/3/pods/1_kubevirt_virt-controller-6c969c86d6-xmlt5-virt-controller.log). 

@mhenriks I can see you are the author of the test. Do we need it? If we really want to see `provisioning` in functional test then maybe we need to create a clone DV. That way we can stop provisioning (for example by utilizing source in use). WDYT?

**Comment by mhenriks** [comment]
> @mhenriks I can see you are the author of the test. Do we need it? If we really want to see provisioning in functional test then maybe we need to create a clone DV. That way we can stop provisioning (for example by utilizing source in use). WDYT?

Good detective work here, I like the idea about changing this from import to clone.

**Pull request merged**
