### PR TITLE
[release-0.30] Bump kubevirtci: Stabilize SRIOV lane

### PR DESCRIPTION
**Pull request by ormergi**
**What this PR does / why we need it**:
This is a cherry-pick of #3509 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
@ormergi I believe these 2 hunks are also required for the bump:
https://github.com/kubevirt/kubevirt/pull/3536/commits/4561ec5396e19f8d8136f8947fd15f5b87f4b2ac#diff-813e1c58f7ca2595e98f7d7ead25d208
https://github.com/kubevirt/kubevirt/pull/3536/commits/4561ec5396e19f8d8136f8947fd15f5b87f4b2ac#diff-a5a178b4c66835110ceff63c61d28c96

**Comment by ormergi** [comment]
> @ormergi I believe these 2 hunks are also required for the bump:
> [4561ec5#diff-813e1c58f7ca2595e98f7d7ead25d208](https://github.com/kubevirt/kubevirt/commit/4561ec5396e19f8d8136f8947fd15f5b87f4b2ac#diff-813e1c58f7ca2595e98f7d7ead25d208)
> [4561ec5#diff-a5a178b4c66835110ceff63c61d28c96](https://github.com/kubevirt/kubevirt/commit/4561ec5396e19f8d8136f8947fd15f5b87f4b2ac#diff-a5a178b4c66835110ceff63c61d28c96)

Can you please elaborate why this is necessary?

**Comment by ormergi** [comment]
/close
No longer needed

**Pull request closed without merging**
