### PR TITLE
Add mirrors for the fedora image

### PR DESCRIPTION
**Pull request by cynepco3hahue**
**What this PR does / why we need it**:
Add mirrors for the Fedora image
I chose one with the biggest bandwidth from https://admin.fedoraproject.org/mirrormanager/mirrors/Fedora/29

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@slintes I still can see the problem with Fedora image, so I do not really sure it helps.
I think the problem, that download partially succeeds, but after checking the hash sum fails.

**Comment by slintes** [comment]
Too bad. But still better than only having 1 url only, that way we at least prevent errors when a mirror is down.
Maybe even remove download.fedoraproject.org? Maybe that's the only one causing problems?

**Comment by cynepco3hahue** [comment]
@rmohr Checked bazel cache, and it has the Fedora image, so looks like we have some problems with connectivity to bazel cache

**Comment by cynepco3hahue** [comment]
@rmohr Propose to build artifacts, before running the cluster, so I will try it

**Comment by rmohr** [comment]
@cynepco3hahue removed the cache clean and the error is back. Could it be that stdci recycles the docker volume and your `clean`  really did the trick?

**Comment by rmohr** [comment]
But still not sure if it wouldn't have occurred with the cache clean again.

**Comment by cynepco3hahue** [comment]
@rmohr Clean does not really help, I still can see 3 lanes with the same error. Also, I added `curl` before and it succeeds to download the image without any troubles. I currently do not have any other ideas, any thoughts?

**Comment by gbenhaim** [comment]
- Currently, docker volumes are not being kept between jobs. Can we use a bind mount instead of a docker volume?

- It indeed looks like the download didn't finished successfully, thus the sha256 was wrong. Do we know from where it tried to download the image `greenhouse` or fedora mirrors?

**Comment by rmohr** [comment]
> Currently, docker volumes are not being kept between jobs. Can we use a bind mount instead of a docker volume?

That is perfect. We don't want to keep them. 

> It indeed looks like the download didn't finished successfully, thus the sha256 was wrong. Do we know from where it tried to download the image greenhouse or fedora mirrors?

We still have the Fedora mirror on the first place. So it is still preferred. Maybe we just have to move it to the end of the list. 

Gal could you also verify that all nodes have sufficient space left for docker in docker? It still looks a little bit like it might be related to a single node issue.

**Comment by gbenhaim** [comment]
> Currently, docker volumes are not being kept between jobs. Can we use a bind mount instead of a docker volume?

That is perfect. We don't want to keep them.

> It indeed looks like the download didn't finished successfully, thus the sha256 was wrong. Do we know from where it tried to download the image greenhouse or fedora mirrors?

We still have the Fedora mirror on the first place. So it is still preferred. Maybe we just have to move it to the end of the list.

>> I would like to understand if the connectivity issue is between the ci pod and greenhouse pod, or between the ci pod and the fedora mirror. How can we know if it failed to fetch the image from cache or not?

Gal could you also verify that all nodes have sufficient space left for docker in docker? It still looks a little bit like it might be related to a single node issue.

I've checked it now, all nodes have 200GB+ free space.

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by rmohr** [comment]
ci test please

**Comment by rmohr** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
@rmohr @slintes 
I think I will close this PR, it just does not solve anything, we still have two problems:
- from some reason, build does not take fedora image from greenhouse
- it downloads only part of the image, so checksum does not correct(I think it some bazel bug)

**Comment by rmohr** [comment]
We should really try downgrading to bazel 0.21.

**Comment by rmohr** [comment]
Closing this one works for me.

**Pull request closed without merging**
