### PR TITLE
Specify a node to create a VM

### LINKED ISSUE #10937: Specify a node to create a VM
**Is your feature request related to a problem? Please describe**:

Though we have [Node assignment](https://kubevirt.io/user-guide/operations/node_assignment/) to chose which node to be scheduled. But in some scenarios we still need to specify an exact node to create a virtual machine and the function is the same to K8s' POD.

**Describe the solution you'd like**:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-cirros
spec:
  template:
    spec:
      nodeName: host-0-1

```

**Describe alternatives you've considered**:

**Additional context**:

### PR DESCRIPTION
**Pull request by matthewei**
**What this PR does / why we need it**:

Though we have [Node assignment](https://kubevirt.io/user-guide/operations/node_assignment/) to chose which node to be scheduled. But in some scenarios we still need to specify an exact node to create a virtual machine and the function is the same to K8s' POD.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10937

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-cirros
spec:
  template:
    spec:
      nodeName: host-0-1
```

### CODE REVIEW

**Comment by matthewei** [comment]
Pending tests

**Comment by dankenigsberg** [comment]
@matthewei thank you very much for your contribution and a happy new year.

We already have two method to specify on which node the VM should run: `nodeSelector` and `nodeAffinity`. We should not add a third method. I wish we had just one (but it's very hard to deprecate a field once it was introduced).

The VMI schema is quite complex as it is. It take time for users to learn and properly use; it has plenty of code to parse and validate; We should be very careful before adding more fields to it.

**Comment by matthewei** [comment]
> @matthewei thank you very much for your contribution and a happy new year.
> 
> We already have two method to specify on which node the VM should run: `nodeSelector` and `nodeAffinity`. We should not add a third method. I wish we had just one (but it's very hard to deprecate a field once it was introduced).
> 
> The VMI schema is quite complex as it is. It take time for users to learn and properly use; it has plenty of code to parse and validate; We should be very careful before adding more fields to it.

Hi @dankenigsberg , Thanks a lot and a nice day. I know what your concern but as you know the pod also has this feature to chose which node to be selceted. As kubevirt is considered to manage the virtual machine as a pod. We shouldn't give up on the code because it's complicated. In fact, it's not complicated. Why not give user a new method  to chose node?

**Comment by dankenigsberg** [comment]
> I know what your concern but as you know the pod also has this feature to chose which node to be selceted. As kubevirt is considered to manage the virtual machine as a pod. 

IMHO the fact that k8s's Pod has three methods to choose on which node it should run is a historical mistake that should not be repeated. In fact, in a cloud-native environment, workers are dispensable: a failure in a single worker must not affect your workload. Therefore, letting a user select a specific node is an invitation for serious operational complexity. In a production system, node affinity should refer to an availability zone, or a another collection of many nodes, not a single named one.

> We shouldn't give up on the code because it's complicated. In fact, it's not complicated. Why not give user a new method to chose node?

pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go has moew than 2700 lines of code. That is complex. Adding another field means increasing this complexity. It means adding more tests that may fail. We should add fields only if they are really needed by our users. Can you share more about the requirement to add this field? Maybe I am mistaken, and this is actually necessary.

**Comment by matthewei** [comment]
> We shouldn't give up on the code because it's complicated. In fact, it's not complicated. Why not give user a new method to chose node?

The openstack has this feature and this is my original idea. The openstack can allow user to chose one node to boot a VM. So I think we also need it. 

```shell
openstack server create --flavor m1.small --image cirros --key-name mykey --availability-zone nova:compute-node-1 myinstance
```

I also agree your opinion and we can use  nodeSelector to chose which one node to be selected. What about to extend `virtctl` command to realize it? we don't need change so many codes.

**Comment by dankenigsberg** [comment]
> The openstack has this feature and this is my original idea. The openstack can allow user to chose one node to boot a VM. So I think we also need it.
> 
> ```shell
> openstack server create --flavor m1.small --image cirros --key-name mykey --availability-zone nova:compute-node-1 myinstance
> ```
> 
> I also agree your opinion and we can use nodeSelector to chose which one node to be selected. What about to extend `virtctl` command to realize it? we don't need change so many codes.

Yes, I think that adding such an option to https://kubevirt.io/user-guide/virtual_machines/creating_vms/ is very reasonable.

**Comment by matthewei** [comment]
> > The openstack has this feature and this is my original idea. The openstack can allow user to chose one node to boot a VM. So I think we also need it.
> > ```shell
> > openstack server create --flavor m1.small --image cirros --key-name mykey --availability-zone nova:compute-node-1 myinstance
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also agree your opinion and we can use nodeSelector to chose which one node to be selected. What about to extend `virtctl` command to realize it? we don't need change so many codes.
> 
> Yes, I think that adding such an option to https://kubevirt.io/user-guide/virtual_machines/creating_vms/ is very reasonable.

Do you mind if I expand virtctl to implement this feature?

**Comment by dankenigsberg** [comment]
> Do you mind if I expand virtctl to implement this feature?

Not at all.

**Comment by fabiand** [comment]
FWIW I think that KubeVirt needs to beef up it's strength in --availability-zone

**Pull request closed without merging**
