### PR TITLE
[e2e] Improve events deletion in AfterEach

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
Currently, we are deleting every events in a namespace after each test. The way we are doing this increased the runtime of the e2e lanes by a considerable amount.
Let's use delete collection instead of retrieving the events and delete one by one.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Alternative for https://github.com/kubevirt/kubevirt/pull/9960
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
Please consider https://github.com/kubevirt/kubevirt/pull/8848

**Comment by xpivarc** [comment]
Both the PRs seem to be ready. I feel it comes down to want is more right.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Pull request merged**
