### PR TITLE
Increase rate limits for k8s test reporter

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

We fetch quite some resources. Increase the rate limiter a little bit, to shorten report times, which can otherwise easily be minutes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by rmohr** [comment]
@xpivarc do you also plan to give LGTM or should I look for another reviewer?

**Comment by xpivarc** [comment]
> @xpivarc do you also plan to give LGTM or should I look for another reviewer?

/lgtm
I usually allow others to have look but I don't see harm here :) Thanks for the PR!

**Pull request merged**
