### PR TITLE
[release-0.44] Ensure optimal CPU pinning with dedicated CPUs

### PR DESCRIPTION
**Pull request by rmohr**
This is a manual cherry-pick of #6251

```release-note
Better place vcpu threads on host cpus to form more efficient passthrough architectures
```

### CODE REVIEW

**Comment by rmohr** [comment]
/close

just closing because of  the wrong base

**Review by jean-edouard — COMMENTED** [review]
/approve

**Comment by vladikr** [comment]
/lgtm 
Thanks, I don't see any issues.

**Pull request merged**
