### PR TITLE
Mirror fedora cloud images on GCS

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

The fedora mirror has pretty often temprorary issues. Add the images to
GCS to reduce the amount of failed downloads. The original source is preferred.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
> [GET returned 403 Forbidden

Hm, the limiter got triggered, which should limit public access in case we run out of budget. I don't understand why yet.

> Can you please add a comment or something, on how to get image there when we update to another one?

It is done manually now. I started on a prow plugin which does that automatically.

**Comment by slintes** [comment]
> It is done manually now. I started on a prow plugin which does that automatically.

nice :+1:

**Comment by rmohr** [comment]
/approve

The bucket adjustments work

**Pull request merged**
