### PR TITLE
Update CDI to v1.31.0

### PR DESCRIPTION
**Pull request by maya-r**
**What this PR does / why we need it**:
In #5006 we have an "end-to-end" style test which enables preallocation and we see that it also disables discard.
For this test to pass, we need the latest fixes to preallocation, and a Preallocation field in v1alpha1 DataVolumes.
This is available since CDI v1.31.0.

This also means we fetch from quay.io :-) 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Obsolete #5099 if this one is merged first.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by stu-gott** [comment]
/override pull-kubevirt-e2e-k8s-cnao-1.19

The only two test failures in this run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5126/pull-kubevirt-e2e-k8s-cnao-1.19/1366456692199395328 are exactly the ones fixed in PR 5114

**Comment by maya-r** [comment]
I think it is fair to override the k8s-1.18 result.
This latest test run is the same failures as the cnao lane, which we say we have a fix for in another PR: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5126/pull-kubevirt-e2e-k8s-1.18/1366552574982885376

(let's see if this works)
/override pull-kubevirt-e2e-k8s-1.18

/test pull-kubevirt-e2e-k8s-1.19

**Comment by aglitke** [comment]
```
for i in `seq 1 100`; do
    /retest
done
```
😬

**Comment by stu-gott** [comment]
/override pull-kubevirt-e2e-k8s-1.18

Per comment from @maya-r 9 hours prior, pull-kubevirt-e2e-k8s-1.18 failed with the exact two expected/known test failures and nothing else.

**Comment by maya-r** [comment]
We appear to be moving backwards when it comes to passing CI

**Comment by stu-gott** [comment]
@rmohr all lanes on this PR have passed at least once.

**Comment by stu-gott** [comment]
/override pull-kubevirt-e2e-k8s-1.17-rook-ceph
/override pull-kubevirt-e2e-k8s-1.18
/override pull-kubevirt-e2e-k8s-1.19

All these lanes have passed previously

**Pull request merged**
