### PR TITLE
preformance: Use libinstancetype and libvmi during instance type tests

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/sig scale
/sig code-quality

### What this PR does

The instance type related performance tests now use `libvmi` and `libinstancetype` to generate the required resources.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by enp0s3** [comment]
@lyarwood Thank you!
/approve

**Comment by lyarwood** [comment]
> Putting an hold only if a sig-scale review is strictly required. Feel free to unhold otherwise /hold

/cc @rthallisey 

Would you mind taking a look?

I'll address the nit from @fossedihelm in a follow up as it's going to hit various other paths.

**Comment by lyarwood** [comment]
> > Putting an hold only if a sig-scale review is strictly required. Feel free to unhold otherwise /hold
> 
> /cc @rthallisey
> 
> Would you mind taking a look?
> 
> I'll address the nit from @fossedihelm in a follow up as it's going to hit various other paths.

/cc @alaypatel07 

If Ryan isn't around would you mind taking a look and unholding if you're okay with this?

**Review by alaypatel07 — APPROVED** [review]
Thanks for cleaning up the density test code, changes look good.

When digging into this I found that many critical metrics are missing when running vmi with instance types test: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12248/pull-kubevirt-e2e-k8s-1.29-sig-performance/1806716873765556224/artifacts/performance/VM-instance-type-preference-perf-audit-results.json, for example CREATE-virtualmachineinstance-count, CREATE-pod-count, etc

This is something that needs to be looked into as a separate issue @lyarwood 

/lgtm

**Pull request merged**
