### PR TITLE
WIP: RFC: podman compatibility in the developer workflow

### PR DESCRIPTION
**Pull request by fromanirh**
**What this PR does / why we need it**:
Nowadays the developer workflow requires docker. This PR wants to make it possible to use podman instead. In other words, if you do
```bash
alias docker=podman
```
you should see no difference (unless you look at the output of `ps`) in your developer workflow :)

What works today:

- `make`
- `make test`

Definition of "works": I use it in my workflow and get the desired results.

There is no ETA yet - I'm working on this PR on my spare cycles.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
N/A

**Special notes for your reviewer**:
This PR is not ready for a real review, let alone for merge. I posted to make the other developers aware of this effort and to have a place to discuss issues, things we should have/fix and so on.

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by fromanirh** [comment]
@stu-gott FYI - we briefly talked about this few times in the recent past

**Comment by rmohr** [comment]
@fromanirh most work will be to convert gocli. It is shipped itself in a container and uses the dockers-sdk. The rest should mostly, like done here, exchanging docker with podman.

**Comment by fromanirh** [comment]
> @fromanirh most work will be to convert gocli. It is shipped itself in a container and uses the dockers-sdk. The rest should mostly, like done here, exchanging docker with podman.

@rmohr ack, thanks for the tip

**Pull request closed without merging**
