### PR TITLE
Add: Kasten by Veeam - K10 to Integrations

### PR DESCRIPTION
**Pull request by mlavi**
**What this PR does / why we need it**:
 Adds Kasten K10 integration to the ADOPTERS.md file for inclusion to the community.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
None

**Special notes for your reviewer**:
 As discussed in the community meeting, I'm finally following up! This is an attempt to fix my previous PR #9605
 CC: @aburdenthehand @usrbinkat 
 
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm
/ok-to-test

**Comment by aburdenthehand** [comment]
@mlavi Great to see! Thanks for following up :)
/lgtm

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
