### PR TITLE
Remove obsolete docs/iscsi-authentication.md

### PR DESCRIPTION
**Pull request by matthewei**
### What this PR does
Remove obsolete docs/iscsi-authentication.md

Fixes #

### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
This documentation is obsolete. If anything we should remove it.

**Comment by matthewei** [comment]
> This documentation is obsolete. If anything we should remove it.

okay, need me remove it?

**Comment by xpivarc** [comment]
> > This documentation is obsolete. If anything we should remove it.
> 
> okay, need me remove it?

More than happy if you do

**Comment by matthewei** [comment]
> > > This documentation is obsolete. If anything we should remove it.
> > 
> > 
> > okay, need me remove it?
> 
> More than happy if you do

done

**Review by brianmcarey — COMMENTED** [review]
/lgtm

The PR description just needs to be updated for the removal of the doc

**Comment by matthewei** [comment]
> /lgtm
> 
> The PR description just needs to be updated for the removal of the doc

OK

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by xpivarc** [comment]
I edited your PR description to match what is being done. Thank you for the PR

**Pull request merged**
