### PR TITLE
[Don't Merge] Add vendor to src tree

### PR DESCRIPTION
**Pull request by davidvossel**
Many go projects include the vendor directory in their source tree. This has a couple of benefits.

* More stable testing... Example, CI isn't going to fail when dependencies can't be pulled. 
* Faster builds and tests -  Automated builds don't have to reconstruct vendor file. 
* Guaranteed reproducible builds - There's no chance of a dependency getting mutated.

The downside is the vendor src tree is huge. 

If we decide to go with this change, we'll need to always remember to commit the vendor directory when glide.yaml is updated.

### CODE REVIEW

**Comment by davidvossel** [comment]
looking at files changed might break your browser.

**Comment by stu-gott** [comment]
I'd prefer it if we didn't adopt this change. Our vendor tree is *massive*... I'm concerned about permanently slowing down git operations if one of our dependencies doesn't have good git hygiene (e.g. binary blobs in source tree).

But I represent only one perspective. Maybe there are strong arguments how this is beneficial.

**Comment by davidvossel** [comment]
You're right. This does explode the size of our repo quite a bit and syncing KubeVirt will take longer if we take in this change.

**Comment by rmohr** [comment]
That patch causes a little bit of trouble on CI. Should start working again now.

**Comment by stu-gott** [comment]
retest this please

**Comment by rmohr** [comment]
@mpolednik which commands did you run to prune the vendor dependencies?

**Comment by mpolednik** [comment]
@rmohr 

`dep prune` prunes the tree, but normally that would leave all the objects in git.
`git filter-branch --tree-filter 'rm -rf vendor' --prune-empty HEAD` then removes the git objects. Is that what you mean?

**Comment by davidvossel** [comment]
i was able to prune around 5000 files by removing _test.go files from vendor

**Pull request merged**
