### PR TITLE
Set domain fixed values like name and UUID in the virt-handler

### LINKED ISSUE #124: Set fixed values like the emulator in virt-handler instead of virt-controller
Currently we set some Domain attributes like UUID, Name and Emulator in virt-controller.

They should actually be set in the domain manager in virt-handler and these fields should not even be part of v1.DomainSpec. Emulator is not important for the cluster wide view and UUID and Name are duplicates of the v1.VM metadata.

 - [ ] Remove these fields from v1.DomainSpec
 - [ ] Set fields in manager.SyncVM before starting or updating a VM

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Remove UUID and name attributes from the domain spec 
Resolve #124

### CODE REVIEW

**Comment by berrange** [comment]
This is conflicting & duplicating with work I've already done to refactor the Domain Spec XML handling.

**Comment by cynepco3hahue** [comment]
@berrange oh sorry I just saw the issue and wanted to resolve it, so do I need just close this one?

**Comment by berrange** [comment]
On closer look it is actually almost identical to what I've done so resolving conflicts should be pretty easy. I think there is something missing though - removing name / uuid from the public DomainSpec is good, but it is still present in the internal DomainSpec, because the data needs to be given to libvirt. So I would have expected virt-handler/virtwrap/manager.go SyncVM to be setting  Name + UUID on the internal DomainSpec

**Comment by rmohr** [comment]
Yes, looks like setting the UID is missing in manager.go. The name was already set in the `SyncVM` method before.

**Comment by rmohr** [comment]
Everything works as expected. Since @berrange gave his approval in general for this PR, merging.

**Pull request merged**
