### PR TITLE
Remove domain label from VMI metrics

### LINKED ISSUE #3477: Remove `domain` label from Metrics
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

We still expose the `domain` label in our metrics. This originates from our original metrics implementation where the more useful labels like `name` and `namespace` did not exist. We can remove it now.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by ArthurSens**
**What this PR does / why we need it**:
This PR removes domain labels from VMI metrics. They are being removed because they originate from the original metrics implementation where the more useful labels like `name` and `namespace` did not exist and now can be removed

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3477 

**Special notes for your reviewer**:

**Release note**:

```release-note
This change will possibly break dashboards that use the domain label to identify VMIs. 

action required
Use name and namespace labels instead
```

### CODE REVIEW

**Comment by dhiller** [comment]
@ArthurSens there is one test failing related to metrics in these lanes, maybe you need to adjust the functional test to your changes:

* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3500/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1267462309534502913
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3500/pull-kubevirt-e2e-k8s-1.16/1267485843925241856
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3500/pull-kubevirt-e2e-k8s-1.15-ceph/1267479429936844800

The other three lanes are failing due to unrelated problems we currently have when spinning up docker in docker tests.

**Comment by xpivarc** [comment]
@ArthurSens Can you squash commits? Anything else you want to do about this?

**Comment by ArthurSens** [comment]
After discussing with @fabiand and @danielBelenky, I think we might want to send a deprecation note about this label before applying this patch, I don't know if it is possible to merge without adding this patch to the next release though

I don't know the procedure for this case :grimacing:

**Comment by ArthurSens** [comment]
Oh god I just messed up my rebase real bad
I'll just open a new PR for this

**Pull request closed without merging**
