### PR TITLE
Add Cockpit Demo pod

### PR DESCRIPTION
**Pull request by fabiand**
These patches will add a cockpit pod which has the KubeVirt Machines page provider.

### CODE REVIEW

**Comment by fabiand** [comment]
please test this

**Comment by fabiand** [comment]
retest this please

**Comment by fabiand** [comment]
@rmohr what is the magic sentence to get jenkins to test it? :)

**Comment by rmohr** [comment]
@fabiand it is ok for me to have a pod which can deploy that copckpit version, but I would prefer to not have the code as part of core kubevirt ...

**Comment by fabiand** [comment]
Could you explain this a little?

**Comment by rmohr** [comment]
@fabiand because kubevirt does not need a UI (like kubernetes). If we do something like this, we will get bug reports, always have to keep it in sync, test it, ....

I really don't want to go into that direction. I would rather focus on having a good kubectl experience, especially since doing a good UI is complex and complicated ...

But I am ok to include a manifest in the kubevirt demo environment if it works reasonable (for fast overview or something like that). Until then providing a manifest in another repo would do it too ...

**Comment by fabiand** [comment]
Very well.

**Pull request closed without merging**
