### PR TITLE
podman: Use kubevirtci's KUBEVIRTCI_PODMAN_SOCKET

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
In order to make the code easier to maintain
and agnostic of custom socket path,
use `KUBEVIRTCI_PODMAN_SOCKET`.

See https://github.com/kubevirt/kubevirtci/pull/833
for more details.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
Not related to this PR

/test pull-kubevirtci-bump-kubevirt

**Comment by oshoval** [comment]
pull-kubevirt-unit-test failures not related

**Review by enp0s3 — APPROVED** [review]
/approve
Thank you @oshoval

**Comment by oshoval** [comment]
Thanks Felix and Igor

**Pull request merged**
