### PR TITLE
Fix 'make generate' to not keep unused client autogenerated files

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
Noticed this when making https://github.com/kubevirt/kubevirt/pull/7563,
I was getting rid of the v1beta1 client but had to rm it manually since it stuck around after make generate.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder-redhat** [comment]
Nice! Thanks @akalenyu!

**Comment by rmohr** [comment]
/hold

Let's discuss this for a moment. I explicitly never added a blanko `--delete` when copying out. I think this is not good for the experience, since it kind of removes files in a random-looking way in your folder. Could you limit this to specific auto-generated folders maybe?

**Comment by akalenyu** [comment]
> /hold
> 
> Let's discuss this for a moment. I explicitly never added a blanko `--delete` when copying out. I think this is not good for the experience, since it kind of removes files in a random-looking way in your folder. Could you limit this to specific auto-generated folders maybe?

I was under the impression that you'd only have changes made inside the container
& the copy that is present there (when the script finished) is exactly what you would want back on your host?

**Comment by rmohr** [comment]
/unhold

looks great now. Thanks!

**Pull request merged**
