### PR TITLE
Quarantine 2 sig-compute flaky tests

### PR DESCRIPTION
**Pull request by fgimenez**
Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

**What this PR does / why we need it**: quarantine flaky tests to improve suite stability.
* `[Serial][rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system][sig-compute] VM Live Migration Starting a VirtualMachineInstance  with a Fedora shared NFS PVC (using nfs ipv4 address), cloud init and service account should be migrated successfully, using guest agent on VM [test_id:5004] with postcopy`
  * Reported by flakefinder https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-05-16-168h.html#row0
  * Recent failures:
    * https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sig-compute/1394135611610238976
    * https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-cgroupsv2/1394080246579335168
    * https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-sig-compute/1394057588013797376
    * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5637/pull-kubevirt-e2e-k8s-1.19-sig-compute/1394131651264516096
    * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5580/pull-kubevirt-e2e-k8s-1.20-sig-compute/1394056541820162048
* `[sig-compute]HookSidecars [rfe_id:2667][crit:medium][vendor:cnv-qe@redhat.com][level:component] VMI definition [Serial]with sidecar feature gate disabled [test_id:2666]should not start with hook sidecar annotation`
  * Reported by flakefinder https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-05-16-168h.html#row5
  * Recent errros:
    * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-sig-compute/1393574551383707648
    * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sig-compute/1392927628029071360
    * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5652/pull-kubevirt-e2e-k8s-1.19-sig-compute/1394168093344796672
    * https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5637/pull-kubevirt-e2e-k8s-1.20-sig-compute/1393829404286652416   

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder-redhat** [comment]
Hey @fgimenez ,

Regarding `test_id:5004` - please see the quick discussion on the test in [this PR](https://github.com/kubevirt/kubevirt/pull/5495), you might find it useful.

Regarding `test_id:2666` - please bear in mind that sidecar tests are about to be removed from tier1 as sidecar feature gate it not supported anymore.

**Comment by iholder-redhat** [comment]
> Hey @fgimenez ,
> 
> Regarding `test_id:5004` - please see the quick discussion on the test in [this PR](https://github.com/kubevirt/kubevirt/pull/5495), you might find it useful.
> 
> Regarding `test_id:2666` - please bear in mind that sidecar tests are about to be removed from tier1 as sidecar feature gate it not supported anymore.
> 
> /lgtm

@fgimenez Also in [this PR](https://github.com/kubevirt/kubevirt/pull/5495) notice that `[test_id:4747]` fails on the same issue. Could `4747` and `5004` be related?

**Comment by fgimenez** [comment]
/test pull-kubevirt-build-arm64
/test pull-kubevirt-client-python

quay timeouts

**Comment by dankenigsberg** [comment]
> Regarding test_id:2666 - please bear in mind that sidecar tests are about to be removed from tier1 as sidecar feature gate it not supported anymore.

@iholder-redhat kubevirt hyperconverged operator does not expose the sidecar feature as it has security downsides. Red Hat customers, for example, do not want it. However, on the KubeVirt level, I was not aware of plans to deprecate this feature and its tests. I suspect do not want to drop tests while keeping the production code. Please make sure that you discuss feature deprecation in a wide forum.

**Comment by iholder-redhat** [comment]
> > Regarding test_id:2666 - please bear in mind that sidecar tests are about to be removed from tier1 as sidecar feature gate it not supported anymore.
> 
> @iholder-redhat kubevirt hyperconverged operator does not expose the sidecar feature as it has security downsides. Red Hat customers, for example, do not want it. However, on the KubeVirt level, I was not aware of plans to deprecate this feature and its tests. I suspect do not want to drop tests while keeping the production code. Please make sure that you discuss feature deprecation in a wide forum.

Hey Dan,
Thanks for the clarification :)

I was talking to @stu-gott about this and he said that we can simply delete all of the code for the tests that relay on sidecar feature gate in upstream. That's what we both understood from the Slack thread in which wide range of people were talking about this. In today's quarantine meeting @phoracek and I talked about this and he thought there might be a misunderstanding here, therefore he sent a clarification message in the Slack thread to hear other people's opinion about this.

**Comment by fgimenez** [comment]
> @fgimenez Also in [this PR](https://github.com/kubevirt/kubevirt/pull/5495) notice that `[test_id:4747]` fails on the same issue. Could `4747` and `5004` be related?

@iholder-redhat hmm maybe not sure, in the recent failures linked above `test_id:5004` was failing alone:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sig-compute/1394135611610238976
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-cgroupsv2/1394080246579335168
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-sig-compute/1394057588013797376
https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5637/pull-kubevirt-e2e-k8s-1.19-sig-compute/1394131651264516096
https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5580/pull-kubevirt-e2e-k8s-1.20-sig-compute/1394056541820162048

**Pull request merged**
