### PR TITLE
api: Move the core API storage version to `v1` and deprecate `v1alpha3`

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

This change moves the storage version for all core API CRDs to v1. This does not impact existing objects that will continue to be stored using their original v1alpha3 version while being served as v1alpha3 or v1, as was the case previously.

Work will be required in the future to ensure all stored v1alpha3 objects are read and updated to v1 but for the time being this isn't required as part of this PR.

For more context please review the following k8s documentation:

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning

Additionally the following KubeVirt dev ML thread covers this topic:

https://groups.google.com/g/kubevirt-dev/c/bSayedthHmY

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

Interested in this PR? Then you will love https://github.com/kubevirt/kubevirt/pull/9575 !

**Release note**:

```release-note
* The `kubevirt.io/v1` `apiVersion` is now the default storage version for newly created objects
* The `kubevirt.io/v1alpha3` `apiVersion` is now deprecated and will be removed in a future release
```

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/approve

I know this is a draft... but this is exactly what I'd expect to see. If there are no issues hit during CI, i dont' see any reason why this can't be merged.

**Comment by 0xFelix** [comment]
/hold

Need to create the runbook for the alert first

**Comment by 0xFelix** [comment]
@sradco 

Moved https://github.com/kubevirt/kubevirt/pull/9724/commits/91a2b7a002c957995036e5543f2b92a674324e7b to separate PR https://github.com/kubevirt/kubevirt/pull/9724

**Pull request merged**
