### PR TITLE
WIP chore: Introduce sig-compute

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/cc @0xFelix 
/cc @xpivarc 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
/cc @dhiller 
Can you please have a look as well?

**Comment by lyarwood** [comment]
> /hold
> 
> The idea of sigs is to not define them on a feature level, but rather on a crossfunctional level.

`sig-network`, `sig-storage` and `sig-live-migration` all exist and counter that suggestion.

> if we start to do feature drive sigs, where do we end? And we actualy loose the focus of sigs: maintain and improve shared knowledge. HOW good controlelrs are written, HOW good APIs look, etc. With feature driven sigs, the focus is on the feature, then I worry that the shared info (which we want to maintain) to rot anyhow.

I understand but think the two can co-exist (once `sig-api` and `sig-controllers` are actually populated) as the current proposal would already with the wider list of approvers and reviewers.

**Comment by fabiand** [comment]
Quick note, I just noticed that during all the SIG iterations, we did not introduce `sig-compute` and `sig-storage` even tho they are used in i.e. the tests.

Can we change this pr to rather introduce the "missing" sigs in this tpo level owner_alias file:
```
tests $ git grep -oe "sig-[a-z-]\+" | cut -d ":" -f2 | sort -u

sig-compute
sig-compute-migrations # too fine grained, don't add
sig-compute-realtime # too fine grained, don't add
sig-monitoring
sig-network
sig-network-approvers
sig-network-reviewers
sig-operator
sig-performance
sig-scale-approvers
sig-scale-reviewers
sig-something  # bogus, don't add
sig-storage
sig-test-approvers
sig-test-reviewers
```

**Comment by lyarwood** [comment]
> Quick note, I just noticed that during all the SIG iterations, we did not introduce `sig-compute` and `sig-storage` even tho they are used in i.e. the tests.
> 
> Can we change this pr to rather introduce the "missing" sigs in this tpo level owner_alias file:
> 
> ```
> tests $ git grep -oe "sig-[a-z-]\+" | cut -d ":" -f2 | sort -u
> 
> sig-compute
> sig-compute-migrations # too fine grained, don't add
> sig-compute-realtime # too fine grained, don't add
> sig-monitoring
> sig-network
> sig-network-approvers
> sig-network-reviewers
> sig-operator
> sig-performance
> sig-scale-approvers
> sig-scale-reviewers
> sig-something  # bogus, don't add
> sig-storage
> sig-test-approvers
> sig-test-reviewers
> ```

Okay I've switched the PR over to introducing the missing `sig-compute` and seeding that group with myself and @0xFelix with an eye on looking after the core instance type code.

After talking thigs over with @fabiand on slack I'm also going to organise a call in a few weeks to discuss the logistics around these SIGs, namely to agree on the final list of SIGs, define a process for adding/removing SIGs and a process for adding/removing individuals from SIGs.

**Comment by lyarwood** [comment]
> Okay I've switched the PR over to introducing the missing `sig-compute` and seeding that group with myself and @0xFelix with an eye on looking after the core instance type code.
> 
> After talking things over with @fabiand on slack I'm also going to organise a call in a few weeks to discuss the logistics around these SIGs, namely to agree on the final list of SIGs, define a process for adding/removing SIGs and a process for adding/removing individuals from SIGs.

FWIW My ML post, call invite (03/08/23 @ 13:00 BST) and notes can be found below:

- https://groups.google.com/g/kubevirt-dev/c/OkaCbq8uKcI
- https://groups.google.com/g/kubevirt-dev/c/aSwIC-9P0d8
- https://docs.google.com/document/d/1yOtxWS2eIgA2VT71NbFaDEzGyVfmiDCwoRBHKow0K6c/edit

**Pull request closed without merging**
