### PR TITLE
Fix base branch reference for coveralls

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:
Use `PULL_BASE_REF` for referencing the base branch for coverage. Use `PULL_PULL_SHA` to override the git sha, as the one fetched from the presubmit is different due to branch rebasing. Use `PROW_JOB_ID` to reference the prow job this build result originates from. 

See [prow env var docs](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#job-environment-variables)) 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by stu-gott — COMMENTED** [review]
/approve

**Comment by dhiller** [comment]
@rmohr should be good now, PTAL. Thanks!

**Comment by rmohr** [comment]
/lgtm
It does still not look correct, but it should unblock a postsubmit. We can iterate on it in a follow-up PR.

**Comment by dhiller** [comment]
Now the unit tests ran into timeout (which is not typical according to the job history)

**Pull request merged**
