### PR TITLE
Update kubevirt_vmi_memory_used_bytes type

### PR DESCRIPTION
**Pull request by sradco**
Signed-off-by: Shirly Radco <sradco@redhat.com>

**What this PR does / why we need it**:
Update kubevirt_vmi_memory_used_bytes recording rule type to gauge.
It was set to counter by mistake. The recording rule is calculated based on gauge metrics.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sradco** [comment]
@enp0s3 @machadovilaca Please review. Thank you.

**Comment by enp0s3** [comment]
/hold
@sradco can you please submit the `make generate` changes?

**Comment by sradco** [comment]
> /hold @sradco can you please submit the `make generate` changes?

Yes, Done. Sorry for that.
/unhold

**Pull request merged**
