### PR TITLE
[release-0.56] tests, console: Prevent NewExpecter negative timeout scenario

### PR DESCRIPTION
**Pull request by orelmisan**
**What this PR does / why we need it**:
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/9497 and the proposed change in https://github.com/kubevirt/kubevirt/pull/9515.

Run `make generate` in order to update the year in the license comment of the generated files, in order to pass the `pull-kubevirt-generate` lane.

Cherry-picked the commit from PR https://github.com/kubevirt/kubevirt/pull/8987 in order to pass the `pull-kubevirt-e2e-windows2016 lane`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by AlonaKaplan** [comment]
Why did you have to run `make generate` for this backport?

**Comment by orelmisan** [comment]
> Why did you have to run `make generate` for this backport?

So the `pull-kubevirt-generate` lane will pass.

**Comment by orelmisan** [comment]
> > Why did you have to run `make generate` for this backport?
> 
> So the `pull-kubevirt-generate` lane will pass.

This lane fail every new year, because it runs `make generate` and then sees a git diff because the year in the license comment has been updated to the current year.

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/1563805cd946b0e7f02bb5968812e4c9d8be0d5c..90b435b3a2438880983f3756b97b61290fed80ca): Added the commit from PR #8987 in order to pass the `pull-kubevirt-e2e-windows2016` lane.

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
