### PR TITLE
controller: Use a nicer launcher pod name separator

### PR DESCRIPTION
**Pull request by fabiand**
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

### CODE REVIEW

**Comment by fabiand** [comment]
Maybe we can do this change now, as I think that we do not rely on the name of the container/pod anymore.

**Comment by davidvossel** [comment]
retest this please

**Comment by davidvossel** [comment]
> Maybe we can do this change now, as I think that we do not rely on the name of the container/pod anymore.

Do you remember what we relied on the pod's name for?  I've only ever seen the pod -> vm relationship maintained through labels.

**Comment by rmohr** [comment]
It was only of interest when we had to detect the pod on the node by parsing `docker ps`.

**Pull request merged**
