### PR TITLE
Explicitly test packages in case of error

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

We found out that `go test -cover` seems to swallow the error output (in this case it was 
`FAIL    kubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook/admitters [build failed]`
). In order to keep the output still helpful we test each package again in case of error to have at least a hint for the user what to do about this.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @rmohr @phoracek mind taking a look whether you find is helpful? Alternative ideas welcome :)

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
FYI @danielBelenky @jean-edouard

**Comment by rmohr** [comment]
@dhiller so far I always saw my failing tests. Did you locally run the tests also with `-v`? Otherwise the output is swallowed. I agree that the failing tests (especially if they don't compile) are hard to see in travis, but they should be there.

**Comment by dhiller** [comment]
> @dhiller so far I always saw my failing tests. Did you locally run the tests also with `-v`? Otherwise the output is swallowed. I agree that the failing tests (especially if they don't compile) are hard to see in travis, but they should be there.

Actually I just overlloked the error in the build log: https://travis-ci.org/github/kubevirt/kubevirt/jobs/669180603#L1623

So it's all there. I don't think it makes sense to change anything. Although I'd have this line more prominent. Do you know if there's a way to customize travis build log with error patterns or the like?

**Comment by rmohr** [comment]
I don't think so. We could probably do something like `tee` the output, store interesting patterns in an extra file and then `cat` the file after the test run.

**Pull request closed without merging**
