### PR TITLE
Run guestfs tests in parallel

### PR DESCRIPTION
**Pull request by alicefr**
Run guestfs tests in parallel.

Signed-off-by: Alice Frosi <afrosi@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
@alicefr could you maybe add to the PR description the reason why the tests can now run in parallel?
Or were they serial by mistake? Thanks!

**Comment by alicefr** [comment]
@jean-edouard mistake or old version, I think I was following the storage tests and they were serial at that time. There isn't a particular reason

**Pull request merged**
