### PR TITLE
[release-0.44] Fix issues in up metrics and alerts based on namespace labels

### PR DESCRIPTION
**Pull request by erkanerol**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2008166

Manual cherry-picks
- #6570
- #6588
- #6652

Signed-off-by: Erkan Erol <eerol@redhat.com>

```release-note
Fixes issues in up metrics and alerts based on namespace labels
```

### CODE REVIEW

**Comment by erkanerol** [comment]
@rmohr May I get approval for this PR?

**Comment by rmohr** [comment]
/lgtm
/approve
@erkanerol in general individual backports are preferred. Just FYI.

**Pull request merged**
