### PR TITLE
bump to latest kubevirtci

### PR DESCRIPTION
**Pull request by SchSeba**
This update is for a rebuild of the okd 4.1 provider

related to https://github.com/kubevirt/kubevirtci/pull/172

Signed-off-by: Sebastian Sch <sebassch@gmail.com>

**Release note**:

```release-note
NONE
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/2866)

### CODE REVIEW

**Comment by slintes** [comment]
let's also test the updated lane :)

/test pull-kubevirt-e2e-okd-4.1

**Comment by cynepco3hahue** [comment]
oh okd-4.1 succeeded and also has better runtime `Test started yesterday at 9:22 PM passed after 5h39m17s` interesting, maybe we really need to limit it to one job only.

**Pull request merged**
