### PR TITLE
OWENERS: Removing a couple of folks who are not active anymore

### PR DESCRIPTION
**Pull request by fabiand**
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

**What this PR does / why we need it**: Removing inactive folks from OWNERS

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabiand** [comment]
@xpivarc @AlonaKaplan @jean-edouard please review

**Comment by jean-edouard** [comment]
/retitle OWNERS: Removing a couple of folks who are not active anymore
/lgtm

**Pull request merged**
