### PR TITLE
fix:  hot unplug last one nic failed

### PR DESCRIPTION
**Pull request by watermelon-brother**
**What this PR does / why we need it**:
hot unplug last one nic will failed
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
It`s not work when  send request to remove last one nic hotplug.
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by watermelon-brother** [comment]
@maiqueb

**Review by maiqueb — COMMENTED** [review]
Could you add some unit tests for this ? 

An e2e test would also be required.
@EdDev / @ormergi as you've taken over this feature.

**Comment by EdDev** [comment]
Nice one.

/test pull-kubevirt-build 
/test pull-kubevirt-e2e-k8s-1.27-sig-network
/test pull-kubevirt-e2e-kind-1.27-sriov
/test pull-kubevirt-generate
/test pull-kubevirt-unit-test

**Comment by EdDev** [comment]
@watermelon-brother , one unit-test is failing and also an e2e test related.
I guess this is not that trivial.

**Comment by ormergi** [comment]
@watermelon-brother Thanks for the contribution :slightly_smiling_face: 
Please add reasoning for this change including the problem description to the PR description and commit message body.

**Comment by maiqueb** [comment]
Just wanted to say that conceptually, the change looks correct. 

Try to address the unit test scenario first. 

Let us know if you need help with the failing tests / adding more (tests).

**Comment by watermelon-brother** [comment]
@0xFelix @xpivarc

**Comment by maiqueb** [comment]
Do you need help adding the required e2e / unit tests ? @watermelon-brother

**Comment by EdDev** [comment]
> Do you need help adding the required e2e / unit tests ? @watermelon-brother

@maiqueb , I have checked this myself.
It is hard to add unit and e2e tests to this area.

I will send a refactoring to the code to allow proper unit tests.
Regarding the e2e tests, there is a change in the working which should reveal this bug in an easy manner.

When the refactoring change will be ready, I will test it with this fix and update here.

**Comment by EdDev** [comment]
> I don't understand how adding an e2e test for this could be difficult. Don't we test unplug for an interface ?... This would be testing that with a VM having only a single interface IIUC.

The unplug on the VM is happening as expected, the only part that is buggy is that the CNI annotation on the pod is not happening.

**Comment by maiqueb** [comment]
> > I don't understand how adding an e2e test for this could be difficult. Don't we test unplug for an interface ?... This would be testing that with a VM having only a single interface IIUC.
> 
> The unplug on the VM is happening as expected, the only part that is buggy is that the CNI annotation on the pod is not happening.

Thus you can just check the associated pod network status annotation, right ?

**Comment by EdDev** [comment]
> Thus you can just check the associated pod network status annotation, right ?

We strive not to test implementation details, just the API.
As work is in done in this area, where this information is exposed through the API, we better wait for it to do a proper validation.

Ref: https://github.com/kubevirt/kubevirt/pull/10063

**Comment by xpivarc** [comment]
@EdDev How do we move this forward?

**Comment by EdDev** [comment]
After confirming this is still relevant, I prepared a change: https://github.com/kubevirt/kubevirt/pull/10756

**Comment by EdDev** [comment]
The issue has been resolved through an alternative PR.

I recommend closing this PR. In the meantime I’m putting it back on the previous lifecycle state.

/lifecycle rotten

**Pull request closed without merging**
