### PR TITLE
Fix sync of generated client-go to master

### PR DESCRIPTION
**Pull request by phoracek**
Signed-off-by: Petr Horacek <phoracek@redhat.com>

**What this PR does / why we need it**:

In the current state, we never update the master branch of
kubevirt/client-go repository. Even we try to push there with `git push
origin master`, the push is never applied and exits with:

+git push origin master
Everything up-to-date

The reason for that is, that our chenges are checked out on branch
"master-local" while the aforemenetioned command tries to push from the
checked out master branch.

With this change, we explicitly push from the currently checked-out
branch to master.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
It might be clearer if it said:

    git push origin ${TARGET_BRANCH}-local:master

But it seems to make sense! thanks for the patch.

**Comment by maya-r** [comment]
perhaps this works:
/lgtm

**Comment by phoracek** [comment]
Thanks @maya-r. I don't mind changing it if you find it clearer. What about `${TARGET_BRANCH}-local:${TARGET_BRANCH}`? My only worry with `"master"` is that it would be the only place where we call it by the "real" name and not the variable.

**Comment by maya-r** [comment]
sure, whichever works, even the original :-)

**Comment by phoracek** [comment]
All right, tell me what you think

**Review by rmohr — APPROVED** [review]
/lgtm
/approve

Nice catch and long overdue that we fix that. :+1:

**Pull request merged**
