### PR TITLE
Update metrics.md file

### PR DESCRIPTION
**Pull request by sradco**
Signed-off-by: Shirly Radco <sradco@redhat.com>

**What this PR does / why we need it**:
We have a bug with the  doc-generator that corrupted the metrics.md.
This patch updates the file structure to be more readable.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
The bug in doc-generator will be fixed in a separate PR.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sradco** [comment]
@davidvossel @rmohr  Hi, I dont believe the tests failed due to a relevant issue in the pr. What should I do?

**Comment by sradco** [comment]
@ashleyschuett @vatsalparekh @davidvossel Please review my patch. I believe it passed CI.

**Comment by rmohr** [comment]
@sradco normally we fix the generator instead of doing manually changes. Is it so difficult to fix it?

**Review by davidvossel — COMMENTED** [review]
/approve

Practically, without generation logic I can't cross reference every metric documented in this file with what exists in the code.  I can tell there are definitely parts of the previous .md file that were inaccurate though.

The long term sustainable solution here is we have to fix doc generator. That said, we're in a better spot with your manual updates than we were previously, so as a stop gap to improving/fixing doc-generator I don't see a reason to not take this in.

I'll let someone else provide the final lgtm

**Comment by sradco** [comment]
> @sradco normally we fix the generator instead of doing manually changes. Is it so difficult to fix it?

@rmohr I will fix the doc-generator in a separate pr, since this needs to go to the next release and currently file is corrupted.
The fix is according the the existing doc-generator logic and doesn't cause a conflict.

**Comment by sradco** [comment]
@rmohr I created this issue for fixing the doc-generator logic https://github.com/kubevirt/kubevirt/issues/5834

**Comment by nunnatsa** [comment]
> /approve
> 
> Practically, without generation logic I can't cross reference every metric documented in this file with what exists in the code. I can tell there are definitely parts of the previous .md file that were inaccurate though.
> 
> The long term sustainable solution here is we have to fix doc generator. That said, we're in a better spot with your manual updates than we were previously, so as a stop gap to improving/fixing doc-generator I don't see a reason to not take this in.
> 
> I'll let someone else provide the final lgtm

Please see a fix in the doc-generator, here: #6115

**Pull request merged**
