### PR TITLE
Replace dead "stress" binary with new, maintained, "stress-ng" binary

### PR DESCRIPTION
**Pull request by iholder-redhat**
**What this PR does / why we need it**:
The PR addresses [this issue](https://github.com/kubevirt/kubevirt/issues/6061).

**Release note**:

```release-note
replace dead "stress" binary with new, maintained, "stress-ng" binary
```

### CODE REVIEW

**Comment by ormergi** [comment]
Hey @iholder-redhat I suggest that to run migration test few more times to make sure they are not flaky

**Comment by iholder-redhat** [comment]
> Hey @iholder-redhat I suggest that to run migration test few more times to make sure they are not flaky

Great idea! thanks!

Passed: 1
Failed: 0
/test pull-kubevirt-e2e-k8s-1.19-sig-compute pull-kubevirt-e2e-k8s-1.20-sig-compute pull-kubevirt-e2e-k8s-1.21-sig-compute

**Comment by iholder-redhat** [comment]
Passed: 0
Failed: 1
/test pull-kubevirt-check-tests-for-flakes

**Comment by iholder-redhat** [comment]
Passed: 2
Failed: 0
/test pull-kubevirt-e2e-k8s-1.19-sig-compute pull-kubevirt-e2e-k8s-1.20-sig-compute pull-kubevirt-e2e-k8s-1.21-sig-compute

**Comment by iholder-redhat** [comment]
**sig compute:**
Passed: 2
Failed: 0
/test pull-kubevirt-e2e-k8s-1.19-sig-compute pull-kubevirt-e2e-k8s-1.20-sig-compute pull-kubevirt-e2e-k8s-1.21-sig-compute

**test-for-flakes:**
It seems like nothing fails but the lane exceeds its timeout. Let's try again.
/pull-kubevirt-check-tests-for-flakes

**Comment by iholder-redhat** [comment]
I thing we're confident on sig-compute lanes (all 3 of them passed 4 times in a row), but `pull-kubevirt-check-tests-for-flakes` keeps failing.

It looks like no actual test is failing but that the timeout have exceeded:
```
{"component":"entrypoint","file":"prow/entrypoint/run.go:255","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 5m0s grace period","severity":"error","time":"2021-07-19T00:09:14Z"}
```

@fgimenez do you think it has something to do with my PR or it's maybe effected by something else?

could it be that since the old `stress` binary was crashing and now it actually runs we hit the timeout?

**Comment by iholder-redhat** [comment]
Trying one more time
/pull-kubevirt-check-tests-for-flakes

**Comment by iholder-redhat** [comment]
Trying one more time
/test pull-kubevirt-check-tests-for-flakes

**Comment by rmohr** [comment]
/approve

/hold 

feel free to unhold when confident that everything is fine.

**Comment by fgimenez** [comment]
> @fgimenez do you think it has something to do with my PR or it's maybe effected by something else?

doesn't look related to your PR, we have seen before `pull-kubevirt-check-tests-for-flakes` timing out when there are a bunch of lengthy tests to be executed :+1:

**Comment by iholder-redhat** [comment]
> > @fgimenez do you think it has something to do with my PR or it's maybe effected by something else?
> 
> doesn't look related to your PR, we have seen before `pull-kubevirt-check-tests-for-flakes` timing out when there are a bunch of lengthy tests to be executed

Thanks!
If that's the case I guess we can merge it.
/unhold

**Pull request merged**
