### PR TITLE
flake, quarantine: test_id:1672 hugepages-2Mi with guest memory set explicitly

### PR DESCRIPTION
**Pull request by dhiller**
### What this PR does
Before this PR:

According to [quarantine docs](https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md#putting-tests-in-quarantine) tests may be put in quarantine if they have a 20%+ impact.

The above test has 26% impact over the last 2 days, thus we quarantine it. 
We also see an overall degradation of merges from the queue for that reason.

https://search.ci.kubevirt.io/?search=hugepages-2Mi+with+guest+memory+set+explicitly&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

After this PR:
Test is quarantined, so it will not block merges with it's high failure rate.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer
/cc @brianmcarey @EdDev 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
Do we do release notes?

**Review by EdDev — APPROVED** [review]

**Comment by brianmcarey** [comment]
> > Do we do release notes?
> 
> What do you mean? This is not a user-facing change.

+1 - Probably better to have Release note : `NONE`

**Comment by dhiller** [comment]
I see that failure rate does not seem to have improved:
* yesterday's failures on merged PRs have been 14 alone - https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2024-04-26.html#%5bsig-compute%5dConfigurations%20VirtualMachineInstance%20definition%20%5brfe_id%3a140%5d%5bcrit%3amedium%5d%5bvendor%3acnv-qe%40redhat.com%5d%5blevel%3acomponent%5dwith%20hugepages%20should%20consume%20hugepages%20%5bSerial%5d%5btest_id%3a1672%5dhugepages-2Mi%20with%20guest%20memory%20set%20explicitly
* impact is still 26%: https://search.ci.kubevirt.io/?search=hugepages-2Mi+with+guest+memory+set+explicitly&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

@xpivarc what is the status of your investigation? If you need more time on this, let's take the quarantine in, so you will be able to work on this without having to rush?

**Pull request merged**
