### PR TITLE
Duplicate kubelet restart test in sig-compute

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
This ensures we catch something like https://github.com/kubevirt/kubevirt/pull/9616#issuecomment-1566168918 in the sig-compute lane,
with a test that isn't likely to get skipped (i.e. unsupported bridge binding on some platforms)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by vasiliy-ul — APPROVED** [review]

**Comment by ormergi** [comment]
The issue we saw related to virt-launcher pods request for kvm/tun devices, and not network resources.

I suggest removing this test from sig-network altogether because we do not rely on Kubevirt's device plugins for bridge binding.
@EdDev @AlonaKaplan @maiqueb WDYT?

**Comment by EdDev** [comment]
> The issue we currently have is related to the fact that virt-launcher pods consume kvm/tun devices provided by Kubevirt decide plugins and not network resources.

I do not understand this statement.
Kubevirt device plugin allows the network part to create the tap device.
> 
> I suggest removing this test from sig-network altogether because we do not rely on Kubevirt's device plugins for bridge binding. @EdDev @AlonaKaplan @maiqueb WDYT?

I think we do rely on the tun device to create tap devices.

**Comment by xpivarc** [comment]
Let's make sure we DO NOT remove this test. Duplicating might be too much and a comment explaining the importance of this test might be lightweight and as such effective.

**Comment by akalenyu** [comment]
> Let's make sure we DO NOT remove this test. Duplicating might be too much and a comment explaining the importance of this test might be lightweight and as such effective.

I think the reasoning for this PR was that this test has very specific requirements
that would make it get skipped on non-kubevirtci environments

The idea is to have a less requiring version of this test in the compute lane that
should not have a problem to run on other platforms

**Comment by xpivarc** [comment]
/approve
@akalenyu Thank you for reminding me!

**Pull request merged**
