### PR TITLE
[release-1.0] infra: Bump Go to 1.19.12

### LINKED ISSUE #10213: go 1.18.8 throwing High and Critical CVEs
**What happened**:

What happened:
Container scans reveal high and critical CVEs with current golang version of go go-1.18.8

What you expected to happen:

Update go to the newest version which to mitigate the vulnerabilities.

How to reproduce it (as minimally and precisely as possible):
Running a security scan for CVEs against the containers

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.2
- Kubernetes version (use `kubectl version`): 1.26.1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:
Bump go 1.19.12

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10213

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
@brianmcarey , this is the bump for release-1.0.
If you can create an image for this one as well, I'll appreciate it. Thanks!

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by brianmcarey** [comment]
> @brianmcarey , this is the bump for release-1.0. If you can create an image for this one as well, I'll appreciate it. Thanks!

@EdDev here is the image built from release-1.0 with your changes: `quay.io/kubevirt/builder:2308030851-9ae62631c`

**Comment by EdDev** [comment]
> @EdDev here is the image built from release-1.0 with your changes: `quay.io/kubevirt/builder:2308030851-9ae62631c`

Thank you!
Updated.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Pull request merged**
