### PR TITLE
Nominate myself as a sig-compute approver

### PR DESCRIPTION
**Pull request by iholder101**
### What this PR does
Before this PR:
I a top-level approver, but not assigned to any SIGs.

After this PR:
I am assigned as a sig-compute approver.

### Why we need it and why it was done in this way
This is part of the process to refine SIGs and ownerships in Kubevirt.
Related to https://github.com/kubevirt/kubevirt/pull/11046 and https://github.com/kubevirt/kubevirt/pull/11355.
Also see below links for reference.

Links to places where the discussion took place: 
- https://groups.google.com/g/kubevirt-dev/c/-5TLpOcRkco
- https://groups.google.com/g/kubevirt-dev/c/dXvwU6Pon7Y

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- ~[ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required~
- [X] PR: The PR description is expressive enough and will help future contributors
- [ ] ~Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)~
- [ ] ~Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)]~(https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] ~Upgrade: Impact of this change on upgrade flows was considered and addressed if required~
- [ ] ~Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test~
- [ ] ~Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.~
- [X] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder101** [comment]
On draft until https://github.com/kubevirt/kubevirt/pull/11355 merges, which creates sig-compute (which doesn't exist currently).

**Comment by iholder101** [comment]
@dhiller FYI: IIUC we now have a list of file extensions that if are the only ones being modified the tests wouldn't run. I think that we can safely add OWNER_ALIASES and similar files to that list.

**Review by jean-edouard — COMMENTED** [review]
/approve

**Review by enp0s3 — APPROVED** [review]

**Pull request merged**
