### PR TITLE
Fix issues that virt-operator cannot extract MonitorNamespace and MonitorServiceAccount from JSON

### LINKED ISSUE #3086: Specify monitorNamespace not work
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

> /kind enhancement

**What happened**:
1. install kubevirt v0.26.0
2. install prometheus operator
3. update kubevirt object using following yaml
```
apiVersion: kubevirt.io/v1alpha3
kind: KubeVirt
metadata:
  name: kubevirt
spec:
  monitorNamespace: monitoring
  monitorAccount: prometheus-k8s
```
servicemonitor not created
**What you expected to happen**:
servicemonitor created under monitoring namespace
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
if i create namespace `openshift-monitoring`， servicemonitor will be created under namespace  `openshift-monitoring`，but what i want is servicemonitor created under namespace `monitoring`
**Environment**:
- KubeVirt version (use `virtctl version`):
v0.26.0
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by cchengleo**
**What this PR does / why we need it**:

virt-operator cannot extract `monitorNamespace` and `monitorAccount` when specifying using the following YAML:
```
apiVersion: kubevirt.io/v1alpha3
kind: KubeVirt
metadata:
  name: kubevirt
spec:
  monitorNamespace: monitoring
  monitorAccount: prometheus-k8s
```

When extracting values from a JSON map, the key name is expected to start with capitalized characters.

More details could be found at https://github.com/kubevirt/kubevirt/issues/3086#issuecomment-669601043

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3086

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix an issue which prevented virt-operator from installing monitoring resources in custom namespaces.
```

### CODE REVIEW

**Comment by rmohr** [comment]
@cchengleo very nice catch. Would you mind signing your commit to make our DCO bot(s) happy?

**Comment by cchengleo** [comment]
> @cchengleo very nice catch. Would you mind signing your commit to make our DCO bot(s) happy?

Hi @rmohr, thanks for the reminder. Just signed off DCO.

**Comment by rmohr** [comment]
@cchengleo what we see here is abnormal. As unlikely as it seems, really your change could be the reason.

**Comment by rmohr** [comment]
@cchengleo it seems like the job which dumps the install strategy is consistently failing. Check this file (collected by the job and accessible via the artifacts button): https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4029/pull-kubevirt-e2e-k8s-1.16/1299099510370209792/artifacts/0_pods.log. It shows that the `install-strategy-upload` container is failing.

**Comment by rmohr** [comment]
Since the jobs waits 7 hours, I deleted the jobs for now. Sorry for the inconvenience. I would suggest to locally do a `make cluster-up` and `make cluster-sync` and inspect  the cluster to see why it fails.

**Comment by cchengleo** [comment]
> Since the jobs waits 7 hours, I deleted the jobs for now. Sorry for the inconvenience. I would suggest to locally do a `make cluster-up` and `make cluster-sync` and inspect the cluster to see why it fails.

Thanks for the information. Let me inspect locally and see why the job fails. I guess maybe some test scripts need to be changed.

**Comment by cchengleo** [comment]
@rmohr I have fixed the issue and made the pipeline happy. The bug comes when getting the default monitor namespace when no additional property was assign.

**Comment by ashleyschuett** [comment]
Can we add some tests to make sure we don't accidentally break this?

**Comment by cchengleo** [comment]
@ashleyschuett This is a small fix. As long as the `cluster-up` and `cluster-sync` could bootstrap the cluster, I think we get covered.

**Comment by cchengleo** [comment]
> Can we add some tests to make sure we don't accidentally break this?

Good idea, I have added the unit-test for covering this.

**Pull request merged**
