### PR TITLE
Prometheus verbosity

### PR DESCRIPTION
**Pull request by fromanirh**
**What this PR does / why we need it**:
Reduce promethues messages, which arent' very informative unless we are troubleshooting issues,
and in that case we want more verbose log anyway.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes: https://github.com/kubevirt/kubevirt/issues/2729

**Special notes for your reviewer**:
N/A

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
@fromanirh I guess it is not intentional that the verbosity commit is on top of the ballooning commits.

**Comment by fromanirh** [comment]
> @fromanirh I guess it is not intentional that the verbosity commit is on top of the ballooning commits.

definitely :) Fixing

**Pull request merged**
