### PR TITLE
Extract control fns

### PR DESCRIPTION
**Pull request by admiyo**

### CODE REVIEW

**Comment by admiyo** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by admiyo** [comment]
retest this please

**Comment by admiyo** [comment]
Realized I missed job.go, too

**Comment by admiyo** [comment]
retest this please

**Comment by admiyo** [comment]
retest this please

**Comment by admiyo** [comment]
retest this please

**Comment by rmohr** [comment]
@admiyo also have a look at #157 , that should stabilize one test you saw failing repeatedly here ...

**Pull request merged**
