### PR TITLE
Use latest kubevirtci version

### PR DESCRIPTION
**Pull request by danielBelenky**
Signed-off-by: Daniel Belenky <dbelenky@redhat.com>

**What this PR does / why we need it**:
The latest kubevirtci version includes support for local
provisioner for ODK provider.

### CODE REVIEW

**Comment by slintes** [comment]
@danielBelenky you need to run `make generate` for actually pulling in the ci changes :)

**Comment by booxter** [comment]
@danielBelenky please add `release-note` section to the PR description to remove the warning label.

**Comment by danielBelenky** [comment]
> @danielBelenky please add `release-note` section to the PR description to remove the warning label.

Added `release-note-none` label. Thanks!

**Comment by danielBelenky** [comment]
Resolved in: https://github.com/kubevirt/kubevirt/pull/2781

**Pull request closed without merging**
