### PR TITLE
[Bug-fix]: Clean target migration orphan pods

### PR DESCRIPTION
**Pull request by iholder-redhat**
**What this PR does / why we need it**:
### Background
This is a follow-up PR to https://github.com/kubevirt/kubevirt/pull/7599.
The above PR solved a major bug in which the migration is being stuck and cannot be cancelled if the target pod is unschedulable (look at the PR description for more info), but introduced a new, much less significant bug, that this PR aims to solve.

### Reproduction
The bug can occur on the following circumstance:
* A migration object is posted to the cluster
* Then, two things happen in parallel:
  * The target pod is being created (before handing off to virt-handler)
  * The migration gets cancelled and deleted
* The target migration pod (i.e. the "orphan" pod) waits for the source pod to start the migration. It will wait until the timeout exceeds. The default timeout is [5 minutes](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/watch/migration.go#L73).
* A new migration is being posted. This migration is blocked since ["there are already multiple pods running for vmi"](https://github.com/kubevirt/kubevirt/blob/v0.55.0/pkg/virt-controller/watch/migration.go#L783).
* When the target pod is killed because of timeout, the new migration will start.

### Urgency
This bug is not severe for multiple reasons; after the timeout exceeds the migration will succeed, a simple workaround exists (simply killing the target virt-launcher manually) and the fact that it's pretty rare to create and immediately cancel a migration. But, while not being severe, it still needs to be solved.

## Solution:
The solution is fairly simple.

During virt-controller's target pod creation logic, and before the check for multiple pods running for the vmi (which leads to a re-enqueue of the migration), the controller would try to clean orphan pods.

virt-controller already has all the information it needs - a migration informer, a pod informer, etc. All it needs to do is scan the target pods for the VMI and check if the migration object for the pod still exists. If it doesn't, the pod will be deleted and the error would not occur.

Obviously, unit and functional tests are also added to this PR.

-----

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1719190

**Release note**:

```release-note
[Bug-fix]: Clean target migration orphan pods
```

### CODE REVIEW

**Comment by iholder-redhat** [comment]
FYI @davidvossel @vladikr 
Since https://github.com/kubevirt/kubevirt/pull/7599 had merged this is now ready to review

**Review by davidvossel — COMMENTED** [review]
i don't think this bug happens anymore after your PR.

In your previous PR. the mechanism that causes the migration to cancel before the handler hand off is the pod deletion. After the handoff occurs we can't delete the pod.

There's no gap there. So either the pod will get deleted before handoff due to a cancelled migration, or the handler owns the pod and the migration controller should not touch it.

**Comment by iholder-redhat** [comment]
> i don't think this bug happens anymore after your PR #7599. That's part of the reason why i insisted on the pod deletion being the thing that cancels the migration before the handoff.
> 
> So, in your previous PR, the mechanism that causes the migration to cancel before the handler hand off is the pod deletion. After the handoff occurs we can't delete the pod.

Right, but you're assuming here that if a target pod exists the migration controller would know of that. Since we're counting on informers here, nothing is guaranteed. Or am I missing something?
 
> There's no gap there. So either the pod will get deleted before handoff due to a cancelled migration, or the handler owns the pod and the migration controller should not touch it.

I think that this scenario still can occur:
* vmim is being created
* target migration pod is created

Now, let's say that the vmim is being deleted very quickly and that virt-controller's `MigrationController` does not know yet that a target pod is created. IOW, its informers aren't synced yet. So this could happen:
* vmim is being cancelled
* virt-controller finalizes the migration (since to its knowledge, no target pod exists and no handoff occurred).
* vmim is finalized

Does that make sense?

**Comment by davidvossel** [comment]
> Right, but you're assuming here that if a target pod exists the migration controller would know of that. Since we're counting on informers here, nothing is guaranteed. Or am I missing something?

the expectation logic exists to guarantee us that the informer has caught up to the reconcile loop.

**Comment by iholder-redhat** [comment]
> > Right, but you're assuming here that if a target pod exists the migration controller would know of that. Since we're counting on informers here, nothing is guaranteed. Or am I missing something?
> 
> the expectation logic exists to guarantee us that the informer has caught up to the reconcile loop. That only works for creations and deletions though. In our case, this is a pod creation, so as long as we use an expectation, the pod's existence in the sync function should be accurate

What if we cancelled the migration before the target pod was created?
In this situation we don't have any expectations, right?

**Comment by davidvossel** [comment]
> What if we cancelled the migration before the target pod was created?
In this situation we don't have any expectations, right?

right. no expectations, and no orphaned pod either.

**Comment by iholder-redhat** [comment]
> > What if we cancelled the migration before the target pod was created?
> > In this situation we don't have any expectations, right?
> 
> right. no expectations, and no orphaned pod either.

Yup, you're right.
Sorry for the confusion and noise, and thanks for insisting on the current implementation :) it indeed made our logic a lot safer.

/close

**Pull request closed without merging**
