### PR TITLE
Adding Eddy as a sig-network approver

### PR DESCRIPTION
**Pull request by AlonaKaplan**
### What this PR does
Edward is a core developer in the kubevirt network team,  
he sent more than 250 PRs to kubevirt and reviewed more than 750.

He pays close attention to the broad picture, clean code, project conventions and CI limitations . His reviews are comprehensive.

He certainly deserves to be a network approver.

Before this PR:
Eddy wasn't sig-network approver.

After this PR:
Eddy is a sig-network approver.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

The following apply to the part of project for which one would be an approver in the [OWNERS_ALIASES](https://github.com/kubevirt/kubevirt/tree/main/OWNERS_ALIASES) file.

- [x] Reviewer of the project for at least 3 months
- [x] Primary reviewer for at least 10 substantial PRs to the project
- [x] Reviewed or merged at least 30 PRs to the project
- [x] Nominated by an approver
- [x] With no objections from other approvers
- [x] Done through PR to update the top-level OWNERS file

### Release note

```release-note

```

### CODE REVIEW

**Comment by AlonaKaplan** [comment]
/approve
/hold
@enp0s3 @phoracek please share your opinion.

**Comment by xpivarc** [comment]
Please follow https://github.com/kubevirt/community/blob/main/membership_checklist.md and https://github.com/kubevirt/community/blob/main/membership_policy.md#approver

**Comment by AlonaKaplan** [comment]
> Please follow https://github.com/kubevirt/community/blob/main/membership_checklist.md and https://github.com/kubevirt/community/blob/main/membership_policy.md#approver

Updated the PR message with the checklist.
Since I"m the only current approver of the sig I"m not sure what other approvers should approve this PR.

**Comment by enp0s3** [comment]
/lgtm
I don't see anything in the membership policy that can contradict with Eddy's [contributions](https://github.com/kubevirt/kubevirt/graphs/contributors)

**Comment by phoracek** [comment]
/lgtm

Well deserved and long overdue

**Comment by fabiand** [comment]
:rocket:

**Pull request merged**
