### PR TITLE
[release-0.59]  Ensure virt-export route has redirect policy

### PR DESCRIPTION
**Pull request by awels**
This is a manual cherry-pick of #12195

/assign awels

```release-note
Virt export route has an edge termination of redirect
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
/hold
wait for https://github.com/kubevirt/kubevirt/pull/12361
Feel free to unhold once the latter is merged

**Comment by awels** [comment]
/hold cancel
@alicefr @mhenriks further backport.

**Pull request merged**
