### PR TITLE
Add Ready into wider output of crds

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

From 
```
# ./cluster-up/kubectl.sh get vm -o wide
NAME        AGE   VOLUME   CREATED   
vm-cirros   6s

```
to 
```
# ./cluster-up/kubectl.sh get vm -o wide
NAME        AGE   VOLUME   CREATED   READY
vm-cirros   6s                        true           true

```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by jichenjc** [comment]
@maya-r can you help to review this ? Thanks

**Comment by maiqueb** [comment]
Wouldn't `running` be more desirable ? 

Do you happen to know the difference between `ready` & `running` ? 

And furthermore, we would need you to check this is correct by adapting the existent function test in https://github.com/kubevirt/kubevirt/blob/2ea4795d9a90d8bb6955656ccb04d89c83296a47/tests/kubectl_test.go#L114

**Comment by jichenjc** [comment]
> https://github.com/kubevirt/kubevirt/blob/2ea4795d9a90d8bb6955656ccb04d89c83296a47/tests/kubectl_test.go#L114

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5370/pull-kubevirt-e2e-k8s-1.18/1379692344797827072

[owner:@sig-compute]oc/kubectl integration [rfe_id:3423][vendor:cnv-qe@redhat.com][level:component]oc/kubectl get vm/vmi tests should verify set of wide columns for [test_id:3466]virtualmachineinstance

this passed

**Comment by maiqueb** [comment]
Recently #5528 was merged, which adds a status field to the `VirtualMachine` CRD.

Do we want to have that plus this `running` column ? Is that information redundant ?

**Pull request closed without merging**
