### PR TITLE
virt-controller, vm: Refactor dynamic interface handling

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

 Perform a single patch operation for an object instead of multiple
 patching (one per interface).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Nice thanks

**Comment by AlonaKaplan** [comment]
PR's https://github.com/kubevirt/kubevirt/pull/9896/ first commit - `virt-controller, hotplug iface: Patch VMI once` has exactly the same content.

**Comment by EdDev** [comment]
> PR's #9896 first commit - `virt-controller, hotplug iface: Patch VMI once` has exactly the same content.

There are two PR/s depending on this (also #9979).
You could wait for one of the others to get in which include the change or just let this in sooner.
I do not know when the others will be ready for merge.

**Comment by EdDev** [comment]
This has been merged as part of #9979 , closing.

**Pull request closed without merging**
