### PR TITLE
Reduce kubevirt-ci loads by removing redundant operations 

### PR DESCRIPTION
**Pull request by Barakmor1**
Doesn't make sense to run make manifests and make build-functests For postsubmit job that publish the api to seperated repo

/cc @rmohr 
/cc @dhiller 
/cc @enp0s3 
/cc @xpivarc 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Barakmor1** [comment]
/hold 
Maybe there is a reason, will wait for others to respond

**Comment by Barakmor1** [comment]
@brianmcarey

**Comment by xpivarc** [comment]
@dhiller @rmohr Any reason to keep this around?

**Comment by dhiller** [comment]
> @dhiller @rmohr Any reason to keep this around?

Two reasons:
1. no capacity to check whether it's really not required there. IIRC the script is used in more than one place
2. not a big issue, since it's a postsubmit

**Pull request closed without merging**
