### PR TITLE
Add ineffassign checks to nogo

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Integrate https://github.com/gordonklaus/ineffassign into our nogo test suite. Ineffassign finds ineffective (unused) assignments and does not report false positives. This makes it a perfect candidate to be always run and to enforce fixing everything which it reports.

**Why does the integration look so complicated?**

With our bazel-use we already use a lot of the [nogo](https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst) checkers. This PR adds the ineffassign check as a custom analyzer. This nogo framework has the advantage that it can analyze a huge amount of code extremely fast, since the AST tree is only created once and then fed into the analyzers in parallel (in parallel to other analyzers and in parallel to the actual build). As a final peace, only files which are changed are re-analyzed due to the normal dependency tree building of bazel. This allows running these checks always without much noticeable delay for developers which are building the source code.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

~Right now this PR uses a fork of https://github.com/gordonklaus/ineffassign which allows using it as a library. This can be undone once https://github.com/gordonklaus/ineffassign/pull/56 is merged.~

~Once https://github.com/kubevirt/kubevirt/pull/4905 is merged I will fix the remaining reports.~

We use upstream now, https://github.com/gordonklaus/ineffassign/pull/56  is merged.

Thanks @zhouhao3 for kicking this rolling with https://github.com/kubevirt/kubevirt/pull/4905 and https://github.com/kubevirt/kubevirt/pull/4812

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
@ezrasilvera @davidvossel FYI.

The builds will fail right now since I don't actually fix our ineffassign issues in the code yet.

**Comment by rmohr** [comment]
And there we go: builds  failing on the first ineffassign issue:

```
14:19:31: /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/sandbox/processwrapper-sandbox/1916/execroot/__main__/pkg/cloud-init/cloud-init.go:547:3: ineffectual assignment to files
```

**Review by fgimenez — APPROVED** [review]
/lgtm

Awesome!

**Pull request merged**
