### PR TITLE
Increase timeout values for expose tests further.

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

Increases the time out values for expose tests from 5 to 7 minutes, as [one of them has again run into a timeout](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2019-12-12-168h.html).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by petrkotas** [comment]
Hi @dhiller thanks for this, I am wandering, do we have a networking issue? Have these tests been always flaky on the sriov and networking tests?

I have seen tests time out due to network load on the test cluster. I am wandering whether the issue is back.

**Comment by dhiller** [comment]
> Hi @dhiller thanks for this, I am wandering, do we have a networking issue? Have these tests been always flaky on the sriov and networking tests?

The tests in `expose_test` I've been addressing have been flaky due to timeout issues only IMHO, given a good enough timeout they started to be green nearly all the time. I could reproduce the flakiness by setting the test system under load via `stress-ng`. For this special test the timeout value seemed not to be good enough in one test. So i gradually increased again to hopefully make it always green.

> 
> I have seen tests time out due to network load on the test cluster. I am wandering whether the issue is back.

Hmm, can't tell honestly. I'm not a network expert, so I couldn't debug such an issue easily. If you have some spare cycles you might take a quick glance. Also if you can recommend a network stress testing tool, I'm eager to learn.

**Comment by petrkotas** [comment]
Unfortunately I am not an network expert either. These types of errors were usually solved by @phoracek .

**Pull request merged**
