### PR TITLE
schema doc - new line

### PR DESCRIPTION
**Pull request by mfranczy**
**What this PR does / why we need it**:
Fixed schema doc.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
VM high performance - add cache options
```

### CODE REVIEW

**Comment by mfranczy** [comment]
@SchSeba, @vladikr I forgot to add "." in the doc section, could you take a look and approve if this ok?

**Comment by mfranczy** [comment]
@rmohr true, thanks. Done.

**Comment by rmohr** [comment]
@mfranczy could you squash the commits?

**Comment by mfranczy** [comment]
@rmohr done.

**Pull request merged**
