### PR TITLE
[release-0.55] Improve non-root path handling

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Manual cherry-pick of #8198 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Improve path handling for non-root virt-launcher workloads
```

### CODE REVIEW

**Comment by rmohr** [comment]
/close

wrong target branch. reopening.

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
