### PR TITLE
Update to current reviewers list

### PR DESCRIPTION
**Pull request by stu-gott**
**What this PR does / why we need it**:

Nominate @yuhaohaoyu for removal from the current reviewers list.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by stu-gott** [comment]
/cc @yuhaohaoyu

Hao, would you like to continue to be a reviewer?

**Comment by yuhaohaoyu** [comment]
> /cc @yuhaohaoyu
> 
> Hao, would you like to continue to be a reviewer?

@stu-gott Hi Stu, Please kindly remove me from the reviewer list. Thanks and Best Wishes.

**Comment by stu-gott** [comment]
Thanks @yuhaohaoyu! Good luck!

**Review by xpivarc — COMMENTED** [review]
/approve
Based on https://github.com/kubevirt/kubevirt/pull/8003#issuecomment-1168724812

Good luck and thank you for your contributions @yuhaohaoyu

**Review by dhiller — APPROVED** [review]
/approve

Good bye @yuhaohaoyu, all the best!

**Pull request merged**
