### PR TITLE
Add bump kubevirtci script

### PR DESCRIPTION
**Pull request by oshoval**
Script would update hack/config-default.sh,
and then its possible to run make generate in order to fetch
newest kubevirtci cluster-up folder

Signed-off-by: Or Shoval <oshoval@redhat.com>

```release-note
NONE
```

### CODE REVIEW

**Comment by alonSadan** [comment]
looks good to me

**Comment by oshoval** [comment]
@rmohr 
updated according request, thx

**Comment by oshoval** [comment]
> I suppose you forgot to run `make generate` and commit the changes afterwards somehow. Therefore the Travis build complains.
> 
> /lgtm cancel

tried make generate, it didnt change a thing locally
(its logical because i didnt touch any existing files, just added new one in this PR)
rebased, hope it would help somehow

**Comment by oshoval** [comment]
@dhiller 
travis passed, rebase fixed it, thanks

was great i think if we could bypass sometimes all those lanes, when the fix is something like adding new standalone fix / README and such ?

**Comment by dhiller** [comment]
> was great i think if we could bypass sometimes all those lanes, when the fix is something like adding new standalone fix / README and such ?

We can override the job results manually if needed with [`/override <test-lane>`](https://prow.k8s.io/command-help) AFAIR

Other than that the tests act as a safety net, so I wouldn't recommend it in general, just as you already mentioned only for small changes in README, docs etc.

**Comment by dhiller** [comment]
> > was great i think if we could bypass sometimes all those lanes, when the fix is something like adding new standalone fix / README and such ?
> 
> We can override the job results manually if needed with [`/override <test-lane>`](https://prow.k8s.io/command-help) AFAIR
> 
> Other than that the tests act as a safety net, so I wouldn't recommend it in general, just as you already mentioned only for small changes in README, docs etc.

We could also automate this by using `run_if_changed: <regex>` but I fear that the expression would be really unreadable. Haven't looked at it in detail, though.

**Comment by oshoval** [comment]
> > > was great i think if we could bypass sometimes all those lanes, when the fix is something like adding new standalone fix / README and such ?
> > 
> > 
> > We can override the job results manually if needed with [`/override <test-lane>`](https://prow.k8s.io/command-help) AFAIR
> > Other than that the tests act as a safety net, so I wouldn't recommend it in general, just as you already mentioned only for small changes in README, docs etc.
> 
> We could also automate this by using `run_if_changed: <regex>` but I fear that the expression would be really unreadable. Haven't looked at it in detail, though.

yep , maybe we just need a flag /override all, that even will be ran manually only just when  we feel right, (for example by one of the maintainers) ?

**Comment by oshoval** [comment]
for sure not connected, can we override please? or run retest ?

pull-kubevirt-e2e-k8s-1.16.2
---

Summarizing 1 Failure:

[Fail] Configurations [rfe_id:898][crit:medium][vendor:cnv-qe@redhat.com][level:component]New VirtualMachineInstance with all supported drives [It] [test_id:1020]should not create the VM with wrong PCI adress 
/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:1569

Ran 407 of 485 Specs in 11406.697 seconds
FAIL! -- 406 Passed | 1 Failed | 1 Pending | 77 Skipped
--- FAIL: TestTests (11406.72s)

**Pull request merged**
