### PR TITLE
Quarantine flaky tests

### PR DESCRIPTION
**Pull request by fgimenez**
Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

**What this PR does / why we need it**: `test_id:1540` and `test_id:1541` have started failing a lot since 2021-04-27 at ~13:00 CEST. These are a few recent failed builds:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5551/pull-kubevirt-e2e-k8s-1.20-sig-network/1387317121746210816
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5536/pull-kubevirt-e2e-k8s-1.20-sig-network/1387249325372870656
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5520/pull-kubevirt-e2e-k8s-1.20-sig-network/1387214162077159424
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5533/pull-kubevirt-e2e-k8s-1.19-sig-network/1387289666457178112
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5533/pull-kubevirt-e2e-k8s-1.19-sig-network/1387176344839786496
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5536/pull-kubevirt-e2e-k8s-1.19-sig-network/1387168793662328832

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by EdDev** [comment]
Work to solve it is done in https://github.com/kubevirt/kubevirt/pull/5554 .

@fgimenez , are you ok with waiting for that PR to be finalized? I hope in a few hours.

**Comment by fgimenez** [comment]
/hold

> @fgimenez , are you ok with waiting for that PR to be finalized? I hope in a few hours.

sure, sgtm

**Review by EdDev — APPROVED** [review]
Based on input from @AlonaKaplan , I agree we need to look into the issue in more depth.
I originally though it is due to the Guest Agent not reporting the information on time, but this is surely not what happens as the VM/s in the tests do not have the Guest Agent at all.

**Comment by AlonaKaplan** [comment]
@oshoval  Is there a chance the bug was introduces [here](https://github.com/kubevirt/kubevirt/pull/5428/commits/3e9ba98a98acc41134788bb1e85bfca9eeeea9e0#diff-5ff91cfce1a15b5c8b1de6a76129f6b6b6eb76ee77c67f74c8941ac3c940f038R294) . And if there is not guest agent we override the interfaces with an empty struct (this not always fails since we have a raise between the - resync and the update event sent by libvirt).

**Comment by oshoval** [comment]
> @oshoval Is there a chance the bug was introduces [here](https://github.com/kubevirt/kubevirt/pull/5428/commits/3e9ba98a98acc41134788bb1e85bfca9eeeea9e0#diff-5ff91cfce1a15b5c8b1de6a76129f6b6b6eb76ee77c67f74c8941ac3c940f038R294) . And if there is not guest agent we override the interfaces with an empty struct (this not always fails since we have a raise between the - resync and the update event sent by libvirt).

I saw this flake even before 5428 was merged,
and here it should merge between empty and the interfaces themself
https://github.com/kubevirt/kubevirt/pull/5428/commits/3e9ba98a98acc41134788bb1e85bfca9eeeea9e0#diff-98b8339212e612cd92ce33649e492336892a3ed649f368b181aad9aa2854138cR1373
wdyt ?

**Comment by phoracek** [comment]
/approve cancel

We identified the PR that caused this regression in production code and will revert it.

@fgimenez I believe we can close this.

**Pull request closed without merging**
