### PR TITLE
Update virtio-win image to 0.1.217-1

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

This updates the virtio-win image in the virtio-container-disk to version 0.1.217-1.

The current version 0.1.171 misses the `.exe` and `.msi` installers.

**Special notes for your reviewer**:

How to update the `storage.googleapis.com` mirror?

**Release note**:

```release-note
Update virtio-container-disk to virtio-win version 0.1.217-1
```

### CODE REVIEW

**Comment by maya-r** [comment]
/lgtm

> How to update the storage.googleapis.com mirror?

It's always https://storage.googleapis.com/builddeps/sha256-of-file, but CI is making sure to create it and I think it will also update the WORKSPACE if you omit it, so it's not a big deal if it's not added.

**Review by jean-edouard — COMMENTED** [review]
Thank you! This is necessary for Windows 11, as the current version will BSOD on signature issues.
/approve
/hold
Holding to leave time to re-add the googleapis mirror link, feel free to unhold when done.

**Comment by 0xFelix** [comment]
@maya-r I added the sha256 sum, just in case. While I'm at it I also updated to version 0.1.217-1, which was just released.

@jean-edouard Can you have a look again?

/unhold

**Pull request merged**
