### PR TITLE
fix, generate: remove YEAR from `boilerplate.go.txt` to avoid breaking `make generate` every year

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

Problem: the code generation (i.e. `deepcopy-gen`) regenerates the code using [`hack/boilerplate/boilerplate.go.txt`](https://github.com/kubevirt/kubevirt/blob/7e3aa9fff0226fea881fa4efc7906bad3cfcf4be/hack/boilerplate/boilerplate.go.txt#L2) as a blueprint for the copyright header.

This file has a placeholder `YEAR` that is replaced by code generation with the current year.

At the beginning of every new year this breaks all PRs, since after running `make generate` the target will fail by complaining that the generated code differs, since the YEAR has changed.

This PR removes the `YEAR` placeholder from the template to fix the problem from now on.

References:
* ["The general rule is that the year to include in a copyright notice is the year of first publication of the work."](https://www.copyrightlaws.com/copyright-symbol-notice-year/#:~:text=The%20general%20rule%20is%20that,posting%20content%20on%20your%20blog.)
* year fixes
  * [2023](https://github.com/kubevirt/kubevirt/pull/9005)
  * [2022](https://github.com/iholder101/kubevirt/commit/f5c709695bb86732def95cd83e4165f877b9a3b0)
  * [2021](https://github.com/iholder101/kubevirt/commit/0738efc9851ff31214409c2c9919ed28d5f4dce6)
  * [2020](https://github.com/iholder101/kubevirt/commit/f5a2fe985f3a566c58644e2f5a79fb1492cb2b55)
* [Linux Foundation article about copyright notices in OS projects](https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects) for reference.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @enp0s3 

Thanks for bringing this up!

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
Remove year from generated code copyright
```

### CODE REVIEW

**Comment by dhiller** [comment]
/override pull-kubevirt-e2e-kind-1.27-vgpu

Unrelated, overriding lane.

**Comment by acardace** [comment]
Is the year required for the copyright header? I've always seen it included.

**Comment by dhiller** [comment]
> Is the year required for the copyright header? I've always seen it included.

I would turn the question around: can something be right that is breaking a lot of builds every year?

**Comment by dhiller** [comment]
Please also see [the Linux Foundation recommendation](https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects) for reference.

**Comment by dhiller** [comment]
@acardace updated the PR description, hope it makes it more clear now.

**Comment by acardace** [comment]
/approve
Also thank you @dhiller for addressing my question :)

**Review by orelmisan — APPROVED** [review]
Thank you @dhiller

**Comment by dhiller** [comment]
Flakes, flakes everywhere :confused:

/retest-required

**Pull request merged**
