### PR TITLE
test: move RuntimeClass functions from utils

### PR DESCRIPTION
**Pull request by codingben**
Move CreateRuntimeClass and DeleteRuntimeClass
functions from utils to vmi_configuration_test to
make utils shorter.

Signed-off-by: Ben Oukhanov <boukhanov@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by maya-r — CHANGES_REQUESTED** [review]
I think you can resolve the test failure with `make bazel-generate` and committing the changes to tests/BUILD.bazel

**Comment by codingben** [comment]
@maya-r Done, thank you!

**Comment by xpivarc** [comment]
Hi @codingben 
I noticed there are multiple PRs with the same intention behind(moving functions from utils). I think the preferred way of contributing these changes would be to have it as a series of commits rather than a series of PRs. 

Thank you for your contribution.

**Comment by codingben** [comment]
@xpivarc I agree with you, the question is what others think about it? @maya-r @EdDev @dankenigsberg WDYT?

**Pull request closed without merging**
