### PR TITLE
Fix make vagrant-deploy after namespace change

### PR DESCRIPTION
**Pull request by davidvossel**
virt-handler wasn't getting cleaned up correctly after the NS change.

I also removed TPR cleanup now. We're pretty far beyond that at this point.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Pull request merged**
