### PR TITLE
Update go-grcp dependency to fix flaky tests. 

### LINKED ISSUE #3610: [Flaky test][test_id:3145]should update kubevirt from previous release to target tested release
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Operator [rfe_id:2291][crit:high][vendor:cnv-qe@redhat.com][level:component]should update kubevirt [test_id:3145]from previous release to target tested release 

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3588/pull-kubevirt-e2e-k8s-1.18/1273368964344320000

### PR DESCRIPTION
**Pull request by davidvossel**
**What this PR does / why we need it**:

The VMI pod was having connections refused after control plane updates, which resulted in a longer than expected shutdown time. After updating the grpc dependency, this issue appeared to go away locally. I was able to do around 20 iterations of the test without failure, were it previously failed after around 3-4 iterations. 

below is what the grpc connection failure would look like. It resulted in virt-handler not receiving the final domain notify from virt-launcher during shutdown. Even with this error, the VMI still eventuallly shuts down as expected, but it's because our watchdog times out and not because we detected it through the normal expected flow.

```
{"component":"virt-launcher","level":"error","msg":"Could not send domain notify event.","pos":"client.go:267","reason":"rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /var/run/kubevirt/domain-notify-pipe.sock: connect: connection refused\"","timestamp":"2020-06-26T16:01:39.089711Z"}
```

```release-note
Update go-grpc dependency to v1.30.0 in order to improve stability
```

### CODE REVIEW

**Comment by davidvossel** [comment]
oops, i forgot to include some vendored files. The pr has been updated

**Comment by davidvossel** [comment]
/hold

the issue showed up in the v1.18 test lane

**Comment by davidvossel** [comment]
/hold cancel

This is caused by a transient connection error. I'm attempting to further mitigate this through introducing notify client retry logic during connect. I don't fully understand the root cause so it's unclear whether this will help or not. I'm having difficulty reproducing this locally as well after the grpc update, yet our CI encountered it again for 1.18.

It's very strange that this mostly occurs on 1.18/1.17 clusters and not 1.16 clusters, because the k8s version has nothing to do with the logic in question. Perhaps we're simply more likely to hit whatever race condition is going on with those later versions.

**Comment by davidvossel** [comment]
@rmohr in order to unblock PRs, I increased the timeout time which should at least let the test pass. The VMI will eventually shutdown, but it will be as a result of us detecting it's down because of the watchdog, and not the normal flow.

I'm not 100% sure what the issue is here, it's very difficult to reproduce this locally. My best guess is that the `transient` error the client reports is something that will hopefully resolve after retrying to connect. I put in logic in virt-launcher to re-attempt connecting to the notify socket in the event that an error is encountered during the dial which may help. I'm unsure though.

The issue is, I can't prove whether the retry connect logic helps or not because it's actually the old version of kubevirt and virt-launcher that the VMI is started with during the update test, so any change I make won't have an impact until the next release.

I want to unblock CI, so I increased the timeout and left a note in a comment about why the timeout is so long.

**Comment by rmohr** [comment]
/hold

Oh, forgot that the WORKSPACE file needs an update.

**Comment by rmohr** [comment]
/override continuous-integration/travis-ci/pr

Travis is passing bit the update on the pr failed

**Comment by rmohr** [comment]
@davidvossel would you mind preparing a cherry-pick for that PR?

**Pull request merged**
