### PR TITLE
Rename OfflineVirtualMachine to StatefulVirtualMachine (take 2)

### PR DESCRIPTION
**Pull request by mlsorensen**
This supercedes #1010 

This addresses #985 and is just a starting off point that passes my initial testing. I'm sure there are other pieces I'm not aware of that will need to be adjusted as well.  I see at the very least we need to adjust kubevirt/demo.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by rmohr** [comment]
@mlsorensen you can also simply "rebase" instead of merging changes in your branch. Also in case you  messed up your branch, simply fix it and the force push to your branch which you used for the PR. Maybe that helps you.

**Comment by fabiand** [comment]
Marcus, sorry for this little push back.

To give it a bit more context: In general there seems to be the agreement
to change the name.
Just with such a change the general question arose if the names and roles
are a good fit, or if this broader setup (aka relationship and "roels" of
and between OVM and VM) should be kept. Or if there are different nuances
to it.

Due to PTOs, holidays etc this got a little delayed, but I hope that we
find a conclusion soon.

Let's see that we pick up this topic on the ml this week and find an end.

After all - Thanks for your work, and it is welcome - it just triggered
another reflex :)

**Comment by mlsorensen** [comment]
Oh it's fine, it's a big change and it makes sense that the community should discuss. It's just a change that will conflict quite a bit until it's applied so I'd like to hold off on fixing conflicts until I know it's something that will be applied.

**Comment by fabiand** [comment]
Thanks for the work, closing this in favor of #1102

**Pull request closed without merging**
