### PR TITLE
Add NonRoot feature gate

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
We are going to test NonRoot extensively from now on
and therefore there is no reason to call it
Experimental. Let's rename it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
Users can now enable the NonRoot feature gate instead of NonRootExperimental
```

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
IMO this warrants a release note. All in all, you're changing how to configure the cluster. Hence, I'm setting the hold on it.

Other than this, all good.

/hold

**Comment by rmohr** [comment]
/lgtm
/approve

> IMO this warrants a release note

Adding a release note sounds like a good idea.

**Comment by fossedihelm** [comment]
It is not necessary to address it in this PR, but maybe we can also remove this? https://github.com/kubevirt/kubevirt/blob/28a4fff2e6601dddc458e87b265dfe12e331e8b7/tools/manifest-templator/manifest-templator.go#L119
Thanks

**Comment by xpivarc** [comment]
@maiqueb @rmohr 
Thanks for the review. I would still wait for project-infra PRs to get merged.

@fossedihelm 
You are right! The ugly hack can be removed.

**Comment by maiqueb** [comment]
> @maiqueb @rmohr Thanks for the review. I would still wait for project-infra PRs to get merged.

Cool :) Feel free to remove the hold when those are in.

> 
> @fossedihelm You are right! The ugly hack can be removed.

**Comment by xpivarc** [comment]
/hold cancel
/retest
Relevant PRs are in. We are now covering everything important.

**Pull request merged**
