### PR TITLE
Fix SetDomainSpecStrWithHooks to handle mutating `OnDefineDomain` calls

### LINKED ISSUE #7690: Hotplug volumes incorrectly handles mutating `OnDefineDomain` callback
**What happened**:
When VMI is started together with hook-sidecar that implements `OnDefineDomain` and which changes the specification of the `Disk`, in particular `Source.File` the hotplug volumes implementation seems to incorrectly handle that case.

Here is VMI spec:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: vmi-name
spec:
  domain:
    devices:
      disks:
        - name: rootdisk
          disk:
            bus: virtio
      interfaces:
        - bridge: {}
          name: default
  networks:
    - name: default
      pod: {}
  volumes:
    - name: rootdisk
      persistentVolumeClaim:
        claimName: pvc-name
```

When this VMI is being handled by the `virt-launcher` for the first time it goes to https://github.com/kubevirt/kubevirt/blob/b25c30a9e2d9826e053f54c5bf5a7abe50caf3b1/pkg/virt-launcher/virtwrap/manager.go#L820 call. Then fails on https://github.com/kubevirt/kubevirt/blob/b25c30a9e2d9826e053f54c5bf5a7abe50caf3b1/pkg/virt-launcher/virtwrap/manager.go#L842 because the domain is not defined and finally gets to https://github.com/kubevirt/kubevirt/blob/b25c30a9e2d9826e053f54c5bf5a7abe50caf3b1/pkg/virt-launcher/virtwrap/manager.go#L851 which then calls `OnDefineDomain` callback for each sidecar. If then the sidecar changes the disk definition like so:
```
	bootDiskLocation = domainSpec.Devices.Disks[0].Source.File // Get default boot disk location.

	// Update boot disk name to be "tmp_disk.img" in domain xml
	dir := filepath.Dir(bootDiskLocation)
	bootDiskLocation = filepath.Join(dir, "tmp_disk.img")
	domainSpec.Devices.Disks[0].Source.File = bootDiskLocation
```
and sends the changed domain back then this piece of code https://github.com/kubevirt/kubevirt/blob/b25c30a9e2d9826e053f54c5bf5a7abe50caf3b1/pkg/virt-launcher/virtwrap/manager.go#L911-L945 seems to handle it incorrectly. It first detaches the disk (it was never attached in the first place) and then attaches it again. But since the name is the same attaching fails as the detaching may not finished yet. Following logs are present:
```
{"component":"virt-launcher","kind":"","level":"info","msg":"Detaching disk rootdisk, target vda","name":"vmi-januszm-wfl8p-0","namespace":"default","pos":"manager.go:948","timestamp":"2022-04-29T15:14:36.662766Z","uid":"6898cd9d-54e6-43d1-b70c-355fe7dbfd1c"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Attaching disk rootdisk, target vda","name":"vmi-januszm-wfl8p-0","namespace":"default","pos":"manager.go:969","timestamp":"2022-04-29T15:14:41.749287Z","uid":"6898cd9d-54e6-43d1-b70c-355fe7dbfd1c"}
{"component":"virt-launcher","level":"error","msg":"unsupported configuration: non unique alias detected: ua-rootdisk","pos":"virDomainDeviceValidateAliasImpl:1294","subcomponent":"libvirt","thread":"31","timestamp":"2022-04-29T15:14:41.749000Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"attaching device","name":"vmi-januszm-wfl8p-0","namespace":"default","pos":"manager.go:977","reason":"virError(Code=67, Domain=20, Message='unsupported configuration: non unique alias detected: ua-rootdisk')","timestamp":"2022-04-29T15:14:41.749680Z","uid":"6898cd9d-54e6-43d1-b70c-355fe7dbfd1c"}
```

I think this particular case was missed and it hasn't been included in tests.

**What you expected to happen**: Hotplug should work without errors when `OnDefineDomain` callback changes the source file of the disk.

**How to reproduce it (as minimally and precisely as possible)**: Run aforementioned VMI with `OnDefineDomain` callback which mutates the `.Source.File`.

**Additional context**: None

**Environment**:
- KubeVirt version (use `virtctl version`): v0.50.0
- Kubernetes version (use `kubectl version`): v1.23.0
- VM or VMI specifications: Posted above
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by saiprashanth173**
Signed-off-by: Prashanth Dintyala <vdintyala@nvidia.com>

**What this PR does / why we need it**:

Currently, `SetDomainSpecStrWithHooks` does a DeepCopy of `wanted domain spec`, and uses it for calling hook-sidecars' `OnDefineDomain` implementation. The domain spec obtained from the `OnDefineDomain` contains the latest spec and is passed to the following `virConn.DomainDefineXML` call.  If the hook-sidecar mutates the domain spec, e.g., changing the specifications of `Disk` as described in  #7690, these changes are not reflected in the `wanted domain spec`. Any implementation uses the `dom` returned by `SetDomainSpecStrWithHooks` to get the `original domain spec` (through `dom.GetXMLDesc` call) and compares it with the stale `wanted domain spec` (like we do in https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-launcher/virtwrap/manager.go#L916-L960) would result in incorrect behavior.   

This PR mutates the `wanted domain spec` to ensure that it contains all the changes made by the hooks.      

   
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7690

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
Setting up a test with a VM that has hook in it might be hard, I would at a minimum write a unit test that overrides the hooks manager and have the hooks manager return a different domain and verify that that domain is the one returned instead of the original one. Code looks fine to me btw, just needs some tests.

**Comment by saiprashanth173** [comment]
@rthallisey @awels Thanks for your review. Sure, I can add a test for this.

@rthallisey  Do you have some pointers on how I can start a VM that mutates the disks?  I could find some examples for testing hooks here https://github.com/kubevirt/kubevirt/blob/main/tests/vmi_hook_sidecar_test.go, but it wasn't clear to me on how I can:
1. push a sidecar container image that mutates a disk
2. I see that the existing sidecar tests use a container disk, I wonder if I can reuse something existing to add a test that mutates a disk. 

@awels  based on how `SetDomainSpecStrWithHooks` is implemented, I am not sure if we can override the  hook manager here. Do you suggest I refactor the implementation a bit and pass a mock hook manager?  Please correct me if I missed something. 

```
func SetDomainSpecStrWithHooks(virConn cli.Connection, vmi *v1.VirtualMachineInstance, wantedSpec *api.DomainSpec) (cli.VirDomain, error) {
	hooksManager := hooks.GetManager() // <---- not sure how to replace this call

	domainSpec, err := hooksManager.OnDefineDomain(wantedSpec, vmi)
	if err != nil {
		return nil, err
	}
```

I have one idea in mind on how we can test this, I wanted to walk it by you before I start coding. In the hook manager's unit tests, I see that we start a few dummy hooks here: https://github.com/kubevirt/kubevirt/blob/main/pkg/hooks/manager_test.go#L63-L80. I plan to add a hotplug unit test, that starts a hook which mutates the domain spec and tests if the flow is working correctly. Tests might look something like this:

```
		It("should not attach/detach a disk if it is mutated by a hook sidecar", func() {
                        //  initialize vars etc. 
                        socket, err := startDomainMutatorHook(socketPath, socketName)
                        hookManager := hooks.GetManager()
                        err := hooks.Collect()
                        defer func() {
                            socket.Close()
                            os.Remove(socketPath)
                            hookManager.Collect(0) // cleanup hookManager.
                         }()
                        // verify if callback map has hook
                        // Run hotplug test with disk mutation
                        // verify if everything went through as expected
                        .... 
                }
```

Please let me know your thoughts.

**Comment by awels** [comment]
Looks like there is no Interface for the hooks manager yet, There are only 3 public functions, so it should be simple enough to make that an interface (which the Manager already implements). Then I would basically write something like this:
```go
var getHooksManager := func() *hooks.ManagerInterface {
  return hooks.GetManager()
}

func SetDomainSpecStrWithHooks(virConn cli.Connection, vmi *v1.VirtualMachineInstance, wantedSpec *api.DomainSpec) (cli.VirDomain, error) {
  hooksManager := getHooksManager()

  domainSpec, err := hooksManager.OnDefineDomain(wantedSpec, vmi)
  if err != nil {
    return nil, err
  }
```
And now in your unit test you can replace getHooksManager with your own function that returns a mock version of the interface. Maybe rename the current Manager struct something else and then name the Interface HookManager or something. The 3 current functions are `Collect`, `OnDefineDomain`, and `PreCloudInitIso`

**Comment by saiprashanth173** [comment]
@awels thanks for the suggestion. I added a unit test for `SetDomainSpecStrWithHooks`, do you mind reviewing it when you get a chance.

**Comment by VirrageS** [comment]
/assign @mhenriks

Could you take a look?

**Comment by mhenriks** [comment]
/approve

Thanks @saiprashanth173!

**Pull request merged**
