### PR TITLE
Bump go-yaml version to cover fixed ddos heuristic

### PR DESCRIPTION
**Pull request by petrkotas**
**What this PR does / why we need it**:

This PR bumbs go-yaml to v2.2.4, which has the ddos vulnerability fixed.

Issue:
go-yaml preceding 2.2.4 had vulnerability to ddos attack via billion laughs bomb.
Such attack lead to program to be unresponsive.
Issue has been described in
https://raesene.github.io/blog/2019/10/15/From-stackoverflow-to-CVE/

Moreover dependencies in our vendor have update in progress:

* ghodss/yaml - https://github.com/ghodss/yaml/pull/58
* &check; onsi/gomega - https://github.com/onsi/gomega/pull/362
* &check; gophercloud/gophercloud - https://github.com/gophercloud/gophercloud/pull/1751
* &check; go-openapi/runtime - https://github.com/go-openapi/runtime/pull/161
* &check; go-openapi/validate - https://github.com/go-openapi/validate/pull/118
* &check; go-openapi/spec - https://github.com/go-openapi/spec/pull/103
* &check; go-openapi/loads - https://github.com/go-openapi/loads/pull/25
* &check; go-openapi/swag - https://github.com/go-openapi/swag/pull/38

Signed-off-by: Petr Kotas <petr.kotas@gmail.com>

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
@petrkotas @slintes I wonder if we should also bump `staging/src/kubevirt.io/client-go/go.mod`, since that one is exported independently of the main `go.mod`.

**Comment by petrkotas** [comment]
Hi @rmohr we can do this separately, since it will require working on the dependencies. The yaml.v2 is used indirectly via dependencies and these have to be updated. WDYT?

**Comment by slintes** [comment]
> Hi @rmohr we can do this separately, since it will require working on the dependencies. The yaml.v2 is used indirectly via dependencies and these have to be updated.
> 
> Or we can try to go with `replace`, but I am not sure how well it will work.
> 
> WDYT?

I'd vote for replace in client-go. kubevirt itself is fine without it.
```
msluiter@slintes 🎩︎  ~/dev/work/kubevirt/kubevirt ‹pull/yaml›  ‹kubernetes-admin@kubernetes/default›
$ go list -m all | grep yaml.v2
go: finding kubevirt.io/client-go v0.0.0-00010101000000-000000000000
gopkg.in/yaml.v2 v2.2.4

msluiter@slintes 🎩︎  ~/dev/work/kubevirt/kubevirt/staging/src/kubevirt.io/client-go ‹pull/yaml›  ‹kubernetes-admin@kubernetes/default›
$ go list -m all | grep yaml.v2
gopkg.in/yaml.v2 v2.2.2
```

**Comment by petrkotas** [comment]
Hi @slintes I have provided the replace. However it seems it still keeps some older dependencies in the `go.sum`, I am guessing it will resolve with never version of the dependent libraries.

**Comment by slintes** [comment]
AFAIK go.sum is supposed to keep old entries.

But this looks good I'd say:
```
$ go list -m all | grep yaml.v2
gopkg.in/yaml.v2 v2.2.2 => gopkg.in/yaml.v2 v2.2.4
```

Thanks!

/lgtm

**Comment by petrkotas** [comment]
@slintes Thanks for the review, I have rebased the code.

**Pull request merged**
