### PR TITLE
Websocket virt api

### PR DESCRIPTION
**Pull request by rmohr**

### CODE REVIEW

**Comment by rmohr** [comment]
@admiyo @stu-gott  that one should be ready. You can check out #178, to also have a commandline tool if you want to test it yourself.

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
Rebased to let functional tests use the latest vagrant code

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by admiyo** [comment]
retest this please

**Comment by fabiand** [comment]
@rmohr got an idea why jenkins is failing?

**Comment by rmohr** [comment]
@fabiand not yet sure. Hope to start the stabilization task for jenkins. Most of the time we have timeouts in tests, since jenkins is very slow, or different failing checks if the cluster is finally ready.

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
@fabiand I verified them by running the test locally, but please don't merge until I switched the console test from alpine to cirros.

**Pull request merged**
