### PR TITLE
Move our CI to k8s-1.10.3

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Relevant PR from kubevirtci repo - https://github.com/kubevirt/kubevirtci/pull/14

Signed-off-by: Lukianov Artyom <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
retest this please

**Comment by cynepco3hahue** [comment]
vagrant-release has some strange error:
```
------------------------------
•! Panic in Spec Setup (BeforeEach) [0.031 seconds]
VMPreset
/root/go/src/kubevirt.io/kubevirt/tests/vmpreset_test.go:42
  Preset Matching [BeforeEach]
  /root/go/src/kubevirt.io/kubevirt/tests/vmpreset_test.go:135
    Should not be applied to existing VMs
    /root/go/src/kubevirt.io/kubevirt/tests/vmpreset_test.go:233

    Test Panicked
    unable to find api field in struct Unstructured for the json field "metadata"
    /gimme/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505

    Full Stack Trace
    	/gimme/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505 +0x229
    kubevirt.io/kubevirt/tests.PanicOnError(0x12dce00, 0xc4207e5440)
    	/root/go/src/kubevirt.io/kubevirt/tests/utils.go:730 +0x4a
    kubevirt.io/kubevirt/tests.cleanNamespaces()
    	/root/go/src/kubevirt.io/kubevirt/tests/utils.go:649 +0x71f
    kubevirt.io/kubevirt/tests.BeforeTestCleanup()
    	/root/go/src/kubevirt.io/kubevirt/tests/utils.go:311 +0x20
    kubevirt.io/kubevirt/tests_test.glob..func17.1()
    	/root/go/src/kubevirt.io/kubevirt/tests/vmpreset_test.go:62 +0xdb
    kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc4203347e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/root/go/src/kubevirt.io/kubevirt/tests/tests_suite_test.go:42 +0xaa
    testing.tRunner(0xc42023ef00, 0x12666b0)
    	/gimme/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:777 +0xd0
    created by testing.(*T).Run
    	/gimme/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:824 +0x2e0
```

**Comment by cynepco3hahue** [comment]
retest this please

**Comment by cynepco3hahue** [comment]
retest this please

**Comment by stu-gott** [comment]
Trying to sync my cluster to test this (`make cluster-sync`) and running into this issue with one of the images:

```
Sending build context to Docker daemon 3.072 kB                                                                                                                                                
Step 1/9 : FROM fedora:27                                                                                                            
 ---> 9110ae7f579f                                                                                                      
Step 2/9 : MAINTAINER "The KubeVirt Project" <kubevirt-dev@googlegroups.com>               
 ---> Using cache                                                                                                      
 ---> ea76a97e9da6                                                                                                                                                                             
Step 3/9 : ENV container docker                                                                                      
 ---> Using cache                                                                                                                                                                              
 ---> 5c44c3f9b759                                                                                                                                                            
Step 4/9 : RUN dnf -y install make git gcc && dnf -y clean all                                                                                                                                 
 ---> Using cache                                                                                                 
 ---> eecdecae7a9f                                                                                                                                                                             
Step 5/9 : ENV GIMME_GO_VERSION 1.9.2                                                                         
 ---> Using cache                                                                                                                                                                              
 ---> e622def18238                                                                                                          
Step 6/9 : RUN mkdir -p /gimme && curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | HOME=/gimme bash >> /etc/profile.d/gimme.sh                                        
 ---> Using cache                                                                                              
 ---> 62be11a89003                                                                                                                                                                             
Step 7/9 : ENV GOPATH "/go" GOBIN "/usr/bin"                                                                               
 ---> Using cache                                                                                                                                                                              
 ---> ff14da4e5efd                                                                                                             
Step 8/9 : RUN mkdir -p /go &&     source /etc/profile.d/gimme.sh &&     go get github.com/masterzen/winrm-cli                                                                                 
 ---> Using cache                                                                                                                    
 ---> b9f26fb03094                                                                                                                                                                             
Step 9/9 : LABEL "kubevirt" '' "winrmcli" ''                                                                                   
 ---> Using cache                                                                                                                                                                              
 ---> 04138daa94cf                                                                                                           
Successfully built 04138daa94cf                                                                                                                                                                
hack/build-docker.sh push                                                                                     
The push refers to a repository [docker.io/kubevirt/virt-controller]                                                                                                                           
47ac386dba14: Preparing                                                                                                                                                                        
8805a457dbe3: Preparing                                                     
39bae602f753: Preparing                          
denied: requested access to the resource is denied            
make[1]: *** [Makefile:47: publish] Error 1 
```

Is this trying to push to a public docker repo?

**Comment by stu-gott** [comment]
That's possible, but I never changed anything. `make cluster-sync` works on master

**Comment by cynepco3hahue** [comment]
retest this please

**Comment by cynepco3hahue** [comment]
OK to test

**Comment by cynepco3hahue** [comment]
retest this please

**Comment by cynepco3hahue** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
> and it pushes to the right repo.
> Does it possible that you override ${docker_prefix} variable from some local configuration file?

Maybe we override something in a strange way which does not affect ci runs?

**Comment by cynepco3hahue** [comment]
@stu-gott  Can you also check if you have `hack/config-provider-k8s-1.10.3.sh` and what configuration does it have?

**Comment by rmohr** [comment]
Nothing severe seems to be broken (except from the timeout in some lanes). Merging this, to let other PRs continue their test runs (better than not merging and producing more failed runs in other PRs). A follow-up PR can fix any remaining issues detected later.

**Pull request merged**
