### PR TITLE
Fixed multiple addition of PodScheduled condition on VMI

### LINKED ISSUE #2581: PodUnschedulable condition is added over and over instead of being replaced
**Is this a BUG REPORT or FEATURE REQUEST?**:

We add pod conditions to the VMI, to make it more obvious if things go wrong. This logic does not seem to work. Instead of replacing an existing condition, it just appends it over and over.

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

just create a VMI without a PVC: `kubectl.sh create -f  examples/vmi-windows.yaml`.

```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'failed to render launch manifest: didn''t find PVC disk-windows'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  - lastProbeTime: null
    lastTransitionTime: 2019-08-08T10:48:25Z
    message: 'failed to render launch manifest: didn''t find PVC disk-windows'
    reason: FailedPvcNotFound
    status: "False"
    type: Synchronized
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'failed to render launch manifest: didn''t find PVC disk-windows'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'failed to render launch manifest: didn''t find PVC disk-windows'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by slintes**
**What this PR does / why we need it**:
Fixed multiple addition of PodScheduled condition on VMI

**Which issue(s) this PR fixes**:
Fixes #2581 

**Special notes for your reviewer**:
For conditions.go I was on the wrong track, however having a test more doesn't hurt.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by slintes** [comment]
> This test is failing:
> 
> ```
> With not existing PVC [test_id:1040] should get unschedulable condition 
> ```

fixed

**Comment by rmohr** [comment]
@slintes, we will need another PR. This should just have called '`AddCondition`. If we explicitly replace, then the timestamp changes every time. This means watchers get notified which will then replace the condition again.

**Comment by slintes** [comment]
Mh, but the vmi is requeued anyway because of the error, so what difference does it make?
(Also, AddCondition only checks the condition type, no potentially changed value. I can improve that of course, just saying)

**Comment by rmohr** [comment]
> Mh, but the vmi is requeued anyway because of the error, so what difference does it make?
> (Also, AddCondition only checks the condition type, no potentially changed value. I can improve that of course, just saying)

I see now that we don't set the  timestamp (we probably should), so it may potentially not be replaced always again. Still, in theory we could get into situation where we permanently reorder conditions. 

That AddCondition only checks for the condition is a "pragmatic" solution in k8s in general, where we live in most cases with the chance that the error may be outdated, but we definitely avoid permanent fast changes, because of slightly changing error messages.

**Pull request merged**
