### PR TITLE
Follow general recommendation in setting go toolchain version

### PR DESCRIPTION
**Pull request by akalenyu**
### What this PR does
It is recommended to either specify the toolchain in it's own directive,
or omit the toolchain directive and specify it on the go version string.
Today, we have a bit of a mixture, which may or may not result in
unexpected builds when building kubevirt on different platforms (go 1.22.0 "command" and 1.22.2 toolchain).

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
Our `go` version is `1.22.2` which is matching the toolchain. I am ok with dropping the `toolchain` as I do not see a requirement for it and it future it could be easy to miss the mismatch.

**Comment by dominikholler** [comment]
Thanks for dropping the toolchain. What is the motivation to specify the z part of the go version?

**Comment by akalenyu** [comment]
> Thanks for dropping the toolchain. What is the motivation to specify the z part of the go version?

That's the general recommendation I am seeing, especially when it comes to building go projects on a downstream platform

**Comment by EdDev** [comment]
> > Thanks for dropping the toolchain. What is the motivation to specify the z part of the go version?
> 
> That's the general recommendation I am seeing, especially when it comes to building go projects on a downstream platform

Specifying the Z version requires constant update whenever we bump Go (in the same minor release) and is limiting the build of the project to that version (as a minimum).
Is there a way to declare that we want the latest version available for a specific minor release of Go, without fixing on the full specific one?

**Comment by akalenyu** [comment]
> > > Thanks for dropping the toolchain. What is the motivation to specify the z part of the go version?
> > 
> > 
> > That's the general recommendation I am seeing, especially when it comes to building go projects on a downstream platform
> 
> Specifying the Z version requires constant update whenever we bump Go (in the same minor release) and is limiting the build of the project to that version (as a minimum). Is there a way to declare that we want the latest version available for a specific minor release of Go, without fixing on the full specific one?

Doesn't seem like it. Note this is already a requirement today though https://github.com/kubevirt/kubevirt/pull/11470

**Comment by EdDev** [comment]
> > Specifying the Z version requires constant update whenever we bump Go (in the same minor release) and is limiting the build of the project to that version (as a minimum). Is there a way to declare that we want the latest version available for a specific minor release of Go, without fixing on the full specific one?
> 
> Doesn't seem like it. Note this is already a requirement today though #11470

That is the build system, limited to the build tooling used (e.g. bazel, dockerfiles).
Changing go.mod has implication on building kubevirt with different tooling (i.e. on D/S).

**Comment by akalenyu** [comment]
> > > Specifying the Z version requires constant update whenever we bump Go (in the same minor release) and is limiting the build of the project to that version (as a minimum). Is there a way to declare that we want the latest version available for a specific minor release of Go, without fixing on the full specific one?
> > 
> > 
> > Doesn't seem like it. Note this is already a requirement today though #11470
> 
> That is the build system, limited to the build tooling used (e.g. bazel, dockerfiles). Changing go.mod has implication on building kubevirt with different tooling (i.e. on D/S).

Correct, what the existing form of the go.mod gives you when building is a hybrid of the `go` directive version (old go command) with "correct" toolchain. This may not be what we're after

**Comment by dominikholler** [comment]
I do not understand why we are discussion about the tool chain to a z-version in the upstream source code at all. Isn't go 1.21 EOL in a view weeks, and downstream distributors have to care about this?

**Comment by akalenyu** [comment]
> I do not understand why we are discussion about the tool chain to a z-version in the upstream source code at all. Isn't go 1.21 EOL in a view weeks, and downstream distributors have to care about this?

Not sure I understand. Today we specify `go 1.22.0` which is arguably not the intention by whoever bumped the go version. The proposed way is just as legitimate

**Comment by dominikholler** [comment]
> Not sure I understand. Today we specify go 1.22.0 which is arguably not the intention by whoever bumped the go version. The proposed way is just as legitimate

ups, yes, this PR is referring to go 1.22. But this will be EOL in next February, so it delays the problem just by 6 month, but it does not change the problem. From my point of view, the build env should set the golang toolchain and z version which should be used, and the upstream source code should only specify which y version is required. This way the responsibility of selecting a  golang toolchain which contains all required fixes is on the build env, and the go.mod can express the developers expectation about the y-version of golang.

Is there a specific motivation, e.g. a bugfix, to enforce a minimal z-version of golang?

**Comment by akalenyu** [comment]
> and the upstream source code should only specify which y version is required

This is not the case today prior to this PR as well. The toolchain directive exists and can't be dropped since go mod vendor will put it back.
The problem is that today you'll be forcing a "wrong" go command for all build envs, possibly without them knowing
(This is something we witnessed, right?)

Regarding the totolchain, build envs can override that - https://go.dev/doc/toolchain
`The GOTOOLCHAIN environment setting can force a specific Go version, overriding the go and toolchain lines`

**Comment by dominikholler** [comment]
> This is not the case today prior to this PR as well. The toolchain directive exists and can't be dropped since go mod vendor will put it back.

From my point of view, this is a not helpful behavior of `go mod` . In downstream builds, the `toolchain` directive is overwritten. We should double check, but I hope the the `toolchain` directive does not hurt the downstream build.
But the `go` directive seems to be relevant.

**Comment by akalenyu** [comment]
/close
https://github.com/kubevirt/kubevirt/pull/12584

**Pull request closed without merging**
