### PR TITLE
Lift quarantine from 4621

### PR DESCRIPTION
**Pull request by brybacki**
Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

**What this PR does / why we need it**:

Removes quarantine label from test 4621. Issue https://github.com/kubevirt/kubevirt/issues/4527, was fixed by https://github.com/kubevirt/kubevirt/pull/5178. 

Did not see it happen since merging the fix.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brybacki** [comment]
just testing storage lane 
/test pull-kubevirt-e2e-k8s-1.19-sig-storage

**Review by fgimenez — APPROVED** [review]
/lgtm

**Pull request merged**
