### PR TITLE
Fix network test to make it 'restricted' PSA compliant

### PR DESCRIPTION
**Pull request by acardace**
**What this PR does / why we need it**:
This will enable us to make the network PSA lane gating. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by EdDev — APPROVED** [review]

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by acardace** [comment]
/hold
The whole PR was submitted to retest, my bad.

**Pull request merged**
