### PR TITLE
Add functional tests using NFS as backing store

### PR DESCRIPTION
**Pull request by stu-gott**
**What this PR does / why we need it**:
Tests existing functionality using NFS

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by stu-gott** [comment]
/hold
there are likely other tests we'll want to add

**Comment by vladikr** [comment]
@stu-gott did you have a chance to check the failures? I'm not sure if these are just flaky tests...

**Comment by vladikr** [comment]
/hold

There's clearly an issue here

**Comment by stu-gott** [comment]
@vladikr I think there was an interesting side effect to the re-factor of migration_tests.go. Because two functions in the test suite were both named "runVMIAndExpectLaunch", I conflated them--but they did subtly different things.

**Comment by stu-gott** [comment]
/hold cancel

Issue is resolved

**Comment by vladikr** [comment]
thanks!
/lgtm

**Pull request merged**
