### PR TITLE
Some unit tests appear to be more load sensitive than expected

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Reducing the amount of retests for now until the tests are improved.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve
/hold

Let's make sure that we create an issue where we collect the flakiness we discovered so far.

FYI @acardace

**Comment by dhiller** [comment]
/unhold

Issue #5313 created

**Comment by vasiliy-ul** [comment]
There are still tests that use real timeouts and they may fail randomly under load. Probably it was a bit too early to enable parallel runs...

**Comment by vasiliy-ul** [comment]
@rmohr , maybe we should consider reverting the commit completely for the time being? If it blocks PRs then probably some more work is needed before enabling it.

**Comment by rmohr** [comment]
Unit tests pass. Merging to improve the situation for other PRs.

**Pull request merged**
