### PR TITLE
cluster: Add a fedora template

### PR DESCRIPTION
**Pull request by fabiand**
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
We have already a lot of stuff under the cluster, maybe it time to create two directories `cluster/vms` and `cluster/templates`
Template lgtm :smile:

**Comment by fabiand** [comment]
Let me see if I can find some structure ...

**Comment by rmohr** [comment]
Let's stop adding all those templates at all. We have enough examples already. If they are meant to  be used by e.g. manageIQ, then they should be included there.

**Comment by fabiand** [comment]
Both existing templates are not working out of the box.

This newly introduced template does, because it's using a registry disk.

**Comment by stu-gott** [comment]
I agree that items not critical to running a KubeVirt cluster probably don't belong there.

Now that we have a user-guide repository, would it be worth considering moving any example templates/manifests there? A lot of the documents have examples inline, but it might be helpful to also have a dedicated directory.

**Comment by fabiand** [comment]
So, flame me. But I'll merge this template. I'll propose some changes to make the locations better.

**Pull request merged**
