### PR TITLE
virt-controller: use controller.NamespacedKey() instead of manual strings

### PR DESCRIPTION
**Pull request by jean-edouard**
### What this PR does
Before this PR:
Many calls to `GetByKey()` use manually built strings with `namespace + "/" + name`

After this PR:
Those calls now use `controller.NamespacedKey()` instead

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
Nice cleanup!

/lgtm

**Review by fossedihelm — COMMENTED** [review]
/approve

**Comment by lyarwood** [comment]
/hold

Apologies for the hold but wouldn't it be better to use [`NamespacedName`](https://pkg.go.dev/k8s.io/apimachinery@v0.31.0/pkg/types#NamespacedName) either in-line or at least in `NamespacedKey`?

**Comment by jean-edouard** [comment]
> /hold
> 
> Apologies for the hold but wouldn't it be better to use [`NamespacedName`](https://pkg.go.dev/k8s.io/apimachinery@v0.31.0/pkg/types#NamespacedName) either in-line or at least in `NamespacedKey`?

Nice, yeah. We have many key functions and they probably need a big cleanup (the per-object functions also don't make sense to me). Can that be a separate effort?

**Comment by lyarwood** [comment]
> > /hold
> > Apologies for the hold but wouldn't it be better to use [`NamespacedName`](https://pkg.go.dev/k8s.io/apimachinery@v0.31.0/pkg/types#NamespacedName) either in-line or at least in `NamespacedKey`?
> 
> Nice, yeah. We have many key functions and they probably need a big cleanup (the per-object functions also don't make sense to me). Can that be a separate effort?

Yeah happy to help, just wanted to raise this as an alternative but if everyone is happy with this for now then I'm not going to stand in the way.

/hold cancel

**Pull request merged**
