### PR TITLE
Avoid setting SELinuxOptions on virt-launcher when no type is specified

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
Setting SELinuxOptions to anything, including "{}", has implications.
It notably disables automatic relabelling of overlay2 mounts.
Avoid setting SELinuxOptions when no SELinux type is specified.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
@rmohr good call, the tests were already present but needed to be adjusted. Done.

**Comment by rmohr** [comment]
@jean-edouard would we have catched this on the selinux enabled 1.17 lane?

**Comment by jean-edouard** [comment]
@rmohr yes indeed!

**Comment by rmohr** [comment]
@jean-edouard can you run `make`? The code formatting seems to be wrong.

**Comment by jean-edouard** [comment]
@rmohr done

**Pull request merged**
