### PR TITLE
tests: Continue moving helpers that are node related to libnode.

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

As part of the effort to cleanup `tests/utils.go` and better structure the e2e tests, move more helpers to `libnode`.
The first commit also includes some import aliases fixes. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by dteplits — APPROVED** [review]

**Review by enp0s3 — APPROVED** [review]
/approve

**Pull request merged**
