### PR TITLE
Don't send watch error when ioerror occurs

### LINKED ISSUE #5859: Notify server can go to crash-looping and handler functionality will degrade
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
While simulating ioerrors I noticed we sent a [error watch event](https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-launcher/notify-client/client.go#L219) that is causing shut down of notify server. This server is serving all VMs on the node and is used to provide domains to our decisions in the sync. 

The ioerror seems to be reported more than once and this will quickly full our queue. This will cause another shut down after the server will restart and the launcher sent another error event from the queue.

I have a suspicion that this also effects life-cycle operations of the VMs.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5859

**Special notes for your reviewer**:
We might to this also with libvirt re-connections.

**Release note**:
```release-note
Fix: ioerrors don't cause crash-looping of notify server
```

### CODE REVIEW

**Comment by xpivarc** [comment]
`The cluster provider kind-1.19-sriov does not exist` weird

**Comment by xpivarc** [comment]
/cc @rmohr 
Can you have a look?

**Comment by rmohr** [comment]
> We might to this also with libvirt re-connections.

There we send it intentionally, because we have to know that we need to recheck, since we may have missed something. It is still risky, since it will restart the whole watcher, but at least we are using the intended mechanism for reporting in this case. Should be improved.

**Comment by rmohr** [comment]
> /cc @rmohr
> Can you have a look?

@xpivarc looks good. Since I can't find any resume tests, did you verify that resume worked after this change?

**Comment by xpivarc** [comment]
> > /cc @rmohr
> > Can you have a look?
> 
> @xpivarc looks good. Since I can't find any resume tests, did you verify that resume worked after this change?

I verified it manually and this [test](https://github.com/kubevirt/kubevirt/pull/5864) should cover this bug and resume at the same time.

**Comment by rmohr** [comment]
> I verified it manually and this [test](https://github.com/kubevirt/kubevirt/pull/5864) should cover this bug and resume at the same time.

Thanks. :+1: 

/lgtm
/approve

**Pull request merged**
