### PR TITLE
Run the migration finalizing code only when the migration is complete

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
Before this PR, `finalizeMigration()` gets called prematurely, causing the logs to show "migration finalized successfully" for ongoing migrations, that may eventually fail.
Since the source handles the migration, but the target needs to run the finalizers, this PR adds a VMI condition to inform the target of the completion of the migration.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by vladikr — COMMENTED** [review]
/approve
Thanks @jean-edouard !

**Review by acardace — APPROVED** [review]

**Comment by jean-edouard** [comment]
Added a fair amount of test code in last force-push.
@acardace PTAL
@iholder101 FYI

**Review by acardace — APPROVED** [review]

**Pull request merged**
