### PR TITLE
Fix duplicate strings in hotplug tests

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Fix identified code smells in sonar cloud.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brybacki** [comment]
/lgtm

Generally looks good. Introducing constants for some commands is good, for errors also good, but I do not like constants for the most of the "By" comments,

I know it is a "copy paste", but it was more readable before, and now you just repeat the long constant name instead of a long literal. It is now compile-time checked, but who cares for comment.

I think, that if there is is series of a few comments/messages with code repeated, we need to extract a common helper. If just a comment, I would personally leave it.

**Comment by awels** [comment]
/hold
We discussed this PR a bit, and decided it makes more sense to see if we can reduce code duplication a bit, which should also reduce the 'code smells' I will take a look at doing that later.

**Comment by awels** [comment]
/retest
Should be good to go for testing and reviewing at this point.

**Comment by brybacki** [comment]
/lgtm
Great, now its much better.

**Pull request merged**
