### PR TITLE
Add tests for trim reducing space usage on filesystem and block storage

### PR DESCRIPTION
**Pull request by maya-r**
Test flow:
Boot Fedora
Write large file
Write down space usage
Write small file
Delete large file, trim /

Write down space usage again

If preallocated, we expect no change in disk usage.
If trim is expected to work (default) we expect a decrease.
If trim isn't expected to work (thick provisioned) we expect an increase, due to the small file.

Both OCS and local storage are tested.

Depends on kubevirt#5578 to be merged first.

**What this PR does / why we need it**:
Testing actual end-to-end functionality.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
Draft until kubevirt#5578 is merged.

**Comment by alicefr** [comment]
Looks good :)

**Review by kgoldbla — CHANGES_REQUESTED** [review]
Looks ok. Please add the requirement CNV-5750 to the test:

**Comment by mhenriks** [comment]
@maya-r I think the toolbox should be baked into kubevirtci for `rook-ceph-default`

**Review by kgoldbla — COMMENTED** [review]
lgtm

**Comment by maya-r** [comment]
the goveralls failure seems to originate from kubevirt#5694, rather than from this PR.

**Comment by maya-r** [comment]
> @maya-r I think the toolbox should be baked into kubevirtci for `rook-ceph-default`

Done :)

**Pull request merged**
