### PR TITLE
[Release-0.44] Move host-disk to handler

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
This is backport of https://github.com/kubevirt/kubevirt/pull/6240

This moves the responsibility of creating disks to virt-handler. It is needed for rootless virt-launcher 

BZ #https://bugzilla.redhat.com/show_bug.cgi?id=2001984

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
This backport of https://github.com/kubevirt/kubevirt/pull/6240 also sneaks in most of https://github.com/kubevirt/kubevirt/pull/6233.
Could we maybe explicitly backport the commits from both PRs, to avoid future confusion?
Also, when cherry-picking, please use `-x` to keep a link to the original commits.

**Review by jean-edouard — COMMENTED** [review]
/approve

**Review by davidvossel — COMMENTED** [review]
/lgtm

**Pull request merged**
