### PR TITLE
design principle: The Razor

### PR DESCRIPTION
**Pull request by dankenigsberg**
I heard The Razor evoked several times during design discussions, but I don't seem to find
it mentioned in a formal setting.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
@fabiand @rmohr @booxter 
I think we should mention this principle explicitly and loudly.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dankenigsberg** [comment]
>  I guess it relates to "Occam’s Razor"? I like it :)

I believe it is, and to https://en.wikipedia.org/wiki/Philosophical_razor in general. It bothers me that I don't know who coined it in the KubeVirt context, though.

**Comment by dankenigsberg** [comment]
@fabiand is this acceptable?

**Comment by fabiand** [comment]
Thanks

**Comment by fabiand** [comment]
For reference: This is not new, we have been following this razor for along time. Thus Dan is just documenting reality.

**Pull request merged**
