### PR TITLE
Improve logging usage

### PR DESCRIPTION
**Pull request by mz-pdm**

### CODE REVIEW

**Comment by petrkotas** [comment]
I will copy the commit message from first commit here, since it got lost.

# Improve logging usage
The structured logger is good for producing comprehensive logs, however it is
not that good for being used directly in the code.  Let's introduce some
changes that:

- Make the code shorter, so it's easier to read.
- Make the logging lines shorter, so the logging messages can be read without
  horizontal scrolling.
- Reduce the chain of method calls so one can see easily also code other than
  logging in editors highlighting method calls.
- Reduce code duplication.

To not make logging too messy, methods for setting message levels are turned
into terminal methods.  Those methods are almost always used, so they can be
used as such rather than using extra Msg method call.  In rare cases when we
don't want to use typical logging patterns, new Level method can be used.

It would be nice to access logging methods from objects being logged.
However due to Go limitations we can't do that easily, so we have to use
something like `vm.Log().Info' rather than simply `vm.Info'.

**Comment by petrkotas** [comment]
I like this patch. The logging is now more readable and shorter to write.

**Comment by davidvossel** [comment]
retest this please

**Comment by mz-pdm** [comment]
David Vossel <notifications@github.com> writes:

> The only thing that caught my eye was the VM object's log function. I'm not sure that's a pattern we want to start using.
> I'd be okay with still having to specify Object() to avoid adding Log() functions for each cluster object we work with.

It's not necessary to add Log() to each cluster object, just to those
that are worth it (i.e. define once, use many times) – the rest can use
Object().  I don't know whether there are already some ideas about using
different loggers, but if we like to use separate loggers for some
objects then object Log() functions will help with that.  And Log()
implementation is trivial, so it's not a big deal.

Despite that I'm not particularly happy with it too, it lacks some
elegance.  But it's IMO still better to use o.Log() than let's say
logging.Object(o), for the reasons mentioned in the commit message.
Maybe somebody has a better idea?

> --------------------------------------------------------------------------------------------------------------------
>
> In pkg/logging/logging_test.go:
>
>> @@ -297,8 +323,8 @@ func TestObject(t *testing.T) {
>  	setUp()
>  	log := MakeLogger(MockLogger{})
>  	log.SetLogLevel(DEBUG)
> -	vm := v1.VirtualMachine{}
> -	log.Object(&vm).Log("test", "message")
> +	vm := newVM()
>
> why change this?

To avoid circular package references.

**Comment by davidvossel** [comment]
> Despite that I'm not particularly happy with it too, it lacks some
elegance.  But it's IMO still better to use o.Log() than let's say
logging.Object(o), for the reasons mentioned in the commit message.

I agree that it o.Log() looks nicer than logging.Object(o). I don't feel good about making our logging package a dependency for things like /pkg/api/v1 now though. That's what we have to do in order to get this functionality. It's also why you had to work around the circular dependency.

**Comment by rmohr** [comment]
I can understand the desire to make the logging lines a little bit shorter, however, I am also not very happy with the changes here. 

We are using a structured logger, and I like that with the builder we have clearly structured way on what logs what. E.g. the `.Object(vm)`, logs object information. If we later on also want to log the controller, we can simply do something like `.Controller(migration).Object(vm)`, or `.Object(vm).ManagedBy(migration)`. I also explicitly like the separation of `.Reason()` and `.Msg()`, because it also corresponds to what will be logged in which fields.

Some thoughts on how to make the lines a little bit shorter:

 * Having a the `logging.DefaultLogger()` is very long. Renaming logging to e.g. log and have a global Log variable which is set to logging. DefaultLogger().
 * Since V() only makes sense in combination with Info(), let's combine it

The outcome would be:

```golang
log.Log.Info().With("costm_key", "custom_val" ).Msg("whatever") # defaults to InfoV(1)
log.Log.InfoV(3).With("costm_key", "custom_val" ).Msg("whatever")
log.Log.Error().Reason(err).Msg("lala") # reason is not a must, but msg is.
```
It can be made even shorter by having a `log.Error()`, `log.Info()`, ... global method for the default logger in the log package.


If it is confusing for people, that `.Msg()` or `.Msgf()` are the the last ones executed, renaming it to `.Log()` or `.Logf()` would also be an option for me.

**Comment by mpolednik** [comment]
> Since V() only makes sense in combination with Info(), let's combine it

Please let's keep at least some consistency in the Go universe and keep V() a function.

As for the logging itself, if we really want structured logging (which I'm not fan of, not with the code burden that glog doesn't carry) AND a bit of consistency with kube*, I could imagine getting rid of message and making Info, Error, Warning etc. terminals in the builder. That would lead to logging lines such as

logging.DefaultLogger().Object(VM).Reason(Err).Error("VM isn't running")

The advantage of that is if you remove the structured part, you'll arrive to a point where the line looks similarly to other logging frameworks:

logging.DefaultLogger. ... .Error("VM isn't running")
\---------------------/
imagine this being *log

**Comment by rmohr** [comment]
> logging.DefaultLogger().Object(VM).Reason(Err).Error("VM isn't running")

+1

> As for the logging itself, if we really want structured logging (which I'm not fan of, not with the code burden that glog doesn't carry)

I really want to use structured logging.

**Comment by mz-pdm** [comment]
David Vossel <notifications@github.com> writes:

> I agree that it o.Log() looks nicer than logging.Object(o). I don't
> feel good about making our logging package a dependency for things
> like /pkg/api/v1 now though. That's what we have to do in order to get
> this functionality.

OK, I can omit that in the patch and we can look for better ways to
express it in future patches (again: suggestions welcome).

**Comment by rmohr** [comment]
> - Changing logging.DefaultLogger() to log.Log.

Works for me

> - Making Info(), Error(), etc. terminals.

Works for me

> - Nobody has protested against using additional arguments for formatted
  strings so I can think I can keep that too.

I would suggest `Error()` and `Errorf()` if that is what you mean.

**Comment by mz-pdm** [comment]
I believe I made all the agreed changes in the updated version of the patch.

**Comment by davidvossel** [comment]
It sounds like we're in agreement this should go in.

Since this touches so many files, we should merge this immediately once it is rebased.

**Comment by mz-pdm** [comment]
Rebased and updated.

**Comment by rmohr** [comment]
ok to test

**Pull request merged**
