### PR TITLE
Remove nft ruleset files

### PR DESCRIPTION
**Pull request by rhrazdil**
**What this PR does / why we need it**:
Instead of loading nftable rules from files, that are
built in the release, create the table and basechains
in the handler code.

With the nat table and base chains created in handler, these
files are not required anymore and are removed in the 2nd commit.

This simplifies build process of downstream projects, that don't use bazel
build system, and need to ensure existence of the nft files.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by AlonaKaplan** [comment]
Thanks @rhrazdil looks good. Please remove from draft.

**Review by EdDev — APPROVED** [review]
Thank you!

**Comment by EdDev** [comment]
@rhrazdil , I would not include a release-note here, because it is not a user facing change. Users are not suppose to notice this at all.

/retest

**Comment by rhrazdil** [comment]
@EdDev That's correct. I've removed the note, thanks!

**Pull request merged**
