### PR TITLE
Go 1.12.8 and more

### PR DESCRIPTION
**Pull request by slintes**
**What this PR does / why we need it**:
Several updates:

- Fedora 30 base image for builder image
- Go 1.12.8
- Go 1.12 branch for goimports
- K8s 1.13.4 versions of deepcopy-gen, defaulter-gen
- bazel 1.0.0
- newer bazel packages for dealing with newer Go version
- updated image shasum detection, because they are not logged during push anymore

**Special notes for your reviewer**:
Update: Thanks Roman for finding the cause (updated toolchain with cgo)
~~bazel build fails with this, and I have no clue yet why:~~

```
<resolved>
```

**Release note**:
```release-note
Update to Go 1.12.8
```

### CODE REVIEW

**Comment by rmohr** [comment]
/lgtm
/approve

@slintes anything missing from your point of view?

**Comment by slintes** [comment]
> @slintes anything missing from your point of view?

No, I have everything in here what I wanted to have in. When CI is happy, I'm happy as well :)

**Comment by slintes** [comment]
ah, while looking at another PR, I know what I wanted to do: how can I push some new dependencies to our mirror and update/add urls to the WORKSPACE?

**Comment by rmohr** [comment]
> ah, while looking at another PR, I know what I wanted to do: how can I push some new dependencies to our mirror and update/add urls to the WORKSPACE?

There is a binary in a WIP PR: https://github.com/kubevirt/project-infra/pull/226/files#diff-eed372f314cfbb704da887242297a5d6R1. It does the upload and updates the WORKSPACE file. I used it to fix the dependencies on the releases, but it can't be used right now from CI.

**Comment by slintes** [comment]
somehow I managed to break the operator tests with this

/hold

**Comment by slintes** [comment]
rebased because of merge conflict...

**Comment by slintes** [comment]
ups
/hold cancel
/retest

**Pull request merged**
