### PR TITLE
Move staging/src/kubevirt.io/client-go/api/utils.go to staging/src/ku…

### LINKED ISSUE #7272: Relocate the functions in staging/src/kubevirt.io/client-go/api/utils.go
This is a request for internal cleanup.

The  `staging/src/kubevirt.io/client-go/api/utils.go` only contains 2 util functions used for test only.

Our code base depends on the `kubevirt.io/kubevirt/tests` package. Also, we have a higher `kube-openapi` version. Now the `kube-openapi` version conflicts with the version that is used in Kubevirt. This is because the https://github.com/kubevirt/kubevirt/blob/main/tests/utils.go file imports the `kubevirt.io/client-go/api` only to use the util functions in https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/client-go/api/utils.go. 

Also, by looking at the util functions in https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/client-go/api/utils.go, I feel they are more aligned with the functions in https://github.com/kubevirt/kubevirt/blob/main/tests/utils.go.

I suggest to just move the functions from https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/client-go/api/utils.go to https://github.com/kubevirt/kubevirt/blob/main/tests/utils.go, so that depending on `kubevirt.io/kubevirt/tests` won't bring the `kube-openapi` dependency transitively.

I am happy to send a PR. Please let me know if there are any concerns.

### PR DESCRIPTION
**Pull request by zhuchenwang**
…bevirt.io/api/utils.go

Signed-off-by: Zhuchen Wang <zcwang@google.com>

**What this PR does / why we need it**: Decouple the test util code with openapi generated code to avoid the kube-openapi conflict by just using the test util code.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7272

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
Thanks for your PR. Let's see if everything works. One quick preliminary note: can you edit the description adding `NONE` in the `Release note` section? Thanks

/cc @xpivarc
Maybe you want to have a look
/ok-to-test

**Comment by fossedihelm** [comment]
@zhuchenwang please run `make` and `make generate` and commit changes. Thanks

**Comment by zhuchenwang** [comment]
I think I missed one file and the tests are failing. I just committed the fix and `make` and `make generate` are run.

**Comment by zhuchenwang** [comment]
@fossedihelm I did run `make generate`, but it doesn't change any files.

**Comment by fossedihelm** [comment]
@zhuchenwang Your `vendor/modules.txt` is not aligned with the expected one. 
Run `make deps-sync` and commit the changes :slightly_smiling_face:  Thanks

**Pull request closed without merging**
