### PR TITLE
Remove quarantine from test 5004

### PR DESCRIPTION
**Pull request by iholder-redhat**
**What this PR does / why we need it**:
As part of our [quarantine proceedure](https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md), this PR gets test 5004 out of qarantine after it was fixed in this PR: https://github.com/kubevirt/kubevirt/pull/6804

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder-redhat** [comment]
@fgimenez @xpivarc @vladikr FYI

Finally! :smile: :partying_face: :tada: :birthday: :balloon:

**Comment by fgimenez** [comment]
> @fgimenez @xpivarc @vladikr FYI
> 
> Finally! smile partying_face tada birthday balloon

/lgtm

awesome, great work!

**Comment by vladikr** [comment]
/approve

Great work :)

**Pull request merged**
