### PR TITLE
rpm: Minimize QEMU installation

### PR DESCRIPTION
**Pull request by andreabolognani**
**What this PR does / why we need it**:

In a similar vein to the recent minimization of libvirt, we want to install as little of QEMU as possible while still retaining the functionality we care about.

**Special notes for your reviewer**:

iSCSI support is the one thing I was not entirely sure about, because it looks like there are some references to it in KubeVirt; however, the test `[sig-storage] Storage Starting a VirtualMachineInstance [rfe_id:2288][crit:high][vendor:cnv-qe@redhat.com][level:component]With Alpine ISCSI PVC (using ISCSI IPv4 address) [test_id:3139]should be successfully started` still passed after my changes, so I *think* we should be good.

If it's confirmed that QEMU's iSCSI driver can go, I will try to prepare a follow-up PR that removes all references to it.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by andreabolognani** [comment]
I realized that SPICE support has been dropped from KubeVirt a while ago, and so one more QEMU component (along with its many dependencies) could be removed :)

**Comment by rmohr** [comment]
/retest

a quay connection issue.

**Comment by rmohr** [comment]
/lgtm

let's see if we get now results without quay issues.

**Comment by andreabolognani** [comment]
@rmohr can you please re-lgtm the changes?

**Comment by andreabolognani** [comment]
@rmohr As far as I can tell all of the CI failures so far have been caused by timeouts or hitting the pull rate limit on Docker Hub... Is there anything that I should do to help this move forward, or should I just sit back and wait patiently for the situation to sort itself out? Thanks :)

**Pull request merged**
