### PR TITLE
instancetype: Add testids to functional tests

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

Add testids to instancetype functional tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lyarwood** [comment]
/cc @akrejcir 
/cc @davidvossel 

Apologies for the delay with this, should be ready for review now.

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
