### PR TITLE
remove nested-virt steps as they are in ci template now

### PR DESCRIPTION
**Pull request by sallyom**
@dhiller needed for this: https://github.com/openshift/release/pull/7457 

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
Hey Sally! Thanks for your work. 

Did you base this on kubevirt/kubevirt#3122? If not, can  you assist in making out the changes that are missing in the other PR?

**Comment by dhiller** [comment]
Maybe we rather can work together on kubevirt/kubevirt#3122 as it contains another tool compile that is required for dumping debug information.

**Comment by sallyom** [comment]
> Maybe we rather can work together on #3122 as it contains another tool compile that is required for dumping debug information.

yes, i did not see that PR, I'll incorporate this change into 3122 : )

**Comment by sallyom** [comment]
will cherry-pick this into https://github.com/kubevirt/kubevirt/pull/3122
closing

**Pull request closed without merging**
