### PR TITLE
Nominate Antonio as an approver in the tests directory.

### PR DESCRIPTION
**Pull request by stu-gott**
Nominate Antonio as a test approver.

Signed-off-by: Stu Gott <sgott@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by jean-edouard — APPROVED** [review]

**Comment by davidvossel** [comment]
/lgtm

yep, i approve :)

**Comment by xpivarc** [comment]
/approve
/hold
Antonio authored 60+ [PRs](https://github.com/kubevirt/kubevirt/pulls?q=is%3Aclosed+is%3Apr+author%3Aacardace) 
and touched 150+ [PRs](https://github.com/kubevirt/kubevirt/pulls?page=1&q=is%3Apr+commenter%3Aacardace+is%3Aclosed+-author%3Aacardace)

Holding so others have time to go over this. I believe we can unhold on Monday if no objections are raised.

Thank you for your contributions so far!

**Pull request merged**
