### PR TITLE
Allow infra components to be scheduled to master nodes

### PR DESCRIPTION
**Pull request by iholder101**
In many environments the `master` key is still being used (e.g. [1]).

[1] https://docs.openshift.com/container-platform/4.15/nodes/scheduling/nodes-scheduler-taints-tolerations.html

Therefore, allow infra pods to be scheduled to such nodes as well.

### Special notes for your reviewer
Follow-up to: https://github.com/kubevirt/kubevirt/pull/11659
See this comment especially: https://github.com/kubevirt/kubevirt/pull/11659#discussion_r1555270580

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder101** [comment]
Special thanks to @brianmcarey who proactively raised my attention to this.
In https://github.com/kubevirt/kubevirt/pull/11659#discussion_r1555270580 I've intended to include the master label, but since it was deprecated it was eventually removed from the PR. We should bring it back to support old clusters that were upgraded and lack the CP label.

/cc @acardace @fossedihelm

**Review by fossedihelm — APPROVED** [review]
Thank you @iholder101!
As already said I agree with this change
https://github.com/kubevirt/kubevirt/pull/11659#discussion_r1570264920
Sorry for the initial wrong suggestion

**Comment by iholder101** [comment]
> Thank you @iholder101! As already said I agree with this change [#11659 (comment)](https://github.com/kubevirt/kubevirt/pull/11659#discussion_r1570264920) Sorry for the initial wrong suggestion

No need to apologize!
You were pointing out true facts :) I also wasn't aware that the master label is still used in some environments.

Thank you!

**Pull request merged**
