### PR TITLE
[tests]: validate the readiness of kubevirt components before executing a test

### PR DESCRIPTION
**Pull request by enp0s3**
Signed-off-by: Igor Bezukh <ibezukh@redhat.com>

**What this PR does / why we need it**:
It is important for a test to be executed under a healthy Kubevirt deployment. Therefore we need
to ensure ahead of time that the control-plane components are ready.  

**Special notes for your reviewer**:
- We can improve test infra code by adding a matcher for Daemonset readiness 
 I've added it in TODO since I don't want this PR to drift away from its main purpose

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by acardace — APPROVED** [review]
Looks good, thank you!

**Review by davidvossel — COMMENTED** [review]
/approve

**Pull request merged**
