### PR TITLE
[release-0.26] Rewrite container-disk main on C to prevent memory overconsumption

### PR DESCRIPTION
**Pull request by rmohr**
This is an automated cherry-pick of #2844
/assign @cynepco3hahue 

```release-note
Rewrite container-disk main.go file on C to prevent memory overconsumption
```

### CODE REVIEW

**Comment by rmohr** [comment]
/override pull-kubevirt-e2e-k8s-1.14
/override ci/prow/images
/override pull-kubevirt-e2e-k8s-1.15-ceph
/override pull-kubevirt-e2e-k8s-1.16

Interesting, because I created a wrong PR to master before, the jobs triggered there show up here too. Skipping them since they can't succeed on release-0.26.

**Comment by davidvossel** [comment]
/retest

The functional tests were failing because the 0.26.3 release was still pending which caused our upgrade functional tests to fail. That should be sorted now.

**Pull request merged**
