### PR TITLE
fix English typo

### PR DESCRIPTION
**Pull request by dankenigsberg**

### CODE REVIEW

**Comment by dankenigsberg** [comment]
@fabiand, I need to re-read the readme; but it seems that it does not explain why it is a good idea to run VMs via k8s.

**Comment by fabiand** [comment]
Please see
https://github.com/kubevirt/kubevirt.github.io/blob/master/about.md
and
https://github.com/kubevirt/kubevirt.github.io/blob/master/index.md

I think in addition it is a good idea to keep the mission and motivation in this repo, @berrange

**Comment by berrange** [comment]
Needs a commit signoff added.

I don't thin we need to duplicate all that info in the README file too - at most just point people to the website from the README

**Comment by fabiand** [comment]
Thanks!

**Pull request merged**
