### PR TITLE
Positional changes around the Kubevirt logo in the README.md file

### PR DESCRIPTION
**Pull request by Saha-7**
**What this PR does / why we need it**:

-  Shifted the Logo of Kubevirt at the top in the Readme file.
- And made the tag lines alignment in the centre.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

`#Before`

KubeVirt

`#After`

LatestKubeVirt

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by prnaraya** [comment]
Thank you for the PR! Would you please update the PR title to be something more descriptive of what this PR is changing?

**Comment by iholder101** [comment]
> Thank you for the PR! Would you please update the PR title to be something more descriptive of what this PR is changing?

+1

In addition, if you don't mind:
1. Change the commit message as well
2. Fill out "What this PR does / why we need it:" section
3. under `Release note:`, Please write `NONE`

Thanks a lot for your contribution!

**Comment by Saha-7** [comment]
> > Thank you for the PR! Would you please update the PR title to be something more descriptive of what this PR is changing?
> 
> +1
> 
> In addition, if you don't mind:
> 
> 1. Change the commit message as well
> 2. Fill out "What this PR does / why we need it:" section
> 3. under `Release note:`, Please write `NONE`
> 
> Thanks a lot for your contribution!

Yeah Sure!

**Comment by Saha-7** [comment]
I have one doubt, Should I remove the signed off tag line ?

**Comment by iholder101** [comment]
> Yeah Sure!

Thanks!

> I have one doubt, Should I remove the signed off tag line ?

You should keep it only at the bottom of the commit message.
See [this](https://github.com/kubevirt/kubevirt/pull/9763/commits/b3ee981b44a0613c07daed54caa96a2bdcbf8b61) as an example.

tip: this can be added automatically with `git commit --signoff`

**Comment by Saha-7** [comment]
> > Yeah Sure!
> 
> Thanks!
> 
> > I have one doubt, Should I remove the signed off tag line ?
> 
> You should keep it only at the bottom of the commit message. See [this](https://github.com/kubevirt/kubevirt/pull/9763/commits/b3ee981b44a0613c07daed54caa96a2bdcbf8b61) as an example.
> 
> tip: this can be added automatically with `git commit --signoff`

I edited the PR message details & Title. is it ok now ? Let me know if any changes required.

**Comment by iholder101** [comment]
> > > Yeah Sure!
> > 
> > 
> > Thanks!
> > > I have one doubt, Should I remove the signed off tag line ?
> > 
> > 
> > You should keep it only at the bottom of the commit message. See [this](https://github.com/kubevirt/kubevirt/pull/9763/commits/b3ee981b44a0613c07daed54caa96a2bdcbf8b61) as an example.
> > tip: this can be added automatically with `git commit --signoff`
> 
> I edited the PR message details & Title. is it ok now ? Let me know if any changes required.

Thanks a lot! Appreciate it!

You can also remove `Signed-off-by: Pritam Saha <saha7pritam@gmail.com>` suffix from the title and replace the commit subject from it to `Changes in the Readme.MD file` if you don't mind.

/ok-to-test
/lgtm

**Comment by Saha-7** [comment]
Changed the PR title & `Signed-off-by: Pritam Saha <saha7pritam@gmail.com>` section removed. Can you please tell me how to change the commit subject ? I have never done this before.

**Comment by iholder101** [comment]
> Changed the PR title & `Signed-off-by: Pritam Saha <saha7pritam@gmail.com>` section removed. Can you please tell me how to change the commit subject ? I have never done this before.

Basically you need to edit the commit message (e.g. by `git commit --amend`) and re-push the PR.
But that's okay, you can leave it as it is for now and remember it for follow-up PRs :)

Thanks again for you contribution!

**Comment by Saha-7** [comment]
1 check to fail is it the reason that this PR is not merged yet?

**Comment by orelmisan** [comment]
> 1 check to fail is it the reason that this PR is not merged yet?

Thank you for the PR @Saha-7.
PRs need to have `lgtm` and `approved` tags in order for the automation to merge them.
This PR was not yet approved by one of the maintainers.
You can see who the maintainers are under "approvers" in [this](https://github.com/kubevirt/kubevirt/blob/main/OWNERS_ALIASES) docuemnt.

**Comment by Saha-7** [comment]
Okay got it.

**Pull request merged**
