### PR TITLE
Add archive upload option to image upload command

### PR DESCRIPTION
**Pull request by ShellyKa13**
Signed-off-by: Shelly Kagan <skagan@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
this should be merged after PR: https://github.com/kubevirt/containerized-data-importer/pull/1969 is merged,
released and CDI version is bumped in kubevirt

**Release note**:

```release-note
Use virtctl image-upload to upload archive content
```

### CODE REVIEW

**Comment by brybacki** [comment]
You say: "this should be merged with/after PR: kubevirt/containerized-data-importer#1969"

Actually this can be merged after the CDI part is merged, released and CDI version is bumped in the kubevirt

**Comment by ShellyKa13** [comment]
/hold
should be merged only after bump of CDI to v1.41

**Pull request merged**
