### PR TITLE
set numa memory mode

### PR DESCRIPTION
**Pull request by 1iza**
**What this PR does / why we need it**:

I create a  vm with numa, but i can not set  numa memory police, the police defaults to "Strict" now,
so I want to set  numa memory allocation policies .

**Release note**:

```release-note
set  numa memory allocation policies
```

### CODE REVIEW

**Comment by maya-r** [comment]
cc @vladikr

**Review by marceloamaral — COMMENTED** [review]
Looks great! But there are still some necessary updates in `numaMapping()` to calculate and allocate the available memory, as it was initially only implemented to support the `strict` policy.

Therefore, [`involvedCells`] (https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-launcher/virtwrap/converter/numa_placement.go#L25) returns a numamap with only the CPUs allocated. However, if the policy is `interleaving`, the memory allocation can be from a socket where the VMI has no CPU allocated. Likewise, this also happens to some extent with the "preferred" policy.

Therefore, you will need to [allocate memory] (https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-launcher/virtwrap/converter/numa_placement.go#L96) from `NUMA.Cells` in accordance with the NUMA policy.

Finally, you will also need to add tests for it, checking the `interleaving` and `preferred` allocation from Cells that the domain does not have CPUs allocated.

**Comment by knopt** [comment]
@1iza are you still actively working on this feature? I'm interested in making progress on this functionality and I'm wondering if you need any help

**Comment by knopt** [comment]
Hey @marceloamaral - I'm interested in finishing this PR, unless the author decides to do it.

Do you think that support of a usecase of a VM needing access to numa nodes from a socket which it doesn't have any CPUs allocated at, is required in the first implementation?

I understand that doing so is possible with qemu, however, I don't think it's very common, and noone has expressed a need for such KubeVirt feature (for instance through an gh issue), contrary to interleaving over VM's CPU numa nodes. 

Additionally, dynamic numa nodes selection for a VM's CPU numa nodes interleaving is well defined, assuming interleaving over all of the CPUs numa nodes. On the other hand, we would need very thoughtful design to support dynamic selection of numa nodes from another socket. I believe that this is doable, however, it is doubtful if the effort is needed, and worth it.

**Comment by marceloamaral** [comment]
/unhold
It makes sense to move forward with this PR.
Thanks!

**Pull request closed without merging**
