### PR TITLE
Run the network pod tests only on the compute container

### PR DESCRIPTION
**Pull request by SchSeba**
Run the network pod tests only on the compute container
**What this PR does / why we need it**:
Fix the network tests

related to https://github.com/kubevirt/kubevirt/pull/1797

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/1799)

### CODE REVIEW

**Comment by SchSeba** [comment]
/cc @vladikr 
@gageorsburn FYI

**Comment by booxter** [comment]
Ouch, so the fix was THAT easy. Can you please also remove iproute package from disk image while at it? It will also prove that the change works, as well as will get rid of unnecessary package in the disk image.

**Comment by SchSeba** [comment]
@booxter Done lets wait for CI

**Comment by rmohr** [comment]
@SchSeba, hm looks like some of the test lanes got killed. Retriggering.

**Comment by rmohr** [comment]
ci test please

**Comment by rmohr** [comment]
The openshift clusters are affected by a bug in `openshift-ansible` and I see that the networking lanes passed now with these tests. Also the whole k8s-1.11.0 lane.

**Pull request merged**
