### PR TITLE
Add UpdateConfiguration to KubeVirt CR

### PR DESCRIPTION
**Pull request by acardace**
**What this PR does / why we need it**:
Adds a field `UpdateConfiguration` to let a cluster-admin override how the KubeVirt control-plane update is carried out, this PR only introduces the possibility to customize the `MaxUnavailable` setting for DaemonSets (aka virt-handler).

The reason behind this is to have a knob to make the update process faster at the expense of the upgrade safety (KubeVirt's default is to update virt-handler 1 node at a time).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Add parameter to control the number/percentage of virt-handler nodes to be updated in parallel when upgrading/downgrading KubeVirt
```

### CODE REVIEW

**Comment by acardace** [comment]
@davidvossel Do you think we still want this now that the canary upgrade patch is already in main?

**Comment by davidvossel** [comment]
> @davidvossel Do you think we still want this now that the canary upgrade patch is already in main?

We might want it in the future, but I think we're okay to put this PR on hold (close it and reopen in future if needed). I'd like to see if we can get away with the canary upgrade work you did without exposing a new tuning unless it is absolutely necessary

**Comment by acardace** [comment]
/close
For now this can be closed if the canary upgrade work won't be considered enough it can be re-opened.

**Pull request closed without merging**
