### PR TITLE
WIP tests, make networking test dual stack compatible

### PR DESCRIPTION
**Pull request by oshoval**
The first commit is a cherry-pick of #3958

Signed-off-by: Or Shoval <oshoval@redhat.com>

```release-note
None
```

### CODE REVIEW

**Comment by phoracek** [comment]
@oshoval have you repushed this as new PR by mistake?

**Comment by oshoval** [comment]
> @oshoval have you repushed this as new PR by mistake?

its a draft, the first which i guess you meant the first, is a cherry-pick
the 2nd is the important one, which is still WIP (and have a bug)

**Comment by oshoval** [comment]
marking ready just so the team knows what we working on, per request, 
there is still work in this PR

**Pull request closed without merging**
