### PR TITLE
update README.md point to a more specific page

### PR DESCRIPTION
**Pull request by xichengliudui**
Signed-off-by: xichengliudui <liuduidui@beyondcent.com>

**What this PR does / why we need it**:
update README.md point to a more specific page

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by xichengliudui** [comment]
ci test please

**Comment by xichengliudui** [comment]
@ovirt-infra Yes, I plan to continue to contribute to multiple projects. How can I join the project organization? easy to run test.

**Comment by slintes** [comment]
Hey @xichengliudui, thanks for your contribution!
I'm unsure if we want to replace the generic k8s url, but I like the idea of adding a link to the blog post. Can you change it so that it's an additional link?
And because this is a doc only change, there is no need to trigger CI :)

**Comment by xichengliudui** [comment]
I didn't know that I didn't need a CI test because I submitted it for the first time. Sorry.

**Pull request closed without merging**
