### PR TITLE
Make virtctl ssh/pf work with dots in vm name

### LINKED ISSUE #8290: virtctl ssh and portforward are broken when vm name has a dot in it
**What happened**:
I have a VM that has dots in its name (it is named `vm-windows10-x64.roblabla-vm`). It lives in the default namespace. It is currently impossible to connect to it via ssh:

```
$ virtctl ssh vm-windows10-x64.roblabla-vm
You are using a client virtctl version that is different from the KubeVirt version running in the cluster
Client Version: v0.53.0
Server Version: v0.49.0
can't access VMI vm-macos12-x64: virtualmachineinstance.kubevirt.io "vm-macos12-x64" not found
```

Even when explicitly specifying the namespace, it still fails

```
$ virtctl ssh --namespace default vm-windows10-x64.roblabla-vm
You are using a client virtctl version that is different from the KubeVirt version running in the cluster
Client Version: v0.53.0
Server Version: v0.49.0
can't access VMI vm-macos12-x64: virtualmachineinstance.kubevirt.io "vm-macos12-x64" not found
```

What's super confusing is that `virtctl vnc` works totally fine here, as it doesn't have the very weird namespace behavior that `virtctl ssh` has.

**What you expected to happen**:
When explicitly specifying the namespace, I expect the dots to not be stripped from the VM name. Or otherwise, having *some way* of connecting to it.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a vm with a dot in the name
- Try to `virtctl ssh` to it.

**Environment**:
- KubeVirt version (use `virtctl version`): (Server: 0.49.0, Client: 0.53.0)
- Kubernetes version (use `kubectl version`): (Server: 1.21.11, Client: 1.22.5)
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by roblabla**
**What this PR does / why we need it**:
Currently, virtual machines may have dots in their VM name. This currently breaks the logic for parsing portforward/ssh/scp targets, as they assume that no dots can appear in the vm name.

To fix this, we assume that only the last part of the target name (after splitting on dots) is the namespace. A namespace cannot contain dots, so that seems like a safe assumption.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8290 

**Special notes for your reviewer**:

**Release note**:

```release-note
- virtctl ssh, port-forward and scp now accept dots in vm names.
```

### CODE REVIEW

**Review by vasiliy-ul — COMMENTED** [review]
Hi @roblabla, nice fix. Maybe you could also add tests for that?

/ok-to-test

**Comment by alicefr** [comment]
Could you please add your case in the unit tests: https://github.com/kubevirt/kubevirt/blob/97732e01c4d0dc4a05559a78527622f3b4c84457/pkg/virtctl/templates/target_test.go#L12 ?

**Comment by vasiliy-ul** [comment]
> ERROR: git tree state is not clean!

@roblabla, you also need to include the changes introduced by the formatter. Without those, the CI will not pass.

**Comment by maiqueb** [comment]
> I don't really understand the CI failure here, and the logs don't give much indication of what went wrong that I can see (All it says is " Test Failed! 7 issues found. " without saying what those issues are?). Can someone point me in the right direction?

I don't understand what CI failure you mean - but given the only failure you have in on the [fossa lane](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8291/pull-kubevirt-fossa/1561408576595955712), I'm assuming that's the one.

If so, you can disregard that error - that lane is not required, and as such, it won't affect merging your PR.

Your PR requires the `lgtm` and `approved` labels, which must be given by a community member, and a maintainer.

@roblabla

**Review by xpivarc — COMMENTED** [review]
This means that we require a namespace when `.` is in the name. Worth documenting?

**Comment by fossedihelm** [comment]
> This means that we require a namespace when `.` is in the name. Worth documenting?

I agree! Otherwise we need to find a new separator for `name<separator>namespace`. But this requires a wider discussion IMHO.

**Pull request closed without merging**
