### PR TITLE
[release-0.44] Show migration progress timeout in actual seconds

### PR DESCRIPTION
**Pull request by jean-edouard**
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/7654

```release-note
NONE
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
/hold
Something is not right...

**Comment by xpivarc** [comment]
> /hold Something is not right...

@dhiller We might need a cache wipe.

**Comment by xpivarc** [comment]
/hold
We need https://github.com/kubevirt/project-infra/pull/2092

**Pull request merged**
