### PR TITLE
virt-operator: Remove flavor.kubevirt.io RBAC

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype

**What this PR does / why we need it**:

This was previously required to allow deployments to upgrade from v0.54 and should have been dropped with the release of v0.56.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm

Thanks!

**Review by vasiliy-ul — COMMENTED** [review]
/approve

**Pull request merged**
