### PR TITLE
Use smaller writes for fstrim test, improve messaging on failure

### PR DESCRIPTION
**Pull request by maya-r**
Should speed things up, and reduce the chance we'll hit timeouts.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
/test pull-kubevirt-e2e-k8s-1.19-sig-storage
/test pull-kubevirt-e2e-k8s-1.20-sig-storage
/test pull-kubevirt-e2e-k8s-1.21-sig-storage

hoping to see the fstrim test fail...

**Comment by maya-r** [comment]
@mhenriks - this is missing approval, could you have a look?
this flake doesn't seem very frequent. adding prints will make it easier to debug when it happens in the periodic tests.

**Review by dhiller — COMMENTED** [review]
/approve

/hold

Remove hold when ready.

**Comment by brybacki** [comment]
I think it is ready
/unhold

**Pull request merged**
