### PR TITLE
Use canonical import path for libvirt

### PR DESCRIPTION
**Pull request by andreabolognani**
**What this PR does / why we need it**:

Switches the import path for libvirt from the GitHub mirror to the canonical vanity import path ([`libvirt.org/libvirt-go`](https://libvirt.org/libvirt-go)).

**Special notes for your reviewer**:

Assuming I've done everything correctly, this PR should introduce no functional changes. 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by danielBelenky** [comment]
/retest
/lgtm
/approve
/hold

Looks good, please feel free to unhold whenever you're ready.

**Comment by andreabolognani** [comment]
> Looks good, please feel free to unhold whenever you're ready.

@danielBelenky can you expand a bit on that? The PR is ready as far as I'm concerned, and I've never had to unhold a PR before - I'm not even sure if I have the appropriate permissions. Am I missing some process-related requirement?

**Comment by rmohr** [comment]
@andreabolognani you should have the permission. the hold command is useful for cases where you want to block the merge on approved PRs for some time. This allows authors to move the PR forward without a maintainer looking at the PR again (who for whatever reason thought that it may not yet be ok for  the author to move forward with it). Other cases are that some minor changes are still discussed where the maintainer is already happy with the code, but wants to give contributors the chance to finish the discussion on them. Here the hold can again be removed from the people on the discussion without the need for a maintainer. Cases like this basically.

**Comment by andreabolognani** [comment]
@rmohr this *mostly* makes sense to me but it sure is different from how things are done in other projects I contribute to, so it will probably take me a while to wrap my head around it... In the meantime, thanks for the explanation and for being around to help shepherd my patches through :)

**Pull request merged**
