### PR TITLE
[release-1.0] Manual cherry-pick of 10058

### PR DESCRIPTION
**Pull request by alicefr**
Manual backport of https://github.com/kubevirt/kubevirt/pull/10058

**What this PR does / why we need it**:
For correctly deploying Windows Shared Cluster Filesystem, we need to be able to configure the error policy to `report`.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2249846

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Release note**:

```release-note
Add field errorPolicy for disks
```

### CODE REVIEW

**Comment by akalenyu** [comment]
looks good, any special conflicts we should pay attention to? or was this the only pain point? https://github.com/kubevirt/kubevirt/compare/e43f686fb602d732e02940a4dfb6d4c179cfacfe..2475468b37e8a79f1557a95b80098e5f6348d8b3

**Comment by alicefr** [comment]
> looks good, any special conflicts we should pay attention to? or was this the only pain point? https://github.com/kubevirt/kubevirt/compare/e43f686fb602d732e02940a4dfb6d4c179cfacfe..2475468b37e8a79f1557a95b80098e5f6348d8b3

not really, only that function was refactored between this feature and the 1.o release

**Comment by alicefr** [comment]
/hold

we need to clarify if this is an acceptable backport

**Review by vasiliy-ul — COMMENTED** [review]
Follow-up of the discussion: https://github.com/kubevirt/kubevirt/pull/10736#discussion_r1395635043

This backport PR changes the API. However, it does not break compatibility, as it only brings new fields and constants. The alternative solution to later backport https://github.com/kubevirt/kubevirt/pull/10736 introduces a change in the default behavior.

From my perspective, this PR is a better alternative. The only issue I see is the downgrade path. If we want to support downgrades e.g. between patch versions (e.g. 1.1.1 -> 1.1.0) the code here may break migration of running workloads. If this is not a big concern for the project, I think we shall go with it. Other thoughts?

**Comment by alicefr** [comment]
From the discussion https://github.com/kubevirt/kubevirt/pull/10736#discussion_r1395635043, this seems the more preferable way to proceed with the setting of the error policy for Windows, I'm upholding as consequences of the discussion

/unhold

**Comment by vasiliy-ul** [comment]
BTW, as we now have sig-api regular meetings, maybe makes sense to bring this up there?

**Comment by xpivarc** [comment]
> Follow-up of the discussion: [#10736 (comment)](https://github.com/kubevirt/kubevirt/pull/10736#discussion_r1395635043)
> 
> This backport PR changes the API. However, it does not break compatibility, as it only brings new fields and constants. The alternative solution to later backport #10736 introduces a change in the default behavior.
> 
> From my perspective, this PR is a better alternative. The only issue I see is the downgrade path. If we want to support downgrades e.g. between patch versions (e.g. 1.1.1 -> 1.1.0) the code here may break migration of running workloads. If this is not a big concern for the project, I think we shall go with it. Other thoughts?

We officially don't support downgrades. There are no tests for it as of now and I did not hear an interest in supporting it for now.

**Review by vasiliy-ul — APPROVED** [review]
Ok, if we do not support downgrades, then I think this should be good to go.

**Comment by vladikr** [comment]
+1 fwiw :)

**Comment by alicefr** [comment]
Thanks everyone for the quick help!

**Pull request merged**
