### PR TITLE
Change vm-resource CRD kind and add short names

### LINKED ISSUE #439: With our switch to CRDs it is now possible to give our VM it's final name "VirtualMachine"
So far, we used for our VirtualMachine object the name `VM`, to allow us  doing simple things at the client side, like `kubectl get vms` in contrast to `kubectl get virtualmachine`. Now with CRDs in place, we can change it and use the proper `VirtualMachine` Kind and still keep the vm/vms convenience.

Our CRD should look like this:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualmachines.kubevirt.io
spec:
  group: kubevirt.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: virtualmachines
    singular: virtualmachine
    kind: VirtualMachines
    shortNames:
    - vm
    - vms
```
Minor code adjustments might be necessary (Replacing e.g. "VM" with "VirtualMachine").

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Fixes #439 
Signed-off-by: Lukianov Artyom <alukiano@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
ok to test

**Comment by rmohr** [comment]
and can you rebase?

**Comment by cynepco3hahue** [comment]
@rmohr Can you please re-run Jenkins job, I tested it locally and all tests passed.

**Comment by rmohr** [comment]
retest this please

**Comment by davidvossel** [comment]
As soon as we can get regression tests to pass I'm good with this change.  We should merge it quickly after it passes. This is patch is going to be a pain to have to constantly rebase.

**Comment by cynepco3hahue** [comment]
@rmohr @davidvossel Do I have possibility to see `journalctl` of jenkins job, for my local `make functest` all passes without any errors?

**Comment by rmohr** [comment]
retest this please

**Pull request merged**
