### PR TITLE
Kubevirt namespace

### PR DESCRIPTION
**Pull request by stu-gott**
Switch default namespace to 'kubevirt'

```release-note
Default namespace for KubeVirt components is now kubevirt
```

### CODE REVIEW

**Comment by fabiand** [comment]
/cc @aglitke @mhenriks please note the mentioned carshes.

@stu-gott nice patch :) Could you please also cross-reference the user-guide updates with this bug, to see when they are in place as well?

**Comment by aglitke** [comment]
See https://github.com/kubevirt/containerized-data-importer/issues/531 .  To unblock this, please keep CDI in the kube-system namespace until it can also be moved.

**Comment by fabiand** [comment]
Ping?

**Comment by rmohr** [comment]
@stu-gott @aglitke I don't understand what is blocking us here for moving KubeVirt. On CI we run KubeVirt already completely in random namespaces. We  don't have to install CDI in a special namespace.

**Comment by fabiand** [comment]
@aglitke please provide a feedback today, otherwise I'd suggest to move forward as is.

**Comment by stu-gott** [comment]
@rmohr the problem with this PR as written is that the RBAC rules we create for KubeVirt moved to the new namespace. CDI was depending on them still being in the `kube-system` namespace.

Two possible approaches:

1. KubeVirt keeps an RBAC rule around allowing read-write to ConfigMaps in `kube-system`
2. CDI creates their own RBAC rules for namespaces those components depend on, so that the projects can be independent.

The better approach from my POV is the second path. Is that reasonable @aglitke @mhenriks ?

**Comment by fabiand** [comment]
Ah, so it sounds as if the rule is about this specific configmap, then I'm
good.

**Comment by stu-gott** [comment]
Please note I made the namespace CDI components use configurable separately.

**Comment by fabiand** [comment]
@stu-gott do you know if the CI passes on your local host?

**Comment by stu-gott** [comment]
ci test please

**Comment by stu-gott** [comment]
ci test please

**Comment by stu-gott** [comment]
I believe the one remaining failing test might be spurious.

**Comment by fabiand** [comment]
ci test please

**Comment by fabiand** [comment]
All k8s tests pass, thus looks good to me.

**Comment by fabiand** [comment]
The remaining kube-system namespaces are related to CDI and vendored code.

**Pull request merged**
