### PR TITLE
Add prow automation for unit-test

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
This is the first step to move the validations we do at travis
to prow so we have a proper test results and artifacts dir, also
we can check a ci result view including unit test at prow.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
The prow job PR https://github.com/kubevirt/project-infra/pull/398

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
@qinqon I think the builder image in the job is not up-to-date.

**Comment by qinqon** [comment]
@rmohr updated job with newer image, maybe it make sense to add something at `unit-test.sh` to check that the builder image we are using is aligned with the one at `hack/dockerized` ?

**Comment by qinqon** [comment]
Running at https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3202/pull-kubevirt-unit-test/1247078563367096320

**Comment by qinqon** [comment]
something has change at kubevirt

```
+ make bazel-test
hack/dockerized "hack/bazel-fmt.sh && hack/bazel-test.sh"
FATAL: $USER is not set, and unable to look up name of current user: (error: 0): Success
make: *** [Makefile:26: bazel-test] Error 36
```

**Comment by qinqon** [comment]
re-running with USER=root
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3202/pull-kubevirt-unit-test/1247086995251924992

**Comment by qinqon** [comment]
root is not a good option

```
+ make bazel-test
hack/dockerized "hack/bazel-fmt.sh && hack/bazel-test.sh"
FATAL: mkdir('/.cache/bazel/_bazel_root'): (error: 13): Permission denied
make: *** [Makefile:26: bazel-test] Error 36
```

**Comment by rmohr** [comment]
> something has change at kubevirt
> 
> ```
> + make bazel-test
> hack/dockerized "hack/bazel-fmt.sh && hack/bazel-test.sh"
> FATAL: $USER is not set, and unable to look up name of current user: (error: 0): Success
> make: *** [Makefile:26: bazel-test] Error 36
> ```

The cc rules from bazel are trying to look up a user.Not sure what it needs it for. In the source code it looks not like it really needs it for anything relevant for us. Can you just try setting `USER` to something?

**Comment by qinqon** [comment]
@rmohr setting it to root fails at :

```
+ make bazel-test
hack/dockerized "hack/bazel-fmt.sh && hack/bazel-test.sh"
FATAL: mkdir('/.cache/bazel/_bazel_root'): (error: 13): Permission denied
make: *** [Makefile:26: bazel-test] Error 36
```

**Pull request closed without merging**
