### PR TITLE
expose,e2e: remove tests checking svc after vm removed

### PR DESCRIPTION
**Pull request by rhrazdil**
This PR proposes removal of expose tests that verify that the service doesn't work after the VM is removed.
These tests are currently marked as flaky with QUARANTINE label, however testing such behaviour doesn't seem to provide value to KubeVirt, because it's not KubeVirt responsibility make a service "not work".

When a VMI/VMIRS/VM is deleted, KubeVirt responsibility is to delete the virt-launcher pod backing the actual virtual machine.

There is no need to test that k8s Endpoints subset pointing to the virt-launcher pod(s) is empty, as it's Kubernetes responsibility to populate k8s Endpoints based on the selector defined in the k8s Service.

For the flake itself, it appears to occur when waiting for the jobs to fail, see
https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8335/pull-kubevirt-e2e-k8s-1.23-sig-network/1572312639533486080#1:build-log.txt%3A3995
One of the 4 jobs is still Active, when the timout is hit.

Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by EdDev — COMMENTED** [review]
Very nice!

> Testing such behaviour doesn't seem to provide any value to
kubevirt.

typo: behavior

It will be beneficial to share the reason it does not provide value, it may not be trivial to all (or future us).

**Comment by rhrazdil** [comment]
Thank you @EdDev, I have updated the PR description with a reasoning for removing the test, do you find it better?

>>Testing such behaviour doesn't seem to provide any value to
kubevirt.

>typo: behavior

I prefer using British English to American,

**Comment by EdDev** [comment]
> Thank you @EdDev, I have updated the PR description with a reasoning for removing the test, do you find it better?

Thank you.
Could you please also update the commit message?

**Comment by rhrazdil** [comment]
@EdDev Updated the commit message

**Review by EdDev — APPROVED** [review]
Thank you!

**Comment by rhrazdil** [comment]
@yossisegev FYI, this tas has a label, you may want to obsolete it in your test plan
https://github.com/kubevirt/kubevirt/pull/8523/commits/f3f29def4cc8cfa74acecf9ed9aa9f382df5f464#diff-868b9e2c371b0f31a98aa6f4d7e35437e529a2036be78eefd99c052a8e6c2d20L869

**Comment by yossisegev** [comment]
Thanks Radim, I'll look into it and see if we will entirely delete this test case (the motivation, as described in this PR, makes a lot of sense).

**Pull request merged**
