### PR TITLE
[release-1.3] cleanup(tests,virtctl): Drop virtctl expose functests

### PR DESCRIPTION
**Pull request by ormergi**
### What this PR does

**Manual** backport https://github.com/kubevirt/kubevirt/pull/12948

Before this PR:

After this PR:

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by orelmisan — COMMENTED** [review]
Thank you for the PR @ormergi.
Is it an automatic cherry-pick? Were there any manual changes?

**Comment by ormergi** [comment]
> Thank you for the PR @ormergi. Is it an automatic cherry-pick? Were there any manual changes?

Unfortuantly automatic cherry-pick doesnt work due to conflicts.
I had to change this line https://github.com/kubevirt/kubevirt/pull/13183/files#diff-9988e8f74129e7501bc8c2db1d54946cdb13a38e90642603b3ba4a53fe062075R160 to use the variable that lives in tests/utils.go becuase the PR that moves it doesnt exist on this branch.

**Comment by xpivarc** [comment]
Is this really worth backporting?

**Comment by xpivarc** [comment]
/hold
Also you missed 1.4

**Comment by ormergi** [comment]
> Is this really worth backporting?

Some of these tests are flaky we see these flakes also in periodic release lanes, so I think its nice removing them from the release branch we currently support.
Changes are done in e2e tests only, no production code is changed, so I think its safe.

>  Also you missed 1.4

It seem that these changes bits exist in release-1.4 branch
https://github.com/kubevirt/kubevirt/pull/12948#issuecomment-2457063843

@xpivarc

**Comment by EdDev** [comment]
> Is this really worth backporting?

Yes, it causes a lot of noise when executing and has no value.
Backporting test removal seems reasonable to me with zero risk to production.

/approve

**Pull request merged**
