### PR TITLE
builder: Bump GOLANGCI_LINT_VERSION to v1.54.0

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

This will be used by https://github.com/kubevirt/kubevirt/pull/10002 to introduce a second run of `golangci-lint` using `ginkgolinter` to search for any focused containers outside of the limited subset of directories of the first run.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lyarwood** [comment]
/hold cancel
@brianmcarey  when you're back from PTO would you mind taking a look at this? Will be used by https://github.com/kubevirt/kubevirt/pull/10002 once landed and built.

**Comment by lyarwood** [comment]
/hold cancel
/cc @brianmcarey 

When you're back from PTO would you mind taking a look at this? Will be used by https://github.com/kubevirt/kubevirt/pull/10002 once landed and built.

**Comment by brianmcarey** [comment]
> /hold cancel /cc @brianmcarey
> 
> When you're back from PTO would you mind taking a look at this? Will be used by #10002 once landed and built.

@lyarwood sorry for only picking this up now - I have published a new builder with this change : `quay.io/kubevirt/builder:2308311459-fffe1d649`

**Comment by lyarwood** [comment]
@brianmcarey no issues and thanks, I've included the `KUBEVIRT_BUILDER_IMAGE` bump commit in this PR now.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Pull request closed without merging**
