### PR TITLE
Fix spelling error

### PR DESCRIPTION
**Pull request by ansijain**
Fix spelling error	
       tupple-->tuple
https://github.com/kubevirt/kubevirt/issues/6125

Signed-off-by: ansijain <ansi.jain@india.nec.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NA
```

### CODE REVIEW

**Review by vatsalparekh — APPROVED** [review]
/lgtm

**Comment by ansijain** [comment]
@vatsalparekh would you mind giving lgtm label. The previous one was removed as I have added a commit

**Comment by dankenigsberg** [comment]
/lgtm
mea culpa

**Pull request merged**
