### PR TITLE
[release-1.1] Ensure virt-export route has redirect policy

### PR DESCRIPTION
**Pull request by awels**
This is a manual cherry-pick of #12195

/assign awels

```release-note
Virt export route has an edge termination of redirect
```

### CODE REVIEW

**Comment by awels** [comment]
I accidentally created a PR against the main branch and closed it, that is why all those failed tests are showing up. They are main branch tests.

**Comment by fossedihelm** [comment]
ooooh! Now I got it! Thank you
/lgtm

**Comment by awels** [comment]
Can I get an approve on this? @mhenriks @alicefr

**Pull request merged**
