### PR TITLE
Handle mdev device type removal in CR

### PR DESCRIPTION
**Pull request by yeahdongcn**
Signed-off-by: Xiaodong Ye <yeahdongcn@gmail.com>

**What this PR does / why we need it**:

I'm using KubeVirt to provision Windows VM with vGPU.

The CR change looks like the following:

```yaml
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
      - GPU
      - HostDevices
    mediatedDevicesConfiguration:
      nodeMediatedDeviceTypes:
      - mediatedDevicesTypes:
        - gpu-2001
        - gpu-2002
        nodeSelector:
          kubernetes.io/hostname: ubuntu
    permittedHostDevices:
      mediatedDevices:
      - mdevNameSelector: gpu-1g
        resourceName: domain.com/gpu-1g
      - mdevNameSelector: gpu-2g
        resourceName: domain.com/gpu-2g
```

As I have two GPUs on the node, `virt-handler` create the mdev device for me with the two types. I can specify `domain.com/gpu-1g` and `domain.com/gpu-2g` in VMI spec.

I remove `gpu-2002` (`domain.com/gpu-2g`) today and from the `virt-handler` log, it shows the devices are removed first and then added back with new UUIDs.

```log
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully removed mdev 01ce94f6-bb67-434d-b9ed-a61a2281c9f7","pos":"common.go:168","timestamp":"2022-09-07T06:03:13.417457Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully removed mdev 0d120114-9a9d-44e2-a658-c9cca96283d4","pos":"common.go:168","timestamp":"2022-09-07T06:03:13.431106Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully removed mdev 4f672142-2c46-4945-bb91-8f720e4ddb8a","pos":"common.go:168","timestamp":"2022-09-07T06:03:13.447046Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully removed mdev 7206af6f-ebf2-4aba-9e09-69dee60785ab","pos":"common.go:168","timestamp":"2022-09-07T06:03:13.462928Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully removed mdev 7cf31cd2-059d-413f-b797-e3be0b92617f","pos":"common.go:168","timestamp":"2022-09-07T06:03:13.478993Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully removed mdev b4def0fc-1d8f-450d-b10f-31cbdcadf078","pos":"common.go:168","timestamp":"2022-09-07T06:03:13.492476Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully removed mdev b6834f4c-d539-472d-8239-d7f4853ce201","pos":"common.go:168","timestamp":"2022-09-07T06:03:13.501963Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully removed mdev b8fb2a5c-2a54-40a1-9995-39e72bdbd71e","pos":"common.go:168","timestamp":"2022-09-07T06:03:13.513730Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2002 - 3bada9aa-039a-43e9-a074-93e586342193","pos":"common.go:149","timestamp":"2022-09-07T06:03:13.525000Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2002 - 1260d1ef-14df-40d2-ba45-68125b1199cc","pos":"common.go:149","timestamp":"2022-09-07T06:03:13.538453Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2002 - 6ca1ec56-ad32-44eb-bd2b-6bd5343f0319","pos":"common.go:149","timestamp":"2022-09-07T06:03:13.551050Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2002 - ad88503d-617c-4a36-8c26-a75b52f1da7b","pos":"common.go:149","timestamp":"2022-09-07T06:03:13.564816Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2002 - ec5f7875-7451-44b8-98b0-56d76ce515ce","pos":"common.go:149","timestamp":"2022-09-07T06:03:13.577789Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2002 - 072c1bdf-a71b-4786-b5b0-5963bec85159","pos":"common.go:149","timestamp":"2022-09-07T06:03:13.587705Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2002 - afc519d8-bd39-432c-9937-c8d89dcb6d23","pos":"common.go:149","timestamp":"2022-09-07T06:03:13.598181Z"}
virt-handler {"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2002 - 5603c65f-fc69-4db8-8b48-37afc1a7613e","pos":"common.go:149","timestamp":"2022-09-07T06:03:13.607759Z"}
```

This PR fixes the above issue and by applying this change, `gpu-2001` mdev devices are created (which is expected). Please see the following logs:

```log
{"component":"virt-handler","level":"info","msg":"Successfully removed mdev 5229c104-2536-40c4-9b3a-dd412e7c8826","pos":"common.go:168","timestamp":"2022-09-07T07:40:25.175260Z"}
{"component":"virt-handler","level":"info","msg":"Successfully removed mdev 6c1de653-5ad8-422d-af92-2b85e3ced719","pos":"common.go:168","timestamp":"2022-09-07T07:40:25.186457Z"}
{"component":"virt-handler","level":"info","msg":"Successfully removed mdev 7ba9d542-756b-40fe-af79-687fa2762f74","pos":"common.go:168","timestamp":"2022-09-07T07:40:25.196289Z"}
{"component":"virt-handler","level":"info","msg":"Successfully removed mdev 8a39299a-b908-4ebd-b959-1327a589a4a3","pos":"common.go:168","timestamp":"2022-09-07T07:40:25.205700Z"}
{"component":"virt-handler","level":"info","msg":"Successfully removed mdev bad9d52b-604c-4b71-a264-1249ee914a1d","pos":"common.go:168","timestamp":"2022-09-07T07:40:25.214700Z"}
{"component":"virt-handler","level":"info","msg":"Successfully removed mdev c5a417df-3ad3-4bdf-bf99-5572ae329462","pos":"common.go:168","timestamp":"2022-09-07T07:40:25.223889Z"}
{"component":"virt-handler","level":"info","msg":"Successfully removed mdev d65d975c-bb3f-4f7e-8e21-34e728a3e605","pos":"common.go:168","timestamp":"2022-09-07T07:40:25.235513Z"}
{"component":"virt-handler","level":"info","msg":"Successfully removed mdev fc793dbd-15a8-4228-adfc-b989ac7902de","pos":"common.go:168","timestamp":"2022-09-07T07:40:25.248575Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - 138c34f1-13ef-4874-8c8a-96c9b6bfe5e2","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.263495Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - 8bc4fe85-144c-4f61-8550-d75540e7cca2","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.276287Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - 96070d61-7fa9-4a32-a793-5338ad541331","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.287997Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - b01943d2-463b-4f80-8c2c-bdbe011335f9","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.300014Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - 59cdff47-b185-4276-88b3-1d635ea40a81","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.313137Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - b623e555-b145-43be-a859-95960e2cdc0a","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.327240Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - e177db2a-c3e1-4c7a-bf68-8b484c745251","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.343319Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - 9970acfa-956b-491e-9515-4796ebc50eff","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.357946Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - 296193c7-1afa-4a9d-b4c4-f1a1c4c58330","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.368492Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - adc4f8cb-ae07-475e-bfa2-a746b6b356ce","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.377170Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - b9f1392e-d415-4a11-a33d-9d828d34cc1c","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.386734Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - af77ae54-bc45-45e9-9406-8de9632d4267","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.396317Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - da3ccfaa-6e30-43ae-922b-3d5c6dd23f8a","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.406645Z"}
{"component":"virt-handler","level":"info","msg":"Successfully created mdev gpu-2001 - 16366d62-5bf9-4686-bc49-9e0be91b46fd","pos":"common.go:149","timestamp":"2022-09-07T07:40:25.422189Z"}
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
This PR also fixes one typo and two static check issues.

**Release note**:

```release-note
Fixed the issue that mdev device type removal in CR doesn't take effect.
```

### CODE REVIEW

**Comment by alicefr** [comment]
Would be possible to add unit tests that check this case?

**Comment by yeahdongcn** [comment]
> Would be possible to add unit tests that check this case?

I wish I could... But due to https://github.com/kubevirt/kubevirt/issues/7568, it may be too hard for me.

**Comment by yeahdongcn** [comment]
@alicefr Done. Please see the latest commit (which also fixes several typos and issues found by `vscode`). Thanks.

```
❯ pwd
/home/xiaodongye/ws/other/kubevirt/pkg/virt-handler/device-manager
❯ go test -count=1 .
ok      kubevirt.io/kubevirt/pkg/virt-handler/device-manager    3.612s
```

**Comment by alicefr** [comment]
It looks good to me. Small suggestion, maybe split in 2 commits the typo fixes and the actual bug fix.
/lgtm

**Comment by yeahdongcn** [comment]
@alicefr All required tests are passed, this PR may need an `approve` label to be merged.

**Comment by alicefr** [comment]
@yeahdongcn I think you need a rebase for fixing the failed test

**Comment by yeahdongcn** [comment]
> @yeahdongcn I think you need a rebase for fixing the failed test

Done.

**Comment by xpivarc** [comment]
@vladikr Can you have a look?

**Comment by vladikr** [comment]
@yeahdongcn I've very sorry for the late reply... This makes total sense to me.
Could you please rebase your PR?

**Pull request closed without merging**
