### PR TITLE
virtwrap: Don't ignore <memory><target><address>

### PR DESCRIPTION
**Pull request by acardace**
Starting with [1], which is part of 9.7.0, libvirt requires that the base address is preserved when updating a memory device.

Right now KubeVirt ignores the field, resulting in

  cannot modify memory address from '0x0x100000000' to '0x0'

on update.

[1] https://gitlab.com/libvirt/libvirt/-/commit/0b7af96492993bc8bacbff0dd8f9ea950772aff6

https://issues.redhat.com/browse/CNV-39421

### What this PR does
Before this PR:

Memory hotplug doesn't work anymore with libvirt 10.0 and qemu 8.2. 

After this PR:

Memory hotplug works with libvirt 10.0 and qemu 8.2. 

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

To use memory hotplug guests must run at least Linux v5.16.

https://lore.kernel.org/qemu-devel/20211130092838.24224-1-david@redhat.com/

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by andreabolognani** [comment]
@acardace I'm okay with this change going in, obviously :) but I don't understand why this specific commit is being singled out. Is that because the downstream builds are already using newer libvirt and thus hitting the issue, which the upstream builds still are not?

FYI, I've temporarily paused the work on https://github.com/kubevirt/kubevirt/pull/11256 to try and sort out some other stuff, but I'd appreciate any help with debugging the remaining issues.

**Comment by acardace** [comment]
> @acardace I'm okay with this change going in, obviously :) but I don't understand why this specific commit is being singled out. Is that because the downstream builds are already using newer libvirt and thus hitting the issue, which the upstream builds still are not?
> 
> FYI, I've temporarily paused the work on #11256 to try and sort out some other stuff, but I'd appreciate any help with debugging the remaining issues.

Hi @andreabolognani, yes that's exactly why. Downstream builds are already hitting this issue so it's quite urgent we fix and backport this.

https://issues.redhat.com/browse/CNV-39421

**Comment by andreabolognani** [comment]
Sounds reasonable.

/lgtm

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
