### PR TITLE
 [release-0.51] Fixing host model support heterogeneus cluster

### PR DESCRIPTION
**Pull request by Barakmor1**
**What this PR does / why we need it**:
Calculate selectors only for the initial Node to remeber the required features,
allow vmi with host-model to migrate when target node does't have the same host-model cpuModel.
manual backporting https://github.com/kubevirt/kubevirt/pull/7672 ,https://github.com/kubevirt/kubevirt/pull/7770 from main
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
The original PR has 5 commits, I would expect this one to have 5 as well (unless most of the code had to be rewritten, but that doesn't seem to be the case).
Please use `git cherry-pick -x` to keep a reference to the original commit IDs.
This PR seems to not only backport #7672 but also parts of #7770, namely this commit: https://github.com/kubevirt/kubevirt/commit/47794de11e687846a3f8675dd00220fb48857c8c
I would suggest cherry-picking that commit too and explicitly stating it in the PR description.
Finally, in the PR title, please move `[release-0.51]` to the beginning of the line.

**Comment by Barakmor1** [comment]
> The original PR has 5 commits, I would expect this one to have 5 as well (unless most of the code had to be rewritten, but that doesn't seem to be the case). Please use `git cherry-pick -x` to keep a reference to the original commit IDs. This PR seems to not only backport #7672 but also parts of #7770, namely this commit: [47794de](https://github.com/kubevirt/kubevirt/commit/47794de11e687846a3f8675dd00220fb48857c8c) I would suggest cherry-picking that commit too and explicitly stating it in the PR description. Finally, in the PR title, please move `[release-0.51]` to the beginning of the line.

Hey @jean-edouard  ,
You are right this PR also back port  #7770  And some of the code  has been rewritten so i took the main branch as reference.

Please note that some of the original commits are using function of `libnode`,`libvmi` and `alertIfHostModelIsUnschedulable` function  that weren't exist in older versions which make it very difficult  using `git cherry-pick` with the original commits.

Also i had to modify some of the additional tests(second commit) because we discovered that they are flacky ( #7752 ).

Because of the complexity of maintaining the order of the commits and the amount of versions that we need to be back port I decided to simplify it to 2 commits (i think that the commits are small and cohesive) .

**Comment by jean-edouard** [comment]
We should be really careful with backports. Including various bits from various PRs can make subsequent backports exponentially harder.
Since this is effectively backporting 3 PRs (#7672 #7752 #7770), can one or two of those be backported cleanly? (i.e. using cherry-picks).
Thanks for the improved PR description and commit messages, that's already a big improvement to help future backporters.

**Comment by Barakmor1** [comment]
@jean-edouard This is the history of these PRs:
1) https://github.com/kubevirt/kubevirt/pull/7672 got merged 
2) lot of tests started to failed because of some things that were missing in #7672
3) we fixed this bug in #7070 and **modifed** ALL the functions that were **modified** in #7672 (`prepareNodeSelectorForHostCpuModel` , `alertIfHostModelIsUnschedulable` , `loadDomCapabilities` )
4) we discovered that  tests that update the nodes are flaky because of the node's heartbeat and Itamar created this PR  #7752
5) i couldn't back port  #7752 because it has many dependencies that didn't exist in previous versions so i just added eventually when updating nodes instead of patching them like Itamar did in   #7752

beside that the original tests are using functions that are in `libnode` and `libvmi` so i couldn't backport the commits of the tests as well.
and also in the original commits we modify `alertIfHostModelIsUnschedulable` that didn't exist in previous versions

I know that it is much harder to review this PR without keeping the original commits and the order but i couldn't find a better way.

**Comment by Barakmor1** [comment]
in other versions i used `git cherry pick` to get commits from this version when it was possible:

https://github.com/kubevirt/kubevirt/pull/7957
https://github.com/kubevirt/kubevirt/pull/7956
https://github.com/kubevirt/kubevirt/pull/7955
https://github.com/kubevirt/kubevirt/pull/7954
https://github.com/kubevirt/kubevirt/pull/7953
https://github.com/kubevirt/kubevirt/pull/7952
https://github.com/kubevirt/kubevirt/pull/7950
https://github.com/kubevirt/kubevirt/pull/7949
MERGED:
https://github.com/kubevirt/kubevirt/pull/7870
https://github.com/kubevirt/kubevirt/pull/7857

**Pull request closed without merging**
