### PR TITLE
Cleanup versions of sig-storage label

### PR DESCRIPTION
**Pull request by brybacki**
**What this PR does / why we need it**:

Updates all the storage labels in test to the one correct
version "[sig-storage]".

All tests in tests/storage directory are already marked as sig-storage
by the top level SigDescribe, no need to mark individual tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brybacki** [comment]
@fgimenez this is the cleanup of the labels.

There is also an issue that some tests have storage and compute labels. But for the other problem I would like to open a separate PR where we can actually decide/discuss who owns the test, and refactor if needed.

**Review by fgimenez — APPROVED** [review]
/lgtm

> There is also an issue that some tests have storage and compute labels. But for the other problem I would like to open a separate PR where we can actually decide/discuss who owns the test, and refactor if needed.

ok sounds good

**Comment by brybacki** [comment]
@mhenriks I did some cleanup to make sig-storage labels consistent, wdyt?

**Comment by brybacki** [comment]
/hold
I'll update tests/storage_test.go later today

**Pull request merged**
