### PR TITLE
[e2e] Move migration tests files in their own package 

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
`migration_test.go` file has grown a lot over time.
This has compromised the readability of the file itself, as well as its maintainability.
In addition, containing several overlapping `Contexts`, several flakes have recently been discovered due to the test setup as much as the code base.
The primary intention of this PR is to create a starting point for the separation of different contexts in different files, in order to isolate them.
This PR also contains several refactoring commits to reduce code duplication, providing utility functions widely usable.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Looking at the changes entirely can lead to a loss.
I suggest to go commit by commit and try to follow the journey I took, which can basically be summarized as this:
- Creation of the `tests/migration` package and move related files there
- Removal of some duplicated functions in `utils` file
- Generalization of some utility functions in `migration` file
- Extract eviction strategy migration tests in their own file
- Extracting of some common utility functions which supports vmi creation with `Option`
- Extracting of an utility function to create a Windows vmi
- Some re-organization of the `migration` file

**Release note**:

```release-note
NONE
```

/cc @xpivarc @iholder101 @Barakmor1 @jean-edouard @acardace

### CODE REVIEW

**Review by jean-edouard — COMMENTED** [review]
Great refactoring, thanks!
/approve
As a side note, while we have all these tests centered around migration, we should see migrations as standard VM(I) operations, just like shutdown or reboot. I hope the existence of the "migration" test module and the "migrations" lanes don't discourage developers from adding migrations to outside tests.
**All test lanes currently support live migration**, and adding migrations to "non-migration" tests should be encouraged. Too often do we see various storage/network/other features fail in the field after a migration, and that could be caught earlier if more tests included a migration.
Maybe we should find a place in the developer documentation to add something about that.

**Comment by fossedihelm** [comment]
> Great refactoring, thanks! /approve As a side note, while we have all these tests centered around migration, we should see migrations as standard VM(I) operations, just like shutdown or reboot. I hope the existence of the "migration" test module and the "migrations" lanes don't discourage developers from adding migrations to outside tests. **All test lanes currently support live migration**, and adding migrations to "non-migration" tests should be encouraged. Too often do we see various storage/network/other features fail in the field after a migration, and that could be caught earlier if more tests included a migration. Maybe we should find a place in the developer documentation to add something about that.

Thanks @jean-edouard. I think you are right, we should do something from this point of view. Let me just add that the rationale behind this refactoring is to start separating things based on their functionality. Doing it all in once would have been too hard to do and to review. At least this is my point of view :slightly_smiling_face:

**Comment by fossedihelm** [comment]
Rebased: main conflicts with https://github.com/kubevirt/kubevirt/pull/9470. Covered the new file with the refactoring

**Comment by fossedihelm** [comment]
Rebased: fixed conflicts with https://github.com/kubevirt/kubevirt/pull/9432: Here was done the same extraction of common `libvmi.WithConfigMap`, etc... So, the 5th commit become `Use libvmi option` instead of `Extract libvmi option`

**Comment by fossedihelm** [comment]
Close in favor of https://github.com/kubevirt/kubevirt/pull/10362

**Pull request closed without merging**
