### PR TITLE
test kubevirt/kubevirtci#913 changes

### PR DESCRIPTION
**Pull request by ormergi**
Signed-off-by: Or Mergi <ormergi@redhat.com>

**What this PR does / why we need it**:
Test kubevirt/kubevirtci#913 changes

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ormergi** [comment]
1/1 Success

/test pull-kubevirt-e2e-kind-1.23-sriov

**Comment by ormergi** [comment]
2/2 Success

/test pull-kubevirt-e2e-kind-1.23-sriov

**Comment by ormergi** [comment]
4/4 Success

/test pull-kubevirt-e2e-kind-1.23-sriov

**Comment by ormergi** [comment]
5/5 Success

/test pull-kubevirt-e2e-kind-1.23-sriov

**Comment by EdDev** [comment]
Perhaps also add the other lane (1.22) in the next attempt: pull-kubevirt-e2e-kind-1.22-sriov

**Comment by ormergi** [comment]
6/6 Success

/test pull-kubevirt-e2e-kind-1.23-sriov
/test pull-kubevirt-e2e-kind-1.22-sriov

**Comment by EdDev** [comment]
> Why? its not voting and we plan to drop it soon anyway

To test more.

**Comment by EdDev** [comment]
7/7 Success

/test pull-kubevirt-e2e-kind-1.23-sriov
/test pull-kubevirt-e2e-kind-1.22-sriov

**Comment by ormergi** [comment]
8/8 Success

/test pull-kubevirt-e2e-kind-1.23-sriov
/test pull-kubevirt-e2e-kind-1.22-sriov

**Comment by EdDev** [comment]
9/9 Success

/test pull-kubevirt-e2e-kind-1.23-sriov
/test pull-kubevirt-e2e-kind-1.22-sriov

**Comment by EdDev** [comment]
10/10 success.

**Pull request closed without merging**
