### PR TITLE
Select mount point for hot pluggable volumes by additional PV name match

### LINKED ISSUE #9437: Hotplug - invalid volume path for volumes with the same mountpoints
**What happened**:
The function [parentMountInfoFor](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-handler/isolation/isolation.go#L197) reads the root of the mount within the filesystem of hp container and tries to locate a mountpoint containing it on the host. This doesn't work well if the mount root is the same for multiple volumes.

To make it more clear let's consider the following example, I used longhorn and nfs csi drivers to create 4 PVCs.
With longhorn I am able to create two PVCs without a problem. With NFS I cannot create more than one.

<details>
<summary>Longorhn PVC 1</summary>

```yaml
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: test-longhorn-1
spec:
  storageClassName: kubevirt-longhorn
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1G
---
apiVersion: v1 
kind: Pod 
metadata:
  name: test-longhorn-1
spec:
  containers:
  - image: busybox
    name: testpodwithcsi
    command: ["sh", "-c", "while true; do ls -la /opt; echo this file system was made availble using kubevirt-csi-driver; mktmp /opt/test-XXXXXX; sleep 1m; done"]
    imagePullPolicy: Always
    volumeMounts:
    - name: pv0002
      mountPath: "/opt"
  volumes:
  - name: pv0002
    persistentVolumeClaim:
      claimName: test-longhorn-1
```
</details>

<details>
<summary>Longorhn PVC 2</summary>

```yaml
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: test-longhorn-2
spec:
  storageClassName: kubevirt-longhorn
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1G
---
apiVersion: v1 
kind: Pod 
metadata:
  name: test-longhorn-2
spec:
  containers:
  - image: busybox
    name: testpodwithcsi
    command: ["sh", "-c", "while true; do ls -la /opt; echo this file system was made availble using kubevirt-csi-driver; mktmp /opt/test-XXXXXX; sleep 1m; done"]
    imagePullPolicy: Always
    volumeMounts:
    - name: pv0002
      mountPath: "/opt"
  volumes:
  - name: pv0002
    persistentVolumeClaim:
      claimName: test-longhorn-2
```
</details>

<details>
<summary>NFS PVC 1</summary>

```yaml
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: test-nfs-1
spec:
  storageClassName: kubevirt-nfs
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1G
---
apiVersion: v1 
kind: Pod 
metadata:
  name: test-nfs-1
spec:
  containers:
  - image: busybox
    name: testpodwithcsi
    command: ["sh", "-c", "while true; do ls -la /opt; echo this file system was made availble using kubevirt-csi-driver; mktmp /opt/test-XXXXXX; sleep 1m; done"]
    imagePullPolicy: Always
    volumeMounts:
    - name: pv0002
      mountPath: "/opt"
  volumes:
  - name: pv0002
    persistentVolumeClaim:
      claimName: test-nfs-1
```
</details>

<details>
<summary>NFS PVC 2</summary>

```yaml
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: test-nfs-2
spec:
  storageClassName: kubevirt-nfs
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1G
---
apiVersion: v1 
kind: Pod 
metadata:
  name: test-nfs-2
spec:
  containers:
  - image: busybox
    name: testpodwithcsi
    command: ["sh", "-c", "while true; do ls -la /opt; echo this file system was made availble using kubevirt-csi-driver; mktmp /opt/test-XXXXXX; sleep 1m; done"]
    imagePullPolicy: Always
    volumeMounts:
    - name: pv0002
      mountPath: "/opt"
  volumes:
  - name: pv0002
    persistentVolumeClaim:
      claimName: test-nfs-2
```
</details>

After applying the above I can see the following mountinfo details in the hp container (hp container restarts after a new pvc is added so you can see one mountpoint at the time):

Longhorn PVC 1
````
...
Major = {int} 8
Minor = {int} 5
Root = {string} "/var/lib/docker/volumes/5ca2bb9039ab2655d5e4d33350c6445519ec2d334c6ce0cbc3983a4bba613a37/_data/local-path-provisioner/pvc-1baee64d-2744-4a21-b438-23592e6d4e0b_cluster-zf6lqmsfrv_pvc-f59c6740-db6a-45ae-93fc-d4cbe9ee2cb9" 
Mountpoint = {string} "/pvc-f59c6740-db6a-45ae-93fc-d4cbe9ee2cb9"
...
````

Longhorn PVC 2
````
...
Major = {int} 8
Minor = {int} 5
Root = {string} "/var/lib/docker/volumes/5ca2bb9039ab2655d5e4d33350c6445519ec2d334c6ce0cbc3983a4bba613a37/_data/local-path-provisioner/pvc-9be77631-af2f-4a86-afa9-74d0c2acad90_cluster-zf6lqmsfrv_pvc-4fd93b67-1159-45c1-a1b5-8622030bdb20" 
Mountpoint = {string} "/pvc-4fd93b67-1159-45c1-a1b5-8622030bdb20"
...
````

NFS PVC 1
````
...
Major = {int} 0
Minor = {int} 1697
Root = {string} "/"
Mountpoint = {string} "/pvc-5c014f0a-265c-4c42-b939-1dae04c0399c"
...
````

NFS PVC 2
````
...
Major = {int} 0
Minor = {int} 1697
Root = {string} "/"
Mountpoint = {string} "/pvc-84d0cc09-a34d-4295-9f65-a9dc5bd20138"
...
````

As you can observe the root path and device number (Major, Minor) is the same for NFS PVCs, as the result the function `parentMountInfoFor`   will return multiple mount point candidates including mount points of different PVCs that leads to error after.

When this happens virt-handler logs incorrect path for NFS PVC 2 (pvc-84d0cc09-a34d-4295-9f65-a9dc5bd20138), it returns a mount point of NFS PVC 1 (pvc-5c014f0a-265c-4c42-b939-1dae04c0399c) as the function decides which mountpoint it should return based on the path length.

```
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance cluster-zf6lqmsfrv/musing-boyd-5c7478bc87-dmgv5","pos":"vm.go:1474","reason":"failed to mount filesystem hotplug volume pvc-84d0cc09-a34d-4295-9f65-a9dc5bd20138: lstat /proc/1/root/var/lib/kubelet/pods/1c8ccc09-d642-4669-8b4a-995be9f81158/volumes/kubernetes.io~empty-dir/hotplug-disks/pvc-5c014f0a-265c-4c42-b939-1dae04c0399c.img/disk.img: not a directory","timestamp":"2023-03-15T13:18:14.083879Z"}
```

**What you expected to happen**:
Appropriate mount point paths should be returned for PVCs that have the same root and device number.

**How to reproduce it (as minimally and precisely as possible)**:
Run nfs server with https://github.com/kubernetes-csi/csi-driver-nfs, deploy the above PVCs and hotplug them to VM.

I faced the issue with Kubermatic and hotplug was done by the kubevirt csi driver but it should be the same behaviour if you hotplug the volumes over virtctl.

**Additional context**:
Related to https://github.com/kubevirt/kubevirt/pull/5108

**Environment**:
- KubeVirt version (use `virtctl version`): I used master branch to recreate the issue but all versions are affected after merge of [5108](https://github.com/kubevirt/kubevirt/pull/5108) PR 
- Kubernetes version (use `kubectl version`): Client Version: v1.25.3, Server Version: v1.25.6
- VM or VMI specifications: 
<details>

````yaml

apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  creationTimestamp: "2023-03-15T12:24:38Z"
  finalizers:
  - kubevirt.io/virtualMachineControllerFinalize
  - foregroundDeleteVirtualMachine
  generation: 46
  labels:
    cluster.x-k8s.io/cluster-name: zf6lqmsfrv
    cluster.x-k8s.io/role: worker
    kubevirt.io/nodeName: user-worker
    kubevirt.io/vm: musing-boyd-5c7478bc87-dmgv5
    md: musing-boyd
  name: musing-boyd-5c7478bc87-dmgv5
  namespace: cluster-zf6lqmsfrv
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: musing-boyd-5c7478bc87-dmgv5
    uid: daffc691-420e-4031-bc8b-c86587e11d39
  resourceVersion: "63146"
  uid: 4a21dd4a-cc50-45af-965e-3d172d09e5d8
spec:
  affinity: {}
  dnsConfig:
    nameservers:
    - 8.8.8.8
  dnsPolicy: None
  domain:
    cpu:
      cores: 1
      model: host-model
      sockets: 4
      threads: 1
    devices:
      disks:
      - disk:
          bus: virtio
        name: datavolumedisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      - disk:
          bus: scsi
        name: pvc-f59c6740-db6a-45ae-93fc-d4cbe9ee2cb9
        serial: e233cb71-2d4a-428c-8ee7-259e50506b0e
      - disk:
          bus: scsi
        name: pvc-4fd93b67-1159-45c1-a1b5-8622030bdb20
        serial: b351c379-8a39-446f-a009-34f851226481
      - disk:
          bus: scsi
        name: pvc-5c014f0a-265c-4c42-b939-1dae04c0399c
        serial: 2729caa7-abf2-4290-a07a-e17b96cfcdb1
      - disk:
          bus: scsi
        name: pvc-84d0cc09-a34d-4295-9f65-a9dc5bd20138
        serial: 9e57862d-69f4-4a6d-bab6-7fb34fa918b1
      interfaces:
      - bridge: {}
        macAddress: 4a:90:6d:ba:8b:59
        name: default
    features:
      acpi:
        enabled: true
    firmware:
      uuid: e0e24b2b-ac89-5dd6-8553-60e1a69d4c96
    machine:
      type: q35
    resources:
      limits:
        cpu: "4"
        memory: 8192M
      requests:
        cpu: "4"
        memory: 8192M
  evictionStrategy: External
  networks:
  - name: default
    pod: {}
  terminationGracePeriodSeconds: 30
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        md: musing-boyd
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
  volumes:
  - dataVolume:
      name: musing-boyd-5c7478bc87-dmgv5
    name: datavolumedisk
  - cloudInitNoCloud:
      secretRef:
        name: userdata-musing-boyd-5c7478bc87-dmgv5-1678883064
    name: cloudinitdisk
  - dataVolume:
      hotpluggable: true
      name: pvc-f59c6740-db6a-45ae-93fc-d4cbe9ee2cb9
    name: pvc-f59c6740-db6a-45ae-93fc-d4cbe9ee2cb9
  - dataVolume:
      hotpluggable: true
      name: pvc-4fd93b67-1159-45c1-a1b5-8622030bdb20
    name: pvc-4fd93b67-1159-45c1-a1b5-8622030bdb20
  - dataVolume:
      hotpluggable: true
      name: pvc-5c014f0a-265c-4c42-b939-1dae04c0399c
    name: pvc-5c014f0a-265c-4c42-b939-1dae04c0399c
  - dataVolume:
      hotpluggable: true
      name: pvc-84d0cc09-a34d-4295-9f65-a9dc5bd20138
    name: pvc-84d0cc09-a34d-4295-9f65-a9dc5bd20138
status:
  activePods:
    1c8ccc09-d642-4669-8b4a-995be9f81158: user-worker
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-15T12:24:38Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'cannot migrate VMI: PVC musing-boyd-5c7478bc87-dmgv5 is not shared,
      live migration requires that all PVCs must be shared (using ReadWriteMany access
      mode)'
    reason: DisksNotLiveMigratable
    status: "False"
    type: LiveMigratable
  - lastProbeTime: "2023-03-15T12:24:46Z"
    lastTransitionTime: null
    status: "True"
    type: AgentConnected
  - lastProbeTime: null
    lastTransitionTime: "2023-03-15T13:06:54Z"
    message: 'failed to mount filesystem hotplug volume pvc-84d0cc09-a34d-4295-9f65-a9dc5bd20138:
      lstat /proc/1/root/var/lib/kubelet/pods/1c8ccc09-d642-4669-8b4a-995be9f81158/volumes/kubernetes.io~empty-dir/hotplug-disks/pvc-5c014f0a-265c-4c42-b939-1dae04c0399c.img/disk.img:
      not a directory'
    reason: Synchronizing with the Domain failed.
    status: "False"
    type: Synchronized
  guestOSInfo:
    id: centos
    kernelRelease: 3.10.0-1127.el7.x86_64
    kernelVersion: '#1 SMP Tue Mar 31 23:36:51 UTC 2020'
    name: CentOS Linux
    prettyName: CentOS Linux 7 (Core)
    version: "7"
    versionId: "7"
  interfaces:
  - infoSource: domain, guest-agent
    interfaceName: eth0
    ipAddress: 10.244.1.35
    ipAddresses:
    - 10.244.1.35
    - fe80::4890:6dff:feba:8b59
    mac: 4a:90:6d:ba:8b:59
    name: default
    queueCount: 1
  - infoSource: guest-agent
    interfaceName: dummy0
    mac: 3a:9b:a2:6d:ba:46
  - infoSource: guest-agent
    interfaceName: nodelocaldns
    ipAddress: 169.254.20.10
    ipAddresses:
    - 169.254.20.10
    mac: fe:79:5a:c8:eb:10
  - infoSource: guest-agent
    interfaceName: kube-ipvs0
    ipAddress: 10.241.8.207
    ipAddresses:
    - 10.241.8.207
    - 10.241.2.74
    - 10.241.0.1
    - 10.241.0.10
    mac: d6:ec:22:4e:67:82
  - infoSource: guest-agent
    interfaceName: flannel.1
    ipAddress: 172.26.0.0
    ipAddresses:
    - 172.26.0.0
    - fe80::3c1a:5aff:fe6c:68e9
    mac: 3e:1a:5a:6c:68:e9
  - infoSource: domain, guest-agent
    interfaceName: cali10c25dcf845
    ipAddress: fe80::ecee:eeff:feee:eeee
    ipAddresses:
    - fe80::ecee:eeff:feee:eeee
    mac: ee:ee:ee:ee:ee:ee
  launcherContainerImageVersion: docker.io/mfranczy/virt-launcher:debug13
  migrationMethod: BlockMigration
  migrationTransport: Unix
  nodeName: user-worker
  phase: Running
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2023-03-15T12:24:38Z"
  - phase: Scheduling
    phaseTransitionTimestamp: "2023-03-15T12:24:38Z"
  - phase: Scheduled
    phaseTransitionTimestamp: "2023-03-15T12:24:38Z"
  - phase: Running
    phaseTransitionTimestamp: "2023-03-15T12:24:41Z"
  qosClass: Guaranteed
  runtimeUser: 107
  selinuxContext: none
  virtualMachineRevisionName: revision-start-vm-daffc691-420e-4031-bc8b-c86587e11d39-1
  volumeStatus:
  - name: cloudinitdisk
    size: 1048576
    target: vdb
  - name: datavolumedisk
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 10G
      filesystemOverhead: "0.055"
      requests:
        storage: 10G
      volumeMode: Filesystem
    target: vda
  - hotplugVolume:
      attachPodName: hp-volume-fx5h2
      attachPodUID: 2819eea9-9f83-470d-84a7-5ab3b7b00959
    message: Successfully attach hotplugged volume pvc-4fd93b67-1159-45c1-a1b5-8622030bdb20
      to VM
    name: pvc-4fd93b67-1159-45c1-a1b5-8622030bdb20
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: "1073741824"
      filesystemOverhead: "0.055"
      requests:
        storage: "1073741824"
      volumeMode: Filesystem
    phase: Ready
    reason: VolumeReady
    target: sdb
  - hotplugVolume:
      attachPodName: hp-volume-fx5h2
      attachPodUID: 2819eea9-9f83-470d-84a7-5ab3b7b00959
    message: Successfully attach hotplugged volume pvc-5c014f0a-265c-4c42-b939-1dae04c0399c
      to VM
    name: pvc-5c014f0a-265c-4c42-b939-1dae04c0399c
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 1Gi
      filesystemOverhead: "0.055"
      requests:
        storage: "1073741824"
      volumeMode: Filesystem
    phase: Ready
    reason: VolumeReady
    target: sdc
  - hotplugVolume:
      attachPodName: hp-volume-fx5h2
      attachPodUID: 2819eea9-9f83-470d-84a7-5ab3b7b00959
    message: Created hotplug attachment pod hp-volume-fx5h2, for volume pvc-84d0cc09-a34d-4295-9f65-a9dc5bd20138
    name: pvc-84d0cc09-a34d-4295-9f65-a9dc5bd20138
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 1Gi
      filesystemOverhead: "0.055"
      requests:
        storage: "1073741824"
      volumeMode: Filesystem
    phase: AttachedToNode
    reason: SuccessfulCreate
    target: ""
  - hotplugVolume:
      attachPodName: hp-volume-fx5h2
      attachPodUID: 2819eea9-9f83-470d-84a7-5ab3b7b00959
    message: Successfully attach hotplugged volume pvc-f59c6740-db6a-45ae-93fc-d4cbe9ee2cb9
      to VM
    name: pvc-f59c6740-db6a-45ae-93fc-d4cbe9ee2cb9
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: "1073741824"
      filesystemOverhead: "0.055"
      requests:
        storage: "1073741824"
      volumeMode: Filesystem
    phase: Ready
    reason: VolumeReady
    target: sda


````

</details>

- Cloud provider or hardware configuration: kind cluster with Kubermatic (KubeVirt VMs as tenant worker nodes scenario)
- OS (e.g. from /etc/os-release): Ubuntu 21.10
- Kernel (e.g. `uname -a`): 5.4.0-144-generic
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by mfranczy**
**What this PR does / why we need it**:
Allows to find mount points on a node by PV name in case there are multiple mount points returned.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9437 

**Special notes for your reviewer**:

**Release note**:

```release-note
Select mount point for hot pluggable volumes by additional PV name match
```

### CODE REVIEW

**Comment by mfranczy** [comment]
Looks like the failing tests are not related to the PR.

**Comment by alicefr** [comment]
@mfranczy  do you mind adding a functional test in the hotplug suite that recreates the situation described in https://github.com/kubevirt/kubevirt/issues/9437 ?

**Comment by alicefr** [comment]
@mfranczy I'm not quite sure about the reason for adding the pv information to the VMI status? Is it for storing the information somewhere?

**Comment by mfranczy** [comment]
hey @alicefr, the reason is describe in the issue https://github.com/kubevirt/kubevirt/issues/9437

**Comment by mfranczy** [comment]
> @mfranczy do you mind adding a functional test in the hotplug suite that recreates the situation described in https://github.com/kubevirt/kubevirt/issues/9437 ?

If CI provides NFS server then I think I can do it.

**Comment by alicefr** [comment]
> > @mfranczy do you mind adding a functional test in the hotplug suite that recreates the situation described in #9437 ?
> 
> If CI provides NFS server then I think I can do it.

Even if it doesn't, it can be useful to have a functional test that add, remove and readd a PVC with the same name.

**Comment by mfranczy** [comment]
> Even if it doesn't, it can be useful to have a functional test that add, remove and readd a PVC with the same name.

Hm, I am not sure if I follow. The PR fixes the issue when there are mutliple different PVCs with the same root of mountpoints. I don't get how adding, removing and readding the same PVC will test the issue? Could you elaborate? Thanks.

**Comment by xpivarc** [comment]
> > @mfranczy do you mind adding a functional test in the hotplug suite that recreates the situation described in #9437 ?
> 
> If CI provides NFS server then I think I can do it.

We do have nfs-csi. You need to enable `KUBEVIRT_DEPLOY_NFS_CSI`

**Comment by alicefr** [comment]
> > Even if it doesn't, it can be useful to have a functional test that add, remove and readd a PVC with the same name.
> 
> Hm, I am not sure if I follow. The PR fixes the issue when there are mutliple different PVCs with the same root of mountpoints. I don't get how adding, removing and readding the same PVC will test the issue? Could you elaborate? Thanks.

Yes, sorry you are right. I have read the issue wrongly. Still, if you manage to add a functional test with NFS, it will be useful.

**Comment by mfranczy** [comment]
> We do have nfs-csi. You need to enable KUBEVIRT_DEPLOY_NFS_CSI

Ok then I think it should not be a problem to add functional tests that check this.

>  Yes, sorry you are right. I have read the issue wrongly. Still, if you manage to add a functional test with NFS, it will be useful.

No worries. Sure I will add.

**Comment by mfranczy** [comment]
hey @alicefr, sorry for the delay with this PR, currently I am on parental leave. Once I am back i will finish it.

**Comment by alicefr** [comment]
@mfranczy no worry, just ping me when you are ready for a second round for review

**Comment by mfranczy** [comment]
@alicefr appropriate tests already exist, so I extended those with fs storage class (NFS in that case by looking at [the config](https://github.com/kubevirt/kubevirt/blob/main/tests/default-ceph-config.json))

**Comment by mfranczy** [comment]
Looks like my tests changes broke them, I didn't have enough resources to test the change locally. Will try to figure out what's wrong.

**Comment by mfranczy** [comment]
I found out why tests didn't pass. However, I see the issue has been solved by https://github.com/kubevirt/kubevirt/pull/9591 with different approach.

**Pull request closed without merging**
