### PR TITLE
Fix stdci configuration for the project

### PR DESCRIPTION
**Pull request by danielBelenky**
Signed-off-by: Daniel Belenky <dbelenky@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by danielBelenky** [comment]
ci test please

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by rmohr** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by rmohr** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
@danielBelenky I see this tracebacks
```
15:46:30 [check-patch.k8s-1.10.3-dev.el7.x86_64] Traceback (most recent call last):
15:46:30 [check-patch.k8s-1.10.3-dev.el7.x86_64]   File "/home/jenkins/workspace/kubevirt_kubevirt_standard-check-pr/jenkins/scripts/usrc.py", line 11, in <module>
15:46:30 [check-patch.k8s-1.10.3-dev.el7.x86_64]     import yaml
15:46:30 [check-patch.k8s-1.10.3-dev.el7.x86_64] ImportError: No module named yaml
```

**Comment by ifireball** [comment]
@cynepco3hahue  yeah, we already fixed that

**Comment by ifireball** [comment]
ci test please

**Comment by rmohr** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by rmohr** [comment]
Going to merge this one once the  tests look reasonable, in order to see what happens when all our PRs trigger full runs in standardci.

**Comment by rmohr** [comment]
ci test please

**Pull request merged**
