### PR TITLE
Remove phoracek from network reviewers

### PR DESCRIPTION
**Pull request by phoracek**
I'm not reviewing PRs assigned to me.

### What this PR does
Before this PR: phoracek was assigned as a reviewer to network PRs.

After this PR: phoracek is no longer assigned.

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [x] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [x] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by EdDev — APPROVED** [review]

**Comment by dhiller** [comment]
:stop_sign: please refrain from manual retesting.

:warning: this PR is being held to stop automatic retesting. Quarantine PR https://github.com/kubevirt/kubevirt/pull/11244 is given priority.

/hold

**Comment by oshoval** [comment]
seems the 
SKIP_PATTERN="^(docs/)|(OWNERS|OWNERS_ALIASES|.*\.(md|txt))$"
didnt work here well

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11246/pull-kubevirt-e2e-k8s-1.29-ipv6-sig-network/1757736377035788288

**Comment by fabiand** [comment]
I think it did, but this PR was (I asume) part of a batch which touched another file:

```
+ CI_GIT_ALL_CHANGES='OWNERS_ALIASES
pkg/virt-handler/dmetrics-manager/dmetrics-manager.go'
```

Check this pre-submit
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11246/pull-kubevirt-e2e-k8s-1.29-sig-network/1757729400150822912/build-log.txt

it ended early.

**Comment by oshoval** [comment]
> I think it did, but this PR was (I asume) part of a batch which touched another file:
> 
> ```
> + CI_GIT_ALL_CHANGES='OWNERS_ALIASES
> pkg/virt-handler/dmetrics-manager/dmetrics-manager.go'
> ```
> 

It ain't a batch i think in this case, maybe it is a race if `pkg/virt-handler/dmetrics-manager/dmetrics-manager.go`
was merged between starting the job and running the command 
anyhow if we find why in the future we can improve, thanks

> Check this pre-submit https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11246/pull-kubevirt-e2e-k8s-1.29-sig-network/1757729400150822912/build-log.txt
> 
> it ended early.

Right

**Comment by AlonaKaplan** [comment]
/hold
please merge those 2 PR is your one -
https://github.com/kubevirt/kubevirt/pull/11255
https://github.com/kubevirt/kubevirt/pull/11257

**Comment by phoracek** [comment]
Closed in favor of https://github.com/kubevirt/kubevirt/pull/11258

**Pull request closed without merging**
