### PR TITLE
e2e,compute: Quarantine very flaky usb redir test

### PR DESCRIPTION
**Pull request by brianmcarey**
### What this PR does

This test is causing a lot of impact and leading to PRs getting stuck in the merge queue. It more than qualifies for quarantining[1]

[1] https://search.ci.kubevirt.io/?search=with+usbredir+support+Should+work+several+times&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

/cc @dhiller @xpivarc @victortoso 

This is blocking up the merge queue a bit so it would be good to get this in as soon as possible. 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
Related PR: https://github.com/kubevirt/kubevirt/pull/12977

**Comment by fossedihelm** [comment]
> Related PR: #12977

Ops, different test

**Comment by victortoso** [comment]
Should probably apply to the other two tests too for now.

**Comment by brianmcarey** [comment]
> Should probably apply to the other two tests too for now.

I haven't seen them failing that much but if you think it is best, I can add it to the other two?

**Comment by brianmcarey** [comment]
> Should probably apply to the other two tests too for now.

Applied it to the three tests - https://github.com/kubevirt/kubevirt/compare/000f353e1c0574136527360f457d42466ebce7b8..7a28a3390dec09b15815be22be395161ea728dc9

**Comment by victortoso** [comment]
> I haven't seen them failing that much but if you think it is best, I can add it to the other two?

Yes. One of them I actually removed with https://github.com/kubevirt/kubevirt/pull/12977/commits/222b245a2aa18674cec8db20594bf770673bb33c

I just triggered the CI with a quick possible fix... let's see:
https://github.com/kubevirt/kubevirt/pull/12977/commits/b09174a0b6f2be61727bf73b9d4ac316ccad7290

Feel free to quarantine them anyway till we are sure they work as expected. Sorry for the delay on fixing this.

**Comment by brianmcarey** [comment]
> ee to quarantine them anyway till we are sure they work as expected. Sorry for the delay on fixing this.

Thanks @victortoso   - can you add an lgtm if you are happy?

**Comment by brianmcarey** [comment]
/override pull-kubevirt-fossa 

Not related to this PR.

**Comment by brianmcarey** [comment]
/override pull-kubevirt-e2e-k8s-1.31-sig-storage 

Not related to this change

**Pull request merged**
