### PR TITLE
Removal of VM rename

### PR DESCRIPTION
**Pull request by omeryahud**
We came to the conclusion that we don't want the rename functionality
as it contradicts core k8s principals.

**What this PR does / why we need it**:
The VM Rename feature has caused several issues, for example:
- https://bugzilla.redhat.com/show_bug.cgi?id=1954014
- https://bugzilla.redhat.com/show_bug.cgi?id=1954017

And because it contradicts with core principals of k8s, we decided to drop it completely.

**Which issue(s) this PR fixes**:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1954014
Fixes  https://bugzilla.redhat.com/show_bug.cgi?id=1954017

**Release note**:

```release-note
virtctl rename support is dropped
```

### CODE REVIEW

**Comment by rmohr** [comment]
> We came to the conclusion that we don't want the rename functionality
> as it contradicts core k8s principals.

Great to hear that :)

**Comment by rmohr** [comment]
@omeryahud 

```
/tmp/cache/bazel/6f347497f91c9a385dcd9294645b76e0/sandbox/processwrapper-sandbox/1467/execroot/__main__/staging/src/kubevirt.io/client-go/kubecli/vm_test.go:198:74: undefined: "kubevirt.io/client-go/api/v1".RenameOptions
```

seems like there are still some traces left.

**Review by davidvossel — COMMENTED** [review]
/approve

i'm giving this a preemptive approve. looks really close, and I want this out asap. 

run something like this command below in order to make sure all references are removed. 

```grep -r -n -i rename pkg/* hack/* tests/* staging/*```

**Pull request merged**
