### PR TITLE
[DO NOT MERGE] Create basic RBAC permissions for KubeVirt

### LINKED ISSUE #299: Version to use
Which version of kubernetes the master branch compliant to? I am running kubernetes cluster via kubeadm and the steps doesn't work with either stable or latest versions. Now I am back at using Kubernetes 1.5.6 version but virt-controller and virt-handler throws these errors.

kubectl logs -f virt-handler-6793p
E0707 13:42:27.509285       1 reflector.go:201] kubevirt.io/kubevirt/pkg/kubecli/controller.go:167: Failed to list *v1.VM: User "system:serviceaccount:default:default" cannot list vms.kubevirt.io in the namespace "default". (get vms.kubevirt.io)

kubectl logs -f virt-controller-3230119827-jjz1z
E0707 11:58:42.154691       1 reflector.go:201] kubevirt.io/kubevirt/pkg/informers/virtinformers.go:90: Failed to list *v1.VM: User "system:serviceaccount:default:default" cannot list vms.kubevirt.io in the namespace "default". (get vms.kubevirt.io)

virsh list doesn't list any VMs. Althought kubectl get vms show test testvm, but there isn't a pod created.

### PR DESCRIPTION
**Pull request by rmohr**
Make sure that KubeVirt can run on Kubernetes instances where RBAC is
enabled. Further give the haproxy admin rights right now, to allow it to
forward all calls to the apiserver.

This does not at all provide a more secure way to run KubeVirt. It's
only purpose at this stage is to allow friction-less deployments on
RBAC enabled Kubernetes clusters.

The depolyment can be properly secured, as soon as we have movedm from
our haproxy approach to the Aggregated API Server.

Fixes #299, #62 and does some initial work for #301.

Signed-off-by: Roman Mohr <rmohr@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
Something is still not completely right. Don't merge yet!

**Comment by davidvossel** [comment]
any more word on this?

I think it's really important that we start working with RBAC now for each of our components.

With RBAC limited to exactly what each component consumes, it means we have to be explicit about any new capabilities that are being added to a component. This will make it obvious when we try to give a component access to cluster capabilities it really shouldn't have access to.

**Comment by rmohr** [comment]
Ok, so the latest state on this is, that everything works when starting VMs, ... by hand. However functional tests  currently don't start because of a permission error. Will look into it as soon as I can. But someone  else can pick it up too. Also @admiyo confirmed that he could practically unchanged use this PR on OpenShift during his investigations.

**Comment by fabiand** [comment]
@rmohr if you don#t mind then I'd update this PR

**Comment by rmohr** [comment]
Please go ahead. That would be great.

**Comment by fabiand** [comment]
Obsoleted by #418.

Closing this one.

**Pull request closed without merging**
