### PR TITLE
fix tiny typo

### PR DESCRIPTION
**Pull request by dankenigsberg**
Signed-off-by: Dan Kenigsberg <danken@redhat.com>

```release-note
NONE
```

### CODE REVIEW

**Comment by dankenigsberg** [comment]
One of the failures now is
```  [rfe_id:2291][crit:high][vendor:cnv-qe@redhat.com][level:component]infrastructure management
  /root/go/src/kubevirt.io/kubevirt/tests/operator_test.go:840
    [test_id:3149]should be able to create kubevirt install with image prefix
    /root/go/src/kubevirt.io/kubevirt/tests/operator_test.go:939
------------------------------
• Failure [533.702 seconds]
Operator
/root/go/src/kubevirt.io/kubevirt/tests/operator_test.go:56
  [rfe_id:2291][crit:high][vendor:cnv-qe@redhat.com][level:component]infrastructure management
  /root/go/src/kubevirt.io/kubevirt/tests/operator_test.go:840
    [test_id:3150]should be able to update kubevirt install with custom image tag [It]
    /root/go/src/kubevirt.io/kubevirt/tests/operator_test.go:1005
     Timed out after 300.000s.
    Unexpected error:
        <*errors.errorString | 0xc00182aec0>: {
            s: "Waiting for conditions to indicate deployment (conditions: [{Type:Available Status:True LastProbeTime:2020-05-23 11:26:18 +0000 UTC LastTransitionTime:2020-05-23 11:26:18 +0000 UTC Reason:UpdateInProgress Message:Transitioning from previous version devel with registry registry:5000/kubevirt to target version devel_alt using registry registry:5000/kubevirt} {Type:Progressing Status:True LastProbeTime:2020-05-23 11:26:18 +0000 UTC LastTransitionTime:2020-05-23 11:26:18 +0000 UTC Reason:UpdateInProgress Message:Transitioning from previous version devel with registry registry:5000/kubevirt to target version devel_alt using registry registry:5000/kubevirt} {Type:Degraded Status:True LastProbeTime:2020-05-23 11:26:18 +0000 UTC LastTransitionTime:2020-05-23 11:26:18 +0000 UTC Reason:UpdateInProgress Message:Transitioning from previous version devel with registry registry:5000/kubevirt to target version devel_alt using registry registry:5000/kubevirt}])",
```
It is obviously unrelated to this PR, but I think that this test should be improved to give a bit more information for the reason we fail to deploy KubeVirt operator. The assertion should at least collect the status of the KubeVirt cr.

**Comment by dankenigsberg** [comment]
```
• Failure [122.602 seconds]
[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle
/root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:75
  [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating a VirtualMachineInstance
  /root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:97
    when virt-handler is responsive
    /root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:491
      [test_id:1633]should indicate that a node is ready for vmis [It]
      /root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:492
       Timed out after 120.000s.
      Nodes should be schedulable
      Expected
          <string>: false
      to equal
          <string>: true
       /root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:511
```

I see in https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3459/pull-kubevirt-e2e-k8s-1.17/1265054010600067072/artifacts/1_nodes.log that node01 was indeed non-schedulable, but it would require a lot more digging to find out why.

**Comment by dankenigsberg** [comment]
```
[rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking
/root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:50
  Multiple virtual machines connectivity using bridge binding interface
  /root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:115
    with a service matching the vmi exposed
    /root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:301
      [test_id:1547] should be able to reach the vmi based on labels specified on the vmi [It]
      /root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:321
       Expected
          <v1.PodPhase>: Failed
      to equal
          <v1.PodPhase>: Succeeded
       /root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:330
------------------------------
STEP: starting a pod which tries to reach the vmi via the defined service
STEP: waiting for the pod to report a successful connection attempt
{"component":"tests","level":"info","msg":"++ head -n 1\n+++ nc myservice.kubevirt-test-default 1500 -i 3 -w 3\nNcat: Connection timed out.\n+ x=\n+ echo ''\n+ '[' '' = 'Hello World!' ']'\n+ echo failed\n+ exit 1\n\nfailed\n","pos":"vmi_networking_test.go:71","timestamp":"2020-05-27T00:54:44.065079Z"}
```

I fail to find anything of value in the logs https://gcsweb.apps.ovirt.org/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3459/pull-kubevirt-e2e-k8s-1.16/1265414392770465792/artifacts/pods/ which are mostly empty. https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3459/pull-kubevirt-e2e-k8s-1.16/1265414392770465792/artifacts/1_vmis.log shows 4 seemingly-well VMs, one exposed.

https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3459/pull-kubevirt-e2e-k8s-1.16/1265414392770465792/artifacts/pods/1_kubevirt-test-default_netcatv5qbn-netcat.log indeed has `Ncat: Connection timed out.` but I cannot really tell why.

**Comment by rmohr** [comment]
Relevant test results are good. Going to merge some trivial PRs alongside with some stabilization PRs for CI.

**Pull request merged**
