### PR TITLE
fix: resolve critical issue with keyboard input for s390x

### PR DESCRIPTION
**Pull request by nestoracunablanco**
Testers reported that keyboard input was not recognized when attempting to access the VM via VNC. This issue arose because no virtual keyboard was configured for the s390x architecture. This explains why console and SSH access functioned without any problems.

### What this PR does
Before this PR: critical bug when connecting via VNC to s390x guests

After this PR: 

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by Davo911** [comment]
cc: @cfilleke

**Review by lyarwood — APPROVED** [review]
/lgtm

This is pretty straight forward and in line with what we are already doing for `arm64`.

That said `autoAttachGraphicsDevices` is getting abused here with this different behaviour between architectures not actually documented anywhere AFAICT. 

https://kubevirt.io/api-reference/main/definitions.html#_v1_devices
https://kubevirt.io/user-guide/compute/virtual_hardware/#video-and-graphics-device

An alternative would be to change the behaviour of `autoAttachInputDevice` per architecture instead but that could be a follow up?

FWIW it would be super useful if we had `s390x` functional test lanes to catch this stuff :)

**Comment by nestoracunablanco** [comment]
Thank you all for your understanding.

-     Regarding the need for more generic code, I agree that this is worth considering. However, it's important to note that for ARM, the bus type is USB, while for s390x, it is Virtio.
-     As for the functional tests, this error cannot currently be captured, even in tests for other architectures. Nevertheless, we can brainstorm potential solutions. The end-to-end tests I have reviewed for VNC primarily focus on checking the connection.

One final thought: a generic error in QEMU related to input devices could impact virtctl vnc and the console view in the OpenShift dashboard, and as far as I know, we do not currently test for this.

**Pull request merged**
