### PR TITLE
update k8s 1.13.3 multus image to fix ovs image pull error

### PR DESCRIPTION
**Pull request by SchSeba**
**What this PR does / why we need it**:
update k8s 1.13.3 multus image to fix ovs image pull error

**Release note**:

```release-note
none
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/2122)

### CODE REVIEW

**Comment by SchSeba** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
For reference - https://kubevirt-master-stdci-production.apps.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/377//artifact/check-patch.k8s-multus-1.13.3.el7.x86_64/mock_logs/script/stdout_stderr.log

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by booxter** [comment]
This image definitely reduces the number of failures (specifically with ovs-cni tests) so I think it's worth merging. I don't see anything in the list of failures that would specifically link to the image.

**Pull request merged**
