### PR TITLE
virt-launcher, hostdev: Extract hot(un)plug from SR-IOV

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

Extract the hot(un)plug code from the SR-IOV package to allow its usage
by the other hostdevice types.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
/retest

@vladikr , would you have time looking at this PR?

**Review by ormergi — APPROVED** [review]
Thank you! 

I think its worth mentioning in the commit message the functions you had to generalize (e.g `FilterHostDevicesByAlias` and `SafelyDetachHostDevices`)
It took few moments to realize it :sweat_smile:

**Comment by enp0s3** [comment]
@EdDev Thank you!
/approve

**Pull request merged**
