### PR TITLE
Add '[Serial]Operator should reconcile components test updating a deployment is reverted to it's original state' test to quarantine

### PR DESCRIPTION
**Pull request by fgimenez**
Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

**What this PR does / why we need it**: This test has started failing a lot since 2021-03-25 18:44 CET, this is flakefinder report https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-03-26-024h.html#row5 (4 errors, 0 success)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
This started to happen only very recently:

https://search.ci.kubevirt.io/?search=Operator+should+reconcile+components+test+updating+a+deployment+is+reverted+to+it%27s+original+state&maxAge=336h&context=1&type=junit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

/cc @ashleyschuett 

would you mind checking if it is related to one of the latest reconcile changes in the operator?

**Comment by acardace** [comment]
I'm seeing this failure too, when running it locally it passes fine but if I simulate some CPU load using cpuburn (say more than 50% load) it starts failing reliably, maybe the timeout should be more generous(?).

**Comment by rmohr** [comment]
> I'm seeing this failure too, when running it locally it passes fine but if I simulate some CPU load using cpuburn (say more than 50% load) it starts failing reliably, maybe the timeout should be more generous(?).

That can very well be. Can you see which components need so long to be reverted?

**Comment by ashleyschuett** [comment]
looking into a solution for this

**Comment by ashleyschuett** [comment]
I think merging the CRD reconciliation PR #5310 caused this issue. The constant updates are making the KV and cache not match and unable to reconcile.  I have created PR #5310 to revert this PR and think we should wait until @acardace PR #5017 is merged to implement reconciling the CRD.

**Comment by ashleyschuett** [comment]
It looks like this test hasn't failed since the CRD PR was reverted. How long should we wait until closing this? 

https://search.ci.kubevirt.io/?search=Operator+should+reconcile+components+test+updating+a+deployment+is+reverted+to+it%27s+original+state&maxAge=24h&context=1&type=junit&name=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by fgimenez** [comment]
/hold

> It looks like this test hasn't failed since the CRD PR was reverted. How long should we wait until closing this?

awesome, let's put this one on hold for a few days and close it if we don't find any other failure, I'll keep track of it.

**Comment by fgimenez** [comment]
/unhold
/retest

It is still failing https://search.ci.kubevirt.io/?search=Operator+should+reconcile+components+test+updating+a+deployment+is+reverted+to+it%27s+original+state&maxAge=336h&context=1&type=junit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job @nunnatsa is already working on it

**Comment by fgimenez** [comment]
/test pull-kubevirt-e2e-k8s-1.19-sig-storage

The test has failed again yesterday https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5440/pull-kubevirt-e2e-k8s-1.19-operator/1381898759792758784

**Comment by erkanerol** [comment]
I think this PR can solve the problem in this test. #5458

**Comment by fgimenez** [comment]
The test keeps failing, I'll close this PR and add it to a new batch.

**Pull request closed without merging**
