### PR TITLE
fix bug:failed when using block mode pvc for hotplug

### PR DESCRIPTION
**Pull request by zhangziren1988**
**What this PR does / why we need it**:
fix bug:failed when using block mode pvc for hotplug

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by maiqueb — COMMENTED** [review]
I think this is OK, whoever, I am not versed in storage; @awels / @maya-r does this look good to you ? 

@zhangziren1988 please note https://github.com/kubevirt/kubevirt/pull/4955#issuecomment-772334168; you need to ammend you commit w/ the `-s' flag.

**Comment by zhangziren1988** [comment]
I have corrected the dco problem，could you please tag lgtm again？thank you @awels / @maya-r

**Comment by maya-r** [comment]
I think the PR should first be done to master, so it is available on all future releases, and only then backported to a release

**Comment by maiqueb** [comment]
> (Sorry didn't notice this at first) I think the PR should first be done to master, so it is available on all future releases, and only then backported to a release

+1 - I also didn't note this was a PR sent to the release.

**Comment by maya-r** [comment]
/close
done in kubevitr#5422

**Comment by maya-r** [comment]
also: if you want to see it in a given release, please try replying with "/cherry-pick branch-name' in the merged pr.

**Pull request closed without merging**
