### PR TITLE
Change example video image

### PR DESCRIPTION
**Pull request by benukhanov**
Signed-off-by: Ben Oukhanov <boukhano@redhat.com>

**What this PR does / why we need it**:

IMHO, our example video image is too big and it takes too much space. Let's make it smaller -> [Click](https://github.com/benukhanov/kubevirt/tree/docs/asciinema#introduction) here to see how it looks in the forked repository.

Please let me know if we can remove `Click the image below to see an example video` instruction.

**Special notes for your reviewer**:

If this PR will be declined, then let's make this image as a gif.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
I think it does look better.

**Comment by benukhanov** [comment]
> I think it does look better.

Thanks, do you think we need `Click the image below to see an example video` text instruction or I can remove it?

**Comment by maiqueb** [comment]
> > I think it does look better.
> 
> Thanks, do you think we need `Click the image below to see an example video` text instruction or I can remove it?

I honestly do not mind either.

**Comment by benukhanov** [comment]
> > > I think it does look better.
> > 
> > 
> > Thanks, do you think we need `Click the image below to see an example video` text instruction or I can remove it?
> 
> I honestly do not mind either.

Done, thanks! :)

**Comment by benukhanov** [comment]
Why we need to run tests for small change in readme? :)

**Comment by dankenigsberg** [comment]
> Why we need to run tests for small change in readme? :)

Because nobody wrote the logic to exclude *md files from test lanes (hint hint).

More seriously, the storage lane is still very flakey. I suspect @fgimenez @aglitke are already aware and working to fix it.

**Comment by fgimenez** [comment]
> Because nobody wrote the logic to exclude *md files from test lanes (hint hint).

Indeed, this is a well-known issue with Prow, see https://kubernetes.slack.com/archives/C09QZ4DQB/p1626291051471200 and https://kubernetes.slack.com/archives/CDECRSC5U/p1626296455106400 for context and the reasoning behind not allowing this kind of thing on Prow by default. Maybe some additional logic as Dan suggests even in the job definition might help.

> More seriously, the storage lane is still very flakey. I suspect @fgimenez @aglitke are already aware and working to fix it.

Yes, there is work in progress to improve these lanes. For the time being, only 1.21-sig-storage (the most stable) is required for PRs to be merged. For instance, in this case only an approval by a maintainer is missing, other than that the  1.20-sig-storage lane is not blocking the merge.

**Comment by benukhanov** [comment]
@dankenigsberg Rebased.

**Pull request merged**
