### PR TITLE
Move Zvi to emeritus approvers

### PR DESCRIPTION
**Pull request by zcahana**
**What this PR does / why we need it**:

Since I've left my job at IBM, I expect to have much less time to invest in the KubeVirt project.
Therefore I feel it's better to step down from my approver role.

I hope to remain involved to some extent, as much as time permits.
And either way I definitely stick around, so feel free to tag me here or on Slack if anything relevant comes up.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by dankenigsberg** [comment]
Take care, @zcahana .

**Review by dankenigsberg — APPROVED** [review]

**Comment by rmohr** [comment]
/approve

thanks @zcahana for your great work and insights! Good luck.

**Pull request merged**
