### PR TITLE
Make build basesystem configurable

### PR DESCRIPTION
**Pull request by VirrageS**
**What this PR does / why we need it**: When using custom rpm server it is often needed to configure basesystem. Therefore, we can do that using env variable as we also do with other values.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: None

**Special notes for your reviewer**: None

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alicefr** [comment]
@VirrageS do you think it make sense to add this information to the [custom-rpm guide](https://github.com/kubevirt/kubevirt/blob/main/docs/custom-rpms.md)? If so, would you mind adding a couple of lines to explain the variable and how to use it?

**Comment by VirrageS** [comment]
Good idea! I will try to do that soon :)

**Pull request merged**
