### PR TITLE
[release-0.36] add webhook to validate kubevirt CR updates

### PR DESCRIPTION
**Pull request by ashleyschuett**
**What this PR does / why we need it**:

Cherry pick of bug fix https://github.com/kubevirt/kubevirt/pull/4599

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1895414

**Special notes for your reviewer**:

**Release note**:
-->
```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — COMMENTED** [review]
/approve

can you look at the failures on the lane [here](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4619/pull-kubevirt-e2e-k8s-1.19/1334416558121816065) and confirm that these are caused by a temporary cluster glitch?

**Comment by davidvossel** [comment]
shouldn't this specific webhook be in the virt-operator component.  I feel uneasy having an operand CRD validated by the infrastructure installed by the operand. This creates a dependency where the operand's infrastucture can actually block the operator from proceeding in the event that the webhook is down.

I'm not 100% sure this will work in the uninstall case, where we're taking KubeVirt down. Depending on the order in which the webhook is unregistered and virt-api is removed, we could be in a situation where updates can no longer occur on the KubeVirt cr.

**Comment by davidvossel** [comment]
> I'm not 100% sure this will work in the uninstall case, where we're taking KubeVirt down. Depending on the order in which the webhook is unregistered and virt-api is removed, we could be in a situation where updates can no longer occur on the KubeVirt cr.

uninstall likely works given the uninstall functional tests work... I'm still uneasy about this PR from an architecture standpoint. It crosses boundaries by having the operands infra validate the top level operator's CRD.

**Comment by ashleyschuett** [comment]
> uninstall likely works given the uninstall functional tests work... I'm still uneasy about this PR from an architecture standpoint. It crosses boundaries by having the operands infra validate the top level operator's CRD.

I agree, this was an over-site on my part. This functionality should belong to the operator validation webhook configuration. I have updated it in this PR on master https://github.com/kubevirt/kubevirt/pull/4644 and will then cherry-pick it back to the release branch.

**Review by dhiller — APPROVED** [review]
/lgtm

**Pull request merged**
