### PR TITLE
wrong apiVersion used for VirtualMachineRestore owner references

### PR DESCRIPTION
**Pull request by mhenriks**
interestengly, only an issue on ocp

Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

**What this PR does / why we need it**:

Issue discovered in OCP testing.  Interesting wasn't an issue upstream.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
@mhenriks what exactly happened on ocp with the wrong owner reference?

**Comment by mhenriks** [comment]
> @mhenriks what exactly happened on ocp with the wrong owner reference?

Couldn't update the resource with bogus owner reference.

**Pull request merged**
