### PR TITLE
Updating k8s to v0.21.4

### PR DESCRIPTION
**Pull request by visheshtanksale**
Signed-off-by: Vishesh Ajay Tanksale <vtanksale@apple.com>

**What this PR does / why we need it**:
Updating k8s dependencies to v0.21.4

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Updated k8s dependencies to v0.21.4
```

### CODE REVIEW

**Comment by rmohr** [comment]
It did not like the quay outage.

/test all

**Comment by visheshtanksale** [comment]
Quay looks green yet tests failing with quay dns error

/test all

**Comment by rmohr** [comment]
@visheshtanksale I think the failing tests are an indicator for an incompatibility. This error

```
unexpected error event: an error on the server ("unable to decode an event from the watch stream: http2: response body closed") has prevented the request from succeeding
```

is probably due to some changes in the k8s core libaries.

**Comment by visheshtanksale** [comment]
@rmohr The error is being thrown when the tests are waiting for certain events [here](https://github.com/kubevirt/kubevirt/blob/126fc4a26e02f47c069d7becfd86acaca138df66/tests/utils.go#L384). It failing intermittently for the tests. I am not sure why is this happening and how is it related to the k8s upgrade. Looking further.

**Comment by rmohr** [comment]
> @rmohr The error is being thrown when the tests are waiting for certain events [here](https://github.com/kubevirt/kubevirt/blob/126fc4a26e02f47c069d7becfd86acaca138df66/tests/utils.go#L384). It is failing intermittently for the tests. I am not sure why is this happening and how is it related to the k8s upgrade. Looking further.

Hm, let's see if it was temporary. Thanks for looking.

**Comment by visheshtanksale** [comment]
> > @rmohr The error is being thrown when the tests are waiting for certain events [here](https://github.com/kubevirt/kubevirt/blob/126fc4a26e02f47c069d7becfd86acaca138df66/tests/utils.go#L384). It is failing intermittently for the tests. I am not sure why is this happening and how is it related to the k8s upgrade. Looking further.
> 
> Hm, let's see if it was temporary. Thanks for looking.

It doesn't look like its temporary. It appears intermittently on my setup. Still not sure what's  causing this.

**Comment by fossedihelm** [comment]
@rmohr This PR can be closed because of [https://github.com/kubevirt/kubevirt/pull/7056](https://github.com/kubevirt/kubevirt/pull/7056)

**Pull request closed without merging**
