### PR TITLE
Bump kubevirtci to latest version

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

The automation prow job has an issue, doing a manual bump until I could fix it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
I checked the image for the job, it didn't have the right version. Fixed here: https://github.com/kubevirt/project-infra/pull/1314

**Review by dhiller — APPROVED** [review]
/approve

**Comment by rmohr** [comment]
> I checked the image for the job, it didn't have the right version. Fixed here: [kubevirt/project-infra#1314](https://github.com/kubevirt/project-infra/pull/1314)

thanks :+1:

**Pull request merged**
