### PR TITLE
add genesiscloud to adopters

### PR DESCRIPTION
**Pull request by toelke**
**What this PR does / why we need it**:

As discussed during the project meeting on Tuesday, here is our entry to the adopters list.

```release-note
* Add Genesis Cloud to the adopters list
```

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
Hey @toelke !

Glad to have you onboard .

**Comment by maiqueb** [comment]
You'll need to signoff your git commit.

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
