### PR TITLE
Improve removing traces from old deployments

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Lukianov Artyom <alukiano@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
ok to test

**Comment by davidvossel** [comment]
retest this please

**Comment by davidvossel** [comment]
maybe we should consider using a non-default namespace for all our componenets/services/pvcs/etc...

**Comment by cynepco3hahue** [comment]
@davidvossel I added this PR as temporary fix for the problem under the #558

**Comment by cynepco3hahue** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by cynepco3hahue** [comment]
@rmohr One test failed on timeout
```
Summarizing 1 Failure:

[Timeout...] CloudInit UserData CloudInit Data Source NoCloud [It] should launch VMs with user-data in k8s secret 
/var/lib/jenkins/workspace/kubevirt-functional-tests/go/src/kubevirt.io/kubevirt/tests/vm_userdata_test.go:133

Ran 46 of 48 Specs in 958.535 seconds
FAIL! -- 45 Passed | 1 Failed | 0 Pending | 2 Skipped --- FAIL: TestTests (958.54s)
```

**Comment by rmohr** [comment]
retest this please

**Pull request merged**
