### PR TITLE
Fix qemu-system-* process lookup

### PR DESCRIPTION
**Pull request by vasiliy-ul**
**What this PR does / why we need it**:

- Lookup qemu process by executable prefix
    
  Exact matching with `qemu-system` does not work since the executable name also includes a suffix with current architecture, e.g. qemu-system-x86_64. This leads to errors of type:
    
        no QEMU process found under process 16427 child processes

- Detect the qemu emulator binary in runtime during e2e testing
    
  Avoid hardcoding qemu-kvm since the underlying images may use e.g. qemu-system-*.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vasiliy-ul** [comment]
Hi @brianmcarey, how can I trigger the `realtime` tests in CI on this PR? I do not see presubmits in https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml though there are some in https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml.

**Comment by brianmcarey** [comment]
> Hi @brianmcarey, how can I trigger the `realtime` tests in CI on this PR? I do not see realtime presubmits in https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml though there are some in https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml.

Hi @vasiliy-ul, looks like the lane was removed by accident during the removal of the 1.24 lanes - I will create a PR to add another lane. 
https://github.com/kubevirt/project-infra/pull/2790/files#diff-26f7cd0389085c1da47f919a02c4dbeca5ddd96ca00d8e49c0862f698475aaf9L1236

**Pull request merged**
