### PR TITLE
network, fqdn: Fix subdomain flow

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:

The subdomain was set in the DHCP config under the condition IPv6 enabled.
It is wrong, because the subdomain is not related to IPv6, and need to be
populated even if IPv6 is disabled, so in case it is specified,
the missing search domain will be added as part of IPv4 DHCP server
(which currently used by default, and always exists for masquerade interfaces).

Additional change:

Add missing subdomain unit test.
In case IPAM is enabled on bridge interface,
the subdomain should be propagated by
the bridge generator.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Fixes a problem of https://github.com/kubevirt/kubevirt/pull/6508
In case IPv6 is disable in the cluster, DHCP won't add the missing domain for masquerade interfaces.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by vasiliy-ul** [comment]
Also noticed that bug while working on the PR https://github.com/kubevirt/kubevirt/pull/6958 :

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6958/pull-kubevirt-e2e-k8s-1.20-sig-network/1471446077797306368

Though I could observe the same failure with the Bridge binding as well...

**Comment by oshoval** [comment]
> Also noticed that bug while working on the PR #6958 :
> 
> https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6958/pull-kubevirt-e2e-k8s-1.20-sig-network/1471446077797306368
> 
> Though I could observe the same failure with the Bridge binding as well... I wonder why the masquarade test wasnt failing before.

It is not the same problem imo
the bug this PR fix happens when ipv6 is disabled in the cluster, and is happening in this case always
the code that it fixes is only for masquerade flow (bridge doesn't have conditioning of ipv6)

The flakes you shown are most likely because the dhcp takes some time after the console is ready

**Review by EdDev — COMMENTED** [review]
Looks good, thanks.
I only have a small request to update the first commit message subject:
> fqdn, Fix masquerade flow 

network, fqdn: ....

**Comment by oshoval** [comment]
> Looks good, thanks. I only have a small request to update the first commit message subject:
> 
> > fqdn, Fix masquerade flow
> 
> network, fqdn: ....

Done, thanks

**Comment by oshoval** [comment]
/test pull-kubevirt-build 

quay problems

**Review by EdDev — APPROVED** [review]
Thanks!

**Comment by oshoval** [comment]
/cc @AlonaKaplan 
can you please take a look ?

**Review by AlonaKaplan — APPROVED** [review]
/approve

**Pull request merged**
