### PR TITLE
Publish the vmi create sequence diagram from SIG-scale meeting

### PR DESCRIPTION
**Pull request by rthallisey**

### CODE REVIEW

**Comment by mazzystr** [comment]
@rthallisey Any chance that we can get this converted to an svg so we can modify it easier in the future?

**Comment by rthallisey** [comment]
moved to svg

**Comment by maya-r** [comment]
/release-note-none
@mazzystr it looks like your review comment was answered, does it look good to you?

**Comment by rthallisey** [comment]
@davidvossel this is the picture we created at the beginning of sig-scale.  Do you want to have this in tree?  Otherwise, we should close

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

It might get outdated over time, but this is a pretty great diagram for people to reference. I say we keep it.

**Comment by rthallisey** [comment]
rebased.  Hopefully the tests will pass now

**Pull request merged**
