### PR TITLE
remove [QUARANTINE] tag from test_id:4746

### PR DESCRIPTION
**Pull request by Barakmor1**
Signed-off-by: Barak Mordehai <bmordeha@redhat.com>

**What this PR does / why we need it**:
remove the [QUARANTINE] tag from test_id:4746
due to the test stabilization.
https://github.com/kubevirt/kubevirt/pull/6734
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by fgimenez — APPROVED** [review]
/lgtm

Thanks!

**Review by jean-edouard — COMMENTED** [review]
/approve

**Pull request merged**
