### PR TITLE
[release-0.30] Add test to check kubevirt disk perms

### PR DESCRIPTION
**Pull request by kbidarkar**
Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>

**What this PR does / why we need it**: `Add test to check kubevirt disk perms`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: `Add test to check kubevirt disk perms`

**Release note**:

```
None
```

### CODE REVIEW

**Comment by kbidarkar** [comment]
Backport of #3518

**Comment by rmohr** [comment]
@kbidarkar seems like travis had a hickup. Could you do a push on this PR, so that travis gets triggered again?

**Comment by rmohr** [comment]
@kbidarkar I don't see a reference to the PR on master. Did the cherrypick command not work for you? If no, please still add a reference.

**Comment by rmohr** [comment]
PR is good and waiting for ages already.

**Pull request merged**
