### PR TITLE
Remove template tests

### PR DESCRIPTION
**Pull request by xpivarc**
### What this PR does
Templates are specific to Openshift platform. Unfortunately we lack the infrastructure to test/maintain
these and there is no reason to test Openshift's feature in our project.

This platform specific template mechanism is now replaced by Kubevirt's own opinionated API called
InstanceTypes and Preferences.

Fixes #

Links to places where the discussion took place: 

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
I am favor of reducing e2e tests in general, especially the edge cases and the ones who have little overall value over unit tests.
Said that, it feels that more reasoning is needed here.

> Unfortunately we lack the infrastructure to test/
> maintain these. Therefore let's remove them.

Can you please explain this a little more? Lack of infra due to resources or no setup to execute them?
Is it deprecated?
Is it covered in unit tests at some level?

**Comment by xpivarc** [comment]
@EdDev Updated the description. Let me know if you feel like more is needed to be said.

**Review by EdDev — APPROVED** [review]
Thanks!

**Comment by lyarwood** [comment]
/lgtm

@akrejcir @0xFelix @ksimon1 should we add coverage for this directly in SSP instead?

**Comment by akrejcir** [comment]
> /lgtm
> 
> @akrejcir @0xFelix @ksimon1 should we add coverage for this directly in SSP instead?

I would say no. These tests only check `oc` functionality, that it can apply templates that contain a `VirtualMachine` object.
I assume this is already tested by openshift for any objects.

**Comment by 0xFelix** [comment]
I agree with @akrejcir, let's drop `oc` specific tests from KubeVirt.

**Comment by vladikr** [comment]
+1

/approve

**Pull request merged**
