### PR TITLE
instancetype: Add package to lint Makefile target and fix *some* issues

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

This change adds the pkg/instancetype directory to the lint Makefile target and fixes some identified issues.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lyarwood** [comment]
/cc @0xFelix 

We've spoken offline about this, if you have time a review would be appreciated!

**Review by 0xFelix — APPROVED** [review]
Thanks!

/lgtm
/retest

**Comment by lyarwood** [comment]
/hold

Still looking for review/approval for this PR but I'd like https://github.com/kubevirt/kubevirt/pull/9584 to land first to keep it clean and avoid backporting this change.

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
