### PR TITLE
Support testing kubevirt on RHCOS

### PR DESCRIPTION
**Pull request by danielBelenky**
On RHCOS, the root (/) directory is mounted as read only so when we try
to create a host-disk under root it fails. We should use /var/ instead.

Signed-off-by: Daniel Belenky <dbelenky@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by enp0s3 — APPROVED** [review]
/lgtm

**Comment by jean-edouard** [comment]
/hold
This needs a corresponding fix in kubevirtci, like for example at: https://github.com/kubevirt/kubevirtci/blob/master/cluster-provision/k8s/1.17/provision.sh#L355
It used to be `/tmp` instead of `/provision`, which worked just fine, I never understood the need for switching to a custom root directory...

**Comment by danielBelenky** [comment]
> /hold
> This needs a corresponding fix in kubevirtci, like for example at: https://github.com/kubevirt/kubevirtci/blob/master/cluster-provision/k8s/1.17/provision.sh#L355
> It used to be `/tmp` instead of `/provision`, which worked just fine, I never understood the need for switching to a custom root directory...

Good point. I've created: https://github.com/kubevirt/kubevirtci/pull/436

**Review by jean-edouard — APPROVED** [review]
/hold cancel
/lgtm

**Comment by danielBelenky** [comment]
/hold
I think that there is a problem with this PR. I'll have more details tomorrow.

**Comment by danielBelenky** [comment]
/hold cancel
this one is ready for code-review/merge :smile:

**Review by enp0s3 — APPROVED** [review]
/lgtm

**Pull request merged**
