### PR TITLE
Fix: Set the end featurename with the conventional name with "Gate" word

### PR DESCRIPTION
**Pull request by Davidffry**
### What this PR does
Before this PR: just change the typo to respect the "conventional name" with the Gate word in the end of each feature

After this PR: /

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made: just change the typo to respect the "conventional name" with the Gate word in the end of each feature

The following alternatives were considered: leave it like that

Links to places where the discussion took place: https://github.com/kubevirt/user-guide/pull/780

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ X ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ X ] PR: The PR description is expressive enough and will help future contributors
- [ X] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ X ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ X ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ X ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ X ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note

```

### CODE REVIEW

**Comment by 0xFelix** [comment]
Thanks for the PR. What about `CPUManager` / `CPUManagerGate`?

**Comment by Davidffry** [comment]
Sorry I forget this one. ;) thanks

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by xpivarc** [comment]
@Davidffry please have a look at the failures. you can run `make` locally in order to see what is wrong

**Pull request closed without merging**
