### PR TITLE
Discover server version API version dynamically

### PR DESCRIPTION
**Pull request by benwatcisco**
This future-proofs querying the version of a running Kubevirt instance
by dynamically determining the preferred API.

Signed-off-by: Ben Warren <bawarren@cisco.com>

**What this PR does / why we need it**:
Determines the kubevirt API version on a cluster before querying the Kubevirt version info.  Without this fix, the **virtctl version** command fails when querying a cluster where the Kubevirt API version is older, for example **v1alpha1**

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
None

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by cynepco3hahue** [comment]
@benwatcisco Unittests complains
```
• Failure [0.002 seconds]
Kubevirt Version Client
/root/go/src/kubevirt.io/kubevirt/pkg/kubecli/version_test.go:36
  should fetch version [It]
  /root/go/src/kubevirt.io/kubevirt/pkg/kubecli/version_test.go:48
  Path mismatch
  Expected
      <string>: /apis/subresources.kubevirt.io
  to equal
      <string>: /apis/subresources.kubevirt.io/v1alpha2/version
  /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/gomega/ghttp/handlers.go:39
```

**Comment by rmohr** [comment]
ok to test

**Comment by benwatcisco** [comment]
Updated to pass CI

**Pull request merged**
