### PR TITLE
console tests: increase timeout

### PR DESCRIPTION
**Pull request by akalenyu**
### What this PR does
30 seconds is a stretch here in my opinion, since we have no guarantee things will converge this quickly on the CI env with parallel testing and resource constraints.
This is causing flakes:
https://search.ci.kubevirt.io/?search=%5C%5Btest_id%3A1588%5C%5Dshould+return+OS+login&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
> Often times I see 300 seconds used as a timeout for Eventually, when waiting for a VM to become Ready, etc. Should we settle on one "universal" value?

I don't think there's a one fits all, but maybe we can provide some guideline for common cases. 300 is really bad because it just hides slow startups from us.

**Review by 0xFelix — COMMENTED** [review]
/approve

**Comment by xpivarc** [comment]
/hold 
Please allow me to have a look at the offender.

**Comment by xpivarc** [comment]
I haven't checked the others but from one job
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-e2e-k8s-1.30-sig-compute/1867248063328817152 I can see following
```
{
      "name": "volumedisk0-init",
      "state": {
          "terminated": {
              "exitCode": 0,
              "reason": "Completed",
              "startedAt": "2024-12-12T17:19:08Z",
              "finishedAt": "2024-12-12T17:19:21Z",
              "containerID": "cri-o://57b54dfcdf3cf98095f4643311105208fd6cff2958827a223ac4484531a1bc34"
          }
      },
```
The started and finished is difference of 13 seconds alone but what does the container do? It just starts binary and exits.  One of the reasons could be that the host was really running out of time. I am running out of time at the moment but this should be investigated. 
Feel free to unhold if you are confident that we are not experiencing bug in lower layers (such as runtine, kubelet, kernel)...

**Comment by xpivarc** [comment]
Also I would suggest 60 seconds timeout at worst as that is what we see in our testing as worst case

**Comment by akalenyu** [comment]
> I haven't checked the others but from one job https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-e2e-k8s-1.30-sig-compute/1867248063328817152 I can see following
> 
> ```
> {
>       "name": "volumedisk0-init",
>       "state": {
>           "terminated": {
>               "exitCode": 0,
>               "reason": "Completed",
>               "startedAt": "2024-12-12T17:19:08Z",
>               "finishedAt": "2024-12-12T17:19:21Z",
>               "containerID": "cri-o://57b54dfcdf3cf98095f4643311105208fd6cff2958827a223ac4484531a1bc34"
>           }
>       },
> ```
> 
> The started and finished is difference of 13 seconds alone but what does the container do? It just starts binary and exits. One of the reasons could be that the host was really running out of time. I am running out of time at the moment but this should be investigated. Feel free to unhold if you are confident that we are not experiencing bug in lower layers (such as runtine, kubelet, kernel)...

I see what you're saying.. the lower level bug is unrelated to this PR imo. 30 seconds is wayyy too ambitious for CI

**Comment by brianmcarey** [comment]
@akalenyu @xpivarc  `A new VirtualMachineInstance with a serial console [test_id:1588]should return OS login` is qualifying for quarantine - https://search.ci.kubevirt.io/?search=test_id%3A1588&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

Should we look at increasing this timeout to 60 to see if it helps?

**Comment by xpivarc** [comment]
@akalenyu Let's change for the 60 seconds that should be enough. Anything more should not be acceptable. The timeout did work for at least a year so the flakiness points to some issue.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by xpivarc** [comment]
/hold cancel
Thank you! @brianmcarey Would you mind documenting the found probable issue where simple containers takes so much time?

**Pull request merged**
