### PR TITLE
kubevirtci: move cluster-up into its own folder to allow OWNERS

### PR DESCRIPTION
**Pull request by dhiller**
### What this PR does
Before this PR:

We use [kubevirtci] for spinning up virtualized k8s clusters for testing (locally and on CI). Therefore we source the cluster-up folder into kubevirts' project folder root. Also we have the cluster-up-sha.txt which is used to verify which version we use currently, so that we can determine whether an update is necessary.

Related to how OWNERS files work, and since both of those items are located in the root folder, we currently need a root approver for approving pull requests that bump kubevirtci.

During the work we discovered a circular dependency from kubevirtci (namely virtctl.sh) calling the virtctl binary built by kubevirt.

[kubevirtci]: https://github.com/kubevirt/kubevirtci

After this PR:

Thus, to be able for sig-buildsystem to own kubevirtci we move it to it's own folder `kubevirtci`. In that folder we place an OWNERS file with which we as sig-buildsystem claim ownership of kubevirtci.

Also, we have created `hack/virtctl.sh` and moved all calls from kubevirtci/cluster-up/virtctl.sh to the newly created script. 

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by acardace** [comment]
@dhiller I'd also shoot an email to the mailing list, this is sort of a breaking change as lots of people probably have scripts relying on that path (like myself).

**Comment by dhiller** [comment]
> /approve
> 
> approving the intention but there are real errors in the build lanes, please take a look.

@acardace 

> /approve
> 
> approving the intention but there are real errors in the build lanes, please take a look.

@acardace thanks for the heads up, I opened an [issue on kubevirtci](https://github.com/kubevirt/kubevirtci/issues/1277) for the issue. I likely can fix the issue inside k/kubevirt by moving the script and calls towards `hack/` folder, which makes more sense anyway.

**Comment by dhiller** [comment]
FYI @iholder101 since you had approved the bump PR :)

**Comment by dhiller** [comment]
[Test failures on 1.31 sig-compute](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12872/pull-kubevirt-e2e-k8s-1.31-sig-compute/1838925040142258176) are unrelated to this change.

**Comment by dhiller** [comment]
> @dhiller: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kubevirt-e2e-arm64	[ca79389](https://github.com/kubevirt/kubevirt/commit/ca79389bdb35c25e9a9c3c8dbd174f4a17899633)	[link](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12872/pull-kubevirt-e2e-arm64/1839226532862627840)	false	`/test pull-kubevirt-e2e-arm64`

@brianmcarey the arm lane doesn't seem to be very stable - it failed twice on this PR already

**Comment by iholder101** [comment]
> FYI @iholder101 since you had approved the bump PR :)

> /unhold since this is a draft anyway

Please ping me when this is ready to review again :)

**Comment by dhiller** [comment]
Rebase done, should be ready for review now.

**Comment by dhiller** [comment]
@brianmcarey FYI - freshly rebased :wink:

**Review by brianmcarey — COMMENTED** [review]
/lgtm 

Thanks @dhiller ! 

As far as I can see there have been no arguments against this change on the [mailing list post](https://groups.google.com/g/kubevirt-dev/c/wycXN4W43Uk) so it should be ok to go in.

**Comment by akalenyu** [comment]
@dhiller doesn't this break the `k` alias? or do you have some bash shenanigans that guess the kubectl path?

**Comment by jean-edouard** [comment]
> @dhiller doesn't this break the `k` alias? or do you have some bash shenanigans that guess the kubectl path?

Oh, could that be causing:
```
build@jed:~/kubevirt$ kubectl get pods -n kubevirt
E1112 10:10:41.945858 1699502 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:32833/api?timeout=32s\": dial tcp 127.0.0.1:32833: connect: connection refused"
[...]
The connection to the server 127.0.0.1:32833 was refused - did you specify the right host or port?
build@jed:~/kubevirt$ 
```

**Comment by dhiller** [comment]
> > @dhiller doesn't this break the `k` alias? or do you have some bash shenanigans that guess the kubectl path?
> 
> Oh, could that be causing:
> 
> ```
> build@jed:~/kubevirt$ kubectl get pods -n kubevirt
> E1112 10:10:41.945858 1699502 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:32833/api?timeout=32s\": dial tcp 127.0.0.1:32833: connect: connection refused"
> [...]
> The connection to the server 127.0.0.1:32833 was refused - did you specify the right host or port?
> build@jed:~/kubevirt$ 
> ```
> 
> If so, what's the workaround? Edit:
> 
> ```
> export KUBECONFIG=`pwd`/kubevirtci/_ci-configs/$KUBEVIRT_PROVIDER/.kubeconfig
> alias kubectl=`pwd`/kubevirtci/_ci-configs/$KUBEVIRT_PROVIDER/.kubectl
> ```

I am using `direnv` in conjunction with the following

    export KUBECONFIG=$(cd $(pwd) && ./kubevirtci/cluster-up/kubeconfig.sh)

Also I'd rather

	alias kubectl=$(pwd)/kubevirtci/cluster-up/kubectl.sh

May I ask what exactly doesn't work for you? What do we need to improve?

**Comment by akalenyu** [comment]
> > May I ask what exactly doesn't work for you? What do we need to improve?
> 
> Well I think we need to be very loud about this change, as every dev will need to update their bashrc. It will also be an annoyance whenever we work on older branches that still use the old path, but I guess there's nothing we can do about that.

We could have the alias detect the name dynamically but I don't have much experience with bash
to sign off on the idea. something like `find . -type f -name kubectl.sh`

**Comment by dhiller** [comment]
> > > May I ask what exactly doesn't work for you? What do we need to improve?
> > 
> > Well I think we need to be very loud about this change, as every dev will need to update their bashrc. It will also be an annoyance whenever we work on older branches that still use the old path, but I guess there's nothing we can do about that.
> 
> We could have the alias detect the name dynamically but I don't have much experience with bash
> to sign off on the idea. something like `find . -type f -name kubectl.sh`

Maybe creating a wrapper script inside `hack/` folder could work - we might just port those back and add this to the mailing list thread we originally created. 

WDYT @akalenyu @jean-edouard

**Comment by akalenyu** [comment]
> > Maybe creating a wrapper script inside `hack/` folder could work
> 
> You mean `cluster-up/`? Anyhow it sounds like a good idea

@dhiller I really liked the idea though

**Pull request merged**
