### PR TITLE
cleanup(tests,virtctl): Drop virtctl expose functests

### PR DESCRIPTION
**Pull request by 0xFelix**
### What this PR does

The functional tests are testing functionality that is outside of the scope of this command. The command is only creating a Service, while the functional tests are asserting that basic network functionality of Kubernetes is behaving correctly.

By ensuring the command creates Services as expected, all important test cases in the scope of the command are already covered.

Therefore the the functional tests of virtctl expose are dropped.

The helper generateHelloWorldServer is moved closer to its remaining use in bindingplugin_slirp.go. The no longer used helpers in libnet are removed.

Before this PR:

virtctl expose functests test out of scope behavior of virtctl expose.

After this PR:

virtctl expose functests do not duplicate unit tests and do not test out of scope behavior.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by alicefr** [comment]
For POV, looks good
/lgtm

**Review by EdDev — COMMENTED** [review]
Thank you!

I am in favor of removing these e2e tests once https://github.com/kubevirt/kubevirt/pull/12855 gets in. Unit tests are a better fit, especially for `virtctl` only commands.

/approve

Feel free to unhold once that PR gets in.
/hold

**Comment by 0xFelix** [comment]
#12855 was merged

/hold cancel

**Pull request merged**
