### PR TITLE
podman: Support non root user via default root socket

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Since https://github.com/kubevirt/kubevirtci/pull/824
a non root user can use rootful podman via a socket (as docker supports).
For that we need to support the default root socket path `/run/podman/podman.socket`
in case the default root socket path was used.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
/cc @brianmcarey 
can you please take a look ?

**Review by brianmcarey — COMMENTED** [review]
lgtm

**Comment by oshoval** [comment]
> lgtm

Thanks, can you please add the `/` ?

**Review by enp0s3 — APPROVED** [review]
/approve
thank you @oshoval !

**Comment by oshoval** [comment]
Thanks all

/retest
not related

**Comment by EdDev** [comment]
> a non root user can use rootful podman via a socket (as docker supports).

This and the ref PR (https://github.com/kubevirt/kubevirtci/pull/824) seem worrying to me.
podman explicitly wants to avoid it.
It is also dependent on an explicit configuration by the user (that controls podman), as he needs to grant access to a specific user on that (root) socket.

Can you please clarify the scenarios you are trying to solve here? Is this documented?

**Comment by oshoval** [comment]
> > a non root user can use rootful podman via a socket (as docker supports).
> 
> This and the ref PR ([kubevirt/kubevirtci#824](https://github.com/kubevirt/kubevirtci/pull/824)) seem worrying to me. podman explicitly wants to avoid it. It is also dependent on an explicit configuration by the user (that controls podman), as he needs to grant access to a specific user on that (root) socket.
> 
> Can you please clarify the scenarios you are trying to solve here? Is this documented?

You can see that we are using the solution mentioned here 
https://github.com/containers/podman/issues/6809#issuecomment-668535032

Kubevirt / kubevirtci already supported that, but with the XDG socket (if you start the socket with `--user`)
This PRs just allow to use it easier

There are some unofficial blogs about it (looking for official one) for example
https://medium.com/devops-dudes/how-to-setup-root-less-podman-containers-efd109fa4e0d

The podman.socket is meant for docker compatibility
what we are doing here is basically what docker does, docker creates a socket that is accessible to docker group

The scenarios we are to allow easily use kubevirtci / kubevirt as non root

**Comment by EdDev** [comment]
> You can see that we are using the solution mentioned here [containers/podman#6809 (comment)](https://github.com/containers/podman/issues/6809#issuecomment-668535032) [containers/podman#6809 (comment)](https://github.com/containers/podman/issues/6809#issuecomment-662031057)

I prefer to see the summarized explanation that is relevant to kubevirt, not to some specific user that once had a similar issue.

> Kubevirt / kubevirtci already supported that, but with the XDG socket (if you start the socket with `--user`) This PRs just allow to use it easier

So what documentation was updated which expresses this new thing?
I am trying to understand which scenario you enabled support for now.
 
> There are some unofficial blogs about it (looking for official one) for example https://medium.com/devops-dudes/how-to-setup-root-less-podman-containers-efd109fa4e0d
> 
> The podman.socket is meant for docker compatibility what we are doing here is basically what docker does, docker creates a socket that is accessible to docker group

The reasoning to have a socket for podman may have been triggered for such a compatability, but I do not think it is limited today for it.

And if someone abuses these sockets, it does not mean we need to support them.

> The scenarios we are to allow easily use kubevirtci / kubevirt as non root

My claim is that we do not want to take responsibility on the location of the socket and its access settings.
If a user wants to provide non-root user access to a root created socket, it is up to him.
If a user wants to use a specific path to a socket, it is up to him to specify where the socket is.
We can have one default, and anything else must be explicitly configured (env variable?), otherwise we will never stop adding condition to the scripts.

**Pull request merged**
