### PR TITLE
Bump kubevirtci with fix for CDI DV GC tests

### PR DESCRIPTION
**Pull request by brianmcarey**
**What this PR does / why we need it**:

This PR includes changes from the bump-kubevirtci PR[1] and changes from a PR[2] that include fixes for tests for the new version of CDI that is included in the bump of kubevirtci. The storage lanes fail without this fix on the bump-kubevirtci PR. 

[1] https://github.com/kubevirt/kubevirt/pull/8449
[2] https://github.com/kubevirt/kubevirt/pull/8534

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @arnongilboa @brybacki @xpivarc 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
@arnongilboa can you take a look as well
/lgtm

**Review by arnongilboa — APPROVED** [review]

**Pull request merged**
