### PR TITLE
Make e2e runs more lightweight by making our builder image obsolete

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Instead of running `make cluster-up && make cluster-sync && make functest` within our builder container, make them run just with bazel and gcc present. These targets work now without the builder image if `KUBEVIRT_RUN_UNNESTED` is set to true.

This allows us to not pull a 2 GB image on every e2e start in CI and is also convenient to have local.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Review by dhiller — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
