### PR TITLE
Remove linux-bridge creation before Multus tests suite starts

### PR DESCRIPTION
**Pull request by ormergi**
Signed-off-by: Or Mergi <ormergi@redhat.com>

**What this PR does / why we need it**:
As for today on Multus tests suite [[1]](https://github.com/kubevirt/kubevirt/blob/259de8032ac84f8c8a3e6f37cbb94f598f936c3d/tests/network/vmi_multus.go#L101) we create a linux-bridge on each cluster node [[2]](https://github.com/kubevirt/kubevirt/blob/259de8032ac84f8c8a3e6f37cbb94f598f936c3d/tests/network/vmi_multus.go#L173)    [[3]](https://github.com/kubevirt/kubevirt/blob/259de8032ac84f8c8a3e6f37cbb94f598f936c3d/tests/network/vmi_multus.go#L1409)
before all tests starts in order for the tests that uses bridge CNI plugin to work.

The bridge CNI plugin is capable of creating a linux-bridge on the cluster nodes 
according to the NAD definition as being done on the tests.
Thus there is no need to create the linux-bridge beforehand.

This PR removes the code that deploy DaemonSet which creates the linux-bridge before all test starts.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by alonSadan — APPROVED** [review]
Thanks Or.

**Review by EdDev — COMMENTED** [review]
So can you confirm that there are no tests that check inter-node connectivity with this bridge?

**Comment by ormergi** [comment]
> So can you confirm that there are no tests that check inter-node connectivity with this bridge?

Yes I double checked, there are no other tests that uses it.

**Comment by EdDev** [comment]
> > So can you confirm that there are no tests that check inter-node connectivity with this bridge?
> 
> Yes I double checked, there are no other tests that uses it.

So it is worth pointing out, that if that will be required, we will have to either return this method back or find another solution.
(i.e. connecting the bridge to a node interface to have access to networks beyond the node)

**Review by EdDev — APPROVED** [review]
It feels always good when we remove code, thanks!

**Review by phoracek — APPROVED** [review]
/approve

**Pull request merged**
