### PR TITLE
[release-1.1] VMClone: Emit an event in case restore creation fails

### PR DESCRIPTION
**Pull request by orelmisan**
**What this PR does / why we need it**:
Manual cherrypick of PRs #10470, #10903 and #10918.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
~~The first commit contains the output of `make generate` in order to pass the `make generate` CI lane.
This is required since the year in the generated files' license comment has changed to 2024.
Hopefully this will not be needed next year due to https://github.com/kubevirt/kubevirt/pull/10863.~~

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
VMClone: Emit an event in case restore creation fails
```

### CODE REVIEW

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/974e2b8626602e696735bd56da862c3f42eabc7a..47b8308800d818a969b9b9769a5a0038f05df475): Update the first commit message.

**Review by RamLavi — APPROVED** [review]
/lgtm

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/47b8308800d818a969b9b9769a5a0038f05df475..372034a41e44f9522b29b02116488399087f1d88): Rebase and dropped the first commit containing the output of `make generate` as it was introduced by #10974.

**Review by enp0s3 — COMMENTED** [review]
/approve

**Review by RamLavi — APPROVED** [review]
/lgtm

**Pull request merged**
