### PR TITLE
Revert "guestlog, quarantine: Quarantine flakey QOSGuaranteed test"

### LINKED ISSUE #12074: Tracker: Quarantined guestlog QOSGuaranteed test
**What happened**:

As discussed on the [kubevirt-dev ML](https://groups.google.com/g/kubevirt-dev/c/c-zMktLPMlo) this test has become flaky again after some seemingly unrelated changes. This bug will track work to bring the test back out of quarantine and will start by tracking the progress of a yet to be raised libvirt bug.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
### What this PR does

This reverts commit 0c2c76a390e83b96f6187535bf801c3ff6bdd7ad.

As discussed on the [kubevirt-dev ML](https://groups.google.com/g/kubevirt-dev/c/c-zMktLPMlo) the flake appears to be resolved now so we can unquarantine the test. This will also need to be backported to `release-1.3` assuming it is also fixed there.

Fixes #12074

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
@lyarwood @tiraboschi I can confirm that test flakiness stopped around 2024-06-14 for 1.29 and 1.30:
* https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.30-sig-compute&width=5
* https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.29-sig-compute&width=5

And also it has gotten much better on 1.28 - however, I'm seeing mild flakiness there still:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.28-sig-compute/1802431110282481664
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.28-sig-compute/1806055046337531904

**Comment by dhiller** [comment]
See also this ci-search query: https://search.ci.kubevirt.io/?search=flood+the+serial+console+for+QOSGuaranteed+VMs&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by dhiller** [comment]
Also I think that this result differs from what we saw when we quarantined the test - I faintly remember that there's been one extra character appearing that shouldn't have been there, where now the pattern expected is different...

**Comment by lyarwood** [comment]
> Also I think that this result differs from what we saw when we quarantined the test - I faintly remember that there's been one extra character appearing that shouldn't have been there, where now the pattern expected is different...

Yeah I think @0xFelix found that there were a few instances of an extra `0` being returned that broke the test but AFAICT the current failures aren't the same. I can't really tell why it's failing here as the expected line is present but the test still isn't happy.


Happy to /hold this for now while we check this out.

**Comment by tiraboschi** [comment]
> Also I think that this result differs from what we saw when we quarantined the test - I faintly remember that there's been one extra character appearing that shouldn't have been there, where now the pattern expected is different...

I think it's basically the same issue.
In the last failure from 4 days ago we got:
```
logline 0002307 0002307 0002307 0002307 0002307 0002307 0002307 0002307 0002307 0002307 0002307 0002307 0002307 0002307 0002307
logliine 0002308 0002308 0002308 0002308 0002308 0002308 0002308 0002308 0002308 0002308 0002308 0002308 0002308 0002308 0002308
logline 0002309 0002309 0002309 0002309 0002309 0002309 0002309 0002309 0002309 0002309 0002309 0002309 0002309 0002309 0002309
```
so this time the duplicate character is an `i` and not a `0` but I think it's exactly the same issue.

The file here:
https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.28-sig-compute/1806055046337531904/artifacts/serial_logs_content_e64b6770-d696-494d-ad48-c997bfc39950.txt
is simply a copy of the file we got from `libvirt/virtlogd` before the data reaches our integration code and/or the k8s logging subsystem so we can be 100% sure that the issue is already contained in what we are receiving from `libvirt/virtlogd`.

Here a reference of how we are extracting it via a different code path `if CurrentSpecReport().Failed()` 
https://github.com/kubevirt/kubevirt/blob/81e62b66e79650fbbdfa177b570ab8a4f5c5d086/tests/guestlog/guestlog.go#L247-L261

**Comment by 0xFelix** [comment]
As @tiraboschi pointed out, any character in the logfile can be duplicated, not just `0`s.

**Comment by dhiller** [comment]
update: we reiterated over this tests flakyness in the periodic lanes, and so far we have seen it fail only once in one lane over the last two weeks, so it seems to be fixed or at least the flakyness doesn't satisfy the criteria of quarantining - in short, I would support the test being taken out of quarantine.

Opinions?

@lyarwood @0xFelix @tiraboschi 

* [testgrid - kubevirt-e2e-k8s-1.30-sig-compute](https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.30-sig-compute&width=5)
* [testgrid - kubevirt-e2e-k8s-1.29-sig-compute](https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.29-sig-compute&width=5)
* [testgrid - kubevirt-e2e-k8s-1.28-sig-compute](https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.28-sig-compute&width=5)

**Comment by lyarwood** [comment]
@dhiller Thanks for keeping an eye on this and apologies for not pushing things along on my end. If it's looking more stable I think we can go ahead with this revert. If it does crop up again however we should really revisit the tests and potentially make them a little more forgiving if we agree that a few extra characters isn't the end of the world given our use cases.

**Comment by 0xFelix** [comment]
@dhiller ACK, let's take it back out of quarantine.

**Comment by dhiller** [comment]
> @dhiller Thanks for keeping an eye on this and apologies for not pushing things along on my end. If it's looking more stable I think we can go ahead with this revert. If it does crop up again however we should really revisit the tests and potentially make them a little more forgiving if we agree that a few extra characters isn't the end of the world given our use cases.

Fully agree - path should be making the test more resilient wrt this.

/lgtm
/approve

**Pull request merged**
