### PR TITLE
Add test-id's for VM Error States Test Cases

### PR DESCRIPTION
**Pull request by kbidarkar**
Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>

**What this PR does / why we need it**: `Add test-id's for VM Error States Test Cases`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: `Add test-id's for VM Error States Test Cases`

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by zcahana** [comment]
Thanks @kbidarkar !

/lgtm
/retest

**Comment by enp0s3** [comment]
/hold
lets wait for https://github.com/kubevirt/kubevirt/pull/6280 to get in. We have a an issue with a sig-network macvtap test

**Pull request merged**
