### PR TITLE
Fix gofmt warning: redundant type from array, slice, or map composite literal

### PR DESCRIPTION
**Pull request by Hellcatlk**
Signed-off-by: Zou Yu <zouy.fnst@cn.fujitsu.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
@Hellcatlk there is nothing wrong with your code changes. However I would be more interested in either ensuring that our code formatters fix this on the fly, or that we just ignore these errors. Maybe you can have a look if e.g. `goimports` can be asked to fix this on the fly.

**Comment by Hellcatlk** [comment]
Run `gofmt -s -d` can see these changes.

**Comment by rmohr** [comment]
> Run `gofmt -s -d` can see these changes.

`goimports` rungs `gofmt` but not with the `-s` option. If we want this formatting enforced, I think we should run gofmt as part of `hack/bazel-fmt.sh`. I am not so much a fan of repetitive work wich just wastes time of engineers. If you are interested that would be the direction I would look into. We would probably need a `gofmt` bazel rule similar to https://github.com/ash2k/bazel-tools/tree/master/goimports. The `rules_go` toolchain has already access to the `gofmt` binary.

**Pull request merged**
