### PR TITLE
[clone] network, macvtap bind mech: add a MAC parameter to the bind mech

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:
This allows us to stop using virtIface on the pod networking
setup occurring in virt-handler on follow up PRs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
This is #5057 clone with a rebase.
(I could not push to @maiqueb repo/branch)

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by maiqueb** [comment]
You can drop this; I've rebased the original PR - please take another look at it whenever you can.

/hold

**Comment by EdDev** [comment]
> You can drop this; I've rebased the original PR - please take another look at it whenever you can.
> 
> /hold

Great, thanks.
I failed to get enough attention to get this in even with this clone :(

**Pull request closed without merging**
