### PR TITLE
[release-1.3] bug-fix: ensure deletion of PDB of VMI when reaching final state

### PR DESCRIPTION
**Pull request by dasionov**
Manual backport of #12809 and #12690.

```release-note
None
```

Jira Ticket - https://issues.redhat.com/browse/CNV-49315

### CODE REVIEW

**Comment by dasionov** [comment]
/reopen

@xpivarc i'm fixing the test :)

**Comment by xpivarc** [comment]
@dasionov Sorry I mistake it with bot PR :)

**Comment by dasionov** [comment]
> @dasionov Sorry I mistake it with bot PR :)

All good :+1:

**Pull request merged**
