### PR TITLE
schema: update json tags to allow optional fields be empty

### PR DESCRIPTION
**Pull request by lukas-bednar**
Related to #547

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by lukas-bednar** [comment]
Unfortunately I got another issue related to this `omitempty` issue, I will try to stack them up in this PR.

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by rmohr** [comment]
For arrays it is difficult, since there is not really a difference between an empty array or nil, as far as the go deserializer is concerned. I think this is one of the cases, where we would need something like a real `optional` attribute. I think something like 

```go
Graphics []VMGraphics `json:"graphics,omitempty" optional:"true"`
```

is more accurate.

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by rmohr** [comment]
ok to test

**Comment by ovirt-infra** [comment]
Some tests failed

**Pull request merged**
