### PR TITLE
usbredir test: Add GinkgoRecover for goroutines

### LINKED ISSUE #12787: ginkgo: ReportAfterSuite failed with "Test Report unavailable because a Ginkgo parallel process disappeared"
**What happened**:
Recently we have been seeing `sig-compute` test lanes fail on `ReportAfterSuite` with the message.

```
Test Report unavailable because a Ginkgo parallel process disappeared
```

[Example failure in job]

Failures are not specific besides sig-compute - there's periodics and presubmits on several k8s providers failing (see [CI search] on the issue)

**What you expected to happen**:
Test suite should not fail on `ReportAfterSuite`.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:
* issue seen on [this PR](https://github.com/kubevirt/kubevirt/pull/12640) unrelated to the error
* [Example failure in job]
* [CI search]

/sig ci
/sig compute
/kind failing-test

/cc @fossedihelm @brianmcarey 

[Example failure in job]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12640/pull-kubevirt-e2e-k8s-1.31-sig-compute/1833418440296108032#1:build-log.txt%3A7355
[CI search]: https://search.ci.kubevirt.io/?search=Test+Report+unavailable+because+a+Ginkgo+parallel+process+disappeared&maxAge=336h&context=1&type=all&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

### PR DESCRIPTION
**Pull request by xpivarc**
### What this PR does
Fixes https://github.com/kubevirt/kubevirt/pull/12640#issuecomment-2343226644

Fixes #12787

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
/lgtm
@dhiller @xpivarc nice find

**Review by dhiller — APPROVED** [review]
Thank you @xpivarc !

Source: https://github.com/kubevirt/kubevirt/pull/12640#issuecomment-2343226644

**Comment by fossedihelm** [comment]
ref: https://github.com/kubevirt/kubevirt/issues/12787

**Comment by fossedihelm** [comment]
Wow! Are the usbredir tests broken? https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12793/pull-kubevirt-check-tests-for-flakes/1833816822990770176

**Comment by xpivarc** [comment]
> Wow! Are the usbredir tests broken? https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12793/pull-kubevirt-check-tests-for-flakes/1833816822990770176

They are flaky and it is good that the lane detects it as well

**Comment by victortoso** [comment]
We had [this check ](https://github.com/kubevirt/kubevirt/pull/11643#discussion_r1621290531)in the PR that introduced but it wasn't failing at that time. Not sure what has changed?

**Comment by victortoso** [comment]
I honestly think it is fine to have GinkoRecover() in tests, so I'll also
/lgtm

**Comment by dhiller** [comment]
/override pull-kubevirt-e2e-k8s-1.29-sig-storage

Unrelated to this change.

**Comment by akalenyu** [comment]
> /override pull-kubevirt-e2e-k8s-1.29-sig-storage
> 
> Unrelated to this change.

Definitely unrelated, I am seeing that the guest-console-log container exited for some reason:
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12793/pull-kubevirt-e2e-k8s-1.29-sig-storage/1833818950031380480/artifacts/k8s-reporter/1/1_pods.log
But don't see anything in the log/yaml
```
                        "state": {
                            "terminated": {
                                "exitCode": 1,
                                "reason": "Error",
                                "startedAt": "2024-09-11T12:30:57Z",
                                "finishedAt": "2024-09-11T12:31:18Z",
                                "containerID": "cri-o://089363357ca031388035fcbc919c9e42d2f3b704b8d0268779aad8453a4a31b3"
                            }
```
@tiraboschi does this make any sense? is there some path that could fail without output?

**Comment by dhiller** [comment]
/override pull-kubevirt-e2e-k8s-1.31-sig-compute

Lane failure caused by flaky test: https://search.ci.kubevirt.io/?search=%5C%5Btest_id%3A1669%5Dshould+show+the+requested+guest+memory+inside+the+VMI&maxAge=336h&context=1&type=all&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Pull request merged**
