### PR TITLE
Fix SRIOV lane: bump kubevirtci

### PR DESCRIPTION
**Pull request by ormergi**
**What this PR does / why we need it**:
Bump kubevirtci to get latest changes sriov provider kubevirt/kubevirtci#459
With those changes SRIOV lane should run tests successfully.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ormergi** [comment]
https://github.com/kubevirt/kubevirtci/pull/459

**Review by EdDev — APPROVED** [review]

**Comment by ormergi** [comment]
Thank you!

**Pull request merged**
