### PR TITLE
Provide debug info in case of kubevirt missed start

### PR DESCRIPTION
**Pull request by fedepaol**
**What this PR does / why we need it**:
While running sriov ci tests, a few runs failed for timed out waiting for the condition on kubevirts/kubevirt during cluster-deploy. This PR provides debug information in case the deadline is missed. 

**Release note**:

```release-note

NONE

```

### CODE REVIEW

**Comment by slintes** [comment]
good idea, but travis seems to be unhappy with formatting, please run `make generate`

**Comment by fedepaol** [comment]
Done!

**Comment by slintes** [comment]
too bad that this didn't happen in the tests for this PR, would have liked to see it in action :wink: 

/lgtm
/approve

**Pull request merged**
