### PR TITLE
VMI update admitter: Rm call to deprecated IsKubeVirtServiceAccount

### PR DESCRIPTION
**Pull request by orelmisan**
### What this PR does
IsKubeVirtServiceAccount is deprecated [1], adjust the code to use `admitter.kubeVirtServiceAccounts` instead.

[1] https://github.com/kubevirt/kubevirt/pull/12568

Partially addresses https://github.com/kubevirt/kubevirt/issues/11177.

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/7ec15508ee4e3723d241c054c8a4136833323312..412fc26ac49cda4c35b4da463fc3bc0b855dd4ca): Changed commit subject.

**Review by ShellyKa13 — COMMENTED** [review]
/lgtm

**Comment by iholder101** [comment]
/kind cleanup

Thank you @orelmisan!
Not that it should block this PR, but TBH I think it would have been great if you'd take this another step further and remove this deprecated function altogether in this PR, from a glance it seems that this additional step would be pretty easy to do.

/approve

**Comment by orelmisan** [comment]
> /kind cleanup
> 
> Thank you @orelmisan! Not that it should block this PR, but TBH I think it would have been great if you'd take this another step further and remove this deprecated function altogether in this PR, from a glance it seems that this additional step would be pretty easy to do.
> 
> /approve

Thank you @iholder101.
I have the next step figured out.
Its a bit more complex than in seems to I wanted so save it for a follow-up.

**Comment by orelmisan** [comment]
> > /kind cleanup
> > Thank you @orelmisan! Not that it should block this PR, but TBH I think it would have been great if you'd take this another step further and remove this deprecated function altogether in this PR, from a glance it seems that this additional step would be pretty easy to do.
> > /approve
> 
> Thank you @iholder101. I have the next step figured out. Its a bit more complex than it seems so I wanted so save it for a follow-up.

@iholder101 the follow-up is ready https://github.com/kubevirt/kubevirt/pull/13602.

**Pull request merged**
