### PR TITLE
Detect and report an ErrImagePull/ImagePullBackOff VM status

### PR DESCRIPTION
**Pull request by zcahana**
**What this PR does / why we need it**:

This PR extends the VM status field (`.status.printableStatus`) with new `ErrImagePull`/`ImagePullBackOff` statuses, reported when an error occurs when pulling a container image for the VM.

This will typically indicate that one of the container disks of the VM has failed to be pulled, but may also indicate that there was an error pulling the virt-launcher image or one of its init container images.

**Special notes for your reviewer**:

This was implemented by first propagating the `ErrImagePull`/`ImagePullBackOff` container status from the virt-launcher pod, to the VMI conditions (Synchronized=False, Reason: `ErrImagePull`/`ImagePullBackOff`), and then from the VMI to the VM's status.

This approach involves additional updates to the VMI object. Alternatively, we could have avoided that by adding a pod informer to the VM controller, and propagate the status directly from the pod to the VM (without updating the VMI). But there's a caveat too:
- If we configure the pod informer callbacks to trigger the controller with each pod update, then we add quite a lot of additional processing to the VM controller. This is not necessarily better than additional VMI updates.
- If we avoid pod informer callbacks in the VM controller, we won't be able to track the ErrImagePull-->ImagePullBackOff transitions in the pod, so we'll have to just report a single value in the VM status.

Eventually, I chose the pod-->VMI-->VM approach since it's (1) able to report both ErrImagePull, ImagePullBackOff statuses from the pod, and (2) provides visibility to this kind of error via the VMI object too.

**Release note**:
```release-note
Report ErrImagePull/ImagePullBackOff VM status when image pull errors occur
```

### CODE REVIEW

**Comment by kbidarkar** [comment]
@zcahana  For the testcase: `VirtualMachine: A valid VirtualMachine given should report an error status when image pull error occurs` it is [test_id:6869]

**Comment by zcahana** [comment]
Thanks @ashleyschuett and @kbidarkar!
I've rebased + updated the functest with the new test_id.
The PR is now ready for re-review.

**Comment by zcahana** [comment]
>/lgtm

Thanks @ashleyschuett! do you think there's anything else needed for an /approval or this is ready to go as-is?

**Pull request merged**
