### PR TITLE
tests, network: Remove vmi Status ip normalization

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
Now that the CIDR is not included at the VMI Status IPs (https://github.com/kubevirt/kubevirt/pull/4217) we don't need to
remove it before compare it with the pod Ips.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Thanks
nit: please add https://github.com/kubevirt/kubevirt/pull/4217 to the PR description

**Review by phoracek — APPROVED** [review]
/lgtm

**Pull request merged**
