### PR TITLE
[release-0.48] virt-launcher, hostdevice: Respect SR-IOV guest pciAddress and bootOrder

### PR DESCRIPTION
**Pull request by orelmisan**
This is a manual cherry-pick of #7422 and #7501.
It fixes Bugzilla [2070050](https://bugzilla.redhat.com/show_bug.cgi?id=2070050).

**Release note**:

```release-note
Fixed setting custom guest pciAddress and bootOrder parameter(s) to a list of SR-IOV NICs.
```

### CODE REVIEW

**Review by EdDev — APPROVED** [review]

**Review by ormergi — APPROVED** [review]

**Comment by orelmisan** [comment]
Opened PR #7489 in order to pass `pull-kubevirt-generate`.

**Review by EdDev — APPROVED** [review]

**Comment by orelmisan** [comment]
https://github.com/kubevirt/kubevirt/pull/7480

**Review by ormergi — APPROVED** [review]

**Pull request merged**
