### PR TITLE
Collect component Role rules under operator Role instead of ClusterRole

### PR DESCRIPTION
**Pull request by jean-edouard**
### What this PR does
Before this PR:
virt-operator collects rules from virt-* Roles and ClusterRoles under its ClusterRole

After this PR:
virt-operator collects rules from virt-* Roles under its Role and ClusterRoles under its ClusterRole

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Less privileged virt-operator ClusterRole
```

### CODE REVIEW

**Comment by stu-gott** [comment]
/approve
/cc @davidvossel 

This PR looks completely sane, but would like a second set of eyes.

**Comment by fossedihelm** [comment]
/lgtm
Looks good from my point of view, e2e tests have shown no regression
/hold
Put a hold to give @davidvossel a chance to chime in

**Review by davidvossel — COMMENTED** [review]
overall, I agree with the changes here. We should be reducing virt-operator's RBAC scope as much as possible.

It's possible the cluster scoped access to some of these resources is a result of having a cluster scoped KubeVirt object. Maybe we should start enforcing that the kubevirt crd exists in the same namespace as virt-operator

**Comment by jean-edouard** [comment]
> overall, I agree with the changes here. We should be reducing virt-operator's RBAC scope as much as possible.
> 
> It's possible the cluster scoped access to some of these resources is a result of having a cluster scoped KubeVirt object. Maybe we should start enforcing that the kubevirt crd exists in the same namespace as virt-operator

https://github.com/kubevirt/kubevirt/blob/6f802d8ac97da609067850558e5ee9c4e8e9b895/pkg/virt-operator/kubevirt.go#L882

**Comment by davidvossel** [comment]
> > overall, I agree with the changes here. We should be reducing virt-operator's RBAC scope as much as possible.
> > It's possible the cluster scoped access to some of these resources is a result of having a cluster scoped KubeVirt object. Maybe we should start enforcing that the kubevirt crd exists in the same namespace as virt-operator
> 
> https://github.com/kubevirt/kubevirt/blob/6f802d8ac97da609067850558e5ee9c4e8e9b895/pkg/virt-operator/kubevirt.go#L882

yay!

Looks great then! thanks

**Comment by jean-edouard** [comment]
@fossedihelm added a smal unit test, PTAL!

**Review by fossedihelm — APPROVED** [review]
Thank you!

**Comment by stu-gott** [comment]
I just remembered why we only honor KubeVirt CR's from the install namespace. At some point in the past it was noted that if you installed two CRs in different namespaces, all sorts of merriment ensued. Locking it to the install namespace ensures there will be only one.

**Pull request merged**
