### PR TITLE
WIP-Testing weird issue

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by xpivarc** [comment]
Looks like the mprotect fails because of capabilities.

**Comment by vladikr** [comment]
> Looks like the mprotect fails because of capabilities.

What capability is missing?

**Comment by xpivarc** [comment]
> > Looks like the mprotect fails because of capabilities.
> 
> What capability is missing?

Actually, it fails when capabilities are set on the virt-launcher binary.

**Pull request closed without merging**
