### PR TITLE
Tests: Keep export resources after vmexport download to improve debugging

### PR DESCRIPTION
**Pull request by alromeros**
**What this PR does / why we need it**:

Some flakes in tests are getting harder to debug since the vmexport resource is usually cleaned up manually after the command exits. This pull request adds the `keep-vme` flag to most of these tests to retain the resource and improve debugging.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by akalenyu — COMMENTED** [review]
After thinking about this more I think the tests are in the right not using `--keep-vme` as that is more in sync with how users are going to use these virtctl subcommand
So I would be hesitant to change the tests.

BTW, this AfterEach is completely fine, since the k8s reporter will kick in before it

**Comment by alromeros** [comment]
> After thinking about this more I think the tests are in the right not using `--keep-vme` as that is more in sync with how users are going to use these virtctl subcommand So I would be hesitant to change the tests.
> 
> BTW, this AfterEach is completely fine, since the k8s reporter will kick in before it

That's right but both flows are covered already, don't think we have to worry about following the more common use case. Export-related flakes are common and having the object prematurely deleted will always make debugging harder.

**Comment by alromeros** [comment]
We are reconsidering this behavior so it'll probably be better addressed in another PR.

**Pull request closed without merging**
