### PR TITLE
Add VM snapshot recording rules to documentation

### LINKED ISSUE #7720: Missing documentation for new vm snapshot recording rules
**Description**:
In PR #7533, new recording roles were added, but they are missing from the documentation here https://github.com/kubevirt/kubevirt/blob/main/docs/metrics.md

**What you expected**:
The new recording rules should be added to https://github.com/kubevirt/kubevirt/blob/main/docs/metrics.md.

**URL**:
They should be added to https://github.com/kubevirt/kubevirt/blob/main/docs/metrics.md

**Additional context**:
Add any other context about the issue here.

CC @akalenyu 

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2143165

### PR DESCRIPTION
**Pull request by sradco**
Signed-off-by: Shirly Radco <sradco@redhat.com>

**What this PR does / why we need it**:
This PR adds kubevirt_vmsnapshot_disks_restored_from_source_total and kubevirt_vmsnapshot_disks_restored_from_source_bytes recording rules to the documentation in metrics.md.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7720 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sradco** [comment]
@enp0s3 @iholder101 Can you please review this PR?

**Review by enp0s3 — COMMENTED** [review]
/approve

**Pull request merged**
