### PR TITLE
network, Refactor dhcp refrences to DHCP

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This PR refactors functions names and struct to use DHCP instead of dhcp, without changing any code logic

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by rhrazdil — APPROVED** [review]

**Comment by rhrazdil** [comment]
@RamLavi You may need to re-push emtpy change for the jobs to kick in

**Review by maiqueb — COMMENTED** [review]
Do you mind squashing these commits, or prefer to have them all ? I see no reason to segment this so much,

**Comment by maiqueb** [comment]
> Do you mind squashing these commits, or prefer to have them all ? I see no reason to segment this so much,

I'm setting this in hold so you're forced to address it :) Feel free to remove the hold if you don't want to squash. 

/hold

**Comment by RamLavi** [comment]
/hold cancel

@maiqueb, I rebased, please re-review

**Review by maiqueb — APPROVED** [review]
Thanks.

**Pull request merged**
