### PR TITLE
net, setup: Execute the pre-setup once per VMI

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

The pre-setup step includes operations that are required to be executed
once per VMI (claiming special devices ownership).

The current implementation may executes the pre-setup every reconcile
loop instead of once. This change modifies the behavior and assures the
pre-setup is only executed once per VMI.

In addition, adjusted the order of operations in the setup function to allow future development.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
Flaky unrelated unit tests: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/10321/pull-kubevirt-unit-test/1693956060181696512

/test pull-kubevirt-unit-test

**Comment by AlonaKaplan** [comment]
> Instead of performing a costly virt-launcher detection operation for
> (potentially) each reconcile, do it only once per VMI.

setup is performed only when needed (VM start, hotplug/unplug/migration). It is not performed on each reconcile cycle.
The change in this PR seems ok, but I"m not sure if this optimization is required. It complicates the code and adds configState info it doesn't need/relevant to it.

Please re-consider the need of this PR.

**Comment by EdDev** [comment]
> setup is performed only when needed (VM start, hotplug/unplug/migration). It is not performed on each reconcile cycle.

In the case of `hotplug`/`hotunplug`,  it will re-enter the setup as long as the status is not stable, i.e. until it is updated to reflect the up-do-date state. This may take some time, especially if the system is unable to reach the desired state (e.g. unsuccessful in plugin or unplugging an interface).
It is correct that in a "good" scenario it will not re-calculate this information, but in an unstable scenario it will.

> The change in this PR seems ok, but I"m not sure if this optimization is required. It complicates the code and adds configState info it doesn't need/relevant to it.

The virt-launcher PID is indeed an inconvenient complication here.
It has duplication at several objects. Perhaps we can look into this and check if we can reduce it.

If you have an idea on how to reduce the complexity here, please throw ideas.
As this is not anywhere urgent, we can wait with this for a while, perhaps as part of other refactorings we will see a way to simplify it further.

**Comment by EdDev** [comment]
change: Rebased and left only the simple logic in-place.

The detection of the pid has not been left due to its complexity, we will revisit it later.

**Comment by EdDev** [comment]
The last commit will be handled as part of a different PR, closing this one.

**Pull request closed without merging**
