### PR TITLE
e2e,compute: Add [Serial] label to sig-compute tests with serial decorator

### PR DESCRIPTION
**Pull request by brianmcarey**
### What this PR does

The [Serial] label is still used for the splitting of sig-copmute tests between parallel and serial[1]

Include this label on sig-compute tests that have the serial decorator

[1] https://github.com/kubevirt/kubevirt/blob/08417a74594779672949f21803589e14fb274276/automation/test.sh#L437C1-L443C71

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve

**Review by fossedihelm — COMMENTED** [review]
It looks good, thank you!
Do you mind add the `[Serial]` also to these?:
- https://github.com/kubevirt/kubevirt/blob/df0037684f979221a9f493bfa27275314f3601dd/tests/infrastructure/crds.go#L41
The `DescribeInfra` already has `[Serial]` but I would like to see it every time the decorator appears, for consistency and future changes.
- https://github.com/kubevirt/kubevirt/blob/df0037684f979221a9f493bfa27275314f3601dd/tests/vmi_lifecycle_test.go#L92
The only `It` contained in the `Context` has the `[Serial]` , but same reasoning of the previous one.

We should close the gap for storage and network too, can we do it in a separate PR?
- https://github.com/kubevirt/kubevirt/blob/df0037684f979221a9f493bfa27275314f3601dd/tests/network/bindingplugin_macvtap.go#L52
- https://github.com/kubevirt/kubevirt/blob/df0037684f979221a9f493bfa27275314f3601dd/tests/network/bindingplugin_slirp.go#L51
- https://github.com/kubevirt/kubevirt/blob/df0037684f979221a9f493bfa27275314f3601dd/tests/network/vmi_lifecycle.go#L108-L109
Here we should just move the `Serial` above

Thank you for this effort

**Comment by dhiller** [comment]
> It looks good, thank you! Do you mind add the `[Serial]` also to these?:
> 
> * https://github.com/kubevirt/kubevirt/blob/df0037684f979221a9f493bfa27275314f3601dd/tests/infrastructure/crds.go#L41
>   
>   The `DescribeInfra` already has `[Serial]` but I would like to see it every time the decorator appears, for consistency and future changes.
> * https://github.com/kubevirt/kubevirt/blob/df0037684f979221a9f493bfa27275314f3601dd/tests/vmi_lifecycle_test.go#L92
>   
>   The only `It` contained in the `Context` has the `[Serial]` , but same reasoning of the previous one.
> 
> We should close the gap for storage and network too, can we do it in a separate PR?
> 
> * https://github.com/kubevirt/kubevirt/blob/df0037684f979221a9f493bfa27275314f3601dd/tests/network/bindingplugin_macvtap.go#L52
> * https://github.com/kubevirt/kubevirt/blob/df0037684f979221a9f493bfa27275314f3601dd/tests/network/bindingplugin_slirp.go#L51
> * https://github.com/kubevirt/kubevirt/blob/df0037684f979221a9f493bfa27275314f3601dd/tests/network/vmi_lifecycle.go#L108-L109
>   
>   Here we should just move the `Serial` above
> 
> Thank you for this effort

FYI @EdDev @akalenyu

**Comment by EdDev** [comment]
Why we are adding the text tags and not depending only on the regular labels?
What did I miss here?

Having to ways to mark something is not great.

**Comment by brianmcarey** [comment]
> Why we are adding the text tags and not depending only on the regular labels? What did I miss here?
> 
> Having to ways to mark something is not great.

This is only really relevant to the compute lanes due to the way we split the parallel and serial tests into different lanes[1].

We have to maintain the text label until we find a better way of splitting them. Splitting on the Serial label doesn't work at the moment - https://github.com/kubevirt/kubevirt/pull/13187#issuecomment-2458903972

[1]  https://github.com/kubevirt/kubevirt/blob/08417a74594779672949f21803589e14fb274276/automation/test.sh#L437C1-L443C71

**Comment by dhiller** [comment]
> > Why we are adding the text tags and not depending only on the regular labels? What did I miss here?
> > Having to ways to mark something is not great.
> 
> This is only really relevant to the compute lanes due to the way we split the parallel and serial tests into different lanes[1].
> 
> We have to maintain the text label until we find a better way of splitting them. Splitting on the Serial label doesn't work at the moment - [#13187 (comment)](https://github.com/kubevirt/kubevirt/pull/13187#issuecomment-2458903972)
> 
> [1] [`08417a7`/automation/test.sh#L437C1-L443C71](https://github.com/kubevirt/kubevirt/blob/08417a74594779672949f21803589e14fb274276/automation/test.sh#L437C1-L443C71)

Sorry for being pedantic here - `Serial` is a **decorator, not a label**. Therefore you can't filter for Serial directly, since `--label-filter` only works on labels.

I haven't yet found a better way to only select serial tests (or at least ginkgo cli doesn't reveal a way to do this) besides adding another label `Serial` into our `decorators` - which is what I'd suggest to be able to select tests in the usual way. But this is still error-prone, as you, @EdDev pointed out.

**Pull request merged**
