### PR TITLE
[release-0.41] Fix [test_id:6978] Should detect a failed migration

### PR DESCRIPTION
**Pull request by enp0s3**
This is a manual cherry-pick of #6643

/assign enp0s3

Signed-off-by: Igor Bezukh <ibezukh@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by xpivarc — APPROVED** [review]
Note: This test was observed to be still flaky even with this fix.

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
