### PR TITLE
apimachinery: Move patch operations to a patch package

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

Patch helpers are moved from the pkg/util/types package to apimachinery/patch package.
The old package name was too general.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
change: Rebase

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
