### PR TITLE
Add k8s-1.17.0 kubevirtci

### PR DESCRIPTION
**Pull request by dhiller**
Signed-off-by: Daniel Hiller <daniel.hiller.1972@gmail.com>

**What this PR does / why we need it**:
Adds the kubevirtci provider for k8s 1.17. Still missing the pushed image sha though. See kubevirt/project-infra#269

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by danielBelenky** [comment]
This PR overlaps with #2927. Since you updated to a newer version of `kubevirtci`, would I drop my PR?

Other than that LGTM.

/lgtm

**Comment by rmohr** [comment]
/approve

Can we take this in to get a working okd lane again?

**Comment by dhiller** [comment]
@rmohr ATM this is based on the commit from the kubevirtci PR from kubevirt/kubevirtci#220. I thought we shouldn't merge it with this? Maybe we should merge that one first, and I go update the kubevirtci sha here and then we're good to go?

**Comment by dhiller** [comment]
So we should be good to go now.

**Comment by dhiller** [comment]
@rmohr do we want to wait for the tests to finish? I mean, all lanes have been green once ;-)

**Pull request merged**
