### PR TITLE
tests, utils: Move functions from tests utils and tighten test/utils lines limit 

### PR DESCRIPTION
**Pull request by ShellyKa13**
### What this PR does
Move functions from the tests utils to where they belong.

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by codingben — APPROVED** [review]
/lgtm

**Comment by iholder101** [comment]
Thanks @ShellyKa13 

/approve

**Comment by brianmcarey** [comment]
/hold 

unfortunately the decrease in line limit for utils is clashing in batch runs with https://github.com/kubevirt/kubevirt/pull/11370 - which is causing the batch to loop retrying the failing lint lane. 
screenshot-2024-03-15-14:17:35

**Comment by ShellyKa13** [comment]
/unhold
updated the number of lines according to the merged code. should be ok now.

**Pull request merged**
