### PR TITLE
apply patch e5cd87be4cb39eb38959cbdf9bc4ac0515c19657, and fix its bui…

### PR DESCRIPTION
**Pull request by wonleing**
…ld error

**What this PR does / why we need it**:
This PR originally comes from https://github.com/kubevirt/kubevirt/pull/4384
wangzh21 provide a fix for sound card support on kubevirt. But this fix is not accepted and after such a long time it cannot compile. I make it comiple and merge it to latest code, hope it can be merged into kubevirt master.
If origianl fix has problem, we can try to fix it later.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #https://github.com/kubevirt/kubevirt/pull/4384

**Special notes for your reviewer**:

**Release note**:

```release-note
sound card support on kubevirt. 
make it comiple and port it to latest code
```

### CODE REVIEW

**Comment by wonleing** [comment]
> > Not for now.
> 
> Great!
> 
> > I am wondering your PR is software emulation soundcard or pass through hardware soundcard?
> 
> QEMU's sound card emulation. #6650 is a subset of this PR to limit what we support in KubeVirt and simplify the user interface.
> 
> Would it be fine to close this one so we can move forward with #6650?

OK, please close this PR

**Comment by victortoso** [comment]
> OK, please close this PR

I can't. Either you do it (owner of PR) or someone with the right privileges, @rmohr ?

Cheers,

**Comment by rmohr** [comment]
@victortoso Anyone who is in the kubevirt org can write `/close` :)

**Pull request closed without merging**
