### PR TITLE
[release-1.1] Enables using scripts to modify VMI definition

### PR DESCRIPTION
**Pull request by dharmit**
**What this PR does / why we need it**:
Backports #10479 and #10599 to 1.1

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
Enables using scripts to modify VMI definition
```

### CODE REVIEW

**Comment by dharmit** [comment]
I backported the two PRs mentioned in description using `git cherry-pick <commit-sha> -m 1`, and then squashed them into one. I don't know if there's a specific process being followed to backport on the KubeVirt repo. Please correct me if I'm wrong.

@victortoso @xpivarc

**Comment by dharmit** [comment]
Thinking out loud - is a feature backport (like this PR) OK to do? I'm guessing it's not. More so since 1.1.0-rc is also out. So when could this be available to the users? 1.2?

**Comment by victortoso** [comment]
> Thinking out loud - is a feature backport (like this PR) OK to do?

Sorry, I'm not sure.

/cc @acardace @fabiand

**Comment by victortoso** [comment]
> Sorry, I'm not sure.

Just to clarify. This PR, at this moment, is backporting only https://github.com/kubevirt/kubevirt/pull/10599 which is but a simple fix.

You wish to bring https://github.com/kubevirt/kubevirt/pull/10479 to v1.1 and the question is this can be marked as exception to the feature-freeze

The main logic is 96402deeb2c6797c5edede203174f19e365680a8 which indeed is not part of v1.1.0-rc.0

**Comment by dharmit** [comment]
> This PR, at this moment, is backporting only #10599 which is but a simple fix.

Nope, it's backporting both the PRs. I squashed them into one commit.

> the question is this can be marked as exception to the feature-freeze

Yeah, I guess so. I realized it after opening the PR that 1.1.0-rc has already been cut. :)

**Comment by alicefr** [comment]
@dharmit I share @victortoso's concern about backporting this. Do we have any urgency?

**Comment by dharmit** [comment]
> @dharmit I share @victortoso's concern about backporting this. Do we have any urgency?

Nope, it's not urgent. Just to clarify, I opened this PR because I didn't:
1. know that backporting a feature is not a thing.
2. notice that 1.1 rc was cut.

/close

**Comment by victortoso** [comment]
> Nope, it's backporting both the PRs. I squashed them into one commit.

Ah, my bad. In the future I'd suggestion to simply `git cherry-pick -x` as that has a reference to original commit too.

**Comment by alicefr** [comment]
Probably we should also document how to do cherry picks. I don't recall we have it somewhere, maybe @aburdenthehand do you know?

**Comment by aburdenthehand** [comment]
@alicefr It's sort of mentioned in [kubevirt/docs/release-procedure.md](https://github.com/kubevirt/kubevirt/blob/main/docs/release-procedure.md#merging-to-release-branches) but only specifically relating to the release. 

Maybe something to add to our [developer contributor guide?](https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md)

**Pull request closed without merging**
