### PR TITLE
[Refactor] Validate `evictionStrategy` in KubeVirt Config Update

### PR DESCRIPTION
**Pull request by humblenginr**
**What this PR does / why we need it**:
KubeVirt currently allows the users to set the `spec.configuration.evictionStrategy` to be set to any value. This is, in a way, the root cause of issue #8421. This PR adds a rule in the KubeVirt CR admitter to make sure that only valid `evictionStrategy` values are allowed to be set. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by fossedihelm — COMMENTED** [review]
Thanks for your contribution! IMO, instead of manually checking the validity of the field, this can be simply addressed with [kubebuilder validation annotation](https://book.kubebuilder.io/reference/generating-crd.html#validation).
Placing 
```
// +kubebuilder:validation:Enum=None;LiveMigrate;External
```
on top of the `EvictionStrategy` field definition in the KubeVirtCR struct.
@rmohr @xpivarc Please chime in if this is not the right path.

**Comment by rmohr** [comment]
> Thanks for your contribution! IMO, instead of manually checking the validity of the field, this can be simply addressed with [kubebuilder validation annotation](https://book.kubebuilder.io/reference/generating-crd.html?highlight=kubebuilder:validation:Enum#validation). Placing
> 
> ```
> // +kubebuilder:validation:Enum=None;LiveMigrate;External
> ```
> 
> on top of the `EvictionStrategy` field definition in the KubeVirtCR struct. @rmohr @xpivarc Please chime in if this is not the right path.

If our openapi validation in the webhook itself picks this up as well, we are good (there I mean, that we may already have published the new CR spec, but e.g. virt-api still not updated, we should reject based on the webhook validation in our virt-api webhook).

This is required to allow the following update flow:

 * CR gets updated first to, then we update bottom-up
 * virt-handler first, then virt-controller (both can now already make use of new status fields because of the CR update)
 * virt-api updated at the end (on the spec -- not status -- it will still based on its internal view block unknown fields or unknown enums, even if the CR already allows it).
 
This flow ensures that operators can already add more information to the status without facing any issues, but users can only make use of new fields and features once the full update is done.

For as long as this remains, then we are good.

**Comment by acardace** [comment]
@sudo-NithishKarthik we already use kubebuilder validations in other places for our CRDs, can you change the PR as @fossedihelm suggested?

**Comment by xpivarc** [comment]
One more thing which was not mentioned is that this is not enough. A Kubevirt CR can be created before we have the webhook running and therefore the code should handle invalid cases. But this is still good.

**Comment by sudo-NithishKarthik** [comment]
I will update the PR

**Comment by dharmit** [comment]
> I will update the PR

@humblenginr are you planning to take this PR further? If not, I'd like to pick it up.

**Pull request closed without merging**
