### PR TITLE
Fix virtio hash in WORKSPACE

### PR DESCRIPTION
**Pull request by petrkotas**
**What this PR does / why we need it**:
Fixes the wrong image hash in WORKSPACE
@cynepco3hahue please review

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/2112)

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by slintes** [comment]
would it make sense to use the versioned one from https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.164-2/ and update on demand? This breaks all builds atm.

**Comment by cynepco3hahue** [comment]
@petrkotas Can you please change according to the Marc proposal?

**Pull request merged**
