### PR TITLE
User Kubernetes 1.6.6 in the Vagrant deployment

### PR DESCRIPTION
**Pull request by rmohr**
Make sure, we don't use Kubernetes 1.7, until [1] is fixed or we know a
workaround for it.

[1] https://github.com/kubernetes/kubeadm/issues/335

### CODE REVIEW

**Comment by stu-gott** [comment]
A fix is already in the kubernetes git repo. Is this still something we'd want to merge?

**Comment by admiyo** [comment]
Do not merge.  1.7 fix is released.

**Comment by rmohr** [comment]
We have to wait for 1.7.1 for the fix. I want to try out the proposed workarounds.

**Comment by rmohr** [comment]
Closing this in favor of #292

**Pull request closed without merging**
