### PR TITLE
volume migration: refuse to update the VM if the migration volume strategy is set and the VM is off

### PR DESCRIPTION
**Pull request by alicefr**
### What this PR does
Before this PR:
It was possible to update the VM spec with the migration volume strategy while the VM is off. Volume migration is only possible when the VM is running. This could lead the VM in an inconsistent state

After this PR:
Refuse to update the VM if the volume migration strategy is set but the VM is stopped.

The result if you update the VM with the `updateVolumesStrategy: Migration`: 
```
The request is invalid: : Cannot update the volumes with migration if the VM is off
```

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by mhenriks** [comment]
> This could lead the VM in an inconsistent state

Can you talk more about this?  Maybe give an example?

This change will also prevent a user from "queuing up" a migration that will start when the VM is started

**Comment by alicefr** [comment]
> > This could lead the VM in an inconsistent state
> 
> Can you talk more about this? Maybe give an example?
> 
> This change will also prevent a user from "queuing up" a migration that will start when the VM is started

Sure.
Queuing currently doesn't work for several reasons. First, the VMI doesn't exist and we deduce the migrated volumes by comparing the VM (with the new volumes) and the VMI (with the old volumes).  For some reasons, also getting the old spec [here](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/watch/vm.go#L1757) didn't work and the spec were empty. 

I would say that currently we don't support queuing and it is an improvement we could add later. I think this can be fixed but it wasn't straightforward. 
The webhooks prevents that the user does the update of the volumes while the VM is off and the copy cannot take place. Without this, the volumes are simply replaced and at the next start we get "no bootable device" for the destination volume

**Comment by mhenriks** [comment]
> Queuing currently doesn't work for several reasons. First, the VMI doesn't exist and we deduce the migrated volumes by comparing the VM (with the new volumes) and the VMI (with the old volumes). For some reasons, also getting the old spec [here](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/watch/vm.go#L1757) didn't work for me and the spec were empty.

> I would say that currently we don't support queuing and it is an improvement we could add later. I think this can be fixed but it wasn't straightforward.

If what you say above is true, that the vm controller cannot detect changed volumes without a VMI, then I think we may have a fundamental design flaw.  Wow could we possibly fix that?

> The webhooks prevents that the user does the update of the volumes while the VM is off and the copy cannot take place. Without this, the volumes are simply replaced and at the next start we get "no bootable device" for the destination volume

The obvious problem with webhooks is that they are racy.  The VM may be stopped right after the volumes are updated and before the controller reconciles leading us back to the problem I think you are trying to avoid

**Comment by mhenriks** [comment]
> Well, this isn't a problem. If the VM is stopped then the VMI will be deleted and any ongoing migration will be deleted as well. The VM has in its status the migrated volumes (fixed by https://github.com/kubevirt/kubevirt/pull/12355), so the user can recover from the shutdown

The VM may not be reconciled until both updates (volumes and shutdown) are processed by the webhook and the VMI is deleted (migration may have never been created).  Can you still guarantee that the VM status would be updated appropriately?

**Comment by alicefr** [comment]
@mhenriks I think the problem here is different. Even without the webhook, we can have an update and then immediately a shutdown. It is also not the case that the webhook wants to prevent.

The situation I want to avoid is when the VM is shutdown and the user tries to migrate. This can happen in 2 cases:
1. We shutdown the VM at the same time we do the update. RunStrategy == Halted and the volume migration. 
2. We do the shutdown, RunStrategy == Halted and then the volume migration (always with RunStrategy == Halted)

So, the controller previously needs to process the shutdown and then the volume migration. The webhook simply avoids the update based on the current spec of the VM. Do you think this is still an issue?

**Comment by mhenriks** [comment]
> So, the controller previously needs to process the shutdown and then the volume migration. The webhook simply avoids the update based on the current spec of the VM. Do you think this is still an issue?

Not an issue per-se I get how this could reduce the time a VM is in a funky state

I guess my main point is that we should try not to care about the ordering of operations and if we have to deal with migration start and immediate VM stop why not handle VM stop followed by migration start

**Comment by alicefr** [comment]
> > So, the controller previously needs to process the shutdown and then the volume migration. The webhook simply avoids the update based on the current spec of the VM. Do you think this is still an issue?
> 
> Not an issue per-se I get how this could reduce the time a VM is in a funky state
> 
> I guess my main point is that we should try not to care about the ordering of operations and if we have to deal with migration start and immediate VM stop why not handle VM stop followed by migration start

Yes, this doesn't. It really only checks the run strategy in the spec if the update volume strategy is set to migration

**Pull request closed without merging**
