### PR TITLE
[release-0.44] Pre-pull custom kernel / initrd as an init container

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
Manual backport of https://github.com/kubevirt/kubevirt/pull/6589

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

The PR has a merge conflict.

**Comment by xpivarc** [comment]
> /hold
> 
> The PR has a merge conflict.
Thanks, should be fixed.

**Comment by xpivarc** [comment]
@enp0s3 Can you have a look, please?

**Pull request merged**
