### PR TITLE
Deprecate Skips, it should be handled by labels

### PR DESCRIPTION
**Pull request by xpivarc**
### What this PR does
Deprecate Skips, it should be handled by labels. This helps us and users of our suite to fight shadow skips.

Fixes #

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
Related https://github.com/kubevirt/kubevirt/issues/9804

**Comment by xpivarc** [comment]
> There are some specific skip functions spread in the test files (e.g. `skipIfSwapOff`). Should we cover that deprecation here too?

I will submit a PR to remove those decentralized ones

**Review by jean-edouard — COMMENTED** [review]
/approve

**Review by fossedihelm — APPROVED** [review]
/unhold

**Pull request merged**
