### PR TITLE
Fix serial test labels to use uppercase for first letter

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:
Fixes the serial test label for two tests so that the regular expression matches them. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
/lgtm
@dhiller Is it possible to have a check for this?

**Comment by dhiller** [comment]
> /lgtm @dhiller Is it possible to have a check for this?

Good question. I guess that a simple regular expression check matching on the several used tags could be useful here.

**Comment by dhiller** [comment]
> > /lgtm @dhiller Is it possible to have a check for this?
> 
> Good question. I guess that a simple regular expression check matching on the several used tags could be useful here.

@xpivarc my first quick idea was trying a shell grep on the test names like this:
```
$ find tests -name '*.go' -type f | xargs grep -E '(Context|It|Describe)\(' | grep -oE '\[.*\]' | sed 's/]/]\n/g' | grep -E '\[.*\]' | grep -Ev '\[((test_id|rfe_id)\:([0-9]+|TODO)|(vendor|crit|level|posneg|label):.*|sig-[a-z-]+|Serial|rook-ceph|QUARANTINE|arm64|release-blocker|Conformance|IPv[46]|outside_connectivity|verify-nonroot|small|Sysprep)\]'
[ref_id:139]
[ref_id:142]
[ref_id:2293]
[ref_id:5105]
[ref_id:1182]
[ref_id:2065]
[ref_id:2717]
[flaky]
```
The remaining matches are either obsolete or clear errors, so this might already be good enough. @rmohr WDYT?

**Comment by rmohr** [comment]
> > > /lgtm @dhiller Is it possible to have a check for this?
> > 
> > 
> > Good question. I guess that a simple regular expression check matching on the several used tags could be useful here.
> 
> @xpivarc my first quick idea was trying a shell grep on the test names like this:

Having a check (prefarrably in go) which reads the test descriptions and validates if tags are known would be great.

**Comment by rmohr** [comment]
> Having a check (prefarrably in go) which reads the test descriptions and validates if tags are known would be great.

An easy way would be detecting them on the reporter hooks. So during a normal test run we can ceck the description for tags and fail if unkown tags are included.

**Comment by dhiller** [comment]
> > > > /lgtm @dhiller Is it possible to have a check for this?
> > > 
> > > 
> > > Good question. I guess that a simple regular expression check matching on the several used tags could be useful here.
> > 
> > 
> > @xpivarc my first quick idea was trying a shell grep on the test names like this:
> 
> Having a check (prefarrably in go) which reads the test descriptions and validates if tags are known would be great.

Absolutely, currently looking into this.

**Comment by dhiller** [comment]
> > Having a check (prefarrably in go) which reads the test descriptions and validates if tags are known would be great.
> 
> An easy way would be detecting them on the reporter hooks. So during a normal test run we can ceck the description for tags and fail if unkown tags are included.

Wouldn't it make more sense to even check the labels before the tests are compiled? So they would just not be executed, thus avoiding to waste resources?

**Comment by rmohr** [comment]
> Wouldn't it make more sense to even check the labels before the tests are compiled? So they would just not be executed, thus avoiding to waste resources?

In theory yes, in practice it is hard. Even if you analyze the syntax tree, I can easily confuse any tool. Just consider an example like this:

```go

func MyDescribe(string prefix) {
    Describe(prefix + "something")
}


MyDescribe("[invalid]")
```

The advantage is, when using the reporter entrypoints, that you know for sure that the description which you pass in is complete and fully expanded.

**Pull request merged**
