### PR TITLE
[migration_test]: decrease stressLargeVMSize to 400M

### PR DESCRIPTION
**Pull request by iholder-redhat**
This PR is a continuation of the last PR (https://github.com/kubevirt/kubevirt/pull/5714) to take test 5004 out of quarantine.
Seems that the `stress` command fails on OOM. This is probably due to the fact the fedora images are always increase in size while our memory request (which is currently `1Gi`) stays as is.

There is no reason to use this much memory. 400 Mbs should be enough in order for post-copy to appear, especially when we set our seconds per Gigabyte to `1` in the tests (which means that the total time this migration needs to hang is maximum 1-2 seconds).

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by fgimenez — COMMENTED** [review]
/lgtm

Thanks! If some (5?) retests go well we need to remember to readd the quarantine label before merging.

**Comment by iholder-redhat** [comment]
Lanes fail on tests that not related to this PR (`test_id:3468` failed on `tests/vm_watch_test.go`)

/test pull-kubevirt-e2e-k8s-1.19-sig-compute pull-kubevirt-e2e-k8s-1.20-sig-compute

**Comment by iholder-redhat** [comment]
Once again, `[test_id:3468]` is the only test that failed. 3 more to go.
/test pull-kubevirt-e2e-k8s-1.20-sig-compute pull-kubevirt-e2e-k8s-1.19-sig-compute
/test pull-kubevirt-check-tests-for-flakes

**Comment by iholder-redhat** [comment]
Only test that failed (for 1.19-sig-compute) is `test_id:3145` from `tests/operator_test.go`.
2 more to go.
/test pull-kubevirt-e2e-k8s-1.20-sig-compute pull-kubevirt-e2e-k8s-1.19-sig-compute

**Comment by iholder-redhat** [comment]
1 more to go.
/test pull-kubevirt-e2e-k8s-1.20-sig-compute pull-kubevirt-e2e-k8s-1.19-sig-compute

**Comment by vladikr** [comment]
/approve
Great. Thanks for looking into this!

**Pull request merged**
