### PR TITLE
Remove Zvi from the list of reviewers

### PR DESCRIPTION
**Pull request by zcahana**
**What this PR does / why we need it**:

Follow up to #7351, also remove me from the list of reviewers.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
The commit is not signed but looks good otherwise.

**Comment by rmohr** [comment]
FYI github has a partial outage: https://www.githubstatus.com/. The PR should be fine now. :+1:

**Comment by dhiller** [comment]
@zcahana all the best to you, good luck with your new endeavours!

**Pull request merged**
