### PR TITLE
[WIP] Fetch events and logs from functional tests

### PR DESCRIPTION
**Pull request by rmohr**
Not yet done, but it already fetches logs and events.

Missing:
 * Consistent log formatting
 * Sorting logs according to time stamp
 * Fetching logs from kube-system components

### CODE REVIEW

**Comment by fabiand** [comment]
@rmohr where do we stand here?

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
@admiyo added everything I have.

**Comment by davidvossel** [comment]
as per #529, each container's log can be scraped from /var/log/containers in our vagrant test setup.

I'm closing this PR for now. Feel free to re-open later if necessary.

**Pull request closed without merging**
