### PR TITLE
[WIP] Add new kubevirt metrics

### PR DESCRIPTION
**Pull request by yuvalturg**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by fabiand** [comment]
@yuvalturg please add a release note - I think this is release note worthy

**Comment by sradco** [comment]
@andreyod Will you be able to review this PR please?

**Comment by fabiand** [comment]
What else is needed for this PR to move it forward?

**Comment by yuvalturg** [comment]
> What else is needed for this PR to move it forward?

We are breaking this into multiple PRs, the first one (#4965) was merged

**Comment by yuvalturg** [comment]
We split this to multiple PRs #5096 #5128 #5191.  The storage metrics will be covered in another PR

**Pull request closed without merging**
