### PR TITLE
Add [Serial] tag to test_id:5004

### PR DESCRIPTION
**Pull request by iholder-redhat**
Signed-off-by: Itamar Holder <iholder@redhat.com>

**What this PR does / why we need it**:
This test has been flakie on periodic lanes for a while although stable on pre-submit lanes.
This is another attempt to stabilize the test in periodic lanes - making it not run in parallel by adding `[Serial]` tag to the test.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder-redhat** [comment]
@fgimenez I think that because of this tests' long history of passing presubmits we can save the time and merge it after lanes will pass once. Then we'll keep our eyes open on periodics.

**Comment by fgimenez** [comment]
> @fgimenez I think that because of this tests' long history of passing presubmits we can save the time and merge it after lanes will pass once. Then we'll keep our eyes open on periodics.

Makes sense to me :+1:

**Review by fgimenez — COMMENTED** [review]
/lgtm

**Comment by iholder-redhat** [comment]
all migration tests are under `Describe("[Serial]....,`
Unfortunately this makes this PR redundant.
/close

**Pull request closed without merging**
