### PR TITLE
WIP: Add support for InitContainers

### PR DESCRIPTION
**Pull request by senior7515**
Trying to get early feedback if this will be accepted. 

Signed-off-by: Alexander Gallego <gallego.alexx@gmail.com>

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by senior7515** [comment]
@fabiand and @rmohr  - trying to come up w/ some functest for this. Any suggestions - can something as basic as `echo 'hello world'` on an initcontainer would be helpful? 

Do you have a suggestion on how to capture the output of a container, some direction is greatly appreciated... i'll keep poking through the source code. thanks!

**Comment by senior7515** [comment]
self: need to add hostPID to support my use case.

**Comment by fabiand** [comment]
Another idea would be to modify the network namespace (it's pod wide), i.e. create a dummy interface

**Comment by rmohr** [comment]
> Trying to get early feedback if this will be accepted.

I am still not sure about the use-cases you want to solve with this. Can you outline a few? I am trying to make sure that these use-cases are working with how the vm runs inside the pod and with how much the vm can interact with pod resources. If they are legitimate, I would be happy to accept this.

**Comment by senior7515** [comment]
hi @rmohr  - yeah, writing up a quick `design' doc for you this morning.

**Comment by senior7515** [comment]
Hi Guys, here is a quick overview of our use cases - i wrote 3, I'm sure I could come up w/ another 5.

@rmohr https://docs.google.com/document/d/1xwRs9X92ogFB5MaKZo-yFt0i55IYf4kaHx0w4xyEUfM/edit#

@fabiand  ^^

**Comment by davidvossel** [comment]
@senior7515 Thanks for the contribution! I definitely see the value allowing users to tap into the VM launch flow and introduce their own custom logic. InitContainers are one way of offering an extension point, but they do come with some drawbacks that we should be aware of. 

One drawback is privilege escalation. Users who post the VM manifest may or may not have the privileges necessary to launch the corresponding virt-launcher pod. The pod is created on the user’s behalf by virt-controller in a very controlled way. Users can’t directly influence anything going on in that pod except through modifying the VM API. If we allow users to attach an initContiner to the VM manifest, then we’re allowing them to execute custom logic within an environment they might not have privileges to modify.

The second drawback is we won't be able to offer any reasonable guarantee that we won’t break the logic a user invests in a initContainer.  For example, a user might use an initContainer to modify qemu.conf, but then virt-launcher could stomp on those changes later on.

With all that said, I know there will be use cases where an initContainer is really the only solution. 

I doubt we can officially support initContainers, but we could still consider introducing this logic as an unsupported feature.  If we did that, we'd likely want to consider storing the initContainers as an annotation on the VM object rather than fields directly within the VM spec. We'd also want to feature gate use of initContainers using the kube-config configmap. 

just some things to think about :) I know we'll talk more about this soon.

**Comment by davidvossel** [comment]
@senior7515 thanks for the patch and spawning the interesting conversation around lifecycle hooks. 

Since it looks like we're going to move in the direction having users create their own mutating webhooks in order to modify the Pod spec, I'm going to close this for now.

Feel free to re-open if there's more we should sort through here

**Pull request closed without merging**
