### PR TITLE
Rel23 secure workloads

### PR DESCRIPTION
**Pull request by stu-gott**
Cherry pick of https://github.com/kubevirt/kubevirt/pull/2976

Add uninstall strategies to virt-operator

```release-note
Add `spec.uninstallStrategy` to the KubeVirt CRD, to optionally deny uninstall requests for as long as kubevirt workloads are in the cluster.
```

### CODE REVIEW

**Comment by fabiand** [comment]
/hold

The reason is: We initially came up with this to avoid VMs getting deleted - because we saw this - but the root cause was something else, and not what we are fixing here.
Nevertheless this feature is a major improvement to secure workloads.

**Comment by dankenigsberg** [comment]
As Red Hatters, at this stage we should not backport without a blocker bug.

I welcome this change, but we have KNIP-1218 planned to do it on cnv-2.3, not now.

/hold please.

**Comment by stu-gott** [comment]
Closing PR per previous comments

**Comment by rmohr** [comment]
> As Red Hatters, at this stage we should not backport without a blocker bug.
> 
> I welcome this change, but we have plans to do this in a future release, not now.

:+1:

**Pull request closed without merging**
