### PR TITLE
ENV VAR for client-go scheme registration version

### PR DESCRIPTION
**Pull request by davidvossel**
This is a fix for anyone who is consuming the kubevirt client-go package and encounters the "multiple group-version-kinds associated with type *v1.KubeVirt, refusing to guess at one" error when using the controller-runtime packages. 

Example. ```export KUBEVIRT_CLIENT_GO_SCHEME_REGISTRATION_VERSION=v1alpha3``` would cause only the v1alpha3 api to be registered when using our KubeVirt v1 client-go package.

The larger issue here is KubeVirt is not generating it's client go using the standard client-gen tooling, which is why we end up in odd scenarios like this. While this workaround with the env var should unblock us now that we have both v1 and v1alpha3 apis supported, our long term approach should be to transition to something that is compatible with client-gen. This will take some time though. 

```release-note
KUBEVIRT_CLIENT_GO_SCHEME_REGISTRATION_VERSION env var for specifying exactly what client-go scheme version is registered
```

### CODE REVIEW

**Review by enp0s3 — APPROVED** [review]
Thank you
/lgtm

**Comment by rmohr** [comment]
/approve
/hold

/cc @nunnatsa 
/cc @tiraboschi 

giving this a hold until one of you confirms that this works for HCO.

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
