### PR TITLE
support for more than one conn for vnc

### LINKED ISSUE #10553: Support for multi vnc
**What happened**:
I use this solution to realize [VNC](https://kubevirt.io/2019/Access-Virtual-Machines-graphic-console-using-noVNC.html). There is only one activing url when I open more than one url for the same vm 

**What you expected to happen**:
I can open more than one vnc-url for the same vm

**How to reproduce it (as minimally and precisely as possible)**:
Please follow the [VNC](https://kubevirt.io/2019/Access-Virtual-Machines-graphic-console-using-noVNC.html) and you can get the same result.

### PR DESCRIPTION
**Pull request by matthewei**
Signed-off-by: shenwei_yewu@cmss.chinamobile.com

**What this PR does / why we need it**:
support for more than one conn for vnc
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10553

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by dhiller** [comment]
/test pull-kubevirt-e2e-k8s-1.28-sig-compute

@matthewei I can perform a code review but I don't feel comfortable in thoroughly reviewing it wrt functionality.

@acardace @stu-gott can you think of someone who is comfortable reviewing this one?

**Comment by dhiller** [comment]
@matthewei also I would expect to find some changes regarding unit tests and at least an e2e test that can verify the scenario.

**Comment by matthewei** [comment]
> /test pull-kubevirt-e2e-k8s-1.28-sig-compute
> 
> @matthewei I can perform a code review but I don't feel comfortable in thoroughly reviewing it wrt functionality.
> 
> @acardace @stu-gott can you think of someone who is comfortable reviewing this one?

get it. many thanks

**Comment by matthewei** [comment]
> @matthewei also I would expect to find some changes regarding unit tests and at least an e2e test that can verify the scenario.

actually, I didn't find any test case for vnc.

**Review by 0xFelix — COMMENTED** [review]
Can you please elaborate on what this is trying to achieve? It looks like you try to make calls to `func (t *ConsoleHandler) stream(...)` non-blocking? Usually this func would block the handlers from returning until the stream was closed. IIUC you can already call the API multiple times and open multiple streams, so what is this trying to solve? Also please add unit and E2E tests for your scenario.

**Comment by matthewei** [comment]
> Can you please elaborate on what this is trying to achieve? It looks like you try to make calls to `func (t *ConsoleHandler) stream(...)` non-blocking? Usually this func would block the handlers from returning until the stream was closed. IIUC you can already call the API multiple times and open multiple streams, so what is this trying to solve? Also please add unit and E2E tests for your scenario.

Hi @0xFelix , I just want to realize that the vm can allow more than one vnc connetciont for a vm. 
When I verificated the function of vnc and I found the current vnc only support for one vnc. I would lost the old connection when I created a new connection. So I analysed the origin code and I found that we should keep the old connection.

**Comment by matthewei** [comment]
I found that i made mistakes I will raise another PR for it. I will close this PR.

**Pull request closed without merging**
