### PR TITLE
Bump kubevirt.io/containerized-data-importer-api to v1.47.0

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Latest CDI api has much less dependencies. Update to get it into our api package.

The critical change is from 	`kubevirt.io/controller-lifecycle-operator-sdk` to `kubevirt.io/controller-lifecycle-operator-sdk/api`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Pull in cdi dependencies with minimized transitive dependencies to ease API adoption
```

### CODE REVIEW

**Comment by EdDev** [comment]
Is this also fixing https://github.com/kubevirt/kubevirt/issues/7573 ?

**Comment by EdDev** [comment]
I must admit, I am surprised that kubevirt/kubevirt is dependents on CDI, I thought CDI is an addon that is only dependent on in e2e tests.

**Review by xpivarc — COMMENTED** [review]
/retest
/approve

**Pull request merged**
