### PR TITLE
tests/io_utils: move *FaultyDisk functions to their only user

### PR DESCRIPTION
**Pull request by dankenigsberg**
Similarly to tests/utils, tests/io_utils is a problematic file as it lumps together unrelated functions and dumps them in a catch-all package "tests". This PR moves two of these functions to the only test files that uses them.

```release-note
NONE
```

/kind cleanup
/cc @alromeros

### CODE REVIEW

**Review by enp0s3 — CHANGES_REQUESTED** [review]
@dankenigsberg Thanks for taking care of it
Can you please submit the `make generate` changes?

**Comment by dankenigsberg** [comment]
> @dankenigsberg Thanks for taking care of it Can you please submit the `make generate` changes?

Sorry for the noise I'm generating. One day will I understand why we keep auto-generated files in git.

**Comment by alicefr** [comment]
Looks good, thanks!
/approve

**Review by 0xFelix — COMMENTED** [review]
/approve

Thanks!

**Pull request merged**
