### PR TITLE
Cloud-Init network data referenced by NetworkDataSecretRef does not work

### PR DESCRIPTION
**Pull request by pbudds**
**What this PR does / why we need it**:
Cloud-Init network data referenced by NetworkDataSecretRef does not get propagated into the guest VM and this PR fixes that bug. 

**Release note**:

```release-note
Cloud-Init network data referenced by NetworkDataSecretRef in CloudInit config of VM definition does not propagate into the guest VM
```

### CODE REVIEW

**Comment by rmohr** [comment]
@pbudds thx for the PR.

@danielBelenky FYI in order to start tests for people which are not in the org (the needs-ok-to-test label applied), tests can be run by an explicit `/test [all]` or when the PR has a lgtm.

**Comment by pbudds** [comment]
> @pbudds thx for the PR.
> 
> @danielBelenky FYI in order to start tests for people which are not in the org (the needs-ok-to-test label applied), tests can be run by an explicit `/test [all]` or when the PR has a lgtm.

Thank you @rmohr and @danielBelenky for triggering the tests. The current failures seem unrelated this change to the best of my knowledge. Another try of tests maybe? Please advice on next steps.

**Comment by rmohr** [comment]
@pbudds sorry, the PR fell of my radar. Looks excellent.

**Comment by pbudds** [comment]
Thank you Roman for the review and getting this merged in.

**Pull request merged**
