### PR TITLE
fix: example yaml cannot be verified by converting yaml to json

### PR DESCRIPTION
**Pull request by lvyanru8200**
Set the value of the url to string

**What this PR does / why we need it**:

Change the value of the url to make the sample yaml file deployable

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes https://github.com/kubevirt/kubevirt/issues/9549

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by lvyanru8200** [comment]
cc @fossedihelm

**Comment by fossedihelm** [comment]
Unfortunately, this does not solve the problem. The problem occurs only when trying to apply from a url.
For example:
`k apply -f exaples/vm-alpine-datavolume.yaml` works, but
`k apply -f https://github.com/kubevirt/kubevirt/blob/399ee15bc728a6f7975385d6b0473d752ba0f9dc/examples/vm-alpine-datavolume.yaml` does not work.

**Comment by lvyanru8200** [comment]
> 不幸的是，这并不能解决问题。仅当尝试从 url 申请时才会出现此问题。 例如： `k apply -f exaples/vm-alpine-datavolume.yaml`有效，但 `k apply -f https://github.com/kubevirt/kubevirt/blob/399ee15bc728a6f7975385d6b0473d752ba0f9dc/examples/vm-alpine-datavolume.yaml`无效。
use: 
     https://raw.githubusercontent.com/kubevirt/kubevirt/399ee15bc728a6f7975385d6b0473d752ba0f9dc/examples/vm-alpine-datavolume.yaml

**Comment by lvyanru8200** [comment]
> > 不幸的是，是这并不能解决问题。只有当尝试从 url 申请时才会出现此问题。例如：有效，但`k apply -f exaples/vm-alpine-datavolume.yaml`无效`k apply -f https://github.com/kubevirt/kubevirt/blob/399ee15bc728a6f7975385d6b0473d752ba0f9dc/examples/vm-alpine-datavolume.yaml`。
> > use: 
> > [https://raw.githubusercontent.com/kubevirt/kubevirt/399 ee15bc728a6f7975385d6b0473d752ba0f9dc / 示例 / vm-alpine-datavolume.yaml](https://raw.githubusercontent.com/kubevirt/kubevirt/399ee15bc728a6f7975385d6b0473d752ba0f9dc/examples/vm-alpine-datavolume.yaml)

I see, he should use raw format to apply

**Comment by fossedihelm** [comment]
Using https://raw.githubusercontent.com/kubevirt/kubevirt/399ee15bc728a6f7975385d6b0473d752ba0f9dc/examples/vm-alpine-datavolume.yaml it works.
But also the original https://raw.githubusercontent.com/kubevirt/kubevirt/main/examples/vm-alpine-datavolume.yaml
works.
Said that, I think we found the root cause of the issue. :)

**Pull request closed without merging**
