### PR TITLE
[release-0.58] device manager: externally provided mediated devices should not be removed

### PR DESCRIPTION
**Pull request by acardace**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
@acardace Seesm the cherry-pick did not go well. Can you have a second look?

**Comment by acardace** [comment]
@vladikr @xpivarc can you take a look at this?

I don't really know why the network tests are failing, on my local cluster they pass just fine.

**Comment by xpivarc** [comment]
@EdDev Can you have a look on these failures, please?

**Comment by EdDev** [comment]
> @EdDev Can you have a look on these failures, please?

What did I miss? Do you still have links to the failing jobs?

**Comment by xpivarc** [comment]
> > @EdDev Can you have a look on these failures, please?
> 
> What did I miss? Do you still have links to the failing jobs?

I had a look on this in the end and it was a infra issue. We will investigate why it is happening.

**Pull request merged**
