### PR TITLE
Revert node-labeller from master

### PR DESCRIPTION
**Pull request by ksimon1**
**What this PR does / why we need it**:
Since the node-labeller was only partially
integrated in master, the full feature set
is only available if the standalone node-labeller
is deployed via its operator. This operator
conflicts with the virt-operator. To avoid this
conflict, we revert the node-labeller parts in master.
**Release note**:
```NONE

```
//cc @stu-gott 
Signed-off-by: Karel Simon <ksimon@redhat.com>

### CODE REVIEW

**Comment by davidvossel** [comment]
/hold

I want to review this

**Comment by vladikr** [comment]
@ksimon1 @omeryahud I'm curious. Are we planing to revert this revert at some point?

**Comment by ksimon1** [comment]
@vladikr yes definitely. But currently we have other more urgent tasks which we have to finish.

**Pull request merged**
