### PR TITLE
modules: Run 'make deps-update'

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
Updated `go.mod` file by running `make deps-update`.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Review by lyarwood — APPROVED** [review]
/lgtm

**Comment by rmohr** [comment]
@iholder-redhat I think we can proceed with making the `pull-kubevirt-verify-go-mod ` job required. Or were there any objections on the mailing list? Would be happy if you proceed with that.

**Comment by rmohr** [comment]
> I think it would have been better to first merge this commit and then later make this job required because of PRs that are blocked waiting for this fix

Yes definitely! :)

**Comment by iholder-redhat** [comment]
> @iholder-redhat I think we can proceed with making the `pull-kubevirt-verify-go-mod ` job required. Or were there any objections on the mailing list? Would be happy if you proceed with that.

Right, I fully agree!
I don't remember any objections, but would take another look.

Will get to it soon :)

**Comment by ShellyKa13** [comment]
Can anything be done to make this PR get merge as soon as possible? check if the test failures are relevant to change and if not just let it get in? It blocks at least 2 approved PRs

**Comment by akrejcir** [comment]
This PR does not change any functionality. It just moves a line from one `require` block to another.
Test failures are not related to it.

**Comment by rmohr** [comment]
> Can anything be done to make this PR get merge as soon as possible? check if the test failures are relevant to change and if not just let it get in? It blocks at least 2 approved PRs

The job is not required. It does not block PRs afaik.

**Comment by rmohr** [comment]
Force-merging to resolve the uncertainties :)

**Pull request merged**
