### PR TITLE
Add ocs rbd storageClass for downstream testing

### PR DESCRIPTION
**Pull request by duyanyan**
**What this PR does / why we need it**:
Add ocs rbd storageClass for downstream testing, currently the tests only could be running on "rook-ceph.rbd.csi.ceph.com", "csi-rbdplugin" storage class for upstream

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by rmohr** [comment]
@duyanyan can you run `make` and commit the correctly formatted code? The automatic formatting does not seem to be applied.

**Comment by duyanyan** [comment]
@awels  could you please review the PR?

**Review by enp0s3 — CHANGES_REQUESTED** [review]
Thank you!
Tested the PR-rebased release-0.36 tests against Openshift with Ceph and tests are not skipped.

**Review by enp0s3 — APPROVED** [review]
/lgtm
/approve

**Comment by awels** [comment]
In CDI we pass the name of the storage class we are interested in. For instance we have a --block-sc and tests that use block storage check if the passed in name exists, and if so they execute. Same for snapshot. This way we are more interested in the property of the storage class, than the name. IMO that is much nicer than trying to keep a list of storage classes that we know works in code. It of course makes the caller of the test binary aware that they need to pass the right names or the tests won't work.

**Comment by qinqon** [comment]
"""
/hold
until emergency CI fixes of #5207 are merged
"""

**Pull request merged**
