### PR TITLE
client-go, VMI: Add context to applicable methods 2

### PR DESCRIPTION
**Pull request by orelmisan**
**What this PR does / why we need it**:
This is a follow-up to PR #8908.
Currently, the `VirtualMachineInstance` methods that are using an underlying REST client, are not receiving a context, thus are unstoppable from the outside.

Internally they use `context.Background()` when calling the underlying REST client.

Add the `context` parameter to the VMI's applicable methods:
- Patch
- Watch
- Screenshot
- Pause
- Unpause

Add the `context.Background()` to all calls to these methods.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Partially fixes issue #8885.

**Special notes for your reviewer**:

**Release note**:

```release-note
client-go: Added context to additional VirtualMachineInstance's methods.
```

### CODE REVIEW

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/e98947cbb0e11283699b45c1062963e7e2d5e403..aadb6ef77135688f617c1ae5a953a8794d9fcdd7): Used the context in the Screenshot method.

**Review by RamLavi — APPROVED** [review]
/lgtm

**Review by xpivarc — APPROVED** [review]

**Pull request merged**
