### PR TITLE
Increase verbosity at selinux context run

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
Some commands return just the resutl code on the error that makes
difficult to debug problem, this change also add the command, stdout and
stderr to the error.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Some examples:
Here it just return `The failure to create the tap device only returned `exit status 1` with no additional info.
Journal logs: [https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev/1374300084186910721/artifacts/k8s-reporter/3/nodes/1_journal_node02.log
]- Pod log: https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev/1374300084186910721/artifacts/k8s-reporter/3/pods/1_kubevirt-test-default3_virt-launcher-testvmi-7tspg-7nwrh-compute.log
virt-handler log: https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev/1374300084186910721/artifacts/k8s-reporter/3/pods/1_kubevirt_virt-handler-xmxmq-virt-handler.log

Forced an error to see the output, this is the result

```
"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/vmi-masquerade","pos":"vm.go:1122","reason":"failed to configure vmi network: Critical network error: error creating tap device named tap0; failed to execute command in launcher namespace 150226: failed running command /usr/bin/virt-chroot create-tap --tp-name tap0 --uid 0 --gid 0 --queue-number 0 --mtu 1480, err: exit status 1, output: Error: unknown flag: --tp-name\nUsage:\n  virt-chroot create-tap [flags]\n\nFlags:\n      --gid uint              the group of the owner of the tap device\n  -h, --help                  help for create-tap\n      --mtu uint32            the link MTU of the tap device (default 1500)\n      --queue-number uint32   the number of queues to use on multi-queued devices\n      --tap-name string       the name of the tap device (default \"tap0\")\n      --uid uint              the owner of the tap device\n\nGlobal Flags:\n      --cpu uint32      cpu time in seconds for the process\n      --memory uint32   memory in megabyte for the process\n      --mount string    mount namespace to use\n      --user string     switch to this targetUser to e.g. drop privileges\n\nunknown flag: --tp-name\n","timestamp":"2021-03-25T07:22:43.716067Z"}
```

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by ormergi — APPROVED** [review]
Thanks!

**Comment by qinqon** [comment]
/retest

Looks like hiccup
```
16:48: [205 / 588] GoCompilePkg vendor/github.com/gogo/protobuf/proto/go_default_library.a; 1s remote-cache, processwrapper-sandbox ... (7 actions, 6 running)
12:16:49: [225 / 588] GoCompilePkg vendor/google.golang.org/protobuf/internal/impl/go_default_library.a; 1s remote-cache, processwrapper-sandbox ... (7 actions, 6 running)
12:16:51: [249 / 588] GoCompilePkg vendor/k8s.io/client-go/transport/go_default_library.a; 0s remote-cache, processwrapper-sandbox ... (5 actions, 4 running)
12:16:52: ERROR: /home/prow/go/src/github.com/kubevirt/kubevirt/pkg/certificates/triple/cert/BUILD.bazel:3:11: GoCompilePkg pkg/certificates/triple/cert/go_default_library.a failed due to Exec failed due to IOException: null
12:16:52: com.google.devtools.build.lib.remote.BulkTransferException
12:16:52: 	at com.google.devtools.build.lib.remote.RemoteActionInputFetcher.prefetchFiles(RemoteActionInputFetcher.java:125)
12:16:52: 	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy$SpawnExecutionContextImpl.prefetchInputs(AbstractSpawnStrategy.java:232)
12:16:52: 	at com.google.devtools.build.lib.remote.RemoteSpawnCache.lookup(RemoteSpawnCache.java:243)
12:16:52: 	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:135)
12:16:52: 	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:102)
12:16:52: 	at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
12:16:52: 	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:65)
12:16:52: 	at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:331)
12:16:52: 	at com.google.devtools.build.lib.actions.Action.execute(Action.java:127)
12:16:52: 	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:859)
1
```

**Review by EdDev — APPROVED** [review]

**Comment by qinqon** [comment]
/hold

testing it locally

**Comment by qinqon** [comment]
/unhold 

Confirmed that the error does return only the result code on some cases

**Comment by qinqon** [comment]
/hold

PR to fix unit test is in progress

**Comment by qinqon** [comment]
/hold cancel

Unit test running again it will take the fix.

**Pull request merged**
