### PR TITLE
Fix cluster-up path: ./cluster-up/ -> ./kubevirtci/cluster-up/

### PR DESCRIPTION
**Pull request by iholder101**
### What this PR does
The path changed as part of https://github.com/kubevirt/kubevirt/pull/12872.

Before this PR:
Documentation points to the wrong path.

After this PR:
Documentation points to the right path.

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
@iholder101 I don't think this PR makes sense, since the kubevirtci folder is getting bumped automatically - these changes should be done in kubevirtci repo.

**Review by fossedihelm — COMMENTED** [review]
I think this is in sync with kubevirtci repo, so these changes will be overwritten

**Comment by fossedihelm** [comment]
> I think this is in sync with kubevirtci repo, so these changes will be overwritten

Note for me: read other comments before review :)

**Comment by iholder101** [comment]
> @iholder101 I don't think this PR makes sense, since the kubevirtci folder is getting bumped automatically - these changes should be done in kubevirtci repo.

Ah, thanks for pointing that out!
So IIUC we need to create a similar PR to modify https://github.com/kubevirt/kubevirtci/blob/main/cluster-up/cluster/README_VGPU.md?

Makes sense. Thank you @dhiller and sorry for the noise.

/close

**Pull request closed without merging**
