### PR TITLE
[release-0.53] Fix access to portforwarding on VMs/VMIs with the cluster roles kubevirt.io:[admin|edit]

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/9120

NOTE: bdfc5b57ae02dc9f28f112176f464c7f4ccefb62 was changed from a fix to a feat because the initial
commit adding the permission with the wrong method/verb is not in this
branch.

**Release note**:

```release-note
Fix access to portforwarding on VMs/VMIs with the cluster roles kubevirt.io:admin and kubevirt.io:edit
```

### CODE REVIEW

**Comment by lyarwood** [comment]
/lgtm

Thanks for the extra context in the commits!

**Comment by xpivarc** [comment]
/retest
@brianmcarey 
`docker: Error response from daemon: Get "https://quay.io/v2/": proxyconnect tcp: dial tcp 172.21.50.37:3128: connect: connection refused.` is there a problem?

**Comment by brianmcarey** [comment]
> /retest @brianmcarey `docker: Error response from daemon: Get "https://quay.io/v2/": proxyconnect tcp: dial tcp 172.21.50.37:3128: connect: connection refused.` is there a problem?

Yes there is an issue with the container image cache in the prow-control plane cluster - we will probably have to move the jobs to prow-workloads temporarily - similar to what we did with 0.58 - https://github.com/kubevirt/project-infra/commit/4486f2f626299fe9cb1ffe6009cfb4157efc7c87

**Pull request merged**
