### PR TITLE
[release-0.58]: make generate to switch copyright to 2023

### PR DESCRIPTION
**Pull request by iholder101**
**What this PR does / why we need it**:
Execute `make generate` to switch copyright to 2023

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by enp0s3 — APPROVED** [review]
/approve

**Comment by EdDev** [comment]
Thanks!

We seem to drag this for years now.
And I dare to say it is probably a bad workaround, but it is better than nothing.

**Pull request merged**
