### PR TITLE
set vcpus and memory for a running vmi

### PR DESCRIPTION
**Pull request by Icedroid**
**What this PR does / why we need it**:
We want to set vcpus and memory for a running vmi. 

Now kubevirt generate domain xml as follow:
```
  <memory unit='KiB'>16777216</memory>
  <currentMemory unit='KiB'>16777216</currentMemory>
  <vcpu placement='static'>16</vcpu>
```

If we want to dynamic change vm vcpus and memory, we must make domain xml like this:
```
  <memory unit='KiB'>16777216</memory>
  <currentMemory unit='KiB'>16777216</currentMemory>
  <vcpu placement='static' current='8'>16</vcpu>
```

We can scale-up or scale-down vmi current memory value, but current value can't be large than guest.memory or resources.limit.memory.

We only can scale-up vmi current cpu value and current value can't be large than guest.cpu.cores or resources.limit.cpu.

libvirt virsh setvcpus command can see follow:
https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainSetVcpusFlags

libvirt virsh setmem command can see follow:
https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainSetMemoryFlags

**Release note**:
```release-note
add support set vcpus and memory for a running vmi
```

### CODE REVIEW

**Comment by lyarwood** [comment]
Interesting idea but I have a few questions. 

- How does libvirt increase the vCPU count with `virDomainSetVcpusFlags` when we have provided the guest CPU topology? Does it just increment the total number of sockets, cores or threads?

- I couldn't find any attempt to increase the allocated resources for the `VirtualMachineInstance` resource itself and associated pods, 

- Could you write some integration tests to cover the above?

**Comment by alicefr** [comment]
@Icedroid did you try if this really works? My concerns here are that we rely on the pod resources for setting the number of CPU and memory. So, I'm not quite sure how you can modify the resource of the pod that are immutable. Could you please elaborate a bit more on your approach?

**Comment by Icedroid** [comment]
> Interesting idea but I have a few questions.
> 
> * How does libvirt increase the vCPU count with `virDomainSetVcpusFlags` when we have provided the guest CPU topology? Does it just increment the total number of sockets, cores or threads?
> * I couldn't find any attempt to increase the allocated resources for the `VirtualMachineInstance` resource itself and associated pods,
> * Could you write some integration tests to cover the above?

From libvirt document, we know if processor topology is specified, we can't chage vmi vcpus. 
And I don't know If only affect cores, So vmi must have a guest.cpu value?
> Note that hypervisors may not allow changing the maximum vcpu count if processor topology is specified.
https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainSetVcpusFlags

**Comment by Icedroid** [comment]
> @Icedroid did you try if this really works? My concerns here are that we rely on the pod resources for setting the number of CPUs and memory. So, I'm not quite sure how you can modify the resource of the pod that is immutable. Could you please elaborate a bit more on your approach?

I use virsh setvcpus and virsh setmem in a virt-launcher pod , it works. So I try to implement this for virtctl and virt-api.

**Comment by lyarwood** [comment]
> From libvirt document, we know if processor topology is specified, we can't chage vmi vcpus. And I don't know If only affect cores, So vmi must have a guest.cpu value?
> 
> > Note that hypervisors may not allow changing the maximum vcpu count if processor topology is specified.
> > https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainSetVcpusFlags

I'm pretty sure we always provide a topology defaulting to the number of vCPUs provided to cores so this isn't going to work: 

https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go#L277-L300

**Comment by alicefr** [comment]
> > From libvirt document, we know if processor topology is specified, we can't chage vmi vcpus. And I don't know If only affect cores, So vmi must have a guest.cpu value?
> > > Note that hypervisors may not allow changing the maximum vcpu count if processor topology is specified.
> > > https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainSetVcpusFlags
> 
> I'm pretty sure we always provide a topology defaulting the number of vCPUs provided to sockets so this isn't going to work:
> 
> https://github.com/kubevirt/kubevirt/blob/ddd08652b42882ef05527b6b2c40118d08a42d89/pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go#L277-L300

Well, here we are not even changing the number of vcpu in the VMI definition but directly using libvirt API. So, I'm really wondering if we have the additional resources available inside the pod and how this can work?
Afterwards, this isn't the correct way without passing through VMI mutator webhook and all the KubeVirt checks.

**Comment by lyarwood** [comment]
> Well, here we are not even changing the number of vcpu in the VMI definition but directly using libvirt API. So, I'm really wondering if we have the additional resources available inside the pod and how this can work? Afterwards, this isn't the correct way without passing through VMI mutator webhook and all the KubeVirt checks.

Agreed I also asked about that in my initial comment, I was also concerned that the Libvirt API would also not behave as expected given that we always pass down a guest visible topology to the domain.

**Comment by Icedroid** [comment]
> 
If only set vmi.Spec.Domain.CPU value, domain will not generate cpu topology, so will it work?

**Comment by Icedroid** [comment]
> > > From libvirt document, we know if processor topology is specified, we can't chage vmi vcpus. And I don't know If only affect cores, So vmi must have a guest.cpu value?
> > > > Note that hypervisors may not allow changing the maximum vcpu count if processor topology is specified.
> > > > https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainSetVcpusFlags
> > 
> > 
> > I'm pretty sure we always provide a topology defaulting the number of vCPUs provided to sockets so this isn't going to work:
> > https://github.com/kubevirt/kubevirt/blob/ddd08652b42882ef05527b6b2c40118d08a42d89/pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go#L277-L300
> 
> Well, here we are not even changing the number of vcpu in the VMI definition but directly using libvirt API. So, I'm really wondering if we have the additional resources available inside the pod and how this can work? Afterwards, this isn't the correct way without passing through VMI mutator webhook and all the KubeVirt checks.

Cloud list&watch domain vcpu and memory changing value, and  then patch to vmi?

**Comment by lyarwood** [comment]
> > 
> 
> If only set vmi.Spec.Domain.CPU value, domain will not generate cpu topology, so will it work?

The [`CPU`](https://kubevirt.io/api-reference/master/definitions.html#_v1_cpu) field of  [`DomainSpec`](https://kubevirt.io/api-reference/master/definitions.html#_v1_domainspec) always provides a topology. As I said before if you don't provide anything under `vmi.Spec.Domain.CPU` then a default topology of 1 socket, 1 core and 1 thread is applied.

**Pull request closed without merging**
