### PR TITLE
Fix block detection in ReplacePVCByHostDisk

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
@enp0s3 FYI

**Review by enp0s3 — APPROVED** [review]
/approve

**Pull request merged**
