### PR TITLE
[WIP]: add support to install kwok when running make cluster-sync

### LINKED ISSUE #11128: install kwok during make cluster-sync to work with simulated VMIs
**Is your feature request related to a problem? Please describe**:
sig-scale is working on integrating https://kwok.sigs.k8s.io/ for stress and scale testing the kubevirt stack. For this to work, there needs to be an option to install kwok in make cluster-sync

**Describe the solution you'd like**:
Running the following command should
```
KWOK_DEPLOY=true make cluster-up
```
1. install kwok stack to the kind cluster created by make cluster-sync
2. create the kubevirt related resources (role, rolebinding, stage vmi-ready, stage vmi-delete), similar to this https://github.com/kwok-ci/kubevirt-demo/tree/main/kustomize 

cc @rthallisey

### PR DESCRIPTION
**Pull request by alaypatel07**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #11128 

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by alaypatel07** [comment]
@xpivarc or @jean-edouard  I am wondering if this is the right way to bring static manifests in kubevirt. I see that most of the manifests are generated by `make manifest` can you guide how to best organize static manifests?

Other things are WIP so I will clean it up before this is ready for review

**Comment by xpivarc** [comment]
/cc @dhiller @brianmcarey 
Would you see this as KubevirtCI fit?

**Comment by brianmcarey** [comment]
> /cc @dhiller @brianmcarey Would you see this as KubevirtCI fit?

Yes this does look like it would fit better in kubevirtci. @alaypatel07 would you mind creating a PR over in [kubevirtci](https://github.com/kubevirt/kubevirtci) for this?

**Comment by alaypatel07** [comment]
@brianmcarey sig-scale needs to write an e2e test which needs setup of kwok. All the setup for e2e test like creating the cluster, setting up monitoring stack etc are done using `make cluster-up; make cluster-sync`. In order to follow the pattern, would it make sense to have - `DEPLOY_KWOK=true make cluster-sync` creat the required environment for e2e test?

Out of curiosity, why should this be in kubevirt CI?

**Comment by brianmcarey** [comment]
> @brianmcarey sig-scale needs to write an e2e test which needs setup of kwok. All the setup for e2e test like creating the cluster, setting up monitoring stack etc are done using `make cluster-up; make cluster-sync`. In order to follow the pattern, would it make sense to have - `DEPLOY_KWOK=true make cluster-sync` creat the required environment for e2e test?
> 
> Out of curiosity, why should this be in kubevirt CI?

`make cluster-sync` is generally used for deploying kubevirt onto the kubevirtci cluster.

I think it would be better to deploy kwok during `make cluster-up` like kubevirtci does for other supporting services like prometheus and grafana.

**Comment by alaypatel07** [comment]
closing in favor of https://github.com/kubevirt/kubevirtci/pull/1178

**Pull request closed without merging**
