### PR TITLE
[release-1.3] instancetype: Introduce PreferredEfi to API

### LINKED ISSUE #12743: Unable to configure EFI persistence from preferences
/area instancetype

This is being reported as a bug given the impact it is having on Windows  11 24H2 VMs using bitlocker encryption and the `windows.11` family of common-instancetype preferences. While a workaround does exist in the form of users manually configuring `EFI` from within their `VirtualMachine` it would be cleaner to land and backport the missing support in preferences in the longer term.

**What happened**:

At present prefernces have no way of configuring EFI persistence. The only available fields being `PreferredUseEFi` and `PreferredUseSecureBoot`, both poorly named bools. 

**What you expected to happen**:

Preferences should be able to configure EFI persistence and any future EFI configurables as they appear in the `VirtualMachine` API.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a Windows 11 24H2 `VirtualMachine` using both bitlocker encryption and the `windows.11` preference
*  Reboot the `VirtualMachine`
* `VirtualMachine` fails to reboot

**Additional context**:

Downstream private tracker: https://issues.redhat.com/browse/CNV-44264

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/cc @0xFelix 
/cc @acardace 

### What this PR does

This is a manual backport of #12739 and ca865468b7e9d5917e463d5147dae20637314ea1 from #12740 to avoid conflicts from this and any future instancetype backports.

Fixes #12743

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

https://github.com/kubevirt/kubevirt/blob/main/docs/release-branch-backporting.md#bug-fix-definition

IMHO this is a additive and thus backwardly compatible API change that is fixing a serious shortcoming in the preferences API.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
A new `PreferredEfi` field has been added to preferences to express the preferred `EFI` configuration for a given `VirtualMachine`.
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
The code looks good to me. However, this changes the API of a release version. Are the others fine with this change?

**Comment by lyarwood** [comment]
> The code looks good to me. However, this changes the API of a release version. Are the others fine with this change?

Forgot to include the following justification from the original PR:

https://github.com/kubevirt/kubevirt/blob/main/docs/release-branch-backporting.md#bug-fix-definition

IMHO this is a additive and thus backwardly compatible API change that is fixing a serious shortcoming in the preferences API.

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by acardace** [comment]
/approve
/hold
/cc @xpivarc 

I think this improves the maintainability of the release branch, thank you @lyarwood .
I'd just like to have a second approver looking at this since it is unusual that we backport api additions.

**Comment by xpivarc** [comment]
/hold cancel
This is will help to improve the instance types flow

**Pull request merged**
