### PR TITLE
Remove redundant parameter from virt-api tests

### PR DESCRIPTION
**Pull request by cynepco3hahue**
**What this PR does / why we need it**:
Should solve issues like https://travis-ci.org/qinqon/kubevirt/builds/469413568#L2568

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by davidvossel** [comment]
so for my own understanding, the tests run in parallel if we provide a channel object, but run in series otherwise?

**Comment by cynepco3hahue** [comment]
@davidvossel  If I understood it correct from ginkgo documentation yes.

**Comment by slintes** [comment]
mh, I think the tests still run in series. The done channel only makes a single test async with a timeout:
https://onsi.github.io/ginkgo/#asynchronous-tests
https://onsi.github.io/ginkgo/#parallel-specs

**Comment by qinqon** [comment]
So the test at virt-api has being running always sequencially ?

**Comment by cynepco3hahue** [comment]
> So the test at virt-api has being running always sequencially ?

Looks so, but anyway `Done` parameter is redundant here and it can be a bug in ginkgo, because I think it the only test that has this parameter and also the only one test that sometime fails.

**Pull request merged**
