### PR TITLE
Make migration job a separate container from virt-handler

### PR DESCRIPTION
**Pull request by davidvossel**
decouples migration job script from virt-handler

### CODE REVIEW

**Comment by berrange** [comment]
This is taking the code in the wrong direction and/or addressing the wrong problem with the current migration code. Rather than moving this migrate script to a separate container we need to be killing this script off entirely. The main virt-handler service on the node, which already has the connection to libvirt, should be directly invoking the Migrate() API call on the Domain object that it also already has a handle for. Invokation of virsh will just go away entirely.

**Comment by rmohr** [comment]
@berrange I would rather say, it is a possibility that it goes into the wrong direction. Please also read #154.

To me there are a few things to think about, what the right direction is:

 * How smart do we want to be while migrations? The smarter, the more cluster data is necessary, which means that the node needs more cluster information, which means access to data which it wouldn't need otherwise.
 * Do we want virt-handler to ever have to think about other nodes?
 * If locality is important, would it be sufficient to just place the imperative logic via the scheduler on the source node?

Independent of where we are going, it is a small and clean patch, which makes it clearer what we have at the moment, so I am in favour of taking  it in.

**Comment by berrange** [comment]
We're only talking about starting & monitoring the migration process here. The only info required about the remote host is what its hostname is, so that we can tell libvirtd where to connect. All the data required for actually monitoring & controlling the migration is done soley against the local libvirtd connection. 

The more complex logic for migration is dealing with figuring out where to migrate to, which is in the realm of the scheduler, and dealing with any target host setup which is already the responsibility of virt-handler when creating the POD to receive the incoming migration.

**Comment by rmohr** [comment]
> and dealing with any target host setup which is already the responsibility of virt-handler when creating the POD to receive the incoming migration.

That is not clean to me. Do you mean that the target virt-handler should create the Pod? Currently Kubernetes is scheduling and creating the target Pod for us.

**Comment by berrange** [comment]
No, I'm *not* saying the virt-handler should create the POD on the target host - I was just saying that it responds to the creation of the POD done by k8s schedular in the normal way on migrate target host, but doesn't tell to libvirt spawn QEMU. 

The change I'm talking about here is simply that the virt-handler on the source host should directly talk to libvirt to initiate & run the migration, once the target pod is ready to accept it.

**Comment by rmohr** [comment]
I actually wanted to write "clear" instead of "clean"

**Comment by davidvossel** [comment]
I agree there needs to be a larger discussion around the long term approach we use for migrations.  This is not the forum for that though. Please take it to the mailing list or issue tracker.

The goal of this patch is to merely clean up some non-obvious usage of multiple entry points in the virt-handler container.  This isn't moving the migration logic in any further direction other than making it a little more explicit what exactly is going on... It actually took me a bit to figure out what was going on when I was investigating this for the first time, which is why I had this task on my TODO list.

@berrange If anything, this patch makes it slightly easier to remove the migration script in the future if we want. We just delete the cmd/virt-migration directory when we're ready to make the switch.

**Comment by davidvossel** [comment]
i'll merge this after i fix the merge conflict.

**Comment by stu-gott** [comment]
@davidvossel good catch on making virt-migrator a docker_image vs binary. I missed that.

**Pull request merged**
