### PR TITLE
tests: Extract node related helpers to a dedicated package

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

`utils` is overloaded with multiple functionalities which makes it hard
to properly maintain its content.

Place node helpers under `libnode` package.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
~~Depends on #7439~~

Implemented in two steps, to help reviewers:
- Extract to a different file under the same package.
- Move to another sub-package (which introduces changes at the callers).

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
change: Rebase

**Comment by brybacki** [comment]
Another good step for utils.
:+1: for the commit split. Much easier to review than #7439. And I suppose two first PRs are the same as in 7439.
/lgtm

**Comment by EdDev** [comment]
change: Rebase

**Comment by EdDev** [comment]
change: Rebase

**Comment by brybacki** [comment]
what happened with unit tests here?
/test pull-kubevirt-unit-test

**Comment by AlonaKaplan** [comment]
/approve
Thanks for the cleanup!

**Pull request merged**
