### PR TITLE
tests/utils: Move GetSupportedCPUFeatures to libnode package

### PR DESCRIPTION
**Pull request by RamLavi**
### What this PR does
Before this PR:
GetSupportedCPUFeatures is located in the tests/utils package
After this PR:
GetSupportedCPUFeatures is located in the tests/libnode package where it is more natural for it to be.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by enp0s3 — COMMENTED** [review]
/approve

**Comment by dhiller** [comment]
:stop_sign: please refrain from manual retesting.

:warning: this PR is being held to stop automatic retesting. Quarantine PR https://github.com/kubevirt/kubevirt/pull/11244 is given priority.

/hold

**Comment by dhiller** [comment]
:warning: removing hold since https://github.com/kubevirt/kubevirt/pull/11244 got merged.

/unhold

**Comment by brianmcarey** [comment]
@RamLavi - can you take a look at these lint failures? It is failing in a batch as libnode is planned to be added to the linter[1]

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-code-lint/1758050155778543616#1:build-log.txt%3A81

[1] https://prow.ci.kubevirt.io/git-provider-link?target=pr&repo=%27kubevirt/kubevirt%27&number=11182

/hold

**Comment by RamLavi** [comment]
> @RamLavi - can you take a look at these lint failures? It is failing in a batch as libnode is planned to be added to the linter[1]
> 
> https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-code-lint/1758050155778543616#1:build-log.txt%3A81
> 
> [1] https://prow.ci.kubevirt.io/git-provider-link?target=pr&repo=%27kubevirt/kubevirt%27&number=11182
> 
> /hold

sure!

**Comment by RamLavi** [comment]
After rebase I saw the issue and fixed it.
@brianmcarey PTAL

**Review by brianmcarey — COMMENTED** [review]
/lgtm

/hold cancel

thanks @RamLavi !

**Pull request merged**
