### PR TITLE
exportserver cert rotation configurable like everything else

### LINKED ISSUE #8260: Consider placing kubevirt-export-ca  behind VMExport feature gate
**What happened**:
Providing a `certificateRotateStrategy` in the `KubeVirt` spec does not set/update the duration of the `kubevirt-export-ca` secret. The duration for `kubevirt-export-ca` is always `168h` (7 days).

**What you expected to happen**:
When specifying a config such as:
```
  certificateRotateStrategy:
    selfSigned:
      caOverlapInterval: 4392h
      caRotateInterval: 8760h
      certRotateInterval: 4368h
```
...in the KubeVirt spec, the `kubevirt.io/duration` for `secret/kubevirt-exporter-ca` should be `8760h`. It works as expected for the `kubevirt-ca`.

**How to reproduce it (as minimally and precisely as possible)**:
Specify a `certificateRotateStrategy` on KubeVirt `v0.55.0`. Check the duration of the `kubevirt-exporter-ca` secret with `-o yaml`.

**Additional context**:
I have not set the exportproxy feature flag. This secret was statically added in https://github.com/kubevirt/kubevirt/pull/7863.

**Environment**:
- KubeVirt version (use `virtctl version`): `v0.55.0`
- Kubernetes version (use `kubectl version`): `v1.21.13`
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Bare Metal
- OS (e.g. from /etc/os-release): Debian Buster
- Kernel (e.g. `uname -a`): `5.15.40` variant
- Install tools: Github Releases YAML
- Others: N/A

### PR DESCRIPTION
**Pull request by mhenriks**
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

**What this PR does / why we need it**:

exportserver rotation params were initially hardcoded, but now configurable via standard KubeVirt cert rotation params 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8260

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
looks good to me btw, need to rebase after that other PR, but nothing in here looks strange.

**Review by awels — APPROVED** [review]
looks good

**Comment by awels** [comment]
Looks like some unit tests are failing? I see you added CRDInformer and KubeVirtInformet to application.go, should we have it in application_test.go as well? I see npe in some test.

**Comment by mhenriks** [comment]
> Looks like some unit tests are failing? I see you added CRDInformer and KubeVirtInformer to application.go, should we have it in application_test.go as well? I see npe in some test.

Good call, fixed

**Review by awels — APPROVED** [review]

**Pull request merged**
