### PR TITLE
fix ticker leak

### PR DESCRIPTION
**Pull request by rokkiter**
**What this PR does / why we need it**:
The ticker is not stopped, It will leak
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by vasiliy-ul** [comment]
@rokkiter, nice finding :+1: There are a few more leaking tickers in the code. What about fixing those within this PR as well?

After a quick grep, found those:

https://github.com/kubevirt/kubevirt/blob/417788458b68c37050f5797c603f33f6446d8459/pkg/monitoring/domainstats/downwardmetrics/scraper.go#L151

https://github.com/kubevirt/kubevirt/blob/417788458b68c37050f5797c603f33f6446d8459/pkg/virt-handler/retry_manager.go#L147

Also, the tickers below are actually stopped, but not via a deferred call. I would fix that to avoid accidental issues in the future:

https://github.com/kubevirt/kubevirt/blob/417788458b68c37050f5797c603f33f6446d8459/pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go#L245

https://github.com/kubevirt/kubevirt/blob/417788458b68c37050f5797c603f33f6446d8459/pkg/virt-launcher/monitor.go#L189

**Pull request merged**
