### PR TITLE
Return fedora 28 image for container disk

### LINKED ISSUE #1917: vmi-fedora does not boot, mac address keep changing
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Fedora virtual machine does not start properly. Goes through the lifecycle: scheduling -> running -> failed. The mac address keep changing constantly as shown in output

Also when trying to connect to console the request end with error: serial console not ready.

Attaching logs:

[virt-launcher.log](https://github.com/kubevirt/kubevirt/files/2737159/virt-launcher.log)
[virt-handler.log](https://github.com/kubevirt/kubevirt/files/2737163/virt-handler.log)
[virt-controller-1.log](https://github.com/kubevirt/kubevirt/files/2737165/virt-controller-1.log)

**What you expected to happen**:
Fedora virtual machine to boot normally with console allowing me to connect.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy development setup on current master (make cluster-up, make cluster-sync) and deploy vmi-fedora from examples.

**Anything else we need to know?**:
The culprit is most likely damaged fedora image in fedora container disk.

**Environment**:
- KubeVirt version (use `virtctl version`): current master
- Kubernetes version (use `kubectl version`): current master
- VM or VMI specifications: /cluster/examples/vmi-fedora.yaml
- Cloud provider or hardware configuration: kubevirt ci
- OS (e.g. from /etc/os-release): host fedora 29, inside centos 7 (from kubevirt ci)
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by petrkotas**
**What this PR does / why we need it**:
Fedora 29 image in container disk demo, is not working properly in kubevirt.
This pr returns fedora back to image 28, which was working correctly.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1917 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/1918)

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@petrkotas Do you know why does it not work properly with fedora29?

**Comment by petrkotas** [comment]
Yes, I suspect comehow corrupted image. It works in virt-manager, but it
does not boot in kubevirt. Kubevirt QEMU reports it as  "not valid qcow2".
The logs are in referenced issue.

**Comment by petrkotas** [comment]
It also possible, that my local mirror has corrupted image. I will check
different mirror.
--
s pozdravem,
Petr Kotas

**Comment by rmohr** [comment]
> It also possible, that my local mirror has corrupted image. I will check
> different mirror.

That's it for sure. Just wipe the image from your docker cache.

**Comment by davidvossel** [comment]
I believe we identified this as a local environment issue. Re-open if the issue persists.

**Pull request closed without merging**
