### PR TITLE
chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

### PR DESCRIPTION
**Pull request by Juneezee**
**What this PR does / why we need it**:

Currently we are using 3 YAML packages;

1. `github.com/ghodss/yaml v1.0.0`
2. `gopkg.in/yaml.v2 v2.4.0`
3. `sigs.k8s.io/yaml v1.3.0`

The `github.com/ghodss/yaml` package is no longer actively maintained. There are numerous inquiries about the project's status on its issue tracker: https://github.com/ghodss/yaml/issues. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`, which is actively maintained by Kubernetes SIG and widely used in K8s projects.

We can remove 1 dependency by replacing `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by vasiliy-ul — COMMENTED** [review]
Thanks! The CI is green and from my perspective that looks good.

/approve

**Review by EdDev — APPROVED** [review]

**Pull request merged**
