### PR TITLE
Nominate victortoso as reviewer

### PR DESCRIPTION
**Pull request by victortoso**
**What this PR does / why we need it**:
I started collaborating to KubeVirt back in 2020 but most of my contributions were from last year. My work in Red Hat's virtualization team is very connected with KubeVirt, so I expect to things keep progressing well in 2024.

Most of my reviews or help (e.g: slack) are around areas that I've worked already, like sidecars, device plugins and virtctl.

**Special notes for your reviewer**:

As required per [policy](https://github.com/kubevirt/community/blob/main/membership_policy.md) my approver sponsor is @alicefr (thanks!)

- 20 [PRs merged](https://github.com/kubevirt/kubevirt/pulls?q=author%3Avictortoso+is%3Apr+is%3Amerged)
- 06 [reviewed PRs](https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3Avictortoso+-author%3Avictortoso+) that were merged
- 05 [reviewed PRs](https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Avictortoso+-author%3Avictortoso+is%3Aopen+) that are still open

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alicefr** [comment]
From my side, I can confirm that Victor's expertise is quickly growing in KubeVirt!

He's already contributed to multiple features and code review. Just to mention a couple, the USB redirection and host passthrough device plugin and the sidecar shim.

His background in QEMU and SPICE will be a precious resource for the project.

**Comment by 0xFelix** [comment]
I can only repeat what @alicefr said, I'd be happy to have you as a reviewer!

/lgtm

**Comment by acardace** [comment]
/approve

Thanks @victortoso for all your contributions so far, looking forward to seeing many more!

**Comment by acardace** [comment]
/hold

to give time to other approvers to see this.

**Review by enp0s3 — APPROVED** [review]
@victortoso Thank you!

**Comment by fabiand** [comment]
Tihs is an AWESOME PR.

I wonder why we wonder why we take so long :)
/approve

**Comment by victortoso** [comment]
Thanks everyone!

**Comment by brianmcarey** [comment]
/retest-required

/override pull-kubevirt-e2e-k8s-1.29-sig-monitoring

The monitoring lane is set as optional for now as there is an issue on the more recent kubernetes versions - https://github.com/kubevirt/kubevirt/pull/11110

**Pull request merged**
