### PR TITLE
[release-0.49] [e2e] Increase timeout for agentConnected condition

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/9298
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
/cc @xpivarc

### CODE REVIEW

**Review by xpivarc — COMMENTED** [review]
Thank you!
/approve
/lgtm

**Review by enp0s3 — APPROVED** [review]
/approve

**Pull request merged**
