### PR TITLE
Fix vmrestore with WFFC snapshotable storage class

### PR DESCRIPTION
**Pull request by ShellyKa13**
**What this PR does / why we need it**:
In case we had datavolumetemplates and the storage class was WFFC we would wait for the DVs to become succeeded although with WFFC they will never be.
Instead in case of WFFC we will let the restore complete.
we currently dont have a lane with wffc snapshotable storage class defined in kubevirtCI we plan on adding periodic lane to test all our tests with wffc snapshotable storage class

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # BZ https://bugzilla.redhat.com/show_bug.cgi?id=2172612

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix vmrestore with WFFC snapshotable storage class
```

### CODE REVIEW

**Comment by akalenyu** [comment]
I think this PR can also close https://github.com/kubevirt/kubevirt/issues/7927#issuecomment-1202322731
should be able to edit the PR description to coordinate it automatically

**Review by akalenyu — COMMENTED** [review]
Looks good! I didn't realize we don't have an issue with DVs that were created externally (not dvtemplate)

So I spin up a cluster and tried some func tests,
looks like we may need some adjustments to run on WFFC

One I could find is
```
        waitDVReady := func(dv *cdiv1.DataVolume) *cdiv1.DataVolume {
-               libstorage.EventuallyDV(dv, 180, matcher.HaveSucceeded())
+               libstorage.EventuallyDV(dv, 180, Or(matcher.HaveSucceeded(), matcher.BeInPhase(cdiv1.WaitForFirstConsumer)))
                return dv
        }
```

**Comment by ShellyKa13** [comment]
> I think this PR can also close [#7927 (comment)](https://github.com/kubevirt/kubevirt/issues/7927#issuecomment-1202322731) should be able to edit the PR description to coordinate it automatically

This will not fix this since this is not using the vmrestore process its in the smartclone in cdi with vms.. probably need to look into that.
This PR can fix issue with VM clone since it uses the snapshot-restore controllers.

**Comment by ShellyKa13** [comment]
> So I spun up a cluster and tried some func tests,
> looks like we may need some adjustments to run on WFFC

You are right, I guess when we will add the periodic lane we will find such failures and will need to address them

**Comment by akalenyu** [comment]
> > I think this PR can also close [#7927 (comment)](https://github.com/kubevirt/kubevirt/issues/7927#issuecomment-1202322731) should be able to edit the PR description to coordinate it automatically
> 
> This will not fix this since this is not using the vmrestore process its in the smartclone in cdi with vms.. probably need to look into that. This PR can fix issue with VM clone since it uses the snapshot-restore controllers.

The CDI part is fixed and linked to that issue, I believe your PR just closes the last gap we know of wrt to WFFC

**Pull request merged**
