### PR TITLE
Return to using glide and update to latest client-go 

### PR DESCRIPTION
**Pull request by davidvossel**
Dep is not supported by client-go. Trying to update to the latest client-go using dep turned into a nightmare.

This patch reverts us back to glide and updates us to client-go v5.0.1

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by davidvossel** [comment]
jenkins is failing because something in the dependency tree is requiring mercurial now.

After further investigation, I'm not really happy with how many dependencies are involved now with this new client-go version. I'm going to see if I have any success with chopping off a few of them in the ignore section that I know we won't be using.

**Comment by rmohr** [comment]
hg was definitely missing. Added in https://github.com/kubevirt/project-infra/pull/16

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
build seems to be ok. @davidvossel let me know where you want to go regarding to dependency exclusion.

**Comment by davidvossel** [comment]
@rmohr lets hold off on merging this for another day or two while I investigate if we can slim down the dependencies... it's weird that this change is resulting in etcd and apiserver related packages.

**Comment by davidvossel** [comment]
I was able to successfully cut a few dependencies, but ultimately the new client-go requires us to pull in more than we did in the past.

Once the tests pass, this should be good to go for now.

**Comment by ovirt-infra** [comment]
Some tests failed

**Pull request merged**
