### PR TITLE
Bump kubevirt-ci to latest version

### PR DESCRIPTION
**Pull request by danielBelenky**
Signed-off-by: Daniel Belenky <dbelenky@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
Have the problems with the sr-iov lane been fixed?

**Comment by dhiller** [comment]
@danielBelenky obviously the sr-iov provider has not been fixed. So what is the purpose of this PR?

**Comment by dhiller** [comment]
@danielBelenky is this one still up to date?

**Comment by danielBelenky** [comment]
@dhiller this is not up to date, I'll close this one.

**Pull request closed without merging**
