### PR TITLE
Bump kubevirtci for k8s-1.20

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
kubevirtci: add 1.20 provider and new z-stream releases
```

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

We have a weird new problem since my z release bump in kubevirtci

**Comment by dhiller** [comment]
/close 

closed in favor of https://github.com/kubevirt/kubevirt/pull/4662

**Pull request closed without merging**
