### PR TITLE
[release-0.58] hotplug-disk container: match SELinux level of virt-launcher

### PR DESCRIPTION
**Pull request by jean-edouard**
Manual cherry-pick of #8344 

```release-note
NONE
```

### CODE REVIEW

**Review by fossedihelm — APPROVED** [review]
/lgtm

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by jean-edouard** [comment]
Addressed a couple of broken unit tests. LGTM gone, @fossedihelm PTAL!

**Pull request merged**
