### PR TITLE
[e2e] Decorate hotplug tests with VMLiveUpdateFeaturesGate decorator.

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
CPUHotplug requires `VMLiveUpdateFeatures` fg.
Decorate the related tests with a proper decorator.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Review by xpivarc — APPROVED** [review]
/approve

**Pull request merged**
