### PR TITLE
[release-0.44] Improve non-root path handling

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
Manual cherry-pick of #8198 and #8268

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
The banncheck commits were omitted because they don't seem to work with this version of Bazel.
Since banncheck is in main and all backports come from there this should be fine.
It also makes this backport less intrusive.

**Release note**:

```release-note
Improve path handling for non-root virt-launcher workloads
```

### CODE REVIEW

**Review by stu-gott — COMMENTED** [review]
/approve

Thank you!

**Review by acardace — APPROVED** [review]

**Review by acardace — APPROVED** [review]

**Comment by stu-gott** [comment]
/override pull-kubevirt-e2e-k8s-1.19-sig-network

The one failing test is known to be flaky and unrelated to this patch.

**Pull request merged**
