### PR TITLE
snapshot: Introduce v1beta1 version

### PR DESCRIPTION
**Pull request by mhenriks**
### What this PR does
Before this PR:

snapshot.kubevirt.io has been at v1alpha1 for a very, very long time

After this PR:

Add v1beta1 version which exactly mirrors v1alpha1.  v1alpha1 is still available for now.

v1beta1 will become the "stored" version of the API.  Meaning whenever resources are created/updated, they will be tagged as v1beta1 versions.

Requirements for v1beta1 have been met for a long time:  https://github.com/kubevirt/community/blob/main/docs/api-graduation-guidelines.md#beta 

Fixes #

https://issues.redhat.com/browse/CNV-41867

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Introduce snapshot.kibevirt.io/v1beta1
```

### CODE REVIEW

**Comment by mhenriks** [comment]
cc @alicefr @alaypatel07

**Comment by alicefr** [comment]
@mhenriks do you expect snapshot created with the previous API version to still work with the new one after upgrade? I'm thinking to the case when the VM has been snapshotted and then we upgrade kubevirt with the new API version. Would it make sense to add a functional test for this?

**Comment by mhenriks** [comment]
> > @mhenriks do you expect snapshot created with the previous API version to still work with the new one after upgrade? I'm thinking to the case when the VM has been snapshotted and then we upgrade kubevirt with the new API version. Would it make sense to add a functional test for this?
> 
> Shouldn't matter but I can add a test

@alicefr actually it would be pretty hard to write a meaningful test for this, obviously can create a v1alpha1 version of the resource but it will be converted and stored as v1beta1

**Comment by akalenyu** [comment]
> > > > @mhenriks do you expect snapshot created with the previous API version to still work with the new one after upgrade? I'm thinking to the case when the VM has been snapshotted and then we upgrade kubevirt with the new API version. Would it make sense to add a functional test for this?
> > > 
> > > 
> > > Shouldn't matter but I can add a test
> > 
> > 
> > @alicefr actually it would be pretty hard to write a meaningful test for this, obviously can create a v1alpha1 version of the resource but it will be converted and stored as v1beta1
> 
> Yes, it isn't easy. Maybe it could be a scenario to try as tier-2 test.

@jpeimer I think tier-2 tests even go a step further and test this kind of stuff for real,
creating OLD_VERSION snapshots, and performing the restores on NEW_VERSION
(So they're not even faking it lol)

**Comment by jpeimer** [comment]
> > > > > @mhenriks do you expect snapshot created with the previous API version to still work with the new one after upgrade? I'm thinking to the case when the VM has been snapshotted and then we upgrade kubevirt with the new API version. Would it make sense to add a functional test for this?
> > > > 
> > > > 
> > > > Shouldn't matter but I can add a test
> > > 
> > > 
> > > @alicefr actually it would be pretty hard to write a meaningful test for this, obviously can create a v1alpha1 version of the resource but it will be converted and stored as v1beta1
> > 
> > 
> > Yes, it isn't easy. Maybe it could be a scenario to try as tier-2 test.
> 
> @jpeimer I think tier-2 tests even go a step further and test this kind of stuff for real, creating OLD_VERSION snapshots, and performing the restores on NEW_VERSION (So they're not even faking it lol)

Yes, correct. We create a snapshot, upgrade OCP or CNV, and then restore that snapshot.

**Comment by mhenriks** [comment]
> > > > > > @mhenriks do you expect snapshot created with the previous API version to still work with the new one after upgrade? I'm thinking to the case when the VM has been snapshotted and then we upgrade kubevirt with the new API version. Would it make sense to add a functional test for this?
> > > > > 
> > > > > 
> > > > > Shouldn't matter but I can add a test
> > > > 
> > > > 
> > > > @alicefr actually it would be pretty hard to write a meaningful test for this, obviously can create a v1alpha1 version of the resource but it will be converted and stored as v1beta1
> > > 
> > > 
> > > Yes, it isn't easy. Maybe it could be a scenario to try as tier-2 test.
> > 
> > 
> > @jpeimer I think tier-2 tests even go a step further and test this kind of stuff for real, creating OLD_VERSION snapshots, and performing the restores on NEW_VERSION (So they're not even faking it lol)
> 
> Yes, correct. We create a snapshot, upgrade OCP or CNV, and then restore that snapshot.

@alicefr looks like we have very good tier 2 coverage so will skip functest here

**Pull request merged**
