### PR TITLE
add validation for spec.affinity

### PR DESCRIPTION
**Pull request by simonyangcj**
Signed-off-by: Simon Yang <yang.chenjun@99cloud.net>

**What this PR does / why we need it**:
So far vmi validation webhook does not validate spec.affinity fo vmi template

**Which issue(s) this PR fixes**
Fixes #<https://github.com/kubevirt/kubevirt/issues/8100>

**Special notes for your reviewer**:

**Release note**:
```release-note
Support validation for spec.affinity of vmi template
```

### CODE REVIEW

**Comment by xpivarc** [comment]
Hi @simonyangcj and thanks for the PR.

Do you think we could reuse k8s library here?

**Comment by alicefr** [comment]
Sorry for overloading this PR. But, reading this PR, I was wondering if we could try to dry-run the virt-launcher pod creation and go through all the k8s checks.

**Comment by simonyangcj** [comment]
> Hi @simonyangcj and thanks for the PR.
> 
> Do you think we could reuse k8s library here?

You are right, i will look into it. It would be much easier if we reuse k8s library

@xpivarc

**Comment by enp0s3** [comment]
Hi @simonyangcj! Thank you for the PR, you can refer to [this](https://github.com/kubevirt/kubevirt/pull/6103) PR as well. I've used a `dry-run` approach against the k8s api server in order to validate the `tolerations` and `nodeSelector` fields, since they are part of the k8s podSpec, so they can be validated against their API server admission webhooks. That spares me from the burden of maintaining the PodSpec

**Comment by simonyangcj** [comment]
> Hi @simonyangcj! Thank you for the PR, you can refer to [this](https://github.com/kubevirt/kubevirt/pull/6103) PR as well. I've used a `dry-run` approach against the k8s api server in order to validate the `tolerations` and `nodeSelector` fields, since they are part of the k8s podSpec, so they can be validated against their API server admission webhooks. That spares me from the burden of maintaining the PodSpec

@enp0s3 thank you for your suggestion, i'll look into it :)

**Comment by simonyangcj** [comment]
> Hi @simonyangcj and thanks for the PR.
> 
> Do you think we could reuse k8s library here?

@xpivarc i did some research, yes it would much easier to use k8s library like function `func validateAffinity(affinity *core.Affinity, fldPath *field.Path) field.ErrorList in kubernetes/pkg/apis/core/validation/validation.go`  but we will end up bring in the whole kubernetes to vendor dir. So I`m not sure that`s a good approach

**Comment by enp0s3** [comment]
@simonyangcj Hi. I just noticed you've opened the PR against the `release-0.55` branch. Can you please re-create it against the `main` branch? We have a [backport](https://github.com/kubevirt/kubevirt/blob/main/docs/release-branch-backporting.md) policy regarding the release branches.

**Comment by simonyangcj** [comment]
> @simonyangcj Hi. I just noticed you've opened the PR against the `release-0.55` branch. Can you please re-create it against the `main` branch? We have a [backport](https://github.com/kubevirt/kubevirt/blob/main/docs/release-branch-backporting.md) policy regarding the release branches.

@enp0s3 thank you for your information, I'll close it now and re-create it against main branch

**Comment by simonyangcj** [comment]
new PR is ready for test here https://github.com/kubevirt/kubevirt/pull/8187

**Pull request closed without merging**
