### PR TITLE
[release-0.58]Fix evmcs hyperv bug

### PR DESCRIPTION
**Pull request by Barakmor1**
**What this PR does / why we need it**:
This is a manual backport PRs of : 
https://github.com/kubevirt/kubevirt/pull/8556
which move tests agnostic to Windows OS from Windows lane
and 
https://github.com/kubevirt/kubevirt/pull/8773
that fix evmcs hyperv feature bug.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by jean-edouard — CHANGES_REQUESTED** [review]
Please cherry-pick https://github.com/kubevirt/kubevirt/pull/8556 instead of mashing it into [`f9ba45e` (#8793)](https://github.com/kubevirt/kubevirt/pull/8793/commits/f9ba45e6e05846b55acb7f4c1b5b501cf348959f)

**Comment by Barakmor1** [comment]
> Please cherry-pick #8556 instead of mashing it into [`f9ba45e` (#8793)](https://github.com/kubevirt/kubevirt/pull/8793/commits/f9ba45e6e05846b55acb7f4c1b5b501cf348959f)
> 
> Edit: btw, this other backport PR also needs #8556: #8798

Hey,
Sorry about that i didn't notice.
It's fixed now

**Pull request merged**
