### PR TITLE
Add automation helper binaries and reduce builder image size

### PR DESCRIPTION
**Pull request by rmohr**
Installing pr-creator, issue-creator and issue-labeler into the builder
image while at the same time also cleaning all docker caches to reduce
the builder image size.

Especially `pr-creator` will help to automate basic tasks like pushing kubevirtci, updating vendor dependencies and so on from prow jobs.

Signed-off-by: Roman Mohr <rmohr@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to https://github.com/kubevirt/project-infra/issues/344

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
/lgtm
/approve

Interesting stuff! How will these get used? I understand `issue-creator` creates issues for flaky jobs and clustered failures. Is there a config that we need to enable that runs them automatically somehow or how else do we enable these?

**Comment by dhiller** [comment]
Does this make the flake finder obsolete?

**Comment by rmohr** [comment]
> Does this make the flake finder obsolete?

Hi, no I did not look too much into issue-creator. I was mostly just interested in pr-creator ...

**Comment by rmohr** [comment]
/hold

apparently the bazel versions differ between the different builder architectures.

**Pull request merged**
