### PR TITLE
[DO NOT REVIEW] [TEST] Remove NoSchedule taints for control-planes as well as masters

### PR DESCRIPTION
**Pull request by iholder101**
### What this PR does
Before this PR:

After this PR:

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note

```

### CODE REVIEW

**Comment by iholder101** [comment]
/approve
/lgtm
/hold

I'm doing this solely for running the whole test suite. This PR is **NOT** intended to merge.

**Comment by iholder101** [comment]
@brianmcarey @oshoval can you please LGTM in order to run the whole test suite?
This PR will not get in by any means.

**Comment by oshoval** [comment]
you dont need to lgtm,
just run please /test the vgpu and sriov ones

**Comment by iholder101** [comment]
> you dont need to lgtm, just run please /test the vgpu and sriov ones

Don't you want to run the other lanes as well to be on the safe side?

**Comment by oshoval** [comment]
dont you need it in combination of https://github.com/kubevirt/kubevirt/pull/11659 ?

**Comment by iholder101** [comment]
> dont you need it in combination of #11659 ?

I can cherry pick the commits to here if you want to. But then we'd be testing two things at ones. Your call.

**Comment by oshoval** [comment]
> > dont you need it in combination of #11659 ?
> 
> I can cherry pick the commits to here if you want to. But then we'd be testing two things at ones. Your call.

well they are connected anyhow, sgtm to test together

**Comment by oshoval** [comment]
> > you dont need to lgtm, just run please /test the vgpu and sriov ones
> 
> Don't you want to run the other lanes as well to be on the safe side?

kind doesnt affect them, no need
i dont know but what your other PR does, your call

**Comment by dhiller** [comment]
@iholder101 KubeVirtCI kind provider is completely independent from the "normal" KubeVirtCI k8s providers. IMHO it is enough to _only_ run the kind lanes for the changed kind providers.

**Comment by dhiller** [comment]
And wrt to triggering the test lanes: an `lgtm` is not required, you can trigger any test lane manually at any time. As you saw `test all` triggered all of them.

**Comment by dhiller** [comment]
The above holds true for any KubeVirt org member btw.

**Comment by iholder101** [comment]
> And wrt to triggering the test lanes: an `lgtm` is not required, you can trigger any test lane manually at any time. As you saw `test all` triggered all of them.

Are you sure?
I see that some of the lanes are "Pending" and some are "Expected". IIUC one means "still running" and one means "haven't start running yet". Am I completely off?

**Comment by dhiller** [comment]
The 1.28 and 1.27 are not triggered automatically any more, however manually triggering any lane should still be possible. I'm going to check whether prow jobs have been created. (Note that if no link is visible this might just mean that the test pod has not been created)

**Comment by dhiller** [comment]
(am shortly off for now, will check later)

**Comment by oshoval** [comment]
> The 1.28 and 1.27 are not triggered automatically any more, however manually triggering any lane should still be possible. I'm going to check whether prow jobs have been created. (Note that if no link is visible this might just mean that the test pod has not been created)

those are phase 2 indeed, just forget them, it is enough to test the latest (1.29) in this PR (only because there are additional changes beside kind)

**Comment by dhiller** [comment]
> /test pull-kubevirt-e2e-kind-sriov /test pull-kubevirt-e2e-kind-1.27-vgpu /test all

What I think has happened here is that the issuing of `test all` additionally to the `test whatever` has not come through to the trigger plugin, I guess because it didn't stand alone but additionally to the other `test` triggers (who had been superfluous anyway when using `test all`).

**Comment by oshoval** [comment]
> > /test pull-kubevirt-e2e-kind-sriov /test pull-kubevirt-e2e-kind-1.27-vgpu /test all
> 
> What I think has happened here is that the issuing of `test all` additionally to the `test whatever` has not come through to the trigger plugin, I guess because it didn't stand alone but additionally to the other `test` triggers (who had been superfluous anyway when using `test all`).

if you mean why the phase 2 didnt run, it is because they are "always_run: false"
"test all" won't trigger them

**Comment by oshoval** [comment]
sriov and vgpu passed, i think you can close the PR, thanks

**Comment by iholder101** [comment]
> sriov and vgpu passed, i think you can close the PR, thanks (also all other phase 1 lanes passed, generate is expected to fail) windows is not tested but will be tested as part of the kubevirt PR anyhow

Great!
So can you please approve the other PR? Or is there anything missing?

**Comment by oshoval** [comment]
> > if you mean why the phase 2 didnt run, it is because they are "always_run: false" "test all" won't trigger them, unless you meant that also the phase 1 didn't run due to this command stacking
> 
> I think that is not true. `always_run: false` means that the lanes are not triggered _automatically_, where triggering with `test all` should still work. If that wasn't true, the phrase `test all` would be very misleading, as it didn't mean _all_ but only some, right?
> 
> @oshoval do you have evidence or code pointers that it should behave as you said?

it always was like that, always_run = false never run with test all, not related even the phased plugin
for example we had the bump_kubevirt_kuebvirtci manual lane (which was removed)
it never ran with "test all"

Tide filter according `ps.ShouldRun`, if you think code evidence is required (imho it doesn't)
than i would bet the trigger plugin have same logic to find out what should run

**Comment by oshoval** [comment]
> > sriov and vgpu passed, i think you can close the PR, thanks (also all other phase 1 lanes passed, generate is expected to fail) windows is not tested but will be tested as part of the kubevirt PR anyhow
> 
> Great! So can you please approve the other PR? Or is there anything missing?

it is already lgtmed

**Comment by oshoval** [comment]
@dhiller 
https://github.com/kubernetes-sigs/prow/blob/db89760fea406dd2813e331c3d52b53b5bcbd140/pkg/plugins/trigger/pull-request.go#L356
for example, not sure if "/test all" reach exactly here, but educated guess it is
```
		shouldRun, err := presubmit.ShouldRun(branch, changes, forced, defaults)
		if err != nil {
			return nil, fmt.Errorf("%s: should run: %w", presubmit.Name, err)
		}
```

**Comment by dhiller** [comment]
Hm, interesting. Thanks for educating me @oshoval! I still believe that then the wording of `test all` is very misleading. And I also believe that the behaviour has changed at some point.

**Comment by iholder101** [comment]
Thanks everyone!
/close

**Pull request closed without merging**
