### PR TITLE
Add BootMenu wait when starting a VM as paused

### PR DESCRIPTION
**Pull request by acardace**
**What this PR does / why we need it**:

This will help access the BIOS/EFI menu when starting the VMI as paused otherwise there's not enough actual time to get into it. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
https://issues.redhat.com/browse/CNV-22801

**Release note**:

```release-note
Add boot-menu wait time when starting the VM as paused.
```

### CODE REVIEW

**Comment by lyarwood** [comment]
/lgtm

Makes sense as a backportable workaround but a better solution would be to expose `bootmenu` within` DomainSpec` right?

**Comment by acardace** [comment]
> /lgtm
> 
> Makes sense as a backportable workaround but a better solution would be to expose `bootmenu` within `DomainSpec` right?

hmm, yes and no, I don't think It's that useful in general for VMs but if you think it is I can do a follow-up PR.

**Comment by lyarwood** [comment]
> > /lgtm
> > Makes sense as a backportable workaround but a better solution would be to expose `bootmenu` within `DomainSpec` right?
> 
> hmm, yes and no, I don't think It's that useful in general for VMs but if you think it is I can do a follow-up PR.

Yeah I'm not sure how useful it would actually be but it's definitely cleaner to expose this in `DomainSpec` without relying on the state of the `VirtualMachineInstance` to trigger the behaviour. We'd also avoid the 10 second delay for the guest OS launching for all resumed `VirtualMachineInstances` that this change introduces.

**Comment by acardace** [comment]
> > > /lgtm
> > > Makes sense as a backportable workaround but a better solution would be to expose `bootmenu` within `DomainSpec` right?
> > 
> > 
> > hmm, yes and no, I don't think It's that useful in general for VMs but if you think it is I can do a follow-up PR.
> 
> Yeah I'm not sure how useful it would actually be but it's definitely cleaner to expose this in `DomainSpec` without relying on the state of the `VirtualMachineInstance` to trigger the behaviour. We'd also avoid the 10 second delay for the guest OS launching for all resumed `VirtualMachineInstances` that this change introduces.

I agree, I'll do a follow-up PR soon.

**Pull request merged**
