### PR TITLE
Fixed RBAC for migrations

### PR DESCRIPTION
**Pull request by slintes**
**What this PR does / why we need it**:
Fixed RBAC for migrations:
- view access only for default admin and edit roles
- operator needs removed permissions for updates
- refactored tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by slintes** [comment]
Needs confirmation that this is finally what we really want

/hold

**Comment by davidvossel** [comment]
I'm fine with giving namespaced users the ability to view migration objects without create/update/delete permissions. 

@rmohr @fabiand @vladikr It would be good to hear you all weigh in here as well since I know this was a big topic earlier in the year.

**Comment by rmohr** [comment]
> I'm fine with giving namespaced users the ability to view migration objects without create/update/delete permissions.

It is at least not relevant regarding to security. I also think that I have read the the openshift UI uses the migration objects to indicate if VMIs are migrating. I guess it would be better if it would be discovered by looking at the VMI.

**Comment by fabiand** [comment]
@vladikr do you mind reviewing this one?

**Comment by vladikr** [comment]
I'm fine with this change as well. Especially if we are keeping the migration object namespaced.
But I can't think of a use case for this unless someone wants to keep a list of migration without going through all the VMIs?

**Comment by vladikr** [comment]
> It is at least not relevant regarding to security. I also think that I have read that the openshift UI uses the migration objects to indicate if VMIs are migrating. I guess it would be better if it would be discovered by looking at the VMI.

Agree, we keep more information in the VMI.

**Comment by fabiand** [comment]
@stu-gott is there somebody who could pick this up?

**Pull request closed without merging**
