### PR TITLE
[release-0.58][e2e]: improve cloud-init user-data specs

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/9242
`libwait` package was introduced later than realease-0.58, so here we still use the package `tests`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/cc @enp0s3

### CODE REVIEW

**Review by enp0s3 — COMMENTED** [review]
/approve

**Comment by fossedihelm** [comment]
Forget it was mine :D

**Pull request merged**
