### PR TITLE
migration controller: set vmi as vmim owner reference

### PR DESCRIPTION
**Pull request by jean-edouard**
### What this PR does
Before this PR:
Migration objects have no owner reference and can potentially survive their VMI.
Worse, it could survive a VM restart.

After this PR:
Migration objects are owned by their VMI and will be deleted along with it.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by fossedihelm — APPROVED** [review]

**Comment by fossedihelm** [comment]
From the code looks like this could not happen. Did you observe this happening?
Also, could we add a release note? Thank you

**Comment by jean-edouard** [comment]
> From the code looks like this could not happen.

Tell me more! My concern would be:
- VMI is shutting down, its ongoing migration gets enqueued in the migration controller
- VMI shuts down quickly and restarts
- Migration controller finally executes on key, finds the VMI by name, doesn't remove VMIM object.

Also, even if that concern is invalid, I still think it makes sense for the VMI to be the owner of the VMIM, WDYT?

> Did you observe this happening?

I did not

> Also, could we add a release note?

I can't see any valuable information to include in the notes for the next release, what did you have in mind?

Thanks for the review!

**Comment by jean-edouard** [comment]
> > > From the code looks like this could not happen.
> > 
> > 
> > Tell me more! My concern would be:
> 
> From the migration controller code, once a vmi disappear (the vmi is deleted from the cache), it performs the migration deletion [https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/watch/migration.go#L316-L330](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/watch/migration.go?rgh-link-date=2024-08-06T12%3A51%3A17Z#L316-L330):
> 
> ```
> 	if !vmiExists {
> 		var err error
> 
> 		if migration.DeletionTimestamp == nil {
> 			logger.V(3).Infof("Deleting migration for deleted vmi %s/%s", migration.Namespace, migration.Spec.VMIName)
> 			err = c.clientset.VirtualMachineInstanceMigration(migration.Namespace).Delete(context.Background(), migration.Name, v1.DeleteOptions{})
> 		}
> 		// nothing to process for a migration that's being deleted
> 		return err
> 	}
> ```
> 
> There could be some corner cases, as you described. I was just curious if this was observed.
> 

Yes, that's the migration controller code I was referring to. For it to run, we need a migration controller thread to pop the corresponding key.
If the queue is very long when we add to it, it could take minutes for that to happen. My concern is if a VMI restarts during those minutes.
That potentially very long time is a wider problem by the way, that I tried to mitigate with this rotting PR: https://github.com/kubevirt/kubevirt/pull/11616

**Review by xpivarc — COMMENTED** [review]
The migration now contains the migration status, something which we loose as next migration kicks in or if the vmi disappears. I wonder if simply adding UID as way to identify what VMI should have been migrated would be enough and slightly better in case of debugging.

**Pull request closed without merging**
