### PR TITLE
Update alert rules guidelines

### PR DESCRIPTION
**Pull request by sradco**
Signed-off-by: Shirly Radco <sradco@redhat.com>

**What this PR does / why we need it**:
This PR adds a guideline for alerts, to have a verbose message, since it is being used in the [metrics.md](https://github.com/kubevirt/kubevirt/blob/master/docs/metrics.md) automatically and adds the definition for alerts severity levels.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sradco** [comment]
@stu-gott @davidvossel I don't believe the failed tests are related to this PR. Please review.

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

Excellent! thanks for all your work on improving our policies/processes around alerting and monitoring

**Pull request merged**
