### PR TITLE
fix(client-go): Use proxy from config if present

### LINKED ISSUE #12808: virtctl socks proxy
You can add something like:
```
  proxy-url: socks5://localhost:10001
```
to your kubeconfig to reach a k8s on the other side of a socks proxy.

virtctl console/vnc just hangs with such a kubeconfig file.

### PR DESCRIPTION
**Pull request by 0xFelix**
### What this PR does

Use the proxy found in kubeconfig if present and fallback to http.ProxyFromEnvironment, as the comment for Config.Proxy suggests.

> Proxy is the proxy func to be used for all requests made by this
> transport. If Proxy is nil, http.ProxyFromEnvironment is used. If Proxy
> returns a nil *URL, no proxy is used.

Previously a proxy configured in kubeconfig was ignored and only http.ProxyFromEnvironment was used.

Before this PR:

Proxies configured in kubeconfig are ignored in client-go for asynchronous subresources like VNC or Console.

After this PR:

Proxies configured in kubeconfig are used in client-go for asynchronous subresources like VNC or Console.

Fixes #12808

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
fix: Proxies configured in kubeconfig are used in client-go for asynchronous subresources like VNC or Console
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
@xpivarc Not sure what to do about testing here. There aren't any tests at all for this?

**Comment by lyarwood** [comment]
> @xpivarc Not sure what to do about testing here. There aren't any tests at all for this?

I asked offline if this was generated code given the path and you highlighted that @fossedihelm is extracting this in https://github.com/kubevirt/kubevirt/pull/12828, assuming folks want to go in that direction then maybe rebase this change on top and introduce a test there?

**Review by xpivarc — COMMENTED** [review]
/approve
@fossedihelm @lyarwood

**Comment by fossedihelm** [comment]
Ops, it falls outside of my radar.
/lgtm

**Pull request merged**
