### PR TITLE
[release-1.0] enable live migration with dedicated cpus and isolated emulator thread

### PR DESCRIPTION
**Pull request by acardace**
Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/9722 + `make generate` run to fix dates.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
I don't know if there will be conflicts with https://github.com/kubevirt/kubevirt/pull/11012
/lgtm

**Comment by acardace** [comment]
> I don't know if there will be conflicts with #11012 /lgtm

Let's see if this passes all tests before that one, in that case we'll hold #11012

**Comment by dhiller** [comment]
@acardace how can this be a manual cherry pick of https://github.com/kubevirt/kubevirt/pull/9722, which has only 2 changed files with a couple of lines removed?

**Comment by dhiller** [comment]
I would at least expect some explanation which backports had to be made additionally in the PR description, so people can follow along.

**Comment by acardace** [comment]
> I would at least expect some explanation which backports had to be made additionally in the PR description, so people can follow along.

It wasn't an additional backport, I just had to run `make generate` separately and I did a separate commit for that so that it's pretty clear that this is a backport + make generate.

**Comment by dhiller** [comment]
> > I would at least expect some explanation which backports had to be made additionally in the PR description, so people can follow along.
> 
> It wasn't an additional backport, I just had to run `make generate` separately and I did a separate commit for that so that it's pretty clear that this is a backport + make generate.
> 
> https://github.com/kubevirt/kubevirt/pull/11015/commits

Thank you for clarifying, and I'll take the blame of not backporting the year removal fix :(

**Review by dhiller — COMMENTED** [review]
/approve

**Pull request merged**
