### PR TITLE
Revert "tests: temporarily disabling couple of extremely flaky test"

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
It re-enables a couple of tests which are hopefully not flaky since the nfs-server image was moved to quay.io

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — COMMENTED** [review]
Maybe lets XFail them instead enabling ?
this way they will run, but not fail the lane in case of error, so its a win win
(just need to manually check out, or see it in the flake finder which shows it IIRC)

**Comment by jean-edouard** [comment]
/retest
No failure related to the 2 tests, looks promising.

**Comment by oshoval** [comment]
any idea please if the Serial helped ?

**Comment by jean-edouard** [comment]
> any idea please if the Serial helped ?

I believe it did! At first glance, it doesn't seem like those 2 tests ever failed after I marked them serial, good hunch!
It would be a good idea to look at the code and find which part is indeed not "threadsafe" to confirm that this was the issue.
I'll have a look if I find the time.
/assign jean-edouard

**Comment by oshoval** [comment]
is this a dupe then ?
https://github.com/kubevirt/kubevirt/issues/4829

**Comment by rmohr** [comment]
If I remember this correctly they failed with a timeout due to very long startup times, as soon as ganesha was invovled. Did the startup times go dow too with "serial"?

**Comment by jean-edouard** [comment]
> If I remember this correctly they failed with a timeout due to very long startup times, as soon as ganesha was invovled. Did the startup times go dow too with "serial"?

It seems to me that most tests that fail on a timeout usually do so in an Eventually() or an expecter that was never going to get what it was expecting but still waited the whole timeout.
I'm pretty sure that's what was happening here.
But since it doesn't happen in serial, I expect that some shared code doesn't support parallel execution.
I'll try to have a closer look at the code later today.

**Comment by jean-edouard** [comment]
Closing in favor of https://github.com/kubevirt/kubevirt/pull/5945

**Pull request closed without merging**
