### PR TITLE
tests: Move service-account helpers to a separate file

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

Continue cleaning up `utils` by extracting out code to dedicated file with common logic/responsibility.

It has not yet been placed under a dedicated package due to some dependencies to the original `utils` file.
This should be resolved as `utils` is cleaned up.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
~~Depends on #7439~~

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
> > Would it be worth encoding into the file name(or somewhere else) that this is all test suite setup-related?
> 
> I have a `testsuite` In the working. I found it useful to first split by subject/responsibility and only then by usage. It may be hard to notice now, but some parts here are used by tests directly.

/lgtm
You have my blessing as long as you have a follow-up in mind.

**Comment by EdDev** [comment]
Change: Rebase & remove dependency on other PR/s.

**Review by enp0s3 — APPROVED** [review]
/approve

**Pull request merged**
