### PR TITLE
De-quarantine simple clone functest

### PR DESCRIPTION
**Pull request by iholder-redhat**
**What this PR does / why we need it**:
This PR https://github.com/kubevirt/kubevirt/pull/8120 solved flakieness of "simple clone" functest.

Following [this process](https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md), since 3 days passed without failures, we can remove the quarantine.

**Useful links:**
Test grid: https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.24-sig-storage&width=20&show-stale-tests=

CI search: https://search.ci.kubevirt.io/?search=.*with+a+simple+clone.*&maxAge=48h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ShellyKa13** [comment]
according to the process need to see it doesnt fail for 2 weeks. do you plan to merge only then?

**Comment by xpivarc** [comment]
/approve
@brianmcarey and I discussed this and afaik this was actually a code problem. Therefore I think it is not really a flaky test. We can always react fast if we see this flaky.

**Review by brianmcarey — COMMENTED** [review]
/lgtm 

Feel free to remove the hold whenever you want - this test has been passing consistently across 4 periodic lanes so it looks good.

**Comment by ShellyKa13** [comment]
I also support removing it from quarantine so it is approved I approve :)

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Pull request merged**
