### PR TITLE
Document CDI deploy for cluster-sync

### PR DESCRIPTION
**Pull request by brybacki**
Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

**What this PR does / why we need it**:

Document new ENV Variable introduced in PR #6339. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

In my opinion that CDI is not installed by default is not what was agreed on. I think the behaviour should be changed to the default setting.

**Comment by brybacki** [comment]
> /hold
> 
> In my opinion that CDI is not installed by default is not what was agreed on. I think the behaviour should be changed to the default setting.

Great. 

Today, when trying to run tests locally, I was surprised that CDI is not here. I have found about a new env var from @maya-r. So default to true would be good in my opinion. Anyway, documentation should say something about the new variable.

**Comment by oshoval** [comment]
> In my opinion that CDI is not installed by default is not what was agreed on. I think the behaviour should be changed to the default setting.

By mistake I did it opt-out only for CI, and then asked this https://github.com/kubevirt/kubevirt/pull/6339#issuecomment-919219261

Sorry for the inconvenience

**Comment by brybacki** [comment]
@oshoval thanks for info. I see it is now enabled by default. Since the new variable is not documented, I have updated the PR. 

@rmohr Do you want some more information? More elaborate documentation? Or is it ready to be `unhold`?

**Comment by brybacki** [comment]
I have updated it to reflect current state, 
@rmohr Is it ready to be unhold?

**Pull request merged**
