### PR TITLE
allow disabling pvspinlock to support older guests kernels

### PR DESCRIPTION
**Pull request by vladikr**
**What this PR does / why we need it**:
Some older guest os may experience a kernel panic if pvspinlock is not disabled.
Such as: 
```
[  134.251405] BUG: unable to handle kernel paging request at ffffffff8104e8f7
[  134.252284] IP: [<ffffffff8104e8f7>] kvm_kick_cpu+0x27/0x30
```
This PR will simply allow disabling the pvspinlock in the VMI schema.

**Release note**:
```release-note
allow disabling pvspinlock to support older guest kernels
```

### CODE REVIEW

**Review by stu-gott — COMMENTED** [review]
This looks good. Very straightforward. One thing that appears to be missing is a default test. I see a check where we explicitly set the pvspinlock to false and verify that--but I don't see one where we do nothing and expect it to be true.

**Comment by vladikr** [comment]
It's true by default at all times.

**Comment by stu-gott** [comment]
/lgtm

Ah! I had misread the code in converter.go

**Review by jean-edouard — COMMENTED** [review]
/approve

**Pull request merged**
