### PR TITLE
Use updated os images

### PR DESCRIPTION
**Pull request by cynepco3hahue**
**What this PR does / why we need it**:
New images include fix from https://github.com/kubevirt/kubevirtci/pull/54

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
The multus 1.10 cluster seems to be not updated yet.

**Comment by SchSeba** [comment]
@rmohr Maybe it will be better if I update my PR about openshift 3.11 multus and then we merge it?

https://github.com/kubevirt/kubevirtci/pull/52
https://github.com/kubevirt/kubevirt/pull/1726

**Comment by cynepco3hahue** [comment]
> The multus 1.10 cluster seems to be not updated yet.

Do you mean 3.10, I checked yesterday and I did not see the problem with the python-docker package on the provision, so I skipped it.

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
@SchSeba I prefer to separate this changes from multus. Multus define new provider when here I just fix python-docker problem. Also, multus provider does not intersect with default os provider.

**Comment by cynepco3hahue** [comment]
hm stange I see os-3.10-multus started to fail on the same problem with the docker package

**Comment by rmohr** [comment]
for reference: https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/2782/artifact/ci_build_summary.html

**Comment by rmohr** [comment]
ci test please

**Comment by awels** [comment]
I can confirm the cluster doesn't come up properly when using the image for CDI either. The cluster works for a few minutes and then the api server stops responding.
```bash
[awels@awels containerized-data-importer]$ ./cluster/kubectl.sh get pods --all-namespaces
No resources found.
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding (get pods)
```

**Comment by cynepco3hahue** [comment]
@awels  Yes it looks like part of pods failed to start properly, I will investigate it.

**Comment by cynepco3hahue** [comment]
https://github.com/openshift/origin/blob/893b40d74d4c284446076f4c55f3d98da16ea09a/pkg/apps/strategy/support/acceptor.go#L48 the strange error that we can see under `router` deploy pod, looks like a watch on RS fails, it can be related to the all `connection refused` that we can see, but I can not find why API server refuses the connection.

**Comment by awels** [comment]
@cynepco3hahue What can I do to give you more information? When I start another deployment of the router pod, it fails in the same way. I can give you access to my system if you want.

**Comment by cynepco3hahue** [comment]
@awels not too much, strange thing that OS with CRI-O runs normally, so I have suspicions that new `python-docker-py` includes some changes that affect openshift. Will try to get old `python-docker` package to check if it will work fine with it.

**Comment by cynepco3hahue** [comment]
@awels Looks like the problem is the latest docker package, I will try it with docker version that worked before and will update images.

**Comment by cynepco3hahue** [comment]
From all OpenShift jobs, I can see that
```
+ cluster/kubectl.sh get pods -n kubevirt --no-headers
+ grep -v Running
cdi-http-import-server-79cc449d4d-77lft   0/1       CrashLoopBackOff   5         5m
```
I will check it locally.

**Comment by cynepco3hahue** [comment]
@rmohr Can you take a look? I think we can merge it.

**Comment by rmohr** [comment]
@cynepco3hahue looks great!

**Pull request merged**
