### PR TITLE
update ADOPTERS.md to add Oracle as an adopter for KubeVirt

### PR DESCRIPTION
**Pull request by scoter-oracle**
Signed-off-by: Simon Coter [simon.coter@oracle.com](mailto:simon.coter@oracle.com)
This PR adds Oracle as an adopter for KubeVirt.
We today leverage KubeVirt as a module for our own Kubernetes distribution (Oracle Cloud Native Environment).

Release-note:
```
NONE
```

### CODE REVIEW

**Comment by aburdenthehand** [comment]
@scoter-oracle - Thanks for the PR! This is great to see.
Can I ask you to please sign-off on your commit ([instructions here](https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md#contributor-compliance-with-developer-certificate-of-origin-dco)) and either include a release note or write 'NONE' in the release note field of the PR description? 

If you overwrote the PR template, then it looks like this:
\```release-note

\```

**Comment by aburdenthehand** [comment]
@scoter-oracle - Thanks for the PR! This is great to see.
Can I ask you to please sign-off on your commit ([instructions here](https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md#contributor-compliance-with-developer-certificate-of-origin-dco)) and either include a release note or write 'NONE' in the release note field of the PR description? 

If you overwrote the PR template, then it looks like this:

**Comment by xpivarc** [comment]
@scoter-oracle 
You need to drop the merge commit as it is not signed.

**Pull request closed without merging**
