### PR TITLE
DHCPv6 server should handle request without iana option

### LINKED ISSUE #9843: GuestOS send DHCPv6 request will cause virt-launcher crash
**What happened**:

I find my GuestOS Ubuntu 18.04 will send DHCPv6 **InformationRequest** (not contains IA_NA option), the request will cause 
 virt-launcher DHCPv6 server crash.

virt-launcher log
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x161b977]

goroutine 133 [running]:
kubevirt.io/kubevirt/pkg/network/dhcp/serverv6.(*DHCPv6Handler).buildResponse(0xc00070f7a0, {0x1ce0ea0?, 0xc0002e3860})
	pkg/network/dhcp/serverv6/serverv6.go:118 +0x437
kubevirt.io/kubevirt/pkg/network/dhcp/serverv6.(*DHCPv6Handler).ServeDHCPv6(0x0?, {0x1cde950, 0xc0006b35f0}, {0x1ccc040, 0xc0002f93b0}, {0x1ce0ea0, 0xc0002e3860})
	pkg/network/dhcp/serverv6/serverv6.go:81 +0x119
created by kubevirt.io/kubevirt/vendor/github.com/insomniacslk/dhcp/dhcpv6/server6.(*Server).Serve
	vendor/github.com/insomniacslk/dhcp/dhcpv6/server6/server.go:97 +0x3c5
```

tcpdump log of tap0 device.
```
52:54:00:b8:3a:b2 > 33:33:00:01:00:02, ethertype IPv6 (0x86dd), length 104: (flowlabel 0x58c08, hlim 1, next-header UDP (17) payload length: 50) fe80::5054:ff:feb8:3ab2.546 > ff02::1:2.547: [bad udp cksum 0x8888 -> 0x196d!] dhcp6 inf-req (xid=99d61 (option-request DNS-server DNS-search-list NTP-server SNTP-servers rapid-commit) (client-ID vid 0000ab11038b64bc) (elapsed-time 65535))
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.59.0
- GuestOS: Ubuntu 18.04 (Kernel 4.1.5.0-176)

### PR DESCRIPTION
**Pull request by lxs137**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9843

**Special notes for your reviewer**:

**Release note**:

```release-note
DHCPv6 server handle request without iana option
```

### CODE REVIEW

**Comment by EdDev** [comment]
> DHCPv6 server should handle request without iana option

Could you please reason for it?

**Comment by lxs137** [comment]
> > DHCPv6 server should handle request without iana option
> 
> Could you please reason for it?

I found my VM could send InformationRequest, which not contains IA_NA Option, the request will cause virt-launcher crash. 
 
More details please look at #9843

**Comment by EdDev** [comment]
> @EdDev I found my VM could send dhcpv6 Information-request, which not contains IA_NA Option, the request will cause virt-launcher crash.
> 
> More details please look at #9843

Thank you.
Could you please update the commit message with this info so we will have it logged for future us?
E.g. something like:
> When sending DHCPv6 InformationRequest (not contains IA_NA option), the request will cause
virt-launcher DHCPv6 server crash.

**Review by EdDev — COMMENTED** [review]
The fix looks good, thank you.
Please just justify/reason the change in the commit message so we would have this information available in the future.

it would also be helpful if you can confirm that this has been tested with the mentioned Ubuntu OS, assuring it solved the problem.
We do not have e2e tests to cover it.

**Comment by lxs137** [comment]
> assuring

@EdDev I have updated the commit message. The bugfix works well on my Ubuntu GuestOS :-)

**Review by EdDev — APPROVED** [review]
Thank you!

**Review by maiqueb — APPROVED** [review]
Thank you, looks good.

**Comment by AlonaKaplan** [comment]
Thanks!
/approve

**Pull request merged**
