### PR TITLE
make generate to switch copyright to 2023

### PR DESCRIPTION
**Pull request by iholder101**
**What this PR does / why we need it**:
Execute `make generate` to switch copyright to 2023

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by enp0s3 — COMMENTED** [review]
/approve

**Comment by iholder101** [comment]
For the record and to raise attention:

I think this is a classic example of a waste of CI resources (+blockage of other PRs).

Ideally, our CI should realize that since only comments are changed there is no real need to run the whole test suite. This is even worse, since PRs for v0.58 and v0.53 are also created, so we're running the whole test suite 3 times blocking many PRs for no good reason.

FYI @dhiller @brianmcarey

**Review by EdDev — APPROVED** [review]

**Comment by EdDev** [comment]
> For the record and to raise attention:
> 
> I think this is a classic example of a waste of CI resources (+blockage of other PRs).
> 
> Ideally, our CI should realize that since only comments are changed there is no real need to run the whole test suite. This is even worse, since PRs for v0.58 and v0.53 are also created, so we're running the whole test suite 3 times blocking many PRs for no good reason.
> 
> FYI @dhiller @brianmcarey

Or, better, it should not touch the copyright!
The copyright should either remain as it was, or add a period in case it changed (e.g. `20018-2023`).
But marking as if the file is a new one, is probably just wrong.

**Comment by iholder101** [comment]
> Or, better, ...

I agree, just want to stress that the two don't contradict each other :)
My previous comment also refers to PRs that change comments typo / commit description / etc.

**Comment by enp0s3** [comment]
@iholder101 @EdDev This is happening because we are running the code generators from scratch, upon each call to `make generate`. That deserves improvement, to run only on changed files. And with a year range

**Comment by iholder101** [comment]
> @iholder101 @EdDev This is happening because we are running the code generators from scratch, upon each call to `make generate`. That deserves improvement, to run only on changed files. And with a year range

YES! :+1: 
It will also greatly improve `make generate`'s performance which currently includes no caching and always runs from scratch as you mentioned.

**Pull request merged**
