### PR TITLE
Write virtctl errors to stderr

### PR DESCRIPTION
**Pull request by orelmisan**
Signed-off-by: Orel Misan <omisan@redhat.com>

**What this PR does / why we need it**:
virtctl was writing errors to stdout so errors couldn't be differentiated from regular output
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
virtctl errors are written to stderr instead of stdout
```

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
Seems like the correct move. 

/ok-to-test

**Comment by maiqueb** [comment]
@orelmisan I think this seemingly minor change does require some release notes - i.e. if I (for whatever reason) have some automation relying on the stdout of this command, it'll break).

**Comment by EdDev** [comment]
Nice. Have you managed to check it really works?

**Comment by orelmisan** [comment]
@maiqueb you are right, a release note was added, thanks

**Comment by orelmisan** [comment]
> Nice. Have you managed to check it really works?

@EdDev this was tested using manual IO redirection, for example:
$ virtctl foo 2> /dev/null
$ virtctl ssh nonexistentvm 2> /dev/null
$ virtctl ssh 2> /dev/null

**Comment by orelmisan** [comment]
Clarification: this PR lets the user the ability to differentiate errors (stderr) from general output (stdout).
A user can filter stdout, stderr or both using the shell's IO redirection feature:
```bash
$ virtctl foo 2> virtctl_errors.log
$ virtctl ssh nonexistentvm 2>> virtctl_errors.log
$ virtctl ssh >> virtctl.log 2> /dev/null
```

**Review by EdDev — APPROVED** [review]
Thank you!

**Pull request merged**
