### PR TITLE
Reduce default CompletionTimeoutPerGiB from 800s to 150s

### PR DESCRIPTION
**Pull request by iholder101**
### What this PR does
During upgrades VMs are being migrated all over the place, perhaps multiple times per VM. The `CompletionTimeoutPerGiB` [1] parameter is crucial for these scenarios, as a too-high value can cause a migration to hang for a huge amount of time before either switching to post-copy, using a paused/cold migration [2], or cancelling the migration and trying again. The current default of 800 seconds (~= 13.3 minutes) per GB is assumed to be too high on most environments, and therefore is reduced to 150 seconds (2.5 minutes).

As an example, if a guest needs to transfer 64GBs, it will take more than 14 hours (!!) [3] before switching to post-copy.
After this change, it'll switch after about 2.5 hours, which is assumed to be enough.

[1] https://kubevirt.io/user-guide/compute/live_migration/#completion-time
[2] https://github.com/kubevirt/kubevirt/pull/11833
[3] `64*800` seconds == `51200` seconds == `51200/3600` hours == 14.2 hours

Before this PR:
The default for `CompletionTimeoutPerGiB` is 800 seconds (~= 13.3 minutes).
if a guest needs to transfer 64GBs, it will take more than 14 hours (!!) before switching to post-copy.

After this PR:
The default for `CompletionTimeoutPerGiB` is 150 seconds (= 2.5 minutes).
if a guest needs to transfer 64GBs, it'll switch after about 2.5 hours

### Additional context
This PR follows the suggestion in this comment: https://github.com/kubevirt/user-guide/pull/834#issuecomment-2353287824

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] ~Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required~
- [X] PR: The PR description is expressive enough and will help future contributors
- [X] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] ~Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)~
- [ ] ~Upgrade: Impact of this change on upgrade flows was considered and addressed if required~
- [ ] ~Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test~
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] ~Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered~

### Release note

```release-note
Reduce default CompletionTimeoutPerGiB from 800s to 150s
```

### CODE REVIEW

**Comment by vladikr** [comment]
/approve
We saw that the default 800 seconds from the `completionTimeoutPerGiB` is too high. 
We need to reduce it significantly.
150 seconds seems safe enough for me. 

I want to get Jenifer's advice as well. But I have not found the correct username ...

**Comment by iholder101** [comment]
> /approve We saw that the default 800 seconds from the `completionTimeoutPerGiB` is too high. We need to reduce it significantly. 150 seconds seems safe enough for me.
> 
> I want to get Jenifer's advice as well. But I have not found the correct username ...

/cc @jeniferh

**Comment by iholder101** [comment]
Holding for a while to let others share their opinions.
/hold

**Comment by iholder101** [comment]
/remove-kind api-change

There are no API changes here except for documentation.

**Comment by iholder101** [comment]
After a week with no objections I'll remove the hold.
/hold cancel

**Comment by jeniferh** [comment]
> > /approve We saw that the default 800 seconds from the `completionTimeoutPerGiB` is too high. We need to reduce it significantly. 150 seconds seems safe enough for me.
> > I want to get Jenifer's advice as well. But I have not found the correct username ...
> 
> /cc @jeniferh

Nice improvement @iholder101 , thanks!  Yeah we discussed ~200 awhile back, so your 150 logic sounds good to me.

**Comment by iholder101** [comment]
> > > /approve We saw that the default 800 seconds from the `completionTimeoutPerGiB` is too high. We need to reduce it significantly. 150 seconds seems safe enough for me.
> > > I want to get Jenifer's advice as well. But I have not found the correct username ...
> > 
> > 
> > /cc @jeniferh
> 
> Nice improvement @iholder101 , thanks! Yeah we discussed ~200 awhile back, so your 150 logic sounds good to me.

Thank you @jeniferh!
If you'd have information on the affect of this change, especially w.r.t. upgrade times, it will be appreciate if you'd share it :)

**Pull request merged**
