### PR TITLE
WORKSPACE: Update CirrOS to 0.6.2 and remove invalid Alpine builddep URLs

### PR DESCRIPTION
**Pull request by lyarwood**
/cc @0xFelix 

### What this PR does

$subject, happy to also bump alpine to a later release if it would be useful.

After this PR:

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm

@brianmcarey Can you shed some light on how the builddep URLs became invalid? IIRC that cache is managed by us and and files in it should stay valid as long as they're referenced? Will the next run of the cache updater recreate these URLs?

**Comment by brianmcarey** [comment]
> /lgtm
> 
> @brianmcarey Can you shed some light on how the builddep URLs became invalid? IIRC that cache is managed by us and and files in it should stay valid as long as they're referenced? Will the next run of the cache updater recreate these URLs?

These URLs are generally created by the periodic mirroring job as @lyarwood mentioned in his commit - how were the broken URLs created? Were the files manually uploaded?

**Comment by lyarwood** [comment]
/hold
/retest-required

Just holding while I take another look at the CI failures, these might be legit.

> These URLs are generally created by the periodic mirroring job as @lyarwood mentioned in his commit - how were the broken URLs created? Were the files manually uploaded?

I think these were manually updated while nothing was uploaded.

**Comment by brianmcarey** [comment]
> > These URLs are generally created by the periodic mirroring job as @lyarwood mentioned in his commit - how were the broken URLs created? Were the files manually uploaded?
> 
> I think these were manually updated while nothing was uploaded.

Yea that would probably be the cause - these URLs are created as part of the mirroring automation so they are managed with automation.

**Comment by 0xFelix** [comment]
@brianmcarey My bad, didn't check the commit message. Thanks for clarifying it.

**Pull request closed without merging**
