### PR TITLE
[e2e]: improve the virt-handler rate limiter test

### PR DESCRIPTION
**Pull request by enp0s3**
Signed-off-by: Igor Bezukh <ibezukh@redhat.com>

**What this PR does / why we need it**:
It was seen that under high utilization the un-mounting process
can be way slower that the test timeouts, thus object deletion timeout
can be reached and the test will fail.

Replace a bootable VM with a non bootable one. That should
spare the test from spending time on mounting and un-mounting
the container-disk volumes as part of the VM state transition.

Fixes #
https://search.ci.kubevirt.io/?search=virt+handler+rate+limiter&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Special notes for your reviewer**:
For non-bootable VMs, the traversal of the phases for the VMI and the VMI pod is the same as if a VM has a bootable OS.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/approve

interesting approach. this could very well help :)

**Review by dhiller — APPROVED** [review]
Thanks!

**Pull request merged**
