### PR TITLE
transition to CDI beta API and use CDI 1.20.0 for testing

### PR DESCRIPTION
**Pull request by mhenriks**
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

**What this PR does / why we need it**:

Should be pretty self explanatory.  CDI has a beta API now.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Use CDI beta api
```

### CODE REVIEW

**Comment by mhenriks** [comment]
attn @orenc1 @tiraboschi

**Comment by orenc1** [comment]
All test passed.
@danielBelenky , could you please review & approve?
https://github.com/kubevirt/hyperconverged-cluster-operator/pull/699
is waiting for this to be merged.

Thanks

**Comment by rmohr** [comment]
@mhenriks would it make sense to move these updates to kubevirtci and consume newer cdi versions through a kubevirtci bump to be more outage-resilient and to improve the deployment speed on cluster-synces?

**Comment by rmohr** [comment]
/hold

@mhenriks would it make sense to move these updates to kubevirtci and consume newer cdi versions through a kubevirtci bump to be more outage-resilient and to improve the deployment speed on cluster-synces?

**Comment by mhenriks** [comment]
@rmohr that would be nice, but the important part of this is the API version update and I'd like to get that in ASAP to unblock HCO/@orenc1.

**Comment by rmohr** [comment]
> @rmohr that would be nice, but the important part of this is the API version update and I'd like to get that in ASAP to unblock HCO/@orenc1.

What is the timeframe we are talking about and the importance?

**Comment by rmohr** [comment]
/hold cancel

As @mhenriks pointed out, the CDI dependencies are hosted on docker hub which means that short-term outages will be covered by or CI docker hub proxy. To streamline all the test dependency management and ensure that we keep resilient and get more resilient we need to move such dependencies to kubevirtci. We both a gree on that and it will happen.

**Comment by rmohr** [comment]
/approve cancel

Still need to discuss some upgrade paths regarding to CDI and KubeVirt.

**Comment by rmohr** [comment]
@mhenriks is my assumption correct that one who updates kubevirt now has to update CDI first to not run into weird situations, since there seems to be no overlap-deprecation-time on the client where we can allow people to still stick to an older CDI version?

**Comment by mhenriks** [comment]
NOPE

**Pull request closed without merging**
