### PR TITLE
[release-0.58]Fix and arrange libvmi.GetPodByVirtualMachineInstance function to avoid flakiness

### PR DESCRIPTION
**Pull request by Barakmor1**
**What this PR does / why we need it**:
This PR is manual backport of  https://github.com/kubevirt/kubevirt/pull/8902/commits/7e53ea9cf346ef6f98217c1be206875a7d7924e8
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder101** [comment]
/lgtm

/cc @enp0s3 
Can you please also have a look?

**Comment by enp0s3** [comment]
@Barakmor1 Hi, I see the following error: 
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   tests/vmi_gpu_test.go
no changes added to commit (use "git add" and/or "git commit -a")
make: *** [Makefile:131: build-verify] Error 1
```

Perhaps you need to commit `make generate` changes

**Comment by Barakmor1** [comment]
> @Barakmor1 Hi, I see the following error:
> 
> ```
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git restore <file>..." to discard changes in working directory)
> 	modified:   tests/vmi_gpu_test.go
> no changes added to commit (use "git add" and/or "git commit -a")
> make: *** [Makefile:131: build-verify] Error 1
> ```
> 
> Perhaps you need to commit `make generate` changes

Done :)

**Review by enp0s3 — APPROVED** [review]
/approve

**Pull request merged**
