### PR TITLE
converter: Hint at the type of serial console

### PR DESCRIPTION
**Pull request by fabiand**
**What this PR does / why we need it**:
It's leaving a hint in the API docs about what type of console we are adding

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by xpivarc — APPROVED** [review]
/approve

**Comment by xpivarc** [comment]
/hold
Missing `make generate`

**Comment by fabiand** [comment]
working on it

**Comment by fabiand** [comment]
@xpivarc my builder vm got destroyed, do you have a chance to take over this patch?

**Pull request merged**
