### PR TITLE
Fix flaky SEV test

### PR DESCRIPTION
**Pull request by vasiliy-ul**
**What this PR does / why we need it**:

This PR is supposed to fix the SEV test which was added to quarantine https://github.com/kubevirt/kubevirt/pull/9996

Considering that we want to ensure SEV devices are not advertised when the feature gate is disabled, probably it makes more sense to check the allocatable resources. Since the capacity just reflects the maximum number observed at some point in time.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by xpivarc** [comment]
@vasiliy-ul 
Were you able to reproduce locally?

**Comment by xpivarc** [comment]
Thanks, great findings!

**Comment by vasiliy-ul** [comment]
/cc @brianmcarey 

This PR includes `Revert "Quarantine flaky SEV test that tries to reset SEV capacity"`. I added this commit to test in CI. How shall we proceed with the fix? I can remove the revert, and we can give this fix a try for some time on the quarantine lanes. Then, if the results are stable enough, we can remove the test from quarantine in a separate PR. Or shall we do it right here?

**Comment by brianmcarey** [comment]
> /cc @brianmcarey
> 
> This PR includes `Revert "Quarantine flaky SEV test that tries to reset SEV capacity"`. I added this commit to test in CI. How shall we proceed with the fix? I can remove the revert, and we can give this fix a try for some time on the quarantine lanes. Then, if the results are stable enough, we can remove the test from quarantine in a separate PR. Or shall we do it right here?

Yes that sounds good to me - lets just go with the fix for now and we should get a good signal from the periodic lanes after a few days if this has worked.

**Comment by vasiliy-ul** [comment]
Dropped the revert and restored the `[QUARANTINE]` label. I think the PR should be ready. Let's see how it works on the periodics.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Pull request merged**
