### PR TITLE
Forward all in masquerade 0.17

### PR DESCRIPTION
**Pull request by SchSeba**
**What this PR does / why we need it**:
Cherry-pick for https://github.com/kubevirt/kubevirt/pull/2331

**Release note**:

```release-note
forward all ports using masquerade
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/2542)

### CODE REVIEW

**Comment by SchSeba** [comment]
make a rebase after we merged the nftable.

**Comment by SchSeba** [comment]
@rmohr The tests looks good now can you please take another look?

**Comment by rmohr** [comment]
@cynepco3hahue can you have a look and approve?

**Pull request merged**
