### PR TITLE
Remove IO error storage tests from quarantine

### PR DESCRIPTION
**Pull request by akalenyu**
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>

**What this PR does / why we need it**:
Following the standard protocol of waiting 14 days,
these have been green since https://github.com/kubevirt/kubevirt/pull/7455.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
https://search.ci.kubevirt.io/?search=should+pause+VMI+on+IO+error&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by xpivarc — APPROVED** [review]

**Comment by xpivarc** [comment]
Please include CI search https://search.ci.kubevirt.io/?search=should+pause+VMI+on+IO+error&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by akalenyu** [comment]
> Please include CI search https://search.ci.kubevirt.io/?search=should+pause+VMI+on+IO+error&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

Added in PR description

**Comment by xpivarc** [comment]
/cc @dhiller 
Can you approve?

**Comment by dhiller** [comment]
/approve

/override pull-kubevirt-e2e-kind-1.23-vgpu

Overridden vgpu failure due to failure to delete cluster although tests have passed.

FYI @EdDev

**Pull request merged**
