### PR TITLE
[release-0.59] Bump to go 1.19.12

### LINKED ISSUE #10213: go 1.18.8 throwing High and Critical CVEs
**What happened**:

What happened:
Container scans reveal high and critical CVEs with current golang version of go go-1.18.8

What you expected to happen:

Update go to the newest version which to mitigate the vulnerabilities.

How to reproduce it (as minimally and precisely as possible):
Running a security scan for CVEs against the containers

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.2
- Kubernetes version (use `kubectl version`): 1.26.1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:
Bump to go 1.19.12

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10213 

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
It needs the builder image generated and pushed to the registry (then specified for consumption back here).

@brianmcarey , could you help with this?

/hold

**Review by brianmcarey — COMMENTED** [review]
@EdDev - sure I can get this built - does it make more sense to bump this in main first and then backport? Or is this urgent? 

EDIT:

I built the following against release-0.59 with your change -> `quay.io/kubevirt/builder:2308022054-e175af729`

**Comment by EdDev** [comment]
> @EdDev - sure I can get this built - does it make more sense to bump this in main first and then backport? Or is this urgent?

Good point.
I will do this also on `release-1.0`.

Regarding main, I think we need to bump it to Go 1.20 or the coming  Go 1.21, as the existing 1.19 will reach end of support (when 1.21 comes in).
 As Go 1.21 is expected to be released in a week or two, I suggest to wait for it and them bump.
 
> I built the following against release-0.59 with your change -> `quay.io/kubevirt/builder:2308022054-e175af729`

Thanks you!
I will update the PR.

**Comment by EdDev** [comment]
change: Added the build image that includes Go 1.19.12.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

Just one nit - can you update the PR title to make it clear that its for release-0.59 - `[release-0.59]`

**Pull request merged**
