### PR TITLE
prometheus: network: report packets and error

### PR DESCRIPTION
**Pull request by fromanirh**
**What this PR does / why we need it**:
Add metrics about packets and errors, which will be consumed
by the UI.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
N/A

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by fromanirh** [comment]
the windows lane keep failing because
```
Unable to connect to the server: net/http: TLS handshake timeout
```

**Comment by rmohr** [comment]
@fromanirh it is still the same run: https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=kubevirt&pr=2432. Windows lane has the issue that it can only run once in parallel. Not your turn yet.

**Comment by rmohr** [comment]
> all lanes green! :)



@fromanirh I see a pattern there when it comes to your PRs ;)

**Pull request merged**
