### PR TITLE
Add make target to protoc generation

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
Calling "make generate" everytime there is a change at a .proto file
takes a lot of time, this change move the protoc generation to
hack/gen-proto.sh and it's called from hack/generate.sh and from a
target at Makefile so it can be called if needed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
/lgtm

but the CI outage is still going on.

**Review by enp0s3 — APPROVED** [review]
/approve

**Pull request merged**
