### PR TITLE
Prepare migration tests to be executed in parallel

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Make 40+ migration tests run in parallel and move them to dedicated test lanes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve

**Comment by rmohr** [comment]
/hold

to allow a coordinated merge with the job definition updates.

**Comment by rmohr** [comment]
/test pull-kubevirt-e2e-k8s-1.22-sig-storage

Unrelated error.

**Pull request merged**
