### PR TITLE
[release.1.3] Manual backport of 12395

### PR DESCRIPTION
**Pull request by alicefr**
### What this PR does
Manual backport of #12395 
The API change consists in a new condition which helps to better understand why the volume migration isn't possible.
This backport also includes the  commit from #12241 to facilitate the backport of the unit tests.

### Release note

```release-note
Add new condition for VMIStorageLiveMigratable
```

### CODE REVIEW

**Comment by dhiller** [comment]
@alicefr there's something wrong here - I thought it was just a hiccup, since I didn't see anything in the logs. Maybe you can take a look?

**Comment by alicefr** [comment]
@dhiller you are right sorry, now it should be fine

**Comment by fossedihelm** [comment]
/unhold
https://github.com/kubevirt/kubevirt/pull/12783 merged

**Review by fossedihelm — APPROVED** [review]
Thank you!

**Comment by fossedihelm** [comment]
Comments come from an older non-finished review. Please ignore them

**Pull request merged**
