### PR TITLE
tests, net, hotplug: Drop stopped VM test

### PR DESCRIPTION
**Pull request by EdDev**
### What this PR does

The scenario of marking a network interface to be unplugged (set to
`absent` state) can be considered redundant because it is not a
hotunplug (the VM is not running, i.e. no VMI) scenario.

Dropping this test from the e2e tests and moving it to a unit test seems
more appropriate.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

Depends on #12018 , please review only the last commit in this PR context.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
cc @orelmisan @ormergi

**Review by orelmisan — COMMENTED** [review]
Thank you for the PR @EdDev.
Since the unit tests are introduced by https://github.com/kubevirt/kubevirt/pull/12090, I suggest that we will wait for it to be merged first.
Other than that, lgtm.
WDYT?

**Review by ormergi — APPROVED** [review]

**Comment by ormergi** [comment]
> Thank you for the PR @EdDev. Since the unit tests are introduced in #12090, I suggest that we will wait for it to be merged first. Other than that, lgtm. WDYT?

In a scenario of stopped VM, the spec has not been used yet and there is no underlying VMI/pod/guest, the subject interface can be removed entirely from the spec,  I dont think there is much to cover in unit tests.

Note that this test was added to cover the case where virtctl is used to unplugn an interface from a stopped VM.
Today virtctl have no such verbs, uplug interfaces is done by mutating the VM spec.

**Comment by orelmisan** [comment]
> In a scenario of stopped VM, the spec has not been used yet and there is no underlying VMI/pod/guest, the subject interface can be removed entirely from the spec, I dont think there is much to cover in unit tests.

AFAIU the current logic - if the VM is stopped (meaning there is no VMI) and there are interfaces marked as absent, the VM controller will do nothing until there will be a VMI [1].

[1] https://github.com/kubevirt/kubevirt/blob/7f691054aad5d1930f0c385df5429c1128652fe3/pkg/virt-controller/watch/vm.go#L3139

**Review by orelmisan — APPROVED** [review]
Thank you

**Review by ormergi — APPROVED** [review]

**Comment by EdDev** [comment]
Raising

/approve

**Pull request merged**
