### PR TITLE
Fix MAC and bridge tests

### PR DESCRIPTION
**Pull request by yuvalif**
* remove VMIs after each test in the vmi_bridge_test suite, to decreate the load from the test cluster
* remove the ability to add static MAC to interfaces connected to a "pod" network, and related tests. this was merged from "master" but is not needed in cnv-1

```release-note
NONE
```

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@danielBelenky Have some problem with docker
```
Status: Downloaded newer image for docker.io/kubevirtci/gocli@sha256:aa7f295a7908fa333ab5e98ef3af0bfafbabfd3cee2b83f9af47f722e3000f6a
/usr/bin/docker-current: Error response from daemon: grpc: the connection is unavailable.
make: *** [cluster-down] Error 125
```
under the job https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/1636//artifact/check-patch.windows2016-release.el7.x86_64/mock_logs/script/stdout_stderr.log

Can you take a look please?

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by yanirq** [comment]
[[epic-detailed-monitoring] Prepare components for metrics collection for scale tests](https://trello.com/c/qe7PGx2c/8-epic-detailed-monitoring-prepare-components-for-metrics-collection-for-scale-tests)

**Pull request merged**
