### PR TITLE
refector: fix deprecated function

### PR DESCRIPTION
**Pull request by yj-yoo**
### What this PR does
deprecated

1. rand.Seed()
2. grpc.WithInsecure()
3. StreamWithContext()
4.
golang.org/x/crypto/ssh/terminal
https://pkg.go.dev/golang.org/x/crypto/ssh/terminal
5.
k8s.io/utils/pointer
https://pkg.go.dev/k8s.io/utils/pointer

6.
etc...

detail #11316 

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note

```

### CODE REVIEW

**Comment by victortoso** [comment]
Hi @yj-yoo, thanks for the PR.

Would you mind reworking the commits to have one commit per deprecated fix? This will make reviewing much easier and faster. Also, as mentioned in this https://github.com/kubevirt/kubevirt/issues/11316#issuecomment-1956250395 if there are any important rationales for the change, please add it in their respective commit log. Thanks!

**Comment by yj-yoo** [comment]
@victortoso 
Thanks for the reply.
I understand that someone else is also working on the issue I wrote about. Can I continue with this regardless?

**Comment by yj-yoo** [comment]
@victortoso As you advised, I closed this issue, subdivided the work, and raised the issue. #11348

**Comment by victortoso** [comment]
> @victortoso As you advised, I closed this issue, subdivided the work, and raised the issue. https://github.com/kubevirt/kubevirt/pull/11348

There was no need to close it. My suggestion was to mainly break down the big commit in smaller ones, each with its deprecated function being changed plus the rationale behind it. Besides being easier to review, If we don't agree with one function, you would just need to drop the commit related to that change. Simpler.

Thanks for your work.

**Comment by yj-yoo** [comment]
@victortoso 
However, I found another solution for the pointer package, which takes up a lot of space, and have already modified it and created another PR😂. Could you please review that PR?

**Pull request closed without merging**
