### PR TITLE
Add SUSE to ADOPTERS.md

### PR DESCRIPTION
**Pull request by vasiliy-ul**
**What this PR does / why we need it**:

https://github.com/kubevirt/community/issues/110

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hw-claudio** [comment]
Acked-by: Claudio Fontana <cfontana@suse.de>

-- 
Claudio Fontana
Engineering Manager Virtualization, SUSE Labs Core

SUSE Software Solutions Italy Srl

**Comment by jfehlig** [comment]
Looks good Vasily. Thanks!

**Comment by mazzystr** [comment]
@vasiliy-ul  Wow!  This is amazing!  Thank you for this!  

Please invite the project to speak at a SuSe event sometime.  I have inside information that the project organizer has great interest in it. ;)

**Pull request merged**
