### PR TITLE
Replace unmaintained go-ps package with the gopsutil package

### PR DESCRIPTION
**Pull request by iholder101**
### What this PR does
As @Barakmor1 mentioned in a [previous PR](https://github.com/kubevirt/kubevirt/pull/13216), we are currently using https://github.com/mitchellh/go-ps as a dependency for Kubevirt. This package helps finding running processes, their PID and PPID, executable name, and so on. However, this package is deprecated and unmaintained for a while now. As the package maintainer [writes](https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc):

> I will no longer be accepting issues or pull requests and will never tag a new release ...  I've almost completely ignored issues and pull requests for a couple years.

This PR drops go-ps as a dependency, replacing it with https://github.com/shirou/gopsutil, which is maintained (latest released only 2 weeks ago) and is very popular (above 10k stars on github).

Before this PR:
Kubevirt is dependent on the unmaintained https://github.com/mitchellh/go-ps package.

After this PR:
https://github.com/mitchellh/go-ps is entirely dropped in favor of https://github.com/shirou/gopsutil.

### Special notes for your reviewer
* Keeping the code testable wasn't trivial. I had to introduce an internal process type that would be able to be mocked, keeping the unit tests isolated from the actual system.
* In the new package, the process struct carries a lock. Therefore, I had to change some function signatures to deal with pointers rather with struct copies.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] ~Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required~
- [X] PR: The PR description is expressive enough and will help future contributors
- [X] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [X] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] ~Upgrade: Impact of this change on upgrade flows was considered and addressed if required~
- [X] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] ~Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.~
- [ ] ~Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered~

### Release note

```release-note
Replace unmaintained go-ps package with the gopsutil package
```

### CODE REVIEW

**Comment by Barakmor1** [comment]
@iholder101, I haven’t had the chance to dive into the details yet but i noticed that this PR removes about 1,000 lines but adds around 45,000, which raised some concerns for me.

**Comment by iholder101** [comment]
> @iholder101, I haven’t had the chance to dive into the details yet but i noticed that this PR removes about 1,000 lines but adds around 45,000, which raised some concerns for me.

100% of the new files presented in this PR are vendored files. The old package was old and unmaintained and was probably smaller in size.

The actual (i.e. non-vendored) amount of code added in this PR isn't very large AFAICT.

**Comment by iholder101** [comment]
I've now checked how this change affected virt-handler's binary size.

Before this PR:
```
bash-5.1# ls -lh /usr/bin/virt-handler
-r-xr-xr-x. 1 root root 63M Jan  1  1970 /usr/bin/virt-handler
```

After this PR:
```
bash-5.1# ls -lh /usr/bin/virt-handler
-r-xr-xr-x. 1 root root 64M Jan  1  1970 /usr/bin/virt-handler
```

So we're talking about 1MB difference, which is pretty negligible.

**Comment by jean-edouard** [comment]
I am also concerned about the amount of vendored code added here. How much do we trust github users shirou/lufia/tklauser/... for staying on top of bugs and security concerns?
Also, to me, growing binaries that use `ps` by 1MB seems huge!
At this point, I'd actually prefer maintaining our own `ps` function rather than depending on all that stuff, but I'm curious about what others think.

**Comment by fossedihelm** [comment]
> I am also concerned about the amount of vendored code added here. How much do we trust github users shirou/lufia/tklauser/... for staying on top of bugs and security concerns? Also, to me, growing binaries that use `ps` by 1MB seems huge! At this point, I'd actually prefer maintaining our own `ps` function rather than depending on all that stuff, but I'm curious about what others think.

Agree, I think we use this only in 5 places and we can get rid of all the stuff that it is providing.

**Comment by iholder101** [comment]
> I am also concerned about the amount of vendored code added here. How much do we trust github users shirou/lufia/tklauser/... for staying on top of bugs and security concerns?

I'd say it depends.
Here we're talking about a very famous repo with mroe than 10k starts on github. It seems well-maintained and widely used.

> Also, to me, growing binaries that use `ps` by 1MB seems huge!

Is it?
Values are also rounded, so it might be even less than a MB. Intuitively I wouldn't consider this as a "huge" change. Can you explain why it is significant in your opinion?

I'd also point out that if it doesn't affect the binary size, I'm not sure if adding more lines of code to vendored packages has a major downside.

> At this point, I'd actually prefer maintaining our own `ps` function rather than depending on all that stuff, but I'm curious about what others think.

I think this is a valid approach, but that it has downsides as well:
* <ins>Maintainability</ins>: I'm not sure we should get into the business of dealing with processes. Currently we use this package for several usages, but these could expand over time. What if we'd need to know a process' memory consumption for example? This would add maintenance and testing responsibility to Kubevirt on a subject it is not focused on.
* <ins>Security</ins>: Because this is outside of our core expertise, we might insert security bugs as well. I'm not sure that a package that's focused on this area will be worse than us in this aspect.

Saying that, I do think that implementing it ourselves makes sense and is a valid alternative. If there are objections to getting this in I'd close this PR. When I'll have the time I might circle back to this.

**Review by orelmisan — COMMENTED** [review]
Thank you for the PR @iholder101.

Were there any alternative packages being considered?

**Comment by akalenyu** [comment]
> I am also concerned about the amount of vendored code added here. How much do we trust github users shirou/lufia/tklauser/... for staying on top of bugs and security concerns? Also, to me, growing binaries that use `ps` by 1MB seems huge! At this point, I'd actually prefer maintaining our own `ps` function rather than depending on all that stuff, but I'm curious about what others think.

Yeah I've peeked at this before, ending up with the same conclusion as in https://github.com/cloudnative-pg/cloudnative-pg/issues/3612#issuecomment-2225815502

**Comment by alicefr** [comment]
> > I am also concerned about the amount of vendored code added here. How much do we trust github users shirou/lufia/tklauser/... for staying on top of bugs and security concerns?
> 
> I'd say it depends. Here we're talking about a very famous repo with mroe than 10k starts on github. It seems well-maintained and widely used.
> 
> > Also, to me, growing binaries that use `ps` by 1MB seems huge!
> 
> Is it? Values are also rounded, so it might be even less than a MB. Intuitively I wouldn't consider this as a "huge" change. Can you explain why it is significant in your opinion?
> 
> I'd also point out that if it doesn't affect the binary size, I'm not sure if adding more lines of code to vendored packages has a major downside.
> 
> > At this point, I'd actually prefer maintaining our own `ps` function rather than depending on all that stuff, but I'm curious about what others think.
> 
> I think this is a valid approach, but that it has downsides as well:
> 
> * Maintainability: I'm not sure we should get into the business of dealing with processes. Currently we use this package for several usages, but these could expand over time. What if we'd need to know a process' memory consumption for example? This would add maintenance and testing responsibility to Kubevirt on a subject it is not focused on.
> * Security: Because this is outside of our core expertise, we might insert security bugs as well. I'm not sure that a package that's focused on this area will be worse than us in this aspect.
> 
> Saying that, I do think that implementing it ourselves makes sense and is a valid alternative. If there are objections to getting this in I'd close this PR. When I'll have the time I might circle back to this.

TBH, I think the functionalities we use from that package aren't that complicated. It mostly reads files from proc. I would be in favor to have our implementation. In this way, we have a minimal set of functionalities that we needs and not packages from github users. Thing which contradicts our own [guidelines](https://github.com/kubevirt/kubevirt/blob/main/docs/coding-conventions.md#short-coding-conventions-tldr)

**Comment by iholder101** [comment]
Thanks for the feedback folks. I'll circle back to this.

/close

**Pull request closed without merging**
