### PR TITLE
[release-1.2] VM controller - move unit tests to fake client (VirtualMachineInterface)

### PR DESCRIPTION
**Pull request by xpivarc**
### What this PR does
Backport of https://github.com/kubevirt/kubevirt/pull/11726

Fixes #

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
/test 
pull-kubevirt-unit-test

**Review by fossedihelm — APPROVED** [review]

**Review by jean-edouard — COMMENTED** [review]
/approve

**Pull request merged**
