### PR TITLE
[release-1.1] Admit eviction on completed virt-launcher pods

### PR DESCRIPTION
**Pull request by fossedihelm**
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/12451
### Release note

```release-note
Fix: eviction requests to completed virt-launcher pods cannot trigger a live migration
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
/hold
release 1.3 (https://github.com/kubevirt/kubevirt/pull/12495) and release 1.2 (https://github.com/kubevirt/kubevirt/pull/12496) first.
/cc @orelmisan @davidvossel

**Comment by jean-edouard** [comment]
Looks like you're also backporting [`0827137` (#11532)](https://github.com/kubevirt/kubevirt/pull/11532/commits/08271370cf1c4ca835034a062338944601413a8b)
Is there any chance you could make that backport explicit? (i.e. cherry-pick that commit first and amend the PR description).
Thanks

**Comment by fossedihelm** [comment]
> Looks like you're also backporting [`0827137` (#11532)](https://github.com/kubevirt/kubevirt/pull/11532/commits/08271370cf1c4ca835034a062338944601413a8b) Is there any chance you could make that backport explicit? (i.e. cherry-pick that commit first and amend the PR description). Thanks

Right! I thought I was picking just a little part of the PR, but didn't realize that was an entire commit.
Adjusted. Thank you!

**Comment by fossedihelm** [comment]
/retest
@jean-edouard can you have a second look? Thanks

**Review by jean-edouard — APPROVED** [review]

**Pull request merged**
