### PR TITLE
Bump kubevirtci

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Bump kubevirtci to
 * get the newest Z releases of our clusters.
 * consume the k8s provider now with etcd writing to memory only to gather insight if this is an improvement we want to do.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

We have a weird new problem since my z release bump in kubevirtci

**Review by dhiller — COMMENTED** [review]
/lgtm
/approve

**Comment by rmohr** [comment]
/hold cancel

The issue is gone with the newest rebuilds.

**Comment by rmohr** [comment]
@dhiller the etcd-in-memory change is merged and the  bump is up to date.

**Review by dhiller — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
