### PR TITLE
[release-1.2] Manual backport of improve error reporting when fsfreeze fails

### PR DESCRIPTION
**Pull request by alromeros**
### What this PR does

This is a manual backport of https://github.com/kubevirt/kubevirt/pull/11051. I'm adding the quarantined test for consistency, but feel free to argue otherwise.

Fixes # https://issues.redhat.com/browse/CNV-32664

### Release note

```release-note
Bugfix: Improve error reporting when fsfreeze fails
```

### CODE REVIEW

**Comment by mhenriks** [comment]
@xpivarc I think it makes sense to add the quarantined test because eventually (hopefully soon) there will be a fix for the underlying issue that will be backported to this branch.  Since you expressed concern about this test existing at all checking with you to get your thoughts

**Comment by alromeros** [comment]
/cc @xpivarc 
Could you please take a look at this? Thanks!

**Comment by xpivarc** [comment]
@mhenriks @alromeros Please, remind me why the test is in quarantine

**Comment by alromeros** [comment]
> @mhenriks @alromeros Please, remind me why the test is in quarantine

Sure, we have a snapshot bug that prevents some finalizers from being removed. This test triggered this bug quite often so we quarantined it here: https://github.com/kubevirt/kubevirt/pull/11244. I think @mhenriks is already working on the fix.

**Comment by xpivarc** [comment]
Thanks!
/approve

Please, open a tracking issue

**Comment by alromeros** [comment]
Created a tracking issue for the bug as requested https://github.com/kubevirt/kubevirt/issues/11432.

**Pull request merged**
