### PR TITLE
VMExport: Check the error before emitting events

### PR DESCRIPTION
**Pull request by vasiliy-ul**
**What this PR does / why we need it**:

Error check added for `ExporterPodCreated` and `ServiceCreated` events, as the creation of the respective objects may fail.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vasiliy-ul** [comment]
/cc @awels, @mhenriks 

Found this while investigating https://github.com/kubevirt/kubevirt/pull/8167. The events do not cause any issue so far, but probably better to ensure they are not emitted on failure. Makes sense?

**Comment by mhenriks** [comment]
Thanks @vasiliy-ul!

**Pull request merged**
