### PR TITLE
Update vendored copy of libvirt.org/libvirt-go

### PR DESCRIPTION
**Pull request by andreabolognani**
**What this PR does / why we need it**:

We recently updated the libvirt package to 7.0.0, so it makes sense to bring in updated Go bindings as well.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vladikr** [comment]
Thanks @andreabolognani !
/approve
/lgtm

**Comment by maya-r** [comment]
The hand-rolled changes to vendor/ will now be reverted whenever someone runs `make deps-update`.
I'm not sure what the effect of it will be if someone fails to notice this before the code is merged.
I think specifying a commit newer than the release in go.mod might be safer.

**Comment by andreabolognani** [comment]
@maya-r I honestly have no idea what the best practices are when it comes to local changes to vendored dependencies... If you know of a way to make sure the local changes stick around as dependencies are updated, please by all means go ahead and modify things accordingly!

**Comment by maya-r** [comment]
The change I have in mind will effectively change libvirt-go to 7.2.0. Is this OK to do?
If not, I will fork libvirt-go and have a 7.0.0+the one commit we want in a repo.

**Comment by andreabolognani** [comment]
@maya-r Normally I would say updating libvirt-go is quite safe, as the binding are explicitly designed so that they will work seamlessly when built against older versions of the C library; however, in this specific case the new version would also contain [libvirt/libvirt-go@90777c7](https://gitlab.com/libvirt/libvirt-go/-/commit/90777c7917f5c48a951c4101d53fef765f45f321), which has recently been reverted in [libvirt/libvirt-go@40e81f2](https://gitlab.com/libvirt/libvirt-go/-/commit/40e81f2fb182fa451ded6a1b4323ecd6dc3c2845) because it turned out to cause more issues than it solved...

It's possible that KubeVirt would not be immediately affected by this because, despite using modules, it's still on Go 1.13?

Since we're on this topic, [libvirt/libvirt-go#9](https://gitlab.com/libvirt/libvirt-go/-/issues/9) is an issue that has been created specifically to try and figure out the best way forward for libvirt-go in the upcoming modules-only world, and I would really appreciate if any knowledgeable person could drop in and leave their thoughts :)

**Pull request merged**
