### PR TITLE
sig-tests: Add 0xFelix as approver

### PR DESCRIPTION
**Pull request by vladikr**
### What this PR does

Proposing Felix as an approver for kubevirt tests.

Felix has been a long time contributor to the KubeVirt project. He also has done multiple [reviews](https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+is%3Aclosed+commenter%3A0xFelix+test+label%3Aapproved+) and [contributions](https://github.com/kubevirt/kubevirt/pulls?page=4&q=is%3Apr+is%3Aclosed+author%3A0xFelix+test+label%3Aapproved) to tests.

Overall, Felix is interested in improving tests and is actively working on it.

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder101** [comment]
Sounds good from my side :)
Good luck @0xFelix and thanks for your contributions!

/lgtm

**Review by jean-edouard — APPROVED** [review]

**Review by xpivarc — APPROVED** [review]
/approve
/hold 
for others to chime in

**Comment by dominikholler** [comment]
@xpivarc are you comfortable to unhold the PR already?

**Comment by vladikr** [comment]
It has been a week - 7 approvals and no additional comments.
I'll remove the hold.
/unhold

**Review by EdDev — APPROVED** [review]
Thank you for joining the effort!

**Pull request merged**
