### PR TITLE
Update libvirt-go to fix memory leak

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:

For more info see https://gitlab.com/libvirt/libvirt-go-module/-/merge_requests/33

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by stu-gott — COMMENTED** [review]
/approve
/lgtm

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

I confirmed that the changes in the libvirt go module are vendored in this update. thanks!

**Pull request merged**
