### PR TITLE
Use masquerade for tests with explicit pod interface

### PR DESCRIPTION
**Pull request by booxter**
Bridge has issues with fe: MAC address prefix, so unless a test
case depends on bridge type used, we should avoid it.

```release-note
NONE
```

### CODE REVIEW

**Comment by fedepaol** [comment]
/lgtm

@booxter you should add release notes: NONE I think

**Comment by slintes** [comment]
@booxter can you please check failed tests? There are some which look unfamiliar to me... thanks.
https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=kubevirt&pr=2663

/release-note-none

**Comment by booxter** [comment]
/retest

Couldn't reproduce the failures even when using the exact same providers.

**Comment by booxter** [comment]
Right now the PR fails on build stage (because of git clone failure and because of missing file on a server).

**Comment by slintes** [comment]
missing file was fixed in the late (CEST) evening
/test all

**Comment by booxter** [comment]
/hold

at least windows failure is related to this patch b/c the test case expects the VMI to have the same IP address that was allocated to the launcher pod, which is not the case for `masquerade`.

**Comment by booxter** [comment]
Only the windows test failure seems related. The rest are unrelated (based on code path analysis) or can't be reproduced locally (those in vmi_networking_test.go in one of failed jobs).

**Comment by booxter** [comment]
/retest

all failures seem unrelated

**Comment by booxter** [comment]
@slintes looks finally ready to go CI-wise!

**Pull request merged**
