### PR TITLE
Added functional test for custom MAC address for SR-IOV

### PR DESCRIPTION
**Pull request by booxter**
**What this PR does / why we need it**: test custom MAC address for SR-IOV interfaces in kubevirt context

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by booxter** [comment]
/hold

There is a legit CI failure in the sriov job. I suspect that the order of interfaces is not deterministic (probably depends on VF PCI IDs allocated - can be eth0 or eth1), hence the failure. I probably need to adjust the test case so that it doesn't assume a particular name of the interface.

**Comment by SchSeba** [comment]
@booxter I really don't know

**Comment by booxter** [comment]
I think I can work around the order issue by iterating over interfaces and checking the one that has an expected vendor ID (!= virtio ID since VFs may be of different vendors).

/hold

**Comment by booxter** [comment]
/hold cancel

There was some issue with previous version where I used the first interface name for SR-IOV interface, despite it's clearly always eth1+ as per other test cases. The latest version should be fine.

There still may be a theoretical issue with ordering interface names in the suite but we'll deal with that if it actually bites us, and we'll need to deal with it for the whole suite, not just this test case.

**Comment by booxter** [comment]
@SchSeba @phoracek it should be ready for review. Thanks.

**Comment by booxter** [comment]
@phoracek can we merge it? or do we expect the last job to pass? code wise, there is no change this PR affects it, but maybe if I rebase then there is some fix in newest master that would tackle it. Is it worth a rebase?

**Comment by slintes** [comment]
> @phoracek can we merge it? or do we expect the last job to pass? code wise, there is no change this PR affects it, but maybe if I rebase then there is some fix in newest master that would tackle it. Is it worth a rebase?

A rebase is not needed, tide (the prow component for merging) is testing PRs against latest commit on master. We "only" need to stop merging manually, because that will make tide to start tests all over again because of the new head on master... let we check with the team if we want to wait for tide or merge manually.

**Pull request merged**
