### PR TITLE
Introduce PASST_VERSION and update RPMs

### PR DESCRIPTION
**Pull request by andreabolognani**
**What this PR does / why we need it**:

As is already the case for other parts of the virtualization stack like QEMU and libvirt, we want to have very precise control over the version of passt that is used by KubeVirt. Make it possible to lock this choice down using an environment variable.

Note that the version of passt is bumped from `0:0.git.2022_08_04.b516d15-0.el8` to `0:0.git.2022_08_29.60ffc5b-1.el8` in the process: this was necessary because the former is now gone from the COPR repo. In order to make the change effective
and keep things consistent, all RPMs are updated.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by AlonaKaplan** [comment]
The risk with this PR is that now passt rpms have no backup on google cloud.
 @andreabolognani please track a PR uploading the backups (similar to [this](https://github.com/kubevirt/kubevirt/pull/8139)) is sent and being reviewed.

/approve

**Comment by andreabolognani** [comment]
/retest

@AlonaKaplan I'll keep an eye out, but AFAIK the mirroring process and subsequent PR generation are automated and I assume such PRs are reviewed rather swiftly, as the human simply needs to double-check that nothing unexpected has managed to sneak in.

**Comment by enp0s3** [comment]
@AlonaKaplan @andreabolognani Hi folks, since this PR got merged we have issues with running the unit tests. Please see the [log](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8403/pull-kubevirt-goveralls/1566715052252205056). It can be reproduced by running `make test` in your local setup

**Comment by andreabolognani** [comment]
> @AlonaKaplan @andreabolognani Hi folks, since this PR got merged we have issues with running the unit tests. Please see the [log](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8403/pull-kubevirt-goveralls/1566715052252205056). It can be reproduced by running `make test` in your local setup.
> 
> I am yet to find the root cause, please advice.

This appears to be caused by the fact that some of the new binaries / libraries that have been added to the workspace are expecting a newer glibc version than the one in the builder image.

For comparison, the version in the workspace was bumped from `2.28-208` to `2.28-209` by this PR, while the version in the builder image is currently `2.28-203`.

Applying the following diff seems to work around the problem:

```diff
diff --git a/hack/bazel-test.sh b/hack/bazel-test.sh
index 192c71810..39be77264 100755
--- a/hack/bazel-test.sh
+++ b/hack/bazel-test.sh
@@ -25,6 +25,9 @@ EOF
     trap collect_results EXIT
 fi
 
+dnf update --refresh -y
+ln -sf /usr/bin/python3 /usr/bin/python
+
 bazel test \
     --config=${ARCHITECTURE} \
     --features race \
```

So I think it would be enough to build / publish a new version of the builder image and update `hack/dockerized` so that it points to it.

**Comment by rmohr** [comment]
> This appears to be caused by the fact that some of the new binaries / libraries that have been added to the workspace are expecting a newer glibc version than the one in the builder image.

Hm, still the sandbox should give us that without having to bump. I will check it when I have a quiet minute.

**Comment by rmohr** [comment]
> The risk with this PR is that now passt rpms have no backup on google cloud.
> @andreabolognani please track a PR uploading the backups (similar to [this](https://github.com/kubevirt/kubevirt/pull/8139)) is sent and being reviewed.

The mirroring happens daily (if something is there to mirror). I think tomorrow at around 9pm cest there should be a mirror PR opened by our bot. In the past the issue was that we did not merge them for a few days and at some point the RPMs would be gone.

It is at least right now the right process to also not mention the mirror urls explicitly when updating. The mirror bot will add it to the PR.

**Comment by andreabolognani** [comment]
> > This appears to be caused by the fact that some of the new binaries / libraries that have been added to the workspace are expecting a newer glibc version than the one in the builder image.
> 
> Hm, still the sandbox should give us that without having to bump. I will check it when I have a quiet minute.

@rmohr here's what I could figure out so far.

The problematic symbol is `_dl_audit_symbind_alt`, which is not found in the `glibc-2.28-203.el8` package installed in the builder image

```
$ objdump -T /lib64/libc.so.6 | grep _dl_audit_symbind_alt
$
```

but is found in the `glibc-2.28-209.el8` package that is now used by the sandbox

```
$ objdump -T .bazeldnf/sandbox/default/root/lib64/libc.so.6 | grep _dl_audit_symbind_alt
0000000000000000      DF *UND*	0000000000000000  GLIBC_PRIVATE _dl_audit_symbind_alt
```

Note that the symbol is marked as undefined, because the actual implementation is in the dynamic loader

```
$ objdump -T .bazeldnf/sandbox/default/root/lib64/ld-linux-x86-64.so.2 | grep _dl_audit_symbind_alt
00000000000193f0 g    DF .text	0000000000000159  GLIBC_PRIVATE _dl_audit_symbind_alt
```

The sandbox does indeed help avoid build issues caused by running on mismatched operating systems, and in fact the test programs can be built just fine:

```
$ bazel build //pkg/virt-launcher/virtwrap/cmd-server:go_default_test
INFO: Analyzed target //pkg/virt-launcher/virtwrap/cmd-server:go_default_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //pkg/virt-launcher/virtwrap/cmd-server:go_default_test up-to-date:
  bazel-bin/pkg/virt-launcher/virtwrap/cmd-server/go_default_test_/go_default_test
INFO: Elapsed time: 0.188s, Critical Path: 0.06s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

The problem is when we later try to *run* those test programs:

```
$ bazel run //pkg/virt-launcher/virtwrap/cmd-server:go_default_test
INFO: Analyzed target //pkg/virt-launcher/virtwrap/cmd-server:go_default_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //pkg/virt-launcher/virtwrap/cmd-server:go_default_test up-to-date:
  bazel-bin/pkg/virt-launcher/virtwrap/cmd-server/go_default_test_/go_default_test
INFO: Elapsed time: 0.167s, Critical Path: 0.06s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //pkg/virt-launcher/virtwrap/cmd-server:go_default_test
-----------------------------------------------------------------------------
/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/execroot/kubevirt/bazel-out/k8-fastbuild/bin/pkg/virt-launcher/virtwrap/cmd-server/go_default_test_/go_default_test.runfiles/kubevirt/pkg/virt-launcher/virtwrap/cmd-server/go_default_test_/go_default_test: symbol lookup error: /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/execroot/kubevirt/bazel-out/k8-fastbuild/bin/pkg/virt-launcher/virtwrap/cmd-server/go_default_test_/../../../../../rpm/libvirt-libs_x86_64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
```

If we look at the contents of the execution sandbox, the correct files are there

```
$ objdump -T /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/execroot/kubevirt/bazel-out/k8-fastbuild/bin/pkg/virt-launcher/virtwrap/cmd-server/go_default_test_/../../../../../rpm/libvirt-libs_x86_64/libc.so.6 | grep _dl_audit_symbind_alt
0000000000000000      DF *UND*	0000000000000000  GLIBC_PRIVATE _dl_audit_symbind_alt
$ objdump -T /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/execroot/kubevirt/bazel-out/k8-fastbuild/bin/pkg/virt-launcher/virtwrap/cmd-server/go_default_test_/../../../../../rpm/libvirt-libs_x86_64/ld-linux-x86-64.so.2 | grep _dl_audit_symbind_alt
00000000000193f0 g    DF .text	0000000000000159  GLIBC_PRIVATE _dl_audit_symbind_alt
```

but somehow this version of `ld-linux-x86-64.so.2` is not the one being used when running the test.

Looking at `libc.so.6` in the sandbox

```
$ ldd /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/execroot/kubevirt/bazel-out/k8-fastbuild/bin/pkg/virt-launcher/virtwrap/cmd-server/go_default_test_/../../../../../rpm/libvirt-libs_x86_64/libc.so.6 
	/lib64/ld-linux-x86-64.so.2 (0x00007f69a50fa000)
	linux-vdso.so.1 (0x00007ffc1fda0000)
```

I notice that the path to `ld-linux-x86-64.so.2` is an absolute one. Is there any chance that's what causes the run process to poke outside of the sandbox and use the host OS' version instead? That sounds like it would break sandboxing in a pretty fundamental way, so that's probably not it...

Anyway, I don't really know how to dig much further than this. According to [this article](https://blog.bazel.build/2016/03/18/sandbox-easier-debug.html) it should be possible to pass the `--verbose_failures --sandbox_debug` flags to `bazel run` and get an interactive shell inside the sandbox in case of failure, but that doesn't seem to work. Do you know of any other way to inspect the runtime state of the sandbox?

It also looks like this kind of issues would only hit us when symbols are added to glibc *and* they're implemented in the dynamic loader rather than in glibc proper. Perhaps that's infrequent enough that we don't need to care too much about it, and we can simply refresh the builder image when that happens?

**Comment by rmohr** [comment]
> The problem is when we later try to _run_ those test programs:

Ouch I did not extend the sandbox to the `run` command. When you look at `.bazeldnf/sandbox.bazelrc`:

`$ cat .bazeldnf/sandbox.bazelrc
build --sandbox_add_mount_pair=/home/rmohr/kubevirt/.bazeldnf/sandbox/default/root/usr/:/usr/
build --sandbox_add_mount_pair=/home/rmohr/kubevirt/.bazeldnf/sandbox/default/root/lib64:/lib64
build --sandbox_add_mount_pair=/home/rmohr/kubevirt/.bazeldnf/sandbox/default/root/lib:/lib
build --sandbox_add_mount_pair=/home/rmohr/kubevirt/.bazeldnf/sandbox/default/root/bin:/bin

build --incompatible_enable_cc_toolchain_resolution --platforms=//bazel/platforms:x86_64-none-linux-gnu
```

we only add it to `build` (which is inherited by `test`) but not to `run`.

I think just adding these lines to it (in `hack/bootstraph.sh`):

```
run --sandbox_add_mount_pair=/home/rmohr/kubevirt/.bazeldnf/sandbox/default/root/usr/:/usr/
run --sandbox_add_mount_pair=/home/rmohr/kubevirt/.bazeldnf/sandbox/default/root/lib64:/lib64
run --sandbox_add_mount_pair=/home/rmohr/kubevirt/.bazeldnf/sandbox/default/root/lib:/lib
run --sandbox_add_mount_pair=/home/rmohr/kubevirt/.bazeldnf/sandbox/default/root/bin:/bin
```

probably solves it. I think I have time tomorrow morning to follow up on it.

> It also looks like this kind of issues would only hit us when symbols are added to glibc _and_ they're implemented in the dynamic loader rather than in glibc proper. Perhaps that's infrequent enough that we don't need to care too much about it, and we can simply refresh the builder image when that happens

It indeed happens infrequent enough that we did not discover it until now.


@andreabolognani excellent analysis! :)

**Comment by rmohr** [comment]
> I notice that the path to `ld-linux-x86-64.so.2` is an absolute one. Is there any chance that's what causes the run process to poke outside of the sandbox and use the host OS' version instead? That sounds like it would break sandboxing in a pretty fundamental way, so that's probably not it...

Yes that should be fine. We exlicitly mount our /lib64 sandbox directory into the sandbox, so that it does not use the loader from the underlying system.

**Comment by andreabolognani** [comment]
> I think just adding these lines to it (in `hack/bootstraph.sh`) probably solves it.

@rmohr I tried that yesterday and it didn't help. But perhaps I just did it wrong O:-)

Do you know of a way to convince bazel to spawn an interactive shell inside its sandbox? That would help immensely with understanding what's going on.

> Yes that should be fine. We exlicitly mount our /lib64 sandbox directory into the sandbox, so that it does not use the loader from the underlying system.

While looking at bazel's documentation yesterday I noticed the [`--[no]experimental_use_hermetic_linux_sandbox`](https://bazel.build/reference/command-line-reference#flag--experimental_use_hermetic_linux_sandbox) option. Could that be interesting to us? The version of bazel that we're currently using doesn't seem to support it.

> Also it seems to only happen when we do coverage reporting. On normal unit tests it works perfectly fine.

Is that so? For me, running `//pkg/virt-launcher/virtwrap/cmd-server:go_default_test` (among others) fails and that test doesn't seem to be related to coverage.

**Comment by rmohr** [comment]
> > I think just adding these lines to it (in `hack/bootstraph.sh`) probably solves it.
> 
> @rmohr I tried that yesterday and it didn't help. But perhaps I just did it wrong O:-)
> 
> Do you know of a way to convince bazel to spawn an interactive shell inside its sandbox? That would help immensely with understanding what's going on.
> 
> > Yes that should be fine. We exlicitly mount our /lib64 sandbox directory into the sandbox, so that it does not use the loader from the underlying system.
> 
> While looking at bazel's documentation yesterday I noticed the [`--[no]experimental_use_hermetic_linux_sandbox`](https://bazel.build/reference/command-line-reference#flag--experimental_use_hermetic_linux_sandbox) option. Could that be interesting to us? The version of bazel that we're currently using doesn't seem to support it.
> 
> > Also it seems to only happen when we do coverage reporting. On normal unit tests it works perfectly fine.
> 
> Is that so? For me, running `//pkg/virt-launcher/virtwrap/cmd-server:go_default_test` (among others) fails and that test doesn't seem to be related to coverage.

So the unit tests are running fine. Just when coverage is added we see the issue. Since coverage is compiled different, there seems to ba a "leak" somewhere. This seems to happen so seldom though, that I would say +1 for just updating the builder image.

**Comment by andreabolognani** [comment]
> > > Also it seems to only happen when we do coverage reporting. On normal unit tests it works perfectly fine.
> > 
> > Is that so? For me, running `//pkg/virt-launcher/virtwrap/cmd-server:go_default_test` (among others) fails and that test doesn't seem to be related to coverage.
> 
> So the unit tests are running fine. Just when coverage is added we see the issue. Since coverage is compiled different, there seems to ba a "leak" somewhere.

@rmohr is the specific test I mention above related to coverage? Or is coverage enabled in some way that gets triggered by running it? If so, is there a way to disable coverage and see the difference - that is, the failure going away?

I'm very unclear on the topic and just trying to figure out how the pieces fit together :)

> This seems to happen so seldom though, that I would say +1 for just updating the builder image.

I still haven't found a way to poke at the contents of a running bazel sandbox in a useful way, so unfortunately I haven't been able to make much progress towards a definitive solution.

In the meantime, updating the image sounds like the sensible thing to do, at least in the short term, to return things to a sane place. Can you take care of that? Or tag someone who has the necessary privileges to publish a fresh builder image?

**Comment by rmohr** [comment]
> I still haven't found a way to poke at the contents of a running bazel sandbox in a useful way, so unfortunately I haven't been able to make much progress towards a definitive solution.

Yes, I think there is a slightly different command needed. Can't find the reference right now though.



> In the meantime, updating the image sounds like the sensible thing to do, at least in the short term, to return things to a sane place. Can you take care of that? Or tag someone who has the necessary privileges to publish a fresh builder image?

Yes will work on that. Thanks for taking the investigation time!

**Comment by sbrivio-rh** [comment]
@andreabolognani
> Note that the version of passt is bumped from 0:0.git.2022_08_04.b516d15-0.el8 to 0:0.git.2022_08_29.60ffc5b-1.el8 in the process: this was necessary because the former is now gone from the COPR repo.

Sorry for the mess. While passt is making its way into CentOS Stream 9, I'm now maintaining a [fully archived mirror](https://passt.top/builds/copr/) of the Copr repository.

**Comment by sbrivio-rh** [comment]
> @andreabolognani
> 
> > Note that the version of passt is bumped from 0:0.git.2022_08_04.b516d15-0.el8 to 0:0.git.2022_08_29.60ffc5b-1.el8 in the process: this was necessary because the former is now gone from the COPR repo.
> 
> Sorry for the mess. While passt is making its way into CentOS Stream 9, I'm now maintaining a [fully archived mirror](https://passt.top/builds/copr/) of the Copr repository.

Given that only the latest mirrored version would be available for dnf to install (due to how `repomd.xml` is built), I'm now mirroring:
- the latest version available on Copr at https://passt.top/builds/copr/
- previous versions at https://passt.top/builds/copr/ `<version>`. For example, the **repository** at https://passt.top/builds/copr/0^20221024.gc11277b/ will always make `0^20221024.gc11277b` available (and only that).

**Comment by andreabolognani** [comment]
> Given that only the latest mirrored version would be available for dnf to install (due to how `repomd.xml` is built), I'm now mirroring:
> 
> * the latest version available on Copr at https://passt.top/builds/copr/
> * previous versions at https://passt.top/builds/copr/ `<version>`. For example, the **repository** at [https://passt.top/builds/copr/0^20221024.gc11277b/](https://passt.top/builds/copr/0%5E20221024.gc11277b/) will always make `0^20221024.gc11277b` available (and only that).

Neat!

Would it make sense to have the latest version available at https://passt.top/builds/copr/latest instead? That would make things easier to scan, as the per-version repos would no longer get lost among the names of the various buildroots.

**Comment by sbrivio-rh** [comment]
@andreabolognani 

> Would it make sense to have the latest version available at https://passt.top/builds/copr/latest instead? That would make things easier to scan, as the per-version repos would no longer get lost among the names of the various buildroots.

Sure, makes sense, done, let me know if it works for you!

**Comment by sbrivio-rh** [comment]
@andreabolognani 
> One note. It looks like you're mirroring more data than necessary? For the `0^20221024.gc11277b` build, the RPMs are in `centos-stream-9-x86_64/04986981-passt`, but under `centos-stream-9-x86_64` there are a bunch of directories for older builds too... I think you could clean that up and save a bunch of disk space.

I'm keeping those for simplicity of my mirroring script, Copr deletes old builds after 14 days (!) anyway, it's not going to be much.

**Comment by andreabolognani** [comment]
Fair enough :)

**Pull request merged**
