### PR TITLE
Remove ignition experimental support

### PR DESCRIPTION
**Pull request by karmab**
Signed-off-by: karmab <karimboumedhel@gmail.com>

**What this PR does / why we need it**:

Remove Ignition experimental support since using a config drive is a better solution to provide this feature

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by cwilkers** [comment]
Documentation will also need removing/updating (per Quentin Michaud in Slack):
- https://kubevirt.io/2018/ignition-support.html
- https://kubevirt.io/user-guide/virtual_machines/startup_scripts/

For the latter, a section could be added demonstrating use of a config drive to inject an ignition config.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
> Documentation will also need removing/updating (per Quentin Michaud in Slack):

The link to the corresponding Slack conversation is [here](https://kubernetes.slack.com/archives/C8ED7RKFE/p1676037126758499) for future references.

>     * https://kubevirt.io/2018/ignition-support.html

Once the usage of ignition file with config drive have been correctly explained in the docs, [the blog post](https://github.com/kubevirt/kubevirt.github.io/blob/main/_posts/2018-11-20-ignition-support.markdown) can be simply removed imo. I'll try to use ignition with the config drive as discussed and I may be able to help with the documentation then.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
To clarify the removal of the ignition experimental support, only the experimental support through the `kubevirt.io/ignitiondata` annotation and the corresponding featureGate is to be removed. Ignition will continue to be supported by using a config drive, although this is not yet explained in the docs at all. 

As it can be difficult to know how to make ignition work with this config, I propose the minimal working example I was able to produce (only replace the SSH key) : 

vm.yaml : 

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ign-demo
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: ign-demo

    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 4G
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/rhcos:4.9
        - name: cloudinitdisk
          cloudInitConfigDrive:
            userData: |
              {
                "ignition": {
                  "config": {},
                  "proxy": {},
                  "security": {},
                  "timeouts": {},
                  "version": "3.2.0"
                },
                "passwd": {
                  "users": [
                    {
                      "name": "coreos",
                      "sshAuthorizedKeys": [
                        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPL3axFGHI3db9iJWkPXVbYzD7OaWTtHuqmxLvj+DztB root@kubevirt-demo"
                      ]
                    }
                  ]
                },
                "storage": {},
                "systemd": {}
              }
```

This example is heavily inspired by the content of [this issue](https://github.com/kubevirt/kubevirt/issues/7310).

**Comment by cwilkers** [comment]
/remove-lifecycle stale

@xpivarc I agree that a deprecation phase would be best to start with. I'll look into creating a PR for that.
Reference on deprecation: https://github.com/kubevirt/kubevirt/blob/main/docs/deprecation.md

@mh4ckt3mh4ckt1c4s Documentation would be great, kubevirt/user-guide would be the place if you would like to add your example.

**Comment by cwilkers** [comment]
@davidvossel Just checking, this wouldn't happen to be a feature you're making use of?

**Comment by mh4ck-Thales** [comment]
@cwilkers my PR documenting Ignition and containing a similar example than the one I posted here is already ready on the user-guide repo : https://github.com/kubevirt/user-guide/pull/669

**Pull request closed without merging**
