### PR TITLE
Vendor CDI 1.7.0

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Update CDI version to 1.7.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
@awels could you run `make generate`?

**Comment by awels** [comment]
@rmohr Done, did you know that make deps-update no longer works, it keeps failing on some package deep in the bowels of something vendored in.

**Comment by rmohr** [comment]
@awels, no did not know. That can sadly always happen with `deps-update`. In your case, changine `glide.yaml` and running `deps-install` should be sufficient.

**Comment by awels** [comment]
Yeah, that is what I eventually did, I thought make deps-update also runs make generate and I simply forgot that step when I did make deps-install.

**Comment by igoihman** [comment]
ci test please

**Comment by rmohr** [comment]
Hm, travis still thinks that `make generate && make` should be run.

**Comment by awels** [comment]
That is weird, I just re-ran make generate and make, and there we no changes at all. I rebased, lets see if it passes now.

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by rmohr** [comment]
> That is weird, I just re-ran make generate and make, and there we no changes at all. I rebased, lets see if it passes now.

That can be. Thanks @cynepco3hahue  for pushing. A rebase should have solved it. We updated goimports and changed how goimports is invoked a few days ago.

**Comment by cynepco3hahue** [comment]
Failures under the CI unrelated, lgtm.

**Pull request merged**
