### PR TITLE
add virtctl list

### PR DESCRIPTION
**Pull request by karmab**
**What this PR does / why we need it**:
This PR adds a basic list word to virtctl command so that vms get reported with their status, source image and ip when available

```
Name    |Status  |IP          |Source
----    |------  |--          |------
testvm  |Running |10.244.0.41 |kubevirt/cirros-registry-disk-demo
testvm2 |down    |            |kubevirt/fedora-registry-disk-demo
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by SchSeba** [comment]
@karmab Can we achieve it with something like https://github.com/kubevirt/kubevirt/issues/1064

**Comment by karmab** [comment]
the thing is that we cross some data, the ip for instance is gather from the vmi object, not the vm

**Comment by karmab** [comment]
after playing a bit with the additional printer columns feature, i agree it's enough to add relevant fields in the vm/vmi crds

**Comment by fabiand** [comment]
Cool!

I wondered if now everything is ready on the k8s side.

Will you prepare a patch with what needs to be changed on the CRDs?

**Comment by karmab** [comment]
> Cool! I wondered if now everything is ready on the k8s side. Will you prepare a patch with what needs to be changed on the CRDs?

opened https://github.com/kubevirt/kubevirt/pull/1654

**Comment by fabiand** [comment]
Awesome!

**Pull request closed without merging**
