### PR TITLE
[release-1.2] Wait until backend storage PVC is ready before starting VMIs

### PR DESCRIPTION
**Pull request by jean-edouard**
Manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/11373

```release-note
NONE
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
@jean-edouard I think this backport should be adjusted since https://github.com/kubevirt/kubevirt/pull/11800 was merged. The vmiInterface expects 2 parameters here while now it should get 3 (`UpdateOptions`).
```
vmiInterface.EXPECT().Update(context.Background(), gomock.Any())
```

Can you please rebase this? Thank you

**Comment by jean-edouard** [comment]
Ah, thanks, will do.
/test pull-kubevirt-unit-test

**Pull request merged**
