### PR TITLE
lint: Add ginkgolinter & pre-commit config

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

Enable the now available ginkgolinter after the recent version bump of
golangci-lint for use by the lint Makefile target.

Additionally, introduce pre-commit, a useful framework that uses local
git hook scripts to ensure changes meet certain requirements *before*
they are fully committed.

The tool is opt-in and requires the user install pre-commit itself but
this is as easy as:

```sh
$ pip install --user pre-commit && pre-commit install
```

The provided config uses a number of standard hooks and additionally
runs the lint Makefile target.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
@lyarwood hi. 

ginkgolinter already enabled, but it run as part of nogo

I don't care to use golangci-lint to run it, but:
1. I think others will have different opinion about it (@rmohr)
2. ginkgolinter was written originally for KubeVirt. When using golangci-lint, we are depending on their release cycle. Personally, I love to keep KubeVirt the alpha user of the ginkgolinter, and to be able to upgrade its version each time it released.

**Comment by lyarwood** [comment]
> @lyarwood hi.

Hey

> ginkgolinter already enabled, but it run as part of nogo

Yup just wanted some coverage in the `lint` `Makefile` target outside of bazel and build time, ultimately I'd like to provide an opt-in `pre-commit` config in KubeVirt to run this target locally with each commit.

> I don't care to use golangci-lint to run it, but:
> 
> 1. I think others will have different opinion about it (@rmohr ?)
>
> 2. ginkgolinter was written originally for KubeVirt. When using golangci-lint, we are depending on their release cycle. Personally, I would love to keep KubeVirt the alpha user of the ginkgolinter, and to be able to upgrade its version each time it is released.

I'm not suggesting that we drop the original `nogo` use of `ginkgolinter` so that shouldn't change?

**Comment by nunnatsa** [comment]
:+1:  for the pre-commit

Sound good. Just be aware that we could have a gap of versions here.

**Comment by rmohr** [comment]
> Yup just wanted some coverage in the `lint` `Makefile` target outside of bazel and build time, ultimately I'd like to provide an opt-in `pre-commit` config in KubeVirt to run this target locally with each commit.
> 
> >

wouldn't you run at least `make&& make build-functest` as well in such a pre-commit which would run all nogo linters, including the ginkgo linter?

**Comment by lyarwood** [comment]
> > Yup just wanted some coverage in the `lint` `Makefile` target outside of bazel and build time, ultimately I'd like to provide an opt-in `pre-commit` config in KubeVirt to run this target locally with each commit.
> > >
> 
> wouldn't you run at least `make && make build-functest && make test` as well in such a pre-commit which would run all nogo linters, including the ginkgo linter? In principle the idea is that when you run these commands, that you should not have any reason to be forced to fix minor things like formatting or linting issues to make required CI green. `make generate` is in practice needed too, but it takes pretty long and is very often not needed.

I'd argue that you wouldn't run these commands with every single commit or amend no, so some simple lightweight tooling to catch any accidental mistakes (even `F{Context,It} etc) is still worthwhile IMHO.

> I have no special opinion on this PR.

No issues, `pre-commit` would be opt-in anyway so hopefully not breaking existing workflows for folks that don't want to run `lint` with each commit/amend.

**Comment by rmohr** [comment]
> I'd argue that you wouldn't run these commands with every single commit or amend no, so some simple lightweight tooling to catch any accidental mistakes (even `F{Context,It}` etc) is still worthwhile IMHO.

Hm, especially if you are on the same branch and do a series of commits, I would argue exactly the opposite, since bazel is caching it all (it only rebuilds and re-tests what you changed between the commits). But fine for me if you want to do this.

**Review by EdDev — APPROVED** [review]

**Comment by lyarwood** [comment]
/hold

As documented in https://github.com/kubevirt/kubevirt/pull/10136#issuecomment-1647511715 I'm going to wait for a new release of `golangci-lint` before I introduce a full standalone run of the tool using only `ginkgolinter` with the new `forbid-focus-container` flag enabled in the `lint` `Makefile` target.

**Pull request closed without merging**
