### PR TITLE
Update libvirt image to 5.4.0

### PR DESCRIPTION
**Pull request by SchSeba**
related to https://github.com/kubevirt/libvirt/pull/26

This PR is needed because we can't rebuild the image.
libvirt 5.0.0 packages are not longer exist under the virt repo.
Also the qemu pakcage that works with 5.0.0 don't exist any more.

This PR also installed the nftable package needed for ocp 4

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Part of the solution for https://github.com/kubevirt/kubevirt/issues/2400

**Special notes for your reviewer**:

**Release note**:

```release-note
update libvirt base image to 5.4.0
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/2428)

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@SchSeba You also need to update:
- `libvirt_libs` and `libvirt_devel` targets under workspace
- `libvirt-shared-libs` target under the root BUILD file
- libvirt client-go version

**Comment by SchSeba** [comment]
@cynepco3hahue Thanks for the help can you please take another look?

**Comment by cynepco3hahue** [comment]
I see one test that fails under all lanes
```
Configurations [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]VirtualMachineInstance definition with EFI bootloader method [test_id:1668]should use EFI
```
Can you please check it locally?

**Comment by cynepco3hahue** [comment]
Except for this one lgtm
@rmohr @fabiand Does it ok to advance upstream version of the libvirt? Because virt-preview repository does not have any more version 5.1 I think we do not have any choice :smiley:

**Comment by rmohr** [comment]
Updating works for me.

**Comment by rmohr** [comment]
We need to start working on the automatic mirroring of our dependencies in GCE.

**Comment by cynepco3hahue** [comment]
> We need to start working on the automatic mirroring of our dependencies in GCE.

@rmohr Do you have ideas about how can it be done?

**Comment by rmohr** [comment]
@cynepco3hahue something like a postsubmit job which detects that new items were added to the WORKSPACE file. It then uploads the source, modified WORKSPACE by adding the mirror too and do a PR or push to the branch.

**Comment by rmohr** [comment]
@cynepco3hahue we may also do it on the PR directly.

**Comment by SchSeba** [comment]
@cynepco3hahue I will check the EFI

/hold

**Comment by SchSeba** [comment]
the test pass locally without any issue

```
------------------------------
• [SLOW TEST:40.005 seconds]
Configurations
/home/sscheink/Documents/GolangProjects/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:49
  [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]VirtualMachineInstance definition
  /home/sscheink/Documents/GolangProjects/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:139
    with EFI bootloader method
    /home/sscheink/Documents/GolangProjects/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:401
      [test_id:1668]should use EFI
      /home/sscheink/Documents/GolangProjects/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:403
```

I also try to run all the configuration lane and it's also pass
```
Ran 50 of 404 Specs in 1401.456 seconds
SUCCESS! -- 50 Passed | 0 Failed | 0 Pending | 354 Skipped
PASS | FOCUSED
```

**Comment by SchSeba** [comment]
No needed any more
https://github.com/kubevirt/kubevirt/pull/2487

**Pull request closed without merging**
