### PR TITLE
fix some type on doc

### PR DESCRIPTION
**Pull request by tgfree7**
try to fix some typo on doc
Signed-off-by: tgfree <tgfree7@gmail.com>
```release-note
NONE
```

### CODE REVIEW

**Comment by tgfree7** [comment]
> 
/retest-required

**Comment by tgfree7** [comment]
> retest-required
/retest-required

**Comment by tgfree7** [comment]
> @tgfree7: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kubevirt-e2e-k8s-1.23-sig-storage-nonroot	[4a1c0ea](https://github.com/kubevirt/kubevirt/commit/4a1c0ea0cd3f88b02607844c259699356e4b9d27)	[link](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7947/pull-kubevirt-e2e-k8s-1.23-sig-storage-nonroot/1539027957035569152)	true	`/test pull-kubevirt-e2e-k8s-1.23-sig-storage-nonroot`

/retest-required

**Comment by stu-gott** [comment]
/approve

Thanks @tgfree7!

**Comment by tgfree7** [comment]
> /test pull-kubevirt-e2e-k8s-1.23-sig-storage

/retest-required

**Pull request merged**
