### PR TITLE
Improve event logging granularity

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

In order to make it easier to track down issues when we see unwanted
events in our tests, better log which entity was responsible for
triggering the event and not just log the event message itself.

```release-note
NONE
```

### CODE REVIEW

**Comment by davidvossel** [comment]
is it expected that all of these "check-patch" tests fail?

**Comment by rmohr** [comment]
retest this please

**Comment by stu-gott** [comment]
retest this please

**Comment by cynepco3hahue** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by stu-gott** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Pull request merged**
