### PR TITLE
Rename and document Istio's annotations

### PR DESCRIPTION
**Pull request by orelmisan**
### What this PR does
Before this PR:
[Istio](https://istio.io/)'s annotations were written in snake case and had a redundant prefix.

After this PR:
The annotations are aligned with Go's coding conventions [1] and are better documented. 

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 
https://github.com/kubevirt/kubevirt/pull/12480#discussion_r1703831515

### Special notes for your reviewer
According to istio's documentation, the usage of the `sidecar.istio.io/inject` annotation is deprecated [2].
A follow-up PR will adjust the relevant logic.

[1] https://go.dev/doc/effective_go#mixed-caps
[2] https://istio.io/latest/docs/reference/config/annotations/#SidecarInject

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [X] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [X] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Review by EdDev — APPROVED** [review]
Thanks.

Repeating the same reason on similar constants at the same place does not merit two commits IMO. It is an extreme and may annoy reviewers.
But at the same time it does not worth debating over.

The approve requires raising.
/approve

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/7d4b6585eb72de80b7a9726641ae244f69f9c0c1..a51065db054baf0448acf77dd2cc0f48e3d9031a): Squashed the two commits.

**Review by EdDev — APPROVED** [review]

**Comment by xpivarc** [comment]
> Thanks.
> 
> Repeating the same reason on similar constants at the same place does not merit two commits IMO. It is an extreme and may annoy reviewers. But at the same time it does not worth debating over.
> 
> The approve requires raising. /approve

/approve

**Review by ormergi — APPROVED** [review]

**Pull request merged**
