### PR TITLE
Fix access to portforwarding on VMs/VMIs with the cluster roles kubevirt.io:[admin|edit]

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

The API endpoint of subresources.kubevirt.io virtualmachineinstances/portforward
is defined with the GET method/verb but the default RBAC incorrectly only allowed
the PUT method / update verb on this endpoint to the kubevirt.io:[admin|edit] roles.

Since the roles kubevirt.io:[admin|edit] are allowed the GET method/verb
on the VMI/portforward endpoint allow it on the VM endpoint too for
consistency.

**Release note**:

```release-note
Fix access to portforwarding on VMs/VMIs with the cluster roles kubevirt.io:admin and kubevirt.io:edit
```

### CODE REVIEW

**Comment by dhiller** [comment]
/uncc @kbidarkar @maiqueb 
/cc @enp0s3 @acardace 

/approve
/hold

Looks good to me, maybe @enp0s3 @acardace could take a final look?

**Review by xpivarc — APPROVED** [review]

**Review by enp0s3 — APPROVED** [review]
/unhold

**Pull request merged**
