### PR TITLE
Add log messages to hotplug mount phase and improve test

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
This PR is trying to improve debugging experience based on my recent debugging. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by enp0s3 — APPROVED** [review]
/lgtm

**Comment by iholder-redhat** [comment]
@xpivarc do we still need this?

**Pull request closed without merging**
