### PR TITLE
Use latest libvirt-go

### PR DESCRIPTION
**Pull request by cynepco3hahue**
**What this PR does / why we need it**:
The last build includes the fix for "missing error" problem.
It affects our CI runs and in general can affect user flows.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by davidvossel** [comment]
@berrange To pick up the latest changes in libvirt-go, we're pulling in the tip of master. What are your thoughts here? Should that be okay or should we wait for the next libvirt-go release?

**Comment by berrange** [comment]
We would generally recommend to track one of the signed tags, since we can't promise that git master is always going to successfully build.

Certainly any formal releases should be tracking a signed tag. It could be acceptable to track git master for your own daily CI, as long as you're happy with risk of occasional breakage.  We release monthly though, so it isn't very long to wait for changes to get into a signed tag.

**Comment by cynepco3hahue** [comment]
@davidvossel I can change it to tagged release once it available.

**Comment by rmohr** [comment]
Ok, let's take this one in right now and switch to a tagged release once it is there. Results look much better.

**Comment by rmohr** [comment]
> We would generally recommend to track one of the signed tags, since we can't promise that git master is always going to successfully build.

Yes makes sense in general. We are taking the current specific HEAD commit until the tagged release is there.

**Pull request merged**
