### PR TITLE
tests: replace retry with patch

### PR DESCRIPTION
**Pull request by codingben**
Replace RetryWithMetadataIfModified() with Patch
to set VM run strategy instead of using Update.

### Release note

```release-note
None
```

### CODE REVIEW

**Review by RamLavi — APPROVED** [review]
/lgtm

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by codingben** [comment]
@dhiller @brianmcarey Hi, why it's not merging it? `tide` says `Pending — Not mergeable. Retesting: pull-kubevirt-e2e-k8s-1.29-sig-storage` but it's already passed.

**Comment by brianmcarey** [comment]
> @dhiller @brianmcarey Hi, why it's not merging it? `tide` says `Pending — Not mergeable. Retesting: pull-kubevirt-e2e-k8s-1.29-sig-storage` but it's already passed.

Its part of an active batch that is still running - https://prow.ci.kubevirt.io/?type=batch

**Pull request merged**
