### PR TITLE
docs: Remove virt-handler wrong documentation

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
This documentation is unused and quite outdated.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubevirt/kubevirt/issues/9561

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
/cc @alicefr @EdDev

### CODE REVIEW

**Review by EdDev — COMMENTED** [review]
Thanks!
Please reason for the removal also in the commit message.

**Comment by alicefr** [comment]
/hold 
for adressing Ed's comment: https://github.com/kubevirt/kubevirt/pull/9852#pullrequestreview-1461918267

**Comment by fossedihelm** [comment]
> Thanks! Please reason for the removal also in the commit message.

Thanks! Done! @EdDev

**Review by EdDev — APPROVED** [review]
Thanks!

**Pull request merged**
