### PR TITLE
rpm: Add qemu-kvm-device-usb-redirect on aarch64

### LINKED ISSUE #10208: Arm64 -- qemu-kvm-device-usb-redirect package is missing on Arm64 platform
**What happened**:
As there is no rpm package `qemu-kvm-device-usb-redirect` in https://mirror.stream.centos.org/9-stream/AppStream/aarch64/os/Packages/, clientPassthrough does not works on Arm64 platform.
https://github.com/kubevirt/kubevirt/issues/10200

**What you expected to happen**:
clientPassthrough works on Arm64 platform

**Additional context**:
Shall we request to add `qemu-kvm-device-usb-redirect` in https://mirror.stream.centos.org/9-stream/AppStream/aarch64/os/Packages/?

### PR DESCRIPTION
**Pull request by andreabolognani**
###  What this PR does

Add the `usb-redirect` device to QEMU on aarch64, following in the footsteps of x86_64.

Fixes #10208

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by zhlhahaha** [comment]
/lgtm
Thanks @andreabolognani !

**Comment by victortoso** [comment]
Weird unit-test failure, seems unrelated?
Happy to see usbredir on arm too, thanks!

**Comment by andreabolognani** [comment]
@zhlhahaha the `pull-kubevirt-unit-test-arm64` failure is quite surprising. Can you please look into it?

**Comment by zhlhahaha** [comment]
> @zhlhahaha the `pull-kubevirt-unit-test-arm64` failure is quite surprising. Can you please look into it?

Sorry, I just the your comments. I saw the patch has merged. I just did a unit tests on my local arm64 server with the latest kubevirt code. All tests have passed.

**Comment by andreabolognani** [comment]
All good then :)

**Pull request merged**
