### PR TITLE
Entirely remove our custom SELinux policy

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
As of container-selinux v2.193.0, our custom SELinux policy is not needed anymore.
Removing it will drastically improve our security posture, giving virt-launcher the same SELinux permissions as any other unprivileged container.
It also brings the added benefit of cleaning up the codebase and reducing virt-handler start time by about 20 seconds.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
The test lanes that do not include container-selinux v2.193.0 or newer will fail.
This is fixed by https://github.com/kubevirt/kubevirtci/pull/946

**Release note**:

```release-note
We do not install a custom SELinux policy anymore, see docs to ensure your SELinux-enabled nodes use a recent-enough version of container-selinux.
```

### CODE REVIEW

**Comment by stu-gott** [comment]
@xpivarc When placing a hold please explain why it's a necessary action. It's not clear what the path forward is otherwise.

**Comment by xpivarc** [comment]
> @xpivarc When placing a hold please explain why it's a necessary action. It's not clear what the path forward is otherwise.

@stu-gott 
Apologize, we discussed this offline. I had put the hold because there is a dependency that would need to merge first. Therefore I did not want CI or people to look at this. Additionally, I think https://github.com/kubevirt/kubevirt/pull/9048 is a better approach as the dependency in question is quite a big hack and it is hard for me to believe the production system would have it.

**Comment by jean-edouard** [comment]
/close
I'll be back

**Pull request closed without merging**
