### PR TITLE
[wip] [experiment] [do not merge] Collect domain XMLs of tests

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Collecting domain XMLs from our different test lanes to show what we use from domain XMLs and how we use it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by slintes** [comment]
is this replaced by https://github.com/kubevirt/kubevirt/pull/2579 ?

**Comment by rmohr** [comment]
No. Please don't merge this one. This is meant to dump all domain XML of passing tests to gcs. We had some people which are interested in our domain xmls. This gives them xmls with pretty much all features which we have.

**Comment by slintes** [comment]
ack, thx for clarification

**Comment by rmohr** [comment]
/close

not needed right now. Can be reopened if needed.

**Pull request closed without merging**
