### PR TITLE
Fix credential tests: Create secrets in VMI's namespace

### PR DESCRIPTION
**Pull request by xpivarc**
### What this PR does
Fixes a failing compute root lane. https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.29-sig-compute-root/1760142493132787712

Fixes #

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by brianmcarey — COMMENTED** [review]
Looks good to me - can you just mention in the description that this issue was caught in the rootful compute lanes?

**Comment by dhiller** [comment]
Hm, I see that [sig-storage-root is also failing on one test still](https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.29-sig-storage-root). Not sure how the status of that was again, @akalenyu do you remember?

**Review by dhiller — APPROVED** [review]
/approve

Changes look good to me, [have triggered the root lane](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11326/pull-kubevirt-e2e-k8s-1.29-sig-compute-root/1760346539328278528), let's see how it goes.

/hold just for it not to be retriggered until we are sure we are good.

**Comment by akalenyu** [comment]
> Hm, I see that [sig-storage-root is also failing on one test still](https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.29-sig-storage-root). Not sure how the status of that was again, @akalenyu do you remember?

I thought you figured it out in https://issues.redhat.com/browse/CNV-35418?focusedId=23593088&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23593088
But anyway I think @jcanocan or @germag may be able to help here

**Comment by dhiller** [comment]
/unhold

Results from root compute lane are good. Thanks @xpivarc !

**Pull request merged**
