### PR TITLE
api: Add preference enum validation

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype

### What this PR does

This change adds API validation for the enums allowed by a preference for `PreferredCPUTopology` and `SpreadAcross` options. 

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by alaypatel07** [comment]
hi, is there any other change left on the PR? as it is now the PR looks good from api-point of view

**Comment by lyarwood** [comment]
> hi, is there any other change left on the PR? as it is now the PR looks good from api-point of view

Thanks @alaypatel07 I just had to rebase and update the PR, feel free to review now.

**Comment by alaypatel07** [comment]
There was a discussion in sig-api call, just wanted to make sure @lyarwood we are all on the same page. The upgrade flow after this change will be as follows:

1.  kubevirt upgraded
2. new CRDs with kube-builder validations along with old webhook are currently validating CR creations
3. upgrade goes through to the last stage, virt-api is upgraded, new webhook will be installed
4. at this point the validation is only available in the CRD not in webhook.

If the above flow is correct, there will never be a point in time where a CR is created without validation.

With this workflow, this PR looks good from api point of view

/lgtm

**Pull request closed without merging**
