### PR TITLE
Manual bump kubevirtci with CDI 1.57

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
Needs manual bump since fixes are needed

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by enp0s3** [comment]
@akalenyu @mhenriks Hi! I see that you had to change the tests due to the bump, does it mean you won't be backward-compatible since the new CDI version in terms of the places you've changed in the tests?

**Comment by akalenyu** [comment]
> @akalenyu @mhenriks Hi! I see that you had to change the tests due to the bump, does it mean you won't be backward-compatible since the new CDI version in terms of the places you've changed in the tests?
> 
> I think that if the behavior was changed in a non backward-compatible manner it deserves a release note at least.

I would classify these as strictly test issues;
No flows should be relying on CloneRequest/CloneOf annotations (internal to CDI)
And users can keep waiting for Bound on target PVC as they wish

**Pull request merged**
