### PR TITLE
chore: Drop the OpenShift specific access tests

### LINKED ISSUE #10522: Remove of OpenShift specific tests in access_test.go
**Is your feature request related to a problem? Please describe**:
The OpenShift specific access test in `tests/access_test.go` are incomplete and do not run anymore. Therefore I suggest to remove the entirely.

See:

https://github.com/kubevirt/kubevirt/blob/353020eff99ee15b71f2d3761522e862a96ad147/tests/access_test.go#L446

**Describe the solution you'd like**:
Remove all OpenShift specific acces tests in `tests/access_test.go`.

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

The OpenShift specific access tests do not run in any e2e lane and are not required anymore, therefore drop them.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10522

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by brianmcarey — COMMENTED** [review]
/lgtm 

thanks for this @0xFelix - good to clean unused tests.

**Comment by dominikholler** [comment]
@xpivarc is this PR related to https://issues.redhat.com/browse/CNV-31333 ?

**Pull request merged**
