### PR TITLE
k8s: Bump k8s libraries to v0.30.0

### PR DESCRIPTION
**Pull request by fossedihelm**
### What this PR does
This PR bumps k8s vendor to v0.30.0 on go.mod files.
It also performs needed changes in order to comply with the new vendor libraries.

Note: This PR follows the [update-k8s-dependencies.](https://github.com/kubevirt/kubevirt/blob/main/docs/update-k8s-dependencies.md) manual.

This PR takes commit from https://github.com/kubevirt/kubevirt/pull/11840, rebase it into `main` and addresses 
https://github.com/kubevirt/kubevirt/pull/11840#discussion_r1632770138

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Bump k8s deps to 0.30.0
```

/cc @xpivarc @acardace
@RamLavi FYI

### CODE REVIEW

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by dhiller** [comment]
@machadovilaca @sradco there seems to be flakiness present in the sig-monitoring tests, as made visible by the check-test-for-flakes lane. I figure there probably is an order dependence present, so I'd suggest to run them in random order.

* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12097/pull-kubevirt-check-tests-for-flakes/1800563558417698816
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12097/pull-kubevirt-check-tests-for-flakes/1800595489813434368
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12097/pull-kubevirt-check-tests-for-flakes/1800618454152122368


Would you mind taking a look?

**Comment by dhiller** [comment]
^^ The above can also be seen on aonther PR: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12044/pull-kubevirt-check-tests-for-flakes/1800618717697019904

**Pull request merged**
