### PR TITLE
Fix audit logs

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
Fix audit log path and as consequence, we now have audit logs again :)

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```
/cc @rmohr @fgimenez

### CODE REVIEW

**Review by fgimenez — APPROVED** [review]
/approve

Awesome, thx!

**Review by enp0s3 — APPROVED** [review]
Thank you!

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
