### PR TITLE
Run proxies using arbitratry userid

### PR DESCRIPTION
**Pull request by admiyo**
For explanation see:
https://docs.openshift.org/latest/creating_images/guidelines.html
Under "Support Arbitrary User IDs"

### CODE REVIEW

**Comment by davidvossel** [comment]
I'm curious how you encountered this.  Do these containers fail to start without this change in openshift?

**Comment by fabiand** [comment]
Also - Could we use the `runAsUser` field of the `PodSecurityContext` (https://kubernetes.io/docs/api-reference/v1.6/#podsecuritycontext-v1-core) - or `SecurityContext` for `Container`.

**Comment by admiyo** [comment]
Please read the link in the commit request for the rationale.

**Comment by admiyo** [comment]
Without these changes, the containers fail with permissions errors when deploying on origin.

**Comment by fabiand** [comment]
Right, lgtm.

**Pull request merged**
