### PR TITLE
[release-0.42] migration: generate empty isos on target for cloud-inits, configmaps, secrets, ...

### PR DESCRIPTION
**Pull request by jean-edouard**
This is a manual (squash and) cherry-pick of https://github.com/kubevirt/kubevirt/pull/6482 and https://github.com/kubevirt/kubevirt/pull/6519

**Release note**:

```release-note
VMs with cloud-init data should now properly migrate from older KubeVirt versions
```

### CODE REVIEW

**Comment by rmohr** [comment]
@ormergi @oshoval can it be that something is not up-to-date in the sriov job configs for `release-0.42`? I did an override because the pod on this branch is not schedulable (anymore?).

**Comment by ormergi** [comment]
@rmohr We upgraded the SRIOV provider since then and changes the bootstrap image
also changed it to be scheduled on the new CI cluster

**Comment by oshoval** [comment]
> @rmohr We upgraded the SRIOV provider since then, I see we use different bootstrap image also Also we changed SRIOV jobs to be scheduled on the new CI cluster

Right but the branch still have the old provider, maybe its one of the other delicate changes, maybe worth to ask Federico, or align all the fields that make sense one by one

**Pull request merged**
