### PR TITLE
tests: don't use hardcoded kubevirt namespace

### PR DESCRIPTION
**Pull request by dollierp**
**What this PR does / why we need it**:

Some tests use hardcoded "kubevirt" namespace when looking for KubeVirt resources.

As a result, those tests fail to run an a cluster installed using [hyperconverged-cluster-operator](https://github.com/kubevirt/hyperconverged-cluster-operator) which create kubevirt resources in "kubevirt-hyperconverged" namespace.

This PR improve failing tests to make them use the value of the argument ``--installed-namespace`` instead of hardcoded "kubevirt".

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabiand** [comment]
These are needed to run the tests in non-standard namespaces.

**Comment by rmohr** [comment]
ci test please

**Comment by dollierp** [comment]
Updated with `make generate` results.

**Pull request merged**
