### PR TITLE
virt-handler: Remove dep on pkg/network/setup

### PR DESCRIPTION
**Pull request by orelmisan**
### What this PR does
Currently, `NewController()` instantiates the concrete implementations of `netConf` and `netStat`.

Take `netConf` and `netStat` as parameters to `NewController()` in order to make the VMController independent of
`kubevirt.io/kubevirt/pkg/network/setup`.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 
https://github.com/kubevirt/kubevirt/pull/12326#discussion_r1677118016

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [X] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/a8f012912720025cf570ca31d4e92ccb4c9992cf..48cdde2357c382632a4ed9a0b569d50ca73214ca): Rebase

**Review by EdDev — APPROVED** [review]
Thanks.

I cannot approve here, so I’ll just lgtm.

**Comment by orelmisan** [comment]
@xpivarc Could you please have a look?

**Pull request merged**
