### PR TITLE
container-disk, test: replace `Expect(len(..).To(Equal(..))` with `Expect(..).To(HaveLen(..))`

### PR DESCRIPTION
**Pull request by acardace**
**What this PR does / why we need it**:

Replace occurrences of `Expect(len($VAR)).To(Equal($X))` with
`Expect($VAR).To(HaveLen($X)` which is more gomega-idiomatic and gives
better error messages when the expectation fails.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by xpivarc — APPROVED** [review]

**Review by EdDev — COMMENTED** [review]
Could you please try to limit the subject to 50 chars? I sometime pass this number if I have no choice, but never pass 72 chars.
Ref: https://cbea.ms/git-commit/#limit-50

**Comment by acardace** [comment]
> Could you please try to limit the subject to 50 chars? I sometime pass this number if I have no choice, but never pass 72 chars. Ref: https://cbea.ms/git-commit/#limit-50

@EdDev  done, is that better?

**Comment by iholder-redhat** [comment]
/lgtm
thanks @acardace

**Review by EdDev — COMMENTED** [review]
Thanks!

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
