### PR TITLE
[vmi-mutator-webhook]: do not inject LimitRange defaults into VMI

### PR DESCRIPTION
**Pull request by enp0s3**
**What this PR does / why we need it**:
 
Currently when LimitRange is configured with defaults for compute resources such as CPU or memory, 
these defaults are being injected to the VMI spec early in the VMI mutating stage. 
Hence, when looking at the VMI spec we can't really know the source of information 
for these values, whether they are user-defined or not.

This situation causes issues at the stage of launcher-pod rendering. The resource renderer assumes
the VMI spec values are user defined and prefers them over caclulated resource requests.

If the user defines CPU topology with CPU overcommit, the calculated CPU request is being ignored
in favor to the CPU request from the LimitRange.

For example: a VMI with configured CPU topology of 4 vCPU in spec.domain.CPU.cores
will have a resource request of 400m (num_of_cores * 1000 / AllocationRatio).
Lets take LimitRange Default CPU request as 100m. 
The renderred virt-launcher pod will have 100m CPU request instead of 400m.

The proposed solution is to ignore the LimitRange defaults, giving priority 
to user configuration, and later to calculated configuration. 

**Which issue(s) this PR fixes**
https://bugzilla.redhat.com/show_bug.cgi?id=2152534

**Special notes for the reviewer**
If we exceed the resource limits of the LR we will
fail at the pod creation stage rather than on the VMI admission. I think this is the correct
behavior because of `Type: Container`. If the LimitRange would be configured on type VMI/VM for example
then perhaps it would make sense to fail on the VMI admission control.

**Release note**:
```release-note
do not inject LimitRange defaults into VMI
```

### CODE REVIEW

**Comment by iholder101** [comment]
Ah.. code deletion always feels good :smile: 
Great job @enp0s3!

Some other stuff that should maybe also be removed:
- Limit range informer in [virtinformers.go](https://github.com/kubevirt/kubevirt/blob/main/pkg/controller/virtinformers.go#L167)
- Some [RBAC rules](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-operator/resource/generate/rbac/apiserver.go#L164)
- This [test](https://github.com/kubevirt/kubevirt/blob/main/tests/vmi_configuration_test.go#L947)?

**Comment by vladikr** [comment]
> Ah.. code deletion always feels good smile Great job @enp0s3!
> 
> Some other stuff that should maybe also be removed:
> 
> * Limit range informer in [virtinformers.go](https://github.com/kubevirt/kubevirt/blob/main/pkg/controller/virtinformers.go#L167)
> * Some [RBAC rules](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-operator/resource/generate/rbac/apiserver.go#L164)

> * This [test](https://github.com/kubevirt/kubevirt/blob/main/tests/vmi_configuration_test.go#L947)?

Interesting that this test is passing now... @enp0s3 Is it really the case?

**Comment by enp0s3** [comment]
/hold
There is an issue with operator lanes with the downgrade->upgrade test, since we deleted the RBAC for LimitRange, the dongraded virt-api cannot access the LimitRange resource for watching.

**Comment by iholder101** [comment]
> /hold There is an issue with operator lanes with the downgrade->upgrade test, since we deleted the RBAC for LimitRange, the dongraded virt-api cannot access the LimitRange resource for watching.

WDYT about keeping the RBAC rules for a while and removing them in the future? Does that make sense?

**Comment by enp0s3** [comment]
@iholder101 Yes as a workaround I can remove them in a subsequent PR.

**Comment by enp0s3** [comment]
But, in general I will check the upgrade path, it looks suspicious, what happens when we change RBAC? I saw some logic regarding backup of RBAC rules if they are being modified, but yet it looks it doesn't help much.

**Comment by enp0s3** [comment]
@iholder101 Actually this may cause an issue with downgrades i.e. for some reason an upgrade fails and user wants to downgrade to previous version

**Comment by acardace** [comment]
/approve

Nice to see this simplification, thanks @enp0s3 !

**Comment by iholder101** [comment]
/lgtm
Great work!

**Pull request merged**
