### PR TITLE
Fix --max-devices option

### LINKED ISSUE #7751: virt-handler unknown flag: --maxDevices
**What happened**:
virt-handler unknown flag: --maxDevices when I set CR kubevirt  Configuration VirtualMachineInstancesPerNode

**What you expected to happen**:
when I set CR kubevirt  Configuration VirtualMachineInstancesPerNode, virt-handler not work, unknown flag: --maxDevices
virt-handler param --max_devices

**How to reproduce it (as minimally and precisely as possible)**:
when I set CR kubevirt  Configuration VirtualMachineInstancesPerNode, virt-handler not work, unknown flag: --maxDevices
virt-handler param --max_devices

**Additional context**:
pkg/virt-operator/resource/apply/apps.go
func setMaxDevices  should add  --max_devices ds virt-operator Container Command

**Environment**:
- KubeVirt version (use `virtctl version`):  v0.5x
- Kubernetes version (use `kubectl version`): v1.21.8
- VM or VMI specifications: N
- Cloud provider or hardware configuration: N
- OS (e.g. from /etc/os-release): centos7.9
- Kernel (e.g. `uname -a`): N
- Install tools:  virt-operator
- Others: N

### PR DESCRIPTION
**Pull request by kvaps**
**What this PR does / why we need it**:
Fix virt-operator to set kebab-case `--max-device` option

**Which issue(s) this PR fixes**:
Fixes #7751

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
Thanks @kvaps for addressing this. Can you adjust the Release note by putting `NONE` inside a code block (https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks), instead of a plain string, please? Otherwise the PR result with `do-not-merge/release-note-label-needed` label.
Any possibility to add a functional test to cover it? Thanks

**Comment by kvaps** [comment]
sure, fixed

**Comment by xpivarc** [comment]
The only thing missing is a functional test to ensure everything is working and will continue to work. Will you be able to add it?

**Comment by kvaps** [comment]
There are some test, I fixed it as well

https://github.com/kubevirt/kubevirt/blob/f706e94229bc45d42d1085454aa53a9fa324d8f4/pkg/virt-operator/resource/apply/apps_test.go#L387-L392

**Comment by fossedihelm** [comment]
@kvaps I think there is a leftover here: https://github.com/kubevirt/kubevirt/blob/08038294dd7a5c3df28a747e8792b7d938271e97/tests/operator_test.go#L1364

Also, I think that what I and @xpivarc are asking for is a functional test that if the `max-devices` param is passed to the virt-hadler command, ensures that the pod comes up without any errors since the current test suites do not discover this bug.
I think that something like this https://github.com/kubevirt/kubevirt/blob/08038294dd7a5c3df28a747e8792b7d938271e97/tests/operator_test.go#L1362 with the addition that ensures that virt-handler does not have any errors should be enough.

@xpivarc how about refactoring all these plain string args with const Should we face it in a separate PR?https://github.com/kubevirt/kubevirt/blob/08038294dd7a5c3df28a747e8792b7d938271e97/cmd/virt-handler/virt-handler.go#L564

**Comment by xpivarc** [comment]
> @kvaps I think there is a leftover here:
> 
> https://github.com/kubevirt/kubevirt/blob/08038294dd7a5c3df28a747e8792b7d938271e97/tests/operator_test.go#L1364
> 
> Also, I think that what I and @xpivarc are asking for is a functional test that if the `max-devices` param is passed to the virt-hadler command, ensures that the pod comes up without any errors since the current test suites do not discover this bug. I think that something like this
> 
> https://github.com/kubevirt/kubevirt/blob/08038294dd7a5c3df28a747e8792b7d938271e97/tests/operator_test.go#L1362
> with the addition that ensures that virt-handler does not have any errors should be enough.
> 
> @xpivarc how about refactoring all these plain string args with const Should we face it in a separate PR?
> 
> https://github.com/kubevirt/kubevirt/blob/08038294dd7a5c3df28a747e8792b7d938271e97/cmd/virt-handler/virt-handler.go#L564

It should be also reflected on the node object, right? Could we check it?

**Comment by enp0s3** [comment]
functional test is covered in #8083

**Pull request merged**
