### PR TITLE
Drop floppy disks

### PR DESCRIPTION
**Pull request by victortoso**
**What this PR does / why we need it**:
* We have been rejecting floppy disks since v0.16.0 thanks to #2164
* Removing unsupported code is a win.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
running `make generate` is not enough to remove floppy disks from kubevirt.io/client-go. Not sure if there is an extra step due #6661

At the moment:
```bash
$ grep -rniI "floppy" *
staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go:446:                "kubevirt.io/client-go/apis/core/v1.FloppyTarget":                                            schema_client_go_apis_core_v1_FloppyTarget(ref),
staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go:19857:                                                      Description: "Disks describes disks, cdroms, floppy and luns which are connected to the vmi.",
staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go:20041:                                      "floppy": {
staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go:20043:                                                      Description: "Attach a volume as a floppy to the vmi.",
staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go:20044:                                                      Ref:         ref("kubevirt.io/client-go/apis/core/v1.FloppyTarget"),
staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go:20106:                      "kubevirt.io/client-go/apis/core/v1.BlockSize", "kubevirt.io/client-go/apis/core/v1.CDRomTarget", "kubevirt.io/client-go/apis/core/v1.DiskTarget", "kubevirt.io/client-go/apis/core/v1.FloppyTarget", "kubevirt.io/client-go/apis/core/v1.LunTarget"},
staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go:20129:                                      "floppy": {
staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go:20131:                                                      Description: "Attach a volume as a floppy to the vmi.",
staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go:20132:                                                      Ref:         ref("kubevirt.io/client-go/apis/core/v1.FloppyTarget"),
staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go:20145:                      "kubevirt.io/client-go/apis/core/v1.CDRomTarget", "kubevirt.io/client-go/apis/core/v1.DiskTarget", "kubevirt.io/client-go/apis/core/v1.FloppyTarget", "kubevirt.io/client-go/apis/core/v1.LunTarget"},
staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go:20821:func schema_client_go_apis_core_v1_FloppyTarget(ref common.ReferenceCallback) common.OpenAPIDefinition {
```

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by victortoso** [comment]
Rebased.

**Comment by victortoso** [comment]
ping
/retest

**Comment by victortoso** [comment]
ping

**Comment by rmohr** [comment]
/lgtm
/approve

Thanks @victortoso for the consistent rebases!

**Pull request merged**
