### PR TITLE
Hardcode range selector to 5m and add a Primer VMI before each test

### PR DESCRIPTION
**Pull request by rthallisey**
Signed-off-by: Ryan Hallisey <rhallisey@nvidia.com>

We're using the Range Vector variable to focus when we gather metrics, however that's not what it's suppose to be used for.  Range Vector is described in this [blog ](https://www.section.io/blog/prometheus-querying/):
"
Your selection of range duration will determine how granular your chart is. A [1m] duration, for instance, will give a very spiky chart, making it difficult to visualize a trend, looking something like this:
1m-chart

For a one hour view, [5m] would show a decent view:
5m-chart
"
Since we're setting the Range Vector based on the amount of time it takes to run the test 1-2 minutes, the results can vary quite a bit.  A 20 VM test locally using `[1m]` showed 40 CREATE requests while changed the vector to `[5m]` on the same test showed 22.  This would explain why our test results are so inconsistent.  100 VMs are created, by our http count is off so setting to the right range should fix it.  Also, increasing past `[5m]` to `[10m]` showed 21 CREATE requests, so it has diminishing returns.  `[5m]` seemed like the best value.

The one concern I have with the `[5m]` Range Vector is it can overlap with other tests the could happen in parallel.  I ran two tests back to back and CREATE went up to 44 then back down to 22.  Something to keep in mind for later.

In https://github.com/kubevirt/kubevirt/issues/7083, @marceloamaral pointed out that some of the metrics we expect to exist during the test, don't appear.  This PR adds a primer VMI that launcher a single VMI before only the first performance test so that the `increase` has a starting value to compare against in the time series database.

There's some follow up work to this PR that should be considered:
- The range vector needs to be >= `2min` in order to find an accurate increase in CREATE requests, however it could also be lower than 5m to avoid overlap with other tests.  We should have a nice abstraction to handle the ideal range vector based on test time, so that data interpretation is consistent and doesn't get muddied.
- With multiple tests, do we need a new primer if enough time has gone by?

fixes: https://github.com/kubevirt/kubevirt/issues/7083

```release-note
NONE
```

### CODE REVIEW

**Comment by rthallisey** [comment]
@davidvossel @marceloamaral I think this will fix the test

**Comment by rthallisey** [comment]
I also set offset to be right at the end of the test.  That will make sure the range vector is grabs the data right from when this tests ends

**Comment by marceloamaral** [comment]
Thanks Ryan, this is interesting!

However, this will not solve the problem as the real problem is not related to the query but something internal to the KubeVirt code. I created an issue further detailing this issue: #7083.
Since you created this PR I also tested the query with long range (as default in perfaudit code) and short range [5m] as you suggested here. But I didn't see any change in getting more events, changing the range just changes how smooth the curves are on the graph.

As I am creating the scripts to run the density test on our performance cluster, in PR #7060 I also included the workaround to solve this problem of collecting all events from the Prometheus metric `rest_client_requests_total`, through system warm-up (i.e. creating/deleting a VMI) before running the performance test.

**Comment by rthallisey** [comment]
I think it's both Marcelo.  Your fix has to do with metrics not appearing, however the range selector effects how the data that does appear is presented.   If we're going to have accurate thresholds, we want a consistent measurement.

**Comment by marceloamaral** [comment]
Btw, [increase](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) calculates the time series increment in the range vector. So the current implemented query shouldn't be a problem...

I did a test creating 100 VMis and tried to get the CREATE pod with different queries:

(1) with 5m interval in the query
image

(2) with 5m interval in the query and 5m offset
image

(3) with 10m interval in the query
image

The first scenario cannot be used after running the test as we will not get the data. Maybe I'm using it wrong, but the offset didn't show any data for me....The third scenario actually showed the closest result, since I was expecting 100. 

So I still think we should keep the current query using the long interval.
@davidvossel any opinion?

**Comment by rthallisey** [comment]
`sum(increase(rest_client_requests_total{pod=~"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*", verb="CREATE"}[5m])) by (verb, method, resource) > 0`
Screen Shot 2022-01-18 at 7 26 34 AM
`sum(increase(rest_client_requests_total{pod=~"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*", verb="CREATE"}[2m])) by (verb, method, resource) > 0`
Screen Shot 2022-01-18 at 7 26 21 AM
`sum(increase(rest_client_requests_total{pod=~"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*", verb="CREATE"}[1m])) by (verb, method, resource) > 0`
Screen Shot 2022-01-18 at 7 26 08 AM

**Comment by rthallisey** [comment]
>(2) with 5m interval in the query and 5m offset
>
Offset moves time backwards.  So Prometheus is acting like the current time is 5m in the past and that's probably before your test ran.  I don't expect offset to be a high number (less than 1 min).

**Comment by rthallisey** [comment]
I've confirmed that the `increase` metric is not going to gather data when a new cluster is created and the first thing you do is run `make perftest` as @marceloamaral pointed out in [#7083](https://github.com/kubevirt/kubevirt/issues/7083).  Every time I ran the test, I consistently saw nothing on the number of `CREATE` requests.  I added a primer to create a single VMI before the perf test and now more data appears.  Here's an example result:
**Primer Test**
```json
{
  "Values": {
    "CREATE-events-count": {
      "value": 1.4618166666666668
    },
    "GET-endpoints-count": {
      "value": 154.17945
    },
    "GET-nodes-count": {
      "value": 15.129166666666666
    },
    "PATCH-services-count": {
      "value": 20.092000000000002
    },
    "UPDATE-endpoints-count": {
      "value": 94.0845
    },
    "UPDATE-kubevirts-count": {
      "value": 1.6743333333333335
    },
    "UPDATE-virtualmachineinstances-count": {
      "value": 1.9236333333333335
    },
    "running-phase-count": {
      "value": 1
    },
    "vmiCreationToRunningSecondsP50": {
      "value": 0
    },
    "vmiCreationToRunningSecondsP95": {
      "value": 0
    },
    "vmiCreationToRunningSecondsP99": {
      "value": 0
    }
  }
}
```
Followed by the normal **Density Test**
```json
{                                                                                                                                                                                                                                         
   "Values": {                                                                                                                                                                                                                                   
     "CREATE-events-count": {                                                                                                                                                                                                                       
     "value": 68.57939025602866                                                                                                                                                                                                                 
    }, 
    "CREATE-pods-count": {                                                                                                                                                                                                                         
      "value": 21.03949703772217
    },
    "GET-endpoints-count": {
      "value": 279.7757196518876
    },
    "GET-nodes-count": {
      "value": 106.0301062652498
    },
    "PATCH-nodes-count": {
      "value": 1.1220663724483675
    },
    "PATCH-pods-count": {                                                                                                                                                                                                                          
      "value": 21.03949703772217                                                                                                                                                                                                                      
    },
    "PATCH-services-count": {
      "value": 14.239760000000002
    },
    "PATCH-virtualmachineinstances-count": {
      "value": 21.052661400526613
    },
    "UPDATE-endpoints-count": {
      "value": 170.5154129852209
    },
    "UPDATE-kubevirts-count": {
      "value": 1.1866466666666668
    },
    "UPDATE-virtualmachineinstances-count": {
      "value": 170.40607767121628
    },
    "running-phase-count": {
      "value": 20
    },
    "vmiCreationToRunningSecondsP50": {
      "value": 29.18349769780884
    },
    "vmiCreationToRunningSecondsP95": {
      "value": 38.95100986186853
    },
    "vmiCreationToRunningSecondsP99": {
      "value": 39.79020197237371
    }
  }
}
```
You can see the Primer test has no `CREATE` pod requests while the Density test does.  The reason for this is explained in this [blog](https://www.section.io/blog/beware-prometheus-counters-that-do-not-begin-at-zero/).  It doesn't explicitly mention `increase()`, however `increase()` is just [syntactical sugar ](https://stackoverflow.com/questions/38659784/graphing-slow-counters-with-prometheus-and-grafana) around the `rate()` function.  Here's the paragraph that highlights the point:
```
The problem with the first sample of a new metric series is that rate is attempting to compare against a
non-existent previous value and Prometheus does not have enough data with which to interpolate.
```  

I also have an explanation to why I was seeing 40 `CREATE` requests in prometheus when I create 20 VMs with a `[1m]` range vector shown in https://github.com/kubevirt/kubevirt/pull/7075#issuecomment-1015364766 and why the values vary based on the range vector.  The issue is called aliasing and it's explained well in this stackoverflow [link](https://stackoverflow.com/questions/48218950/increase-in-prometheus-sometimes-doubles-values-how-to-avoid).   To summarize, since `rate()`, which `increase()` is based on, is an extrapolation, the values will vary based on the amount of time `rate()` extrapolates over:
```
Here for example the query executed at 1515722220 only sees the 580@1515722085.194 and
581@1515722205.194 samples. That's an increase of 1 over 2 minutes, which extrapolated over
4 minutes is an increase of 2
```
To get an accurate `increase()`, the range vector needs to be larger than the 1-2 minutes we have now and it should really change per metric!  `[5m]` should be a safe measurement for now.  Tests that take longer than 5minutes will need larger values.

**Comment by marceloamaral** [comment]
Interesting @rthallisey, thanks!

Found that [Prometheus double counting issue](https://grafana.com/blog/2021/08/19/how-we-fixed-a-double-counting-prometheus-bug-while-working-on-a-grafana-cloud-project/) was fixed on April 27, 2021 with the PR [prometheus/prometheus/pull/#8748](https://github.com/prometheus/prometheus/pull/8748).

So the latest version of Prometheus should have this fixed. If you have time, could you try this?

**Comment by marceloamaral** [comment]
/hold

Regarding [offset](https://prometheus.io/docs/prometheus/latest/querying/basics/#offset-modifier), I'm not convinced it's the right approach...
Actually `offset` is doing something different than what we need here.

Consider the following example: `rate(rest_client_requests_total[5m] offset 1w)`
This query returns the 5 minute rate that rest_client_requests_total had a week ago.
So it will not be the interval `from now to 1w ago` with 5m steps, but `1w-5m to 1w ago`.

Following the same offset logic, it is also possible to set a specific timestamp back in time with [modifier](https://prometheus.io/docs/prometheus/latest/querying/basics/#modifier): `rate( rest_client_requests_total[ 5m] @ 1609746000)`. This returns the 5 minute rate that rest_client_requests_total had on 2021-01-04T07:40:00+00:00

I think what you want to achieve here is actually the [range query](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries), which has a start, an end, and a step.
This will return an array of multiple evaluations using the steps between the start to end timestamps.

**Review by marceloamaral — CHANGES_REQUESTED** [review]
So could you change the `offset` implementation for the range query?

**Comment by rthallisey** [comment]
> Consider the following example: rate(rest_client_requests_total[5m] offset 1w)
This query returns the 5 minute rate that rest_client_requests_total had a week ago.
So it will not be the interval from now to 1w ago with 5m steps, but 1w-5m to 1w ago.
>
What if our test ran 1 week ago and multiple tests ran after it?  I have the offset programmed to point to the endTime of the test and our results come from the past 5m.  I'm concerned about getting muddied results.

**Comment by rthallisey** [comment]
>Found that Prometheus double counting issue was fixed on April 27, 2021 with the PR prometheus/prometheus/pull/#8748.

So the latest version of Prometheus should have this fixed. If you have time, could you try this?
>
I still see the double counting with the latest version.  The response in https://stackoverflow.com/questions/48218950/increase-in-prometheus-sometimes-doubles-values-how-to-avoid doesn't make it seem like there's no general solution.  A large enough range vector is how prometheus deals with it.

**Comment by marceloamaral** [comment]
>What if our test ran 1 week ago and multiple tests ran after it? I have the offset programmed to point to the endTime of the test and our results come from the past 5m. I'm concerned about getting muddied results.

[range query](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) will address this, you will provide the exact test interval with a start, end and step (e.g. 5m)

**Comment by rthallisey** [comment]
>range query will address this, you will provide the exact test interval with a start, end and step (e.g. 5m)
>
Maybe, but the result should be the same as using `offset`, a range vector and a regular query.   Also, it's not clear to me how a range query can be used with `rate` and `increase` when setting a range vector.  `rate` already sets the interval ranges which I think conflicts with what range query is doing.  I think is something to consider as a follow up discussion.

**Comment by marceloamaral** [comment]
Ok, it is good to go.
/lgtm

**Comment by rthallisey** [comment]
Follow up work:
- The range vector should depend on the prometheus scrape interval (confirmed that interpolation is based on the range vector and scrape interval)
- The range vector needs to be longer than the test duration

**Comment by marceloamaral** [comment]
In the end, this PR was merged with the hard coded range of 5m.
But we agreed at our sig-scale meeting to revert the change it the range to the duration of the test.
Should we roll back this PR or create a new one to update this?

**Comment by rthallisey** [comment]
It will be fixed in a follow up.

**Pull request merged**
