### PR TITLE
[release-1.2] Admit eviction on completed virt-launcher pods

### PR DESCRIPTION
**Pull request by fossedihelm**
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/12451
### Release note

```release-note
Fix: eviction requests to completed virt-launcher pods cannot trigger a live migration
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
/hold
release 1.3 first https://github.com/kubevirt/kubevirt/pull/12495

**Review by xpivarc — APPROVED** [review]
/approve

**Pull request merged**
