### PR TITLE
build: Update make-deps-update results

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

Running `make deps-update` on master branch has unexpected results.
The results are hereby pushed to allow future changes to reflect only the
expected changes.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by enp0s3 — APPROVED** [review]
/lgtm
/approve

**Comment by EdDev** [comment]
@ormergi , this is something new: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5387/pull-kubevirt-e2e-kind-1.17-sriov/1378695043069513731

**Comment by ormergi** [comment]
> @ormergi , this is something new: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5387/pull-kubevirt-e2e-kind-1.17-sriov/1378695043069513731

Probably something on changes on that host (srv17)

**Pull request merged**
