### PR TITLE
add configmap iso support for Windows (i.e. sysprep support)

### PR DESCRIPTION
**Pull request by oatakan**
**What this PR does / why we need it**:
Currently all files coming via configMap are created as symlinks via an ISO file which works on Linux but shows 0 bytes on Windows. This PR adds '-follow-links' switch to iso generation so that the generated iso does not contain any symlink which enables use cases like providing Autounattended.xml for sysprep.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes 2902

**Special notes for your reviewer**:

**Release note**:

```release-note
Allow windows picking up files in configmaps and secrets, by following symlinks when generating the corresponding ISOs.
```

### CODE REVIEW

**Comment by rmohr** [comment]
@oatakan thanks, nice fix! :+1:

**Comment by oatakan** [comment]
@rmohr do you know if I need to do anything on my end? not sure why one of the tests failed.

**Comment by rmohr** [comment]
We suffer from some flaky tests. I hope it is resolved until the end of the week and that the PRs will go in over the weekend.

**Comment by oatakan** [comment]
> We suffer from some flaky tests. I hope it is resolved until the end of the week and that the PRs will go in over the weekend.

Understand. Sounds good.

**Comment by rmohr** [comment]
Merging some trivial PRs alongside with a flaky test fix manually to reduce the backlock.

**Comment by rmohr** [comment]
Thanks again! :+1:

**Pull request merged**
