### PR TITLE
[Testing] Add missing test for Block MultiQueue

### PR DESCRIPTION
**Pull request by stu-gott**
```release-note
NONE
```

### CODE REVIEW

**Comment by sHaggYcaT** [comment]
Overall, I agree with everything, good code. Just minor remark.

**Comment by fabiand** [comment]
@sHaggYcaT which remark?

**Comment by sHaggYcaT** [comment]
@fabiand @stu-gott  about  rfe_id:2065

**Comment by stu-gott** [comment]
@sHaggYcaT So that was in reference to the comments in https://github.com/kubevirt/kubevirt/pull/2259? You approve of the changes in this PR?

**Comment by stu-gott** [comment]
@sHaggYcaT Ah! the rfe_id was wrong. fixed!

**Comment by sHaggYcaT** [comment]
@stu-gott thank you. LGTM.

**Comment by ILpinto** [comment]
LGTM we can merge

**Pull request merged**
