### PR TITLE
Fix double free of VirDomain

### PR DESCRIPTION
**Pull request by vasiliy-ul**
**What this PR does / why we need it**:

The PR fixes double free of VirDomain object in the case when a domain does not exists and it is created.

**Special notes for your reviewer**:
If a domain does not exists, `l.virConn.LookupDomainByName` returns a non-null `err` and the first time `defer dom.Free()` is called at
https://github.com/kubevirt/kubevirt/blob/6d745fc5dfa9b7e3d476cfde6ca38ddb8655c369/pkg/virt-launcher/virtwrap/manager.go#L757-L761
Then one more time after the `if err != nil { ... }` block:
https://github.com/kubevirt/kubevirt/blob/6d745fc5dfa9b7e3d476cfde6ca38ddb8655c369/pkg/virt-launcher/virtwrap/manager.go#L761-L768

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

I'm surprised this doesn't cause a crash. How did you find this?

**Comment by vasiliy-ul** [comment]
> I'm surprised this doesn't cause a crash. How did you find this?

@davidvossel , I am surprised as well... We build and run Kubevirt with our own containers and in fact after updating to 0.40.0 virt-launcher started crashing with SIGSEGV every time a new VM was created. I tried 0.39.1 and the issue was also there. But somehow 0.38.1 was working fine. I am thinking if that might be because of some compiler flags or build options that are used for our base image and/or Kubevirt. Though for Kubevirt we don not set anything special... apart from building it with native Go instead of Bazel.

**Comment by rmohr** [comment]
> @davidvossel , I am surprised as well... We build and run Kubevirt with our own containers and in fact after updating to 0.40.0 virt-launcher started crashing with SIGSEGV every time a new VM was created. I tried 0.39.1 and the crash was also reproducible. But somehow 0.38.1 was working fine with this double-free. I am thinking if that might be because of some compiler flags or build options that are used for our base image and/or Kubevirt. Though for Kubevirt we don not set anything special... apart from building it with native Go instead of Bazel.

I think it was introduce here: https://github.com/kubevirt/kubevirt/pull/4685/files#diff-98b8339212e612cd92ce33649e492336892a3ed649f368b181aad9aa2854138cR1354

**Comment by davidvossel** [comment]
@vasiliy-ul  would you be able to backport this to release 0.39 and 0.40 branches by chance?

**Comment by vasiliy-ul** [comment]
@davidvossel , sure

**Pull request merged**
