### PR TITLE
Add an example migration policy to `/examples` directory

### PR DESCRIPTION
**Pull request by iholder101**
**What this PR does / why we need it**:
This PR adds a migration policy manifest example to our `/examples` directory.
This will ease playing with policies for either testing or exploration.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder101** [comment]
/cc @enp0s3 @Barakmor1
Mind having a quick look?

**Review by xpivarc — COMMENTED** [review]
Please squash the commits. Otherwise LGTM

**Comment by enp0s3** [comment]
/approve
/hold
Please unhold upon addressing @xpivarc comments

**Comment by enp0s3** [comment]
@iholder101 As a follow-up work, Maybe it even worth to extend the `virtctl create` to create migration policy manifests.

**Comment by iholder101** [comment]
> @iholder101 As a follow-up work, Maybe it even worth to extend the `virtctl create` to create migration policy manifests.

For sure!
This is definitely on my check-list (also for VM clones).

**Pull request merged**
