### PR TITLE
prometheus: metrics: add Swap{In,Out} reporting

### PR DESCRIPTION
**Pull request by fromanirh**
**What this PR does / why we need it**:
Add support for more memory metrics: Swap{In,Out} reporting

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubevirt/kubevirt/issues/2023

**Special notes for your reviewer**:
none

**Release note**:
```release-note
Add support to report SwapIn and SwapOut metrics
```

### CODE REVIEW

**Comment by vladikr** [comment]
Looks good, @fromanirh is it really wip ?

**Comment by fromanirh** [comment]
@stu-gott thanks for the review!
@vladikr I was considering adding more tests, but on second thought the ones already in the patch may be sufficient. Removed the WIP tag.

**Comment by fromanirh** [comment]
ci test please

**Comment by fromanirh** [comment]
> @fromanirh it looks good to me. Before merging, could you please verify that this failure is relevant or not... `should include the storage metrics for a running VM `

It seems a glitch, confirmed by a succesfull rerun: https://kubevirt-master-stdci-production.apps.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/656/artifact/ci_build_summary.html

**Pull request merged**
