### PR TITLE
Use ginkgo labels for marking tests

### PR DESCRIPTION
**Pull request by divyaKh**
**What this PR does / why we need it**: This PR focuses on using ginkgo label decorators to mark if GPU tests belong to a specific test lane or not. 
The PR adds a new label ```needs-gpu``` to the group of tests written in ```kubevirt/tests/vmi_gpu_test.go```. It eliminates the dependency on the use of random keywords matchers.
```--label-filter``` is then used with gingko params in ```automation.test.sh```, to indicate that which all test lanes require the GPU tests.

**Which issue(s) this PR fixes** *

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by maiqueb** [comment]
@nunnatsa you were looking into something similar; would you want to coordinate with this effort ?

**Comment by dhiller** [comment]
@divyaKh to make the failing DCO check go away you need to sign your commits as described here: https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md#contributor-compliance-with-developer-certificate-of-origin-dco

**Comment by dhiller** [comment]
> @divyaKh to make the failing DCO check go away you need to sign your commits as described here: https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md#contributor-compliance-with-developer-certificate-of-origin-dco

I have created a utility script that adds a pre-commit hook, so that this happens automatically, you can find the script here: https://github.com/dhiller/utility-scripts/blob/master/git/add-prepare-commit-with-signoff-hook.sh

**Comment by divyaKh** [comment]
> @divyaKh to make the failing DCO check go away you need to sign your commits as described here: https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md#contributor-compliance-with-developer-certificate-of-origin-dco

Hello @dhiller,

I have created a new pull request for the same. I have closed this one. In the new one the commits are signed. Thank you.  Use PR: ginkgo labels for marking tests #8017

**Pull request closed without merging**
