### PR TITLE
Remove Quarantine label from test_id:3311

### PR DESCRIPTION
**Pull request by vatsalparekh**
Signed-off-by: Vatsal Parekh <vparekh@redhat.com>

**What this PR does / why we need it**:
Remove quarantine label from non-flaky test_id:3311

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by fgimenez — APPROVED** [review]
/approve

This test has been in quarantine for a while without a ticket to work on it, it didn't had any recent failure on periodics.

**Review by enp0s3 — APPROVED** [review]
/approve

**Pull request merged**
