### PR TITLE
Handle errors in pkg/watchdog

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
Handle unhandled errors in pkg/watchdog.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Review by xpivarc — COMMENTED** [review]
/approve

**Review by maiqueb — APPROVED** [review]
Thank you!

**Comment by rmohr** [comment]
@akrejcir please don't mass-create individual trivial tiny PRs which are closely related. Just separate them by commit and bundle the changes at least until a reasonable PR since. As the project is set up, this creates a lot of email, review and CI overhead without benefit.

In the past we still merged such mass PRs, despite being discouraged, but I want to ask you to not continue doing that.

The changes as such are very welcome.

**Pull request closed without merging**
