### PR TITLE
Don't add default client flags in client-go to pflags

### LINKED ISSUE #2368: The operator-sdk can't be used with vendored kubevirt
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:

We have 
```
func init() {
	flag.StringVar(&kubeconfig, "kubeconfig", "", "absolute path to the kubeconfig file")
	flag.StringVar(&master, "master", "", "master url")
}
```

in

https://github.com/kubevirt/kubevirt/blob/master/pkg/kubecli/kubecli.go#L55

The flags here are also defined in the operator-sdk and they clash:

```
log is DEPRECATED and will be removed in a future version. Use logs instead.
kubevirt-vm-operator flag redefined: kubeconfig
panic: kubevirt-vm-operator flag redefined: kubeconfig

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc00007a180, 0x18cf060, 0x27590a0, 0x16aa419, 0xa, 0x16ed85b, 0x37)
        /usr/lib/golang/src/flag/flag.go:850 +0x4af
flag.StringVar(...)
        /usr/lib/golang/src/flag/flag.go:759
github.com/masayag/kubevirt-vm-operator/vendor/sigs.k8s.io/controller-runtime/pkg/client/config.init.0()
        /home/masayag/work/go/src/github.com/masayag/kubevirt-vm-operator/vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go:38 +0x98
```

**What you expected to happen**:

Setting these flags should be optional. Let's keep this in mind for #2297.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Controller SDKs add the master and kubeconfig flags very often by
default. Our client added it too by default. Stop doing this, to avoid
flag conflicts.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2368

**Special notes for your reviewer**:

**Release note**:

```release-note
Don't add default pflags in kubevirt.io/client-go to allow integration with operator sdks which add it too.
```

### CODE REVIEW

**Comment by rmohr** [comment]
@masayag that should finally allow the integration with the operator sdk. Note that you will have to vendor `kubevirt.io/client-go` after this is merged. You will not vendor `kubevirt.io/kubevirt`.

**Comment by slintes** [comment]
@rmohr some unit tests seem to be broken

**Comment by cynepco3hahue** [comment]
@rmohr Can you please check unit test failure
```
•... Timeout [5.001 seconds]
VirtualMachineInstance Subresources
/root/go/src/kubevirt.io/kubevirt/pkg/virt-api/rest/subresource_test.go:51
  Subresource api
  /root/go/src/kubevirt.io/kubevirt/pkg/virt-api/rest/subresource_test.go:89
    Should pass client websocket io to server SPDY io [It]
    /root/go/src/kubevirt.io/kubevirt/pkg/virt-api/rest/subresource_test.go:259
    Timed out
    /root/go/src/kubevirt.io/kubevirt/pkg/virt-api/rest/subresource_test.go:259
```

**Comment by cynepco3hahue** [comment]
let's wait for CI

**Comment by rmohr** [comment]
@cynepco3hahue it is broken :)

/hold

**Comment by cynepco3hahue** [comment]
@rmohr Fixed:)

**Pull request merged**
