### PR TITLE
readd perl dependency to libguestfs-tools image

### PR DESCRIPTION
**Pull request by alicefr**
**What this PR does / why we need it**:
Readd perl as dependencies for the libguestfs-tool container image. We force remove perl in the rpm tree in order to minimize the container size. However, perl is required for not interactive editing. Adding it as dependency increase the libguestfs-tools image by 50M. It is a reasonable increment to cover the tekton use case.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #https://github.com/kubevirt/kubevirt-tekton-tasks/issues/113

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
I can't say that I like having perl as dependency though :/

**Comment by alicefr** [comment]
@rmohr the alternative is to install it in the tekton image: https://github.com/kubevirt/kubevirt-tekton-tasks/blob/main/modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile . The usage in KubeVirt main repo is interactive, so we shouldn't encounter this problem. However, this might be a bit strange for the users that rely on this image and they need to know that we removed it.

**Comment by rmohr** [comment]
/retest

seems like it got stuck on the CI outage a few days ago.

**Comment by rmohr** [comment]
@alicefr can you force-push your code after a `commit --amend`, so that we get all labels added by prow?

**Pull request merged**
