### PR TITLE
Remove now stable tests from quarantine

### PR DESCRIPTION
**Pull request by maya-r**
Guestfs test by https://github.com/kubevirt/kubevirt/pull/6739
Controller rate limiter test fixed by https://github.com/kubevirt/kubevirt/pull/6726

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
fyi @fgimenez

**Review by enp0s3 — APPROVED** [review]
Thank you!
/lgtm
/approve

**Comment by fgimenez** [comment]
/lgtm

awesome thanks!

**Pull request merged**
