### PR TITLE
network,ut: Fix flaky test

### PR DESCRIPTION
**Pull request by oshoval**
### What this PR does
The network info interfaces order is not always the same,
because it has map usage in the middle of the flow where it is created, 
hence use `ConsistOf` instead `Equal`.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Review by orelmisan — APPROVED** [review]
Thank you for the PR @oshoval.

The flakiness is because `generateNetworkInfo()`  from `pkg/network/downwardapi/networkinfo.go` iterates over a map and the iteration order is not guaranteed [1].

nit: Please consider adjusting the commit subject to reflect the location where the change has been performed:
> net annotations gen, test: Fix network info flake

[1]  https://go.dev/ref/spec#RangeClause

**Review by nirdothan — COMMENTED** [review]
Thanks for the PR @oshoval 
I'm not sure how the comparison succeeds, as the structs that you are comparing consist of pointers[ like here ](https://github.com/kubevirt/kubevirt/pull/12924/files#diff-f970dfea670015a0719eea67d44fd0bf62cf1691346d4863305838a706527cc3R447) which do not reference the same memory addresses. I'm not sure that Gomega knows or tries to dereference these pointers. Am I wrong?

**Comment by EdDev** [comment]
> I'm not sure how the comparison succeeds, as the structs that you are comparing consist of pointers[ like here ](https://github.com/kubevirt/kubevirt/pull/12924/files#diff-f970dfea670015a0719eea67d44fd0bf62cf1691346d4863305838a706527cc3R447) which do not reference the same memory addresses. I'm not sure that Gomega knows or tries to dereference these pointers. Am I wrong?

See Gomega documentation about the [`Equal` matcher](https://onsi.github.io/gomega/#equalexpected-interface) usage of `DeepEqual`. Most other matchers will use it eventually.

**Comment by EdDev** [comment]
The migration lane fails for an unrelated reason.
@dhiller , @xpivarc FYI

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12924/pull-kubevirt-e2e-k8s-1.31-sig-compute-migrations/1838586981714497536

**Review by EdDev — COMMENTED** [review]
Thank you!

/approve

**Pull request merged**
