### PR TITLE
Switch to the new module-aware, semver-compliant libvirt Go bindings

### PR DESCRIPTION
**Pull request by andreabolognani**
**What this PR does / why we need it**:

The fact that the libvirt Go bindings were not a proper Go module and didn't follow semver has been a source of annoyance in the past. In order to address both issues, a new import path (`libvirt.org/go/libvirt`) has been created where a module-aware, semver-compliant version of the Go bindings will be developed going forward. The old version of the Go bindings (`libvirt.org/libvirt-go`) has been archived and will no longer be updated.

This PR switches to the new bindings. It's marked as a draft because no actual releases of the new bindings exist yet, so I'm just mocking their availability through a `go.mod` `replace` directive.

I'm opening this early to solicit feedback: the first release is not going to be tagged for about a week, so there's still some time to course-correct if necessary.

The new semver-compliant versioning scheme is documented at https://gitlab.com/libvirt/libvirt-go-module/-/blob/master/VERSIONING.rst

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by andreabolognani** [comment]
@rmohr @vladikr can you please take a look and confirm it seems sane? @kwiesmueller also provided input on this topic in the past, so it'd be great to hear from that side too :)

**Comment by andreabolognani** [comment]
> @rmohr @vladikr can you please take a look and confirm it seems sane? @kwiesmueller also provided input on this topic in the past, so it'd be great to hear from that side too :)

Any thoughts? The first release of the module-aware libvirt Go bindings is just a couple of days away now!

**Comment by rmohr** [comment]
> Any thoughts? The first release of the module-aware libvirt Go bindings is just a couple of days away now!

@andreabolognani I read through the linked document describing your reasoning for the version numbers. Looks good to me.

**Comment by kwiesmueller** [comment]
Read through the document as well. Looks good, thank you!

**Comment by andreabolognani** [comment]
@rmohr @kwiesmueller thank you for confirming we're on the right track! I'll turn this into a proper PR once the first release of the new bindings has been tagged :)

**Comment by andreabolognani** [comment]
Now that the first official release of the new Go bindings has officially been tagged, this PR can be considered for merging :)

**Comment by andreabolognani** [comment]
I can't reproduce either failure locally.

/retest

**Comment by rmohr** [comment]
> I can't reproduce either failure locally.

Yes looks good. Thanks!

/lgtm
/approve

**Pull request merged**
