### PR TITLE
[Docs] Update VMRolloutStrategy documentation to include the VM liveUpdateable fields

### PR DESCRIPTION
**Pull request by Barakmor1**
### What this PR does
Before this PR:

After this PR:

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder101** [comment]
Thank you @Barakmor1!

My only concern here is that it would be probable to forget adding these comments for a newly live-updatable field, and that these fields are shared between both VM and VMI objects which might be a bit confusing.

WDYT about documenting the live-updatable field in a centralized place, e.g. here?
https://github.com/kubevirt/kubevirt/blob/4dbd00bb050934f10937fd3a02bb8228068ee1fa/staging/src/kubevirt.io/api/core/v1/types.go#L2539-L2542

**Comment by Barakmor1** [comment]
> Thank you @Barakmor1!
> 
> My only concern here is that it would be probable to forget adding these comments for a newly live-updatable field, and that these fields are shared between both VM and VMI objects which might be a bit confusing.
> 
> WDYT about documenting the live-updatable field in a centralized place, e.g. here?
> 
> https://github.com/kubevirt/kubevirt/blob/4dbd00bb050934f10937fd3a02bb8228068ee1fa/staging/src/kubevirt.io/api/core/v1/types.go#L2539-L2542

Hey, thanks for reviewing! From what I understand, these fields are live-updatable only for the VM object, not the VMI. I've added this clarification in the documentation, so I hope it's clear.

As for centralizing the documentation under VMRolloutStrategy, the issue is that while VMRolloutStrategy controls the live-updatable behavior for memory and CPU, it doesn't apply to the tolerations field, which is also live-updatable.

**Comment by Barakmor1** [comment]
Update: Changed the PR to focus only on VMRolloutStrategy and clarify its purpose.

**Review by enp0s3 — COMMENTED** [review]
/approve
Thanks @Barakmor1! makes sense to me

**Comment by Barakmor1** [comment]
/unhold
Updated to docs to just include which are the live update-able fields

**Pull request merged**
