### PR TITLE
Allow kubevirt-operator to discover kube-prometheus

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

If no monitoring namespace is configured, check in addition to the
`openshift-monitoring` namespace also for the `monitoring` namespace.

https://github.com/prometheus-operator/kube-prometheus deploys
prometheus-operator in a similar enough fasion to openshift that simply
checking if the `monitoring` namespace exists in addition to
`openshift-monitoring` is enough to support autodiscover of
kube-prometheus and automatically deploy our monitoring objects on the
cluster. The same serviceAccount name is used.

`openshift-monitoring` has precedence for backward compatibility.

Finally this PR adds checks for the serviceAccount too (which was on the todo list), to avoid collision with a `monitoring` namespaces which is not related to `kube-prometheus`. `monitoring` is probably a common enough name to lead to such misunderstandings otherwise.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

Related to https://github.com/kubevirt/kubevirtci/pull/608 which immediately benefits from this change, since it allows deploying kube-prometheus to a kubevirtci cluster.

```release-note
Automatically discover kube-prometheus installations and configure kubevirt monitoring
```

### CODE REVIEW

**Comment by marceloamaral** [comment]
Everything looks great to me. 
/approve

It seems to be a flaky test problem
/retest

**Review by ashleyschuett — APPROVED** [review]

**Comment by rmohr** [comment]
/approve

thanks @ashleyschuett @marceloamaral

**Pull request merged**
