### PR TITLE
Update CDI manifests and client library to 1.30.0

### LINKED ISSUE #5071: Kubevirt cluster-sync fails: cdi-insecure-registries config-map not found
/kind bug

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5060/pull-kubevirt-e2e-k8s-1.17/1363387908672720896#1:build-log.txt%3A5471
Fails due to `cdi-insecure-registries config-map not found`
Happens pretty often

**What you expected to happen**:
Should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Possible that this change exposed it 
https://github.com/kubevirt/kubevirt/pull/4947
Before that it might happend but the retry worked around it

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by fgimenez**
Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

**What this PR does / why we need it**: We are having a lot of errors because of ImagePullBackOff of kubevirt/cdi-operator from Docker Hub, for instance https://prow.k8s.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.17/1364830915716452352 These changes bump CDI to the latest version, already available on Quay.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5071

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
/test all

looks good.

**Review by davidvossel — COMMENTED** [review]
/approve

**Comment by fgimenez** [comment]
Looks like there are consistent errors with CDI v1.30.0, trying v1.26.1 (the version currently used) from Quay here #5112, there might be issues pulling images that are not explicitly defined in the manifests, let's see.

**Comment by awels** [comment]
We just released CDI 1.31.0: https://github.com/kubevirt/kubevirt/pull/5126

**Comment by fgimenez** [comment]
/close

superseded by #5126

**Pull request closed without merging**
