### PR TITLE
[WIP] Add selinux check

### PR DESCRIPTION
**Pull request by petrkotas**
This PR add selinux check after the functest is run.
This is preliminary implementation that requires opinions on what is the best way to implement this.

Currently it is hard coded to vagrant. Is this fine?

@fabiand @stu-gott opinions?

Signed-off-by: Petr Kotas <petr.kotas@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/967)

### CODE REVIEW

**Comment by rmohr** [comment]
> Currently it is hard coded to vagrant. Is this fine?

We are going to remove vagrant: #910 ;)

I think that this task is a great opportunity to improve our log- and event-collection during test runs.
What I would love to see, is a `rsyslog` container which runs outside of our cluster, spawned by our client in https://github.com/kubevirt/kubevirtci, like it also does for e.g. the nfs server (https://github.com/kubevirt/kubevirtci/blob/master/gocli/cmd/run.go#L215). We can simply deploy this: https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-syslog.yaml and let it point to our rsyslog server.


Flow:
 1. If gocli is started with --logs-dir, we start a rsyslog daemon which writes everything to --logs-dir
 2. We deploy fluentd as part of our testing infra
 3. We run the tests
 4. We parse the logs for any artifacts which are interesting for us, e.g. selinux denials, which are also collected, since the go to /var/log/audit.log (or something like that).

**Comment by fabiand** [comment]
@petrkotas Hey is there any update on this one - or a PR somewhere else?

**Comment by petrkotas** [comment]
@fabiand actually the pr went kubevirtci/logging after this one is done, we can continue.

**Comment by rmohr** [comment]
> @fabiand actually the pr went kubevirtci/logging after this one is done, we can continue.

Here: https://github.com/kubevirt/kubevirtci/pull/9

**Comment by fabiand** [comment]
:+1:

**Pull request closed without merging**
