### PR TITLE
Quarantine test that triggers AfterSuite ns deletion failure

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
https://search.ci.kubevirt.io/?search=AfterSuite&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=pull-kubevirt.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
/hold
@mhenriks remove when comfortable

**Comment by EdDev** [comment]
Thanks @akalenyu !

**Comment by mhenriks** [comment]
@akalenyu given what you observed with instancetypes, we should we quarantine these as well? 
 https://github.com/kubevirt/kubevirt/blob/main/tests/storage/restore.go#L559

**Comment by akalenyu** [comment]
> @akalenyu given what you observed with instancetypes, we should we quarantine these as well? https://github.com/kubevirt/kubevirt/blob/main/tests/storage/restore.go#L559

I don't think so; if you look at the suite manifests it's always the VM clone tests that trigger this
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/10672/pull-kubevirt-e2e-k8s-1.26-sig-storage/1722904525083250688/artifacts/k8s-reporter/suite/0_vms.log
`"snapshotInProgress": "clone-testclone-snapshot` This name is crafted in the clone flow under `generateSnapshotName`

**Review by dhiller — APPROVED** [review]
/approve

@akalenyu thank you!

**Comment by akalenyu** [comment]
@dhiller @mhenriks should we unhold?

**Comment by brianmcarey** [comment]
We might need this for the release-1.1 branch until we have a solution.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/10743/pull-kubevirt-e2e-k8s-1.26-sig-storage-1.1/1725432727483715584

/cherry-pick release-1.1

**Pull request merged**
