### PR TITLE
VNC: some cleanups

### PR DESCRIPTION
**Pull request by victortoso**
**What this PR does / why we need it**: Small cleanup that I found while reading the VNC code.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by victortoso** [comment]
Rebased. It did not fail locally.
/retest

**Comment by victortoso** [comment]
> @victortoso looks like something went wrong on your rebase. Could you have another look?

Yeah, it went wrong. I'm trying to fix it, sorry for the noise.

**Comment by victortoso** [comment]
Converted to draft to avoid triggering CI

**Comment by victortoso** [comment]
Ok, giving up on the PR, not sure what went wrong so I'll open another one. I thought the procedure below wouldn't give any conflict with Github but seems I need to understand the workflow of PR better.

The last thing I did to fix the rebase was:
```
(master) git pull --rebase
(master) git push github master
(master) git checkout -b fixes-for vnc
(fixes-for-vnc) git cherry-pick git 47756a700 94a40cbb9 2d6f5da6d
(fixes-for-vnc) git push github vnc-small-fixes
```

It just adds more commits to the branch than I have in my victortoso:master
The new PR is fine too, https://github.com/kubevirt/kubevirt/pull/4046

Sorry again for the noise.

**Comment by rmohr** [comment]
@victortoso here a pretty much always working receipt:

```
git pull origin master # considering that origin is kubevirt/kubevirt
git checkout fixes-for-vnc # if not already on that branch
git rebase -i origin/master # resolve all conflicts and drop unwanted commits
git push vtoso fixes-for-vnc --force # force-push on the PR branc, assuming that vtoso is the name of your branch
```

**Pull request closed without merging**
