### PR TITLE
Fix qemu img version

### PR DESCRIPTION
**Pull request by alicefr**
**What this PR does / why we need it**:
Running `make rpms-update` fails with `Package qemu-img-17:7.1.0-3.el9 does not exist`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by andreabolognani** [comment]
> do you think it is better to update other components too or only qemu version is enough?

At some point over the next week or two I'm planning to bump all RPM versions to roughly match what's going to be in RHEL 9.2 - so QEMU 7.2.0, libvirt 9.0.0 and so on. In the meantime, picking a later build of QEMU 7.1.0 to keep `make rpm-deps` working should be fine.

**Comment by andreabolognani** [comment]
Note that QEMU 7.1.0-6 is in CentOS Stream 9 as well, so you could go with that slightly more updated version. It won't matter once we switch to QEMU 7.2.0 :)

**Comment by alicefr** [comment]
Close this, the version has been fixed by da2ab494dc3564140c5e798a1793177bdfe61031

**Pull request closed without merging**
