### PR TITLE
Fix guestfs test failure with PSA enabled

### PR DESCRIPTION
**Pull request by maya-r**
Adjust functions to pass namespace, and use the privileged namespace for the test that runs guestfs as root.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
/hold
Helping tide to merge https://github.com/kubevirt/kubevirt/pull/9124 first

**Comment by stu-gott** [comment]
/hold cancel
#9214 merged

**Comment by stu-gott** [comment]
/retest-required
(I think the bot only takes commands on first line)

**Pull request merged**
