### PR TITLE
Remove hostname limitation for migrations

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:

For a long time, Libvirt was using the hostname
to perform a check if it performs migration
from&to the same node. This check was dropped
or rather it is implemented in another way
since 6799b72d927015db4ce4cab879f072abc91a41ae 2020.

Therefore we can drop this limitation and actually address a long-standing bug with services.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
Bug fix: DNS integration continues to work after migration
```

### CODE REVIEW

**Review by jean-edouard — COMMENTED** [review]
/approve

**Comment by acardace** [comment]
@xpivarc why a draft? I think we want to see the CI give it a spin, right?

**Comment by xpivarc** [comment]
> @xpivarc why a draft? I think we want to see the CI give it a spin, right?

I was running some tests locally. It's working so I am switching from the draft but I would add tests for the situation we want to keep working. Makes sense?

**Comment by rmohr** [comment]
Ugh, I did not even know that we had this workaround in place ...

We did not have an e2e test ensuring that service traffic goes to the new VM?

**Comment by xpivarc** [comment]
> Ugh, I did not even know that we had this workaround in place ...
> 
> We did not have an e2e test ensuring that service traffic goes to the new VM?

I need to check but I doubt it.  I for sure want to add it.

**Comment by xpivarc** [comment]
> Ugh, I did not even know that we had this workaround in place ...
> 
> We did not have an e2e test ensuring that service traffic goes to the new VM?

I need to check but I doubt it.  I for sure want to add it.

**Comment by xpivarc** [comment]
Added a test but it is failing. From what I managed to check the dns is resolved but it never succeeded to connect to the server inside the VM. I will be back.
/cc @EdDev 
Maybe you can spot my mistake.

**Comment by xpivarc** [comment]
@rmohr PTAL

**Comment by xpivarc** [comment]
/cherry-pick release-0.58
/cherry-pick release-0.53
:face_exhaling:

**Pull request merged**
