### PR TITLE
automation: remove ipv6 lane

### PR DESCRIPTION
**Pull request by AlonaKaplan**
**What this PR does / why we need it**:

As the ipv6 lane no longer exists, it can be removed from automation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — CHANGES_REQUESTED** [review]
i think we should either keep it still, or remove also the folder
cluster-up/cluster/kind-k8s-1.17.0-ipv6 (both here and on kubevirtci)

**Comment by ormergi** [comment]
> i think we should either keep it still, or remove also the folder
> cluster-up/cluster/kind-k8s-1.17.0-ipv6 (both here and on kubevirtci)

Removing this folder should be done on kubevirtci repository, once merge we need to bump kubevirtci in this repository
There was a big change in kubevirtci lately and other providers were removed as well

**Comment by oshoval** [comment]
> > i think we should either keep it still, or remove also the folder
> > cluster-up/cluster/kind-k8s-1.17.0-ipv6 (both here and on kubevirtci)
> 
> Removing this folder should be done on kubevirtci repository, once merge we need to bump kubevirtci in this repository
> There was a big change in kubevirtci lately and other providers were removed as well

of course, i didnt meant otherwise.

**Comment by RamLavi** [comment]
@AlonaKaplan, Not sure I follow. 
I assume the lane we want to remove is [kind-k8s-1.17.0-ipv6](https://github.com/kubevirt/project-infra/blob/3836f95533fffd90f5de690ef8f1767c7bf2291f/github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L489), right?
then how is removing the skip flag `KUBEVIRT_E2E_SKIP` assumes to remove the ipv6, like said in the PR title?

I understand KUBEVIRT_E2E_SKIP was added in ipv6 case to skip certain tests since it's not supported there, but surely removing it won't cause the cancellation of the lane, no?

**Comment by oshoval** [comment]
There are also `IsRunningOnKindInfraIPv6` that should be removed if a clean-up is done imo.

**Review by dhiller — APPROVED** [review]
/lgtm
/approve

**Comment by oshoval** [comment]
@dhiller 
we have lots of leftovers, i dont see why its self contained
please see

https://github.com/kubevirt/kubevirt/pull/4368#pullrequestreview-508248228
https://github.com/kubevirt/kubevirt/pull/4368#issuecomment-708414164

**Comment by dhiller** [comment]
> @dhiller
> we have lots of leftovers, i dont see why its self contained
> please see
> 
> [#4368 (review)](https://github.com/kubevirt/kubevirt/pull/4368#pullrequestreview-508248228)
> [#4368 (comment)](https://github.com/kubevirt/kubevirt/pull/4368#issuecomment-708414164)

I beg to differ. cluster-up is vendored in from kubevirtci, so we need to remove it there and then bump kubevirtci here.

**Comment by oshoval** [comment]
> > @dhiller
> > we have lots of leftovers, i dont see why its self contained
> > please see
> > [#4368 (review)](https://github.com/kubevirt/kubevirt/pull/4368#pullrequestreview-508248228)
> > [#4368 (comment)](https://github.com/kubevirt/kubevirt/pull/4368#issuecomment-708414164)
> 
> I beg to differ. cluster-up is vendored in from kubevirtci, so we need to remove it there and then bump kubevirtci here.

of course, i didnt mean otherwise, but there are also more leftovers neto on kubevirt (see the 2nd link please),
and i think we should first remove the lane on them both and then remove the leftovers from kubevirt, i dont see why a point removal should go in, and also in the current order.

**Pull request merged**
