### PR TITLE
Add virt-viewer download instructions for Windows

### PR DESCRIPTION
**Pull request by qmfrederik**
**What this PR does / why we need it**:
Add virt-viewer download instructions for Windows. Took me some searching to figure this out, and thought it was worth documenting.

**Which issue(s) this PR fixes**

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by qmfrederik** [comment]
@rmohr Yes it did!

**Comment by slintes** [comment]
great, but I'm afraid this won't work anymore after merge of https://github.com/kubevirt/kubevirt/pull/1673, because windows seems to be ignored there. Will request to add "remote-viewer" for windows over there.

**Comment by fabiand** [comment]
@slintes I see that #1673 did not get the windows support, correct?

**Comment by slintes** [comment]
@fabiand yes, tracking it in https://github.com/kubevirt/kubevirt/issues/1713

**Comment by fabiand** [comment]
Ack, then I think this one is good to go.

**Pull request merged**
