### PR TITLE
[release-1.2] Integrate sidecar shim image

### LINKED ISSUE #11161: Make `image` field optional in the `HookSidecar` struct
Presently, it's mandatory for a hook sidecar user to provide a container image in the annotations when using the feature. Making this field optional by using an image with digest in virt-operator, much like how it's done in [this commit](https://github.com/kubevirt/kubevirt/pull/9177/commits/88bee3a38e1ab0bbbc3bc5f6fc7605cffc33be4a), would be helpful.

Using an image with digest that is based on some crypto function helps ensure that an image is not tempered with, which could plausibly be the case when using plain tags. This is especially useful in case of disconnected environment where images need to be pulled onto internal registry in advance.

### PR DESCRIPTION
**Pull request by tiraboschi**
### What this PR does
Before this PR: image field in the hooks.kubevirt.io/hookSidecars annotation in [this example](https://github.com/kubevirt/kubevirt/blob/main/examples/vmi-with-sidecar-hook-configmap.yaml) was mandatory.

After this PR: aforementioned field will be optional.

Fixes #11161

### Why we need it and why it was done in this way
The following tradeoffs were made: N/A

The following alternatives were considered: N/A

Links to places where the discussion took place:

### Special notes for your reviewer

This is just a manual cherry-pick of #11272

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Make 'image' field in hook sidecar annotation optional.
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
@victortoso @alicefr FYI

**Comment by victortoso** [comment]
I think this is fine to backport to 1.2 indeed
/lgtm

**Comment by victortoso** [comment]
CI failures seem unrelated.
/lgtm

**Pull request merged**
