### PR TITLE
Add note to consider draft PR to pull request template

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

In the last kubevirt CI group meeting it was discussed that a default to create draft PRs would be favorable. Unfortunately this is not possible: https://github.com/refined-github/refined-github/issues/2238

Thus we add a comment to the Pull Request template notifying the author to consider creating a draft PR, linking the CONTRIBUTING.md section of draft PRs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by EdDev — APPROVED** [review]

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by iholder101** [comment]
Great idea!

/lgtm

**Comment by jean-edouard** [comment]
/approve
/retest
Not holding since this is harmless

**Pull request merged**
