### PR TITLE
virt-handler, hostdevice: Remove legacy support

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

The existing legacy hostdevice processing is broken [1] and untested.
A deprecation notice [2] has been sent with no objections from the
community.

Therefore, the relevant code is hereby removed.

[1] https://github.com/kubevirt/kubevirt/issues/6459
[2] https://groups.google.com/g/kubevirt-dev/c/xmZ8vx9-vME/m/w1Ywu4n3CAAJ

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
Support for legacy GPU definition is removed. Please see https://kubevirt.io/user-guide/virtual_machines/host-devices on how to define host-devices.
```

### CODE REVIEW

**Comment by EdDev** [comment]
change: Rebase

**Comment by EdDev** [comment]
@vladikr @rthallisey, could you please update where we stand with this one?
I do not think the existing code can be used (i.e. it is dead code), or do I miss something?

**Comment by rthallisey** [comment]
The work on the dp side is making progress https://github.com/NVIDIA/kubevirt-gpu-device-plugin/pull/29

**Review by rthallisey — APPROVED** [review]
Support for KubeVirt version 0.36+ merged in the gpu dp earlier today.  Legacy approach can be dropped.

**Comment by vladikr** [comment]
Looks good to me. 
@jean-edouard @alicefr could you please have a brief look to make sure we are not missing anything?

**Review by jean-edouard — APPROVED** [review]

**Comment by alicefr** [comment]
looks good to me

**Comment by vladikr** [comment]
Thanks!
/approve

**Pull request merged**
