### PR TITLE
docs: Fix the ginkgo flags usage example

### PR DESCRIPTION
**Pull request by ezrasilvera**
Signed-off-by: Ezra Silvera <ezra@il.ibm.com>

**What this PR does / why we need it**:
The example on how to run a specific functional tests uses a wrong format causing the `make functest` to fail with printout of the ginkco help

The error we get is `flag provided but not defined: -ginco.focus`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
"NONE"
```

### CODE REVIEW

**Review by EdDev — CHANGES_REQUESTED** [review]
Thanks!

There is a type in the commit message.
I would suggest rephrasing it a bit and give context: something like: `docs: Fix the ginkgo flags usage example`

**Comment by ezrasilvera** [comment]
> Thanks!
> 
> There is a type in the commit message.
> I would suggest rephrasing it a bit and give context: something like: `docs: Fix the ginkgo flags usage example`

@EdDev Done.

**Review by EdDev — APPROVED** [review]
Thank you!

**Review by enp0s3 — APPROVED** [review]
Thank you!

**Comment by danielBelenky** [comment]
/approve

thanks for the PR

**Pull request merged**
