### PR TITLE
Drop file based grace period trigger

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
The file-based trigger was dropped in v0.29 in favor
of marking the metadata of the domain. New virt-launchers
are not using this mechanism since.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by fossedihelm — APPROVED** [review]
Thanks! The PR looks good to me!
I think that this PR strictly related to https://github.com/kubevirt/kubevirt/pull/10837.
Maybe it is worth it to hold one of them, and serialize?

**Comment by xpivarc** [comment]
> Thanks! The PR looks good to me! I think that this PR strictly related to #10837. Maybe it is worth it to hold one of them, and serialize?

Can you elaborate? I do not see any relation as of now.

**Comment by fossedihelm** [comment]
> > Thanks! The PR looks good to me! I think that this PR strictly related to #10837. Maybe it is worth it to hold one of them, and serialize?
> 
> Can you elaborate? I do not see any relation as of now.

Sure! I just see an high probability of conflicts, since they are touching the same file in very close location. Also, they both change the import in the same file. That's it :)

**Comment by xpivarc** [comment]
> > > Thanks! The PR looks good to me! I think that this PR strictly related to #10837. Maybe it is worth it to hold one of them, and serialize?
> > 
> > 
> > Can you elaborate? I do not see any relation as of now.
> 
> Sure! I just see an high probability of conflicts, since they are touching the same file in very close location. Also, they both change the import in the same file. That's it :)

Ah, yeah, this is likely but I don't mind rebasing it one more time.

**Comment by xpivarc** [comment]
Thanks @acardace @fossedihelm . One step closer to less code :)

**Pull request merged**
