### PR TITLE
tests: remove the VM watch tests

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
The VM watch test is flaky. Again.
This test doesn't really make much sense anyway, since what it tests is `kubectl`, which is not part of KubeVirt.
This PR adds debug logs to try and figure out what's going on this time, but I would argue for removing the test entirely and avoid losing more test runs to it.

Edit: added a commit to just remove the tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
With the added logs, that test run clearly shows that the migration status never appeared in the kubectl watch: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7289/pull-kubevirt-e2e-k8s-1.23-sig-compute/1499116060723384320

Since the VMI successfully migrated, it means that kubectl watch can miss random value changes, probably because it uses some kind of polling mechanism.
That effectively invalidates the 2 tests in vm_watch_test.go.

This is 1 more argument in favor of removing those 2 tests. If there's no objection I'll repurpose this PR to do just that.

@rmohr FYI

**Comment by xpivarc** [comment]
@jean-edouard Is migration the only problem? We can use migration policies to throttle the migration and that should give enough time for the watch to propagate.

**Comment by jean-edouard** [comment]
> @jean-edouard Is migration the only problem? We can use migration policies to throttle the migration and that should give enough time for the watch to propagate.

The current flakyness is around migration yes, but it changes over time. So yes, we could tweak things, like we did so many times in the past, to try and reduce flakyness on these... But what's the point? Testing kubectl is just out-of-scope, and what we're testing (ensuring it catches every single status change), is not even something it's supposed to be capable of!

**Comment by rmohr** [comment]
> The current flakyness is around migration yes, but it changes over time. So yes, we could tweak things, like we did so many times in the past, to try and reduce flakyness on these... But what's the point? Testing kubectl is just out-of-scope, and what we're testing (ensuring it catches every single status change), is not even something it's supposed to be capable of!

Yes lets drop it! +1

Let's just ensure that we have tests left which check if set the right printable status fields on the CRD.

**Comment by jean-edouard** [comment]
> > The current flakyness is around migration yes, but it changes over time. So yes, we could tweak things, like we did so many times in the past, to try and reduce flakyness on these... But what's the point? Testing kubectl is just out-of-scope, and what we're testing (ensuring it catches every single status change), is not even something it's supposed to be capable of!
> 
> Yes lets drop it! +1
> 
> Let's just ensure that we have tests left which check if set the right printable status fields on the CRD.

Printable statuses are very well covered by unit tests in `pkg/virt-controller/watch/vm_test.go`. For example, we make sure that a VM that is currently both running and in a migration will get a printable status of "Migrating".
As far as functional tests go, there are some in `tests/vm_test.go`, but they mostly test the more "stable" statuses, like Running of CrashLoopBackOff. This is to be expected, since it's hard to catch more transitional statuses like Migrating or Stopping...
Sounds to me like the best we can do. Do you agree?

**Comment by jean-edouard** [comment]
Just pushed a commit to get rid of the tests and changed the PR title accordingly

**Review by xpivarc — CHANGES_REQUESTED** [review]
Can https://github.com/kubevirt/kubevirt/pull/7289/commits/69a70d8e2ef9b6f6215cc1fefb483fa96a596cbc be dropped?

**Comment by jean-edouard** [comment]
> Can [69a70d8](https://github.com/kubevirt/kubevirt/commit/69a70d8e2ef9b6f6215cc1fefb483fa96a596cbc) be dropped?

Yes it could, but since it produces useful logs, I thought it made sense to keep in the git history.
If for example we ever decide to revert the deletion and revisit the tests, the logs will be there.
But I know it's a long shot and I'm happy to squash out the commit if it bothers anyone :)

**Comment by xpivarc** [comment]
> > Can [69a70d8](https://github.com/kubevirt/kubevirt/commit/69a70d8e2ef9b6f6215cc1fefb483fa96a596cbc) be dropped?
> 
> Yes it could, but since it produces useful logs, I thought it made sense to keep in the git history. If for example we ever decide to revert the deletion and revisit the tests, the logs will be there. But I know it's a long shot and I'm happy to squash out the commit if it bothers anyone :)

Well, it doesn't bother me at least.
/lgtm

**Comment by jean-edouard** [comment]
Force-pushed to fix a merge conflict, no code change.
@xpivarc could you please re-lgtm?

**Review by xpivarc — APPROVED** [review]

**Comment by xpivarc** [comment]
/cherry-pick release-0.41
:crossed_fingers:

**Pull request merged**
