### PR TITLE
Test: Ensure we call MigrateStartPostCopy once

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
This PR fixes test setup and enforce we call the `MIgrateStartPostCopy` once

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
/lgtm
Not sure I understand this part of the commit message "This include fix in test setup"

**Comment by xpivarc** [comment]
/retest
@jean-edouard @vladikr 
Would you be able to approve?

**Pull request merged**
