### PR TITLE
Pick up pod affinities and preferred nod affinities on virt-launcher pods from the cluster config

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Append cluster-workload-pod affinity and cluster-workload-preferred-node
affinity to the virt-launcher pods when configured on the KubeVirt CR.

Before these fields were just ignored, since they were only
applied to virt-handler, but virt-handler is a daemonset and there these
values have no meaning.

Now all scheduling constraints which have no meaning for virt-handler
are appended to the virt-launcher pod for both, migration, as well
as starting VMs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix workload placement by picking up pod affinity and node preferred affinity. They were accidentally ignored before.
```

### CODE REVIEW

**Comment by rmohr** [comment]
@lzang, @zhuchenwang FYI

**Comment by zhuchenwang** [comment]
LGTM

**Pull request closed without merging**
