### PR TITLE
api: missing V1InterfaceBridge type

### PR DESCRIPTION
**Pull request by pkliczewski**
After python client generation using current api definition there is
type missing which makes it impossible to manage VMIs. The missing type
seems to be placeholder and it do not contain any definition. It seems
like it is not used and content for it is unknown so changing it to be
a string fixes the issue.

Fixes: https://github.com/kubevirt/client-python/issues/21
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Comment by SchSeba** [comment]
@pkliczewski I open a [PR](https://github.com/kubevirt/kubevirt/pull/1452) to fix this issue.

I am not sure if making it a string is the right way.
It is good to have a struct that handle the bridge object because in the future we may want to add optional parameter to it.

**Comment by cynepco3hahue** [comment]
@pkliczewski Does this PR still relevant or can I close it?

**Comment by booxter** [comment]
I think it makes sense to reconsider the PR despite a short-term fix for the client issue was merged already.

In the past, we assumed that we will need a lot of additional options per binding type, so we designed the API so that we pass a map of attributes as a value for the per-binding attributes. Now that we spent some time thinking about and building the API, we discovered that we may not have many of these options if at all. Which resulted in usually-empty maps as values to these attributes (`bridge: {}`; `slirp: {}`; etc.) This raises the question whether the initial decision of making these attributes map-typed is correct. I don't think so anymore.

So in this regard, I agree that this API deficiency should be fixed.

In your PR, you convert each of attributes (`bridge`, `slirp`) to string. It's not exactly clear how the value of the string is supposed to be interpreted though. If it's just a flag where a non-empty value means that the particular binding type is to be used then I don't think we need a per-type attribute in the first place. Instead, we could introduce a new attribute (perhaps called `binding` or just `type`) of string type, and allow it to accept values from the list of supported binding types (meaning, one of `slirp`, `bridge`, `direct`, ...) Then also remove `bridge` and `slirp` attributes from API schema since they are superseded by the unified `type` attribute.

What do you think?

**Comment by fabiand** [comment]
ping?

**Comment by fabiand** [comment]
ping?

**Comment by pkliczewski** [comment]
We can work with the code as it is for now.

**Pull request closed without merging**
