### PR TITLE
increase timeout for flaky test ID 3194

### PR DESCRIPTION
**Pull request by ksimon1**
**What this PR does / why we need it**:
increase timeout for flaky test ID 3194

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubevirt/kubevirt/issues/4525

**Special notes for your reviewer**:

**Release note**:

```
NONE
```
Signed-off-by: Karel Šimon <ksimon@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
> increase timeout for flaky test ID 3194

@ksimon1 any insights?

**Comment by ksimon1** [comment]
not yet. I wanted to see, if the test will fail on prow, because locally I was able to reproduce only, when ceph was not ready. And in that case in that case the increasing of timeout helped.
/hold

**Comment by rmohr** [comment]
> not yet. I wanted to see, if the test will fail on prow, because locally I was able to reproduce only, when ceph was not ready. And in that case in that case the increasing of timeout helped.

A possibly helpful tip: It may help to check the ceph logs and readiness in past CI jobs, to see if that was also in the test lanes the cause.

**Comment by ksimon1** [comment]
Closing, as the flakyness is probably caused by 
```
"waiting": {
    "reason": "ImagePullBackOff",
    "message": "Back-off pulling image \"kubevirt/cdi-uploadserver:v1.26.1\""
}
```

**Pull request closed without merging**
