### PR TITLE
Remove PSASeccompAllowsUserfaultfd

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
This feature gate was introduced in  https://github.com/kubevirt/kubevirt/pull/8649, mainly because we couldn't specify Seccomp profile for VMs. Now when we have https://github.com/kubevirt/kubevirt/pull/8917 that allows specifying Seccomp, it is better to just specify the Seccomp profile that works with VMs. Those who wish to run platform default Seccomp that blocks userfaultfd should block the post-copy option on the cluster level(Kubevirt CR and MigrationPolicies).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
This is safe to merge in the window of <0.59 release as no release contains these changes yet.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by acardace** [comment]
/approve
We should merge this asap, before the new release gets cut.

**Review by jean-edouard — APPROVED** [review]

**Pull request merged**
