### PR TITLE
Bump QEMU 8.2 and libvirt 10.0

### PR DESCRIPTION
**Pull request by nickolaev**
### What this PR does
This is an update of the versions of the RPM dependencies. Namely QEMU, libvirt and the relevant VM bios/uefi blobs.
The major part here is QEMU 8.2, which is the latest one available. It also enables a new NIC model `igb` which we'll enable for Kubevirt in a follow-up PR.

### Release note

```release-note
Updating the virt stack: 
    libvirt 10.0.0, qemu 8.2.0, seabios 1.16.3, edk2 20240214
    passt 0^20231204.gb86afe3, virtiofsd 1.10.1
```

### CODE REVIEW

**Comment by andreabolognani** [comment]
@brianmcarey thanks for the heads-up!

You're correct, see #11256 which unfortunately has been a work in progress for a long time now. We should be getting an updated libvirt package relatively shortly though, and with that (*fingers crossed*) all remaining roadblocks should have been cleared.

**Comment by nickolaev** [comment]
> @brianmcarey thanks for the heads-up!
> 
> You're correct, see #11256 which unfortunately has been a work in progress for a long time now. We should be getting an updated libvirt package relatively shortly though, and with that (_fingers crossed_) all remaining roadblocks should have been cleared.

Oh, I missed your PR. Anyway, feel free to close this one in favour of yours.

**Comment by andreabolognani** [comment]
@nickolaev I don't think I can close other people's PRs, but yeah I don't think it makes sense to have this going on at the same time. I am on top of the other PR, it's just that out ability to get it merged unfortunately depends on external factors.

**Pull request closed without merging**
