### PR TITLE
e2e,sig-net: Turn on etcd fsync

### PR DESCRIPTION
**Pull request by ormergi**
### What this PR does
Before this PR:
Following https://github.com/kubevirt/kubevirt/issues/12898 mitigation effort
we see there was some changes around etcd configurations by this KCI bump https://github.com/kubevirt/kubevirt/pull/12677  https://github.com/kubevirt/kubevirtci/pull/1266 before we saw first occurrence of the issue.

In order to eliminate this PR bits related to the issue, this PR opt-out the etcd configurations for sig-net lanes.

Before this PR: 

After this PR:

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note

```

### CODE REVIEW

**Comment by dhiller** [comment]
nit: PR description should be `e2e,sig-net: Turn **off** etcd fsync`

**Review by dhiller — COMMENTED** [review]
/approve

/hold since you might want to update PR headline

/release-note-none

**Review by brianmcarey — COMMENTED** [review]
I'm not sure if this PR makes sense as the network lanes are already running etcd in memory - https://github.com/kubevirt/project-infra/blob/c291e905fae6ec484097c3936fbf03bbbd5be5f4/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L1927C1-L1928C24

**Comment by ormergi** [comment]
@akalenyu hey I am trying to opt-out etcd fsync in sig-net, but it fails https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12944/pull-kubevirt-e2e-k8s-1.31-sig-network/1839332153196810240
Can you tell why its failing?

**Comment by ormergi** [comment]
> I'm not sure if this PR makes sense as the network lanes are already running etcd in memory - https://github.com/kubevirt/project-infra/blob/c291e905fae6ec484097c3936fbf03bbbd5be5f4/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L1927C1-L1928C24

Initially we did set etcd on memory for all sig-network, just for SR-IOV lane (since it used Kind and is known to be I/O intensive setup). 
I wasn't aware all sigs configure like this of this change https://github.com/kubevirt/project-infra/pull/2815

Note that we didnt have etcd issue back then, having etcd timeouts indicate disks are slow, workload is I/O intensive or there is some disk pressure.
Following [#](https://github.com/kubevirt/kubevirt/issues/12898), we see timeouts / deadline exceeded errors all over CI, which may indicates slowness in the cluster, in all lanes. 
Having  etcd timeouts can also indication job density is too high for CI nodes, was as there some change in that area?

**Comment by ormergi** [comment]
@dhiller flag says no-etcd-fsync, having it true means fsync is on, isn't it?

Following Brian comment, does turning off etcd-fsync has meaning if etcd runs in memory?

**Comment by dhiller** [comment]
> @dhiller flag says no-etcd-fsync, having it true means fsync is on, isn't it?
> 
> Following Brian comment, does turning off etcd-fsync has meaning if etcd runs in memory?

@ormergi according to [the PR](https://github.com/kubevirt/kubevirtci/pull/1266) setting `KUBEVIRT_NO_ETCD_FSYNC=true` tells etcd to avoid WAL and fsync operations in order to reduce IO load. @akalenyu did I misunderstand that? If not, I still think the PR description should be renamed as above.

**Comment by akalenyu** [comment]
> @akalenyu hey I am trying to opt-out etcd fsync in sig-net, but it fails https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12944/pull-kubevirt-e2e-k8s-1.31-sig-network/1839332153196810240 Can you tell why its failing?

I'll try to to take a look, weird, since I was able to test it on CDI's CI:
https://github.com/kubevirt/containerized-data-importer/pull/3440
BTW, doesn't sig-network already do etcd in memory? In that case, I am not sure how much less frequent fsyncs
would help. The main motivation for opting out of fsyncs was to replace etcd in mem

Could you share the etcd issues you're hitting with etcd in mem?



> > @dhiller flag says no-etcd-fsync, having it true means fsync is on, isn't it?
> > Following Brian comment, does turning off etcd-fsync has meaning if etcd runs in memory?
> 
> @ormergi according to [the PR](https://github.com/kubevirt/kubevirtci/pull/1266) setting `KUBEVIRT_NO_ETCD_FSYNC=true` tells etcd to avoid WAL and fsync operations in order to reduce IO load. @akalenyu did I misunderstand that? If not, I still think the PR description should be renamed as above.

You are correct

**Comment by ormergi** [comment]
Closing this PR for now because it doesnt seem to improve tests as expected.
Thank you all for the discussion
 
/close

**Pull request closed without merging**
