### PR TITLE
Quarantine high impact failure in sig storage

### PR DESCRIPTION
**Pull request by akalenyu**
This test is failing due to a bug - https://issues.redhat.com/browse/CNV-47542
and only succeeds as a fluke when the VM is stopped before the expansion could happen.
Quarantine while the issue is being worked on.

### What this PR does
Before this PR:

After this PR:

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
Does the test satisfies quarantine criteria? @brianmcarey @dhiller

**Comment by dhiller** [comment]
> Does the test satisfies quarantine criteria? @brianmcarey @dhiller

The [quarantine doc](https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md#putting-tests-in-quarantine) says

> A test must be put in quarantine when any of these conditions is met:
> 
> * It has a failure rate higher than 5% in the last two weeks.
> * It has a failure rate higher than 20% in the last 3 days.

That said, the flakyness percentage doesn't satisfy the criteria that it _must_ be put into quarantine. 

However I think if the SIG decides to work on it and reduce the flakyness by quarantining it for that time themselves, I would be fine with that. 

WDYT?

**Comment by akalenyu** [comment]
> > Does the test satisfies quarantine criteria? @brianmcarey @dhiller
> 
> The [quarantine doc](https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md#putting-tests-in-quarantine) says
> 
> > A test must be put in quarantine when any of these conditions is met:
> > 
> > * It has a failure rate higher than 5% in the last two weeks.
> > * It has a failure rate higher than 20% in the last 3 days.
> 
> That said, the flakyness percentage doesn't satisfy the criteria that it _must_ be put into quarantine.
> 
> However I think if the SIG decides to work on it and reduce the flakyness by quarantining it for that time themselves, I would be fine with that.
> 
> WDYT?

I think this is what makes the stats here looks really bad:
https://github.com/kubevirt/ci-health?tab=readme-ov-file#failures-per-sig-against-last-code-push-for-merged-prs

**Comment by dhiller** [comment]
To add up on this: search [1] says it has 4% impact over the last 14 days

[1]: https://search.ci.kubevirt.io/?search=clone+expected+phase+is+%27Succeeded%27+but+got+%27ImportInProgress%27&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by xpivarc** [comment]
@dhiller @akalenyu Thanks, I was just seeking more information, fine by me if you are already working on this and we can improve merge rate + the 4 vs 5 % is very close

**Pull request merged**
