### PR TITLE
tests: replace To(Equal(...)) to To(HaveLen(...))

### PR DESCRIPTION
**Pull request by benukhanov**
Signed-off-by: Ben Oukhanov <boukhano@redhat.com>

**What this PR does / why we need it**:

Replace `Expect(len(...)).To(Equal(...))` with `Expect(...).To(HaveLen(...))` to get a better info when it fails.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

N/A

**Special notes for your reviewer**:

N/A

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by EdDev — CHANGES_REQUESTED** [review]
Thanks.

Could you please try to limit the subject to 50 chars? I sometime pass this number if I have no choice, but never pass 72 chars.
Ref: https://cbea.ms/git-commit/#limit-50

In addition, please add the reasoning in the commit message as well.

**Comment by benukhanov** [comment]
> Thanks.
> 
> Could you please try to limit the subject to 50 chars? I sometime pass this number if I have no choice, but never pass 72 chars. Ref: https://cbea.ms/git-commit/#limit-50
> 
> In addition, please add the reasoning in the commit message as well.

Done.

**Review by EdDev — APPROVED** [review]
Thank you!

**Review by enp0s3 — APPROVED** [review]
@benukhanov Thank you!
/approve
/retest

**Pull request merged**
