### PR TITLE
Do not try to get the labels if selinux is disabled

### LINKED ISSUE #5124: VM boot failure on ubuntu
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When booting example/vmi-fedora.yaml on **ubuntu**, it failed with following error message form virt-handler
```
{"component":"virt-handler","level":"error","msg":"failed to create tap device named tap0","pos":"podinterface.go:488","reason":"could not retrieve pid 24447 selinux label: operation not supported","timestamp":"2021-03-01T09:51:09.923220Z"}
{"component":"virt-handler","level":"error","msg":"failed to prepare pod networking","pos":"podinterface.go:204","reason":"could not retrieve pid 24447 selinux label: operation not supported","timestamp":"2021-03-01T09:51:09.923333Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vmi-fedora","namespace":"default","pos":"vm.go:1435","reason":"failed to configure vmi network: Critical network error: could not retrieve pid 24447 selinux label: operation not supported","timestamp":"2021-03-01T09:51:09.923729Z","uid":"066dccd6-7db2-428e-b53e-6484192155a4"}
{"component":"virt-handler","level":"error","msg":"virt-launcher crashed due to a network error. Updating VMI vmi-fedora status to Failed","pos":"vm.go:933","timestamp":"2021-03-01T09:51:09.924296Z"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/vmi-fedora","pos":"vm.go:1043","reason":"failed to configure vmi network: Critical network error: could not retrieve pid 24447 selinux label: operation not supported","timestamp":"2021-03-01T09:51:09.956138Z"}
```

**What you expected to happen**:
VM boot successfully.

**How to reproduce it (as minimally and precisely as possible)**:
```
export KUBEVIRT_PROVIDER=kind-k8s-1.17
export KUBEVIRT_NUM_NODES=2
make cluster-up
make cluster-build
make cluster-deploy
kubectl apply -f example/vmi-fedora.yaml
kubectl logs -n kubevirt virt-handler-rhcts
```

**Anything else we need to know?**:
It seems related to the https://github.com/kubevirt/kubevirt/pull/4849/files.
Maybe because no selinux situation is not considered.

**Environment**:
- KubeVirt version: 7c366278fe76a6ec5cd8acacad7a7f3debef850e
- OS (e.g. from /etc/os-release): **Ubuntu 18.04.5 LTS**
- Kernel (e.g. `uname -a`): 5.9.0

### PR DESCRIPTION
**Pull request by vasiliy-ul**
**What this PR does / why we need it**:

Do not retrieve the labels if selinux is disabled

On the nodes which do not run selinux this will lead to errors during VM creation.

Fixes #5124

**Special notes for your reviewer**:

This is just a quick fix for the issue to unblock the ongoing tasks. Maybe not a proper solution.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vladikr** [comment]
@maiqueb Could you please take a look?
@vasiliy-ul perhaps you could a unit test for this? you could look at pkg/virt-handler/selinux/labels_test.go it may give you an idea of how to fake the `NewSelinux` function.

**Comment by vasiliy-ul** [comment]
> @vasiliy-ul perhaps you could a unit test for this? you could look at pkg/virt-handler/selinux/labels_test.go it may give you an idea of how to fake the `NewSelinux` function.

@vladikr , good point. At first I didnt look at the tests (since it was a "quick" fix :) ). Had to refactor the code a bit to decouple the dependencies. Please take a look.

**Comment by condaatje** [comment]
hoping this is a useful factoid:

anyone using (ubuntu) microk8s will have an apparmor dependency via snapd, i believe

**Comment by vladikr** [comment]
overall it looks good to me.
Let's seen that the tests pass.

**Comment by vasiliy-ul** [comment]
I checked the tests and those that failed in `k8s-1.19` lane passed in `k8s-1.18`. I think those are not related to the changes in this PR. Will try to retest at least 1.19 to ensure.

**Comment by jean-edouard** [comment]
/approve
Nit: If we don't already print some sort of warning when SELinux is disabled, maybe here would be a good idea?

**Comment by vasiliy-ul** [comment]
> Nit: If we don't already print some sort of warning when SELinux is disabled, maybe here would be a good idea?

Hm... Dont know, for me it does not seem that selinux is something mandatory. Its a normal situation when there is no selinux at all just because the node runs smth else (apparmor?). Therefore not sure if it is needed to raise a warning when its disabled... and just in case smth bad happens I think the error handling with proper messages should be enough for investigating the issue.

**Comment by vasiliy-ul** [comment]
Are there any concerns about this PR? Is there smth I can clarify or add here? Just wondering since it has an approval but no lgtm label.

**Comment by vladikr** [comment]
> Are there any concerns about this PR? Is there smth I can clarify or add here? Just wondering since it has an approval but no lgtm label.

Looks good to me. Thanks @vasiliy-ul 

/lgtm

**Comment by qinqon** [comment]
"""
/hold
until emergency CI fixes of #5207 are merged
"""

**Pull request merged**
