### PR TITLE
Assert not all tests skipped

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:
We look at the junit xml file to compare the number of tests
against the number of tests skipped and if the number of skipped tests
is not lesser then we fail.

This is to make visible situations like in this PR: #5835 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Add check that not all tests have been skipped
```

### CODE REVIEW

**Review by stu-gott — COMMENTED** [review]
I like this.

Thanks Daniel! Heads up @jean-edouard

**Comment by dhiller** [comment]
@fgimenez FYI

**Comment by dhiller** [comment]
Looks like it works as intended: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6068/pull-kubevirt-e2e-k8s-1.20-operator/1417125080781033472#1:build-log.txt%3A4862

**Review by stu-gott — COMMENTED** [review]
/approve

**Review by fgimenez — APPROVED** [review]
/lgtm

Thanks!

**Review by jean-edouard — COMMENTED** [review]
This looks good.

However, when I ran `make functest` locally last Friday when all tests were getting skipped, this was the output:
```
Ran 0 of 885 Specs in 12.383 seconds
SUCCESS! -- 0 Passed | 0 Failed | 3 Pending | 882 Skipped
```
In that case, skipped was lower than total...

Also the last time this happened about a year ago, the tests were not getting skipped, but `make functest` just always ended up returning true.

Is there any chance we could parse the output of `make functest` and fail is "Passed" is 0 or if "Failed" is non-0? That would cover both cases.

Either way, this is mergable, thank you for addressing this so quickly!!

**Comment by stu-gott** [comment]
/hold

I think we should think on Jed's suggestion before merging this. His ideas seem to have merit. What do you think @dhiller?

**Comment by dhiller** [comment]
> This looks good.
> 
> However, when I ran `make functest` locally last Friday when all tests were getting skipped, this was the output:
> 
> ```
> Ran 0 of 885 Specs in 12.383 seconds
> SUCCESS! -- 0 Passed | 0 Failed | 3 Pending | 882 Skipped
> ```
> 
> In that case, skipped was lower than total...
> 
> Also the last time this happened about a year ago, the tests were not getting skipped, but `make functest` just always ended up returning true.
> 
> Is there any chance we could parse the output of `make functest` and fail is "Passed" is 0 or if "Failed" is non-0? That would cover both cases.
> 
> Either way, this is mergable, thank you for addressing this so quickly!!

Good point, will look into that! Thanks!

**Comment by dhiller** [comment]
> > This looks good.
> > However, when I ran `make functest` locally last Friday when all tests were getting skipped, this was the output:
> > ```
> > Ran 0 of 885 Specs in 12.383 seconds
> > SUCCESS! -- 0 Passed | 0 Failed | 3 Pending | 882 Skipped
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In that case, skipped was lower than total...
> > Also the last time this happened about a year ago, the tests were not getting skipped, but `make functest` just always ended up returning true.
> > Is there any chance we could parse the output of `make functest` and fail is "Passed" is 0 or if "Failed" is non-0? That would cover both cases.
> > Either way, this is mergable, thank you for addressing this so quickly!!
> 
> Good point, will look into that! Thanks!

I've looked into the xml files of two examples where there have been pending test cases:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6039/pull-kubevirt-e2e-k8s-1.18-0.41/1417058011150553088
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6039/pull-kubevirt-e2e-k8s-1.18-0.41/1416852068211101696

The resulting junit xml files show no indication that the pending cases are taken into account as separate pending state cases. I figure this is because on the CI the tests are run in two phases (parallel - serial) and then the result is a merged file of the original junit test files. So I think for CI we should be good enough. 

However, while I haven't looked at what happens when the file is generated locally without parallel execution, I have looked at the code here: https://github.com/onsi/ginkgo/blob/66d7597cc0e5eccd35590d61fdf27845aa492cd0/reporters/junit_reporter.go#L126
This seems to indicate that tests with state pending and skipped are treated equally as skipped.

**Pull request merged**
