### PR TITLE
Update builder image to latest version

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:
Updates the builder image to latest version.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
awesome thanks

**Comment by oshoval** [comment]
/lgtm cancel

(draft still)

**Review by oshoval — APPROVED** [review]
Thanks Daniel

**Comment by dhiller** [comment]
Retesting to check whether #7410 fixed the failing test_id:2666

/retest

**Pull request merged**
