### PR TITLE
tests: move GetCertFromSecret()

### PR DESCRIPTION
**Pull request by codingben**
### What this PR does

Move GetCertFromSecret() out of utils
to the only place where it is used.

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
You need to run `make format`, to update the Bazel files.

**Comment by codingben** [comment]
> You need to run `make format`, to update the Bazel files.

Yeah I need to prepare environment for it. I'm using GitHub Codespaces (Web's IDE) after my account was blocked by GitHub Staff, and they don't provide high-memory VMs for it.

**Review by dankenigsberg — APPROVED** [review]

**Pull request merged**
