### PR TITLE
Give up if migration monitor loop after multiple stat failures

### PR DESCRIPTION
**Pull request by davidvossel**
Previously it looks like we silently fail monitoring the migration under a theoretical failure to retrieve the job stats.  Since the monitor loop reports success/failure, it's unclear if the migration will ever be marked complete if this scenario is encountered.

This pr ensures we eventually break out of the monitor loop if this failure condition is encountered multiple times. 

```release-note
NONE
```

### CODE REVIEW

**Comment by davidvossel** [comment]
@vladikr This caught my eye in another review. Do you think it's necessary?

**Comment by vladikr** [comment]
> @vladikr This caught my eye in another review. Do you think it's necessary?

I'm pretty confident that `MigrateToURI3` will fail in this case and will close the monitor loop with #2200 
Unless getJobInfo fails first... but then if there is no connection to libvirt (as I understand that there is no connection to libvirt in this case), `setMigrationResult` will fail to set the status... so not sure how can we improve this.

**Comment by davidvossel** [comment]
> but then if there is no connection to libvirt (as I understand that there is no connection to libvirt in this case), setMigrationResult will fail to set the status... so not sure how can we improve this

yeah good point. I'm not sure this PR helps anything. I just feel uneasy about there being an exit path from the monitor loop that doesn't attempt to report the result.

**Comment by fromanirh** [comment]
I think @vladikr is right from past experience with vdsm/oVirt. The documentation doesn't state this, but in practice migrateToURI3 (on qemu, the only case we care about) will either:
- exit with error, in which case there will be no job to query for
- exit succesfully only after having complete the handshake between the source and dest QEMUs, so with data transfer in progress - and we can query the status using jobInfo

So this PR should not really be needed granted that we call GetJobInfo only after MigrateToURI3 succesfully returned

As sidenote - and ofc NOT related to this PR, I'm not really clear why we need the migrationErr chan.
But again, not related to this PR.

**Comment by fromanirh** [comment]
> > but then if there is no connection to libvirt (as I understand that there is no connection to libvirt in this case), setMigrationResult will fail to set the status... so not sure how can we improve this
> 
> yeah good point. I'm not sure this PR helps anything. I just feel uneasy about there being an exit path from the monitor loop that doesn't attempt to report the result.

I think @vladikr is right from past experience with vdsm/oVirt. The documentation doesn't state this, but in practice migrateToURI3 (on qemu, the only case we care about) will either:
- exit with error, in which case there will be no job to query for
- exit succesfully only after having complete the handshake between the source and dest QEMUs, so with data transfer in progress - and we can query the status using jobInfo

So this PR should not really be needed granted that we call GetJobInfo only after MigrateToURI3 succesfully returned

As sidenote - and ofc NOT related to this PR, I'm not really clear why we need the migrationErr chan.
But again, not related to this PR.

**Comment by davidvossel** [comment]
@vladikr @fromanirh thanks for the feedback. I'm going to close the PR for now.

**Pull request closed without merging**
