### PR TITLE
Revert to pre-device-plugins behavior for Kubernetes 1.9 and earlier

### PR DESCRIPTION
**Pull request by stu-gott**
fixes https://github.com/kubevirt/kubevirt/issues/1185

### CODE REVIEW

**Comment by stu-gott** [comment]
@vladikr Discussions on the mailing list indicated 1.9.X is a critical path in CI. I think that's already well tested?

**Comment by davidvossel** [comment]
The patch looks good.

I suggest letting the discussion on the mailing list play out a bit further before merging. If we can get away with it, I'd rather we drop 1.9/3.9 support.

**Comment by stu-gott** [comment]
I believe the general consensus is that we are not going to maintain compatibility with Kubernetes 1.9. If that's the case, this PR should be closed as it is exclusively about maintaining functionality in older versions.

**Comment by cynepco3hahue** [comment]
@stu-gott I think you can close it now.

**Pull request closed without merging**
