### PR TITLE
Remove jinja2 leftovers in the release script

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Since #5738  we don't generate templates anymore. Some leftovers make the release script fail.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — COMMENTED** [review]
/approve

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
