### PR TITLE
Implemented PodAffinity and PodAntiAffinity

### LINKED ISSUE #1101: Support podAffinity
The guide indicates that VMs support `podAffinity` (see http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/assigning-vms-to-nodes?id=affinity-and-anti-affinity).

But the api-reference tells otherwise, as `v1.Affinity` only lists `nodeAffinity`.

Either code is missing, or some annotations are wrong.

### LINKED ISSUE #1127: Support podAntiAffinity
The guide indicates that VMs support podAffinity (see http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/assigning-vms-to-nodes?id=affinity-and-anti-affinity).

podAffinity will land soon.

But for consistency it would be good so support podAntiAffinity as well.

### PR DESCRIPTION
**Pull request by slintes**
Fixes #1101, fixes #1127

Signed-off-by: Marc Sluiter <marc@slintes.net>

### CODE REVIEW

**Comment by fabiand** [comment]
Wrt 2. - +1 for having it, but let's tackle it in a separate PR.

therwise we get these endless ones which also become harder to review.

**Comment by davidvossel** [comment]
Wrt 2. - +1 for having it, but let's tackle it in a separate PR.

in this case, since the functional tests are fairly involved I think that makes sense to follow up within a separate PR.

**Comment by slintes** [comment]
@fabiand I'm confused about "wrt 2", because "2" was about function test. Should podAntiAffinity be handled in a separate PR like we discussed, or also function tests?

**Comment by fabiand** [comment]
Sorry for the consusion I meant "wrt 1." (podAntiAffinity)

**Comment by davidvossel** [comment]
> Sorry for the consusion I meant "wrt 1." (podAntiAffinity)

why? it's a simple addition. Just add the antiaffinity struct, run make generate, and add the unit test case.

**Comment by fabiand** [comment]
The only reason is just to not add features to a running PR.

We often just "add that other bit".
Even here it is "not much" on the feature side, but writing the functional tests will take it's time again.

It might be frustrating to have a mergeable PR butthen change the requirements in flight.

So, in oder to be able to close up with some work it might not be an issue to just split it.

Also: That will be two positive PRs instead of one. Come one, that's a win! :)

**Comment by davidvossel** [comment]
> The only reason is just to not add features to a running PR.

This PR is for half a feature. The feature is called the pod "affinity/anti-affinity" feature in k8s. https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity

>It might be frustrating to have a mergeable PR butthen change the requirements in flight.
So, in oder to be able to close up with some work it might not be an issue to just split it.
Also: That will be two positive PRs instead of one. Come one, that's a win! :)

Yeah, I understand the frustration.  I think we scoped the feature wrong in this case. It's not a big deal to split this up into two PRs if that helps though.

**Comment by fabiand** [comment]
> wrt func test: when I run 2 nodes, and check if 2 VMs are scheduled correctly according to node/pod anti-/affinity... how do I know that is wasn't coincidence? Run the same test several times? Feels strange... but I have no better idea yet

That's a really cool challenge!

But as you noted: We can probably rely that k8s does the right thing, if we do our job and put the affinity on the pod.

**Comment by slintes** [comment]
Fixes #1127

**Comment by fabiand** [comment]
> Fixes #1127

This should go into the merge/commit message

**Comment by davidvossel** [comment]
> edit: and tbh it feels like we would test a basic k8s feature with it.... do we want that? The unit test ensures already that affinity is added to the pod, the scheduling is not our business anymore imho

@slintes I think you're right. We'll depend on k8s doing the right thing scheduling wise.

We still need a functional test to verify we aren't somehow breaking the start flow when people use affinity/anti-affinity rules though.

How about a super simple function test that just sets pod affinity/anti-affinity rules on a VM and ensures that the VM can start.  This could be a test case added to tests/vmlifecycle_test.go file

@fabiand does that sound reasonable to you?

**Comment by fabiand** [comment]
Yes, @davidvossel, having a simple test to ensure that the real basics work sounds sane.

Somethign to add to `tests/README.md` "When to add a func test"

**Comment by rmohr** [comment]
Regarding the test, it should be extremely simple to test this in combination with a node selector.  Select for both vms the same node and check that only one gets scheduled (another chance to pull the pod scheduled condition to the vm to also inform the user, since you will see on that condition that it can't be scheduled ). Then remove the anti affinity and it should get scheduled. You can do the same game the other way round to test affinity.

**Comment by fabiand** [comment]
Nifty.

**Pull request merged**
