### PR TITLE
[release-0.58]: Bugfix: virt-handler socket leak

### PR DESCRIPTION
**Pull request by iholder101**
**What this PR does / why we need it**:
Manual backport for https://github.com/kubevirt/kubevirt/pull/8948.

**Special notes for your reviewer**:
The only interesting reason for a backport is the following commit: https://github.com/kubevirt/kubevirt/pull/9002/commits/49dd3c510ad2ae8e475443e156a6b9fb5951202e. In the [original PR](https://github.com/kubevirt/kubevirt/pull/8948) I was using a matcher (`matcher.HaveConditionTrue()`) that doesn't exist in this branch. Therefore, I'm manually checking the condition instead.

**Release note**:

```release-note
Bugfix: virt-handler socket leak
```

### CODE REVIEW

**Comment by iholder101** [comment]
/cc @enp0s3 @Barakmor1 

Would appreciate your review :)

**Comment by iholder101** [comment]
/hold

Blocked by https://github.com/kubevirt/kubevirt/pull/9004.

**Review by enp0s3 — COMMENTED** [review]
/approve

**Pull request merged**
