### PR TITLE
[release-0.41] Improve non-root path handling

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
Manual cherry-pick of #8198 and #8268

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
2 commits have been added to revert most of the changes to the hotplug-disk code. Too much of it relies on relative paths and symlinks...

**Release note**:

```release-note
Improve path handling for non-root virt-launcher workloads
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
/hold
The commits are not ready yet, just want to see how broken the tests are.

**Comment by jean-edouard** [comment]
/hold cancel
Finally un-broke hotplug-disk and container-disk

**Comment by jean-edouard** [comment]
Both network lanes are failing only on a well known flaky test that may never succeed. Probably needs overrides.

**Review by stu-gott — COMMENTED** [review]
/approve

**Pull request merged**
