### PR TITLE
Remove leftover NonRootExperimental feature gate

### PR DESCRIPTION
**Pull request by orelmisan**
**What this PR does / why we need it**:
The NonRootExperimental feature gate was deprecated in PR #8563.

The presence or absence of this feature gate does not change KubeVirt's behavior.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [X] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [X] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
Remove leftover NonRootExperimental feature gate
```

### CODE REVIEW

**Review by EdDev — APPROVED** [review]
Thanks.

I think you need to elaborate in the commit and PR description that this has no API effect. It is basically a leftover, not really an "unused" FG.

Remove a FG from the API itself is problematic or at the minimum questionable.

**Comment by orelmisan** [comment]
> Thanks.
> 
> I think you need to elaborate in the commit and PR description that this has no API effect. It is basically a leftover, not really an "unused" FG.

Changed commit message, PR title and PR description.

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/5ce20e1bf5e29b2f6e2bfc1c3898e0057b741b18..a890070d969073add4a302ae3d3f705de55a6259): Updated commit message to answer review [comment](https://github.com/kubevirt/kubevirt/pull/10582#pullrequestreview-1682690039).

**Review by EdDev — APPROVED** [review]

**Comment by orelmisan** [comment]
> FYI [#10615 (comment)](https://github.com/kubevirt/kubevirt/pull/10615#discussion_r1368742173)

Thank you @fossedihelm, I'll remove it in a follow-up to this PR.

**Comment by EdDev** [comment]
Similar to https://github.com/kubevirt/kubevirt/pull/10615 , I think this change may be problematic and collides with the FG deprecation policy.

**Comment by xpivarc** [comment]
> Similar to #10615 , I think this change may be problematic and collides with the FG deprecation policy. (I admit I did not see it when reviewing this originally, the other PR is big enough to make some bells ring. Sorry :/)

This one is experimental in nature and name as well. I think we are good here but I agree with you about the #10615

**Comment by EdDev** [comment]
> This one is experimental in nature and name as well. I think we are good here but I agree with you about the #10615

I understand. The problem is that we do not have such a classification of what is "experimental" and what it not.
One could consider any FG as experimental (basically it is), as once something is exposed it has the potential to be used and depend on.
Such cases should be added to the policy to cover and clarify the rules.

**Pull request merged**
