### PR TITLE
Nominate 0xFelix for sig-compute approver

### PR DESCRIPTION
**Pull request by acardace**
### What this PR does
Nominating @0xFelix for SIG compute approver

Felix has been contributing to Kubevirt for more than 2 years, he is a very active member of the community contributing both with code and reviews. 

He contributed  100+ PRs https://github.com/kubevirt/kubevirt/pulls?q=is%3Amerged+is%3Apr+author%3A0xFelix, his main contributions were in core KubeVirt, instance types and virtctl, he also helped the project making big strides in having more reliable and maintainable tests.

He reviewed ~ 350 PRs https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+commenter%3A0xFelix+is%3Aclosed+-author%3A0xFelix.

I think @0xFelix deserves to be a sig-compute approvers given the number and the importance of his contributions, also this will help the project grow as Felix does a great job in reviewing a lot of PRs and by having him as an approver will enable us to review and merge code faster.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by enp0s3** [comment]
@0xFelix Thank you for volunteering! 
/approve
/hold

**Comment by lyarwood** [comment]
@0xFelix has been a constant source of detailed reviews for the majority of my time on the project and his initiative around improving some of the more awkward parts of the codebase (yeah I'm looking at you `virtctl`) is to be commended. 

While I'm not a top level `sig-compute` approver I wholeheartedly agree with this change.

/lgtm

**Review by vasiliy-ul — APPROVED** [review]

**Comment by iholder101** [comment]
Thank you @0xFelix and good luck!
/lgtm

**Comment by Barakmor1** [comment]
Good Luck!
/lgtm

**Review by lyarwood — CHANGES_REQUESTED** [review]
@acardace can you rebase this?

**Comment by acardace** [comment]
/unhold

I've rebased it and I also think we can unhold.

**Pull request merged**
