### PR TITLE
Add help text to the phase transition time metrics

### PR DESCRIPTION
**Pull request by sradco**
**What this PR does / why we need it**:
It adds a help text to the VMI phase transition time metrics.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2196257

**Special notes for your reviewer**:
The metrics are histograms.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sradco** [comment]
@machadovilaca  Please review as well

**Comment by sradco** [comment]
@alicefr @maiqueb Please review

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
