### PR TITLE
Make cirros and alpine ready for q35

### PR DESCRIPTION
**Pull request by rmohr**
* Use e1000 as default interface
* Update to cirros 4.0
* Update to alpine 3.7

Signed-off-by: Roman Mohr <rmohr@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by davidvossel** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Pull request merged**
