### PR TITLE
CONTRIBUTING: Spelling fix, propoals -> proposals

### PR DESCRIPTION
**Pull request by EdDev**
Just a small spelling fix in CONTRIBUTING.md.

### CODE REVIEW

**Comment by rmohr** [comment]
> /release-note-none

FYI, you can also write into the `release-note` block a `NONE`. That is the preferred way.

**Comment by EdDev** [comment]
> FYI, you can also write into the `release-note` block a `NONE`. That is the preferred way.

Thanks, I will try it next time!

**Pull request merged**
