### PR TITLE
Migrate to the specified node

### PR DESCRIPTION
**Pull request by liuminjian**
**What this PR does / why we need it**:

I want to migrate the virtual machine to the specified node，so i added a field to VirtualMachineInstanceMigration.

**Special notes for your reviewer**:

**Release note**:

```release-note
migrate the virtual machine to the specified node
```

### CODE REVIEW

**Comment by liuminjian** [comment]
In some cases, some nodes in my cluster need to upgrade hardware, and some nodes do not need to be upgraded, so I need to migrate the virtual machine to the node that does not need to be upgraded, and then migrate the virtual machine back after the hardware upgrade is successful.

**Comment by rmohr** [comment]
> In some cases, some nodes in my cluster need to upgrade hardware, and some nodes do not need to be upgraded, so I need to migrate the virtual machine to the node that does not need to be upgraded, and then migrate the virtual machine back after the hardware upgrade is successful.

This sounds to me like you want to achieve one of two things:

 1. Ensure that no new workloads are added to a node until it is empty so that you can upgrade it, or
 2. you want to not only avoid new workloads on the node but also effectively drain it to start with the update on the node asap

Here is the recommended way how to best integrate kubevirt in the core kubernetes node maintenance patterns: https://kubevirt.io/user-guide/operations/node_maintenance/#node-maintenance.

They normally make selecting target nodes unnecessary.

If you then also think about rebalancing workloads periodically, you can also have a look at the descheduler: https://github.com/kubernetes-sigs/descheduler.

Would that be sufficient, or do you still think that you need manual intervention for migration targets?

**Comment by rmohr** [comment]
And I just see that the documentation is outdated. It still claims that to migrate away with a migration one needs custom kubevirt taints on the node. That is no longer true. Simple `kubectl drain` commands will trigger the right behaviour (shutdown or migration).

**Comment by davidvossel** [comment]
> In some cases, some nodes in my cluster need to upgrade, and some nodes do not need to be upgraded, so I need to migrate the virtual machine to the node that does not need to be upgraded, and then migrate the virtual machine back after the hardware upgrade is successful.

Roman's feedback is a great resource.  I just wanted to note that if you just want to limit what nodes a VMI can migrate to, put a node selector on the VMI and that will limit where the VMI can migrate to.

**Comment by liuminjian** [comment]
> > In some cases, some nodes in my cluster need to upgrade, and some nodes do not need to be upgraded, so I need to migrate the virtual machine to the node that does not need to be upgraded, and then migrate the virtual machine back after the hardware upgrade is successful.
> 
> Roman's feedback is a great resource. I just wanted to note that if you just want to limit what nodes a VMI can migrate to, put a node selector on the VMI and that will limit where the VMI can migrate to.

This is a good idea thanks

**Comment by rmohr** [comment]
@liuminjian do you still think that you need this feature or should the PR be closed?

**Comment by liuminjian** [comment]
> @liuminjian do you still think that you need this feature or should the PR be closed?
closed，thanks

**Comment by liuminjian** [comment]
sorry，i still need this feature. VMI is forbidden to modify content by virtualmachineinstances-update-validator. i want  limit where the VMI can migrate to.

**Comment by davidvossel** [comment]
> @rmohr sorry，i still need this feature. vmi is forbidden to modify content by virtualmachineinstances-update-validator. i want to specify which node to migrate the vm.

interesting. I'd consider making the affinity and nodeSelector portions of the VMI mutable in order to satisfy this use case. We'd essentially be saying that a VMI's affinity rules can change due to the fact that VMIs are portable (live migratable), and the location active VMIs run on may need to change in the future. 

This would allow someone to dynamically influence where a VMI can run after the point a VMI is created.

@rmohr what do you think?

**Comment by rmohr** [comment]
> > @rmohr sorry，i still need this feature. vmi is forbidden to modify content by virtualmachineinstances-update-validator. i want to specify which node to migrate the vm.
> 
> interesting. I'd consider making the affinity and nodeSelector portions of the VMI mutable in order to satisfy this use case. We'd essentially be saying that a VMI's affinity rules can change due to the fact that VMIs are portable (live migratable), and the location active VMIs run on may need to change in the future.
> 
> This would allow someone to dynamically influence where a VMI can run after the point a VMI is created.
> 
> @rmohr what do you think?

Two things: 

 1. I can understand that sometimes one administers oneself into the situation that it may be beneficial to be able to re-arrange the cluster layout without VM restarts. So in general makes sense to me to make it adjustable. So +1 on making it changeable.
 2. @liuminjian this still looks to me like you have flows in your mind which seem to required targeted migrations. Could you please explain why you need that and why the scheduler can't do the best choices for you based on the patterns which I shared earlier? I just want to avoid that you invest into a pattern where you are then permanently competing with the k8s scheduler because migrations start to fail due to various resources constraints on the single target node.

**Comment by liuminjian** [comment]
> > > @rmohr sorry，i still need this feature. vmi is forbidden to modify content by virtualmachineinstances-update-validator. i want to specify which node to migrate the vm.
> > 
> > 
> > interesting. I'd consider making the affinity and nodeSelector portions of the VMI mutable in order to satisfy this use case. We'd essentially be saying that a VMI's affinity rules can change due to the fact that VMIs are portable (live migratable), and the location active VMIs run on may need to change in the future.
> > This would allow someone to dynamically influence where a VMI can run after the point a VMI is created.
> > @rmohr what do you think?
> 
> Two things:
> 
> 1. I can understand that sometimes one administers oneself into the situation that it may be beneficial to be able to re-arrange the cluster layout without VM restarts. So in general makes sense to me to make it adjustable. So +1 on making it changeable.
> 2. @liuminjian this still looks to me like you have flows in your mind which seem to required targeted migrations. Could you please explain why you need that and why the scheduler can't do the best choices for you based on the patterns which I shared earlier? I just want to avoid that you invest into a pattern where you are then permanently competing with the k8s scheduler because migrations start to fail due to various resources constraints on the single target node.

I am working on a project to provide users with virtual machines. The virtual machine created by the user must be able to be scheduled and run normally. So this project will automatically calculate whether there are enough resources for workload scheduling. I will record the inventory of each node's resources for calculation, including network bandwidth, disk io, etc. If the node resources are insufficient, I will restrict users from creating virtual machines, which is not possible with the k8s scheduler.

**Comment by davidvossel** [comment]
> I am working on a project to provide users with virtual machines. The virtual machine created by the user must be able to be scheduled and run normally. So this project will automatically calculate whether there are enough resources for workload scheduling. I will record the inventory of each node's resources for calculation, including network bandwidth, disk io, etc. If the node resources are insufficient, I will restrict users from creating virtual machines, which is not possible with the k8s scheduler.

If we make the VMI's affinity rules mutable in order to influence where a VMI is capable of migrating to, will this satisfy your use case?

**Comment by liuminjian** [comment]
> > I am working on a project to provide users with virtual machines. The virtual machine created by the user must be able to be scheduled and run normally. So this project will automatically calculate whether there are enough resources for workload scheduling. I will record the inventory of each node's resources for calculation, including network bandwidth, disk io, etc. If the node resources are insufficient, I will restrict users from creating virtual machines, which is not possible with the k8s scheduler.
> 
> If we make the VMI's affinity rules mutable in order to influence where a VMI is capable of migrating to, will this satisfy your use case?

yes，it will work for me

**Comment by davidvossel** [comment]
@liuminjian  If this is something you are interested in contributing, the code that impacts whether or not the VMI spec can be mutated is found in here ```pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go``` in the Admit() function.

The change here would be to allow the affinity rules on the VMI to mutate. So when performing the old and new vmi,  you could do something like this

```
oldVMICopy := oldVMI.DeepCopy

// copy over fields we allow to mutate
oldVMICopy.Spec.Affinity = newVMI.Spec.Affinity

// if something we don't allow to mutate changes, that's invalid.
if !reflect.DeepEqual(newVMI.Spec, oldVMCopy.Spec)
// Something changed
}
```

**Pull request closed without merging**
