### PR TITLE
Use new tag based release from kubevirtci

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

Needs https://github.com/kubevirt/project-infra/pull/670 merged. Until then 1.16 will fail.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

Requires https://github.com/kubevirt/project-infra/pull/670 to be merged.

/cc @jean-edouard 
/cc @qinqon 
/cc @dhiller
/cc @danielBelenky

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Review by jean-edouard — APPROVED** [review]

**Pull request merged**
