### PR TITLE
Allow -nonroot to be used as target

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by fgimenez — COMMENTED** [review]
/lgtm

**Comment by rmohr** [comment]
@xpivarc could we solve this with an extra variable which we define on the jobs? All the overloaded meaing of the target is kind of hard to do right.

**Comment by xpivarc** [comment]
> @xpivarc could we solve this with an extra variable which we define on the jobs? All the overloaded meaing of the target is kind of hard to do right.

Works for me

**Pull request closed without merging**
