### PR TITLE
VM admitter: rejects updates to datavolumetemplates

### PR DESCRIPTION
**Pull request by ShellyKa13**
After VM and DVs are created we should not allow to change anything in the datavolumetemplates. This can result in undesirable behavior.

Fixes # Jira-ticket: https://issues.redhat.com/browse/CNV-49865

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by akalenyu — COMMENTED** [review]
CEL could work here instead of us enforcing it on the webhook:
https://kubernetes.io/blog/2022/09/29/enforce-immutability-using-cel/#immutablility-after-first-modification
But I also recall some pushback on it.. IIRC @nunnatsa was involved

**Comment by akalenyu** [comment]
Oh.. slight problem. The dataVolumeTemplates section is mutable for volume migration:
https://kubevirt.io/user-guide/storage/volume_migration/

**Comment by ShellyKa13** [comment]
you are right, forgot about this.. I'll close to reevaluate if there is anything that can be done differently

**Comment by alicefr** [comment]
@ShellyKa13 in general all the vm spec is mutable. In particularly, we need to change the datavolume template section because it requires to have the dv referenced in that section present in the volumes section. So, it isn't strictly needed by volume migration but rather volume migration has the issue that we need to be able to adapt to the change of the volume set.

**Pull request closed without merging**
