### PR TITLE
[release-1.2][BUGFIX] Fix restore panic in case of volumesnapshot missing

### PR DESCRIPTION
**Pull request by ShellyKa13**
This is a manual cherry-pick of PR: https://github.com/kubevirt/kubevirt/pull/11996

### Release note

```release-note
BugFix: Fix restore panic in case of volumesnapshot missing
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm

Thanks!

**Comment by dhiller** [comment]
/override pull-kubevirt-goveralls
/override pull-kubevirt-e2e-k8s-1.29-sig-operator

Overridden due to known instabilities

/unhold

**Pull request merged**
