### PR TITLE
test.sh: use flock instead of a spinlock

### PR DESCRIPTION
**Pull request by danielBelenky**
Instead of using a spinlock, which might leave the lock behind if the
process was killed with SIGKILL, we will use flock which releases the
lock as soon as the process dies.

It's needed now because we're planning to abort tests on a specific PR
when the PR is being updated, the abort is not guaranteed to be
graceful.

Signed-off-by: Daniel Belenky <dbelenky@redhat.com>

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by slintes** [comment]
ci test please

**Comment by rmohr** [comment]
Good to see that aborting PR runs will come.

**Pull request merged**
