### PR TITLE
kernel boot tests flakieness: set new record properly

### PR DESCRIPTION
**Pull request by iholder101**
Signed-off-by: Itamar Holder <iholder@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by iholder-redhat** [comment]
All tests passed. Trying again:
/test pull-kubevirt-e2e-k8s-1.22-sig-compute
/test pull-kubevirt-e2e-k8s-1.23-sig-compute
/test pull-kubevirt-e2e-k8s-1.24-sig-compute

**Comment by iholder-redhat** [comment]
All tests passed. Trying again:
/test pull-kubevirt-e2e-k8s-1.22-sig-compute
/test pull-kubevirt-e2e-k8s-1.23-sig-compute
/test pull-kubevirt-e2e-k8s-1.24-sig-compute

**Comment by iholder101** [comment]
fixed by @alicefr in https://github.com/kubevirt/kubevirt/pull/8492. Thank you!
/close

**Pull request closed without merging**
