### PR TITLE
instancetype: Move revision name to vm status

### LINKED ISSUE #10145: Stop patching `vm.spec.{instancetype,preference}.revisionName` and instead update `vm.status`
/area instancetype
/cc @rmohr 

**What happened**:

At present the `VirtualMachine` controller will directly patch `vm.spec.{instancetype,preference}.revisionName` when a new `ControllerRevision` is captured for the associated resource. By doing this we potentially break declarative management systems who expect the core spec of the `VirtualMachine` to not change post admission. For more on this particular topic see the following sig-architecture document:

https://github.com/kubernetes/community/blob/f88bbbabe89e01bd8f436c339128154e4032d0d5/contributors/devel/sig-architecture/api-conventions.md#spec-and-status

If possible we should stop patching `vm.spec.{instancetype,preference}.revisionName` and instead hold this information somewhere under  `vm.status`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype

**What this PR does / why we need it**:

Previoiusly the `VirtualMachine` controller would directly patch `vm.spec.{instancetype,preference}.revisionName` when a new `ControllerRevision` is captured for the associated resource. By doing this we potentially break declarative management systems who expect the core spec of the `VirtualMachine` to not change post admission. For more on this particular topic see the following `sig-architecture` document:

https://github.com/kubernetes/community/blob/f88bbbabe89e01bd8f436c339128154e4032d0d5/contributors/devel/sig-architecture/api-conventions.md#spec-and-status

This change introduces new `{instancetype,preference}Status` fields to the `VirtualMachineStatus` that will be patched with the `revisionName` going forward. The original `{instancetype,preference}Matcher` `revisionName` field is deprecated ahead of removal in a future release.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10145

**Special notes for your reviewer**:

**Release note**:

```release-note
The `vm.{instancetype,preference}.revisionName` field is now deprecated, previous users should now use `vm.status.{instancetype,preference}Status.revisionName`.
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
Can you restore a VM with just the `InstancetypeStatus` / `PreferenceStatus` containing a `RevisionName` so that is using the specified revision again? Is the status writable by a user at all?

**Comment by lyarwood** [comment]
> Can you restore a VM with just the `InstancetypeStatus` / `PreferenceStatus` containing a `RevisionName` so that is using the specified revision again? Is the status writable by a user at all?

https://github.com/kubevirt/kubevirt/blob/267fdf7dce3aba5dbbb7f56a82b563f66773f862/pkg/virt-operator/resource/generate/rbac/apiserver.go#L115-L125

Yeah it looks like only the cluster role can patch through the API so this will have to be a subresource API?

`virtualmachines/modify-instancetype` or `virtualmachines/clear-instancetye-revisionName`?

**Comment by 0xFelix** [comment]
I'm still not convinced we should put the revision names into the status of a VM.

The spec is the desired state of a VM (including using a revision I might desire as a user), while the status describes the current state of a VM including only information which can be reconstructed from the live state of the VM. (see [[1]](https://kubernetes.io/docs/concepts/overview/working-with-objects/#object-spec-and-status) and [[2]](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status)).

The Kubernetes API spec specifically demands updates to an object (PUT / POST) to ignore changes to the status, so I don't think we should introduce a workaround to write to it. (see [[2]](https://cluster-api.sigs.k8s.io/developer/providers/implementers-guide/controllers_and_reconciliation.html#a-note-about-the-status)).

See also the [Cluster API book](https://cluster-api.sigs.k8s.io/developer/providers/implementers-guide/controllers_and_reconciliation.html#a-note-about-the-status):

> Anything that can’t be recreated, either with some sort of deterministic generation method or by querying/observing actual state, needs to be in Spec.

**Comment by 0xFelix** [comment]
@rmohr @davidvossel @vladikr @xpivarc @iholder101 Do you have an opinion on this?

**Comment by lyarwood** [comment]
/hold

I've rebased the series locally but this is going to be blocked by the current online snapshot behaviour only capturing the spec *and* capturing the original VM at launch for running VMs. I'll write this up as a bug as it's breaking snapshots after liveupdates  as well.

**Comment by lyarwood** [comment]
/remove-lifecycle rotten

Working on this again for 1.4, see https://github.com/kubevirt/community/pull/317 for more on the approach before this series is refreshed.

**Pull request closed without merging**
