### PR TITLE
Sig-storage ownership

### PR DESCRIPTION
**Pull request by alicefr**
### What this PR does
Add sig-storage ownership to additional paths and add alicefr in the sig-storage approvers.

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by alicefr** [comment]
@mhenriks , I created this PR as we discussed with @fabiand and add my self as approver for the group. Please, let me know if it is fine for you.

**Comment by fabiand** [comment]
LGTM!

Please undraft

**Comment by dankenigsberg** [comment]
It looks like the phased plugin missed this PR, too - cc @oshoval @brianmcarey 

/test pull-kubevirt-e2e-windows2016
/test pull-kubevirt-e2e-kind-1.27-vgpu
/test pull-kubevirt-e2e-kind-sriov
/test pull-kubevirt-e2e-k8s-1.29-ipv6-sig-network
/test pull-kubevirt-e2e-k8s-1.27-sig-network
/test pull-kubevirt-e2e-k8s-1.27-sig-storage
/test pull-kubevirt-e2e-k8s-1.27-sig-compute
/test pull-kubevirt-e2e-k8s-1.27-sig-operator
/test pull-kubevirt-e2e-k8s-1.28-sig-network
/test pull-kubevirt-e2e-k8s-1.28-sig-storage
/test pull-kubevirt-e2e-k8s-1.28-sig-compute
/test pull-kubevirt-e2e-k8s-1.28-sig-operator

**Comment by oshoval** [comment]
> It looks like the phased plugin missed this PR, too - cc @oshoval @brianmcarey
> 
> /test pull-kubevirt-e2e-windows2016 /test pull-kubevirt-e2e-kind-1.27-vgpu /test pull-kubevirt-e2e-kind-sriov /test pull-kubevirt-e2e-k8s-1.29-ipv6-sig-network /test pull-kubevirt-e2e-k8s-1.27-sig-network /test pull-kubevirt-e2e-k8s-1.27-sig-storage /test pull-kubevirt-e2e-k8s-1.27-sig-compute /test pull-kubevirt-e2e-k8s-1.27-sig-operator /test pull-kubevirt-e2e-k8s-1.28-sig-network /test pull-kubevirt-e2e-k8s-1.28-sig-storage /test pull-kubevirt-e2e-k8s-1.28-sig-compute /test pull-kubevirt-e2e-k8s-1.28-sig-operator

Thanks, but there is no reason to trigger it, tide should run it eventually
once we have time we can debug it deeper

**Comment by oshoval** [comment]
Here it is expected, it was lgtm + approve while on draft, it wont trigger it
please dont run it manually, tide should run it when all required lanes pass

**Comment by dankenigsberg** [comment]
> please dont run it manually, tide should run it when all required lanes pass

I don't follow. Nothing has been executed on this PR for 4 days. I cannot say where exactly, but something is wrong in the automation.

**Comment by oshoval** [comment]
> > please dont run it manually, tide should run it when all required lanes pass
> 
> I don't follow. Nothing has been executed on this PR for 4 days. I cannot say where exactly, but something is wrong in the automation.

If the labels are added when the PR is on draft, it won't trigger it not when it is on draft (because it doesnt make sense)
and not when it is undrafted (else we can trigger it again and again if it goes back and forth from draft).
It is by the current design at least.
We have a backstop by tide, it will be run automatically when the required jobs are passing, so even if it happens on drafted PRs, or even if an event is missed for one reason or another, we don't need to run it manually.
Tide will run it automatically when all the required jobs passed.
This is part of the fix https://github.com/kubernetes/test-infra/pull/31687

**Comment by dankenigsberg** [comment]
> We have a backstop by Tide

So why had nothing happened for four days?

**Comment by oshoval** [comment]
> > We have a backstop by Tide
> 
> So why had nothing happened for four days?

not sure, 
better to not trigger it please next time so we can see tide status
it seems latest retest was here
https://github.com/kubevirt/kubevirt/pull/11210#issuecomment-1958492434

since then we adapted the tide fix, maybe it could be something transient (those does happen rarely on changes)
lets see next time if it happen please

**Pull request merged**
