### PR TITLE
Add test_id for virtctl dry-run testing

### PR DESCRIPTION
**Pull request by jerry7z**
Signed-off-by: Zhe Peng <zpeng@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
Is this a duplicate of #6876?

**Comment by jerry7z** [comment]
Yes, this duplicate of #6876, I will close this one, sorry.

**Pull request closed without merging**
