### PR TITLE
[release-0.30] Add tests related to qemu processes

### PR DESCRIPTION
**Pull request by kbidarkar**
Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>

**What this PR does / why we need it**: `Add tests related to qemu processes`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: `Add tests related to qemu processes`

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by kbidarkar** [comment]
backport of #3599

**Comment by rmohr** [comment]
/close

Let's not create and approve PRs which  are not already merged on master. At least put a /hold on such a PR. I instructed prow to do a backport once it is merged on master.

**Pull request closed without merging**
