### PR TITLE
Fix Aggregated Discovery

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
See https://github.com/kubevirt/kubevirt/issues/10262

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
Update it here too?

`staging/src/kubevirt.io/client-go/go.mod`

**Comment by rmohr** [comment]
I am a little bit unsure, since normally we bump all of k8s in one go. @xpivarc what do you think?

**Comment by xpivarc** [comment]
@0xFelix @rmohr PTAL

Since it is only a minor update I thought to get away with only client-go. No additional changes seem to be in other dependencies. Nevertheless, I updated all k8s dependencies.

**Review by 0xFelix — APPROVED** [review]
/lgtm

Thanks!

**Review by rmohr — COMMENTED** [review]
/approve

**Pull request merged**
