### PR TITLE
Enable CR status subresource

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Separate status update from spec update by enabling the CR status subresource endpoint.
This gives us:

 * access separation between spec and status changes
 * no accidental status changes by users
 * generations in CRs are bumped which will allow the use of controller revisions

In order to give the controllers most flexibility for up- and downgrading kubevirt, the validation webhook follows the following principle:

 * `.spec` does not allow unknown fields (can be set by controllers and users)
 * `.status` allows unknown fields (can only be set bu controllers).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

TODO:

 * add functional test for the status webhook
 * rename the 1.10.4 provider to 1.10.11

**Release note**:

```release-note
Separate status- from spec updates. On clusters prior to k8s 1.11 or OCP 3.11, the `CustomResourceSubresources` feature-gate needs to be enabled.
```

### CODE REVIEW

**Comment by rmohr** [comment]
/hold cancel

I need to rename the 1.10.4 provider to 1.10.11. The rest is now worth a serious review.

**Comment by rmohr** [comment]
ci test please

**Comment by slintes** [comment]
there used to be more green lanes recently, let's try again

**Comment by slintes** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
hm, I see functional tests from TODO is still missing.

**Comment by rmohr** [comment]
/hold

migrations are broken in this PR

**Comment by slintes** [comment]
@rmohr I think we still want this?

/remove-lifecycle rotten

**Comment by fabiand** [comment]
There is an issue with migrations and status

**Comment by rmohr** [comment]
/close

Replaced with #3889

**Pull request closed without merging**
