### PR TITLE
Fix typos in log output

### PR DESCRIPTION
**Pull request by hs0210**
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>

**What this PR does / why we need it**:

Fix typos in log output.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by davidvossel — APPROVED** [review]
/ok-to-test
/lgtm
/approve

**Comment by rmohr** [comment]
Rolling this change back. This change is done in a vendored part and it is breaking `make generate`.

**Pull request merged**
