### PR TITLE
fix: when disable ipv6  leads to err  (#10857)

### PR DESCRIPTION
**Pull request by hanqingwu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

fix: when disable ipv6  leads to err  (#10857)

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by EdDev** [comment]
Please try to build (run `make`) or even execute the unit tests (run `make test`) locally to see potential issues.

Here is the current error:
```go
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: nogo: errors found by nogo during build-time code analysis:
pkg/network/driver/procsys/netip.go:70:8: Banned API found "os.IsNotExist". Additional info: use errors.Is(err, os.ErrNotExist) instead of os.IsNotExist(err) (bannedAPI)
```

This change also merits a big warning: Kubevirt is not tested on an IPv4 stack only platform and there are no plans to do so. Therefore, there may be other potential failures in such a setup.
In addition, changes to the code may not take this into account in the future, therefore the failure may return unintended.

Still, I think we can take such a change in, I see no strong reason not to.
Just note that if this gets in, it will come only in release v1.2 and it better be tested by the user who encounter the problem if possible.

**Comment by hanqingwu** [comment]
@EdDev    ok, i have change to errors.Is....

**Review by EdDev — APPROVED** [review]
Thanks!

@AlonaKaplan , please have a look.

**Comment by AlonaKaplan** [comment]
Thanks for the contribution.

/approve

**Pull request merged**
