### PR TITLE
rpm: Update virtualization packages

### LINKED ISSUE #10208: Arm64 -- qemu-kvm-device-usb-redirect package is missing on Arm64 platform
**What happened**:
As there is no rpm package `qemu-kvm-device-usb-redirect` in https://mirror.stream.centos.org/9-stream/AppStream/aarch64/os/Packages/, clientPassthrough does not works on Arm64 platform.
https://github.com/kubevirt/kubevirt/issues/10200

**What you expected to happen**:
clientPassthrough works on Arm64 platform

**Additional context**:
Shall we request to add `qemu-kvm-device-usb-redirect` in https://mirror.stream.centos.org/9-stream/AppStream/aarch64/os/Packages/?

### PR DESCRIPTION
**Pull request by andreabolognani**
### What this PR does

Update virtualization packages. Specifically:

* QEMU (8.0.0 → 8.2.0)
* libvirt (9.5.0 → 10.0.0)
* SeaBIOS (1.16.1 → 1.16.3)
* EDKII (20230524 → 20231122)
* passt (20230818 → 20231204)
* virtiofsd (1.7.2 → 1.1.10.1)
* guestfs-tools (1.50.1 → 1.51.6)

Fixes #10208 by adding the `usb-redir` device on Arm.

### Release note
```release-note
This version of KubeVirt includes upgraded virtualization technology based on libvirt 10.0.0 and QEMU 8.2.0.
Each new release of libvirt and QEMU contains numerous improvements and bug fixes.
```

### CODE REVIEW

**Comment by xpivarc** [comment]
@andreabolognani Thanks
/approve
/lgtm

**Comment by andreabolognani** [comment]
@xpivarc I'm seeing mostly timeouts among the failures. I'll start looking into it, but do you have any tips or gut feelings about what could be causing the issues? Just to speed things up if possible :)

**Comment by victortoso** [comment]
> Fixes https://github.com/kubevirt/kubevirt/issues/10208 by adding the usb-redir device on Arm.

Ah, cool.

Perhaps we can make [this test](https://github.com/kubevirt/kubevirt/blob/main/tests/usbredir_test.go#L57) run on arm? Based on [this commit](https://github.com/kubevirt/kubevirt/commit/481b9a29482), all is needed would be adding `[arm64]` to it.

**Comment by rmohr** [comment]
@andreabolognani FYI, seeing the same migration tests failing in https://github.com/kubevirt/kubevirt/pull/10346#issuecomment-1949182310 after bumping only qemu to install an additional tool in the containers.

**Comment by zhlhahaha** [comment]
> > Perhaps we can make [this test](https://github.com/kubevirt/kubevirt/blob/main/tests/usbredir_test.go#L57) run on arm? Based on [this commit](https://github.com/kubevirt/kubevirt/commit/481b9a29482), all is needed would be adding `[arm64]` to it.
> 
> Good idea, but I'll let @zhlhahaha take care of that after this PR has been merged. I wouldn't want to risk holding up the RPM update any longer than it's necessary.

I will give it a try, but currently we get some issue on the e2e tests on Arm64, I will fix it  as soon as possible.

**Comment by zhlhahaha** [comment]
> this test

I have verified the USB Redirection e2e tests. All three tests have passed on Arm64 platform.

**Comment by rmohr** [comment]
According to https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11256/pull-kubevirt-e2e-k8s-1.29-sig-compute-migrations/1762076682878980096 this seems to be mostly related to hotplug tests? Maybe @vladikr or @iholder101 may be able to help?

**Comment by andreabolognani** [comment]
@rmohr I can reproduce `[sig-compute][Serial]Memory Hotplug A VM with memory liveUpdate enabled [test_id:10823]should successfully hotplug memory` locally, so that's good. No idea how to actually debug it, really, but I'll try to figure something out :)

**Comment by iholder101** [comment]
Hey @andreabolognani @rmohr!

I've checkout to your branch and tried to run tests locally. When running `test_id:10823` I figured the following:

The test failed over the following error:
```
  [FAILED] Timed out after 240.000s.
  migration should succeed after 240 s
  Unexpected error:
      <*errors.errorString | 0xc0070080c0>: 
      migration is in the phase: Running
      {
          s: "migration is in the phase: Running",
      }
  occurred
  In [It] at: tests/libmigration/migration.go:63 @ 02/28/24 06:25:11.684
```

It seems however that although the migration is in a Running phase, the new virt-launcher instance is already ready and running:
```bash
iholderZK1[~/kubevirt]> k get vmim -Aw
NAMESPACE                NAME                             PHASE   VMI
kubevirt-test-default1   kubevirt-workload-update-9qnjj   Running           testvmi-fb92r

iholderZK1[~/kubevirt]> k get pods -A | grep virt-launcher
kubevirt-test-default1   virt-launcher-testvmi-fb92r-6fxr5               0/3     Completed   0              110s
kubevirt-test-default1   virt-launcher-testvmi-fb92r-zxv94               3/3     Running     0              96s
```

However, when I glanced over virt-handler's logs I saw many of these:
```
{"component":"virt-handler","kind":"","level":"error","msg":"error encountered reading from client (virt-api) websocket","name":"testvmi-fb92r","namespace":"kubevirt-test-default1","pos":"console.go:323","reason":"websocket: close 1006 (abnormal closure): unexpected EOF","timestamp":"2024-02-28T06:25:21.934785Z","uid":"3900b2b8-b194-4d35-a194-fa9552cf87b6"}

{"component":"virt-handler","kind":"","level":"error","msg":"Error in proxing websocket and unix socket","name":"testvmi-fb92r","namespace":"kubevirt-test-default1","pos":"console.go:332","reason":"websocket: close 1006 (abnormal closure): unexpected EOF","timestamp":"2024-02-28T06:25:21.934984Z","uid":"3900b2b8-b194-4d35-a194-fa9552cf87b6"}

{"component":"virt-handler","level":"info","msg":"http: response.WriteHeader on hijacked connection from kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful/v3.(*Response).WriteHeader (response.go:224)\n","pos":"server.go:3214","timestamp":"2024-02-28T06:25:21.935184Z"}

{"component":"virt-handler","kind":"","level":"error","msg":"error encountered reading from unix socket","name":"testvmi-fb92r","namespace":"kubevirt-test-default1","pos":"console.go:317","reason":"read unix @->/var/run/kubevirt-private/3900b2b8-b194-4d35-a194-fa9552cf87b6/virt-serial0: use of closed network connection","timestamp":"2024-02-28T06:25:21.935322Z","uid":"3900b2b8-b194-4d35-a194-fa9552cf87b6"}
```

So I'm still not sure exactly what's causing the problem or what it has to do with your version bumps, but I hope it's a good starting point for further debug.

Let me know if I can further help you!

**Comment by andreabolognani** [comment]
The serial console bit appears to be a red herring as it shows up in the virt-handler logs quite late, just a little bit before the test is considered failed due to the timeout.

This is the actual error:

```json
{
  "component":"virt-handler",
  "kind":"",
  "level":"error",
  "msg":"failed to finalize migration",
  "name":"testvmi-fb92r",
  "namespace":"kubevirt-test-default1",
  "pos":"vm.go:3384",
  "reason":"server error. command SyncVirtualMachineMemory failed: \"LibvirtError(Code=67, Domain=10, Message='unsupported configuration: cannot modify memory address from '0x100000000' to '0x0'')\"",
  "timestamp":"2024-02-28T17:10:20.824893Z",
  "uid":"05b8381c-0c21-4fac-947d-24d22ee9cbd4"
}
```

I have added support for the attribute to virtwrap. The test still fails with

```
[FAILED] Timed out after 240.000s.
Expected
    <int64>: 134217728
to be >
    <int64>: 134217728
In [It] at: tests/hotplug/memory.go:147 @ 02/28/24 20:32:10.897
```

which indicates that the operation ultimately didn't succeed, but at least it gets a little further.

**Comment by andreabolognani** [comment]
I think I might be getting closer.

Comparing the guest OS' dmesg for the `main` branch and mine, the former contains

```
[    1.891749] virtio_mem virtio7: start address: 0x100000000
[    1.893229] virtio_mem virtio7: region size: 0x8000000
[    1.894578] virtio_mem virtio7: device block size: 0x200000
[    1.896133] virtio_mem virtio7: memory block size: 0x8000000
[    1.897644] virtio_mem virtio7: subblock size: 0x400000
[    1.899322] virtio_mem virtio7: plugged size: 0x0
[    1.900834] virtio_mem virtio7: requested size: 0x0
...
[   19.726909] virtio_mem virtio7: plugged size: 0x0
[   19.727067] virtio_mem virtio7: requested size: 0x8000000
...
[   19.753799]  virtio_mem_add_memory+0x41/0xb0 [virtio_mem]
[   19.753828]  virtio_mem_sbm_plug_and_add_mb+0x9e/0x170 [virtio_mem]
[   19.753831]  virtio_mem_run_wq+0xaa5/0x1550 [virtio_mem]
```

while the latter contains

```
[    2.226584] virtio_mem virtio7: virtio: device refuses features: 3
```

So the issue could be caused by some incompatibility between the implementation of virtio-mem in QEMU 8.2 and the guest driver.

I'll try bumping Alpine to a more recent version to see whether that makes any difference.

**Comment by andreabolognani** [comment]
> So the issue could be caused by some incompatibility between the implementation of virtio-mem in QEMU 8.2 and the guest driver.

Yup, that should be it.

David Hildenbrand confirmed that, as of QEMU 8.2, virtio-mem requires Linux 5.16 or newer to be running inside the guest. Alpine 3.16, which we use for tests, has Linux 5.15, hence the failure.

I'll look into bumping Alpine to 3.19. The version of Fedora that we're using is also a couple of years old... It's probably worth bumping that too.

**Comment by andreabolognani** [comment]
I just hit another roadblock.

```
$ grep VIRTIO_MEM /boot/config-virt 
# CONFIG_VIRTIO_MEM is not set
```

In other words, Alpine 3.19 doesn't come with virtio-mem support. Unsurprisingly, when using an image based on it, the test fails both on my branch and on `main`.

I'll try to figure out whether there's at least one version of Alpine where the virtio-mem driver is both present and new enough to work with QEMU 8.2 next week.

**Comment by andreabolognani** [comment]
> I'll try to figure out whether there's at least one version of Alpine where the virtio-mem driver is both present and new enough to work with QEMU 8.2 next week.

Or today :)

Unfortunately it looks like the virtio-mem driver has been [disabled](https://gitlab.alpinelinux.org/alpine/aports/-/commit/f2d708907ba2fccc8b499c588f713b47d5cba2ed) as part of some refactoring, possibly by mistake. The good news is that, some time later, it was [enabled](https://gitlab.alpinelinux.org/alpine/aports/-/commit/c992a86c6936086a30dd3f88923088fc4213641f) again, though only for the regular kernel build and not the "virt" flavor.

So, by switching to the "lts" kernel package, it should be possible to get things working with Alpine 3.19.

**Comment by andreabolognani** [comment]
I have switched to Alpine 3.19, and at least locally that solves the virtio-mem issues.

Note that I was forced to bump the memory requirements because the "lts" kernel uses more memory than the "virt" kernel that we were using before, but the latter doesn't come with a virtio-mem driver so we can't use it...

I have opened a [merge request against Alpine](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/61693) to try and fix that, but I have no idea how long it will take for that to make its way to the repositories. We might have to take the hit, at least temporarily.

For the same reason, I expect that several additional tests will start failing because the VMI is not been given enough memory to run the lts kernel. We'll see how bad the fallout is once the tests run.

/retest

**Comment by andreabolognani** [comment]
Oh, and in case anyone is wondering the PR is not based on the latest `main` because after https://github.com/kubevirt/kubevirt/pull/11361 I can no longer deploy a working cluster locally. More information shared there.

**Comment by andreabolognani** [comment]
Not sure what the checksum failures on downloaded RPMs are all about, I try fetching one locally and it was fine. Possibly some temporary glitch?

/retest

**Comment by andreabolognani** [comment]
Nope, still failing. Anyone has any idea what's going on?

**Comment by andreabolognani** [comment]
I see. Thanks a lot @brianmcarey!

**Comment by andreabolognani** [comment]
I've looked into the failures that have popped up after the last update and the tests are mostly using the Alpine image, so it's likely that the errors are a consequence of the increased memory usage caused by the (temporary) switch to the lts kernel.

Since the process for getting the virtio-mem driver re-enabled in the virt kernel is progressing fairly well (the change has already landed in edge and will hopefully make its way to 3.19 soon; see [here](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/61693) for details) I'll just leave this be for a bit. I'm off next week, and hopefully things on that side will have been been settled by the time I'm back.

/hold

**Comment by andreabolognani** [comment]
Rebased on top of `main` and picked up a new Alpine 3.19 image that should include a virt kernel with virtio-mem support.

I have reverted the changes related to memory size for test VMs, since hopefully the virt kernel is not much more demanding in Alpine 3.19 than it was in Alpine 3.16. We'll see whether that's actually the case.

**Comment by victortoso** [comment]
@andreabolognani you might want to add that this PR fixes https://github.com/kubevirt/kubevirt/issues/10094 too.

**Comment by sbrivio-rh** [comment]
Would it make sense to update passt to `0^20230222.g4ddbcb9-4.el9` instead? It was packaged one week after this pull request was opened.

**Comment by andreabolognani** [comment]
@sbrivio-rh isn't `0^20231204.gb86afe3-1.el9` that I'm picking up here almost a year newer than `0^20230222.g4ddbcb9-4.el9`? I generally just choose the most recent release available [on the CentOS Stream 9 mirror](https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/).

**Comment by sbrivio-rh** [comment]
> @sbrivio-rh isn't `0^20231204.gb86afe3-1.el9` that I'm picking up here almost a year newer than `0^20230222.g4ddbcb9-4.el9`?

Gosh, you're right of course, sorry for the noise. I'll try to forget about this quickly so that I can keep pretending that date plus short SHA is so much better than semantic versioning. :)

**Comment by victortoso** [comment]
> @andreabolognani you might want to add that this PR fixes #10094 too.

And https://github.com/kubevirt/kubevirt/issues/11591
:)

**Comment by andreabolognani** [comment]
Updated to include @akalenyu's Alpine 3.19 image (see https://github.com/kubevirt/kubevirtci/pull/1167), which features fixed cloud-init support.

Some work is still needed on that front, since I'm getting this error now:

```
can't access VMI testvmi-txhzt: Internal error occurred: dialing VM: dial tcp :22: connect: connection refused
      {
          msg: "can't access VMI testvmi-txhzt: Internal error occurred: dialing VM: dial tcp :22: connect: connection refused",
          err: <*kubecli.AsyncSubresourceError | 0xc002da1620>{
              err: "Internal error occurred: dialing VM: dial tcp :22: connect: connection refused",
              StatusCode: 500,
          },
      }
```

Indeed, the network interfaces do not get configured.

I've found this in the cloud-init log:

```
stages.py[INFO]: Applying network configuration from fallback bringup=False: {'ethernets': {'eth0': {'dhcp4': True, 'set-name': 'eth0', 'match': {'macaddress': 'f6:c3:52:e5:44:b4'}}}, 'version': 2}
```

The `bringup=False` part looks mighty suspicious. Investigating further, please shout if you have any hints.

**Comment by andreabolognani** [comment]
The `networking` service was disabled, hence why we didn't get any networking :)

I've switched to an updated image and at least one of the scp tests passed now. kubevirtci PR coming up shortly.

**Comment by akalenyu** [comment]
> The `networking` service was disabled, hence why we didn't get any networking :)
> 
> I've switched to an updated image and at least one of the scp tests passed now. kubevirtci PR coming up shortly.

Nice find
I still see we have failures, maybe @brianmcarey faced similar issues when bumping fedora?
https://github.com/kubevirt/kubevirt/pull/11419

**Comment by andreabolognani** [comment]
The "fix" for the memory hotplug test case actually made things worse. I've dropped it, those tests should all pass now.

I've started looking into the istio test failures and confirmed that they're caused by Alpine 3.19 rather than the updated virtualization stack. The "bastion" VM can't connect to the other one, even though the network seems to be up. This is way out of my comfort zone, so I'm not sure if I'll be able to figure much out, but I'll give it a shot. If anyone has any suggestions on what I should be looking for, please do share!

**Comment by andreabolognani** [comment]
Enable ssh password authentication using the cloud-init native mechanism instead of a sed script. This should fix the failing istio tests.

**Comment by xpivarc** [comment]
@andreabolognani 
```
"Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=9, Domain=31, Message='operation failed: guest CPU doesn't match specification: extra features: vmx-ins-outs,vmx-true-ctls,vmx-store-lma,vmx-activity-hlt,vmx-vmwrite-vmexit-fields,vmx-apicv-xapic,vmx-ept,vmx-desc-exit,vmx-rdtscp-exit,vmx-apicv-x2apic,vmx-vpid,vmx-wbinvd-exit,vmx-unrestricted-guest,vmx-apicv-register,vmx-apicv-vid,vmx-rdrand-exit,vmx-invpcid-exit,vmx-vmfunc,vmx-shadow-vmcs,vmx-rdseed-exit,vmx-pml,vmx-invvpid,vmx-invvpid-single-addr,vmx-invvpid-all-context,vmx-ept-execonly,vmx-page-walk-4,vmx-ept-2mb,vmx-ept-1gb,vmx-invept,vmx-eptad,vmx-invept-single-context,vmx-invept-all-context,vmx-intr-exit,vmx-nmi-exit,vmx-vnmi,vmx-preemption-timer,vmx-posted-intr,vmx-vintr-pending,vmx-tsc-offset,vmx-hlt-exit,vmx-invlpg-exit,vmx-mwait-exit,vmx-rdpmc-exit,vmx-rdtsc-exit,vmx-cr3-load-noexit,vmx-cr3-store-noexit,vmx-cr8-load-exit,vmx-cr8-store-exit,vmx-flexpriority,vmx-vnmi-pending,vmx-movdr-exit,vmx-io-exit,vmx-io-bitmap,vmx-mtf,vmx-msr-bitmap,vmx-monitor-exit,vmx-pause-exit,vmx-secondary-ctls,vmx-exit-nosave-debugctl,vmx-exit-ack-intr,vmx-exit-save-pat,vmx-exit-load-pat,vmx-exit-save-efer,vmx-exit-load-efer,vmx-exit-save-preemption-timer,vmx-entry-noload-debugctl,vmx-entry-ia32e-mode,vmx-entry-load-pat,vmx-entry-load-efer')",
```
This is the last failing test I see. Any idea why we see such wild error?

**Comment by andreabolognani** [comment]
@xpivarc thanks, that's really helpful! And it rings a bell. I think something about the handling of the vmx features was being discussed recently. I'll try to look the information up and get back to you.

**Comment by andreabolognani** [comment]
Yeah, that would be [RHEL-25995](https://issues.redhat.com/browse/RHEL-25995) which is fixed in `libvirt-10.0.0-5.el9`; unfortunately CentOS Stream 9 only has `libvirt-10.0.0-4.el9` for now. And it looks like another issue might have been introduced by the change ([RHEL-30622](https://issues.redhat.com/browse/RHEL-30622)), so now we need for that to get addressed too. It might be a few more weeks until we can put this behind us I'm afraid :(

**Comment by akalenyu** [comment]
> Yeah, that would be [RHEL-25995](https://issues.redhat.com/browse/RHEL-25995) which is fixed in `libvirt-10.0.0-5.el9`; unfortunately CentOS Stream 9 only has `libvirt-10.0.0-4.el9` for now. And it looks like another issue might have been introduced by the change ([RHEL-30622](https://issues.redhat.com/browse/RHEL-30622)), so now we need for that to get addressed too. It might be a few more weeks until we can put this behind us I'm afraid :(

I've had PRs in [CDI](https://github.com/kubevirt/containerized-data-importer/pull/2947/files#diff-2e7e3f323c3dd4d4dde40be454186e11ebbc335f1c3eab3865a5f2f8de262b87) add their own mirror to the repositories list https://github.com/kubevirt/kubevirt/blob/a8fc5497147b981116aa28dd93df153f349f450e/rpm/repo.yaml#L1

**Comment by andreabolognani** [comment]
Well, there are two reasons why a package that was already built in CentOS Stream 9 is not available from the mirrors:

* it's waiting for the sync job to run, which AFAIK happens once a week or so;
* the build hasn't been marked as verified by QE.

If we were in the first camp it would be possible to skip ahead of the mirror, but that would only save us a few days of waiting and would later need reverting, so probably not worth the effort.

But we're in the second camp instead, where a further issue has been found during validation. So we would be knowingly introduce a regression in KubeVirt... Even if the CI somehow passed, we definitely wouldn't want that.

So our only option is really to just wait for the issue to be fixed and the resulting built to be validated, however annoying that might be :(

**Comment by andreabolognani** [comment]
Pick up `libvirt-10.0.0-5.el9` with a hack so that we can at least make sure that there are no other issues waiting for us after that update has been unblocked.

**Comment by xpivarc** [comment]
`Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=67, Domain=31, Message='unsupported configuration: Target CPU feature count 32 does not match source 103')",`

**Comment by andreabolognani** [comment]
> `Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=67, Domain=31, Message='unsupported configuration: Target CPU feature count 32 does not match source 103')",`

@xpivarc that's not surprising, it's the other issue that I was talking about ([RHEL-30622](https://issues.redhat.com/browse/RHEL-30622)) and that hasn't been resolved upstream yet :)

Can you please try to fish out the various XMLs used in that test? The one for the VM running on the original node, the one used for migration, anything else that might be relevant? That could be useful to track down the issue.

**Comment by andreabolognani** [comment]
Updated to pick up the official 3.19 `alpine-with-test-tooling-container-disk` image from https://github.com/kubevirt/kubevirtci/pull/1167. Sadly, we're still missing the fix for [RHEL-30622](https://issues.redhat.com/browse/RHEL-30622).

**Comment by andreabolognani** [comment]
Updated to pick up libvirt 10.0.0-7, which should contain fixes for all known issues. Unfortunately that build is not available from composes yet, so I'm fetching it straight from koji as a temporary workaround.

**Comment by alicefr** [comment]
@andreabolognani any updates on this? QEMU package for the version `8.0.0-13` aren't available anymore from centos stream. Hence, `make rpms` fails

**Comment by andreabolognani** [comment]
@alicefr see [my last update](https://github.com/kubevirt/kubevirt/pull/11256#issuecomment-2071694379). Things are progressing, albeit slowly. I know this is becoming increasingly problematic. There's not much I can do about it beyond what I'm already doing.

**Comment by alicefr** [comment]
> @alicefr see [my last update](https://github.com/kubevirt/kubevirt/pull/11256#issuecomment-2071694379). Things are progressing, albeit slowly. I know this is becoming increasingly problematic. There's not much I can do about it beyond what I'm already doing.

An using libvirt version `10.0.0-4` isn't an option?

**Comment by alicefr** [comment]
> 10.0.0-4 contains two migration-related issues, so the CI jobs will understandably not pass. 10.0.0-7 addresses them.

Ok, sorry for the noise and thanks for the explanation.

**Comment by andreabolognani** [comment]
libvirt 10.0.0-7, which contains fixes for all known issues affecting KubeVirt, is finally available from a CentOS Stream 9 compose. Fingers crossed for CI actually passing now.

**Comment by victortoso** [comment]
The changes seem fine.
/lgtm

**Comment by andreabolognani** [comment]
@xpivarc it looks like the `pull-kubevirt-e2e-kind-1.27-vgpu` job is the only remaining failure. It's marked as `required: false`, does that mean the failure can be ignored? [Its history](https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-kind-1.27-vgpu) looks spotty at best.

**Comment by akalenyu** [comment]
> @xpivarc it looks like the `pull-kubevirt-e2e-kind-1.27-vgpu` job is the only remaining failure. It's marked as `required: false`, does that mean the failure can be ignored? [Its history](https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-kind-1.27-vgpu) looks spotty at best.

https://groups.google.com/d/msgid/kubevirt-dev/CA%2B3oYq4UjvGMDV3YfBNx%3DbP_-cfP0rpM80y1tEa3N6%2BJJGR89w%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by andreabolognani** [comment]
@akalenyu you mean run that specific test again, hoping that it will fare better this time around?

**Comment by akalenyu** [comment]
> @akalenyu you mean run that specific test again, hoping that it will fare better this time around?

No I mean `/test all` to exercise all lanes again to ensure no new flakes are introduced

**Comment by andreabolognani** [comment]
Okay.

/test all

**Comment by akalenyu** [comment]
/test pull-kubevirt-e2e-k8s-1.30-sig-compute-serial

unrelated flake https://search.ci.kubevirt.io/?search=%5Btest_id%3A1634%5D&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by andreabolognani** [comment]
@xpivarc @akalenyu all but the vgpu test pass. Can we drop the hold and merge?

**Comment by iholder101** [comment]
Seems like @xpivarc was holding because of test failures.
As @akalenyu [mentioned](https://github.com/kubevirt/kubevirt/pull/11256#issuecomment-2098444468), the vgpu lane is currently flaky and not required.
I think it's safe to unhold.

Thank you very much @andreabolognani! I know getting this in wasn't easy :) good job.

/unhold

**Comment by andreabolognani** [comment]
@iholder101 amazing!

Thanks a lot, and thanks in particular to @xpivarc and @akalenyu who were a big help in figuring out and solving some of the nastiest blockers :)

**Pull request merged**
