### PR TITLE
[release-0.55] sriov: Fix network to PCI-Address mapping

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:
This is a manual cherry-pick of the following PRs:
- https://github.com/kubevirt/kubevirt/pull/8093
- https://github.com/kubevirt/kubevirt/pull/8263
- https://github.com/kubevirt/kubevirt/pull/8226
   diffs: 
   - vmi.go: using `EscapeJSONPointer()` from `kubevirt.io/kubevirt/pkg/controller` since it didn't move [yet](https://github.com/kubevirt/kubevirt/commit/19af7003bbeb299ee9ed0155048956556709f554). 
   - tests/network/sriov.go: 
       - refactored test to use old functions prior to recent [refactor](https://github.com/kubevirt/kubevirt/pull/8299).
       - Add skip to test in case Multus is not updated with the updated network-status annotation.
       
This cherry pick PR fixes https://github.com/kubevirt/kubevirt/issues/7444 on `release-0.55` branch

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by EdDev — APPROVED** [review]

**Review by EdDev — APPROVED** [review]

**Comment by RamLavi** [comment]
[fixed](https://github.com/kubevirt/kubevirt/compare/645168bb0011812d8d77db1b41d480570cbca9b7..ddb336670f4e769065746b22829a52db20959747)
/hold cancel

**Pull request merged**
