### PR TITLE
Enable test 6978

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
/cc @dhiller @enp0s3

### CODE REVIEW

**Comment by xpivarc** [comment]
Fixes #6622

**Comment by xpivarc** [comment]
@dhiller I would still proceed with this PR if you don't mind.

**Comment by dhiller** [comment]
> @dhiller I would still proceed with this PR if you don't mind.

I'd approve this PR as soon as we have positive CI signal. I'll take a look tomorrow on this again.

**Review by dhiller — APPROVED** [review]
/approve

Seen successful Test result in 1.23 Migration lane

/retest

**Comment by xpivarc** [comment]
> Retesting to check whether #7410 fixed the failing test_id:2666
> 
> /retest

@dhiller Seems to me it helped, wdyt?

**Pull request merged**
