### PR TITLE
Setup stdci1

### PR DESCRIPTION
**Pull request by rmohr**
Run tests on kubevirt tests on stdci-vms.

### CODE REVIEW

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
ci test please

**Comment by rmohr** [comment]
@ifireball I see

```
Error response from daemon: driver failed programming external connectivity on endpoint k8s-1.10.3-dnsmasq (8a9f317e4cdcb5a2c8d6b68a80d1eb5c0bbf4f53de892a24d4ef64be6ed63313):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport 8443 -j DNAT --to-destination 172.17.0.2:8443 ! -i docker0: iptables: No chain/target/match by that name.
```

on some vms. In the last run on all but nut only on some in previous runs. May be related to docker/firewall issues.

**Comment by ifireball** [comment]
@rmohr isn't that iptables command running inside the k8s VMs your system brings up? I'll need more details in order to figure out if/how the host configuration could cause this...

**Comment by rmohr** [comment]
@ifireball no. We just start our dnsmasq container on your vm. Docker tries to do that iptables command, not us.

**Comment by ifireball** [comment]
@rmohr I see we`re trying to run on VMs here rather then BMs... lets stabilize things on BMs first and the research using VMs ok?

**Comment by rmohr** [comment]
We just start the dnsmasq container with the option to expose all ports in general `-P` and optionally add some more ports with `-p`. And it is privielged (`--privileged`). That's it.

**Comment by ifireball** [comment]
@rmohr ok I managed to reproduce this with:

     sudo docker run -it --rm --privileged -P -p 4444:3333 centos

The puzzling thing is that this works fine on the BMs... I really wonder where is this difference coming from, given that they're both setup the same way with the same scripts...

**Comment by ifireball** [comment]
@rmohr ah it may be an fc28 thing... since all the threads that failed with this issue ran on FC28 VMs.  (Note that 'check-patch.k8s-1.10.3-release.el7.x86_64' which ran on EL7 failed on something else).

Lets try forcing it to use EL7 VMs by adding to following to the YAML:

     runtime-requirements:
        host-distro: same

But again maybe we should just drop the commit that allows it to use VMs and focus on BMs first....

**Comment by rmohr** [comment]
Would `some` have to be `el7` or `EL7` or does it not matter?

**Comment by rmohr** [comment]
Or is it literally `same`?

**Comment by ifireball** [comment]
literally {{same}} to tell it that the host should have the same OS as the CI userspace.

**Comment by ifireball** [comment]
I the meantime I managed to reproduce and find a solution, can see details here:

https://ovirt-jira.atlassian.net/browse/OVIRT-2340

I'll patch our system to prevent this from happening in the future.

**Comment by rmohr** [comment]
@ifireball does the check-patch.yaml look correct? It still shows the same errors.

**Comment by rmohr** [comment]
ci test please

**Comment by ifireball** [comment]
@rmohr since you have an stdci.yaml file in the project root, it should go there

**Comment by rmohr** [comment]
Nesting is too deep. My tests show that running our vms on vms degrades performance too much (we talk about minutes to start e.g. cirros).

**Comment by ifireball** [comment]
please repone this and set it to run on BMs - this PR was originally meant to generally enable STDCI, not just on VMs

**Comment by rmohr** [comment]
@ifireball you mean #1302.

**Pull request closed without merging**
