### PR TITLE
[virt-operator] Remove a webhook check which checks workload placement

### LINKED ISSUE #4720: [flaky ci] Creating a VirtualMachineInstance when virt-handler is not responsive [test_id:1634]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4710/pull-kubevirt-e2e-k8s-1.17/1341915356280655873

tests/vmi_lifecycle_test.go:630
Expected
    <string>: 
to equal
    <string>: NodeUnresponsive
tests/vmi_lifecycle_test.go:663

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/triage build-watcher

### LINKED ISSUE #4958: Tests Suite: [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating a VirtualMachineInstance [Serial]when virt-handler is not responsive [test_id:1634]the node controller should mark the node as unschedulable when the virt-handler heartbeat has timedout
**Is this a BUG REPORT or FEATURE REQUEST?**:

/triage build-watcher
/kind bug

**What happened**:

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-4.8-e2e/1356800216870686720

```
tests/vmi_lifecycle_test.go:582
Should get virthandler client
Unexpected error:
    <*errors.errorString | 0xc0029d29c0>: {
        s: "No virt-handler on node ci-op-131g7tms-37b01-s8rhh-master-0 found",
    }
    No virt-handler on node ci-op-131g7tms-37b01-s8rhh-master-0 found
occurred
tests/vmi_lifecycle_test.go:618
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Allow modifying the node layout with kubevirt installed via taints and
labels without having to shut down all VMIs.

Previously, changing node layout was possible, but it was not possible
to adjust the KubeVirt installation without shutting down all VMIs
first.

The admin-supporting aspect of this feature, to detect if VMIs are left
unmonitored on some nodes where virt-handler is not running, is now
covered via proper alerting.

Further it fixes flakyness in the following test, if CI nodes were under pressure:

```
[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating a VirtualMachineInstance [Serial]when virt-handler is not responsive [test_id:1634]the node controller should mark the node as unschedulable when the virt-handler heartbeat has timedout
```

The symptom was this:

```
tests/vmi_lifecycle_test.go:704
Timed out after 180.000s.
Expected
    <string>: 
to equal
    <string>: NodeUnresponsive
tests/vmi_lifecycle_test.go:740
```

The reason was this: First virt-handler got evicted, then a VMI got started. Sometimes the VMI did not reach the running state until virt-handler was evacuated. In that scenario virt-controller still owned the object, which caused the node controller to not kick in, since it only moves VMIs to failed state on unresponsive nodes, which are owned by virt-handler.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4720 and fixes #4958

**Special notes for your reviewer**:

Flakefinder entry: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-03-14-168h.html#row37

**Release note**:
```release-note
Remove  workload placement validation webhook which blocks placement updates when VMIs are running
```

### CODE REVIEW

**Review by davidvossel — APPROVED** [review]
/approve

yep, i agree this check can cause more issues than it's worth. Now that we have metrics and alerts in place, the situation won't go unnoticed long term if an accident is made

**Comment by rmohr** [comment]
Rebased.

@ashleyschuett would you mind doing a code review? This one would help fixing a flaky test which in turn prepares the ground for #4760 which also helps with other issues.

**Pull request merged**
