### PR TITLE
tests: Fix the istio test to actually perform the required check

### PR DESCRIPTION
**Pull request by AlonaKaplan**
**What this PR does / why we need it**:

The `Istio Virtual Machine with masquerade interface Outbound traffic With Sidecar allowing only registered external services VMI with no explicit ports Should not be able to reach http service outside of mesh` what missing the part that actually verified the test
succeeded. This PR fixes it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by enp0s3 — APPROVED** [review]
Thank you!
/lgtm
/approve

**Comment by EdDev** [comment]
@AlonaKaplan , @rhrazdil , is this still relevant?

**Comment by rhrazdil** [comment]
@EdDev @AlonaKaplan  This was addressed in https://github.com/kubevirt/kubevirt/pull/6135, I believe this can be closed.

**Pull request closed without merging**
