### PR TITLE
e2e, network: Remove VM Running API usage

### PR DESCRIPTION
**Pull request by ormergi**
### What this PR does
The VM Running API is deprecated.

User RunStrategy API in network tests.

Before this PR:
Network e2e tests used the Running API to start VMs

After this PR:
Network e2e tests use RunStrategy APU to start VMs

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by ormergi** [comment]
label code-quality

**Review by orelmisan — COMMENTED** [review]
Thank you for the PR @ormergi 

Overall looks good, since the Running field was not officially deprecated yet, please consider adjusting the reasoning.

**Review by jean-edouard — COMMENTED** [review]
/approve

**Comment by EdDev** [comment]
> /approve

Please feedback to https://github.com/kubevirt/kubevirt/pull/12895#pullrequestreview-2321408856 before proceeding with this.

/hold

**Comment by ormergi** [comment]
@orelmisan / @EdDev what do you suggest changing the reasoning to?

**Comment by orelmisan** [comment]
> @orelmisan / @EdDev what do you suggest changing the reasoning to?

The `RunStrategy` field is the successor of `Running` which is currently being phased out.

**Comment by ormergi** [comment]
> The `RunStrategy` field is the successor of `Running` which is currently being phased out.

Aren't these are all nice work for saying API is deprecated?

**Comment by orelmisan** [comment]
> > The `RunStrategy` field is the successor of `Running` which is currently being phased out.
> 
> Aren't these are all nice work for saying API is deprecated?

PR #12578 officially deprecates `Running`, and is not yet merged.

**Comment by ormergi** [comment]
> > > The `RunStrategy` field is the successor of `Running` which is currently being phased out.
> > 
> > 
> > Aren't these are all nice work for saying API is deprecated?
> 
> PR #12578 officially deprecates `Running`, and is not yet merged.

I think its clear the API is deprecated, it is well known [and announced](https://github.com/kubevirt/kubevirt/issues/11993), there's a work to reduce using it all over e2e by sigs (similar to this PR), and on top of that there is the mention PR that mark the field as deprecated.

@orelmisan I dont think you should block this PR on semantics of commit message/description where the intention, what and  why and are crystal clear backed by reference work plan.
@EdDev please advise how to continue with this PR.

**Comment by orelmisan** [comment]
PR #12578 was merged.
@EdDev can we remove the hold?

**Review by orelmisan — APPROVED** [review]

**Comment by EdDev** [comment]
> PR #12578 was merged. @EdDev can we remove the hold?

/unhold

**Pull request merged**
