### PR TITLE
update go versionm 1.16.1 -> 1.16.6

### PR DESCRIPTION
**Pull request by ashleyschuett**
Signed-off-by: Ashley Schuett <aschuett@redhat.com>

**What this PR does / why we need it**:
Update go version 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Go version updated to version 1.16.6
```

### CODE REVIEW

**Comment by xpivarc** [comment]
Do we want to update the builder image too?

**Comment by ashleyschuett** [comment]
@xpivarc thanks for the reminder. I think I did it correctly now?

**Comment by iholder-redhat** [comment]
Thanks @ashleyschuett !

I'm a bit concerned that go rules don't fully support Go 1.16.6.

The latest go rules version ([v0.24.14](https://github.com/bazelbuild/rules_go/releases/tag/v0.24.14)) that said something about supporting new Go versions says: `Go 1.16.2, 1.16.1, 1.15.10, and 1.15.9 are now supported`. In their latest version's release notes ([v0.28.0](https://github.com/bazelbuild/rules_go/releases/tag/v0.28.0)) they use `go_register_toolchains(version = "1.16.5")`.

On the other hand - I see that CI lanes ended up generally fine.. I would appreciate another opinion on this :)

**Comment by ashleyschuett** [comment]
> In their latest version's release notes (v0.28.0) they use go_register_toolchains(version = "1.16.5").

I can downgrad this to instead use 1.16.5 if that's better? Maybe @dhiller has an opinion?

**Comment by dhiller** [comment]
> > In their latest version's release notes (v0.28.0) they use go_register_toolchains(version = "1.16.5").
> 
> I can downgrad this to instead use 1.16.5 if that's better? Maybe @dhiller has an opinion?

Sorry, missed the notification on this.

IMHO if everything works, we should leave it like this.

**Comment by ashleyschuett** [comment]
> IMHO if everything works, we should leave it like this. 

@dhiller are you okay with giving it an approve then? :)

**Pull request merged**
