### PR TITLE
Remove vmi update collision optimization in virt-handler

### PR DESCRIPTION
**Pull request by davidvossel**
related to #6997 

PR #5982 introduced an optimization that ensured we don't process a vmi in virt-handler after an update until that update has been observed in an informer callback.

Unfortunately, during live migration this expectation can get out of sync. There's a hand off that occurs where a VMI transitions from one virt-handler to another one on another node. That means it's technically possible for an update to be issued in order to perform the handler to handler hand off, and for the corresponding informer to never see the result of the handoff. 

```release-note
NONE
```

### CODE REVIEW

**Comment by davidvossel** [comment]
@vasiliy-ul fyi, If you're still experiencing issues and can continue to reproduce your findings, we should remove the optimization that causes the update delay.

**Comment by davidvossel** [comment]
/hold

I'd like more proof the issue we're aiming to resolve here is occurring in a clean (un-modified) environment before we merge this.

**Comment by vasiliy-ul** [comment]
> @vasiliy-ul fyi, If you're still experiencing issues and can continue to reproduce your findings, we should remove the optimization that causes the update delay.

@davidvossel , I think that is not needed.  Initially I misunderstod the idea behind this optimization. Now I also see that the code is correct. The test failure that I faced is caused by another reason. Please check my comment https://github.com/kubevirt/kubevirt/pull/6997#issuecomment-1019546079.

**Comment by davidvossel** [comment]
closing in favor of #7131

**Pull request closed without merging**
