### PR TITLE
[release-0.26] Increase memory overhead for VFIO devices

### PR DESCRIPTION
**Pull request by vladikr**
This is a manual cherry-pick of #3178

/assign stu-gott

```release-note
NONE
```

### CODE REVIEW

**Comment by phoracek** [comment]
The SR-IOV e2e test won't pass. CPU manager is not enabled on this SR-IOV provider lane (we fixed that only recently on master).

**Comment by rmohr** [comment]
Will this PR break the sriov lane now also for other PRs?

**Comment by rmohr** [comment]
/hold

If that is the case, at least skip failing tests instead of breaking the lane.

**Comment by rmohr** [comment]
Do we use dedicated CPUs because only that triggers the issue, or do we use dedicated CPUs to get a VM with QoS Guaranteed? If the second one I would suggest to change the test to simply use a VM whis has the Guaranteed class assigned.

**Comment by vladikr** [comment]
> Do we use dedicated CPUs because only that triggers the issue, or do we use dedicated CPUs to get a VM with QoS Guaranteed? If the second one I would suggest to change the test to simply use a VM whis has the Guaranteed class assigned.

Well, just because we need a test that verifies this scenario. But the root cause of the issue is QoS Guaranteed. 
I've updated the PR.

**Comment by vladikr** [comment]
> Will this PR break the sriov lane now also for other PRs?

Good point, thanks!

**Pull request merged**
