### PR TITLE
Add clusterrole aggregation for kubevirt CRDs

### PR DESCRIPTION
**Pull request by aglitke**
By default regular users do not have access admin/edit/view access to
CRDs such as those provided by kubevirt.  This causes problems when a
user wants to view these objects in a UI or provision them.  By adding
aggregation labels to the clusterroles the user's existing permissions
for regular objects will be mapped to our CRDs.  This provides a better
experience for users.  Admins who want to lock down kubevirt access
should be able to add it on later.

Signed-off-by: Adam Litke <alitke@redhat.com>

### CODE REVIEW

**Comment by davidvossel** [comment]
> could you add checks to tests/access_test.go to make sure that new users get the right permissions?

@aglitke I bet this is super easy actually. All that needs to change is how the test's service accounts bind to ClusterRoles.  Instead of binding directly to the KubeVirt cluster roles, bind to corresponding aggregated k8s role instead.  Look at createServiceAccount() in tests/utils.go

at that point, the access_test.go tests will be verifying both the default kubeVirt clusterRoles work, and that they aggregate with the default k8s roles.

**Comment by aglitke** [comment]
I am unable to get the tests working and could use some help from someone with more rbac experience.  @davidvossel or @rmohr can you take a look please?  We need this in order to clean up the import-vm-apb.

**Comment by davidvossel** [comment]
ok to test

**Comment by davidvossel** [comment]
@aglitke can you commit what you have so far for the functional tests. I seem to remember you got all but one to pass.

**Comment by aglitke** [comment]
@davidvossel pushed

**Comment by davidvossel** [comment]
@aglitke #1159 should fix the issue you're hitting.

If we're going to aggregate the kubevirt:admin role with the default k8s admin role, we don't need that special kubevirt-config rbac rule or the corresponding functional test.

If we get #1159 merged, you'll just need to rebase your patch and the functional tests will pass.

**Comment by rmohr** [comment]
retest this please

**Comment by davidvossel** [comment]
this should now after being rebased. @aglitke please rebase

**Comment by aglitke** [comment]
Rebased.

**Comment by aglitke** [comment]
@rmohr Is this ready from your perspective?

**Pull request merged**
