### PR TITLE
Remove @dshchedr from the list of test-reviewers

### PR DESCRIPTION
**Pull request by rnetser**
**What this PR does / why we need it**:
Remove @dshchedr from the list of test-reviewers

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
/approve

Please sign of your commit

**Comment by davidvossel** [comment]
/hold

there's 6 commits in this pr for a 1 line change. Please squash down to a single commit

**Comment by danielBelenky** [comment]
* overriding CI because there are clearly no code changes here and I'd rather avoid overloading the CI right now with unnecessary tests.

/override pull-kubevirt-e2e-k8s-1.16
/override pull-kubevirt-e2e-k8s-1.17
/override pull-kubevirt-e2e-k8s-cnao-1.17
/override pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6

**Comment by danielBelenky** [comment]
Merging this one manually because there are no code changes and I'd rather not overload the CI right now with 4 lanes where we don't really need their result for this PR.

**Pull request merged**
