### PR TITLE
volume migration: fix hotplug volumes when the volume migration fg is enabled

### LINKED ISSUE #12670: Hotplug is misbehaving when the volume migration feature gate is enabled
**What happened**:
When the volume migration feature gate is enabled, the volume hotplug action is misinterpreted as a replacement operation and hotplug doesn't work.

**What you expected to happen**:
Hotplug the volume as when the feature gate is disabled

**How to reproduce it (as minimally and precisely as possible)**:
Enable the volume migration feature gate:
```bash
kubectl patch kubevirt kubevirt -n kubevirt --type=json -p='[{"op": "add", "path": "/spec/configuration/vmRolloutStrategy", "value": "LiveUpdate"}]'
kubectl patch kubevirt kubevirt -n kubevirt --type=merge -p='{"spec": {"workloadUpdateStrategy": { "workloadUpdateMethods" : []}}}'
kubectl patch kubevirt kubevirt -n kubevirt --type=json -p='[{"op": "add", "path": "/spec/workloadUpdateStrategy/workloadUpdateMethods/-", "value": "LiveMigrate"}]'
kubectl patch kubevirt kubevirt -n kubevirt --type=merge -p='{"spec": {"configuration": {"developerConfiguration": { "featureGates" : []}}}}'
kubectl patch kubevirt kubevirt -n kubevirt --type=json -p='[{"op": "add", "path": "/spec/configuration/developerConfiguration/featureGates/-", "value": "VMLiveUpdateFeatures"}]'
kubectl patch kubevirt kubevirt -n kubevirt --type=json -p='[{"op": "add", "path": "/spec/configuration/developerConfiguration/featureGates/-", "value": "VolumesUpdateStrategy"}]'
kubectl patch kubevirt kubevirt -n kubevirt --type=json -p='[{"op": "add", "path": "/spec/configuration/developerConfiguration/featureGates/-", "value": "VolumeMigration"}]'
```
Add a volume to a VM:
```bash
$ virtctl addvolume  --volume-name  hotplugdisk vm-dv
```
Check the VM:
```
  status:
    conditions:
[...]
    - lastProbeTime: null
      lastTransitionTime: "2024-08-26T11:14:23Z"
      message: the volumes replacement is effective only after restart
      status: "True"
      type: RestartRequired
```

### PR DESCRIPTION
**Pull request by alicefr**
### What this PR does
Before this PR:
Hotplug is broken when the Volume migration feature gate is enabled. The volume update due to the imperative hotplug are interpreted as a replacement of the volumes.

After this PR:
Hotplug properly works with the volume migration feature gate enabled

Fixes #12670

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by alicefr** [comment]
@awels @mhenriks PTAL

**Comment by mhenriks** [comment]
/approve

@awels looks good to me, what do you think?

**Pull request merged**
