### PR TITLE
tests,libvmi: Append passed options

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
The options that were being passed to the `libvmi.NewFedora` were ignored,
this append them at the end so they can override defaults.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by phoracek — APPROVED** [review]
/approve

**Review by EdDev — APPROVED** [review]
Thank you!

**Pull request merged**
