### PR TITLE
Reduce required memory on guest agent multus test

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Fixes the test on ocp deployments with multus, where less memory is
freely available.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
ci test please

**Comment by rmohr** [comment]
ci test please

**Comment by SchSeba** [comment]
Look like there is an issue starting the pod
```
Pod phase: Pending
```

To be able to understand better why the pod is stuck in pending it will be good to add into the fail dump the `kubectl describe pod` the last part (events)

I think we can do something similar to the kubectl command:

https://github.com/kubernetes/kubernetes/blob/f229aa0ad65a0378645a68ebc7ca2bf65e4957e9/pkg/kubectl/describe/versioned/describe.go#L3279:6

Because if there is a problem with multus or some issue with the kvn/tun/vhost-user allocation we are going to see it only in the events.

This is the relevant part from the test output
```
Pod name: virt-launcher-testvmi27cmmnrc9ndgld4tpcmb8pxmkb2d6q5nvfhz6nknjg	 Pod phase: Pending

metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{"interface":"net1","name":"ovs-net-vlan100","namespace":"kubevirt-test-default"}]'
    k8s.v1.cni.cncf.io/networks-status: ""
    kubevirt.io/domain: testvmi27cmmnrc9ndgld4tpcmb8pxmkb2d6q5nvfhz6q57jkzccmlt
    openshift.io/scc: privileged
  creationTimestamp: 2019-05-21T21:52:51Z
  generateName: virt-launcher-testvmi27cmmnrc9ndgld4tpcmb8pxmkb2d6q5nvfhz6q57jkzccmlt-
  labels:
    kubevirt.io: virt-launcher
    kubevirt.io/created-by: c817527c-7c12-11e9-90d0-525500d15501
  name: virt-launcher-testvmi27cmmnrc9ndgld4tpcmb8pxmkb2d6q5nvfhz6nknjg
  namespace: kubevirt-test-default
  ownerReferences:
  - apiVersion: kubevirt.io/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachineInstance
    name: testvmi27cmmnrc9ndgld4tpcmb8pxmkb2d6q5nvfhz6q57jkzccmlt
    uid: c817527c-7c12-11e9-90d0-525500d15501
  resourceVersion: "24330"
  selfLink: /api/v1/namespaces/kubevirt-test-default/pods/virt-launcher-testvmi27cmmnrc9ndgld4tpcmb8pxmkb2d6q5nvfhz6nknjg
  uid: c819d380-7c12-11e9-90d0-525500d15501
spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - /entry-point.sh
    env:
    - name: COPY_PATH
      value: /var/run/kubevirt-ephemeral-disks/container-disk-data/kubevirt-test-default/testvmi27cmmnrc9ndgld4tpcmb8pxmkb2d6q5nvfhz6q57jkzccmlt/disk_disk0/disk-image
    image: registry:5000/kubevirt/fedora-cloud-container-disk-demo:devel
    imagePullPolicy: IfNotPresent
    name: volumedisk0
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      failureThreshold: 5
      initialDelaySeconds: 2
      periodSeconds: 5
      successThreshold: 2
      timeoutSeconds: 5
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/kubevirt-ephemeral-disks
      name: ephemeral-disks
  - command:
    - /usr/bin/virt-launcher
    - --qemu-timeout
    - 5m
    - --name
    - testvmi27cmmnrc9ndgld4tpcmb8pxmkb2d6q5nvfhz6q57jkzccmlt
    - --uid
    - c817527c-7c12-11e9-90d0-525500d15501
    - --namespace
    - kubevirt-test-default
    - --kubevirt-share-dir
    - /var/run/kubevirt
    - --ephemeral-disk-dir
    - /var/run/kubevirt-ephemeral-disks
    - --readiness-file
    - /var/run/kubevirt-infra/healthy
    - --grace-period-seconds
    - "15"
    - --hook-sidecars
    - "0"
    - --less-pvc-space-toleration
    - "10"
    env:
    - name: KUBEVIRT_RESOURCE_NAME_ovs
    image: registry:5000/kubevirt/virt-launcher:devel
    imagePullPolicy: IfNotPresent
    name: compute
    readinessProbe:
      exec:
        command:
        - cat
        - /var/run/kubevirt-infra/healthy
      failureThreshold: 5
      initialDelaySeconds: 2
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        devices.kubevirt.io/kvm: "1"
        devices.kubevirt.io/tun: "1"
        devices.kubevirt.io/vhost-net: "1"
      requests:
        cpu: 100m
        devices.kubevirt.io/kvm: "1"
        devices.kubevirt.io/tun: "1"
        devices.kubevirt.io/vhost-net: "1"
        memory: "674554432"
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_NICE
      privileged: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/kubevirt-ephemeral-disks
      name: ephemeral-disks
    - mountPath: /var/run/kubevirt
      name: virt-share-dir
    - mountPath: /var/run/libvirt
      name: libvirt-runtime
    - mountPath: /var/run/kubevirt-infra
      name: infra-ready-mount
  dnsPolicy: ClusterFirst
  hostname: testvmi27cmmnrc9ndgld4tpcmb8pxmkb2d6q5nvfhz6q57jkzccmlt
  imagePullSecrets:
  - name: default-dockercfg-tzjbq
  nodeName: node02
  nodeSelector:
    kubevirt.io/schedulable: "true"
    node-role.kubernetes.io/compute: "true"
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 0
    seLinuxOptions:
      type: spc_t
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir: {}
    name: infra-ready-mount
  - hostPath:
      path: /var/run/kubevirt
      type: ""
    name: virt-share-dir
  - emptyDir: {}
    name: libvirt-runtime
  - emptyDir: {}
    name: ephemeral-disks
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-05-21T21:52:52Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-05-21T21:52:52Z
    message: 'containers with unready status: [volumedisk0 compute]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'containers with unready status: [volumedisk0 compute]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2019-05-21T21:52:52Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: registry:5000/kubevirt/virt-launcher:devel
    imageID: ""
    lastState: {}
    name: compute
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: ContainerCreating
  - image: registry:5000/kubevirt/fedora-cloud-container-disk-demo:devel
    imageID: ""
    lastState: {}
    name: volumedisk0
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 192.168.66.102
  phase: Pending
  qosClass: Burstable
  startTime: 2019-05-21T21:52:52Z

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  creationTimestamp: 2019-05-21T21:52:51Z
  finalizers:
  - foregroundDeleteVirtualMachine
  generation: 1
  name: testvmi27cmmnrc9ndgld4tpcmb8pxmkb2d6q5nvfhz6q57jkzccmlt
  namespace: kubevirt-test-default
  resourceVersion: "24297"
  selfLink: /apis/kubevirt.io/v1alpha3/namespaces/kubevirt-test-default/virtualmachineinstances/testvmi27cmmnrc9ndgld4tpcmb8pxmkb2d6q5nvfhz6q57jkzccmlt
  uid: c817527c-7c12-11e9-90d0-525500d15501
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: disk0
      - disk:
          bus: virtio
        name: disk1
      interfaces:
      - bridge: {}
        name: default
      - bridge: {}
        name: ovs
    features:
      acpi:
        enabled: true
    firmware:
      uuid: 358aebfe-48fe-4cb6-9758-2bcef40724a1
    machine:
      type: q35
    resources:
      requests:
        cpu: 100m
        memory: 512M
  networks:
  - name: default
    pod: {}
  - multus:
      networkName: ovs-net-vlan100
    name: ovs
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/fedora-cloud-container-disk-demo:devel
    name: disk0
  - cloudInitNoCloud:
      userDataBase64: IyEvYmluL2Jhc2gKICAgICAgICAgICAgICAgICAgICBlY2hvICJmZWRvcmEiIHxwYXNzd2QgZmVkb3JhIC0tc3RkaW4KICAgICAgICAgICAgICAgICAgICBzZXRlbmZvcmNlIDAKICAgICAgICAgICAgICAgICAgICBpcCBsaW5rIGFkZCBlcDEgdHlwZSB2ZXRoIHBlZXIgbmFtZSBlcDIKICAgICAgICAgICAgICAgICAgICBpcCBhZGRyIGFkZCAxLjAuMC4xMC8yNCBkZXYgZXAxCgkgICAgICAgICAgICAgICAgaXAgYWRkciBhZGQgMS4wLjAuMTEvMjQgZGV2IGVwMgoJICAgICAgICAgICAgICAgIGlwIGFkZHIgYWRkIGZlODA6OmNlM2Q6ODJmZjpmZTUyOjI0YzAvNjQgZGV2IGVwMQoJICAgICAgICAgICAgICAgIGlwIGFkZHIgYWRkIGZlODA6OmNlM2Q6ODJmZjpmZTUyOjI0YzEvNjQgZGV2IGVwMgogICAgICAgICAgICAgICAgICAgIG1rZGlyIC1wIC91c3IvbG9jYWwvYmluCiAgICAgICAgICAgICAgICAgICAgY3VybCBodHRwOi8vY2RpLWh0dHAtaW1wb3J0LXNlcnZlci5rdWJldmlydC9xZW11LWdhID4gL3Vzci9sb2NhbC9iaW4vcWVtdS1nYQogICAgICAgICAgICAgICAgICAgIGNobW9kICt4IC91c3IvbG9jYWwvYmluL3FlbXUtZ2EKICAgICAgICAgICAgICAgICAgICBzeXN0ZW1kLXJ1biAtLXVuaXQ9Z3Vlc3RhZ2VudCAvdXNyL2xvY2FsL2Jpbi9xZW11LWdhCiAgICAgICAgICAgICAgICA=
    name: disk1
status:
  phase: Scheduling

```

**Comment by rmohr** [comment]
/close

@SchSeba fixed the test in #2325

**Pull request closed without merging**
