### PR TITLE
Bump go-iptables version to 0.4.3 to detect version parsing errors.

### PR DESCRIPTION
**Pull request by fedepaol**
**What this PR does / why we need it**:

The latest version of the library contains https://github.com/coreos/go-iptables/pull/69 , which may help in case the scenario described on https://github.com/kubevirt/kubevirt/issues/2660 will happen again.
With this PR we are switching to go-iptables 0.4.3

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE

```

### CODE REVIEW

**Comment by slintes** [comment]
I see no code changes in the vendor dir, I guess you need to run make generate

**Comment by fedepaol** [comment]
> I see no code changes in the vendor dir, I guess you need to run make generate

I did it, just realized it's make deps-update. Good thing you put an eye on this :+1:

**Comment by slintes** [comment]
> > I see no code changes in the vendor dir, I guess you need to run make generate
> 
> I did it, just realized it's make deps-update.

ah yes, sure! :)

**Pull request merged**
