### PR TITLE
Add sevctl to the test image

### PR DESCRIPTION
**Pull request by vasiliy-ul**
**What this PR does / why we need it**:

The PR adds `sevctl` tool to the test image. This is needed for e2e testing of the SEV attestation APIs https://github.com/kubevirt/kubevirt/pull/7197.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

I decided to decouple that part from the attestation PR https://github.com/kubevirt/kubevirt/pull/7197, so it can be reviewed and merged independently as a smaller chunk.

Had to bump edk2 ~and libvirt~ as well:
- current edk2 rpm is not available anymore in the repos
- ~libvirt conflicts with the new edk2~ 

UPD: not picking the latest available edk2 since it will also require a bump of libvirt.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vasiliy-ul** [comment]
As discussed with @andreabolognani in Slack: not picking the latest available edk2 since it will also require a bump of libvirt.

**Comment by vasiliy-ul** [comment]
@alicefr, @iholder101, @xpivarc, @rmohr, @andreabolognani, I decoupled this small change from the SEV PR. Just to make it a bit easier for review in smaller chunks. Would appreciate if you could take a look when have some time and lgtm/approve. Thanks!

**Comment by rmohr** [comment]
/lgtm
/approve

looks great.

**Comment by iholder101** [comment]
Thank you @vasiliy-ul!
/lgtm

**Pull request merged**
