### PR TITLE
Added test_id for probes.go

### PR DESCRIPTION
**Pull request by geetikakay**
Signed-off-by: Geetika Kapoor <gkapoor@redhat.com>

**What this PR does / why we need it**:
Create test id for probes.go 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by geetikakay** [comment]
@akrejcir please review

**Review by xpivarc — COMMENTED** [review]
/approve
@kbidarkar

**Comment by geetikakay** [comment]
@akrejcir Added 'None'

**Comment by geetikakay** [comment]
> @geetikakay a PR needs a release note to be be merged. Can you add `None` to the "Release Note" section of the PR's description?
Done @akrejcir 
> 
> @xpivarc Can you take a look and approve if this is ok?

**Pull request merged**
