### PR TITLE
Vendor CDI up to 1.8.0

### PR DESCRIPTION
**Pull request by mmazur**
**What this PR does / why we need it**: Bumps CDI to 1.8.0

**Special notes for your reviewer**: I've bumped the version in glide.yaml, then ran all of the commands,  lots of things happened, this patch is the result. Seems to work in my limited testing.

**Release note**:

```
Updated vendor/CDI to 1.8.0
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by slintes** [comment]
ci add to whitelist

**Comment by mmazur** [comment]
Yeah, I don't know what CI is complaining about here. I guess update-deps might've updated something I didn't want updated that in turn made something else explode, but I have no way of figuring that out for certain. If someone else could chime in, that'd be great.

**Pull request merged**
