### PR TITLE
handler: aggregate and report all the reasons why a VM isn't migratable

### LINKED ISSUE #12404: List all reasons why LiveMigration is not possible in appropriate condition
**Is your feature request related to a problem? Please describe**:
My problem is that I want to be able to tell my users why live migration is not possible before I attempt a live migration. In particular I want to do a storage live migration. The issue I am having is that only the first issue is listed in the condition on the VM, and not any other issues. This means the user fixes one issue. Then still cannot live migrate and has to check again, fix the next, etc.

**Describe the solution you'd like**:
I would love for the condition to list ALL the issues we have detected instead of just one. This has two benefits. One the user sees all the issues in one place and can attempt to remedy them all at once if possible. Second in my case I am using storage live migration which allows migration of RWO volumes, and if there are other issues my users will never see those issue because the RWO message is the first one shown.

**Describe alternatives you've considered**:
Maybe move the storage conditions to the bottom of the list so it doesn't always show up first.

**Additional context**:
NONE

### PR DESCRIPTION
**Pull request by alicefr**
### What this PR does
Before this PR:
Only the first condition which leads to a not migratable VM is reported, the other can be discovered only when the first is solved.

After this PR:
Better condition reporting for multiple reasons for a not migratable VM.

Fixes #12404 

The initial issue has been reported in relation with volume migration, but this is true for regular migrations as well

### Release note

```release-note
Add new condition MultipleReasonsNotMigratable when the VMI isn't migratable
```

### CODE REVIEW

**Review by fossedihelm — COMMENTED** [review]
Code looks good! I just want to be sure this is something we want to provide. @xpivarc was it by design to only return the first non live migratable condition?

Regarding the code: `newNonMigratableCondition()` can be dropped.
Thank you!

**Comment by alicefr** [comment]
Solution not acceptable, discussion moved to the mailing list

**Pull request closed without merging**
