### PR TITLE
pkg/network/netbinding: Add linter coverage

### PR DESCRIPTION
**Pull request by orelmisan**
### What this PR does
- Break long lines
- Apply gofumpt

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Review by ormergi — APPROVED** [review]
Thanks for the PR, LGTM

**Review by EdDev — COMMENTED** [review]
/approve

There is still a need to approve the `hack/lint-paths.txt` files.
@dhiller , @brianmcarey , can you approve this specific file?

**Comment by dhiller** [comment]
/approve

Not really sure whether that file lint-paths.txt belongs into hack/ folder - maybe it would make sense to have separate files inside the pkg/network, pkg/storage, concatenate them and consume them inside hack/gofumpt.sh and hack/golangci-lint.sh - that way SIG folks could approve themselves? WDYT?

(Not necessarily a task for this PR though)

**Pull request merged**
