### PR TITLE
WIP: Make sure haproxy checks again if DNS entry was not there the first time

### PR DESCRIPTION
**Pull request by rmohr**
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/37)

### CODE REVIEW

**Comment by rmohr** [comment]
Right that should definitely be renamed. Will do that when I am back on this task.

**Comment by fabiand** [comment]
lgtm once Adam's comment is addressed

**Comment by rmohr** [comment]
Still discussing the problems we have with one of the haproxy authors, so sadly not yet ready ....

**Comment by rmohr** [comment]
Seems to not happen anymore

**Pull request closed without merging**
