### PR TITLE
Fix pr leftover mount

### LINKED ISSUE #10172: Leftover mount point from PersistentReservation
**What happened**:
After enabling `PersistentReservation` feature gate, a tmpfs mount point appears on the nodes:
```bash
$ mount | grep daemon
tmpfs on /run/kubevirt/daemons/pr type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
```
It does not disappear if the feature gate is disabled. Also, if `PersistentReservation` is re-enabled once more, multiple mounts are added (and never cleaned-up). 

**What you expected to happen**:
All the resources should be properly cleaned up.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
$ make cluster-up && make cluster-sync
$ ./cluster-up/ssh.sh node01
[vagrant@node01 ~]$ mount | grep daemon # no mounts on the clean install
[vagrant@node01 ~]$ exit
# enable `PersistentReservation` feature gate and wait for re-deployment of KubeVirt
$ kubectl patch -n kubevirt kv kubevirt --type merge -p '{"spec": {"configuration": {"developerConfiguration": {"featureGates": ["PersistentReservation"]}}}}'
$ kubectl -n kubevirt wait kv kubevirt --timeout=100h --for condition=Available
$ ./cluster-up/ssh.sh node01
[vagrant@node01 ~]$ mount | grep daemon # one tmpfs mount appears
tmpfs on /run/kubevirt/daemons/pr type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
[vagrant@node01 ~]$ exit
# disable `PersistentReservation` feature gate and wait for re-deployment of KubeVirt
$ kubectl patch -n kubevirt kv kubevirt --type merge -p '{"spec": {"configuration": {"developerConfiguration": {"featureGates": [""]}}}}'
$ kubectl -n kubevirt wait kv kubevirt --timeout=100h --for condition=Available
$ ./cluster-up/ssh.sh node01
[vagrant@node01 ~]$ mount | grep daemon # the mount is still there
tmpfs on /run/kubevirt/daemons/pr type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
[vagrant@node01 ~]$ exit
# re-enable `PersistentReservation` feature gate and wait for re-deployment of KubeVirt
$ kubectl patch -n kubevirt kv kubevirt --type merge -p '{"spec": {"configuration": {"developerConfiguration": {"featureGates": ["PersistentReservation"]}}}}'
$ kubectl -n kubevirt wait kv kubevirt --timeout=100h --for condition=Available
$ ./cluster-up/ssh.sh node01
[vagrant@node01 ~]$ mount | grep daemon # now several more tmpfs mounts appear
tmpfs on /run/kubevirt/daemons/pr type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /run/kubevirt/daemons/pr type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /run/kubevirt/daemons/pr type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
```

**Additional context**:
I tried to debug the problem and have a few findings:
1. The `pr-helper` container does not terminate properly. It errors out with a message:
    ```
    $ k logs -n kubevirt virt-handler-jrtlw -c pr-helper -f
    qemu-pr-helper: Failed to unlink socket /var/run/kubevirt/daemons/pr/pr-helper.sock: Permission denied
    ```
    This happens because we now set the ownership of the `/var/run/kubevirt/daemons/pr` directory to `107:107` while the container is run under a non-root default user `1001` (which does not have write permissions to that directory). It's weird, but somehow `qemu-pr-helper -k /var/run/kubevirt/daemons/pr/pr-helper.sock` manages to create the socket but fails to delete it (I would assume here that the daemon itself can drop some of the capabilities after initialization, thus the deletion would fail). Initially I thought that was the reason of the leftover mount point, but fixing that did not solve the issues. The fix is just to add `runAsUser: 107` to the `pr-helper` container definition.

2. I tried to make a smaller reproducer with a simple pod, but that does not cause tmpfs mount to appear. So I am not sure where it actually comes from and who/what creates it.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0 and also the main branch
- Kubernetes version (use `kubectl version`): 1.25 (`make cluster-up`)
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by vasiliy-ul**
**What this PR does / why we need it**:

The PR fixes the issues outlined in https://github.com/kubevirt/kubevirt/issues/10172:

- The `pr-helper` container does not terminate properly and reports `Permission denied` error. This happens because the default user for the container is `1001` while the directory where it stores the socket is owned by `107:107 (qemu:qemu)`. Thus, the socket unlink fails.
- Leftover tmpfs mount point on the node. This is likely due to a redundant volume mount of the `pr-helper-socket-vol` in the `virt-handler` container.

Additionally, the PR extends the e2e testing by checking that the resources have been properly cleaned up and also ensures that KubeVirt CR is in ready state before running the actual tests (toggling `PersistentReservation` feature gates triggers redeployment of all the components virt-handler, virt-api, virt-controller, etc. hence it is not enough to wait only for virt-handler).

UPD: added a fix for the race condition mentioned here: https://github.com/kubevirt/kubevirt/pull/10186#issuecomment-1658170870

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10172

**Special notes for your reviewer**:

Please refer to the commit messages for details (each commit is atomic).

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vasiliy-ul** [comment]
```
{ Failure tests/storage/reservation.go:230
Should be able to login to the Fedora VM
Expected success, but got an error:
    <*kubecli.AsyncSubresourceError | 0xc006987218>: 
    Internal error occurred: dialing virt-handler: websocket: bad handshake
    {
        err: "Internal error occurred: dialing virt-handler: websocket: bad handshake",
        StatusCode: 500,
    }
tests/storage/reservation.go:242}
```
Hm.. Locally all the reservation tests were okay when I checked. Will need to debug further. Marking as draft meanwhile.

**Comment by vasiliy-ul** [comment]
> Hm.. Locally all the reservation tests were okay when I checked. Will need to debug further. Marking as draft meanwhile.

So it looks like there is a race condition with selinux permissions. The current implementation relabels the `/var/run/kubevirt/daemons/pr` directory with the expectation that the pr-helper socket will be created **after that**, and it will inherit the new label `system_u:object_r:container_file_t:s0`. In a successful run, it shall look like below:
```console
[root@node01 vagrant]# ls -laZ /var/run/kubevirt/daemons/pr/
total 0
drwxr-xr-x. 2  107  107 system_u:object_r:container_file_t:s0    60 Jul 31 08:47 .
drwxr-xr-x. 3 root root system_u:object_r:container_var_run_t:s0 60 Jul 31 08:47 ..
srwxr-xr-x. 1  107  107 system_u:object_r:container_file_t:s0     0 Jul 31 08:47 pr-helper.sock
```
However, it may happen that pr-helper container will start first and will create the socket **before** virt-handler does proper labeling. In such case, the socket will still have the old label:
``` console
[root@node01 vagrant]# ls -laZ /var/run/kubevirt/daemons/pr/
total 0
drwxr-xr-x. 2  107  107 system_u:object_r:container_file_t:s0    60 Jul 31 09:00 .
drwxr-xr-x. 3 root root system_u:object_r:container_var_run_t:s0 60 Jul 31 09:00 ..
srwxr-xr-x. 1  107 root system_u:object_r:container_var_run_t:s0  0 Jul 31 09:00 pr-helper.sock
```
Eventually, a VM requesting persistent reservation will fail to start with `Permission denied` error (and with the corresponding entry in the `audit.log`).

This needs to be addressed as well.

**Comment by vasiliy-ul** [comment]
> This needs to be addressed as well.

I introduced a mitigation by moving the relabeling of the pr-helper files to the device plugin (when the device is allocated to a VM pod). By that time, we can be sure that there is no race and the socket is already created.

This, however, brought up some other issues. It turns out, it is not possible to use [open(2)](https://man7.org/linux/man-pages/man2/open.2.html) syscall to obtain a writable file descriptor of a unix socket. Such an attempt returns ENXIO and O_PATH will not work for fgetxattr/fsetxattr. Therefore, I've added a separate code flow for sockets. It is based on lgetxattr/lsetxattr ... but then I am a bit concerned about https://github.com/kubevirt/kubevirt/commit/b832389dbe. Any thoughts on that are welcome.

**Comment by vasiliy-ul** [comment]
Hi @rmohr, Just wanted to bring this to your attention, maybe you have some thoughts on that. Here we may need to relabel a unix socket and the current implementation uses `fgetxattr/fsetxattr` (those calls operate on file descriptors). However, it is tricky to get the descriptor of a socket since 1) `open(2)` syscall return `ENXIO` for sockets; 2) `fgetxattr/fsetxattr` will return `EBADF` if opened with `O_PATH`. Hence, I wanted to switch to `lgetxattr` which operates on file paths but then noticed https://github.com/kubevirt/kubevirt/commit/b832389dbe: the commit message states that `lgetxattr` does not return consistent results. I am a bit puzzled here since `lgetxattr` is used also in other projects (e.g. `runc`) and does not seem to cause troubles. I wonder, maybe, you know, if this is also the case with `getxattr`? Would it be safe to switch to it? It is used in `libselinux`:

https://github.com/SELinuxProject/selinux/blob/1d2073557d7199a5cc3ecce9c0cba6cb45a3e726/libselinux/src/fgetfilecon.c#L11

**Comment by rmohr** [comment]
> the commit message states that `lgetxattr` does not return consistent results. I am a bit puzzled here since `lgetxattr` is used also in other projects (e.g. `runc`) and does not seem to cause troubles. I wonder, maybe, you know, if this is also the case with `getxattr`? Would it be safe to switch to it? It is used in `libselinux`

What I can say is that we have seen reports of this in github and we experienced it first hand. In both cases Centos8. With 1.0 out, we could probably argue to not care about this bug in the centos8 kernel version, since centos8 is deprecated? I however did honestly not spend too much time on figuring out what would actually have fixed the issue in the kernel. I would feel more confident if we could  pin down what actually fixed the issue in the kernel.

**Comment by vasiliy-ul** [comment]
> About the syscall, not quite sure. Have you tried to install centos 8 and check if the issue is still present? (Otherwise, I can have a try by creating a socket and using the syscall)

@alicefr, no, I haven't yet tried that on centos 8. My understanding is that the behavior is 'inconsistent' and not always reproducible. If you have a ready installation and have some time, please give it a try. But I am a bit skeptical.

**Comment by vasiliy-ul** [comment]
> Centos 8 mirrors aren't working anymore

IMHO, this is in fact an additional argument in favor of going forward with the lgetxattr-approach. In my opinion, accumulating workarounds to handle external bugs is not a good approach in general. Ideally, I would unify the implementation and switch to using a single approach for relabeling in all the cases. But if we still care too much about keeping compatibility with that centos8 use case, then the implementation in this PR does not change the existing functionality. So it might probably be an acceptable solution.

**Comment by alicefr** [comment]
/approve
/hold

IMO, this looks good, putting a hold if you want to spend more time on the investigation.

**Comment by vasiliy-ul** [comment]
> IMO, this looks good, putting a hold if you want to spend more time on the investigation.

I think for now we can go with the current approach. If someone reports an issue in that area, perhaps we can investigate further.

**Comment by vasiliy-ul** [comment]
@alicefr, btw, I noticed one small issue: currently on the fresh KubeVirt install, if we enable the `PersistentReservation` feature gate, `virt-handler` pod panics here:

https://github.com/kubevirt/kubevirt/blob/9f1ff02c4ec62405cb809a777aa8c2c127298c51/cmd/virt-handler/virt-handler.go#L559-L562

This happens because the change of the CR triggers this callback. The feature gate appears as already enabled, but the socket directory will be created only when the pod is re-deployed with `pr-helper`container. So this results in a crash loop. Perhaps we do not really care, since `virt-handler` will be terminated anyway. Just FYI. Is that the expected behavior?

**Comment by alicefr** [comment]
> @alicefr, btw, I noticed one small issue: currently on the fresh KubeVirt install, if we enable the `PersistentReservation` feature gate, `virt-handler` pod panics here:
> 
> https://github.com/kubevirt/kubevirt/blob/9f1ff02c4ec62405cb809a777aa8c2c127298c51/cmd/virt-handler/virt-handler.go#L559-L562
> 
> This happens because the change of the CR triggers this callback. The feature gate appears as already enabled, but the socket directory will be created only when the pod is re-deployed with `pr-helper`container. So this results in a crash loop. Perhaps we do not really care, since `virt-handler` will be terminated anyway. Just FYI. Is that the expected behavior?

Mmh, I'll avoid all crash loops, they are very confusing imo. Maybe, we should completely remove the function `shouldEnablePersistentReservation` and move the directory chowing where you do the relabeling. WDYT?

**Comment by vasiliy-ul** [comment]
> Maybe, we should completely remove the function shouldEnablePersistentReservation and move the directory chowing where you do the relabeling. WDYT?

Right, that was my thought on that as well, and it is probably the right direction. But then I think we would need to run `pr-helper` as root. Currently, it is run as non-root but since the container is privileged, it has `CAP_DAC_OVERRIDE` so it manages to create the socket. However, later the daemon drops the unneeded caps and then if it  is terminated before the directory is properly chown'ed, it will crash (basically, that is what this PR also fixes for current implemetnation)

**Comment by alicefr** [comment]
> Right, that was my thought on that as well, and it is probably the right direction. But then I think we would need to run `pr-helper` as root. Currently, it is run as non-root but since the container is privileged, it has `CAP_DAC_OVERRIDE` so it manages to create the socket. However, later the daemon drops the unneeded caps and then if it is terminated before the directory is properly chown'ed, it will fail to unlink (basically, that is what this PR also fixes for current implementation)

I'm not a big fan of the idea, but we could wrap the pr-helper command in a script and do the chowing before starting the daemon. I cannot think right now of another simpler solution.

**Comment by alicefr** [comment]
I'm not a big fan of the idea. but we could do the chow of the directory in a script wrapping the pr-helper command if we want to avoid races between the pr-helper container and virt-handler.

**Comment by vasiliy-ul** [comment]
> EDIT: when I did the PR I was assuming (wrongly) that the user a privileged container was 0.

In fact, this is correct, AFAIK. It's just that `pr-helper` container is based on `version-container` which in turn is based on `passwd-image` which has the default user set to `1001`:

https://github.com/kubevirt/kubevirt/blob/9f1ff02c4ec62405cb809a777aa8c2c127298c51/BUILD.bazel#L173

> I'm not a big fan of the idea, but we could wrap the pr-helper command in a script and do the chowing before starting the daemon. I cannot think right now of another simpler solution.

I was also thinking in the direction of using the init-container and `node-labeler.sh` script. But that is not really the scope of that script.


So if we are fine with running pr-helper as root, then probably we can just adjust the user and do the chown in the device plugin.

**Comment by alicefr** [comment]
> So if we are fine with running pr-helper as root, then probably we can just adjust the user and do the chown in the device plugin.

Yes, it seems the easiest approach!  Many thanks for all the investigations!

**Comment by vasiliy-ul** [comment]
Do you want to raise a PR with the fix?

**Comment by alicefr** [comment]
> Do you want to raise a PR with the fix?

Do you mean with root + dropping the function `shouldEnablePersistentReservation`? If so, as you prefer, I don't mind if this is part of this PR.

**Comment by vasiliy-ul** [comment]
> Do you mean with root + dropping the function shouldEnablePersistentReservation? 

Yep.

> If so, as you prefer, I don't mind if this is part of this PR. Otherwise, I can create one.

I'm not sure, I will have time today... So please create one if it's fine for you. I think this PR can go in anyway, and the fix with root may just follow.

**Comment by alicefr** [comment]
@vasiliy-ul do you plan to do the manual backport or should I?

**Comment by vasiliy-ul** [comment]
@alicefr, yes, I will do the backport. Hopefully today)

**Pull request merged**
