### PR TITLE
[release-0.58] Use collector to set migration metrics

### PR DESCRIPTION
**Pull request by machadovilaca**
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/8368

**Release note**:

```release-note
Use collector to set migration metrics
```

### CODE REVIEW

**Review by enp0s3 — COMMENTED** [review]
/approve

**Comment by machadovilaca** [comment]
@enp0s3 @fossedihelm had to update the PR, tests were failing and I noticed an extra set of tests in `tests/monitoring/monitoring.go` from #7918, not sure how

**Comment by fossedihelm** [comment]
> @enp0s3 @fossedihelm had to update the PR, tests were failing and I noticed an extra set of tests in `tests/monitoring/monitoring.go` from #7918, not sure how

Let me check if there are other leftover! Probably you created the branch starting from the other backport PR

**Comment by fossedihelm** [comment]
Ok I think I found the issue: Basically https://github.com/kubevirt/kubevirt/pull/7918 was merged before https://github.com/kubevirt/kubevirt/pull/8368. This means that the latter has some changes based on the first one. Probably the best path will be wait for https://github.com/kubevirt/kubevirt/pull/8747 to be merged and then reapply this. Othewise there is the possibility that some changes will not be cherrypicked. WDYT?
/hold

**Review by fossedihelm — COMMENTED** [review]
Thanks @machadovilaca! Just last thing about the previously removed set of tests.

**Comment by fossedihelm** [comment]
/lgtm
Thanks

**Pull request merged**
