### PR TITLE
dev guide, networking: Update the doc net_admin is still required

### PR DESCRIPTION
**Pull request by AlonaKaplan**
**What this PR does / why we need it**:
net_admin capability was [re-introduced](https://github.com/kubevirt/kubevirt/pull/4645) to virt-launcher.
Update the dev guide accordingly.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
True story.

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
