### PR TITLE
Wait for virt-handler pods after the destructive test

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Probably fixes `virt-handler` failure under https://github.com/kubevirt/kubevirt/issues/1014#issuecomment-389199091
Signed-off-by: Lukianov Artyom <alukiano@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
Hm, in general I like it. However it can bite us if there is a non-schedulable master involved. Maybe we should check for non-schedulable masters?

**Comment by cynepco3hahue** [comment]
@rmohr I still encounter the error with my PR, so I will need to find some other way to recognize that all current virt-handler pods are good and I will add the check for node schedulable state.

**Comment by cynepco3hahue** [comment]
@rmohr Do you want me to check on taints existence or only check for label `kubevirt.io/schedulable=true` is enough?
Because with taints it can be pretty problematic to consider if it `NoSchedule`(you can have different keys with different values)

**Comment by cynepco3hahue** [comment]
@rmohr I think now it more correct, and it avoids toleration checks at all.

**Pull request merged**
