### PR TITLE
Cleanup owner aliases

### PR DESCRIPTION
**Pull request by fabiand**
### What this PR does
Before this PR: We had more but empty and unusued sigs

After this PR: We have less - but used and staffed - sigs

### Why we need it and why it was done in this way
The following tradeoffs were made: Keep the current lis of sigs, but this would require staffing and defining ownership, which is tricky, thus we realign on sig-compute for now

The following alternatives were considered: Keep sigs, but this would require more work to define ownership and update code, htis is too much work that we do not want right now

Links to places where the discussion took place: i.e. https://groups.google.com/g/kubevirt-dev/c/dXvwU6Pon7Y

### Special notes for your reviewer

The decision about sig-node and sig-cluster/scheduling can take place separataely, but should not block this PR.
This PR reflects reality.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by fabiand** [comment]
@xpivarc @acardace please review

cc @iholder101 fyi

**Comment by fabiand** [comment]
cc @enp0s3

**Comment by iholder101** [comment]
While I think that sig-compute would probably be eventually split to some sub-SIGs, I agree that it is more valuable to take the pragmatic approach of starting this process out and refine it later in the future.

/approve

**Comment by dhiller** [comment]
/test 
pull-kubevirt-e2e-windows2016

**Pull request merged**
