### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by victortoso**
**What this PR does / why we need it**: In the docs, fixes a link; updates the path to cluster-up (from cluster)

**Special notes for your reviewer**: Feel free to squash both commits.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by victortoso** [comment]
As per:

> This pull-request has been approved by:
> To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **stu-gott**
> You can assign the PR to them by writing `/assign @stu-gott` in a comment when ready.

/assign @stu-gott

**Comment by victortoso** [comment]
Ping?

**Comment by vladikr** [comment]
I missed this one. 
/approve

**Comment by victortoso** [comment]
/retest
(if I can?)

**Comment by victortoso** [comment]
Well, pull-kubevirt-e2e-k8s-1.17 succeed this last iteration o/

**Comment by xpivarc** [comment]
> Well, pull-kubevirt-e2e-k8s-1.17 succeed this last iteration o/

There are a couple of CI issues that completely blocks meging. We need to wait.

**Comment by victortoso** [comment]
Just k8s-1.17 missing

**Pull request merged**
