### PR TITLE
[release-0.41] Release was again cut without mirrored dependencies

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Update and mirror missing dependencies to restore the build.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by enp0s3 — APPROVED** [review]
/lgtm
/approve

**Comment by enp0s3** [comment]
/hold
need to fix 1.20 lanes in project-infra to check out the correct branch

**Comment by enp0s3** [comment]
/hold cancel
there was some misunderstanding regarding the logs of the failed 1.20 lanes.

**Comment by rmohr** [comment]
/unhold

> need to fix 1.20 lanes in project-infra to check out the correct branch

Don't worry. All is fine. I created the PR by mistake on `master` first. The failing jobs with the strange errors are not defined for `release-0.41` and are therefore not retriggered. We can ignore them.

**Pull request merged**
