### PR TITLE
[SIG-scale] Add the possibility to configure virt-launcher qemu-timeout via virt-controller

### PR DESCRIPTION
**Pull request by marceloamaral**
**What this PR does / why we need it**:
In the recent SIG-scale meeting, we are discussing to run a scale test with more than 110 VMIs per node. 

It is trivial to increase the max number of pods per node, and PR#6098 increased the `virt-handler` max-device to 1000.

However, it is still not possible to create more than 200 VMIs in my environment, because of creating such amount of VMIs the creation process is slow and the `virt-launcher` `qemu` response timeout.

Currently, `virt-launcher` already have `qemu-timeout` flag:
https://github.com/kubevirt/kubevirt/blob/962aabb5f4816066c99b18993513abdca96fcf49/cmd/virt-launcher/virt-launcher.go#L341
However, `virt-launcher` is created and configured by `virt-controller` which does have a flag to configure the `qemu-timeout`.

This PR introduces the possibility to configure `virt-launcher` `qemu-timeout` via `virt-controller`.

Then, it will be possible to patch `KubeVirt` CR, withe the slightly hidden feature in #3612.

For example, creating the file `kubevirt.yaml` to increase the `qemu` timeout to 15mim:
```
spec:
   customizeComponents:
     patches:
     - patch: '[{"op":"add","path":"/spec/template/spec/containers/0/command/-","value":"--launcher-qemu-timeout=900"}]'
       resourceName: virt-controller
       resourceType: Deployment
       type: json
```
And running the following command to patch`KubeVirt` CR:
`kubectl patch --type=merge kubevirt kubevirt -n kubevirt --patch "$(cat kubevirt.yaml)"`

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rthallisey** [comment]
>However, it is still not possible to create more than 200 VMIs in my environment, because of creating such amount of VMIs the creation process is slow and the virt-launcher qemu response timeout
>
How slow?  Why would the last 90 of 200 VMs be slower?  What about other VMI phases, do you see a slow down there too? Or is it only taking too long to for qemu to start?

**Comment by marceloamaral** [comment]
cc @rmohr
cc @rthallisey
cc @davidvossel

**Comment by marceloamaral** [comment]
@rthallisey the default launcher qemu timeout is 3mim. I am not sure how long it takes during the tests, maybe we should log it when higher than 3mim. In the experiments, I tried with 10mim and it worked 2 runs and failed one. Then, I increased to 15mim and it does not timeout anymore.

Regarding the performance, creating 300 VMIs in 3 nodes, the VM creation time was ~5mim, as we saw [here](https://docs.google.com/document/d/1S38AuKl_J2ZcbuN7H3YH9n9sLr2Az6fvQXikBiKy_SM/edit#).
However, creating 300 VMs in only one node, the he VM creation time is ~10mim. 2x slower.
image

Although I am still not sure why, Kubernetes states that the kubelet start getting overloeaded running more than 110 pods per node. Therefore, I am expecting that running 300 VMs, with at least 2 pods per VM (compute volumedisk0), we will already be over the Kubernetes suggestion for small number of nodes. And also higher than the [OpenShift](https://cloud.redhat.com/blog/500_pods_per_node) official report of running with 500 pods per node.

In any case, my goal after having this PR merged, is to analyze overhead of creating VMs within a node versus across nodes. As you can see [here](https://docs.google.com/document/d/1eyvxl0vLWP3oGTaA6ZLYAjBGypjzj1suKaeGpNPpuPA/edit).

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

I'm surprised this timeout get's hit, and even more surprised that increasing it to 15 minutes actually resulted in VMIs finally coming online. It looks like we definitely have some digging to do.

**Pull request merged**
