### PR TITLE
tests: Introduce the `libstorage` sub-package, moving there storage helpers (from utils)

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:
Move storage related helpers from `utils` to a new package `libstorage`.
It includes config, data volumes and storage classes.

This is part of an effort to clean and extract code out of `utils` which is currently overloaded with different helpers from various subjects/verticals.

Another small change related to storage is using `cdi.kubevirt.io/v1beta1` for datavolume (it used `v1alpha1`). 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by brybacki** [comment]
very good change, but needs rebase
/lgtm

**Comment by EdDev** [comment]
> very good change, but needs rebase /lgtm

Thanks!
I rebased now.

**Comment by brybacki** [comment]
@mhenriks this is nice cleanup of the tests with focus on extracting storage utils. WDYT? Do you approve?

**Comment by EdDev** [comment]
change: Rebase

**Pull request merged**
