### PR TITLE
Add a label to all PRs which potentially changes the API

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Add a `kind/api-change` label to every PR which potentially changes the API.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
test1

**Comment by rmohr** [comment]
@stu-gott if I understand the corresponding code in prow correctly, it looks like it only checks merged OWNERS files (which makes a lot of sense).

**Comment by rmohr** [comment]
test

**Comment by rmohr** [comment]
test

**Comment by stu-gott** [comment]
@rmohr ah! so if that's the case, we could either test in a different repo or just clean this PR up and merge it. there's little impact if it's somehow incorrect.

**Comment by rmohr** [comment]
> This is brilliant @rmohr. What a great idea!

@stu-gott just copying: https://github.com/kubernetes/kubernetes/blob/d0b259597a757b7d30b30f063ba032cef291ceac/pkg/api/OWNERS

**Comment by rmohr** [comment]
OWNERS entry will be active once merged. There is now also the `verify-owners` plugin enabled, and I checked in the prow logs that it is active and validated the file.

/hold cancel

**Comment by slintes** [comment]
nice!

**Pull request merged**
