### PR TITLE
cleanup(virtctl): Minor cleanups in virtctl ssh and scp functests

### PR DESCRIPTION
**Pull request by 0xFelix**
### What this PR does

Apply minor cleanups to the virtctl ssh and scp functests:

- Import order
- Format of passed arguments
- Use testsuite.GetTestNamespace(nil) where applicable
- Use NewRepeatableVirtctlCommand instead of manually constructing cmd with CreateCommandWithNS

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by alicefr** [comment]
Same, great job!
/approve

**Comment by brianmcarey** [comment]
/hold

@0xFelix the sig-compute test failures look relevant to me.

**Comment by 0xFelix** [comment]
Reverted the change that caused the issue.

/hold cancel

**Comment by jcanocan** [comment]
Nice catch @brianmcarey!
/lgtm

**Comment by 0xFelix** [comment]
/hold cancel

Cannot replace `CreateCommandWithNS` with `NewRepeatableVirtctlCommand`. Added comments explaining why.

**Comment by dhiller** [comment]
@0xFelix there's flakiness on the virtctl test going on: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12804/pull-kubevirt-check-tests-for-flakes/1833873011611013121

I'll create an issue for this.

**Comment by 0xFelix** [comment]
@dhiller All tests failing in a recent run of `check-tests-for-flakes` have the `exclude-native-ssh` decorator.

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12804/pull-kubevirt-check-tests-for-flakes/1834166102834286592

These can only pass when the binary was built with the `excludenative` flag.

**Comment by jcanocan** [comment]
Happy to see further improvement points.
/lgtm

**Pull request merged**
