### PR TITLE
docs: make it clear kubevirt-ansible is recommended for sriov

### PR DESCRIPTION
**Pull request by booxter**
Now that kubevirt-ansible automatically deploys all the relevant
SR-IOV components on cluster, we should recommend using it unless one
has a legit reason not to (for example, to deploy kubevirt from
sources).

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by booxter** [comment]
Sebastian I personally don't know if that's possible to use kubevirt-ansible with local provider. Have you tried it?

**Comment by SchSeba** [comment]
Sorry I mean with the external provider.

I just want to said that you can add to the document the ability of deploy only multus and the sriov DP and not the kubevirt.yaml ansible playbook.

**Comment by booxter** [comment]
@SchSeba I'm trying to understand the goal for your suggestion. Is it to document options available in kubevirt-ansible? If so, I don't think kubevirt repository is the right place to deep dive.

My goal with this tiny PR is to make sure that readers are aware of a better tool to deploy discussed components, and that they explicitly opt in to deploy from sources (perhaps because they want to develop some new SR-IOV featuresin kubevirt or one of SR-IOV components). I would think that this tiny PR achieves this goal, and adding more details about all the different options that kubevirt-ansible repository provides would not improve for this particular goal.

**Comment by SchSeba** [comment]
sounds good to me

**Comment by booxter** [comment]
@vladikr could you please help with getting this merged? It's a tiny doc update. Thanks.

**Pull request merged**
