### PR TITLE
hack: add [sig-performance] label as possible asigned test

### PR DESCRIPTION
**Pull request by marceloamaral**
Signed-off-by: Marcelo Amaral <marcelo.amaral1@ibm.com>

**What this PR does / why we need it**:

 add [sig-performance] label as possible assigned test

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5835

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by marceloamaral** [comment]
cc @fgimenez

**Review by fgimenez — APPROVED** [review]
/lgtm

Thanks!

**Comment by marceloamaral** [comment]
@fgimenez could you approve?

**Comment by fgimenez** [comment]
> @fgimenez could you approve?

I have already approved, but I'm not one of the approvers here https://github.com/kubevirt/kubevirt/blob/main/OWNERS_ALIASES#L4-L17 maybe @enp0s3 can take a look?

**Review by enp0s3 — APPROVED** [review]
@marceloamaral Thank you! a small nit - can you please change `asigned` to `assigned` in PR desc. and in commit msg?
/approve
/release-note-none

**Comment by enp0s3** [comment]
@marceloamaral Sorry I forgot to mention - In the PR comments the `release-note` should include `NONE` string, or it should not appear.

**Comment by marceloamaral** [comment]
@enp0s3 I fixed the typo error
@fgimenez I updated the release note
Could you please approve and lgtm again?

**Review by fgimenez — APPROVED** [review]
/lgtm

Thanks!

**Comment by marceloamaral** [comment]
\retest

**Comment by fgimenez** [comment]
Some of the sig-storage tests are very flaky https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5978/pull-kubevirt-e2e-k8s-1.20-sig-storage/1413288247768911872 this will help #5998

**Comment by fgimenez** [comment]
> Fixes #5835

@marceloamaral I think this ^^^ in the description of this PR was not intended, right? now #5835 is closed

**Comment by marceloamaral** [comment]
Yes, it was a mistake.... I will reopen #5835

**Pull request merged**
