### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by hs0210**
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>

**What this PR does / why we need it**:
Fix misspelling: directiories --> directories

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
/approve cancel
/hold

@hs0210 thank you for the PR. The code which you are changing here is synchronized from https://github.com/kubevirt/kubevirtci. I fear we need a PR there to fix it, so that it finally lands here.

**Comment by rmohr** [comment]
@ashleyschuett I merged a similar PR lately by accident and hat to revert https://github.com/kubevirt/kubevirt/pull/4826

**Comment by hs0210** [comment]
@rmohr Does this mean I need to close this PR and submit a PR in  https://github.com/kubevirt/kubevirtci ？

**Comment by hs0210** [comment]
@rmohr I have opened a PR in https://github.com/kubevirt/kubevirtci/pull/539.

**Pull request closed without merging**
