### PR TITLE
Fix hotplug volume has a io error when use iscsi protocol csi plugin

### LINKED ISSUE #6564: ADD hotplug volume more than one will cause io error
**What happened**:
when I first add one hotplug volume to a vm ,everything is ok.
but when I second add one or more volume to a vm ,hotplug volume was added before will appear the io error.
**What you expected to happen**:
vm will be paused , because the io error
**How to reproduce it (as minimally and precisely as possible)**:
you can try add hotplug volume in the different time to a vm.

**Anything else we need to know?**:
hotplug volume is use block mode

**Environment**:
- KubeVirt version (use `0.44.0`):

### PR DESCRIPTION
**Pull request by watermelon-brother**
**What this PR does / why we need it**:
Now, virt-controller can delete old attachment pod when the new attachmentpod is running.So,It can't cause the volume  iscsi connection break when delete the old attachment pod.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6564 

**Special notes for your reviewer**:

**Release note**:
None

### CODE REVIEW

**Comment by awels** [comment]
Try running make generate locally and see if that generates any files. The verify is complaining that the state is not clean. The test runs a make generate and sees if anything different from what the PR provides.

**Comment by watermelon-brother** [comment]
make generate and make locally is ok,but online was failed,why? @awels

**Comment by awels** [comment]
So I see some unit test failures in the unit test lane. and in the generate lane I see https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6701/pull-kubevirt-generate/1455444743445024768 which indicates something is not updated, and it tells you to run make generate, which should generate something new. The builds are failing because it is reporting the git state is not clean. Are you sure you committed all the changed files? make generate can generate a bunch of new files that need to be added.

**Pull request closed without merging**
