### PR TITLE
Address sig-storage flakes with in memory etcd

### PR DESCRIPTION
**Pull request by mhenriks**
**What this PR does / why we need it**:

There should always be a VolumeSnapshotClass for "rook-ceph-block" StorageClass.  But the vmsnapshot controller may not have initialized it's VolumeSNapshotClass informer before processing VMSnapshot work items.  Especially in failover/restart situations 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mhenriks** [comment]
attn @akalenyu @awels

**Review by awels — APPROVED** [review]
/lgtm

**Pull request merged**
