### PR TITLE
update hash in vendor file

### PR DESCRIPTION
**Pull request by admiyo**

### CODE REVIEW

**Comment by rmohr** [comment]
Interesting. I always get this diff when I run `make sync` on master:

```
diff --git a/vendor/vendor.json b/vendor/vendor.json
index d0f73f7..e458718 100644
--- a/vendor/vendor.json
+++ b/vendor/vendor.json
@@ -350,7 +350,7 @@
                        "revisionTime": "2016-09-12T16:56:03Z"
                },
                {
-                       "checksumSHA1": "GhPrz8c5VPQmL8TJb47N48TYJH0=",
+                       "checksumSHA1": "kG3Cpk6/MJgArx5rR8YGAmwenZQ=",
                        "origin": "github.com/kubernetes/apimachinery",
                        "path": "k8s.io/apimachinery",
                        "revision": "75b8dd260ef0469d96d578705a87cffd0e09dab8",
@@ -358,7 +358,7 @@
                        "tree": true
                },
                {
-                       "checksumSHA1": "sWR6z1PXXu3D3cEDYfSbf0QTHZc=",
+                       "checksumSHA1": "80DpRsMuo3NZYVYCozAy6/lOUfI=",
                        "origin": "github.com/kubernetes/client-go",
                        "path": "k8s.io/client-go",
                        "revision": "3627aeb7d4f6ade38f995d2c923e459146493c7e",
```
but I don't get yours ...

**Comment by rmohr** [comment]
@davidvossel I see this diff since the client-go update. Do you see that as well?

**Comment by stu-gott** [comment]
For me, the results of `make sync` match @admiyo's

**Comment by davidvossel** [comment]
I get the same as Adam.

**Comment by admiyo** [comment]
please retest this

**Comment by berrange** [comment]
I saw the same as @rmohr for a while. Eventually I have deleted $GOPATH/.cache and $GOPATH/pkg and now see the same diff as @admiyo has proposed here. So I think this is the right fix - any differences are something stale either in the govendor cache, or oudated govendor code.

**Pull request merged**
