### PR TITLE
[release-0.36] Fix RBAC subresource permissions for admin/edit/view roles

### PR DESCRIPTION
**Pull request by rmohr**
This is a manual backport of #6147.

```release-note
Fix rbac permissions for freeze/unfreeze, addvolume/removevolume, guestosinfo, filesystemlist and userlist
```

### CODE REVIEW

**Comment by rmohr** [comment]
> pull-kubevirt-e2e-k8s-1.18

The test history shows that the changed tests still work and that there is nothing failing consistently. Should be ok from that perspective. On 0.36 the tests are not super stable.

**Comment by vladikr** [comment]
> > pull-kubevirt-e2e-k8s-1.18
> 
> The test history shows that the changed tests still work and that there is nothing failing consistently. Should be ok from that perspective. On 0.36 the tests are not super stable.

ok, I was worried that I've missed something.

/approve
/lgtm

**Pull request merged**
