### PR TITLE
Expose libvirtd logs to kubectl logs

### LINKED ISSUE #1310: Not able to debug libvirt issues if launcher crashes
**What happened**:
A VM fails to start, the pod logs hint that it's a libvirt issues:

```
level=info timestamp=2018-07-13T09:22:14.125248Z pos=libvirt.go:256 component=virt-launcher msg="Connecting to libvirt daemon: qemu:///system"

level=error timestamp=2018-07-13T09:22:14.207290Z pos=libvirt_helper.go:146 component=virt-launcher msg="libvirtd exited, restarting"

level=error timestamp=2018-07-13T09:22:15.244135Z pos=libvirt_helper.go:146 component=virt-launcher msg="libvirtd exited, restarting"

level=error timestamp=2018-07-13T09:22:16.280373Z pos=libvirt_helper.go:146 component=virt-launcher msg="libvirtd exited, restarting"
…
panic: failed to connect to libvirtd: cannot connect to libvirt daemon: timed out waiting for the condition

goroutine 1 [running]:

main.createLibvirtConnection(0xc4200b4d80, 0x11f4c80)

    /root/go/src/kubevirt.io/kubevirt/cmd/virt-launcher/virt-launcher.go:111 +0x125

main.main()

    /root/go/src/kubevirt.io/kubevirt/cmd/virt-launcher/virt-launcher.go:253 +0x440

virt-launcher exited with code 2
```

When trying to exec into the compute pod, this fails, because the container continues to crash.

**What you expected to happen**:
Either get the libvirt logs on the pod logs. Or ability to log into the pod to debug libvirt

**How to reproduce it (as minimally and precisely as possible)**:
Make virt-launcher crash and try to debug libvirt

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.7.0-alpha.2
- Kubernetes version (use `kubectl version`): 1.11
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by slintes**
**What this PR does / why we need it**:

Expose libvirtd logs to `kubectl logs` by
- Configure libvirtd to log to stderr
- Redirect libvirtd's stderr to virt-launchers stdout

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #1310

**Special notes for your reviewer**:

**Release note**:
```release-note
Expose libvirtd logs to kubectl logs
```

### CODE REVIEW

**Comment by slintes** [comment]
retest this please

**Comment by michalskrivanek** [comment]
if "1" here enables debug logging (it should, but there might be other options elsewhere) and the intention is to indeed have debug logging then it's very chatty. I'm not sure how much disk space there is, but normally this is always too much (in order of GBs after a while), problematic for any production.
Still, it's the only level producing useful information:)

**Comment by slintes** [comment]
@davidvossel @michalskrivanek when I understand the logging configuration correctly (https://libvirt.org/logging.html), with `log_outputs=1:stderr` I only define that every log level should log to stderr, but I don't change **what** actually is logged, right? When I tested this (but only creating a vm) logs weren't too chatty imho, e.g.:

```$ k logs virt-launcher-testvm1-q78fj compute
level=info timestamp=2018-07-31T20:29:58.632194Z pos=manager.go:69 component=virt-launcher msg="Collected all requested hook sidecar sockets"
level=info timestamp=2018-07-31T20:29:58.632872Z pos=manager.go:72 component=virt-launcher msg="Sorted all collected sidecar sockets per hook point based on their priority and name: map[]"
level=info timestamp=2018-07-31T20:29:58.633393Z pos=libvirt.go:261 component=virt-launcher msg="Connecting to libvirt daemon: qemu:///system"
+ mkdir -p /var/log/kubevirt
+ touch /var/log/kubevirt/qemu-kube.log
+ chown qemu:qemu /var/log/kubevirt/qemu-kube.log
+ [[ -z '' ]]
++ ip -o -4 a
++ grep -v -e '^lo[0-9:]*$'
++ tr -s ' '
++ cut '-d ' -f 2
++ head -1
Selected "eth0" as primary interface
Setting libvirt default network to "eth0"
+ LIBVIRTD_DEFAULT_NETWORK_DEVICE=eth0
+ echo 'Selected "eth0" as primary interface'
+ [[ -n eth0 ]]
+ echo 'Setting libvirt default network to "eth0"'
+ mkdir -p /etc/libvirt/qemu/networks/autostart
+ cat
+ ln -s -f /etc/libvirt/qemu/networks/default.xml /etc/libvirt/qemu/networks/autostart/default.xml
+ echo 'cgroup_controllers = [ ]'
+ '[' -d /dev/hugepages ']'
+ echo 'log_outputs = "1:stderr"'
+ /usr/sbin/libvirtd
2018-07-31 20:29:58.745+0000: 46: info : libvirt version: 4.2.0, package: 1.fc28 (Unknown, 2018-04-04-03:04:18, a0570af3fea64d0ba2df52242c71403f)
2018-07-31 20:29:58.745+0000: 46: info : hostname: testvm1
2018-07-31 20:29:58.745+0000: 46: error : virDBusGetSystemBus:109 : internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2018-07-31 20:29:59.142+0000: 46: error : virDBusGetSystemBus:109 : internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2018-07-31 20:29:59.142+0000: 46: warning : networkStateInitialize:763 : DBus not available, disabling firewalld support in bridge_network_driver: internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2018-07-31 20:29:59.176+0000: 50: error : virPCIDeviceConfigOpen:312 : Failed to open config space file '/sys/bus/pci/devices/0000:00:00.0/config': Read-only file system
2018-07-31 20:29:59.177+0000: 50: error : virPCIDeviceConfigOpen:312 : Failed to open config space file '/sys/bus/pci/devices/0000:00:01.0/config': Read-only file system
2018-07-31 20:29:59.178+0000: 50: error : virPCIDeviceConfigOpen:312 : Failed to open config space file '/sys/bus/pci/devices/0000:00:01.1/config': Read-only file system
2018-07-31 20:29:59.180+0000: 50: error : virPCIDeviceConfigOpen:312 : Failed to open config space file '/sys/bus/pci/devices/0000:00:01.3/config': Read-only file system
2018-07-31 20:29:59.193+0000: 50: error : virPCIDeviceConfigOpen:312 : Failed to open config space file '/sys/bus/pci/devices/0000:00:02.0/config': Read-only file system
2018-07-31 20:29:59.197+0000: 50: error : virPCIDeviceConfigOpen:312 : Failed to open config space file '/sys/bus/pci/devices/0000:00:03.0/config': Read-only file system
2018-07-31 20:29:59.197+0000: 50: error : virPCIDeviceConfigOpen:312 : Failed to open config space file '/sys/bus/pci/devices/0000:00:04.0/config': Read-only file system
2018-07-31 20:29:59.197+0000: 50: error : virPCIDeviceConfigOpen:312 : Failed to open config space file '/sys/bus/pci/devices/0000:00:05.0/config': Read-only file system
2018-07-31 20:29:59.780+0000: 46: error : virCommandWait:2600 : internal error: Child process (/usr/sbin/dmidecode -q -t 0,1,2,3,4,17) unexpected exit status 1: /dev/mem: No such file or directory

2018-07-31 20:29:59.790+0000: 46: error : virNodeSuspendSupportsTarget:336 : internal error: Cannot probe for supported suspend types
2018-07-31 20:29:59.790+0000: 46: warning : virQEMUCapsInit:1229 : Failed to get host power management capabilities
level=info timestamp=2018-07-31T20:30:08.639692Z pos=libvirt.go:276 component=virt-launcher msg="Connected to libvirt daemon"
level=info timestamp=2018-07-31T20:30:08.695002Z pos=virt-launcher.go:143 component=virt-launcher msg="Watchdog file created at /var/run/kubevirt/watchdog-files/default_testvm1"
level=info timestamp=2018-07-31T20:30:08.696439Z pos=client.go:152 component=virt-launcher msg="Registered libvirt event notify callback"
level=info timestamp=2018-07-31T20:30:08.696740Z pos=virt-launcher.go:60 component=virt-launcher msg="Marked as ready"
level=error timestamp=2018-07-31T20:30:08.967462Z pos=common.go:126 component=virt-launcher msg="updated MAC for interface: eth0 - 0a:58:0a:d5:c6:c6"
level=info timestamp=2018-07-31T20:30:08.968157Z pos=converter.go:751 component=virt-launcher msg="Found nameservers in /etc/resolv.conf: \n`\u0000\n"
level=info timestamp=2018-07-31T20:30:08.968173Z pos=converter.go:752 component=virt-launcher msg="Found search domains in /etc/resolv.conf: default.svc.cluster.local svc.cluster.local cluster.local"
level=info timestamp=2018-07-31T20:30:08.968963Z pos=dhcp.go:62 component=virt-launcher msg="Starting SingleClientDHCPServer"
level=info timestamp=2018-07-31T20:30:08.996124Z pos=manager.go:158 component=virt-launcher namespace=default name=testvm1 kind= uid=73083f06-9500-11e8-8273-525500d15501 msg="Domain defined."
level=info timestamp=2018-07-31T20:30:08.996262Z pos=client.go:136 component=virt-launcher msg="Libvirt event 0 with reason 0 received"
2018-07-31 20:30:09.015+0000: 35: error : virDBusGetSystemBus:109 : internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2018-07-31 20:30:09.035+0000: 35: warning : qemuInterfaceOpenVhostNet:687 : Unable to open vhost-net. Opened so far 0, requested 1
2018-07-31 20:30:09.145+0000: 35: error : virCgroupDetect:714 : At least one cgroup controller is required: No such device or address
level=info timestamp=2018-07-31T20:30:09.147728Z pos=client.go:119 component=virt-launcher msg="domain status: 3:11"
level=info timestamp=2018-07-31T20:30:09.154325Z pos=client.go:145 component=virt-launcher msg="processed event"
level=info timestamp=2018-07-31T20:30:09.221890Z pos=client.go:136 component=virt-launcher msg="Libvirt event 4 with reason 0 received"
level=info timestamp=2018-07-31T20:30:09.239242Z pos=client.go:119 component=virt-launcher msg="domain status: 1:1"
level=info timestamp=2018-07-31T20:30:09.240230Z pos=client.go:145 component=virt-launcher msg="processed event"
level=info timestamp=2018-07-31T20:30:09.246999Z pos=client.go:136 component=virt-launcher msg="Libvirt event 2 with reason 0 received"
level=info timestamp=2018-07-31T20:30:09.247658Z pos=manager.go:189 component=virt-launcher namespace=default name=testvm1 kind= uid=73083f06-9500-11e8-8273-525500d15501 msg="Domain started."
level=info timestamp=2018-07-31T20:30:09.248149Z pos=server.go:74 component=virt-launcher namespace=default name=testvm1 kind= uid=73083f06-9500-11e8-8273-525500d15501 msg="Synced vmi"
level=info timestamp=2018-07-31T20:30:09.252035Z pos=client.go:119 component=virt-launcher msg="domain status: 1:1"
level=info timestamp=2018-07-31T20:30:09.253510Z pos=client.go:145 component=virt-launcher msg="processed event"
level=info timestamp=2018-07-31T20:30:09.265052Z pos=server.go:74 component=virt-launcher namespace=default name=testvm1 kind= uid=73083f06-9500-11e8-8273-525500d15501 msg="Synced vmi"
level=info timestamp=2018-07-31T20:30:09.702388Z pos=virt-launcher.go:214 component=virt-launcher msg="Detected domain with UUID cfb867c9-fa3a-51f5-b0f5-485fd556fd68"
level=info timestamp=2018-07-31T20:30:09.702546Z pos=monitor.go:253 component=virt-launcher msg="Monitoring loop: rate 1s start timeout 5m0s"
level=info timestamp=2018-07-31T20:30:10.704495Z pos=monitor.go:222 component=virt-launcher msg="Found PID for cfb867c9-fa3a-51f5-b0f5-485fd556fd68: 171"```

**Comment by michalskrivanek** [comment]
LGTM then. Debug is the one to avoid. The only useful information is in debug, sadly:)
But of course info,warn,err is still better than nothing

**Pull request merged**
