### PR TITLE
add Kubermatic to adopters list

### PR DESCRIPTION
**Pull request by mfranczy**
Signed-off-by: Marcin Franczyk <marcin.franczyk@kubermatic.com>

**What this PR does / why we need it**:
This PR adds Kubermatic to adopters list.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Comment by mfranczy** [comment]
@davidvossel hey, thanks for the approval, I had a quick talk with @dankenigsberg about improving this PR a bit, I will add a better description.

/hold

**Review by dankenigsberg — APPROVED** [review]

**Pull request merged**
