### PR TITLE
Remove config-map warning

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
Config-map support was removed in v0.48.0, let`s
drop the warning as all users should migrate already and upgrade path from v0.48 to today's version is not possible.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
Thank you! Changes look good to me.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Pull request merged**
