### PR TITLE
Expose tsc-timer frequency and scalability on nodes via node-labeller

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

The first part of a series of PRs which will eventually allow VMIs to be migratable with passed through `invtsc` cpu flag.

The first part is focused solely on the node and changes the node-laballer to expose the frequency and if the timer is scalable.
For this purpose two new labels are exposed.

1. `cpu-timer.node.kubevirt.io/tsc-frequency` reporting the frequency of the tsc timer on the node in Hz
2. `cpu-timer.node.kubevirt.io/tsc-scalable` reporting via `true/false` if the tsc timer supports frequency scaling

This information is collected by calling `virsh capabilities` and processed like other labels which use `virsh domcapabilities` to query some node information.

In one or more follow-up PRs this information will be used to set a minimal cluster-compatible tsc frequency on VMIs which request the `invtsc` cpu flag as well as to calculate labels for the scheduler to allow doing migrations with these VMIs to compatible nodes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

The PR also improves the testing code of the node-labeller to not rely on big inlinde xml files and by getting rid of absolute paths which required certain permissions to be written to.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by ksimon1 — COMMENTED** [review]
/lgtm

**Review by davidvossel — APPROVED** [review]
/approve

**Pull request merged**
