### PR TITLE
Updating the README.md file to align with project state

### LINKED ISSUE #2761: Update README.md to align with the project state and with kubevirt.io
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

Two things:
* Our README.md represents the project state from a very long time ago.
* irc is still listed as our main live-communication channel. Realistically it is now #virtualization in k8s slack

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by alosadagrande**
Signed-off-by: Alberto Losada <alosadag@redhat.com>

**What this PR does / why we need it**:

Keep the README.md updated and align with the project state

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2761 

**Special notes for your reviewer**:

It is replaced the chat information to contact with KubeVirt community. It has been added further resources to run and manage KubeVirt: blog and video channel.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by alosadagrande** [comment]
cc/ @rmohr

**Comment by rmohr** [comment]
Thanks a lot!

**Pull request merged**
