### PR TITLE
add myself as a code reviewer

### PR DESCRIPTION
**Pull request by alonSadan**
**What this PR does / why we need it**:

add me as code-reviewer 

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
Please add release label

**Comment by cynepco3hahue** [comment]
After some thoughts, `/lgtm` for the whole project is too broad, we can discuss it again after additional code contributions.
@SchSeba @phoracek Guys, in your opinion, will it be fine to add @alonSadan as `lgtm` for network packages under the KubeVirt?

**Comment by rmohr** [comment]
Let me just add that independent of `/lgtm` rights or not, any code review is very welcome.

**Comment by phoracek** [comment]
@cynepco3hahue I'm all for adding Alon to network modules reviewers.

**Comment by phoracek** [comment]
If @alonSadan really wants to take that responsibility.

**Comment by alonSadan** [comment]
I Think there is a misunderstanding - all I would like is to not wait for the _ok-to-test_ lable to run  CI tests. 
Thanks, and sorry for that.

**Pull request closed without merging**
