### PR TITLE
tests, utils: Remove unused functions

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

Remove unused functions from tests/utils.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by Barakmor1** [comment]
/lgtm
Nice!

**Comment by dhiller** [comment]
> /lgtm Nice! @dhiller why didn't it increase coverage?

In general only non-test code is subject to coverage measure. The tests themselves or code related to these are not subject to measure.

See [`./hack/coverage.sh`https://github.com/kubevirt/kubevirt/blob/9aeae16c723fa76fbe4cf33d694f04f601399ace/hack/coverage.sh#L16) for a definition of where the coverage is measured. Besides that, currently we only measure coverage for unit tests, not for functional tests.

**Comment by EdDev** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **phoracek** after the PR has been reviewed. You can assign the PR to them by writing `/assign @phoracek` in a comment when ready.

@phoracek , could you please have a look?

/assign @phoracek

**Review by phoracek — APPROVED** [review]
/approve

**Pull request merged**
