### PR TITLE
network, bridge binding: Enable container interface

### PR DESCRIPTION
**Pull request by ormergi**
**What this PR does / why we need it**:
Migrating a VM with secondary interfaces that uses bridge binding may cause long
periods of traffic disruption. This occurs when the interface is defined with an
explicit MAC address (manually or automatically through KubeMacPool) on nodes
that have IPv6 enabled.

During the migration, frames may be forwarded to the destination node while the
domain is active on the source and still not running at the destination.

When the migration destination pod is created an IPv6 NS (Neighbor Solicitation)
and NA (Neighbor Advertisement) are sent automatically by the kernel.
The switches at the endpoints (e.g.: migration destination node) tables
get updated and the traffic is forwarded to the migration destination before
the migration is completed [1].

Assuming the used bridge CNI to connect the pod to the node can create the pod
interface in a "link-down" state [2], the IPv6 NS/NA packets are avoided.
However, there is a need to explicitly set the "link-up" when Kubevirt later
processes them.

As part of the pod network configuration calculation, Kubevirt now explicitly
asks to set the relevant interfaces for the bridge binding as "UP".

Fixes: https://issues.redhat.com/browse/CNV-28040
    
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2186372#c6
[2] https://github.com/containernetworking/plugins/issues/951

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
Bug fix: Packet drops during the initial phase of VM live migration https://issues.redhat.com/browse/CNV-28040
```

### CODE REVIEW

**Comment by ormergi** [comment]
I have verified this PR and /containernetworking/plugins/issues/951 changes fixes the bug, here is how:
env:
Three nodes cluster, each node have:
- The original bridge CNI and a modified one (with https://github.com/containernetworking/plugins/issues/951 changes)
- tcpdump probing secondary interface connected to bridge.
Two VMs, client and target:
- Target VM has anti-affinity rule to not run on the same node as client VM.
- Client VM pings the target through the secondary bridge network.
- While the client VM pings, the target VM is migrated.

This test has two flavors: 
1. Kubevirt from main branch, original bridge CNI
2. Kubevirt for this PR branch, modified bridge CNI (w https://github.com/containernetworking/plugins/issues/951 changes).
Each flavor ran few times.

We can see from the client VM ping statistics there are less packet drops:
```
original bridge CNI and kubevirt:
$ cat test-migration-packet-drops/original-bridge-cni-1/ping-stats | grep rec
311 packets transmitted, 257 received, 17.3633% packet loss, time 31477ms
$ cat test-migration-packet-drops/original-bridge-cni-2/ping-stats | grep rec
305 packets transmitted, 255 received, 16.3934% packet loss, time 30866ms
$ cat test-migration-packet-drops/original-bridge-cni-3/ping-stats | grep rec
313 packets transmitted, 301 received, 3.83387% packet loss, time 31468ms
$ cat test-migration-packet-drops/original-bridge-cni-4/ping-stats | grep rec
316 packets transmitted, 311 received, 1.58228% packet loss, time 31761ms
$ cat test-migration-packet-drops/original-bridge-cni-5/ping-stats | grep rec
316 packets transmitted, 261 received, 17.4051% packet loss, time 32014ms
```
modified original bridge CNI and kubevirt:
```
$ cat test-migration-packet-drops/modified-bridge-cni-1/ping-stats | grep rec
301 packets transmitted, 299 received, 0.664452% packet loss, time 30232ms
$ cat test-migration-packet-drops/modified-bridge-cni-2/ping-stats | grep rec
314 packets transmitted, 312 received, 0.636943% packet loss, time 31539ms
$ cat test-migration-packet-drops/modified-bridge-cni-3/ping-stats | grep rec
316 packets transmitted, 314 received, 0.632911% packet loss, time 31733ms
$ cat test-migration-packet-drops/modified-bridge-cni-4/ping-stats | grep rec
312 packets transmitted, 310 received, 0.641026% packet loss, time 31344ms
$ cat test-migration-packet-drops/modified-bridge-cni-5/ping-stats | grep rec
310 packets transmitted, 308 received, 0.645161% packet loss, time 31145ms
```
tcpdump logs on the migration destination node we see no packets get miss-routed during the migration.

**Review by EdDev — COMMENTED** [review]
Thank you.
My comments are about the commit/PR message.


> In a scenario where a VM with a bridge binding interface set with MAC address
> (e.g.: by human or KubeMacPool) on a cluster with IPv6 enabled (dual stack
> or IPv6 single stack) is migrated, we observe packet drops at the inbound traffic
> to the VM immediately after the migration target pod starts.
> These packets are getting routed to the destination node before the migration
> completes.

Migrating a VM with secondary interfaces that uses bridge binding may cause long periods of traffic disruption. This occurs when the interface is defined with an explicit MAC address (manually or automatically through KubeMacPool) on nodes that have IPv6 enabled.

During the migration period, frames may be forwarded to the destination node while the domain is active on the source and still not running on the target.

> When the migration target pod is created an IPv6 NS (Neighbor Solicitation)
> and NA (Neighbor Advertisement) are sent automatically by the kernel.
> The switches at the endpoints (e.g.: migration destination node) tables
> get updated and the traffic is routed to the migration destination before
> the migration is completed [1].

This is occurring at the ethernet (L2) level, so "routing" is confusing. Better use "forwarded".
Maybe some parts here are duplicated from my suggestion above. Perhaps it is better to leave this section with the details of why the frames are forwarder to the target.

> Following the bridge CNI RFE to disable the container interface to prevent the
> container interface from sending IPv6 NS/NA [2], set bridge binding
> interfaces' container interface state to up.

Please try to improve this sentence, it is hard to understand it.

For example:
Assuming the CNI used to connect the pod to the node can create the pod interface in a "link-down" state [ref the CNI plugin PR], the IPv6 NS/NA packets are avoided. However, there is a need to explicitly set the "link-up" when Kubevirt later processes them.

As part of the pod network configuration calculation, Kubevirt now explicitly asks to set the relevant interfaces for the bridge binding as "UP".

**Comment by ormergi** [comment]
@EdDev thanks for the suggestions, please take another look :slightly_smiling_face:

**Review by EdDev — APPROVED** [review]
Thanks! Very clean.

**Pull request merged**
