### PR TITLE
cleanup(virtctl): Drop pkg/virtctl/utils

### PR DESCRIPTION
**Pull request by 0xFelix**
### What this PR does

Replace utils.AtomicBool with the functionally euqivalent atomic.Bool from the
stdlib in imageupload unit tests.

Then drop pkg/virtctl/utils because it is no longer used and can be dropped safely.

Before this PR:

pkg/virtctl/utils duplicates functionality found in the stdlib.

After this PR:

pkg/virtctl/utils is dropped.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
Looks to me like that failure could be related :/

/test pull-kubevirt-unit-test-s390x

**Comment by jcanocan** [comment]
It looks good to me as well. But yeah, the failing lane could be related. I'm not sure why, everything looks fine.

**Comment by 0xFelix** [comment]
The failure is not related to my changes, at least not directly. The conflicting accesses take place on `kubeClient`.

**Comment by 0xFelix** [comment]
`kubeClient` is accessed in several goroutines without any synchronization.
This test file needs a rewrite to get rid of the conflicting accesses on `kubeClient`. :(

/hold

**Comment by 0xFelix** [comment]
Turns out it is easier done than said this time. Added synchronization of goroutines in https://github.com/kubevirt/kubevirt/pull/13419/commits/0b3674dabaf24baf8b88acced41ed83966c9f110. It suffices to get tests to pass for the time being .

**Comment by jcanocan** [comment]
Well done!
/lgtm

**Comment by alicefr** [comment]
Looks good!
/approve

**Pull request merged**
