### PR TITLE
Update libvirt-go to 7.3.0

### PR DESCRIPTION
**Pull request by maya-r**
We wish to include the following commit:
commit f1cd3791f65b17f0b4aba7dc39716ed7046448c6 (tag: v7.2.0)
Author: Vladik Romanovsky
Date:   Fri Mar 26 19:14:53 2021 -0400

    Update GetJobStats to report an accurate job type

And 7.3.0 is the first version which we can consume including
this commit.

**What this PR does / why we need it**:
kubevirt#5590 updated to 7.0.0 + manually adding this commit, but this gets reverted by `make deps-update`.
Let's update past the commit, and have `make deps-update` do the right thing - this is less error-prone.

Technically the first release containing this commit is 7.2.0, but it cannot be consumed due to a Go module issue.

**Release note**:

```release-note
Update libvirt-go to 7.3.0
```

### CODE REVIEW

**Comment by EdDev** [comment]
How can we use an API of 7.3 when the binary is 7.0? I do not understand.

**Comment by maya-r** [comment]
"the binding are explicitly designed so that they will work seamlessly when built against older versions of the C library" - [from Andrea Bolognani](https://github.com/kubevirt/kubevirt/pull/5590#issuecomment-832866446)

**Comment by maya-r** [comment]
Pushed the wrong commit apparently... those failures are real.

**Comment by EdDev** [comment]
> "the binding are explicitly designed so that they will work seamlessly when built against older versions of the C library" - [from Andrea Bolognani](https://github.com/kubevirt/kubevirt/pull/5590#issuecomment-832866446)

@andreabolognani , can you explain this? A new API may introduce new options, which may not be available on older libs. What am I missing here?

@maya-r , to me it sounds like a source of trouble. If this fix is important, it should be back-ported and not assume this kind of compatibility. One problem for example may be with anyone that takes kubevirt and wants to re-distribute (downstream) and instead of choosing a specific libvirt release with its relevant expected go-binding, they will need to do loops and hoops to accommodate to this stuff.
I do not think it is recommended to play with the versions like this.

**Comment by andreabolognani** [comment]
> > "the binding are explicitly designed so that they will work seamlessly when built against older versions of the C library" - [from Andrea Bolognani](https://github.com/kubevirt/kubevirt/pull/5590#issuecomment-832866446)
> 
> @andreabolognani , can you explain this? A new API may introduce new options, which may not be available on older libs. What am I missing here?

@EdDev If you look at how new features are added to the bindings, for example [libvirt/libvirt-go@4ae0a16](https://gitlab.com/libvirt/libvirt-go/-/commit/4ae0a162e7d2d7ba7c1c96b7c9bb6a2b8da06307), you'll see that the Go wrappers include explicit version checks that result in a failure being reported if the Go bindings have been built against an older version of the C library.

So in our case, all functions that have been introduced since libvirt 7.0.0 will still show up as part of the Go API, but will not be usable, so there should be no risk of accidentally introducing a dependency on a newer version of the C library.

> @maya-r , to me it sounds like a source of trouble. If this fix is important, it should be back-ported and not assume this kind of compatibility. One problem for example may be with anyone that takes kubevirt and wants to re-distribute (downstream) and instead of choosing a specific libvirt release with its relevant expected go-binding, they will need to do loops and hoops to accommodate to this stuff.
> I do not think it is recommended to play with the versions like this.

For the C library, we create maintenance branches such as `v7.0-maint` when a fix is important enough that we feel any downstream would have to independently backport it otherwise; this is generally only limited to serious security fixes. Is something like that supported in the Go ecosystem? Could we create a `v7.0-maint` branch in libvirt-go where the commit you need is backported, and get KubeVirt to pick that branch instead of the v7.0.0 tag?

**Comment by EdDev** [comment]
> @EdDev If you look at how new features are added to the bindings, for example [libvirt/libvirt-go@4ae0a16](https://gitlab.com/libvirt/libvirt-go/-/commit/4ae0a162e7d2d7ba7c1c96b7c9bb6a2b8da06307), you'll see that the Go wrappers include explicit version checks that result in a failure being reported if the Go bindings have been built against an older version of the C library.
> 
> So in our case, all functions that have been introduced since libvirt 7.0.0 will still show up as part of the Go API, but will not be usable, so there should be no risk of accidentally introducing a dependency on a newer version of the C library.

OK, this makes it safe then. Thanks for the explanation!

> > @maya-r , to me it sounds like a source of trouble. If this fix is important, it should be back-ported and not assume this kind of compatibility. One problem for example may be with anyone that takes kubevirt and wants to re-distribute (downstream) and instead of choosing a specific libvirt release with its relevant expected go-binding, they will need to do loops and hoops to accommodate to this stuff.
> > I do not think it is recommended to play with the versions like this.
> 
> For the C library, we create maintenance branches such as `v7.0-maint` when a fix is important enough that we feel any downstream would have to independently backport it otherwise; this is generally only limited to serious security fixes. Is something like that supported in the Go ecosystem? Could we create a `v7.0-maint` branch in libvirt-go where the commit you need is backported, and get KubeVirt to pick that branch instead of the v7.0.0 tag?

I really do not know, maybe this binding is not even replaced by the downstream builder, because it is "go" based.

**Comment by andreabolognani** [comment]
> > @EdDev If you look at how new features are added to the bindings, for example [libvirt/libvirt-go@4ae0a16](https://gitlab.com/libvirt/libvirt-go/-/commit/4ae0a162e7d2d7ba7c1c96b7c9bb6a2b8da06307), you'll see that the Go wrappers include explicit version checks that result in a failure being reported if the Go bindings have been built against an older version of the C library.
> > So in our case, all functions that have been introduced since libvirt 7.0.0 will still show up as part of the Go API, but will not be usable, so there should be no risk of accidentally introducing a dependency on a newer version of the C library.
> 
> OK, this makes it safe then. Thanks for the explanation!

One nuance that I failed to mention is that things like flags are defined unconditionally. Even in that scenario you should be fairly safe, because if you try to use a flag that was introduced in libvirt 7.3.0 while building against libvirt 7.0.0, the behavior that is enabled by that flag of course simply **cannot** be triggered in a library that doesn't know about it... So you will not be able to get to the point where you will consider merging a feature that depends on said behavior.

> > For the C library, we create maintenance branches such as `v7.0-maint` when a fix is important enough that we feel any downstream would have to independently backport it otherwise; this is generally only limited to serious security fixes. Is something like that supported in the Go ecosystem? Could we create a `v7.0-maint` branch in libvirt-go where the commit you need is backported, and get KubeVirt to pick that branch instead of the v7.0.0 tag?
> 
> I really do not know, maybe this binding is not even replaced by the downstream builder, because it is "go" based.

I expect downstreams to possibly bring their own libvirt builds, but leave the vendored version of libvirt-go that comes with KubeVirt alone. Even if they were to replace the libvirt build with a newer one, potentially turning some of the stubs into working Go wrappers, there will be no code in KubeVirt using those APIs...

**Pull request merged**
