### PR TITLE
Fix some typos in API comments

### PR DESCRIPTION
**Pull request by hdurand0710**
Signed-off-by: Helene Durand <helene@kubermatic.com>

**What this PR does / why we need it**:
This PR fixes 2 small typos in the API comments. Why is it needed? If you use this APIs to generate some swagger, and swagger clients and use some codespell to check the spelling, there are 2 spelling errors in the generated client code files.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mfranczy** [comment]
hi @maya-r could you approve the PR?

**Comment by maya-r** [comment]
I don't have approve permission, [this is the list of people who do](https://github.com/kubevirt/kubevirt/blob/main/OWNERS_ALIASES#L4-L16).
cc @enp0s3 @fabiand

**Review by dhiller — COMMENTED** [review]
/approve

Thanks for your work!

**Pull request merged**
