### PR TITLE
Add break in validateEmulatedMachine

### PR DESCRIPTION
**Pull request by yeahdongcn**
Signed-off-by: Xiaodong Ye <yeahdongcn@gmail.com>

**What this PR does / why we need it**:
Add the missing `break` in `validateEmulatedMachine`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
1. Correct several typos
2. Remove unnecessary use of `fmt.Sprintf`

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by vasiliy-ul — COMMENTED** [review]
The code looks good. Could you please update the commit message and mention the refactoring changes? Now it does a bit more than adding just a break.

**Review by xpivarc — COMMENTED** [review]
/approve

**Comment by yeahdongcn** [comment]
> The code looks good. Could you please update the commit message and mention the refactoring changes? Now it does a bit more than adding just a break.

Done. Please see the latest commit, thanks.

**Review by vasiliy-ul — APPROVED** [review]
Thanks!

**Review by vasiliy-ul — APPROVED** [review]

**Comment by yeahdongcn** [comment]
@vasiliy-ul There seems to be something wrong in the tests, my other PR (https://github.com/kubevirt/kubevirt/pull/8422) keeps failing too.

**Comment by vasiliy-ul** [comment]
`pull-kubevirt-goveralls` is not a mandatory job, so it should not block the merge.

**Pull request merged**
