### PR TITLE
Revert "reconcile crd to desired state"

### PR DESCRIPTION
**Pull request by ashleyschuett**
Reverts kubevirt/kubevirt#5310

This change causes CRDs to be updated on every pass since the kubernetes API creates them as "v1" but they are returned as v1beta1 and compared against a v1beta1. v1 has new defaulted fields which makes the `EnsureCustomResourceDefinitionV1Beta1` think that the existing object and the desired object are different. We should wait until https://github.com/kubevirt/kubevirt/pull/5017 is merged to fix this.

### CODE REVIEW

**Comment by EdDev** [comment]
Can we protect against such an issue with a small e2e test/check?

**Comment by ashleyschuett** [comment]
@EdDev we could add an e2e test. Kedar and I have been talking about which resources to have these tests for. The problem I see is that we are going to be reconciling 17 different resource types and adding a tests for each one could increase testing time by at least a minute per test since operator functional tests are ran serially

**Comment by EdDev** [comment]
> @EdDev we could add an e2e test. Kedar and I have been talking about which resources to have these tests for. The problem I see is that we are going to be reconciling 17 different resource types and adding a tests for each one could increase testing time by at least a minute per test since operator functional tests are ran serially

If the logic is generic and not per type, then you can just pick a single resource type as a ref check.

**Pull request merged**
