### PR TITLE
Use the selinux enables k8s-1.17 lane

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Use a 1.17 build with selinux enabled. Let's see what breaks.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jean-edouard** [comment]
/lgtm
Tested this locally, SELinux is enabled and enforced, no denial even after starting a VM.
Thanks!

**Comment by rmohr** [comment]
I see some errors here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3235/pull-kubevirt-e2e-k8s-1.17/1245765888964038656. Right now not too many are failing, and this may be fixed with your PR. We will see.

**Comment by rmohr** [comment]
@jean-edouard @vladikr the kubevirtci PR is merged. This one is updated and should be ready.

**Pull request merged**
