### PR TITLE
[release-0.50] Improve non-root path handling

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
Manual cherry-pick of #8198 and #8268

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
The banncheck commits were omitted because they don't seem to work with this version of Bazel.
Since banncheck is in main and all backports come from there this should be fine.
It also makes this backport less intrusive.

**Release note**:

```release-note
Improve path handling for non-root virt-launcher workloads
```

### CODE REVIEW

**Comment by rthallisey** [comment]
These failures don't have anything to do with this change.  Seem like a flake to me.  What do you think @jean-edouard ?

**Review by dhiller — COMMENTED** [review]
/approve

**Pull request merged**
