### PR TITLE
Nominate ShellyKa13 sig-storage approver

### PR DESCRIPTION
**Pull request by mhenriks**
### What this PR does

It is my honor to nominate @ShellyKa13 to be a sig-storage approver. She has been an active KubeVirt [contributor](https://github.com/kubevirt/kubevirt/pulls?q=is%3Amerged+is%3Apr+author%3AShellyKa13) for over three years and has authored some pretty major features in the storage arena, including:

- [Online VM Snapshots](https://github.com/kubevirt/kubevirt/pull/5382)
- [VM Snapshot Guest Agent Integration](https://github.com/kubevirt/kubevirt/pull/5942)
- [VM Memory Dump](https://github.com/kubevirt/kubevirt/pull/7517)

Not only has @ShellyKa13 displayed the ability to own a feature from idea to implementation, she has proven to be a thorough and thoughtful [reviewer](https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+commenter%3AShellyKa13+is%3Aclosed+-author%3AShellyKa13). Her insights have have been invaluable to me personally and I admire the fact that she's not afraid to tell me (in a nice way) when my commit messages suck (they do). Having @ShellyKa13 on board as a sig-storage approver will be a big win for the project.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by mhenriks** [comment]
cc @alicefr @awels @aglitke @alromeros @arnongilboa

**Comment by alicefr** [comment]
/hold
to let the other chime in

**Comment by arnongilboa** [comment]
Well deserved @ShellyKa13 !
/lgtm

**Comment by alromeros** [comment]
Well deserved Shelly!
The ecosystem team lacks approvers so this is well justified.
/lgtm

**Review by enp0s3 — APPROVED** [review]

**Comment by ShellyKa13** [comment]
Thanks for the vote of confidence :)

**Pull request merged**
