### PR TITLE
Fix CDI related fossa errs by bumping CDI

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
Bumping the non-api CDI dependency (1.40->1.55) gets rid of the FOSSA errs generated by CDI repos,
but we should definitely get rid of this dependency altogether by moving pkg/clone over to the API lib.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
/cc @dhiller 
this removes the failure on CDI but there are still some unlicensed deps

**Review by dhiller — APPROVED** [review]
@akalenyu I think that by removing kubevirt.io/controller-lifecycle-operator-sdk a lot of other dependencies go away, which is a good thing. BTW the FOSSA check succeeds here, so let's try to find others who also approve :)

One thing: Could you update the PR description to properly reflect the goal of this PR.

/cc @xpivarc WDYT about this? (I know that we should get of cdi dep entirely but that's another story)

**Comment by xpivarc** [comment]
@dhiller 
Lets no forget to make this required after merge

**Comment by akalenyu** [comment]
/hold cancel
thanks! updated

> @dhiller
Lets no forget to make this required after merge

Do you mean the fossa lane? because there are still flagged deps in it, this PR just gets rid of the CDI ones

**Comment by dhiller** [comment]
@akalenyu it says those two errors (which are legitimate, since there is no license in each of the repos) come from the cdi dependency.

**Comment by dhiller** [comment]
image

**Comment by akalenyu** [comment]
> image

Weird, we have a fossa lane too so I thought 1.55 is clean from errors

**Comment by dhiller** [comment]
Yeah, not sure why it is so unreliable :frowning_face:

**Comment by dhiller** [comment]
When looking at cdi-api it tells me this:

```
~/Projects/github.com/kubevirt.io/containerized-data-importer-api git#v1.55.2 ?1 ❯ grep 'github.com/dave/' go.sum                                                                                                                                                       github.com/dave/dst v0.26.2/go.mod h1:UMDJuIRPfyUCC78eFuB+SV/WI8oDeyFDvM/JR6NI3IU=
github.com/dave/gopackages v0.0.0-20170318123100-46e7023ec56e/go.mod h1:i00+b/gKdIDIxuLDFob7ustLAVqhsZRk2qVZrArELGQ=
github.com/dave/jennifer v1.2.0/go.mod h1:fIb+770HOpJ2fmN9EPPKOqm1vMGhB+TwXKMZhrIygKg=
github.com/dave/kerr v0.0.0-20170318121727-bc25dd6abe8e/go.mod h1:qZqlPyPvfsDJt+3wHJ1EvSXDuVjFTK0j2p/ca+gtsb8=
github.com/dave/rebecca v0.9.1/go.mod h1:N6XYdMD/OKw3lkF3ywh8Z6wPGuwNFDNtWYEMFWEmXBA=
```

So indeed the FOSSA check seems to not have caught this somehow

**Comment by dhiller** [comment]
> When looking at cdi-api it tells me this:
> 
> ```
> ~/Projects/github.com/kubevirt.io/containerized-data-importer-api git#v1.55.2 ?1 ❯ grep 'github.com/dave/' go.sum                                                                                                                                                       github.com/dave/dst v0.26.2/go.mod h1:UMDJuIRPfyUCC78eFuB+SV/WI8oDeyFDvM/JR6NI3IU=
> github.com/dave/gopackages v0.0.0-20170318123100-46e7023ec56e/go.mod h1:i00+b/gKdIDIxuLDFob7ustLAVqhsZRk2qVZrArELGQ=
> github.com/dave/jennifer v1.2.0/go.mod h1:fIb+770HOpJ2fmN9EPPKOqm1vMGhB+TwXKMZhrIygKg=
> github.com/dave/kerr v0.0.0-20170318121727-bc25dd6abe8e/go.mod h1:qZqlPyPvfsDJt+3wHJ1EvSXDuVjFTK0j2p/ca+gtsb8=
> github.com/dave/rebecca v0.9.1/go.mod h1:N6XYdMD/OKw3lkF3ywh8Z6wPGuwNFDNtWYEMFWEmXBA=
> ```
> 
> So indeed the FOSSA check seems to not have caught this somehow

Oh, wait! This tells me we need a FOSSA check for cdi-api!

**Comment by dhiller** [comment]
> > When looking at cdi-api it tells me this:
> > ```
> > ~/Projects/github.com/kubevirt.io/containerized-data-importer-api git#v1.55.2 ?1 ❯ grep 'github.com/dave/' go.sum                                                                                                                                                       github.com/dave/dst v0.26.2/go.mod h1:UMDJuIRPfyUCC78eFuB+SV/WI8oDeyFDvM/JR6NI3IU=
> > github.com/dave/gopackages v0.0.0-20170318123100-46e7023ec56e/go.mod h1:i00+b/gKdIDIxuLDFob7ustLAVqhsZRk2qVZrArELGQ=
> > github.com/dave/jennifer v1.2.0/go.mod h1:fIb+770HOpJ2fmN9EPPKOqm1vMGhB+TwXKMZhrIygKg=
> > github.com/dave/kerr v0.0.0-20170318121727-bc25dd6abe8e/go.mod h1:qZqlPyPvfsDJt+3wHJ1EvSXDuVjFTK0j2p/ca+gtsb8=
> > github.com/dave/rebecca v0.9.1/go.mod h1:N6XYdMD/OKw3lkF3ywh8Z6wPGuwNFDNtWYEMFWEmXBA=
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So indeed the FOSSA check seems to not have caught this somehow
> 
> Oh, wait! This tells me we need a FOSSA check for cdi-api!

FYI @awels

**Comment by akalenyu** [comment]
> > When looking at cdi-api it tells me this:
> > ```
> > ~/Projects/github.com/kubevirt.io/containerized-data-importer-api git#v1.55.2 ?1 ❯ grep 'github.com/dave/' go.sum                                                                                                                                                       github.com/dave/dst v0.26.2/go.mod h1:UMDJuIRPfyUCC78eFuB+SV/WI8oDeyFDvM/JR6NI3IU=
> > github.com/dave/gopackages v0.0.0-20170318123100-46e7023ec56e/go.mod h1:i00+b/gKdIDIxuLDFob7ustLAVqhsZRk2qVZrArELGQ=
> > github.com/dave/jennifer v1.2.0/go.mod h1:fIb+770HOpJ2fmN9EPPKOqm1vMGhB+TwXKMZhrIygKg=
> > github.com/dave/kerr v0.0.0-20170318121727-bc25dd6abe8e/go.mod h1:qZqlPyPvfsDJt+3wHJ1EvSXDuVjFTK0j2p/ca+gtsb8=
> > github.com/dave/rebecca v0.9.1/go.mod h1:N6XYdMD/OKw3lkF3ywh8Z6wPGuwNFDNtWYEMFWEmXBA=
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So indeed the FOSSA check seems to not have caught this somehow
> 
> Oh, wait! This tells me we need a FOSSA check for cdi-api!

CDI vendors in the API lib

**Comment by dhiller** [comment]
> > > When looking at cdi-api it tells me this:
> > > ```
> > > ~/Projects/github.com/kubevirt.io/containerized-data-importer-api git#v1.55.2 ?1 ❯ grep 'github.com/dave/' go.sum                                                                                                                                                       github.com/dave/dst v0.26.2/go.mod h1:UMDJuIRPfyUCC78eFuB+SV/WI8oDeyFDvM/JR6NI3IU=
> > > github.com/dave/gopackages v0.0.0-20170318123100-46e7023ec56e/go.mod h1:i00+b/gKdIDIxuLDFob7ustLAVqhsZRk2qVZrArELGQ=
> > > github.com/dave/jennifer v1.2.0/go.mod h1:fIb+770HOpJ2fmN9EPPKOqm1vMGhB+TwXKMZhrIygKg=
> > > github.com/dave/kerr v0.0.0-20170318121727-bc25dd6abe8e/go.mod h1:qZqlPyPvfsDJt+3wHJ1EvSXDuVjFTK0j2p/ca+gtsb8=
> > > github.com/dave/rebecca v0.9.1/go.mod h1:N6XYdMD/OKw3lkF3ywh8Z6wPGuwNFDNtWYEMFWEmXBA=
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So indeed the FOSSA check seems to not have caught this somehow
> > 
> > Oh, wait! This tells me we need a FOSSA check for cdi-api!
> 
> The CDI project vendors in the API lib, is that not enough?

Not sure how it works there, but when you are changing API project, a possible should catch those issues right away, while a check inside CDI catches it after changes have been merged to API, no?

**Comment by akalenyu** [comment]
> > > > When looking at cdi-api it tells me this:
> > > > ```
> > > > ~/Projects/github.com/kubevirt.io/containerized-data-importer-api git#v1.55.2 ?1 ❯ grep 'github.com/dave/' go.sum                                                                                                                                                       github.com/dave/dst v0.26.2/go.mod h1:UMDJuIRPfyUCC78eFuB+SV/WI8oDeyFDvM/JR6NI3IU=
> > > > github.com/dave/gopackages v0.0.0-20170318123100-46e7023ec56e/go.mod h1:i00+b/gKdIDIxuLDFob7ustLAVqhsZRk2qVZrArELGQ=
> > > > github.com/dave/jennifer v1.2.0/go.mod h1:fIb+770HOpJ2fmN9EPPKOqm1vMGhB+TwXKMZhrIygKg=
> > > > github.com/dave/kerr v0.0.0-20170318121727-bc25dd6abe8e/go.mod h1:qZqlPyPvfsDJt+3wHJ1EvSXDuVjFTK0j2p/ca+gtsb8=
> > > > github.com/dave/rebecca v0.9.1/go.mod h1:N6XYdMD/OKw3lkF3ywh8Z6wPGuwNFDNtWYEMFWEmXBA=
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > So indeed the FOSSA check seems to not have caught this somehow
> > > 
> > > 
> > > Oh, wait! This tells me we need a FOSSA check for cdi-api!
> > 
> > 
> > The CDI project vendors in the API lib, is that not enough?
> 
> Not sure how it works there, but when you are changing API project, a presubmit should catch those issues right away, while a check inside CDI catches it after changes have been merged to API, no?

Yes but even today's PRs have green fossa so we are getting a true negative over at the CDI lane?

**Pull request merged**
