### PR TITLE
[e2e] Relax prometheus cr operator test

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
Checking if the kubevirt PrometheusRule cr exists, a comparison between the posted Cr and a generated one is done. This comparison is too strict, since some vendors could use a different `RUNBOOK_URL`, causing a failure.
From an operator functionality perspective, it is enough to check that the CR exists and the group contains a set of rules.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by assafad** [comment]
Is this test failing on U/S? If so, can you please share these failures? 
`runbook_url` are now populated based on `RUNBOOK_URL_TEMPLATE` env, so I wonder if the failure is because this env isn't set on the failed test environment, like it was set during installation.

**Review by 0xFelix — APPROVED** [review]
/lgtm

Thanks

**Comment by assafad** [comment]
@xpivarc /@0xFelix /@fossedihelm should we `/cherrypick release-1.0`?

**Pull request merged**
