### PR TITLE
remove optional option from secret secretName

### PR DESCRIPTION
**Pull request by ShellyKa13**
Signed-off-by: Shelly Kagan <skagan@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mhenriks** [comment]
Surprisingly, looks like this param is optional in k8s api as well:

https://github.com/ShellyKa13/kubevirt/blob/fix-secret-name-optional/vendor/k8s.io/api/core/v1/types.go#L1176-L1177

**Comment by ShellyKa13** [comment]
@mhenriks thats true but it seems a mistake too no? how is it possible to have secret source without a name? should we prevent this change in kubevirt if k8s is like that? even if for some reason intentional I dont see why it will be like that in kubevirt. Also from what I looked we check in the vm webhook that the secretName is not empty so shouldn't it not be optional in the first place?

**Comment by xpivarc** [comment]
/hold 
Helping Tide.
The storage lane is currently broken. https://github.com/kubevirt/kubevirt/pull/9135 should fix this.
Feel free to remove the hold once this is merged.

**Pull request merged**
