### PR TITLE
Update Copyright to "the KubeVirt Authors"

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:
The current state of copyright statements in file headers is a mixture of "the KubeVirt Authors" vs. company XYZ. Since the authors, initial creation year and year(s) where the file has changed can be looked up in much more detail by looking at the Git history, let's simplify the lives of all contributors by removing the year entirely and just put "the KubeVirt Authors" into the copyright notice.

For everyone interested in statistics: CNCF generates nice contribution stats for KubeVirt, one example is the [company contributions table](https://kubevirt.devstats.cncf.io/d/5/companies-table?orgId=1), lots more to find there.

References:
* [the KubeVirt license](https://github.com/kubevirt/kubevirt/blob/5fe600a4d3b57623744b25ba0d3923782558ce2b/LICENSE#L190)
* [the Linux Foundation recommendation](https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects) for reference.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
Update Copyright to "the KubeVirt Authors"
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
I like the approach but I am afraid that this will generate a huge number retest cycles to be merged.
How about do it step by step? Maybe using a issue to track the different sections?
An example could be:
- production code
- test code
- other tools code

Just an idea

**Comment by fabiand** [comment]
@dhiller thanks for considering the CNCF stats.

The original template was taken from the license template, and I'm just not sure what legal implications this has.

Daniel, can you please sync with the CNCF (maybe with the help of @aburdenthehand ) to see if this change has a license implication.
Or maybe you did check this already?

Putting this on hold until this point has been clarified

/hold

**Comment by aburdenthehand** [comment]
I have reached out to CNCF for clarification.

**Comment by aburdenthehand** [comment]
CNCF confirmed that this section of the [Linux Foundation recommendation](https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects) applies here:
```
"Don’t change someone else’s copyright notice without their permission

You should not change or remove someone else’s copyright notice unless they have expressly (in writing) permitted you to do so. This includes third parties’ notices in pre-existing code."
```

So before we make any changes on this we need to get written permission from Red Hat, IBM, and NVIDIA (and others if I missed someone in my search). I can start tracking down people to provide said permission if we can't to pursue this. The alternative would be to leave as is and add a recommendation that future work is copyrighted as KubeVirt Authors and we enforce that in our reviews.

**Comment by dhiller** [comment]
> CNCF confirmed that this section of the [Linux Foundation recommendation](https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects) applies here:
> 
> ```
> "Don’t change someone else’s copyright notice without their permission
> 
> You should not change or remove someone else’s copyright notice unless they have expressly (in writing) permitted you to do so. This includes third parties’ notices in pre-existing code."
> ```
> 
> So before we make any changes on this we need to get written permission from Red Hat, IBM, and NVIDIA (and others if I missed someone in my search). I can start tracking down people to provide said permission if we want to pursue this. The alternative would be to leave as is and add a recommendation that future work is copyrighted as KubeVirt Authors and we enforce that in our reviews.

OK, closing this then. Since the feedback was non existing, I assume that people are not interested in their Copyright notice being altered.

**Pull request closed without merging**
