### PR TITLE
Add Deckhouse to the Adopters list

### PR DESCRIPTION
**Pull request by kvaps**
**What this PR does / why we need it**:

This PR adds Deckhouse to the KubeVirt Adopters list.

**List of our contributions**:

- Live migration for bridged pod network [[proposal](https://github.com/kubevirt/community/pull/182)] [[implementation](https://github.com/kubevirt/kubevirt/pull/7768)]
- Macvtap mode for pod networking [[proposal](https://github.com/kubevirt/community/pull/186)] [[implementation](https://github.com/kubevirt/kubevirt/pull/7648)]
- https://github.com/kubevirt/macvtap-cni/pull/59

**Special notes for your reviewer**:

**Release note**:

```release-note
Add Deckhouse to the Adopters list
```

### CODE REVIEW

**Comment by xpivarc** [comment]
/approve
/cc @fabiand 

@kvaps Please sign your commit.

**Review by maiqueb — CHANGES_REQUESTED** [review]
Actually, looking in more detail, do you mind moving your entry next to the other vendors ? 

I think the table is meant to be ordered by user type - first end users, then integrations, finally vendors.

Sorry I only noticed it now.

**Comment by kvaps** [comment]
Sorry, I was pretty sure that it is in alphabetical order

**Review by maiqueb — APPROVED** [review]
> Sorry, I was pretty sure that it is in alphabetical order

All good, no need to apologize. I didn't notice until now ...

**Pull request merged**
