### PR TITLE
fix a typo

### PR DESCRIPTION
**Pull request by Longchuanzheng**
Signed-off-by: zhuanlan <zhuanlan_yewu@cmss.chinamoblie.com>

**What this PR does / why we need it**:
fix a typo, `needsSCSIControler` -> `needsSCSIController`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by acardace** [comment]
Hi @Longchuanzheng, you need to add a release note otherwise the PR cannot be merged, in this case `NONE` is fine.

**Comment by Longchuanzheng** [comment]
Hi @acardace, the pull-kubevirt-fossa test failed for many times and I think /retest can't deal with it. I would appreciate it if you can give me some advice.

**Comment by maya-r** [comment]
/lgtm
it's ok, pull-kubevirt-fossa is not a required lane :)

**Pull request merged**
