### PR TITLE
Add missing skip to migration test

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
Add missing skip to migration test

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by acardace — APPROVED** [review]

**Review by enp0s3 — COMMENTED** [review]
@jean-edouard Hi. Don't we have such check already in the top-level `BeforeEach`? ([link](https://github.com/kubevirt/kubevirt/blob/a164566a8be4841930ae5b2cddee065c764a7efd/tests/migration_test.go#L320))

**Comment by jean-edouard** [comment]
> @jean-edouard Hi. Don't we have such check already in the top-level `BeforeEach`? ([link](https://github.com/kubevirt/kubevirt/blob/a164566a8be4841930ae5b2cddee065c764a7efd/tests/migration_test.go#L320))

Good point! Yes, it does now, since it was moved. Closing.

**Pull request closed without merging**
