### PR TITLE
Stop testing trim with Block DVs

### PR DESCRIPTION
**Pull request by maya-r**
after kubevirt/containerized-data-importer#2001, CDI will always
preallocate such DVs, and so all the test cases for non-preallocated
fail all the time.
Remove also the preallocated test - it's a negative test, and now
we would never get the feature on Block DVs.

Another reason to do this is that these tests did a lot of unusual
things like using rook toolbox, and despite a lot of effort, they
were unstable and quarantined for a long time.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
/approve

Test failures look like flakes when looking at [flakefinder 7d](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-12-20-168h.html) and [flakefinder 4w](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-12-16-672h.html).

Let's see how the next run goes.

**Comment by brybacki** [comment]
Some notes for the  `pull-kubevirt-check-tests-for-flakes`. Looking at the logs, there are 5 VMIs, 4 are running (maybe from previous tests?) 

The VMI status from failed test shows this:
```
"type": "PodScheduled",
"status": "False",
"lastProbeTime": null,
"lastTransitionTime": "2021-12-21T11:39:15Z",
"reason": "Unschedulable",
"message": "0/2 nodes are available: 1 Insufficient memory, 1 node(s) had volume node affinity conflict."```

**Pull request merged**
