### PR TITLE
tests, net, hotplug: Drop reset-after-hotplug test

### PR DESCRIPTION
**Pull request by EdDev**
### What this PR does

The hotplug of bridge binding network interface has been covering a
scenario in which after a successful hotplug, the VM is restarted and
the interfaces are re-examined for existence.

This change drops the 2 tests that cover the described scenario.
It is trivial that once the VM spec has been modified, restarting or
starting (post stopping) a VM is identical to the scenario that does not
involve hotplug at all. I.e. it does not matter why the VM spec changed,
the new created VMI spec is going to be based on the VM spec.

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

Depends on #12018 , please review only the last commit in this PR.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note
```release-note
NONE
```

### CODE REVIEW

**Review by ormergi — APPROVED** [review]

**Comment by EdDev** [comment]
change: Rebase

**Review by orelmisan — APPROVED** [review]
Thank you

**Pull request merged**
