### PR TITLE
pkg, cleanup: Remove unused parameters

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Review by enp0s3 — APPROVED** [review]
Thank you!

**Comment by EdDev** [comment]
change: Rebase

**Comment by qinqon** [comment]
"""
/hold
until emergency CI fixes of #5207 are merged
"""

**Comment by EdDev** [comment]
5207 got merged.
/hold cancel

**Comment by rmohr** [comment]
/lgtm cancel

Cancelling lgtm to stop the retesting. The PR needs a rebase and `make` run. It has an implicit merge conflict (git can't see an issue, but imports are missing):

```
10:14:32: /tmp/cache/bazel/18316b1300bb8985bc913139d5cc6323/sandbox/processwrapper-sandbox/2637/execroot/__main__/pkg/virt-handler/vm.go:1260:47: undefined: domain
```

**Comment by EdDev** [comment]
change: rebase (without the fix)

**Comment by EdDev** [comment]
change: [Fixed](https://github.com/kubevirt/kubevirt/compare/f42536f6d21ac38c5866214f80cb0da2d659dede..598edf1989a156dfb3cbc749d039adedff936186) the implicit merge collision.

**Comment by EdDev** [comment]
> /lgtm cancel
> 
> Cancelling lgtm to stop the retesting. The PR needs a rebase and `make` run. It has an implicit merge conflict (git can't see an issue, but there are compile issues):
> 
> ```
> 10:14:32: /tmp/cache/bazel/18316b1300bb8985bc913139d5cc6323/sandbox/processwrapper-sandbox/2637/execroot/__main__/pkg/virt-handler/vm.go:1260:47: undefined: domain
> ```

Done

**Comment by EdDev** [comment]
Passing locally but not on CI (unit test run) :/

**Comment by rmohr** [comment]
> Passing locally but not on CI (unit test run) :/

I think some are flaky. @vasiliy-ul addresses them right now.

/retest

**Comment by EdDev** [comment]
> > Passing locally but not on CI (unit test run) :/
> 
> I think some are flaky. @vasiliy-ul addresses them right now.

ack, thanks.

**Review by enp0s3 — APPROVED** [review]
/lgtm

**Pull request merged**
