### PR TITLE
We silently supress IO driver.

### PR DESCRIPTION
**Pull request by xpivarc**
Signed-off-by: L. Pivarc <lpivarc@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by danielBelenky** [comment]
@xpivarc can you please provide more details on the issue?

**Comment by xpivarc** [comment]
> @xpivarc can you please provide more details on the issue?

From my added test: 
`Unexpected Warning event received: testvmix5rbrwq9jrp6lsk7fl4xppd4jl584tpl4rw5zfdgxl4stkhl,3a6a3d35-a2d4-4f39-b31e-5a0a384b7b59: server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: native I/O needs either no disk cache or directsync cache mode, QEMU will fallback to aio=threads')"`

**Pull request closed without merging**
