### PR TITLE
Add mhenriks to approvers/reviewers list

### PR DESCRIPTION
**Pull request by davidvossel**
Michael has been making quality contributions to KubeVirt for over a year now. He's also consistently displayed solid judgement when it comes to design and code review feedback. I propose we add him as an approver/reviewer. He is a great asset to the storage community looking to extend KubeVirt and will help offer them guidance on getting code merged.

```release-note
NONE
```

### CODE REVIEW

**Comment by davidvossel** [comment]
/hold
/cc @mhenriks @aglitke 

Since this involves adding a new approver, I'd like to see at least two separate approvers give a lgtm other than me. I'll remove the hold after we feel like this has gained proper visibility.

**Comment by davidvossel** [comment]
/hold cancel

alrighty, we just need an approver to give this an `approve` now

**Comment by mhenriks** [comment]
thanks @davidvossel I am honored!

**Pull request merged**
