### PR TITLE
Remove "Snapshot" Feature Gate

### PR DESCRIPTION
**Pull request by mhenriks**
### What this PR does
Before this PR:

Had to enable "Snapshot" feature gate in order to use "snapshot.kubevirt.io" API group

After this PR:

Feature gate is deleted and snapshot API is enabled by default as the API is now beta:  #11955

Fixes #

https://issues.redhat.com/browse/CNV-41868

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Snapshot feature gate removed and snapshot API group is enabled by default
```

### CODE REVIEW

**Comment by fabiand** [comment]
Are the snapshot and restore APIs already stable?

We can only remove the FG if the APIs are stable.

**Comment by fabiand** [comment]
@EdDev 

The API still beta, thus I'd expect the FG to be still be present.
Only once the API is stable (GA), then we remove the FG, correct?

**Comment by EdDev** [comment]
> @EdDev
> 
> The API still beta, thus I'd expect the FG to be still be present. Only once the API is stable (GA), then we remove the FG, correct?

Yes.
Even K8S is now following this per my understanding, specifically with CRDs in beta [1].
> Usually enabled by default. Beta API groups are [disabled by default](https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/3136-beta-apis-off-by-default).

However, a calculated risk can be taken by maintainers. But it needs to be explicit and reason why they are sure the CRD will reach GA and not dropped.

[1] https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages

**Comment by fabiand** [comment]
Just to reference: https://github.com/kubevirt/community/blob/main/design-proposals/feature-lifecycle.md#release-stage-transition-table

**Comment by mhenriks** [comment]
Ah I thought beta was still enabled by default in k8s, probably because the stuff I care about always seems to fall under the "calculated risk" department.  I am fine with holding off on this for one release per our feature lifecycle.  I think can move snapshot API to v1 at that point.  It's been around for 4+ years and I don't think there is any chance of getting rid of it

**Comment by fabiand** [comment]
I think we are positive about removing the FG, but the way forward would be
to GA the API.

How do you feel about moving the API to become stable?

**Comment by mhenriks** [comment]
@fabiand I just moved the snapshot API from alpha to beta here #11955

Do you think it would make sense to wait at least one release to move to GA?

**Comment by fabiand** [comment]
Well, as you said: The API is in use for a very very very long time. And
maybe we can have the exception on that side, and move define the API to be
stable.

I'd support this exception due to the fact that it's been in use for so
long.
And this would help us here, as we could also remove the FG (Edy will tell
us if it should be removed, or unconditionally enabled)

**Pull request closed without merging**
