### PR TITLE
Add node label to migration metrics

### PR DESCRIPTION
**Pull request by machadovilaca**
### What this PR does
Before this PR:

Infra tests were failing because vmi migration metrics did not include node label

After this PR:

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Add node label to migration metrics
```

### CODE REVIEW

**Comment by xpivarc** [comment]
Why is the test passing up-stream (or is it)? What does the node means for this metric as migration happens between 2 nodes?

**Comment by machadovilaca** [comment]
> Why is the test passing up-stream (or is it)?

Me and @fossedihelm wondered about the same thing. In PR tests, compute-serial runs independently from other tests, and in this lane a migration never occurs, so the metric is never pushed and the validation on it never performed.

> What does the node means for this metric as migration happens between 2 nodes?

Usually, the node label is added by Prometheus and represents the node of the metric source pod, that's why in the previous PR related to this feature I removed it.  Discussing with Federico he suggested that for backward compatibility it maybe was better to leave the test as is and re-add this label

**Comment by fossedihelm** [comment]
For completeness, I think we should improve the `should include VMI infos for a running VM` test https://github.com/kubevirt/kubevirt/blob/9172f9183875d07a6d8356679dca0a3f8e8fa182/tests/infrastructure/prometheus.go#L478 trying to avoid such false positive like this.
Maybe we should be more explicit on which metrics are expected, and not rely on the registered.
Thank you!

**Comment by machadovilaca** [comment]
> For completeness, I think we should improve the `should include VMI infos for a running VM` test
> 
> https://github.com/kubevirt/kubevirt/blob/9172f9183875d07a6d8356679dca0a3f8e8fa182/tests/infrastructure/prometheus.go#L478
> 
> trying to avoid such false positive like this.
> Maybe we should be more explicit on which metrics are expected, and not rely on the registered.
> Thank you!

#13337

**Pull request merged**
