### PR TITLE
[release-0.49] Adjust 3 tests to be compatible with single-replica setups

### PR DESCRIPTION
**Pull request by jean-edouard**
This is a manual cherry-pick of https://github.com/kubevirt/kubevirt/pull/7301

```release-note
NONE
```

### CODE REVIEW

**Comment by xpivarc** [comment]
@jean-edouard I think we have miss-configuration in CI

**Comment by jean-edouard** [comment]
> @jean-edouard I think we have miss-configuration in CI

Looks like it, thanks, won't insist with retests!

**Comment by xpivarc** [comment]
@fossedihelm fyi

**Comment by fossedihelm** [comment]
Thanks, I'm looking on it here https://github.com/kubevirt/kubevirt/pull/7337

**Comment by dhiller** [comment]
/hold

I saw this test lane failing on the same test for five times: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7346/pull-kubevirt-e2e-k8s-1.23-sig-network-0.49/1541708928881004544

We should investigate what is going on here.

**Comment by dhiller** [comment]
Same is true for pull-kubevirt-e2e-k8s-1.22-sig-network

**Pull request closed without merging**
