### PR TITLE
Add label "kubevirt.io/os" to VM spec

### LINKED ISSUE #1403: Label "kubevirt.io/os" in vm templates should be placed at spec.template.metadata.labels
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Label "kubevirt.io/os: fedora27" is currently under `metadata.labels`, after the VM is created, cannot find such label in VM's metadata.labels.

**What you expected to happen**:
Place the label "kubevirt.io/os" at spec.template.metadata.labels, and with such a label in place, the operating system could be able to show on web console.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by gouyang**
Signed-off-by: Guohua Ouyang <gouyang@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1403

**Special notes for your reviewer**:

**Release note**:

```release-note
Support displaying operating system of virtual machine on web console.
```

### CODE REVIEW

**Comment by slintes** [comment]
@gouyang there are no changed files?
And related to the title only: I'm wondering if we want to really ***move*** the label, or to have it at both places...?

**Comment by gouyang** [comment]
@slintes From what I tested in #1403, label `kubevirt.io/os` in `metadata` is disappeared after `oc process`, so I don't know whether it need to be there or not.  If it need to be kept there, I will change the title.

**Comment by slintes** [comment]
interesting that `oc process` removes `metadata.label`. Nevertheless I'd prefer to keep it there, too, but let's see what others think.
LGTM

**Comment by rmohr** [comment]
> @slintes From what I tested in #1403, label `kubevirt.io/os` in `metadata.label` is disappeared after `oc process`

@gouyang do you mean that the vm does not have the label if it is just in `metadata.label` from the template itself? That makes sense. To also have it on the VM, it needs to be added to the metadata of the vm too, like you did.

**Comment by rmohr** [comment]
ci test please

**Comment by gouyang** [comment]
> @gouyang do you mean that the vm does not have the label if it is just in `metadata.label` from the template itself? That makes sense. To also have it on the VM, it needs to be added to the metadata of the vm too, like you did.

Yes, the VM doesn't have that label if it is just in `metadata.label`.

**Pull request merged**
