### PR TITLE
Disable the creation of VMIs that are incompatible with live migration

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
Live migration of VMIs with SRIOV/GPU access is very likely to fail.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vladikr** [comment]
I'm not sure... why do you think it will fail with SRIOV/GPU?

**Comment by stu-gott** [comment]
@vladikr I think the issue here is with dedicated hardware. If a physical device is provided directly to a VM, is it migratable?

**Comment by davidvossel** [comment]
> I'm not sure... why do you think it will fail with SRIOV/GPU?

yeah, this is confusing to me as well. it could fail in some scenarios, but it's unclear what makes it likely to fail. there are situations where it's likely to pass I believe... but it's possible i'm missing something.

**Comment by jean-edouard** [comment]
This PR is obviously not the right thing to do, closing for now.

**Comment by fabiand** [comment]
Could somebody explain the exact details of why this got closed?

**Comment by jean-edouard** [comment]
This got closed because it is unclear which settings are incompatible with live migration, if any.

Even if a VMI uses SRIOV/vGPU, it's probably still migratable to a node that also supports those (and has a similar config...)
Still, it might be difficult to test and even harder to fix potential issues with such migrations, so maybe we do want something like this PR, but it has to be made clear that it's a deliberate design decision and not necessarily a technical limitation.

**Comment by vladikr** [comment]
The main issue here is obviously copying of the hardware state (pure hardware operations that were offloaded to the device) during live migration, which is not possible without the hardware and the hypervisor support (I don't think this exist)
However, other projects don't block as this specifically doesn't seem to pose a high risk. 
I don't know if such an issue exists with GPU.

One other issue with SR-IOV is that we will need to rebind the network to the VF on the destination side.
I think @EdDev is looking into this.

**Pull request closed without merging**
