### PR TITLE
passt,selinux: remove tmpfs mount rule

### PR DESCRIPTION
**Pull request by rhrazdil**
The policy should be installed along with passt
package installation.

Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by xpivarc** [comment]
/hold
This does not seem right to me.

**Comment by rhrazdil** [comment]
We need to have container-selinux version [v2.193.0](https://github.com/containers/container-selinux/releases/tag/v2.193.0) 
which includes the policy needed by passt

**Comment by xpivarc** [comment]
We should be ok now because we are using `container_t`

**Pull request closed without merging**
