### PR TITLE
Fix spelling container -> contains

### PR DESCRIPTION
**Pull request by larsks**
Fix a spelling error I spotted while browsing the API docs.

### CODE REVIEW

**Review by zcahana — CHANGES_REQUESTED** [review]
Hi @larsks and thanks for spotting and correcting this.
Actually, this file gets autogenerated, and the real source for this typo is rather [here](https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/api/core/v1/schema.go) - so that's where the fix should go.

**Comment by iholder-redhat** [comment]
Hey @larsks,

Thanks for catching that! Indeed a mistake needs to be fixed.
`swagger.json` is an auto-generated file, therefore to fix it it's needed to edit the original file that causes it to be generated.

In order to fix this:
* Edit [this line](https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/api/core/v1/schema.go#L238) which affects the generation of the line you've edited
* Execute `make generate` to re-generate `swagger.json` (more info on that on our [getting started](https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md) page)

Please don't hesitate to ask if something isn't clear :+1:

**Comment by iholder-redhat** [comment]
> Hi @larsks and thanks for spotting and correcting this. Actually, this file gets autogenerated, and the real source for this typo is rather [here](https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/api/core/v1/schema.go) - so that's where the fix should go.

Ah sorry, I've missed that..
As @zcahana said :)

**Comment by larsks** [comment]
I've updated the PR as requested. I had to manually modify `staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go`, which was not updated by `make generate`.

**Comment by zcahana** [comment]
Thanks @larsks!

/lgtm
/test all

**Comment by larsks** [comment]
I'm not willing to fight CI over a spelling PR.

**Pull request closed without merging**
