### PR TITLE
slow AlpineWithTestTooling startup

### PR DESCRIPTION
**Pull request by AlonaKaplan**
**What this PR does / why we need it**:
When AlpineWithTestTooling supplied with no user data, it takes the image more than 200s to allow login.
Adding default empty user data to speed up the startup.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by EdDev — APPROVED** [review]

**Comment by EdDev** [comment]
/cc @qinqon
FYI

**Comment by EdDev** [comment]
/hold

@AlonaKaplan , can you confirm there is no degradation from the current state?
I see the tests took 1:45h (compared to 1:15h I think in the past).

**Review by phoracek — APPROVED** [review]
/approve

**Comment by AlonaKaplan** [comment]
> /hold
> 
> @AlonaKaplan , can you confirm there is no degradation from the current state? I see the tests took 1:45h (compared to 1:15h I think in the past).

You can see here that there is no degradation from the current state. The current average time is 1:40-1:50.
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.22-sig-network
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.23-sig-network
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.24-sig-network

**Pull request merged**
