### PR TITLE
KubeVirt DataVolume Integration

### PR DESCRIPTION
**Pull request by davidvossel**
# Overview

This PR implements the design as outlined in this [document](https://docs.google.com/document/d/1hFS7w_z_Y6xkqBTijDZs172o-TxWsvfPT2JLiQIMPPM/edit?usp=sharing).

User-guide PR can be found [here](https://github.com/kubevirt/user-guide/pull/100)

Users define a DataVolume as a VMI VolumeSource. KubeVirt controllers then dynamically create the DataVolume which orchestrates a PVC import (and soon clones as well) during the virtual machine start flow on behalf of the user. This means that with DataVolume integration a user can both define a Virtual Machine and the storage associated with a Virtual Machine in a single step.

The goal of this PR is to introduce the most basic DataVolume integration possible in order for us to begin iterating on the feature. There's a lot of work that still needs to be done on CDI/KubeVirt to improve the stability and usability of this integration in production. This is an initial effort to provide the minimum amount of change to kick that effort off. 

## Examples
**VMI Example:** User defines a VMI with a DataVolume in order to import a file from a http server into a PVC which will be used as a disk.  The DataVolume's and PVC's life-cycle are tied to the VMI object.
```
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
metadata:
  name: vmi-alpine-datavolume
spec:
  domain:
    devices:
      disks:
      - disk:
        name: pvcdisk1
        volumeName: pvcvolume1
    resources:
      requests:
        memory: 64M
  volumes:
  - dataVolume:
    name: pvcvolume1
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        selector:
          matchLabels:
            os: datavolume2
      source:
        http:
          url: http://cdi-http-import-server.kube-system/images/alpine.iso
```

**VM Example**: User defines a VM object with a DataVolume in order to import a file on a http server into a PVC which is consumed as a disk.  The resulting PVC is persistent across multiple starts/stops of the VM. The life-cycle of the DataVolume and corresponding PVC are tied to the VM.

```
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: vm-alpine-datavolume
  name: vm-alpine-datavolume
spec:
  running: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vm: vm-alpine-datavolume
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: pvcdisk1
            volumeName: pvcvolume1
        machine:
          type: ""
        resources:
          requests:
            memory: 64M
      terminationGracePeriodSeconds: 0
      volumes:
        name: pvcvolume1
      - dataVolume:
          pvc:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            selector:
              matchLabels:
                os: datavolume2
          source:
            http:
              url: http://cdi-http-import-server.kube-system/images/alpine.iso
```

## Notable Changes

**VMI controller** now dynamically creates a DataVolume object and waits for that DataVolume object to complete before scheduling the Pod.

**VM Controller** now dynamically creates a DataVolume object and waits for the DataVolume object to complete before scheduling the VMI.  The corresponding VMI does not inherit the DataVolume object, instead the DataVolume object is replaced with the underlying PVC in the VMI when a VM runs. This is because the DataVolume lifecycle is owned by the VM controller instead of the VMI in this case.

**Feature Gate** The DataVolume integration is feature gated by the **kubevirt-config** ConfigMap. When the **feature-gates** key has **DataVolumes** as a value, KubeVirt will allow DataVolume integration. Otherwise, our **ValidatingWebhook** will deny any requests to post a VMI/VM that references a DataVolume. CDI's DataVolume CRD must be present if the DataVolumes feature gate is enabled. 

This feature-gate allows KubeVirt to function with or without CDI being present. By using the feature-gate to enable DataVolume support, the admin is declaring that the environment should have a CDI deployment present that supports the DataVolume object.

**CDI Deployment Manifest** The DataVolume CRD object is supplied by CDI. We now install CDI at deploy time for all -dev deployments. The DataVolume feature gate is enabled for -dev as well, which triggers the DataVolume functional tests to run. At the moment we're using a custom CDI deployment for testing. As CDI stabilizes, we will hopefully soon be using an official release. The CDI work is a parallel effort. 

**Unit Testing:** Both VMI and VM controllers test cases related to DataVolume creation.

**Functional Testing:** The *tests/datavolume_test.go* test cases verify both VMI and VM behavior with DataVolumes using a hostPath pv. Images are served by the new cdi-http-import-server image that's created for the purposes of testing. 

**Vendor Changes** Updates k8s dependencies to 1.10.3. Pulls in a CDI hash that has the latest DataVolume updates as a dependency. 

```release-note
Adds DataVolume integration support for VMI and VM objects.
```

### CODE REVIEW

**Comment by davidvossel** [comment]
This PR is dependent on https://github.com/kubevirt/containerized-data-importer/pull/198. CDI's packages need to be restructured before we can consume them in KubeVirt.

**Comment by davidvossel** [comment]
retest this please

**Comment by davidvossel** [comment]
I no longer consider this a WIP.

**Comment by davidvossel** [comment]
> I think that I would want a DataVolumeTemplate section on the VM directly and let the VM controller the DataVolume + copy the DataVolume reference to the VMI once it creates it. Like on StatefulSets. It works for me that the DataVolume then gets deleted once I delete the VM (not the VMI). 

This is where we're getting hung up. Unlike stateful sets and pods, both the VM and VMI need the ability to dynamically create storage during the launch flow.

This means a DataVolumeTemplate would be a source for both VMs and VMIs. 

* When VMs have a DataVolumeTemplate source, the resulting DataVolume is tied to the VM's lifecycle. Each corresponding VMI created from a VM references that DataVolume.
* When VMIs have a DataVolumeTemplate source, the resulting DataVolume is tied to the VMI's lifecycle.

**Comment by rmohr** [comment]
> This is where we're getting hung up. Unlike stateful sets and pods, both the VM and VMI need the ability to dynamically create storage during the launch flow.

If you would add two volume sources, one called `DataVolumeSource` and `EphemeralDataVolumeSource` it would already be better. Then we could easily distinguish betweeen a DataVolume which survives a VMI and a datavolume which does not.

Having ownership for a DataVolume decided based on the fact if a VMI was created by a VM or directly by the user is a no-go for me. If you add a `DataVolumeTemplate` to a VMI, then the VM can  unambiguously manage the DataVolume. A VMI can use an EphemeralDataVolume.

The above would be acceptable for me. In general I don't like it that much that we let the VMI manage other things than just itself, however I can see that this can solve the boot-image issue which we have because we don't have a clear `spec.containers[x].image` equivalent and we definitely want non-host-storage supported ephemeral volumes too.

For many using either a `registryDisk` or `ephemeral` which wraps a golden PVC may also be sufficient.

**Comment by davidvossel** [comment]
> Having ownership for a DataVolume decided based on the fact if a VMI was created by a VM or directly by the user is a no-go for me. If you add a DataVolumeTemplate to a VM, then the VM can unambiguously manage the DataVolume. and map the template to a DataVolumeSource on the VM. A VMI can use an EphemeralDataVolume directly.

DataVolumeTemplate - only pertains to VM objects, dynamically creates a DataVolume which is owned by the VM object. 

DataVolume - a VolumeSource that references an already created DataVolume

EphemeralDataVolume - a dynamically created DataVolume that only exists for the lifecycle of the VMI?

@rmohr  I'm okay with this. It functionally meets all the functionality I need. Are we in agreement this is a viable the path forward?

**Comment by rmohr** [comment]
> @rmohr I'm okay with this. It functionally meets everything I need. Are we in agreement this is a viable the path forward?

Yes that would work for me too.

**Comment by davidvossel** [comment]
obsoleted by  #1475

**Pull request closed without merging**
