### PR TITLE
guestfs: fix fsgroup for openshift

### PR DESCRIPTION
**Pull request by alicefr**
**What this PR does / why we need it**:

In openshift we are moving to restricted SCC and running with uid != 0.

In the case, we run with SCC strategy RunAsAny for the FSGroup this field isn't automatically set. Without the specification of the fsgroup, Kubernetes doesn't change the ownership of the directory where the PVC is mounted. This causes an unusable PVC when we run with uid != 0 as we don't have the right to write in the directory.

This PR adds a new flag for setting the gid and fsgroup manually. The functional tests are always run with this flag to avoid permission issues with the PVC.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Add group flag for setting the gid and fsgroup in guestfs
```

### CODE REVIEW

**Comment by alicefr** [comment]
fyi @akalenyu @xpivarc 
I still need to implement the functional test but at least I'd like to have your feedback on the idea

**Comment by xpivarc** [comment]
>Virt-launcher pods don't encounter this issue because they always run with the [fsGroup](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/services/template.go#L642) set.

Actually only with hugepages. The trick we have for virt-launcher is hidden in virt-handler.

**Comment by alicefr** [comment]
> > Virt-launcher pods don't encounter this issue because they always run with the [fsGroup](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/services/template.go#L642) set.
> 
> Actually only with hugepages. The trick we have for virt-launcher is hidden in virt-handler.

@xpivarc do you mean chowning the PVCs?

**Comment by alicefr** [comment]
@xpivarc @akalenyu pushed a new version. This simply adds a new flag `group` for setting the gid and fsgroup. In the tests. we always set this flag. Later, we can implement a better mechanism if we can control how virtctl is used

**Comment by akalenyu** [comment]
/lgtm

Looks good, I think we are covering a lot here without being too much of a compatibility layer:
- OpenShift unprivileged will work without specifying group
- OpenShift elevated & k8s - I think it is reasonable to expect users to know that they have to supply fsgrp; this nuance goes beyond the guestfs pod.

**Comment by akalenyu** [comment]
hmm looks like we have a real failure, what changed?

**Comment by alicefr** [comment]
I might have done something wrong with trebase. I'll have a look to the failure

**Comment by alicefr** [comment]
@xpivarc @mhenriks could you please have a look to this? I think it is ready to be merged

**Review by xpivarc — COMMENTED** [review]
/approve

**Pull request merged**
