### PR TITLE
[release-0.58] RT fixes

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
This PR brings https://github.com/kubevirt/kubevirt/pull/8233 + https://github.com/kubevirt/kubevirt/pull/8750 + https://github.com/kubevirt/kubevirt/pull/8903

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Conflicts were mainly about imports.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by jordigilh** [comment]
@xpivarc can you confirm that all these commits are required?

**Comment by xpivarc** [comment]
/retest

> @xpivarc can you confirm that all these commits are required?
I believe so.

**Comment by vladikr** [comment]
This is related to RHBZ https://bugzilla.redhat.com/show_bug.cgi?id=1992098

/approve

**Review by jean-edouard — APPROVED** [review]
Diffed with the original PRs, found no major difference.
Just this commit that should probably be dropped instead of whatever it does :smile: [`da364b5` (#9174)](https://github.com/kubevirt/kubevirt/pull/9174/commits/da364b57fced9351e5830a7d75148669dea0e4b3)

/hold
Feel free to unhold

**Comment by xpivarc** [comment]
> Diffed with the original PRs, found no major difference. Just this commit that should probably be dropped instead of whatever it does smile [`da364b5` (#9174)](https://github.com/kubevirt/kubevirt/pull/9174/commits/da364b57fced9351e5830a7d75148669dea0e4b3)
> 
> /hold Feel free to unhold

Removed. The test is not present anymore. Thanks for catching it

**Pull request merged**
