### PR TITLE
Update cirros to latest 0.5.2

### PR DESCRIPTION
**Pull request by MaXinjian**
Signed-off-by: Ma Xinjian <maxj.fnst@fujitsu.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Review by oshoval — COMMENTED** [review]
FYI 
when i tried to bump to 0.5.0 there were some issues / flakes

some of them were partially worked or mentioned on
https://github.com/kubevirt/kubevirt/pull/5055/files

Also the community suggests 512Mi for Cirros , and atm we use 128Mi

**Comment by EdDev** [comment]
@MaXinjian  I'm just curios on the reason you want to upgrade cirros. Could you share?

**Comment by MaXinjian** [comment]
> @MaXinjian I'm just curios on the reason you want to upgrade cirros. Could you share?
I found version of cirros_image_aarch64 is 0.5.0. 
At first. I just want to unify the cirros version. Then, I found newest version is 0.5.2. So unify them to 0.5.2.

**Comment by oshoval** [comment]
> > @MaXinjian I'm just curios on the reason you want to upgrade cirros. Could you share?
> > I found version of cirros_image_aarch64 is 0.5.0.
> > At first. I just want to unify the cirros version. Then, I found newest version is 0.5.2. So unify them to 0.5.2.

We currently use 0.4.0 on some of the variants

**Comment by MaXinjian** [comment]
Since this is not a urgent issue. Close this PR temporarily

**Pull request closed without merging**
