### PR TITLE
Test kubevirt/kubevirtci#932 with #6852

### PR DESCRIPTION
**Pull request by ormergi**
**What this PR does / why we need it**:
Test kubevirt/kubevirtci#932 with #6852

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ormergi** [comment]
rabased

**Comment by maiqueb** [comment]
> /test pull-kubevirt-e2e-k8s-1.25-sig-network

the macvtap tests errors are legit; they are being fixed in https://github.com/kubevirt/kubevirt/pull/8899/files#diff-68e627321b80dbc430497076dbbb04d8c04bfa228c8101c1de507364f295ed08

**Comment by ormergi** [comment]
kubevirt/kubevirtci#932 changes have been merged ([#8605  ](https://github.com/kubevirt/kubevirt/pull/8956)).
#6852 should be rebased to have them.

**Pull request closed without merging**
