### PR TITLE
Add initial owners file

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Allows lgtm and approve to work, which in turn will allow automatic
retest.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabiand** [comment]
@aglitke @nellyc @ILpinto do you mind adding reviewers for storage and tests?

@ILpinto i.e. you could add test reviewers for any change in tests/*

Please see the linked documentation for more informations.

**Comment by fabiand** [comment]
@rmohr what about adding an OWNERS_ALIASES file as well - that might make the rules easier.

**Comment by rmohr** [comment]
Definitely. Right now nothing is mandatory and I just add the file to allow automatic retest. We can do follow-up PRs.

**Comment by rmohr** [comment]
> @aglitke @nellyc @ILpinto do you mind adding reviewers for storage and tests?
> 
> @ILpinto i.e. you could add test reviewers for any change in tests/*
> 
> Please see the linked documentation for more informations.

And please go ahead and add or create the owners file as you think you need them yourselves and push a PR. We can review them and merge them then.

**Pull request merged**
