### PR TITLE
net, hotplug: Graduate network hotplug feature to GA

### PR DESCRIPTION
**Pull request by EdDev**
### What this PR does

The network hotplug feature, limited to bridge and SR-IOV bindings interfaces has not changed since v1.1. There has been no rejections from the community so far and no special additions are foreseen at the moment

The network hotplug feature had a Feature Gate which is dropped by marking it as GA in the next Kubevirt release (v1.4).

User guide has been updated here: https://github.com/kubevirt/user-guide/pull/841

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Network hotplug feature is declared as GA.
```

### CODE REVIEW

**Review by orelmisan — COMMENTED** [review]
Thank you @EdDev.
Could you please emphasize that NIC hotplug is applicable only  for secondary networks?

**Comment by EdDev** [comment]
> Thank you @EdDev. Could you please emphasize that NIC hotplug is applicable only for secondary networks?

Why do I need to emphasize this in this change? The documentation of that the feature means has not changed.

**Comment by orelmisan** [comment]
> > Thank you @EdDev. Could you please emphasize that NIC hotplug is applicable only for secondary networks?
> 
> Why do I need to emphasize this in this change? The documentation of that the feature means has not changed.

I meant in the commit message / PR description.
TBH, I don't think our documentation is explicit enough about this limitation, as stated in https://github.com/kubevirt/user-guide/pull/841#pullrequestreview-2365695715.

**Comment by EdDev** [comment]
> I meant in the commit message / PR description.
> TBH, I don't think our documentation is explicit enough about this limitation, as stated in [kubevirt/user-guide#841 (review)](https://github.com/kubevirt/user-guide/pull/841#pullrequestreview-2365695715).

Why do you think it is not supported?
I do not remember we blocked it.

While the primary network cannot be removed from the pod, it can be removed from the VM and surely can be added to it.
I think we never checked some scenarios, but it does not mean they do not work.

**Comment by orelmisan** [comment]
> > I meant in the commit message / PR description.
> > TBH, I don't think our documentation is explicit enough about this limitation, as stated in [kubevirt/user-guide#841 (review)](https://github.com/kubevirt/user-guide/pull/841#pullrequestreview-2365695715).
> 
> Why do you think it is not supported? I do not remember we blocked it.
> 
> While the primary network cannot be removed from the pod, it can be removed from the VM and surely can be added to it. I think we never checked some scenarios, but it does not mean they do not work.

Is it officially supported?
I don't think its tested e2e.

**Comment by EdDev** [comment]
> Is it officially supported?
> I don't think its tested e2e.

Officially what is written is what we know for sure.
What is not written (and tested) is open for interpretation.

In any case, I see no relation to the feature being graduated as is.
If you think we should add coverage and be more accurate in the documentation, please feel free to contribute.

**Review by orelmisan — APPROVED** [review]

**Review by ormergi — APPROVED** [review]
Thank you, LGTM

**Comment by EdDev** [comment]
I do not see how it can be related to the change, but lets just see if it is indeed the same test.
Prev for ref:  https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13059/pull-kubevirt-check-tests-for-flakes/1845491145635794944

/test pull-kubevirt-check-tests-for-flakes

**Comment by EdDev** [comment]
> I do not see how it can be related to the change, but lets just see if it is indeed the same test. Prev for ref: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13059/pull-kubevirt-check-tests-for-flakes/1845491145635794944
> 
> /test pull-kubevirt-check-tests-for-flakes

It passed and I do not detect a potential flake here.

/unhold

**Comment by xpivarc** [comment]
@EdDev The test is flaky without your PR imo. It should not block the PR.

**Pull request merged**
