### PR TITLE
usbdir test: Add missing defer GinkgoRecover

### PR DESCRIPTION
**Pull request by xpivarc**
### What this PR does
ClientConnect is running in goroutine as well.
Therefore we need another defer here.

Fixes #

### Release note
```release-note
NONE
```

### CODE REVIEW

**Review by fossedihelm — APPROVED** [review]

**Comment by vamsikrishna-siddu** [comment]
Looks good to me
/lgtm

**Review by dhiller — APPROVED** [review]
/approve

**Comment by dhiller** [comment]
@nunnatsa maybe a huge ask, but would it be possible to extend your linter to check for such cases?

**Comment by nunnatsa** [comment]
> @nunnatsa maybe a huge ask, but would it be possible to extend your linter to check for such cases?

Hi @dhiller. Sorry, but it is huge, and I'm not sure it's possible, because the linter should understand that the method is about to run in a new go-routine, and that, at=least, very hard to detect. 

However, I think that this is just another reason not to use gomega assertions within functions. I think the function should return a regular golang error, and the test should assert for non-error.

**Comment by dhiller** [comment]
> > @nunnatsa maybe a huge ask, but would it be possible to extend your linter to check for such cases?
> 
> Hi @dhiller. Sorry, but it is huge, and I'm not sure it's possible, because the linter should understand that the method is about to run in a new go-routine, and that is, at least, very very hard to detect.
> 
> However, I think that this is just another reason not to use gomega assertions within functions. I think the function should return a regular golang error, and the test should assert for non-error.

OK, then maybe it is possible to detect usage of gomega assertions within functions?

**Comment by nunnatsa** [comment]
> > > @nunnatsa maybe a huge ask, but would it be possible to extend your linter to check for such cases?
> > 
> > 
> > Hi @dhiller. Sorry, but it is huge, and I'm not sure it's possible, because the linter should understand that the method is about to run in a new go-routine, and that is, at least, very very hard to detect.
> > However, I think that this is just another reason not to use gomega assertions within functions. I think the function should return a regular golang error, and the test should assert for non-error.
> 
> OK, then maybe it is possible to detect usage of gomega assertions within functions? (sorry again for dumb question)

@dhiller we won't be able to run such a limter rulr on kubevirt... There are way too many functions that perform gomega asserts.

**Pull request merged**
