### PR TITLE
update cdi packages and test manifest to 1.21.0

### PR DESCRIPTION
**Pull request by mhenriks**
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

**What this PR does / why we need it**:

Latest and greatest!  Also may fix `AfterSuite` errors in SRIOV lane.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by davidvossel** [comment]
the change looks fine. Why is there a hold here? Are we waiting on something besides CI?

**Comment by mhenriks** [comment]
Now's not the time for this.  Was mostly interested in debugging SRIOV

**Pull request closed without merging**
