### PR TITLE
Ensure block devices are allowed, when the volume has not been attached to VM

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
The cpu manager overwrites changes we make to the devices.list of running pods. If the timing is wrong this happens right before we want to attach the block device to a VM during hotplug. This PR checks if the volume is ready (and thus attached) and if not but the new device file exists, it ensures that devices.list allows the block device.

This will solve the remaining failures on block device tests. This PR also enables them, and removes the serial from the tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
/hold
Putting in hold, so I can re-run the ceph lane a bunch of times to ensure it is working properly. The code is complete.

**Review by davidvossel — COMMENTED** [review]
/approve

**Comment by vladikr** [comment]
Nice fix!
/lgtm

**Comment by awels** [comment]
/hold cancel
6+ runs with no failures in hotplug.

**Comment by rmohr** [comment]
CI tests are not stable enough at the moment. Merging some obviously ready PRs.

**Pull request merged**
