### PR TITLE
fix: change url and label name for "good-first-issue" on CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ffjlabo**
**What this PR does / why we need it**:
It seems that there isn't a label named `good first issue` but named `good-first-issue` on this repo. 
So I fixed the link on CONTRIBUTING.md.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by dankenigsberg** [comment]
/release-note-none

@ffjlabo I believe that you should explicitly say that this has no related release note for the next KubeVirt release.

**Comment by ffjlabo** [comment]
@dankenigsberg Thank you for your advice. I'll try it!

**Comment by dankenigsberg** [comment]
/retest
is a sin.

**Comment by rmohr** [comment]
CI tests are not stable enough at the moment. Merging some obviously ready PRs.

**Pull request merged**
