### PR TITLE
pkg: Remove unused functions and types

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

Remove unused functions and types.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by zcahana — COMMENTED** [review]
Hi @EdDev, I'm definitely up for removing unused code, hopefully before it becomes a maintenance burden. I'm guessing some of these were actually used in the past, and others were just coded for completeness or just for fun. I've made a couple of minor suggestions to some additional unused types we could also remove now, please take a look.

**Review by EdDev — COMMENTED** [review]
Found more things to remove, there are probably many more hiding around.

**Comment by EdDev** [comment]
change: Answered review comments and removed also unused global variables.

**Comment by zcahana** [comment]
Thanks @EdDev!

/lgtm
/approve

**Pull request merged**
