### PR TITLE
Trilio as adopter

### PR DESCRIPTION
**Pull request by StefanKro**
https://github.com/kubevirt/kubevirt/blob/main/ADOPTERS.md

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by xpivarc** [comment]
Hi @StefanKro and thank you for the PR.
Can you please sign the commit?

FYI @fabiand

**Review by StefanKro — COMMENTED** [review]
its signed now

**Comment by StefanKro** [comment]
> Hi @StefanKro and thank you for the PR. Can you please sign the commit?
> 
> FYI @fabiand

please check if its ok now

**Comment by StefanKro** [comment]
I am trying it via cli

**Comment by xpivarc** [comment]
@StefanKro Please follow https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md#contributor-compliance-with-developer-certificate-of-origin-dco and squash your commits. Thanks.

**Comment by StefanKro** [comment]
Hi,

i swapped the toolset so the latest commits
***@***.***

Should have the signature in them
***@***.***

Cheers
Stefan


Von: xpivarc ***@***.***>
Datum: Freitag, 22. Juli 2022 um 13:43
An: kubevirt/kubevirt ***@***.***>
Cc: Stefan Kroll ***@***.***>, Mention ***@***.***>
Betreff: Re: [kubevirt/kubevirt] Trilio as adopter (PR #8151)

@StefanKro<https://github.com/StefanKro> Please follow https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md#contributor-compliance-with-developer-certificate-of-origin-dco and squash your commits. Thanks.

**Pull request closed without merging**
