### PR TITLE
[tests] Remove Job Delete Deprecation warnings

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Get rid of deprecation warnings when we clean up jobs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by xpivarc — APPROVED** [review]

**Comment by rmohr** [comment]
/hold

seems like there is a semantic change also involved with the pod disruption budgets. The operator tests don't like the change.

**Comment by rmohr** [comment]
/unhold

@xpivarc I realized that our PDB operator code is also called in the tests. Deferring therefore the PDB change.

**Review by xpivarc — APPROVED** [review]

**Comment by rmohr** [comment]
/approve

@xpivarc thanks for the review.

**Pull request merged**
