### PR TITLE
stop using  beta.kubernetes.io/arch

### PR DESCRIPTION
**Pull request by pacoxu**
**What this PR does / why we need it**:
See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by pacoxu** [comment]
There is a generated file that I did not change at first. It failed the CI.
@qinqon could you add a `/ok-to-test` label for this PR?

**Comment by pacoxu** [comment]
BTW, the vendor openshift/api is a little old.
https://github.com/openshift/api/pull/886 stopped using the beta label. I'm not sure if that is related.

**Comment by qinqon** [comment]
@pacoxu changes at cluster-up has to be done at github.com/kubevirt/kubevirtci project also the generated file has to be changed at the source.

**Comment by pacoxu** [comment]
> @pacoxu changes at cluster-up has to be done at github.com/kubevirt/kubevirtci project also the generated file has to be changed at the source.

I opened https://github.com/kubevirt/kubevirtci/pull/892.

**Comment by pacoxu** [comment]
/good-first-issue
？

**Pull request closed without merging**
