### PR TITLE
HostDevice code unification

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

Recent work on SR-IOV has revealed that although kubevirt uses very similar functionality to passthrough a host-device from the node to the guest, the code does not reflect the common aspects of it.

This PR focuses on unifying and structuring the hostdevice handling in kubevirt for generic host-devices, GPU/s and SR-IOV.
The change also covers the "legacy" handing of (v)GPU/s using the NVIDIA DP.

As part of the change, the following main points have been handled:
- Generic, GPU & SR-IOV host-devices now share the same env parsing in
the form of address pools.
- The creation of PCI devices are shared between all.
- The creation of domain MDEV based devices are shared between GPU and
host-devices.

In terms of code-tree structure:
- device:
  - hostdevice:
    - generic
    - gpu
    - sriov

The `hostdevice` package contains the common infrastructure.

As part of this change, all host-devices now include an alias which is
composed from a type name prefix (hostdevice, gpu, sriov), followed by
the device name (e.g. `gpu-mydev0`).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Generic host-device, legacy and SR-IOV are covered by e2e tests, however, vGPU (mdev) is not.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by EdDev** [comment]
change: Rebase

**Comment by jean-edouard** [comment]
Thanks, this is quite a huge PR!
I scrolled through the code and it looks good at first glance.
However, automated testing is quite minimal around mdevs for lack of hardware, as already pointed out in the PR description.
So, I'd like to run some manual testing on this before I feel comfortable approving it.
I should have access to an mdev-capable cluster at the end of the week / beginning of next.
Please bear with me!

**Comment by EdDev** [comment]
> Thanks, this is quite a huge PR!
> I scrolled through the code and it looks good at first glance.
> However, automated testing is quite minimal around mdevs for lack of hardware, as already pointed out in the PR description.
> So, I'd like to run some manual testing on this before I feel comfortable approving it.
> I should have access to an mdev-capable cluster at the end of the week / beginning of next.
> Please bear with me!

Hi @jean-edouard , @vladikr. Just checking to see if there is something I can help with on this (like splitting the PR :) )

**Comment by vladikr** [comment]
> > Thanks, this is quite a huge PR!
> > I scrolled through the code and it looks good at first glance.
> > However, automated testing is quite minimal around mdevs for lack of hardware, as already pointed out in the PR description.
> > So, I'd like to run some manual testing on this before I feel comfortable approving it.
> > I should have access to an mdev-capable cluster at the end of the week / beginning of next.
> > Please bear with me!
> 
> Hi @jean-edouard , @vladikr. Just checking to see if there is something I can help with on this (like splitting the PR :) )

@EdDev Thanks for this work! So far I went over most of the changes and everything makes sense to me.
At the first glance, it seemed that we have broken the correlation between the API objects and the allocated devices, but now I see that it's well preserved.
I don't think it makes sense to split the PR.

Please allow me some more time to review the tests and complete the review.

**Comment by vladikr** [comment]
/approve
Thanks @EdDev, really nice PR. Looks good to me.

**Comment by jean-edouard** [comment]
/hold
Sorry this is taking so long but we now have automated mdev testing provided by:
https://github.com/kubevirt/kubevirt/pull/5974
I suggest we wait until that PR is merged so we can ensure this one doesn't break anything mdev-related.
That probably means this PR will have to be manually rebased, but it seems like the best course of action to ensure code stability.

**Comment by EdDev** [comment]
change: Rebase

**Comment by EdDev** [comment]
@jean-edouard , @vladikr , is this ready now?

**Comment by vladikr** [comment]
thanks @EdDev 
/approve
/lgtm

**Pull request merged**
