### PR TITLE
tests, network: Move test-files to the network subpackage

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

Relocate the network e2e tests under a network subpackage.

This should allow:
- Prow to suggest more relevant reviewers from the sig-network.
- Mark sig-network tests easily.
- Better structuring the e2e tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Thanks

**Review by RamLavi — APPROVED** [review]
/lgtm

**Comment by oshoval** [comment]
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5170/pull-kubevirt-check-tests-for-flakes/1368948867701149698
Please take a look

**Comment by EdDev** [comment]
change: Rebase over #5171

**Review by qinqon — APPROVED** [review]

**Comment by oshoval** [comment]
what about those two ? 
we don't plan to move them ?
CNAO runs the 2nd, and the first is network maybe?

tests/probes_test.go
tests/vmi_lifecycle_test.go

If we don't move them but do need to add sig-network than need to think how to do it on #5167

**Comment by EdDev** [comment]
> what about those two ?
> we don't plan to move them ?
> 
>     1. tests/probes_test.go
> 
>     2. tests/vmi_lifecycle_test.go
> 
> 
> CNAO job runs the 2nd, and the first is network maybe?
> 
> If we don't move them but do need to add sig-network then need to think how to do it on #5167

I have not investigated those is great detail, but they are part of a different "story" per my understanding.
Networking is basically essential in most tests, some do special things but their primary objective belongs to a different owner.

If there are tests which are clearly focusing on networking, then it means they belong into the wrong test file and should get extracted individually.

**Comment by oshoval** [comment]
For some reason it looks like that using the FOCUS with this PR, doesn't catch some of the tests,
but doing the same minimal change on clean master does catch them
Lets sync about it if you are interested please, as this PR might cause it if i am not wrong.

**Comment by EdDev** [comment]
change: Under the network folder, we cannot have the names of the files ending with `_test`. This should fix what @oshoval detected about missing running tests.

**Comment by oshoval** [comment]
> change: Under the network folder, we cannot have the names of the files ending with `_test`. This should fix what @oshoval detected about missing running tests.

Nice, thanks, just in order to learn, why we can't name them like that, and how it caused the problem?

**Comment by EdDev** [comment]
> > change: Under the network folder, we cannot have the names of the files ending with `_test`. This should fix what @oshoval detected about missing running tests.
> 
> Nice, thanks, just in order to learn, why we can't name them like that, and how it caused the problem?

Bazel magic causes files that end with `_test` to be placed in a different (test) artifact. This fits when having unit tests together with the production code, but it does not fit when we subpackage tests.

**Review by oshoval — APPROVED** [review]
Thanks

**Review by qinqon — APPROVED** [review]

**Review by RamLavi — APPROVED** [review]
/lgtm

**Review by qinqon — APPROVED** [review]

**Review by oshoval — APPROVED** [review]

**Comment by EdDev** [comment]
> /approve
> /hold feel free to unhold when the ci is more stable.

10 consecutive runs of running these tests on a dedicated job show no flakes.
Proceeding with this change in order to take in also the next PR and make the job periodic.

Regarding the risk: I think it is no different from quarantining some of the tests, as the only change it brings is the potential reordering of running tests.

/hold cancel

**Review by rhrazdil — APPROVED** [review]
/lgtm

**Pull request merged**
