### PR TITLE
[Doc] Add VM instancetype and preference controller revisions to backup graph

### PR DESCRIPTION
**Pull request by ShellyKa13**
### What this PR does
Document VM instancetype and preference controller revisions in the VM backup dependency graph

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by ShellyKa13** [comment]
@0xFelix I added both. under the instancetype and preferences I added the revisionName:
https://github.com/kubevirt/kubevirt/pull/11288/files#diff-cc02601c5ae50587acbc720c9a305c46c9ac9e99aa9322f8a2888bd6af698ce6R68
https://github.com/kubevirt/kubevirt/pull/11288/files#diff-cc02601c5ae50587acbc720c9a305c46c9ac9e99aa9322f8a2888bd6af698ce6R73
And on top of that I added another missing CR for the VMI.

**Comment by 0xFelix** [comment]
Right, I got it wrong. Sorry for the confusion. IIUC we don't require the ControllerRevision of `status.virtualMachineRevisionName` to be backed up though.

**Comment by ShellyKa13** [comment]
@0xFelix yeah I was just working on adding it to the backup and figured it out myself lol thanks I will remove it and keep only the relevant for instancetype and preferenace

**Review by 0xFelix — APPROVED** [review]
Thanks!

/lgtm

**Pull request merged**
