### PR TITLE
Optimization: set termination grace period to zero on VM deletion

### PR DESCRIPTION
**Pull request by iholder101**
**What this PR does / why we need it**:
VMI's `TerminationGracePeriodSeconds` are defined to let the guest have time to gracefully shutdown. This is needed during the VM life-cycle as guest can shutdown and load back up many times.

When the VM is deleted, however, this means we won't ever start the guest again, hence we can forcefully remove it. This optimization is crucial for scaling as it's one of the current bottle-necks when it comes to mass vm deletions.

**Release note**:

```release-note
Optimization: set set termination grace period to zero on VM deletion
```

### CODE REVIEW

**Comment by iholder-redhat** [comment]
@bbenshab

**Comment by iholder-redhat** [comment]
@vladikr can you please take a look?

BTW, I thought about making a functional test for this. Is there a way we can intentionally spawn a process into a guest that would block graceful shutdown? If we do, then maybe we can do so in a vmi with a large graceful period, then delete the vm and expect it do be gone quickly. WDYT?

**Comment by vladikr** [comment]
It does make sense to me. I couldn't find a reason why would we need to require q graceful OS shutdown on VM deletions.
@davidvossel what do you think?

/approve
/hold

**Comment by xpivarc** [comment]
> It does make sense to me. I couldn't find a reason why would we need to require q graceful OS shutdown on VM deletions. @davidvossel what do you think?
> 
> /approve /hold

Deleting the VM doesn't guarantee one would not create another using the same disk. In this case, there could be behavior that one might not be expecting.

**Comment by lyarwood** [comment]
Agree with @xpivarc that this could be awkward if the disks are reusable by future VMIs. What about dropping the [`VIR_DOMAIN_DESTROY_GRACEFUL`](https://libvirt.org/html/libvirt-libvirt-domain.html#VIR_DOMAIN_DESTROY_GRACEFUL) flag from the call to [`virDomainDestroy`](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainDestroy) so libvirtd at least attempts a clean shutdown before killing the domain?

**Comment by vladikr** [comment]
> Agree with @xpivarc that this could be awkward if the disks are reusable by future VMIs. What about dropping the [`VIR_DOMAIN_DESTROY_GRACEFUL`](https://libvirt.org/html/libvirt-libvirt-domain.html#VIR_DOMAIN_DESTROY_GRACEFUL) flag from the call to [`virDomainDestroy`](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainDestroy) so libvirtd at least attempts a clean shutdown before killing the domain?

Afaik, `VIR_DOMAIN_DESTROY_GRACEFUL` allows libvirt to gracefully shut down the domain. It sends SIGTERM to qemu so it will gracefully shutdown without causing any i/o related errors.
So I wouldn't recommend removing it.



> 
> https://github.com/kubevirt/kubevirt/blob/1d0a42d78aa7aa42188a03a2fd9a261004d8627d/pkg/virt-launcher/virtwrap/manager.go#L1600-L1611
> 
> FWIW openstack/nova uses this approach still when deleting:
> 
> https://github.com/openstack/nova/blob/3675dbf7a4f0a8ab0c71b55025b9883581ac021b/nova/virt/libvirt/driver.py#L1434-L1435
> 
> https://github.com/openstack/nova/blob/3675dbf7a4f0a8ab0c71b55025b9883581ac021b/nova/virt/libvirt/guest.py#L171-L173

**Comment by vladikr** [comment]
> > It does make sense to me. I couldn't find a reason why would we need to require q graceful OS shutdown on VM deletions. @davidvossel what do you think?
> > /approve /hold
> 
> Deleting the VM doesn't guarantee one would not create another using the same disk. In this case, there could be behavior that one might not be expecting.

@xpivarc what is your concern with the disks? This shutdown operation still should be graceful in terms of I/O.
Therefore, I would expect the disks to be reusable. This shouldn't lead to disk corruption.

**Comment by lyarwood** [comment]
> > Agree with @xpivarc that this could be awkward if the disks are reusable by future VMIs. What about dropping the [`VIR_DOMAIN_DESTROY_GRACEFUL`](https://libvirt.org/html/libvirt-libvirt-domain.html#VIR_DOMAIN_DESTROY_GRACEFUL) flag from the call to [`virDomainDestroy`](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainDestroy) so libvirtd at least attempts a clean shutdown before killing the domain?
> 
> Afaik, `VIR_DOMAIN_DESTROY_GRACEFUL` allows libvirt to gracefully shut down the domain. It sends SIGTERM to qemu so it will gracefully shutdown without causing any i/o related errors. So I wouldn't recommend removing it.

Yes but as listed in the docs without the flag libvirtd will still try to gracefully shutdown the domain using SIGTERM but will resort to SIGKILL after an unspecified timeout. Honestly it's weird that timeout isn't configurable but that behaviour might be a useful compromise between trying to shutdown cleanly but still in a timely manner.

I should've asked this to begin with but does `terminationGracePeriodSeconds=0` just immediately destroy the pods making my point about the `VIR_DOMAIN_DESTROY_GRACEFUL` flag pointless anyway?

**Comment by davidvossel** [comment]
> It does make sense to me. I couldn't find a reason why would we need to require q graceful OS shutdown on VM deletions.
@davidvossel what do you think?

i'm unsure. The issue here is I don't think we know all the use cases someone might use `TerminationGracePeriodSeconds` for. 

For something simple like ensuring that `windows update` can finish before shutdown, `TerminationGracePeriodSeconds` probably isn't super important when the VM is being entirely deleted. But I have no idea all the different use cases people use this feature for. It's possible people would like to trigger something custom during shutdown, and that it would be surprising if we had different behavior based on whether the VM is deleted or stopped.

>  This optimization is crucial for scaling as it's one of the current bottle-necks when it comes to mass vm deletions.

Can you provide some more details on what you're observing here?  For example, are you encountering some situations where you need to delete a bunch of windows VMs, but they hang around for like an hour due to updates... Or are you talking about the default 30 grace period being the issue?

**Comment by xpivarc** [comment]
@vladikr But do the guest and its apps get a chance to quit gracefully?  I am worried someone is relying on it and we would change this now. Also if scaling is the issue, can we test an explicit way of stopping with grace 0 + delete?

**Comment by iholder101** [comment]
> > This optimization is crucial for scaling as it's one of the current bottle-necks when it comes to mass vm deletions.
> 
> Can you provide some more details on what you're observing here? For example, are you encountering some situations where you need to delete a bunch of windows VMs, but they hang around for like an hour due to updates... Or are you talking about the default 30 grace period being the issue?

The one who actually investigated this is @bbenshab which probably has more information than I do, so he can keep me honest here.

The problematic situation is a mass deletions of VMs with a grace period. The grace period can be the default, or something the user was setting explicitly. It's also possible that different VMs would have different grace periods. Either way, a mass deletion of thousands of VMs would hang until the grace period exceeds. The goal is to drastically speed up such mass deletion operations.

> But I have no idea all the different use cases people use this feature for. It's possible people would like to trigger something custom during shutdown, and that it would be surprising if we had different behavior based on whether the VM is deleted or stopped.

So IIUC the concern is that all of the below are correct:
1. The VM's disk will be re-used by a new VM in the future
2. Custom logic is applied on shutdowns
3. The custom logic is essential in order for the disk to be re-usable by other VMs

Do I understand the concern correctly?

**Comment by iholder101** [comment]
> @vladikr But do the guest and its apps get a chance to quit gracefully? I am worried someone is relying on it and we would change this now. Also if scaling is the issue, can we test an explicit way of stopping with grace 0 + delete?

+1
@bbenshab can you perform such a test? We can test the same workloads, with and without grace preriods, and see the differences. Or maybe you've already done such a test?

**Comment by bbenshab** [comment]
> 
regarding the concerns above:

 I'm not sure what you mean, if the user decides to delete the VM it cannot be reused, if he wants it to be used in the future he needs to just shut it down not delete it, if it got cloned from an imported DV, that DV will not be impacted on deletion.
 
 that being said, let's talk about large scale which is why I brought up this issue, to begin with, the bigger the scale the larger the impact to VM's deletion, I measure the deletion time in relation to the VMI creation time, which is the "heaviest" operation, the following charts show the creation & deletion times for up to 3200 VMs:


vmi_creation_results
vmi_deletion_results

and to sum things up this table shows the data above & expected behavior and time saved once this commit gets pushed:  

#VM's | creation time to deletion time ratio | Expected optimised results | Saved time in seconds
-- | -- | -- | --
100 VMs | 49.43% | 12.36% | 43.00568182
200 VMs | 62.28% | 15.57% | 108.9857651
400 VMs | 68.04% | 17.01% | 236.0960784
800 VMs | 72.78% | 18.20% | 519.6697248
1600 VMs | 61.84% | 15.46% | 925.1823067
3200 VMs | 84.36% | 21.09% | 2917.239327

please let me know if you have any other concerns

**Comment by davidvossel** [comment]
> that being said, let's talk about large scale which is why I brought up this issue, to begin with, the bigger the scale the larger the impact to VM's deletion, I measure the deletion time in relation to the VMI creation time, which is the "heaviest" operation, the following charts show the creation & deletion times for up to 3200 VMs

we have a force stop mechanism today that people can use if they really need to... We could export a force delete one as well i suppose. I'm just hesitant to make the "force" delete behavior (that ignores grace period) the default behavior. We dont know how people depend on the grace period, so i wouldn't want to make any assumptions here.

**Pull request closed without merging**
