### PR TITLE
[release-1.2] Generated client: drop custom wrapper methods of generated ones for vmi struct

### PR DESCRIPTION
**Pull request by fossedihelm**
### What this PR does
This is a manual cherrypick of https://github.com/kubevirt/kubevirt/pull/11495 and https://github.com/kubevirt/kubevirt/pull/11517.

The two PRs cannot be backported separately, since the first without the second one will break the unit tests, while the second cannot be applied without the first one

### Release note

```release-note
NONE
```

/cc @acardace @xpivarc

### CODE REVIEW

**Review by xpivarc — APPROVED** [review]

**Comment by brianmcarey** [comment]
/override pull-kubevirt-e2e-kind-1.27-vgpu-1.2

Lane has been moved to optional due to issues running on upgraded cluster - https://github.com/kubevirt/project-infra/pull/3385

**Pull request merged**
