### PR TITLE
Mark storage tests with owner:sig-storage

### PR DESCRIPTION
**Pull request by brybacki**
Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

**What this PR does / why we need it**:

Mark storage tests with owner:sig-storage. Next all storage tests can be run on a new - separate test lane.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

This PR is open in draft so we can together decide if the test selection is ok. The PR also needs another commit with changes in the test scripts in `automation/` directory, before it's ready to merger.

Infra PR: https://github.com/kubevirt/project-infra/pull/1032
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brybacki** [comment]
@mhenriks @awels What do you think about the ownership of the tests in [kubevirt/tests/storage_test.go](https://github.com/kubevirt/kubevirt/blob/77c78c9f9f4b2c1e7809177305d5d3be2bd8c040/tests/storage_test.go). 
Is it storage or maybe more a compute/vm thing?

**Comment by brybacki** [comment]
/test pull-kubevirt-check-tests-for-flakes

error `was ERROR: An error occurred during the fetch of repository 'fedora_sriov_lane':`

**Comment by nunnatsa** [comment]
> /cc @nunnatsa should I change something when this PR gets merged: #5222

It will be easier to manage lanes from the project-infra repository and to merge PRs there, instead of developing in two repos. But this is not mandatory.

**Comment by brybacki** [comment]
/hold cancel
we can merge this without waiting #5222, so we can already have the correct owners for tests and possibility to run in a new lane

**Comment by brybacki** [comment]
Both pull-kubevirt-e2e-k8s-1.19 and pull-kubevirt-e2e-k8s-1.18 lanes failing with this message:
`failed to get image info: failed to invoke qemu-img: exit status 2: 'fatal error: runtime: cannot allocate memory`

**Pull request merged**
