### PR TITLE
Add test for creating and starting RHEL VM from a Template

### PR DESCRIPTION
**Pull request by gszasz**
**What this PR does / why we need it**:
Adds a test covering test cases for creating an RHEL VM from a Template using
an external `oc` command.  This test scenario requires a PV containing
the RHEL image present within the test cluster.

We need this PR to be able to test if an operator is able to create and start RHEL VMs from a template.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by gszasz** [comment]
@rmohr I have implemented the requested changes.

**Comment by gszasz** [comment]
@stu-gott @rmohr @cynepco3hahue I have fixed all the issues that were previously causing 2 tests to fail in the STDCI environment. I also rebased my changes on top of the `master` branch and I have resolved all merge conflicts that were introduced in the meantime. The PR is ready to be merged.

**Comment by cynepco3hahue** [comment]
@gszasz Let waits for CI and if will not have related to the PR failures I will merge it.

**Comment by gszasz** [comment]
@cynepco3hahue It seems that we do not have any related failures.

**Comment by fabiand** [comment]
WOOT! :)

**Pull request merged**
