### PR TITLE
Doc to enable feature gate in dev cluster and correct path

### PR DESCRIPTION
**Pull request by dharmit**
**What this PR does / why we need it**:
This PR makes the following documentation changes:
1. Steps to enable feature gate(s) for dev cluster (I couldn't find this in existing docs)
2. Correct the path for trying sidecar hook in the examples.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes - N/A

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by iholder101 — COMMENTED** [review]
Thanks a lot for your contribution @dharmit!

Documenting our environment variables properly is very important. Feel free to contribute more similar PRs!

/approve

**Comment by iholder101** [comment]
> > Documenting our environment variables properly is very important.
> 
> +1. I am working on something related to Sidecar and found it super painful to have to edit the kubevirt resource after every `make cluster-sync` to enable the feature.
> 
> Btw, can you help with an `/ok-to-test` as well? Thanks for reviewing! :)

Your changes are appreciated, please feel free to contribute similar PRs :smiley: 
Thanks a lot!

/ok-to-test
/lgtm

**Comment by dharmit** [comment]
> Your changes are appreciated, please feel free to contribute similar PRs.

Thank you, @iholder101 ! :) 

I'll definitely keep them coming as and when I come across something that could use a doc update.

**Pull request merged**
